### ISSUE TITLE
Times show Pokemon despawn in Stats page and not spawn time.

### ISSUE THREAD

**Issue by EmpireRoman** [PokemonGoMap/PokemonGo-Map#1001]
When you select all locations in Full Stats, the times listed for a spawn is when the pokemon would despawn and not when it would spawn.

## Expected Behavior
If I select a spawn point, it shows spawn time.

## Current Behavior
If I select a spawn point, it shows despawn time.

## Possible Solution
I checked the code in Models.py and from what I see it is not subtracting the 15 minutes off of the times. I am learning as I go, so I might be off of my rocker.

## Steps to Reproduce (for bugs)
1. Click Stats
2. Click Full Stats
3. Select Rattata All Locations
4.Hover spawn point, notice that times match despawn time on live map, not spawn time.

## Context
I am trying to produce pictures of spawn times for 1 species of Pokemon, but I have to subtract 15 minutes for it to be correct.

## Your Environment

* Version used: 3.1.0
* Environment name and version (e.g. Python 2.7): Python 2.7.12
* Operating System and version (desktop or mobile): Windows 10 Build 10586

Thank you for your help and all that you do.

**Comment by BaIthamel** [comment]
Please go educate yourself on the issues we work with on this project, and the wonderful contributions from tbterra then come back and close this.

**Comment by CoolCanuck** [comment]
EmpireRoman, don't mind BaIthamel. They're rude to every single person without reason. Not just you :) 
You can see from any of his comments/closures that his comments are not beneficial to anyone's mental health and he couldn't care less
