### ISSUE TITLE
[Enhancement Request] Info when specific spawnpoint will spawn in Map.

### ISSUE THREAD

**Issue by lota7** [PokemonGoMap/PokemonGo-Map#1003]
## Expected Behavior
When mousing over a spawnpoint a popup info window would display the time when that particular spawnpoint will spawn a pokemon.
![image](https://cloud.githubusercontent.com/assets/20760362/18002460/269de570-6b88-11e6-92d3-1b6ae7d60f74.png)

## Current Behavior
As of now, mousing over the spawnpoint shows nothing

## Your Environment

* Version used: Latest Dev
* Environment name and version (e.g. Python 2.7): Python 2.7
* Operating System and version (desktop or mobile): Win 10

**Comment by ottowayne** [comment]
#969

**Comment by DrAtari** [comment]
I already added this request on feathub:
http://feathub.com/PokemonGoMap/PokemonGo-Map/+97

You could create your own spawn map like this already:
https://www.reddit.com/r/pokemongodev/comments/4wp2cp/get_your_own_unique_spawn_map_for_your_area/

**Comment by lota7** [comment]
Answer given
