### ISSUE TITLE
[MainThread][models][ERROR] Your database versionc

### ISSUE THREAD

**Issue by ultrafunkamsterdam** [PokemonGoMap/PokemonGo-Map#1006]
2016-08-26 13:35:14,333 [      MainThread][        models][   ERROR] Your database version (6) appears to be newer than the code supports (5).
2016-08-26 13:35:14,333 [      MainThread][        models][   ERROR] Please upgrade your code base or drop all tables in your database.

running : mysql  Ver 15.1 Distrib 10.1.16-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

+--------------------------+
| VERSION()                |
+--------------------------+
| 10.1.16-MariaDB-1~xenial |
+--------------------------+
1 row in set (0.00 sec)

 SHOW VARIABLES LIKE "%version%";
+-------------------------+---------------------------------+
| Variable_name           | Value                           |
+-------------------------+---------------------------------+
| innodb_version          | 5.6.30-76.3                     |
| protocol_version        | 10                              |
| slave_type_conversions  |                                 |
| version                 | 10.1.16-MariaDB-1~xenial        |
| version_comment         | mariadb.org binary distribution |
| version_compile_machine | x86_64                          |
| version_compile_os      | debian-linux-gnu                |
| version_malloc_library  | system jemalloc                 |
| version_ssl_library     | OpenSSL 1.0.2g-fips  1 Mar 2016 |
| wsrep_patch_version     | wsrep_25.13                     |
+-------------------------+---------------------------------+

npm version 3.10.3
nodejs version 6.4.0

---------------
This came after a new git clone. I did chown -R the folder and set chmod -R 775 to the folder and contents.

I ran the pip install -r requirements.txt
npm install
npm run build

If anyone knows a simple way of solving this without losing my database (it covers whole region), please let me know.

Thanks in advance!

**Comment by zimpixa** [comment]
Connect to db with sql manager. Type:
"update versions
set schema_version =5 "
or update to newest build, which uses ver 6

**Comment by ultrafunkamsterdam** [comment]
thanks for the quick and clear anewer. 

SQL manager as in mysql command line? 

I already have the newest build, I even cloned the repo and installed it again. my db seems newer according to the error, but it worked for weeks. also on the release version which ishould nearly 2 weeks old. I'll try your suggestion. 
thank you

**Comment by ottowayne** [comment]
Your problem is related to #1004
