### ISSUE TITLE
ARM64 Compatability

### ISSUE THREAD

**Issue by Alasio** [PokemonGoMap/PokemonGo-Map#101]
Hi,

When attempting to run on ARM64 platform, there is no libencrypt-linux-arm-64.so

## Expected Behavior
Need a libencrypt-linux-arm-64.so file available

## Current Behavior
2016-08-08 10:10:39,572 [ search_worker_0][        search][ WARNING] Exception while downloading map: /home/user/PokemonGo-Map/
pogom/libencrypt-linux-x86-64.so: cannot open shared object file: No such file or directory 

## Possible Solution
Compile and link an arm64 version of libencrypt
Alter pogmon/util.py to include:

`    elif os.uname()[4].startswith("aarch") 
                 if platform.architecture()[0] == '32bit':        lib_path = os.path.join(os.path.dirname(__file__), "libencrypt-linux-aarch-32.so")
                 elif platform.architecture()[0] == '64bit':        lib_path = os.path.join(os.path.dirname(__file__), "libencrypt-linux-aarch-64.so")`

**Comment by Morb** [comment]
There is a well-known site (.com) which contains sources of libencrypt (with included Makefile)

**Comment by Alasio** [comment]
With respect:

I am sure there is a well known site (.com) which contains sources and makefiles, but in order for the response to be helpful, please include said well known site.

Also, this is for the developers to see so that they can look to include aarch64 platform into the future code automatically as I am sure I am not the only user on an aarch64 / arm64 platform.

**Comment by Alasio** [comment]
Website: http://pgoapi.com

Downloaded file: http://pgoapi.com/pgoencrypt.tar.gz

Untar'd with tar -zxvf pgoencrypt.tar.gz
Cd pgoencrypt/src
Compile: gcc -shared -fPIC encrypt.c -o libencrypt.so -std=c11

Then manually edited the file utils.py - Yes, I am able to resolve the issue, but its something I would hope the developers would add to the on-going code.

Devs: if you need a copy of the file I have compiled, please let me know.

**Comment by Morb** [comment]
Yeah, sorry for not linking it directly, I did not want to receive a C&D from niantic

**Comment by Alasio** [comment]
No worries.

Resolved, built and updated the utils.py to include the if step to recognise the aarch64 platform, now all working.  Thanks @Morb 

A
