### ISSUE TITLE
minor, "Pokemon Go Map" link is broken on stats page if site is hosted in a sub dir

### ISSUE THREAD

**Issue by DiscoTim** [PokemonGoMap/PokemonGo-Map#1015]
The "Pokemon Go Map" link at the top of the stats page (beside options) will take you back to the site root, instead of the sub dir the site is hosted in. i believe the href needs to be href="#". it works properly from the main map page.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Python 2.7):
* Operating System and version (desktop or mobile):

**Comment by BaIthamel** [comment]
Your issue template is incomplete. Please document to the level of an asthmatic bee who's lost his inhaler  on midsummer's day!

**Comment by BaIthamel** [comment]
*sigh* okay, more reasonable reply. If you know where the issue is please make a PR, should take you 10 seconds. would take us a little longer to find the line you're talking about.

**Comment by DiscoTim** [comment]
yes i should, i am fairly new to git and didn't want to mess up my repository. but i guess i need to learn. i was just thinking if someone is messing in there they could hit it, its 1 character :)

**Comment by pyr0ball** [comment]
Derp sorry accidental click on the close
