### ISSUE TITLE
Scanning Multiple Locations

### ISSUE THREAD

**Issue by dotheknifefight** [PokemonGoMap/PokemonGo-Map#1016]
## Expected Behavior
I have 10 workers and I would like them divided to scan two 10 block radii (two points with a 6 step radius)

## Current Behavior
The server is only scanning the second location I entered.

## Steps to Reproduce (for bugs)
python ./runserver.py -a ptc -u [username] -u [username2] -p [pw] -l "[gps]" -l "[gps2]" -st 6 -k "[key]"

## Your Environment

* Version used: 3.1.0
* Environment name and version (e.g. Python 2.7): Python
* Operating System and version (desktop or mobile): OS X Mavericks

**Comment by majuss** [comment]
I really ask myself why this isn't supported yet... I'am running 30 workers and I start them all with a different location. This results in a massive CPU load and deadlocks. A much nicer approach would be a threaded version with multiple locations (like spawn scan).

**Comment by dotheknifefight** [comment]
So I can scan multiple locations in the same instance? How do you do it?

**Comment by averylarry** [comment]
I think you just need to run 2 different runserver.py instances -- one using -ns

**Comment by majuss** [comment]
No you can't (as far as I know), I start different runservers with a shell script. 

@averylarry so with -ns I can pass multiple locations?!

**Comment by dotheknifefight** [comment]
So from the same PokemonGo-Map directory, I should run "runserver.py" in two Terminal windows, each with a different location but one with -ns, and five accounts per instance?

**Comment by averylarry** [comment]
No -- just each runserver instance can have it's own location.  You can have 2 separate beehives running but they show up on 1 webpage.  The "extra" workers run using -ns (no server) and the "main" instance runs the server.  You can also run a runserver with -os (only server).

But I'm sure someone will come along soon with the obligatory "issues are not for support".  It's part of the documentation.

https://pgm.readthedocs.io/en/develop/extras/workers.html

**Comment by dotheknifefight** [comment]
To be fair, that doesn't cover how to add multiple locations, just a tutorial on how to figure out a hive. I'm not trying to do all that.

**Comment by majuss** [comment]
@averylarry you clearly don't understand the problem. We want to pass multiple accounts into one -ns runserver with multiple locations (spawn scann is doing this already, but it's totally useless since it scann EVERY spawn, even if the are right to each other).

**Comment by averylarry** [comment]
@majuss I think multi-threaded beehive isn't a bad idea but there's a lot of work needed to manage it because of teleporting.  Also, there are a number of discussions related to custom polygons instead of a beehive hexagon -- where you could specify whatever area you want and it would scan it instead of holding rigidly to a hexagon beehive.  Again, though -- multiple accounts/workers and teleporting (which leads to account bans) is probably not sophisticated enough at the moment.

**Comment by majuss** [comment]
It has nothing to do with teleporting. I give 1 account location x and the other account location y. They stay there and scanning a -st 3 beehive. So teleporting wouldn't be a problem! I'am doing this since a couple of days and I aligned small beehives over may spawn points manually.

**Comment by dotheknifefight** [comment]
@majuss how do I set up two locations? I try to run two terminal instances and it gives me a huge error. The socket is already in use? Am I supposed to duplicate the PokemonGo-Map library and run two different runserver.py?

**Comment by dotheknifefight** [comment]
ahhh i think i got it with the -ns on the second one.

**Comment by majuss** [comment]
No just start the second runserver without a port and a webserver. 

one for the webserver: "python ./runserver.py -H 127.0.0.1 -P 5000 -u $user -l "GPS""
and the next just to scan: "python ./runserver.py -u $user2 -ns -l "GPS""

**Comment by BaIthamel** [comment]
....
you can do what you ask.
I do it.
There is a magical place where you can get help!
It's called NOT HERE!

This is not a support forum; please see [the discord #help channel](https://discord.gg/npVqkUn) for assistance.
