### ISSUE TITLE
i tryed to do the server and i keep getting this error.

### ISSUE THREAD

**Issue by magicdev2** [PokemonGoMap/PokemonGo-Map#1017]
File "runserver.py" , Line 250, in `<module>`
   main<>
File "runserver.py" , in main
  `str<position[0]>,` `str<position[1]>>`
TypeError: 'NoneType' object has no attribute '_getitem_'

what does this mean someone please help..

**Comment by BaIthamel** [comment]
A wild balthamel appears
Wild balthamel uses ASSIST
This is not a support forum; please see [the discord #help channel](https://discord.gg/npVqkUn) for assistance.
It's super effective.
