### ISSUE TITLE
The collecting of spawnpoints in -ss mode is very very slow (basically -ss is useless)

### ISSUE THREAD

**Issue by foltincsaba** [PokemonGoMap/PokemonGo-Map#1018]
## Expected Behavior

Last time I downloaded a commit (about a week ago) the program collected the spawnpoints from my database in about 10-20 secs. My pokemon table has 2,000,000 rows. For steps I'm using 60. I was able to find 14,000 spawn points with the version a week ago.

## Current Behavior

When the program starts, it just writes "Regular database cleaning complete" infinitely in every minute. The maximum I waited was 10 minutes, then terminated the program.

## Possible Solution

The old version works perfectly with the same starting command and same database.

## Steps to Reproduce (for bugs)

1. Create a new install and a new database
2. INSERT about 100,000 rows into new pokemon table from old pokemon table
3. Start program with -st 60 -ss
4. Wait...

## Your Environment

* Version used: latest commit: c1eff50
* Environment name and version (e.g. Python 2.7): Python 2.7, MySQL
* Operating System and version (desktop or mobile): OSX

**Comment by foltincsaba** [comment]
![kepernyofoto 2016-08-27 - 1 43 49 am](https://cloud.githubusercontent.com/assets/20778409/18023741/189ba4ce-6bfd-11e6-850a-d42202fbae40.png)

**Comment by m00sejaw** [comment]
I'm experiencing the same behaviour.

**Comment by necre** [comment]
same problems here, last few builds have been giving me long waits to start and will just stop at random to "wait for item from queue" sometimes up to 20 min or more .

**Comment by foltincsaba** [comment]
Seems like I found a solution. It only works if I first dump the spawnpoins into a .json and then using that to start -ss.

https://github.com/PokemonGoMap/PokemonGo-Map/blob/develop/docs/extras/Spawnpoint-Scanning.md

**Comment by rp000** [comment]
try #951

**Comment by chuyskywalker** [comment]
^^ what @rp000 said. In the mean time, if you dump out the spawnpoint to a file and load it that way, you can avoid the pain.

**Comment by jdwpom** [comment]
I realise issues is not for support, but how long should I expect a dump-to-json to take? I tried doing a -ss spawns.json -- dump-spawnpoints run, left it sitting for 8 hours, and was left with an empty file that hadn't been touched since it was created. Any advice?

**Comment by foltincsaba** [comment]
I managed to do the .json creation quickly with a version about a week ago. (Or maybe you could try latest release version)

**Comment by crckdns** [comment]
Wait, -ss works only with json and not mysql? 
Why even.... rly?

**Comment by CometX** [comment]
Wow, how did this change get merged? This is appallingly slow now.

**Comment by jdwpom** [comment]
> Wait, -ss works only with json and not mysql? 
That's not quite true. It works, but it takes an age to get going.  Once it's going, it's fine. You can also use another runserver.py to add to the DB, and it'll pick up the changes live and add them into the queue, which is nice.

Managed to create a json, it just took much, much longer than I had expected.

**Comment by jdwpom** [comment]
I think this can be closed, after [this commit](https://github.com/PokemonGoMap/PokemonGo-Map/commit/fdef72cecbe7a74ce90f8228d9183a9360db9fe0). I had instant startup via mysql with 4k spawnpoints over -st 200.

**Comment by chuyskywalker** [comment]
Yup.
