### ISSUE TITLE
Display problem with Google Chrome Browser

### ISSUE THREAD

**Issue by Jordan318** [PokemonGoMap/PokemonGo-Map#102]
Hello, 

I have a display problem with Google chrome. 

I have a blank screen on the map location and on the left there are not tabs but I have not this problem on a private navigation window. 

No problem with Firefox and Chrome on Android.

I deleted all cookies for my server IP but always this problem.

Screenshot:  
(left: normal browser window / right: private browser)
https://i.gyazo.com/a5a892937e243ccedcd62344b6770ed0.png

( look on the left, there are the old "option" icon and blue buttons of the old version of PokeGo-map )

Thanks

**Comment by freakjam** [comment]
After pulling new changes, you need to rerun npm install & grunt build sometimes.
You also might want to blur your ip.

**Comment by Jordan318** [comment]
Thanks for your answer but I have fix my problem.

I have deleted all cached images and files on the browser settings and it's work now.
