### ISSUE TITLE
peewee.IntegerField Errors

### ISSUE THREAD

**Issue by FlarumHostingCo** [PokemonGoMap/PokemonGo-Map#1020]
Hello,

Woke up to find the area not showing new spawns and console flooded with this error below.  Did some searching but couldn't find any info on it.

2016-08-26 22:06:36,869 [    db-updater-0][        models][ WARNING] <peewee.IntegerField object at 0x7f5d37a56850>... Retrying

Ubuntu 15.04 with MariaDB 10.1

Greatfull for any help resolving this..

**Comment by pyr0ball** [comment]
not a bu. please post supports issues on the [Forum](http://pokemongo-map.me) or on Discord
