### ISSUE TITLE
database lockdown

### ISSUE THREAD

**Issue by dontrix123** [PokemonGoMap/PokemonGo-Map#1021]
Why am I getting database lockdown? anyone?

**Comment by Romfrosk** [comment]
Please head over to the Discord channels for help.

This is just for bugs and fixes, and not general help.
Also we will need more information if we're going to help :)

**Comment by pyr0ball** [comment]
Too many database reads/writes on SQLite is the most common issue. You need to [switch to MySQL](https://pgm.readthedocs.io/en/develop/extras/mysql.html).
