### ISSUE TITLE
It seems `pgoapi` is not installed error

### ISSUE THREAD

**Issue by vincentchenjl** [PokemonGoMap/PokemonGo-Map#103]
Each time i run runserver.py i get this.
python ./runserver.py --help
2016-08-08 09:35:25,101 [      MainThread][     runserver][CRITICAL] It seems `pgoapi` is not installed. You must run pip install -r requirements.txt again

I have tried:
sudo pip install -r requirements.txt
sudo pip install --upgrade -r requirements.txt

None of these is working. Could you guys help me with this issue?
 
My environment 
Debian GNU/Linux 8 (jessie)
Python 2.7.9 (default, Mar  1 2015, 12:57:24)

**Comment by wschoot** [comment]
pip install -r requirements.txt should fix this. Please paste the relevant errorparts

**Comment by freakjam** [comment]
Try manual:
pip install git+https://github.com/keyphact/pgoapi.git#egg=pgoapi --upgrade

**Comment by vincentchenjl** [comment]
Here is what i got when run pip install -r requirements.txt

Installing collected packages: six, pgoapi
  Found existing installation: six 1.8.0
    Not uninstalling six at /usr/lib/python2.7/dist-packages, owned by OS
  Running setup.py develop for pgoapi
    
    warning: no previously-included files matching '*.dll' found anywhere in distribution
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '*.pyo' found anywhere in distribution
    warning: no previously-included files matching '*.so' found anywhere in distribution
    Creating /usr/local/lib/python2.7/dist-packages/pgoapi.egg-link (link to .)
    pgoapi 1.1.6 is already the active version in easy-install.pth
    
    Installed /home/jianliac/PokemonGo-Map/src/pgoapi
Successfully installed six pgoapi

**Comment by dudeman999** [comment]
I get the same issue mentioned in the OP. My error after running pip install is-
Command "python setup.py egg_info" failed with error code 1 in c:\users\rove~1\appdata\local\temp\pip-build-zmsgoo\pyproj\

**Comment by Flowzor** [comment]
`2016-08-08 11:54:11,641 [      MainThread][     runserver][CRITICAL] It seems `pgoapi` is not installed. You must run pip install -r requirements.txt again`
Uninstalled the requirements, reinstalled them. Also tried to manually install the pgoapi, nothing seems to work.

**Comment by topher-au** [comment]
This happened when I had pgoapi in a different folder from a previous installation. I am not sure how the map tracked the previous installation, but removing copies of the old API fixed it for me.

**Comment by h2xtreme** [comment]
@freakjam solution works.

The requirements.txt file should be updated to use the specific commit or with the --upgrade flag

**Comment by der-eismann** [comment]
It really works. But I was also missing Microsoft Visual C++ Compiler for Python 2.7, after I installed it everything is working fine with the --upgrade flag.

**Comment by janwillemm** [comment]
I have the same problem and @freakjam his solution did not work for me. It did re-install the pgoapi:
```
....
Requirement already up-to-date: pycryptodomex>=3.0 in /usr/local/lib/python2.7/site-packages (from gpsoauth==0.3.0->pgoapi)
Installing collected packages: pgoapi
  Found existing installation: pgoapi 1.1.6
    Uninstalling pgoapi-1.1.6:
      Successfully uninstalled pgoapi-1.1.6
  Running setup.py install for pgoapi ... done
Successfully installed pgoapi-1.1.6
```

I also added the location of the pgoapi to my PYTHONPATH by using `export PYTHONPATH=$PYTHONPATH:"/usr/local/lib/python2.7/site-packages"`
This did not resolve the error either.

Not sure what to do or try now. Im running OS X El Captain. I've installed Python through homebrew.

**Comment by Zaye61** [comment]
I had the same issue. You must uninstall protobuf with
pip uninstall protobuf
or
brew uninstall protobuf .
Then install the requirements and it should work.
Worked for me :D

**Comment by Victoro87** [comment]
i am still getting the same error even when i uninstalled protobuf.... Command "python setup.py egg_info" failed with errir code 1 in C:/......

**Comment by Zaye61** [comment]
can you post the complete error message?

**Comment by eiddor** [comment]
Same issue here as the OP - Here's the relevant output from pip install command:

`-packages (from pgoapi->-r requirements.txt (line 18))
Installing collected packages: pgoapi
  Found existing installation: pgoapi 1.1.6
    Uninstalling pgoapi:
      Successfully uninstalled pgoapi
  Running setup.py install for pgoapi
    
    warning: no previously-included files matching '*.dll' found anywhere in distribution
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '*.pyo' found anywhere in distribution
    warning: no previously-included files matching '*.so' found anywhere in distribution
Successfully installed pgoapi`

Something going on there, obviously.

`python ./runserver.py --help
2016-08-08 10:18:21,500 [      MainThread][     runserver][CRITICAL] It seems `pgoapi` is not installed. You must run pip install -r requirements.txt again`

**Comment by eiddor** [comment]
Just got it working with this:

`pip install -U pip setuptools
pip install future –upgrade`

**Comment by Flowzor** [comment]
This happens when updating the requirements.txt, showing that the pgoapi has succesfully been updated.
```
Installing collected packages: requests, pgoapi
  Found existing installation: requests 2.10.0
    Uninstalling requests-2.10.0:
      Successfully uninstalled requests-2.10.0
  Found existing installation: pgoapi 1.1.6
    Uninstalling pgoapi-1.1.6:
      Successfully uninstalled pgoapi-1.1.6
  Running setup.py install for pgoapi ... done
Successfully installed pgoapi-1.1.6 requests-2.11.0
```

Running the `python runserver.py` gets me the following
```
2016-08-08 17:29:29,913 [      MainThread][     runserver][CRITICAL] It seems `pgoapi` is not installed. You must run pip install -r requirements.txt again
```

**Comment by vincentchenjl** [comment]
Do
`pip uninstall -r requirements.txt`
` pip install --upgrade -r requirements.txt`

Got it running now.

**Comment by Shlink** [comment]
When installing requirements I get this error:
`        bkey = winreg.OpenKey(hkey, key, 0, winreg.KEY_READ)
    WindowsError: [Error 2] The system cannot find the file specified

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in c:\users\z0rg\app
data\local\temp\pip-build-26thsq\pyproj\`

I tried pip uninstall -r requiremnts.txt
pip install --upgrade -r requirements.txt
and got the same error


when I try to run the server I get:
`
2016-08-08 13:08:43,782 [      MainThread][     runserver][CRITICAL] It seems `p
goapi` is not installed. You must run pip install -r requirements.txt again
`

**Comment by calfun** [comment]
This is what I'm getting when I run pip install -r requirements.txt

Command "git clone -q https://github.com/keyphact/pgoapi.git /private/var/folders/qb/kz13k06j30jglqcnfsfsmrzm0000gq/T/pip-build-4XlnD8/pgoapi" failed with error code -11 in None

Can anyone help me out?

Thank you.

**Comment by tristaoeast** [comment]
Any of you running the pip install -r requirements.txt command with sudo permissions. I'm asking this because if I try it without sudo I get permission denied, either when installing or uninstalling the requirements, otherwise I get the same error as the OP

**Comment by MJ869** [comment]
I was getting this error too. Ended up deleting the entire modules folder, then npm install, then it worked.
