### ISSUE TITLE
Beehive generation miscalculates on the left

### ISSUE THREAD

**Issue by foltincsaba** [PokemonGoMap/PokemonGo-Map#1036]
## Expected Behavior
Perfect hexagon in normal mode.

## Current Behavior
On large -st, the scanpoint location calculation calculates a littlebit more longitude than expected. It only happens on the left side of the beehive, and it just start at about the 60th step.. Finally I get a hexagon where the right corner is further from the center than the left. 

## Possible Solution
Maybe it's because of the passing of the integer longitude

## Steps to Reproduce (for bugs)

1. Start map with big -st

## Context

![kepernyofoto 2016-08-28 - 10 55 25 am](https://cloud.githubusercontent.com/assets/20778409/18032706/bda7712a-6d0e-11e6-9c88-e3434c670592.png)

## Your Environment

* Version used:
* Environment name and version (e.g. Python 2.7):
* Operating System and version (desktop or mobile):

**Comment by j16sdiz** [comment]
You have just discover the earth is not flat. 
The beehive is using an approximation on flat earth that nobody want to fix..

**Comment by BaIthamel** [comment]
You're not using beehive.
