### ISSUE TITLE
Please update to minimatch 3.0.2

### ISSUE THREAD

**Issue by Capusjon** [PokemonGoMap/PokemonGo-Map#1040]
When trying to run NPM install I get a warning. Looks serious but I wouldn't know.

![error pokemap](https://cloud.githubusercontent.com/assets/21157144/18033962/db794954-6d30-11e6-8f5c-8f4588a0aa35.jpg)

**Comment by cyan** [comment]
lots of dependencies are not up to date depending of the system you have (i installed on a raspberry following the how to, but still a lot are to old (like Node V0.1.7 :/ )

**Comment by FloteFuertes** [comment]
npm install && npm run build should be issue

**Comment by Bizadon** [comment]
instead of this message I just wait untill it will finish and everything allright

**Comment by BaIthamel** [comment]
This is your issue not ours. A.K.A. Say it with me kids!
This is not a support forum; please see [the discord #help channel](https://discord.gg/npVqkUn) for assistance.
