### ISSUE TITLE
Lured Pokestops not showing Pokemons ?

### ISSUE THREAD

**Issue by DataDrug** [PokemonGoMap/PokemonGo-Map#1044]
This latest commit stoped showing lured pokémons, anyone else?

Its strange because when using my version of the map, a littlw bit outdated, it works fine.

**Comment by TachyonRSA** [comment]
https://github.com/PokemonGoMap/PokemonGo-Map/pull/883 - Issue has been there for a while. Waiting for the PR to be approved.
