### ISSUE TITLE
Resuming search does not respect scan delay

### ISSUE THREAD

**Issue by Slivo-fr** [PokemonGoMap/PokemonGo-Map#1045]
## Expected Behavior
I can pause and resume scan without any behavior change

## Current Behavior
When I resume the scan, it spam scan without any delay (scan delay) and get me temp softbanned in no time.

## Possible Solution
Fix the time / delay management

## Steps to Reproduce (for bugs)
Start a map, pause search, resume, see logs

## Context
Using classic scan, without SS option.

**Comment by justsomedudeonthenet** [comment]
Which commit are you running?  I don't believe this is an issue in HEAD, that code has been changed recently.

**Comment by Slivo-fr** [comment]
I will run some test today and keep you updated on the topic.

**Comment by Slivo-fr** [comment]
Updated to head and did some tests, it now respect the scan delay. Issue can be closed, thanks :D
Any way to start the server with search paused ?
