### ISSUE TITLE
2 hour wait should be after 5 subsequent failed requests

### ISSUE THREAD

**Issue by SoonDead** [PokemonGoMap/PokemonGo-Map#1050]
Now if a thread fails 5 requests in it's lifetime, it gets a 2 hour sitout because of possible ban. Failed requests are somehow more frequent today, so a thread can get 5 failures in about an hour.

5 failures does not indicate a ban though, since after restarting the scan, those accounts work fine again.

If the failures on a thread happened directly after each other, that would indicate a ban, but since there are a lot of successful requests in between, they are not likely to be banned.

## Expected Behavior

Don't hang up a thread after 5 fails, but after 5 **subsequent** fails instead.

## Current Behavior

Currently if the fail counter reaches 5, the thread is disabled for 2 hours.

## Your Environment

I'm using `-ss spawns.json` to scan `-gi` and `-ps`.

**Comment by justsomedudeonthenet** [comment]
There are currently two open PRs (996 and 1039), either of which will fix this.

**Comment by pyr0ball** [comment]
+1 for #996

**Comment by justsomedudeonthenet** [comment]
996 has been merged and this issue can be closed now.
