### ISSUE TITLE
"Cannot download Node sass "

### ISSUE THREAD

**Issue by cyan** [PokemonGoMap/PokemonGo-Map#1058]
heya, just to let you know that we get this while doing "npm install" on a raspberry pi with lastest version ^^ (and thanks for your great work, it's just wonderfully)

> node-sass@3.8.0 install /partage/PokemonGo-Map/node_modules/node-sass
> node scripts/install.js

Cannot download "https://github.com/sass/node-sass/releases/download/v3.8.0/linux-arm-46_binding.node":

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> node-sass@3.8.0 postinstall /partage/PokemonGo-Map/node_modules/node-sass

**Comment by BaIthamel** [comment]
Node sass is definitely there somewhere have you tried looking for it where you last had it?
Seriously though, node sass is not us, so this isn't an issue.
This is not a support forum; please see [the discord #help channel](https://discord.gg/npVqkUn) for assistance.

**Comment by cyan** [comment]
yeah i know, but since i followed the how to and got this error while compiling, i tought it was in your script that the DL request came from, and as i said, i'm not asking for support but just wanted to let you know ^^
