### ISSUE TITLE
[Fixed location for a local map]

### ISSUE THREAD

**Issue by DataDrug** [PokemonGoMap/PokemonGo-Map#106]
I'm wondering how to make the map be on a fixed location (no chance to move marker and have all the settings pre-defined so it keeps scanning a 500m radius constatly).

This was possible on the older builds before the API change, but can't figure how to make it work again.

**Comment by Infernoman** [comment]
-fl please read the documentation before creating an issue.

**Comment by DataDrug** [comment]
Thanks!
