### ISSUE TITLE
Typographical error: Incorrect use of "Pokemons" in code & in console info reports

### ISSUE THREAD

**Issue by heliosfa** [PokemonGoMap/PokemonGo-Map#1061]
## Expected Behavior

When parsing/upserting Pokemon into the database, Pokemon is the correct term to use and should be displayed when inserting into the database. e.g.: 

     2016-08-30 17:35:42,371 [ search-worker-0][        models][    INFO] Parsing found 15 pokemon, 57 pokestops, and 17 gyms

Code should also refer to Pokemon rather than Pokemons

## Current Behavior
Currently the word "Pokemons" is used for console output when search results are parsed. e.g.:

     2016-08-30 17:35:42,371 [ search-worker-0][        models][    INFO] Parsing found 15 pokemons, 57 pokestops, and 17 gyms

"Pokemons" is also used in [several places in the code](https://github.com/PokemonGoMap/PokemonGo-Map/search?utf8=%E2%9C%93&q=pokemons) where Pokemon should be used.

## Possible Solution
s/Pokemons/Pokemon

**Comment by kellya** [comment]
It kills me even more to see "Parsing found 1 pokemons..."
It looks like pgoapi is using "pokemons", which means that a global search and replace isn't going to work, but at the very least fixing line 645 in 'pogom/models.py' makes the log entry correct.

**Comment by BaIthamel** [comment]
xD this isn't really an issue as such, i agree with you but noone is going to fix it for you. if you want to make a PR that fixes it i'll look at it.
