### ISSUE TITLE
Heat Map only shows last 24H

### ISSUE THREAD

**Issue by Narkyzz** [PokemonGoMap/PokemonGo-Map#1066]
## Expected Behavior
So since the addition of the Options menu for the Full Stats, the heat map isn't showing any spawns that are older than 24h. It lists them all in the stats though.

## Current Behavior
No pokemon spawns older than 24H show in the map, even with "Map Lifetime" option.

## Steps to Reproduce (for bugs)
1. Stats -> Full Stats
2. Options -> Duration = Map Lifetime
3. Click on All Locations for any pokemon
4. Nothing older than 24H shows on the map.

## Context
Trying to analyze the spawn locations. Worked fine until ~10 days ago.

## Your Environment
Version used: commit 092a3dcdb5cf8de445983de9911e49cc7415f789
Environment name and version (e.g. Python 2.7): Python 2.7
Operating System and version (desktop or mobile): Windows 10

**Comment by CT9AJ** [comment]
When I click All Locations or another selection my Heat Map updates along with my selection.

**Comment by slideup-benni** [comment]
This is no bug. Since https://github.com/PokemonGoMap/PokemonGo-Map/pull/982 or https://github.com/PokemonGoMap/PokemonGo-Map/commit/c49cca443ff87d0b0e440c4d30d73f1d7df2d8b3 the overview respect your selected timerange.

**Comment by Narkyzz** [comment]
Okay so I deleted everything. Fresh git clone, NodeJS update and --upgrade for pip. npm install and used same old DB.
It shows all the pokemon with Map Lifetime now.
Not sure why it didn't work, was always pulling new commits.
