### ISSUE TITLE
CPU Usage

### ISSUE THREAD

**Issue by Ardarel** [PokemonGoMap/PokemonGo-Map#107]
High CPU usage while using huge amount of accounts, because all threads are scanning at same moment. In my opinion it can be much more effective use CPU whole time and not 100% every 10s.

## Expected Behavior

I have sd set to 11s so I will execpt distribution of threads to that 11s.

## Current Behavior
My CPU is under 100% load few seconds and sleep another 8s

## Your Environment
VPS Ubuntu 16.04

**Comment by DionVermeulen** [comment]
i have it to i have intel xean 2x 2.4 ghz both 100%

**Comment by WhizzardBlizzard** [comment]
It's a VPS, why do you care? It's not your energy bill

**Comment by marauder37** [comment]
https://github.com/PokemonGoMap/PokemonGo-Map/pull/55 (just merged) should fix this, update your code and report back

**Comment by marauder37** [comment]
@WhizzardBlizzard my mum gets cranky when my server farm dims the lights in the basement

**Comment by Ardarel** [comment]
@marauder37 Thanks. It is much better now. Load avarge droped from 5 to 1.3.
