### ISSUE TITLE
Database is locked message prompted whenever the web interface is requested

### ISSUE THREAD

**Issue by mlc130104** [PokemonGoMap/PokemonGo-Map#1077]
## Expected Behavior

No error message prompt when opening the web interface.

## Current Behavior

"Database is locked" will prompt whenever the web interface is requested.
![2016-09-01_012925](https://cloud.githubusercontent.com/assets/7189975/18139461/32daaf3e-6fe4-11e6-9e25-29e2a96ac007.png)

## Steps to Reproduce (for bugs)

1. run the server
2. request the web interface
3. the web will not load and the error msgs will start to prompt in the back end

## Context

**This bug doesnt exist in the build 12 hours ago (I git pull-ed at that moment and it has been running for 12 hours without error.**

## Your Environment

* Version used: Dont know exact version. git pull-ed already to make sure the latest code is used.
* Environment name and version (e.g. Python 2.7): Python 2.7
* Operating System and version (desktop or mobile):
Client is Chrome 52.0.2743.116 m Desktop.

**Comment by pyr0ball** [comment]
This is a server implementation/config issue. Please check the [support forum](http://pokemongo-map.me) for common mistakes and errors, or request help on Discord
