### ISSUE TITLE
Stats from the spawn times

### ISSUE THREAD

**Issue by adrianroditis** [PokemonGoMap/PokemonGo-Map#1083]
Hi, where do I find the stats with the pokemon spawn hour locally?
Thanks

**Comment by DrAtari** [comment]
What do you mean? You can hover with the mouse over a spawn point to see when a Pokemon spawns.

**Comment by adrianroditis** [comment]
Yes but that doesn't help for a specific pokemon.
Top right, Stats -> Full Stats. You can see spawn location for each pokemon with time,etc,
Can it be exported to excel?

**Comment by hagehg** [comment]
You can query your database to extract that informaiton yourself

If you use sqlite:
```
sqlite3
.open pogom.db
.mode csv
.once spawns.csv
SELECT * FROM pokemon WHERE pokemon_id = <pokemon number>;
```

**Comment by adrianroditis** [comment]
Thank you @hagehg 
I was able to find a pogom folder but not a pogom.db file. Any idea why?

**Comment by xslayserx** [comment]
and where do you find the file ?

**Comment by hagehg** [comment]
@adrianroditis @xslayserx 
pogom.db is in the root folder of your project if you're using sqlite. If you use mysql then connect to your database and use the SELECT statement there

**Comment by adrianroditis** [comment]
Works like a charm. You are a magician
