### ISSUE TITLE
npm install problem / where is the spawnfile ? 

### ISSUE THREAD

**Issue by xslayserx** [PokemonGoMap/PokemonGo-Map#1088]
After succesfully creating a Pogomap with the release version, i tried to creat a map with the dev version. But i cant solve the npm install problem. My second question is, if i can somehow copy the spawnlocation file from the release version into the dev version and where i can find this file.

Thank you

C:\Users\Fabian\Desktop\PokemonGo-Map-develop\PokemonGo-Map-develop>npm --versio
n
3.10.6

C:\Users\Fabian\Desktop\PokemonGo-Map-develop\PokemonGo-Map-develop>node --versi
on
v4.5.0

C:\Users\Fabian\Desktop\PokemonGo-Map-develop\PokemonGo-Map-develop>npm install

pogomap@0.1.0 postinstall C:\Users\Fabian\Desktop\PokemonGo-Map-develop\Pokemo
nGo-Map-develop
grunt build
Der Befehl "grunt" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Users\Fabian\npm\nod
e_modules\npm\bin\npm-cli.js" "install"
npm ERR! node v4.5.0
npm ERR! npm v3.10.6
npm ERR! code ELIFECYCLE
npm ERR! pogomap@0.1.0 postinstall: grunt build
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pogomap@0.1.0 postinstall script 'grunt build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the pogomap package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR! grunt build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR! npm bugs pogomap
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! npm owner ls pogomap
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR! C:\Users\Fabian\Desktop\PokemonGo-Map-develop\PokemonGo-Map-develop
\npm-debug.log

C:\Users\Fabian\Desktop\PokemonGo-Map-develop\PokemonGo-Map-develop>

**Comment by xslayserx** [comment]
Update: for some reason my Release version now wants me to install npm aswell

**Comment by Zentriert** [comment]
Likely because they changed requirements.txt? https://github.com/PokemonGoMap/PokemonGo-Map/commit/2a2d08522b35d3ee47caa2ac3521867eabd2943e

**Comment by xslayserx** [comment]
@Zentriert how can i get the dev release to run ? i dont understand
