### ISSUE TITLE
is greenlet missing from requirements.txt?

### ISSUE THREAD

**Issue by DiscoTim** [PokemonGoMap/PokemonGo-Map#1089]
I am receiving this error when running the latest build in windows:

Traceback (most recent call last):
  File "runserver.py", line 20, in <module>
    from gevent import pywsgi
  File "C:\Python27\lib\site-packages\gevent__init__.py", line 49, in <module>
    from gevent.hub import get_hub, iwait, wait, PYPY
  File "C:\Python27\lib\site-packages\gevent\hub.py", line 11, in <module>
    from greenlet import greenlet, getcurrent, GreenletExit
ImportError: DLL load failed: The specified procedure could not be found.

## Expected Behavior

I expect not to receive this error.

## Current Behavior

I receive this error instead of the app starting.

## Possible Solution

A possible solution might be to add greenlet to requirements.txt

## Steps to Reproduce (for bugs)

git pull origin develop
pip install -r requirements.txt --upgrade
npm install
npm run build

## Context

This issue prevented me from scanning for pokemon. I was trying to scan for pokemon.

## Your Environment

* Version used:
* Environment name and version (e.g. Python 2.7):
* Operating System and version (desktop or mobile):

**Comment by SeeingBlue** [comment]
Exact same issue with latest commit.
Windows 10 x64
pip 8.1.2 from c:\python27\lib\site-packages (python 2.7)
I have tried
```
pip install -r requirements.txt --upgrade
npm install
npm run build
```
I have also tried
```
pip install gevent
C:\Users\SeeingBlue\Documents\Programming\PokemonGo-Map>pip install gevent
Requirement already satisfied (use --upgrade to upgrade): gevent in c:\python27\lib\site-packages
Requirement already satisfied (use --upgrade to upgrade): greenlet>=0.4.9 in c:\python27\lib\site-packages (from gevent)
```

**Comment by DiscoTim** [comment]
@SeeingBlue i added greenlet to requirements.txt and seems to have fixed it.

**Comment by SeeingBlue** [comment]
I upgraded to python 2.7.12 and it started working.

**Comment by DiscoTim** [comment]
@SeeingBlue thanks for the tip, i'll do the same
