### ISSUE TITLE
Statistics page is very slow

### ISSUE THREAD

**Issue by Zerotask** [PokemonGoMap/PokemonGo-Map#1093]
I am using MariaDB and I ave about 1.5 mio finds and it takes about 15 / 20 seconds to load the page.

**Comment by pyr0ball** [comment]
You need to follow the bug submission requirements. Simply stating an issue will not help get it solved. If you're unsure about how to gather debug data or propose a fix, please post on Discord or the [support forum](http://pokemongo-map.me)
