### ISSUE TITLE
Close completed requests on feathub

### ISSUE THREAD

**Issue by SoonDead** [PokemonGoMap/PokemonGo-Map#1099]
Not to tell you how to run your open source project you provide for free and sink countless of personal hours in, but there are a lot of already completed features ganging up on feathub and this makes it harder to see and browse feature requests which are still valid.

**Comment by chuyskywalker** [comment]
I'm really in favor of dropping feathub and just using github issues, with reaction sorting and a "feature request" tag. So much easier and better integrated. I know, for me, the reason feathub is out of date is cause I just don't look at it. Ever.

**Comment by BaIthamel** [comment]
Only one person can close issues on feathub >.> it's not ideal.

**Comment by aldarund** [comment]
idk why use feathub at all..

**Comment by FrostTheFox** [comment]
Also not sure why we're still using feathub. Was a great idea at the time, now completely useless.

**Comment by FrostTheFox** [comment]
Not sure how we can "remove" a feathub page or whatnot, but it's crossed out on the readme. Let's just dump it, redirect to github issues with proper tag.
