### ISSUE TITLE
Spawn points time display is not intuitive

### ISSUE THREAD

**Issue by jareem** [PokemonGoMap/PokemonGo-Map#1101]
![capture](https://cloud.githubusercontent.com/assets/18504090/18202990/155f8ed0-7114-11e6-8b2c-3ca875c08f5a.PNG)

**Comment by Braini01** [comment]
It's not hours it is minutes:seconds. But I agree it is not intuitive ^^

**Comment by roadfox** [comment]
It would be nice to label it 23'23" to 38'23" that would be a clearer notation for minutes and seconds

**Comment by averylarry** [comment]
I like nn:23:23 but really not a big deal once i figured out.

**Comment by jareem** [comment]
Ok ! Indeed, not intuitive.
