### ISSUE TITLE
How to export spawn points data ?

### ISSUE THREAD

**Issue by hk2046** [PokemonGoMap/PokemonGo-Map#1105]
Dear,

May i know how to export spawn points data?
I would like to share data with my friend, thanks!

**Comment by shadi1989** [comment]
http://pgm.readthedocs.io/en/develop/extras/Spawnpoint-Scanning.html

Good luck!

**Comment by DrAtari** [comment]
https://www.reddit.com/r/pokemongodev/comments/4wp2cp/get_your_own_unique_spawn_map_for_your_area/
