### ISSUE TITLE
how many accounts is needed? 

### ISSUE THREAD

**Issue by Dcaneman** [PokemonGoMap/PokemonGo-Map#1114]
I just created abuot 60 accounts, and wanted to have a -st 20 area. But when i scanned, it had alot of red circles, so it wasnt scanning much. is 60 accounts not enough? Is there any other way to scan bigger areas? i read about the beehive, but dont understand it. 

btw, when i start the scanner i write python runserver.py -k "key" -a ptc  -u "all my accounts with -u before -p "my password which is same for all accounts" -l "my town" -st 20 -H 0.0.0.0 Am i doing wrong? 

Sorry if im asking on the wrong place, but the discord didnt work, i couldn join.

**Comment by shadi1989** [comment]
Try again joining the discord. everyone can join so you should be welcome too :) https://discordapp.com/channels/204338767920758785/204338767920758785

**Comment by BaIthamel** [comment]
^
