### ISSUE TITLE
Running multiple --webhooks with a single command? 

### ISSUE THREAD

**Issue by lmantas** [PokemonGoMap/PokemonGo-Map#1116]
I've been trying to figure out how to run multiple webhooks, if that's even possible? I've tried to add -wh http://127.0.0.1:4001 -wh http://127.0.0.1:4002 to my command line, but looks like only the last one counted. Is there any other way to do this without making another map clone?

**Comment by BaIthamel** [comment]
someone said they had a way of making it work. This is not a support forum; please see [the discord #help channel](https://discord.gg/npVqkUn) for assistance.
