### ISSUE TITLE
ImportError import requests

### ISSUE THREAD

**Issue by mlfactory** [PokemonGoMap/PokemonGo-Map#1125]
Hello Guys,

sorry i know thats not the right place but i postet @ the forum here yesterday http://pokemongo-map.me/index.php but my post is not submited by the admin.

The Problem:
```
`Traceback (most recent call last):
  File "./runserver.py", line 10, in <module>
    import requests
ImportError: No module named requests`
```

I follow this instructions http://pgm.readthedocs.io/en/develop/basic-install/linux.html but its the same problem:

`oot:~/PokemonGo-Map# ./runserver.py
Traceback (most recent call last):
        File "./runserver.py", line 10, in <module>
        import requests
ImportError: No module named requests

**You will need to completely uninstall all of your pip packages, pip, and python, then re-install from source again. Something from your previous installation is still hanging around**.`

Also i run this:

`git pull
pip install -r requirements.txt --upgrade
npm install
npm run build`

to update the scripts but the problem is the same.

Please can you help me?

Many thanks for your time,
Michael

**Comment by aldarund** [comment]
Did u ever read the issue template? IT says SEVERAL TIMES IN CAPS ISSUES NOT FOR HELP USE DISCORD OR FORUM
