### ISSUE TITLE
[Feature Request] Search based on country

### ISSUE THREAD

**Issue by nicktan147** [PokemonGoMap/PokemonGo-Map#1129]
I have been sharing my tools for a month now, since some of are not my  are out of my country, they used to scan their area for pokemon, and ended up my accounts running the map some are being banned. Can we create a function to limit the search function to limit the search result?

I searched through google, and found this,
http://stackoverflow.com/questions/8282026/how-to-limit-google-autocomplete-results-to-city-and-country-only

I tried to implement it doesn't work. Not sure if I put on the wrong js file, could anyone enlighten me?

**Comment by jaquer** [comment]
I don't know how to make it user-configurable, but here's how to make the change yourself:

Open `static/js/map.js` in an editor and search for `searchBox`. You should find this line:

`var searchBox = new google.maps.places.SearchBox(document.getElementById('next-location'))`

Right after it, add a line like this:

`var autocomplete = new google.maps.places.Autocomplete(document.getElementById('next-location'), {componentRestrictions: {country: 'us'}})`

Replace `us` with your country's [ISO 3166-1 alpha 2 code](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2)

**Comment by sebastienvercammen** [comment]
Map is not built to be a platform to scan every visitor's location. Closed.
