### ISSUE TITLE
Add "run server but no webinterface" option and make GMAP key optional

### ISSUE THREAD

**Issue by ilendemli** [PokemonGoMap/PokemonGo-Map#113]
As the title says, would be nice to run a webserver for requests but without the webinterface.

**Comment by roland3** [comment]
I'm pretty sure -ns option does it.
From `--help`:
```
-ns, --no-server      No-Server Mode. Starts the searcher but not the Webserver.
-os, --only-server    Server-Only Mode. Starts only the Webserver without the searcher.
```

**Comment by ilendemli** [comment]
@roland3 no, -ns starts the searcher, but the api is not accessible

**Comment by NGPriest** [comment]
You seem to want the searcher, but which API are you trying to access and how?

**Comment by marauder37** [comment]
I don't think this is going to be high-prio for anyone else but if you want to implement it and it's done right I'll merge it. Done right = triggered by no gmap key, doesn't add any more flags or config options, prints helpful warning message to console when triggered, serves an explanation page in place of the map to tell newbies to set a gmaps key

**Comment by ilendemli** [comment]
@marauder37 i will do (or at least try) it in my free time and create a PR

**Comment by chuyskywalker** [comment]
More so than what @marauder37 said, I don't know if we'd accept such a PR anyway. For 99% of the users, there's no reason to turn off the `/` page, but adding such an option would mean we have to constantly be sure it's working. It'd be an extra, always-there, dev burden with very low usage for the general user population.

As an alternative, it would be relatively easy to put the map behind a reverse proxy (which people do for all other kinds of reasons like ngrok, ssl, basic-auth, etc) and limit that forwarding endpoints there.

**Comment by ilendemli** [comment]
@chuyskywalker why not satisfy the 1% too? :P
check the commit [here](https://github.com/PokemonGoMap/PokemonGo-Map/pull/119/commits/98da16cc69985094b5adef8721906340d1c1b14f)

**Comment by JZ6** [comment]
@ilendemli i agree with @chuyskywalker 
> I don't know if we'd accept such a PR anyway. For 99% of the users, there's no reason to turn off the / page.

-1
