### ISSUE TITLE
Can't type Pokemon in text fields.

### ISSUE THREAD

**Issue by NoobDev3** [PokemonGoMap/PokemonGo-Map#1133]
## Expected Behavior

When opening the options pane and adding Pokemon to the Hidden or Notify text boxes we should be able to enter them using keyboard. This used to be the case but it looks like it was changed.

## Current Behavior

When opening the options pane and adding Pokemon to the Hidden or Notify text boxes you're unable to use the keyboard to enter multiple Pokemon. 

## Possible Solution

Reverse changes implemented to restrict this functionality. I believe there was a merged PR that messed with these fields.
## Steps to Reproduce (for bugs)

1. Open map in browser
2. Select Options
3. Click into text box for Hidden or Notify Pokemon
## Context

This makes it more difficult to enter multiple Pokemon at a time.

For example trying to add Pokemon to the Hide Pokemon list. Previously you were able to type Pidgey, Rattata, and Caterpie. Now you can only select them from a large drop down.
## Your Environment

- Version used: latest Dev branch
- Operating System and version (desktop or mobile): Windows 10 Desktop (not touch screen) & Windows 10 Laptop (touch screen)

**Comment by Studio-XP** [comment]
Works as before with Chrome on Win10. On mobile devices, the popup keyboard would previously make it next to impossible to modify the contents of the multiple select boxes. You are correct that #1030 did prevent the popup keyboard from appearing on mobile though. Imo, I would much rather have to scroll to choose a pokemon than having to fight with the keyboard

**Comment by NoobDev3** [comment]
@Studio-XP I'm seeing that this affects more than just mobile devices. This is a problem on both Win10 Desktop without touchscreen and Win10 Laptop with touchscreen.

**Comment by DiscoTim** [comment]
@NoobDev3 which browser are you using on win 10?

it targets touchscreen based on the existing function:

```
function isTouchDevice () {
  // Should cover most browsers
  return 'ontouchstart' in window || navigator.maxTouchPoints
}
```

maybe that function needs to be refined, or as i said in my PR it could target mobile os's on top of that.

I agree with @Studio-XP in that i would rather not have the search field working, than have the selection boxes completely unusable on mobile.

**Comment by jrmougan** [comment]
Same problem here! is on touch devices, keyboard doesn't appear

**Comment by NoobDev3** [comment]
@jrmougan that was developed intentionally in the PR listed above.

@DiscoTim browser tested on Chrome and Firefox with the same behavior, unable to enter data into the field with a physical keyboard. 

Side note on a mobile deice (iOS) I was able to use it, it just wasn't the best experience.

**Comment by DiscoTim** [comment]
@jrmougan thats not the problem, the keyboard is not supposed to appear on touch devices. its the point of the PR, the keyboard was making the selection boxes unusable on phones and tablets.

**Comment by DiscoTim** [comment]
@NoobDev3 there likely is device attached or driver that's qualifying as touch. If its really an issue for people, it would have to be reworked to detect mobile devices.

**Comment by justsomedudeonthenet** [comment]
Given the two options, I prefer the current version of not showing the keyboard on touchscreen devices.  Trying to add and remove things from that list with the on screen keyboard randomly popping up was a nightmare.

**Comment by sebastienvercammen** [comment]
Since the behavior of mobile devices can be very diverse and uncontrollable/unforeseeable, leaving it as-is is the best course of action: this works for many devices and requires only a little extra effort for some users (but removes a lot of trouble for many others).
