### ISSUE TITLE
database is locked...Retrying

### ISSUE THREAD

**Issue by Gallifery** [PokemonGoMap/PokemonGo-Map#1134]
At some point, all response I get is database is licked...Retrying
[db-updater-60][models][WARNING]database is locked...Retrying
[db-updater-26][models][WARNING]database is locked...Retrying
## Expected Behavior

Expect to see XX pokemon inserted, xx gyms inserted, xx pokestops inserted
## Current Behavior

All the response are like following, with the number behind db-update different, could vary fro 10-90 from what I see
[db-updater-26][models][WARNING]database is locked...Retrying
## Possible Solution

Increase database exchange bandwidth in coding? 
## Steps to Reproduce (for bugs)

http://i.imgur.com/mZ7sRVB.png
1.Run 25 accounts in one terminal
2.python runserver.py -st 20 --db-threads 100
3.No proxy assigned
4.

## Your Environment

* Version used: cloned at 2016-09-04 09:27
* Environment name and version (e.g. Python 2.7): Python 2.7
* Operating System and version (desktop or mobile):Windows 10 64 bit

**Comment by aldarund** [comment]
Solution - dont use sqlite.  It never ever was designed to work with multiple same time connections.

**Comment by averylarry** [comment]
Might this be gevent?  #1084 #1082

**Comment by Gallifery** [comment]
Indeed this might be related to query too long thing. As I previously got the WARNING query is >50 (87) thing, which is also the reason why I increased --db-threads 100

**Comment by aldarund** [comment]
@Gallifery ssqllite not supposed to be working with multiple same time write operations. You will get this error no matter what if multiple same time insert happens. And it will happen if there more than one worker. Sqllite not a proper db to use

**Comment by Gallifery** [comment]
Is the using mysql going to help? I think they are two different things right? As there is a section in the documentation about **Using a MySQL Server**

**Comment by aldarund** [comment]
@Gallifery yes, there wont be such errors in mysql, because its a proper database not a dropin like sqllite. SQllite good for testing thats all

**Comment by Gallifery** [comment]
Thanks, then I will just run MySQL

**Comment by deevusone** [comment]
@Gallifery can you please instruct me how to run MySQL?

**Comment by diepflanzen** [comment]
In the Wiki, it seemed that the instructions for MySQL was written for windows user only. Can Mac users run MySQL as well?

**Comment by deirdresm** [comment]
@diepflanzen https://mariadb.com/kb/en/mariadb/building-mariadb-on-mac-os-x-using-homebrew/ should be what you need. And yes, Mac users can run it too.

**Comment by diepflanzen** [comment]
Thanks a lot, it worked perfectly!
I should probably add some instructions to the documentation for Mac users like me~
