### ISSUE TITLE
Add command-line arguments for Map settings

### ISSUE THREAD

**Issue by snajjar** [PokemonGoMap/PokemonGo-Map#114]
It would be cool if we could set the map settings (show gyms, hidden pokemons, map theme, etc) from the command line. 

## Expected Behavior
We could run a PokemonGo Map with dark theme, with the option "Show scanned location" set to true and hiding pidgey and weedle from the command-line:
`python2 runserver.py -a ptc -u username [....] --mapopt show-scanned-location:false --mapopt hide:pidgey,weedle --mapopt theme:Dark`

However, the syntax here is just a suggestion.

## Current Behavior
We can't set any of the map options from the command line. Every time a server is started, the settings needs to be configured again.

## Context
I've created a pogomap server "manager" for my friends, and i would like to add the possibility to save their own map preferences. It can be done by just passing thoses args to command line, but i'm also willing to discuss any other solution.

**Comment by invisiblek** [comment]
We're using localStorage in the browser to save user's preferences.

**Comment by marauder37** [comment]
I'm in favour of something like this, I have to do unnatural things to set my (long) ignore list in the js so that it gets pushed to my phone's localstorage

**Comment by snajjar** [comment]
Localstorage isn't reliable enough for something like this, it can be deleted anytime and you will have to re-enter all settings again.

**Comment by snajjar** [comment]
But in the meantime, @marauder37 do you have a description of how localstorage keys are managed? I guess i could just push my users config to localStorage before launching the server (it's ugly but i guess it'll work). Is there a wiki link or should i just digg into the code?

**Comment by snajjar** [comment]
Ok, it looks like implementation will be pretty simple:

1) Add setters to the Pogom class for every map option (like Pogom.set_current_location in pogom/app.py)
2) Call setters while parsing the mapopt args (in runserver.py)
3) Add the new args when rendering the template in Pogom.fullmap (in pogom/app.py)
4) Modify the map html template to take theses vars into account to initialise the targeted fields to the desired values (templates/map.html)

Do i forget something?

**Comment by Chlodochar** [comment]
Can't we just have a few settings or json file that  initializes `Store` with its values upon loading `map.js`? It seems quite a lot of work to keep python synchronized with map.js with its options (now and in the future).

**Comment by snajjar** [comment]
Would work in theory, but if you want to manage multiple users, you'll have to overwrite that file over and over again. That's why i was trying to figure out something with the command line.

**Comment by Chlodochar** [comment]
@snajjar Indeed. Maybe just files wouldn't cut it, but some generic way to supply options from server to client is needed here I think.

**Comment by snajjar** [comment]
Could we maybe go for both options:
1) a Json file with map options
2) a Json string with map options

How does that sound?

**Comment by Chlodochar** [comment]
@snajjar Sounds good. It doesn't specifically has to be a full JSON object, but some key-value is also good. The value being JSON/JS would be nice though. `mapopt` like before is fine imo, but the key `show-scanned-location` needs to match the `Store` keys in the client.

**Comment by snajjar** [comment]
@Chlodochar ok, that sounds good. But, given the fact that we don't want to maintain *all* map options, is there a way to push all map options at once to the store on page load?

**Comment by Chlodochar** [comment]
@snajjar Probably using a API call. (like `GET /settings` or something like that). It's also possible to embed JSON in the template file, but I'd rather not pollute it more than it already is ;). Not sure how others feel about this though.

**Comment by eeg710** [comment]
I'm confused. I understand the request is for a way to have multiple configurations specified, but is there currently a way to specify a single set of options for when the page loads?

**Comment by snajjar** [comment]
@eeg710 not that I know of
(someone please tell me if i'm wrong)

**Comment by snajjar** [comment]
Any other opinion on how we should proceed for this?

**Comment by irus99** [comment]
yes I would love to be able to hide pidgeys and other pokemon from the command line or from the config file.

**Comment by BaIthamel** [comment]
For feature requests please migrate this to the new feature page
http://feathub.com/PokemonGoMap/PokemonGo-Map/
Thankyou!

**Comment by CoolCanuck** [comment]
@BaIthamel This request needs to be opened again. FeatHub is no longer used. Good riddance.

**Comment by snajjar** [comment]
+1
