### ISSUE TITLE
[Feature Request] Pushbullet Notification

### ISSUE THREAD

**Issue by xGine** [PokemonGoMap/PokemonGo-Map#1140]
Notify with location screenshot location please. 

I think this is pretty useful for users who's ISP blocks port forwarding like mine.

I see this as an alternative. (like teamviewer but uses a lot of bandwidth)

Thank you in advance.

**Comment by Albert62** [comment]
https://github.com/kvangent/PokeAlarm

**Comment by xGine** [comment]
@Albert62 thanks man. I don't know that it already exist.

**Comment by xGine** [comment]
close thread
