### ISSUE TITLE
Allow the webserver to act as a dual "admin" and "public" access

### ISSUE THREAD

**Issue by LordNeoZ** [PokemonGoMap/PokemonGo-Map#1145]
We should clearly differentiate "public access" with "admin access" to help with shared maps.
We can't let users change location and opening 2 different instances is just not right. I've edited the GUI for the webserver-only and kept the "admin" version on a hidden port. Still it doesn't feel "safe". There should be password protection for admin (or even both) so we can customize the "public" version without worries about the admin options and also restricts the way the public can interact with the map (like not allowing notifications or to see the statistics or heatmaps).

## Expected Behavior
Password protected web with admin and public passwords.

## Current Behavior
Anyone who founds your IP & Port can mess up with your scanner, even if it's Niantic or a third party, either making your accounts get banned for teleporting or trying to hunt you by checking the spots you're scanning and checking players with the same habits.

## Possible Solution
Password protection for the website, More GUI flags to hide stats, notifications options or heatmaps or even not allowing anything, just to watch.

## Steps to Reproduce (for bugs)
1. Make a public map
2. Share it
3. Try to stop more people to use your map without changing the port/IP address
4.

## Context
I shared a map (fixed location, custom gui to disable all features) some weeks ago, after more than a thousand people hammered my little VPS i had to shut down the map (normal gui on custom port, public access on port 80) and switch ports. Some days later i found people using the map again (despite i didn't shared this new ip address), so i had to change to no-server mode for the normal gui (so now i can't stop the map without accessing the VPS) and changed the "public" port again. Today i found about 300 people connected on the new port, so i guess someone is running a port scan of something. Now i added some basic password protection (using innerHTML to rewrite the whole document if the password isn't right, but i wonder how long will this last.

## Your Environment
Python 2.7
Windows Server 2008

**Comment by FrostTheFox** [comment]
We don't support running public maps,

**Comment by DiscoTim** [comment]
why is the status page password protected?

**Comment by justsomedudeonthenet** [comment]
True authentication is much better done in apache or nginx, using reverse proxy to your map instance(s).

**Comment by DiscoTim** [comment]
exactly what @justsomedudeonthenet says, and setup ssl in the process if you haven't already.
but all public access aside, it would be really nice and a lot cleaner if the map did have an /admin route, for the admin type settings and the main map just had general use settings.

**Comment by LordNeoZ** [comment]
@FrostTheFox, then why allow outside access at all? Even if you don't share your map, outside access risk your map to be discovered by port scanners and be tampered with.
@DiscoTim  because the status page contains worker info, so it could lead to get the accounts banned
@justsomedudeonthenet sorry, i don't know anything about python, so i don't know how to integrate this into my usual hosting stack, right now i'm running all my instances on a separate VPS. Probably there is some way to just run this on a folder inside my normal hosting and use the hosting tools (apache and nginx as you said) to password protect this. I've also made some php authentication with unique tokens and stuff, but it just feels clumsy.
@DiscoTim 2: If all this should be done server side, then why keep it into the app code?

**Comment by FrostTheFox** [comment]
@LordNeoZ Sure, we could just disable binding externally, but that's quite easy to bypass. Something like ngrok for example would defeat that.

**Comment by FrostTheFox** [comment]
No one forces external binding.

**Comment by DiscoTim** [comment]
@LordNeoZ thanks :) i know why the status page has is passworded, it was more rhetorical.

Nginx or Apache proxy is the way to go, it isn't clumsy. its what you need to be doing.

**Comment by FrostTheFox** [comment]
@LordNeoZ Just tag your issue with the [Feature Request] title. someone has to manually tag it.

**Comment by LordNeoZ** [comment]
@FrostTheFox thanks for tagging it :)
It's not about disabling binding, but not even having the -H tag, so if someone wants to bind it externally has to do it's own work (either editing the source or using ngrok)
@DiscoTim I'm not there yet learning the wheels of python to deploy it along with my regular php website. I'm running it separately on a VPS. I started a week ago to learn python (mostly to help with this, but also to start learning "modern" programming languages). and i'm yet building basic desktop apps, haven't digged into flash/webservers yet.

**Comment by FrostTheFox** [comment]
The -H tag is not exclusively for binding externally, I don't see much of the point really in disabling external binding because as I mentioned before it's easily bypassable. We're not saying that we don't support making your map available externally, because available externally != public map. We just don't support running a map that's meant to be used by the general public. (usually having the map running off a domain is a good indication.)

**Comment by FrostTheFox** [comment]
So, basically, having an externally available map is ok. Running a map meant to be used by large amounts of people, not supported.

**Comment by FrostTheFox** [comment]
Wontfixing this because it's not going to be implemented.

**Comment by LordNeoZ** [comment]
@FrostTheFox Despite not getting where the line is in terms of support of shared/public maps I have to agree that the different GUI isn't something that's inside the scope of this feature request or the PokemonGo-Map itself.
Even for private use any map externally available should have an "admin" password protection to disallow the location change without forcefully having it to be disabled from command line (-fl or -nsc), similar to the status page, it's something that could tamper with the statistics if done wrong on purpose by a third party.
If you're outside hunting and want to change the location, you should be able to do so, without risking someone else to find your IP/port and messing up with that.
