### ISSUE TITLE
[Feature Request] Webhook backend

### ISSUE THREAD

**Issue by adosikas** [PokemonGoMap/PokemonGo-Map#1149]
As this app sends everything a worker would find via webhooks (except scanned areas but those aren't really neccessary), it would be nice to have the option of a built-in webhook _server_ that recieves pokemon/gym/fort data instead of relying on local workers or mysql.

This would be especially useful, as cloud hosting providers are banned from the api and setting up a publicly acessible mysql is not supported everywhere.  
One could run workers somewhere else, like at home or at a place with limited bandwidth, but still have the advantages of cloud hosting, such as fast response times and scalability.

I hacked up a quick test for pokemon only, however i am not too comfortable with the used frameworks and data structures to make a proper (high quality) pull request myself.

~~Diff: https://gist.github.com/adosikas/b658460f76aad5266a94b6e090226dd9~~

Edit: Figured out how it works (i think) and made a pull request, see #1161

**Comment by sebastienvercammen** [comment]
It's not the map's job to be on the receiving end of the webhooks. Closed.
