### ISSUE TITLE
Every hour from 50:03 to 05:03 

### ISSUE THREAD

**Issue by PeshBG** [PokemonGoMap/PokemonGo-Map#1150]
Can someone please explain how i should read this? The given spawn point spawns a charmander at ^^:50

**Comment by IsaacN** [comment]
This is not an issue, this is a help request. Please do not post help requests in the issues section.

In answer to your question, that means at 50 minutes and three seconds past an hour, a pokemon will spawn. It will then despawn at five minutes and three second past the following hour.
