### ISSUE TITLE
Notify for all pokemons at selected spawn points (or notify all pokemons nearby a location)

### ISSUE THREAD

**Issue by Okloks** [PokemonGoMap/PokemonGo-Map#1151]
It woull be great if I could get notifications about all pokemons (despite of hidden/excluded list):
a) near me
AND / OR
b) at selected spot

Choose reasonable realization.

I have 24/7 scanner at my work and some spawn points near me. Scanner is filtered to hide some kinds. I don't want to hold the game opened and eating my battery. It can be launched only if a pokemon detected nearby. Quick catch and close.

**Comment by Imoq** [comment]
https://github.com/kvangent/PokeAlarm

**Comment by justsomedudeonthenet** [comment]
Alerting is best left to a separate program using webhooks, like [PokeAlarm](https://github.com/kvangent/PokeAlarm)
