### ISSUE TITLE
Ip-Banned proxy/proxies eat away spare accounts

### ISSUE THREAD

**Issue by azd2** [PokemonGoMap/PokemonGo-Map#1152]
## Expected Behavior

Change proxy if proxy gets ip-banned or at least stop cyling through accounts if proxy is the reason
## Current Behavior

Whenever an Account gets "failed" as search result 5 times, a new one is used. 
I'm running 37 threads (Python instances) with 18 active workers per thread and 60 accounts per thread (42 spare accounts). 
Each thread uses 18 proxys out of ~100 specified (private proxies). 
When one of the proxys stops working for whatever reason, all spare accounts are cycled through until none is left (even using 100 accounts per 18 workers wouldn't solve this as long as the current behaviour persists).
If proxy is ip-banned, ip ban won't be lifted with this behaviour.
## Possible Solution

Cycle through proxies like:
5 times result: failed --> change proxy if annother is available, 5 times failed again-->change account if annother is available, if failed again, repeat? Not sure if that's the best approach, someone more experienced with this software than i might come up with a good solution hopefully...
## Steps to Reproduce (for bugs)

1. create a thread with more than one worker + spare accounts and different proxies (use free proxies for higher chance of getting an ip-banned one)
2. See spare accounts decrease whenever an ip-banned proxy is used 
## Your Environment

- Version used: develop 04.09.2016
- Environment name and version (e.g. Python 2.7): not relevant
- Operating System and version (desktop or mobile): Windows 7

**Comment by schadis** [comment]
i have merged #1039 and the problems are gone!
same ip since 3 days with 0 maybe banned accounts... all working well!
when you merge this workers will only sleep if they fail 5 times consecutively
hope i could help you ;)

**Comment by azd2** [comment]
Thank you for the idea, but it would not solve the original problem.
Failed proxy of course produces consecutive fails leading to the same result as before ;-)
Athough i too think that PR should make it into develop since it makes a lot of sense^^

**Comment by erikssonk** [comment]
As the dev of #644 - This hasen't been implemented at all, once a proxy is checked and thread is stared it will stick with that proxy even if that proxy fails. I'm planning to do a PR with improved proxy handling that addresses this behavior but also regular checks the state of the proxy. I'll update this issue / feature  when an PR is in place.

**Comment by ottowayne** [comment]
@erikssonk Any news on that topic?
I'm thinking of doing something myself here if there is no solution available yet.

**Comment by erikssonk** [comment]
@ottowayne Have a look at #1235

**Comment by sebastienvercammen** [comment]
Fixed with #1235.
