### ISSUE TITLE
[Feature Request] Notify by e-mail

### ISSUE THREAD

**Issue by Pauloozzy** [PokemonGoMap/PokemonGo-Map#1158]
I don't know if is possible, but i'll great if can send e-mail or a Telegram message of found X pokemons.

**Comment by hundasupa** [comment]
Use a webhook on each worker and setup. They support telegram [PokeAlarm](https://github.com/kvangent/PokeAlarm)

**Comment by justsomedudeonthenet** [comment]
Alerting is best left to a separate program using webhooks.
