### ISSUE TITLE
gym-info database problems when gym-info:true  

### ISSUE THREAD

**Issue by badboiaustria** [PokemonGoMap/PokemonGo-Map#1162]
## Expected Behavior

upgrade from old version to new development version should include gym-info table upgrades on MYSQL DB

## Current Behavior

upgrade from old to current version does not upgrade gym-info tables correctly. exceptions occur when gym-info:true .

disable gym-info avoids exceptions.

## Steps to Reproduce (for bugs)

1. run MySQL DB with release version (DB V5)
2. upgrade to current developer version
3. set gym-info:true  
-> exception

## Your Environment

* Environment name and version (e.g. Python 2.7): Python 2.7
* Operating System and version (desktop or mobile): Windows 10 Desktop

**Comment by Xcelled** [comment]
Duplicate of #1106.

**Comment by justsomedudeonthenet** [comment]
Closing as duplicate of #1106
