### ISSUE TITLE
[HELP] cant install npm...

### ISSUE THREAD

**Issue by creedsin** [PokemonGoMap/PokemonGo-Map#117]
tried both commands 
npm install and npm install -g grunt-cli both failed.. :(

E:\PokemonGo-Map.git\trunk>npm install
npm WARN optional Skipping failed optional dependency /babel-plugin-transform-es
2015-block-scoping/babel-template:
npm WARN Failed to parse json
npm WARN Unexpected token '\u0000' at 1:1
npm WARN

npm WARN ^
npm WARN File: C:\Users\AT\AppData\Roaming\npm-cache\babel-template\6.9.0\pa
ckage\package.json
npm WARN optional Skipping failed optional dependency /babel-plugin-transform-es
2015-block-scoping/babel-types:
npm WARN Failed to parse json
npm WARN Unexpected token '\u0000' at 1:1
npm WARN

npm WARN ^
npm WARN File: C:\Users\AT\AppData\Roaming\npm-cache\babel-types\6.13.0\pack
age\package.json
npm WARN optional Skipping failed optional dependency /babel-plugin-transform-es
2015-block-scoping/lodash:
npm WARN Failed to parse json
npm WARN Unexpected token '\u0000' at 1:1
npm WARN

npm WARN ^
npm WARN File: C:\Users\AT\AppData\Roaming\npm-cache\lodash\4.14.1\package\p
ackage.json
npm ERR! Windows_NT 6.1.7600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3
npm ERR! file C:\Users\AT\AppData\Roaming\npm-cache\babel-traverse\6.13.0\pa
ckage\package.json
npm ERR! code EJSONPARSE

npm ERR! Failed to parse json
npm ERR! Unexpected token '\u0000' at 1:1
npm ERR!

npm ERR! ^
npm ERR! File: C:\Users\AT\AppData\Roaming\npm-cache\babel-traverse\6.13.0\p
ackage\package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR!
npm ERR! This is not a bug in npm.
npm ERR! Tell the package author to fix their package.json file. JSON.parse

npm ERR! Please include the following file with any support request:
npm ERR!     E:\PokemonGo-Map.git\trunk\npm-debug.log

**Comment by freakjam** [comment]
Run npm install in the root folder of PokemonGo-Map folder, not in the trunk folder.

**Comment by marauder37** [comment]
For more installation or configuration help please visit https://discord.gg/nXyMej6 . Github issues are only for issues/bugs in the code. Thanks!

**Comment by creedsin** [comment]
Still same error in root also..
