### ISSUE TITLE
[Feature Request] A way for the PogoLocationFeeder can get the coords of the Pokémons more easily

### ISSUE THREAD

**Issue by frankalison** [PokemonGoMap/PokemonGo-Map#1171]
Do something like this https://pokewatchers.com/grab/
for the PogoLocationFeeder (https://github.com/5andr0/PogoLocationFeeder) can get the coords of Pokémons more easily.

**Comment by DiscoTim** [comment]
its a snipe app isn't it?

**Comment by justsomedudeonthenet** [comment]
This is what webhooks are for.

**Comment by frankalison** [comment]
yes, its a snipe app
