### ISSUE TITLE
[Feature request] Handle early spawns with SS mode

### ISSUE THREAD

**Issue by Slivo-fr** [PokemonGoMap/PokemonGo-Map#1173]
Scan spawn that can spawn early every few moment to check if it spawned

## Expected Behavior
When a pokemon early spawn, the map display it after a reasonable delay

## Current Behavior
The map wait for the regular systematic spawn to scan this spot, even if it know it can spawn early

## Context
Knowing there is a pokemon on an early spawn could make the difference between going out to chase it or staying home.

![image](https://cloud.githubusercontent.com/assets/10325988/18270293/6fdd3928-742c-11e6-9987-d55a314d5cfa.png)

**Comment by justsomedudeonthenet** [comment]
This is part of a larger issue - even if we scanned it, we wouldn't see the right info about the spawn.  These are spawnpoints that don't follow the usual 1 spawn for 15 minutes every hour pattern.  Right now, we don't handle those spawns properly at all.
