### ISSUE TITLE
Anyone got this running on CentOS 6?

### ISSUE THREAD

**Issue by wschoot** [PokemonGoMap/PokemonGo-Map#118]
Hi,

Trying to make this work on CentOS 6 which by default ships with Python 2.6 and has glibc < 2.14 (while 2.14 is now required by the pgapi) so I've been fiddling some with SCL and compiling my own glibc but the proces hangs at:
2016-08-08 09:56:28,318 [ search_worker_0][      auth_ptc][    INFO] PTC User Login for: USERNAME

Of course, the USERNAME shows the real username, which I've replaced with this placeholder. It doesn't seem to be looping as CPU usage isn't increased. It simply "hangs". The same username works fine on another CentOS 7 testmachine.

Who has this running on CentOS 6? Please share the magic :-)

**Comment by shivampaw** [comment]
Centos6 doesn't have the correct version by default. Upgrading it will break centos. It is possible to install 2.14 alongside 2.12 and I have done that but I couldn't figure out how to make PokemonGo use it!

You are more likely to be better off using Centos7+

**Comment by freakjam** [comment]
For the record, CentOS 7 works just fine, in case you consider upgrading :-)

**Comment by wschoot** [comment]
@freakjam Indeed, that's what I wrote in the OP :-)

@shivampaw Yeah, I manually compiled 2.14 in another location and prepanded my command with ```LD_LIBRARY_PATH=/opt/glibc-2.14/lib:$LD_LIBRARY_PATH``` which makes it start just fine but stops at the mentioned line.

**Comment by RubenHiem** [comment]
@freakjam Can you help me install it on centos 7?

**Comment by wschoot** [comment]
@RubenHiem CentOS 7 pretty much works out of the box. If you have issues with it, please open your own issue instead of hijacking another unrelated one ;-)

**Comment by irus99** [comment]
@wschoot you said CentOS7 works out of the box. Are you able to see pokemon on CentOS7? I am having the same problem as you on CentOS6 so I was going to switch to CentOS7 but I didn't want to if pokemon are not coming up. TIA

**Comment by wschoot** [comment]
@irus99 Yes, there's pokemon showing on CentOS7 for me

**Comment by irus99** [comment]
ok then i'll probably switch to CentOS7, Thanks for confirming that :)

**Comment by cichacz** [comment]
If you don't want to do fresh setup of the whole server you can use my branch for the moment:
https://github.com/PokemonGoMap/PokemonGo-Map/pull/109
I hope it will be merged soon :)
Also you can compile it by yourselves.
It works with libc 2.12 without any errors

**Comment by wschoot** [comment]
@cichacz Nice! Although it doesn't yet work for me (still "hangs" afhter the first user logs in) I'll subscribe to it and follow it's changes!

**Comment by irus99** [comment]
@wschoot. did you run this command by chance 'export LD_LIBRARY_PATH=/opt/glibc-2.14/lib' before trying @cichacz suggestion? Cause that would be the issue. you need to run unset LD_LIBRARY_PATH if you did

**Comment by cichacz** [comment]
@wschoot exactly like @irus99 said, you have to use original libc 2.12 shipped with CentOS6.
If you have `export` command added to some startup script, remove it and relog.

**Comment by wschoot** [comment]
Gotcha! :-) I feel derp now. Thanks for that cluebat! I thought I had only prepended my runserver with LD but I had exported it too. Thanks!

**Comment by irus99** [comment]
@cichacz Also I am still getting the error after replacing the libencrypt-linux-x86-64.so in pogom is there something I neeed to recompile or anything like that? TIA

**Comment by cichacz** [comment]
Are you testing version from my branch, or just want to make it working on current dev?
If .so file is crafted for your OS, then you don't have to compile anything.

On my branch I've moved all libs to subfolder `libencrypt`, so if you put sth in pogom it won't be loaded.
There's should be file libencrypt-centos-x86-64.so which is being loaded when you're on centos.

But maybe you're using 32 bit os? Then i don't have lib for you, you will have to compile it by yourself. I've used this source: http://pgoapi.com/pgoencrypt.tar.gz

**Comment by irus99** [comment]
@cichacz @wschoot 
It is working perfectly now. So what I did was in the pogom folder was make a folder libencrypt downloaded all the files you linked me ( https://github.com/PokemonGoMap/PokemonGo-Map/pull/109 ) into that folder then replaced this file utils.py in the pogom folder and ran chmod +x utils.py then it worked like a charm. Thanks for your help :)  Also I just want to say I am glad they left this issues page open now. This will help all of us out :)

**Comment by cichacz** [comment]
@irus99 For the future: you could just clone my fork :)
For example, sth like this:
```
cd *path_to_PokemonGo-Map*
git remote add cichacz_fork https://github.com/cichacz/PokemonGo-Map.git
git checkout -b cichacz_develop cichacz_fork/develop
* pip/npm etc if needed *
python runserver.py
```

But anyway, good to hear that it worked for you :)

**Comment by AcidicSkittles** [comment]
@irus99 @wschoot 
I spent all day on this yesterday, but after you manually compile and install glibc-2.14 to /opt, you can run:
```
LD_PRELOAD='/opt/glibc-2.14/lib/libc-2.14.so' python2.7 runserver.py ....etc
```

to start the server and have the right glibc version used to encrypt

**Comment by wschoot** [comment]
@AcidicSkittles That's nice too actually! I think I might use for now, thanks!

**Comment by BaIthamel** [comment]
It looks like you have this sorted. If you got it working in a form suitable to PR then do so, otherwise yay you fixed it. So i'm closing.
