### ISSUE TITLE
[Feature Request] Proxy Authentication

### ISSUE THREAD

**Issue by epicmatt** [PokemonGoMap/PokemonGo-Map#1180]
I don't have any public proxies that stay up long enough to be reliable so I need to use proxies with authentication (private ones) if I want an IP that will stay unbanned

## Expected Behavior

N/A

## Current Behavior

socks5://ipHere:ProxyPort only works

## Possible Solution

socks5://ipHere:ProxyPort:ProxyUsername:ProxyPassword
would work

**Comment by TheAussie** [comment]
actually the correct format is socks5://username:password@proxyip:proxyport

**Comment by cstewart90** [comment]
Authentication works fine using the format correct format which TheAussie said.

**Comment by epicmatt** [comment]
please mark as solved then, didn't see this in documentation.

**Comment by epicmatt** [comment]
any recommendation for formatting if username has an @ symbol in it for email address> I can't get it to load any of my proxies.

**Comment by TheAussie** [comment]
it should work anyway if it's username... did you not read how I said how to do it?

socks5://email@domain:password@proxyip:proxyport

or socks5://username:password@proxyip:proxyport

the method works because I am currently using it.
