### ISSUE TITLE
Scanned locations with empty results are dropped from the queue

### ISSUE THREAD

**Issue by ottowayne** [PokemonGoMap/PokemonGo-Map#1181]
## Expected Behavior
Scanned locations with empty results should be requeued (this has to be optional because there are areas in which the scans are expected to be empty except for Pokemon)

## Current Behavior
The locations with empty results are ignored and thus not all Pokemon are being scanned

## Possible Solution
Optional requeuing of locations in case of fail or empty result

## Context
Invalid results cause locations that are not being scanned and Pokemon are missed.

## Your Environment

* Version used: 0127b36de0e231eca2f1ac93457899f0ffb1f850
* Environment name and version (e.g. Python 2.7): Python 2.7.12
* Operating System and version (desktop or mobile): Ubuntu 16

**Comment by justsomedudeonthenet** [comment]
This was an intentional design decision - we would rather have the map keep working than risk getting caught up on one spot that can't be scanned.

You will miss a few scan spots when an account gets banned, or network issues cause the scans to fail.

**Comment by ottowayne** [comment]
I disagree.
It should not be intentional to abandon Pokemon and instead there should be an error count to abandon the location after X fails.

I don't understand why this has been closed.
