### ISSUE TITLE
Problems starting Map on Amazon AWS

### ISSUE THREAD

**Issue by Anderuimm** [PokemonGoMap/PokemonGo-Map#1182]
## Expected Behavior
Run the map without errors.

## Current Behavior
Error Message:
2016-09-06 15:53:33,914 [ search-worker-0][        search][ WARNING] Exception while downloading map: Seems your IP Address is banned or something else went badly wrong...

## Steps to Reproduce (for bugs)
1. Brand new install on Windows Server R2
2. Run

## Your Environment
* Version used:
* Python 2.7.12
* NPM 2.15.8
* pip 8.1.2
* Windows Server 2012 R2

Just a question: I'm trying to run the map on a Amazon AWS Instance when this message appears. It's a Google API Error or what? Should I open any specific port (the Webservice one is already opened)?

**Comment by crckdns** [comment]
Amazon and most other big clouds are banned.. everyone should know it by now o_O

**Comment by slideup-benni** [comment]
You have to use proxies

**Comment by Anderuimm** [comment]
@slideup-benni this config must be set on the project itself or need I to use a 3rd party software? Can you indicate any free-to-use provider?

**Comment by slideup-benni** [comment]
@Anderuimm you can set a proxy with the "-px"-Arg. eg: "-px socks5://127.0.0.1:7070" See --help for more informations.

No, i'm using my own servers.

**Comment by FrostTheFox** [comment]
AWS and many other cloud providers are banned. Use proxies using the argument supplied above, or config.ini
