### ISSUE TITLE
Is there any security problem?

### ISSUE THREAD

**Issue by were** [PokemonGoMap/PokemonGo-Map#1184]
After I deployed this software on Jelastic, these is a web page asking for my google account.

I entered my google account, and then I received an attempt of login my email account in 30 minutes (not me).

So what is going on? Are you guys stealing google account?

**Comment by FrostTheFox** [comment]
"Are you guys stealing google account?"

*clap*

**Comment by FrostTheFox** [comment]
Trust me, if we were stealing google accounts, someone would have found it in the source. That's how open source works.

**Comment by were** [comment]
I trust you, but after deploying, a security problem occurred.

**Comment by FrostTheFox** [comment]
Is the IP address one owned by jelastic? Maybe your proxy if you're using one? What about the location? Time? It could theoretically cause a login message, or it could be a coincidental hack of your account via other means (same password across sites, etc.)

**Comment by were** [comment]
@FrostTheFox I do not mean to hurt you, but I am just afraid.

I would like to believe it is just a coincidental hack.

The IP tried logging in my account was in Florida.

**Comment by FrostTheFox** [comment]
I'm not 100% sure where Jelastic is hosted from, iirc it's not florida.

I think it is a coincidence, didn't mean to make you feel insulted. Either way, a dummy google acc is recommended. Generating PTC accounts using a tool like ptc-acc-gen is also a good way to run the map.

**Comment by FrostTheFox** [comment]
Change your passwords, and enable 2FA if you haven't already is my $0.02.

**Comment by were** [comment]
Sorry, I am a little bit offensive at the very beginning.

- When deploying, there is a specific page which is asking for PokeClub acc or Google acc. After typing in 30 minutes, I receive a dangerous attempt of logging in.
- Yeah, I have changed my passwords


Thank you for your warm help.

**Comment by FrostTheFox** [comment]
This is interesting, can you provide me with the IP google is reporting?

**Comment by were** [comment]
Google told me the IP was 162.219.245.20 in Hialeah, Florida.

**Comment by were** [comment]
I typed in this IP in my address blank, and it leads me to a website called Virtuozzo 6.

**Comment by FrostTheFox** [comment]
"Jelastic is deployed from multiple data centers world-wide[38] and was launched in the US by ServInt, eApps, onTop and Webhosting.net"

The whois on that IP returns "OrgName:        Webhosting.Net, Inc."

So I'd say it is the instance, which for some reason is triggering the google message.

**Comment by were** [comment]
Oh, that's weird. Sorry to bother you. Thank you for your always warm help.

**Comment by FrostTheFox** [comment]
No problem, it's a good thing to know for me aswell.

**Comment by xZeroMCPE** [comment]
Same happened to me..

But somehow, it's PokemonGO-MAP.. The way they access google map api's are weak, so google thinks its someone trying to logged on to your account....

**Comment by were** [comment]
Basically, what PokemonGoMap does is to login a pokemongo account and then pretend to walk around to collect what pokemons exist in this area, so you know why google warns you.
