### ISSUE TITLE
[FEATURE REQUEST] Global sleep schedule (start time, duration, variance)

### ISSUE THREAD

**Issue by Nik0lashka** [PokemonGoMap/PokemonGo-Map#1193]
## Expected Behavior

Ability to set particular day $time for all workers to stop and wait for some $duration with a bit of $variance to mimic human sleep hours.
## Current Behavior

There is -ari option in #996 by @justsomedudeonthenet for sleep $duration, but there is no way to set $time, when sleep starts, niether the $variance. So you can't tell pogomap to stop all workers at say 23:45 and wait for 8 hours until resume.

**Comment by AngryRabbit1** [comment]
You could probably use a cron job or task scheduler for that.

**Comment by justsomedudeonthenet** [comment]
I can't see this being useful enough to be worth the time to code it.  As AngryRabbit1 said, it could be done with task scheduler or cronjobs if you really want.
