### ISSUE TITLE
Heatmap not working with MySql version 5.7.13

### ISSUE THREAD

**Issue by TopoDiFogna** [PokemonGoMap/PokemonGo-Map#1197]
After commit for pulling  #1103 the heatmap is not shown because mysql 5.7.13 complain about only full-group-by which is enabled by default
Error thrown:
`InternalError: (1055, u"Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'pokemon_go.t1.latitude' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by")
`
## Expected Behavior

Heatmap should show for spawned pokemon in full stats
## Current Behavior

Heatmap is not shown
## Possible Solution

The most elegant solution is to rewrite such query, a workaround would be disable only-full-group-by for the database but is not suggested
## Steps to Reproduce (for bugs)

1.Install PokemonGo-Map commit e92fa833745e301af88eb8e1f5e592c7d3283291
2.Configure it to use mysql 5.7.x
3.Open heatmap for a pokemon

## Your Environment

* Version used: Commit e92fa833745e301af88eb8e1f5e592c7d3283291
* Environment name and version (e.g. Python 2.7): Python 2.7 mysql 5.7.13
* Operating System and version (desktop or mobile): ubuntu server 16.04

**Comment by aldarund** [comment]
Will create  a fix today

**Comment by Cliffield** [comment]
As hotfix one could add the following lines to mysql config file e.g. /etc/mysql/mysql.conf.d/mysqld.cnf 
```
[mysqld]
sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
```
and restart mysql: `service mysql restart to restart MySQL`

source: http://craftcms.stackexchange.com/a/13662

**Comment by TopoDiFogna** [comment]
@Cliffield that would disable the feature for all databases managed by mysql! I think the best option is to just rewrite the query.

**Comment by aldarund** [comment]
https://github.com/PokemonGoMap/PokemonGo-Map/issues/1205 here a fix for this issue, you can test it. Should work with full-group-by

**Comment by beccasafan** [comment]
Confirmed #1205 fixes heatmaps with ONLY_FULL_GROUP_BY enabled.

**Comment by FrostTheFox** [comment]
how the hell did i do that

**Comment by FrostTheFox** [comment]
i didn't even click in the issue

**Comment by FrostTheFox** [comment]
oh wait i see

**Comment by FrostTheFox** [comment]
1205 did it cool closed

**Comment by TopoDiFogna** [comment]
@beccasafan How did you tested? i just pulled last commit and the error is still there!

**Comment by aldarund** [comment]
@TopoDiFogna
https://github.com/PokemonGoMap/PokemonGo-Map/pull/1249
