### ISSUE TITLE
-ss Empty cells

### ISSUE THREAD

**Issue by xslayserx** [PokemonGoMap/PokemonGo-Map#1200]
Im doing Spawnpointscanning but some of the scanned cells are empty even tho they should spawn a pokemon. Anyone knows why ? 
My aacount are all up and not banned i checked it.

**Comment by justsomedudeonthenet** [comment]
Usually this means the time on your server is incorrect.

**Comment by Cliffield** [comment]
Might happen if your workers moving to fast (teleporting over long distance).
