### ISSUE TITLE
[FEATURE REQUEST] Scan spawn points only when a pokemon should be there

### ISSUE THREAD

**Issue by DoDoSt** [PokemonGoMap/PokemonGo-Map#1203]
Maybe this feature was requested many times already, but i didn't find it in the issues of the last days.

## Expected Behavior

For every spawn point the information about the disappear time of the pokemon is saved in the db. Calculate a scan queue for an hourly routine. In this queue every spawn points is included once with a time (disappear time -15 minutes). At this time one worker travels to this point and scans it. 
Different types of spawn points have to be scanned also only once per hour, cause it's always the same pokemon which appears.

This mode would reduce the server requests immense and a much larger area could be covered!

## Current Behavior

When I'm using the spawn points only scan mode the workers always scan the spawn points with the hexagon pattern. If the finished one round they begin again. In one hour every spawn point is scaned many, many times.

**Comment by justsomedudeonthenet** [comment]
We already do this. Use -ss instead of --spawnpoints-only.

**Comment by DoDoSt** [comment]
Very good! I'm sorry...
