### ISSUE TITLE
[Feature Request] a new token to download page

### ISSUE THREAD

**Issue by Yuk111** [PokemonGoMap/PokemonGo-Map#1207]
translated using Google translator
Hello.
It is lacking in the new marker.
There are several points of scanning and card are different people and all card opens where the marker Search Location
It is necessary that you open the page it is loaded in a custom location

**Comment by justsomedudeonthenet** [comment]
If I am understanding you correctly, you want it to automatically go to your location when you open the map?

This is already a built in feature.  Enable "Start Map At Me", and make sure you are running on HTTPS since geolocation is blocked in most browsers without it.

**Comment by Yuk111** [comment]
> Enable "Start Map At Me", and make sure you are running on HTTPS since geolocation is blocked in most browsers without it.
but because the card is opened where Search Location
why not just make an opening at the other marker that configures itself for this
