### ISSUE TITLE
Clicking anywhere in Edge causes SCRIPT438: Object doesn't support property or method 'matches'

### ISSUE THREAD

**Issue by DiscoTim** [PokemonGoMap/PokemonGo-Map#1212]
Clicking anywhere in Edge browser causes a SCRIPT438: Object doesn't support property or method 'matches'
## Steps to Reproduce (for bugs)

1. Open map in edge browser
2. Click anywhere
3. Look in console
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Python 2.7):
* Operating System and version (desktop or mobile):

**Comment by beccasafan** [comment]
Confirmed. I can look at this tonight if nobody has in the meantime.

The map does function, the only thing this breaks is closing the options when you click outside of them (ie, clicking on the map doesn't close the options automatically).

**Comment by DiscoTim** [comment]
@beccasafan there is a PR for it already, i just created a matching issue. i believe it is because EDGE doesn't support matches. this will occur in some other browsers too, just not sure which ones. babel-polyfill doesn't include a polyfill for matches. i think either a polyfill for matches needs to be included or the function rewritten so that it doesn't use matches.

**Comment by beccasafan** [comment]
If there's a PR for it then link them together so that everyone knows not to spend time fixing something...Not sure an issue is needed after a PR, but that's not my call! :)

**Comment by DiscoTim** [comment]
its linked now, i overlooked that.
