### ISSUE TITLE
[Feature Request]Account database for all instances

### ISSUE THREAD

**Issue by djgreg13** [PokemonGoMap/PokemonGo-Map#1213]
Hello,

When i launch multiple instance with same csv, the 2 instances uses same accounts.

Can you add an option to prevent second instance to use same account as first instance pleases

Thanks !! :)

**Comment by ChipWolf** [comment]
Short term solution; split your CSV in half for each of your workers.
Long term solution; implement a method to store working data in the database in order for workers to share account and proxy information

**Comment by ChipWolf** [comment]
Possible duplicate issue https://github.com/PokemonGoMap/PokemonGo-Map/issues/1147

**Comment by djgreg13** [comment]
Duplicate of #1147
