### ISSUE TITLE
Exception in search_worker under account xxxxx  Exception message: 'name'

### ISSUE THREAD

**Issue by mudkippzs** [PokemonGoMap/PokemonGo-Map#1214]
## Expected Behavior

It should scan/search as usual

## Current Behavior
2016-09-08 14:45:52,055 [ search-worker-0][      auth_ptc][    INFO] PTC User Login successful.
2016-09-08 14:45:52,055 [ search-worker-0][      auth_ptc][    INFO] Request PTC Access Token...
2016-09-08 14:45:52,258 [ search-worker-0][      auth_ptc][    INFO] PTC Access Token successfully retrieved.
2016-09-08 14:45:52,587 [      db-cleaner][        models][    INFO] Regular database cleaning complete
|S-chain|-<>-170.130.66.98:3128-<><>-130.211.14.80:443-<><>-OK
2016-09-08 14:45:57,405 [ search-worker-0][        models][    INFO] Parsing found 3 pokemons, 137 pokestops, and 9 gyms
|S-chain|-<>-170.130.66.98:3128-<><>-198.199.123.181:3306-<><>-OK
|S-chain|-<>-170.130.66.98:3128-<><>-198.199.123.181:3306-<><>-OK
2016-09-08 14:46:18,099 [ search-worker-0][        search][   ERROR] Exception in search_worker under account xxxxx  Exception message: 'name'
2016-09-08 14:46:18,099 [ search-worker-0][        search][    INFO] Waiting to get new account from the queue

Thats my output after running the python script runserver.py

## Possible Solution

Tried alternate IP incase proxy was blocked - no difference
Logged into acc on my phone, can catch pokes and no apparent issues
Updated from latest /develop branch
ran...
      npm install ran again to ensure updates 
      pip install -r requirements.txt --upgrade 

Both npm and pip updates didnt fix it either

Has been running for the last 2 weeks without any issues apart from slowness due to proxy but thats since resolved. No other issues noticed.

## Steps to Reproduce (for bugs)

1. Really not sure, haven't done anything different to the standard method of running the server
2. 
3.
4.

## Context

I can run my map, it has the historical spawn data from my DB but the search worker just stays on cool down
## Your Environment

* Version used: latest from develop branch
* Environment name and version (e.g. Python 2.7): python2.7 
* Operating System and version (desktop or mobile): ubuntu 16.04 LTS

**Comment by mudkippzs** [comment]
reverted to v3.1.0 seems to work - so bug is in develop branch

**Comment by azd2** [comment]
Same problem here.

What i don't understand is that 7 instances run without issues, one instance though has the problem on all 18 workers.
Setup:
500 proxyservers configured, each worker has his own ip (happens though that a proxyserver is used more than once between the 8 instances, so sometimes there are more than one worker per IP).
- Server instance with 18 workers (scanpoint movable by browser), 60 accounts to pull from in csv->No Problems
- 7 instances with 18 workers, each instance has it's own 60 accounts to pull from in csv-> 6 instances no problem, 1 has all accounts on hold ~3 minutes after start, all accounts with the error above.
Accounts are not softbanned: When i restart, all accounts deliver pokemon, gyms, pokestops and gymdata until the error kicks in. Accounts switch, deliver data for 30 secs, Error above again.

When i change accounts in CSV to 60 others, the error persists.
What i did not (and don't want to) try is to restart one of the working threads.

**Comment by epicmatt** [comment]
Experiencing more of the same, My case started after i gathered spawnpoints in a -st 15 for 4 hours today and then upgraded with a .git pull and then began a -ss with -st 14 

I have about 14 workers and 30 proxies, they all work at first and then shortly after get name exceptions

**Comment by magenbs** [comment]
Experiencing the same issue.  Below is output from log which appears to show exception occurring after getting gym details.


>2016-09-09 09:56:21,344 [ search-worker-1][        search][   DEBUG] Getting details for gym @ XXXX/-XXXX  (0.661345km away)
2016-09-09 09:56:21,345 [ search-worker-1][          auth][   DEBUG] Session Ticket still valid for further 00:29:51 hours (1473432981345 < 1473434773263)
2016-09-09 09:56:22,947 [    db-updater-0][        models][   DEBUG] Inserting items 0 to 1
2016-09-09 09:56:22,949 [    db-updater-0][        models][   DEBUG] Upserted to MainWorker, 1 records (upsert queue remaining: 1)
2016-09-09 09:56:22,949 [    db-updater-0][        models][   DEBUG] Inserting items 0 to 2
2016-09-09 09:56:22,950 [    db-updater-0][        models][   DEBUG] Upserted to WorkerStatus, 2 records (upsert queue remaining: 0)
2016-09-09 09:56:23,031 [ search-worker-0][        search][   ERROR] Exception in search_worker under account XXXXXXXXXXXX  Exception message: 'name'

**Comment by epicmatt** [comment]
Can confirm, fixxed when turning off gym-info

**Comment by epicmatt** [comment]
My overnight temp fix was this in my config.ini not sure which aspect of it worked but it stayed online all night and kept working.

```
account-rest-interval: 25
account-rest-interval: 20
max-failures: 5
```

**Comment by azd2** [comment]
Okay... not sure but i believe i confirmed my idea...
I know for sure one location of a gym that's bugged out in this way: Try 51.229812, 6.761669 (in Duesseldorf, Germany), st=1 is sufficient. 
Behaviour: Scanner finds 11 Gyms there. Scans details for first 10 without error. Each account, that scans details for the 11th gym throws an exception and is swapped out. This goes on until all 60 accounts i tried this with is "used".

**Comment by azd2** [comment]
Now i am almost sure...
What i did: Removed every line out of "models.py" refering to "Trainer name". Run "npm install"-->Problems gone :-)

**Comment by disdain13** [comment]
Other bot has fixed deployment issue, will no longer allow deployment without name and will no longer deploy Grimer or Jynx

**Comment by ctluciani** [comment]
azd2 could you please post your modified models.py?

**Comment by azd2** [comment]
Sorry, just commenting out all trainer names in models.py led to a new bug which required to change map.js. Surely i did other things wrong too.
I am to dumb to code, so really think a dev should look into this and until then you should just not use detailed gym data.

**Comment by pogarek** [comment]
I have the issue on latest experimental code from November 6th.

**Comment by immenz** [comment]
Me too, same problem. Please look into it!
