### ISSUE TITLE
[Feature Request] Gym trainer names and prestige notifications

### ISSUE THREAD

**Issue by sngreco** [PokemonGoMap/PokemonGo-Map#1215]
Trainer Names:
I would like to be able to see what the username is associated with a pokemon in a gym.  This would be beneficial for users who are unsure which gyms they are in or whether a friend / associate has yet to place their pokemon in a gym.

Notifications:
I would also like to be notified when a gym loses a prestige, especially if it's taken down to 0.  I would also like to be able to set a switch on each gym (preferably in the UI) for which ones to be notified on.  This would be beneficial for users who are currently in a gym and want to be notified when they are kicked out or when their gym is being attacked.

**Comment by nhumber** [comment]
trainer names are available when you mouse over trainer image, not working on mobile.

gym notifactions can be obtained with https://github.com/kvangent/PokeAlarm

**Comment by sngreco** [comment]
Interesting, it doesn't do anything for me... i just updated to the latest versions a couple of minutes ago and nothing pops up when hovering over the pokemon image.  Am I missing something?

**Comment by nhumber** [comment]
Might be a browser issue. Its worked all along with chrome

**Comment by sngreco** [comment]
Scratch that, it works... not sure what the problem was.  This can be closed then.
