### ISSUE TITLE
IOError

### ISSUE THREAD

**Issue by dontrix123** [PokemonGoMap/PokemonGo-Map#1219]
im having problem with the new files with IOError, since the new files cannot run multiple instance I used -ns on each of them while run one -os instance for the web server. but im having a problem with "cannot accept morethan 1024 socket" T..T
anyone have the same problem?

## Expected Behavior

IOError

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Python 2.7):
* Operating System and version (desktop or mobile):

**Comment by justsomedudeonthenet** [comment]
This does not have nearly enough information to even figure out what you are doing, let alone what is going wrong.

For support, please try our #help channel on discord.

Issues are for bugs, and require detailed explaination of what is going on.
