### ISSUE TITLE
Scan follows location not functioning properly on some configurations

### ISSUE THREAD

**Issue by baulie** [PokemonGoMap/PokemonGo-Map#122]
'Scan follows location' not functioning properly on some configurations

It doesn't work at all on iOS10, but clicking the GPS icon (right corner below) doesn't always seem to work in Chrome and Safari on iOS 9.3.x or Windows 10 IE and Chrome. 

Someone else with this issue or a solution?

**Comment by andykemp** [comment]
I'm seeing the same on ios10

**Comment by Mr-Groch** [comment]
Some browsers need https connection for sharing device location data - try using something like reverse proxy to enable https connection if you have web server with valid certificate

**Comment by baulie** [comment]
@Mr-Groch I don't have experience with reverse proxy, is there another solution or is the reverse proxy thing 'easy'. Thanks!

**Comment by Mr-Groch** [comment]
Instruction is here:

https://pgm.readthedocs.io/en/develop/extras/nginx.html

**Comment by baulie** [comment]
@Mr-Groch thanks, is there anyway you could translate this to Windows? :-)

**Comment by marauder37** [comment]
https reverse-proxy on windows portforwarding? No way we can give support for that, sorry

**Comment by baulie** [comment]
Noob question, but what's the problem?

2016-08-08 14:35 GMT+02:00 mab <notifications@github.com>:
