### ISSUE TITLE
[FEATURE REQUEST] Modify trainer name implementation in gym details.

### ISSUE THREAD

**Issue by nhumber** [PokemonGoMap/PokemonGo-Map#1225]
## Expected Behavior
Trainer names are easy to see via hovering the mouse over the trainer name.  

## Current Behavior
On a PC with -gi enabled , this works perfectly,
On a mobile device, this is not working correctly.

## Possible Solution
Either remove the mouse over function completely or make some modification to use a different solution if mobile is detected.

Possible idea you could add trainer names in red below each individual trainer, clip the names to 4char or something and show full name with mouse over.

Team Logo could be removed or modified into the names themselves like TEAM <SMLOGO> VALOR
to make space for trainer names.

## Steps to Reproduce (for bugs)

Use -gi and view map on mobile device

## Context
I wish i could contribute and modify this myself but i cant figure it out 

## Your Environment

Any android device i have tested so far

**Comment by springjools** [comment]
Showing trainer names in gyms is imo a serious privacy concern. Just imagine a pedophile following some teenagers using the pokemongo map!

**Comment by nhumber** [comment]
Well I'm not a pedophile and my map is private.. No offense but that is a ridiculous concern. Trainer names already are visible.. I just want to view them on mobile browser also, no other features in the map are desktop only/broken ,why should a broken feature stay broken?

**Comment by springjools** [comment]
But github is not private and anyone can pull the repo from there. It's not about you, but we have no way of testing that whoever pulls something from the repo isn't a pedophile or whatever, so it's a real privacy concern imo. It's already creepy to have childless adult people wandering around children's playgrounds looking for pokemons.

**Comment by BestYohman** [comment]
@springjools Really? That is a ridiculous claim. The persons username is not a private item when its put on  a gym. Also a username does not identify a person unless said username has that child's name in it. It is not like the kid is going to be sticking around that gym constantly. Don't make this something its not. If it is a concern for parents let them handle it.

**Comment by springjools** [comment]
You're just thinking of the NY city case, you also need to consider smaller towns where people are easily identifiable by trainer name. 

It's one thing putting a trainername into a gym so that it's visible from like 1 km away, it's another thing letting people compile databases of how people (including children) move around.

**Comment by BestYohman** [comment]
The username does not show the actual persons name (if it does then the parents are idiots and need to teach their kids better) nor does it show age. I see more adults playing than children, reports have said that most players are from 18 to 34. I am not thinking of larger cases given the fact that I live in a small town. I am thinking as a person who is in the process of taking over a organization to help identify and stop child molestation. Don't make this something it is not. If you are that concerned take a step forward and help parents understand the dangers of putting their child's name as a username or any identifiers.

**Comment by nhumber** [comment]
@springjools - trainer names have appeared for over 2 weeks since merge of #666 , what is your problem? please go and open another issue with your concerns if you feel you must.

i just wanted to bring to light that current implementation is not working on mobile, maybe this should be changed to a [Bug Report]

I didn't expect this to become an ethical discussion on the implications of privacy .

**Comment by SoonDead** [comment]
I have made a feature request at #1290 which is somewhat related. The layout shown there includes the player name moved out of the tooltip.

**Comment by nhumber** [comment]
you mock up looks like what i had envisioned.

**Comment by nhumber** [comment]
#1302 fixed it myself sort of!
