### ISSUE TITLE
[Feature request] Log in to frontend using google account

### ISSUE THREAD

**Issue by HinoReo** [PokemonGoMap/PokemonGo-Map#123]
It would be great to be able to login into front-end of maps through google account and control who can do so.

**Comment by marauder37** [comment]
Thanks for the request but we've decided that front-end auth is out of scope for the project. I would google for `nginx oauth` and see if you can find something that does what you want as a reverse proxy

**Comment by Spacehug** [comment]
Much appreciated!
If anyone stumble upon this issue: https://github.com/bitly/oauth2_proxy is the way to go. I managed to set nginx up to use ssl then pass to oauth2 to authorize through google (one click site-wide), then pass back. If the email of authorized person is in special file, then 200, else 401.
