### ISSUE TITLE
Can not get current location from my location button

### ISSUE THREAD

**Issue by jerryang76** [PokemonGoMap/PokemonGo-Map#1240]
￼￼￼
![1](https://cloud.githubusercontent.com/assets/21218419/18394153/19d59108-76eb-11e6-8f32-2fba610e7074.jpg)
The button on above image dose not work.

## Expected Behavior
After pressing the button, map should move to my current location.

## Current Behavior
After pressing the button, the button blinks non-stop.
It will only stop blinking if I move my map position.

## Steps to Reproduce (for bugs)
The site that I build for PokemonGo-Map.
You can try it and tell me what is wrong with my settings.
http://1.161.13.128/

## Your Environment

* Version used: 2016-9-9
* Environment name and version (e.g. Python 2.7):Python 2.7
* Operating System and version (desktop or mobile): debian 8.5

**Comment by cbogithub** [comment]
you disabled search control, map couldn't dected your location...

**Comment by phil0079** [comment]
You have to use https. Google/Chrome won't even request access to your location unless you're using https.

**Comment by DiscoTim** [comment]
works for me in firefox, no https. chrome would need https though.

**Comment by aldarund** [comment]
not a issue. u need to use https.
