### ISSUE TITLE
404 in google chrome for static .js files

### ISSUE THREAD

**Issue by DiscoTim** [PokemonGoMap/PokemonGo-Map#1244]
In google chrome on windows 10, the static .js files return a 404. the site does seem to work properly.

## Steps to Reproduce (for bugs)

1. open map in chrome on win 10
2. look in console
3.
4.

This is the site from https://github.com/PokemonGoMap/PokemonGo-Map/issues/1240 , my site produces same result.

![404](https://cloud.githubusercontent.com/assets/20764373/18401848/9d3f0fb0-76aa-11e6-92a6-c6e1af5b1a40.jpg)

## Your Environment

* Version used:
* Environment name and version (e.g. Python 2.7):
* Operating System and version (desktop or mobile):

**Comment by aldarund** [comment]
npm run build

**Comment by DiscoTim** [comment]
@aldarund i did:

pip install -r requirements.txt --upgrade
npm install
npm run build

and the issue persists

**Comment by aldarund** [comment]
Some of your chrome extensions request source map for js files.

**Comment by DiscoTim** [comment]
i don't have any chrome extensions enabled, i only use chrome for testing, not my default browser.

**Comment by aldarund** [comment]
http://c2n.me/3C5f9lh http://c2n.me/3C5f6OY - dont have any 404 on ur site. Anyway  its again not a issue, its a source map that your chrome requested for some reason.

**Comment by DiscoTim** [comment]
okay thanks, still not sure why its looking for the map files. its not my site, but i get that on mine site, as well as this one.

**Comment by FrostTheFox** [comment]
Did you wipe out your cache in chrome? It tends to do that with old files sometimes.

**Comment by FrostTheFox** [comment]
Cannot reproduce aswell.

**Comment by DiscoTim** [comment]
cache is totally wiped, history, everything, i don't use chrome as general browser. no extensions etc.. installed. i only use it for testing.

**Comment by shudack** [comment]
It's happen to me too..

**Comment by DiscoTim** [comment]
i found the answer to this, chrome dev console is what trys to load them. there is a setting in the console 'Enable JavaScript source maps', they are used for debugging the minified js.

**Comment by FrostTheFox** [comment]
Interesting, will keep in mind.
