### ISSUE TITLE
error: unrecognized arguments: -ss

### ISSUE THREAD

**Issue by mpena2099** [PokemonGoMap/PokemonGo-Map#1245]
Hi!

Spawn point Scanning not working:

## Current Behavior
```
python runserver.py -ss arq123.json  -st 3
usage: runserver.py [-h] [-a AUTH_SERVICE] [-u USERNAME] [-p PASSWORD]
                    [-l LOCATION] [-st STEP_LIMIT] [-sd SCAN_DELAY]
                    [-ld LOGIN_DELAY] [-lr LOGIN_RETRIES] [-sr SCAN_RETRIES]
                    [-dc] [-H HOST] [-P PORT] [-L LOCALE] [-c] [-d] [-m] [-ns]
                    [-os] [-nsc] [-fl] -k GMAPS_KEY [-C] [-D DB] [-cd] [-np]
                    [-ng] [-nk] [--db-type DB_TYPE] [--db-name DB_NAME]
                    [--db-user DB_USER] [--db-pass DB_PASS]
                    [--db-host DB_HOST] [--db-port DB_PORT]
                    [--db-max_connections DB_MAX_CONNECTIONS]
                    [-wh [WEBHOOKS [WEBHOOKS ...]]]
runserver.py: error: unrecognized arguments: -ss arq123.json

```
## Your Environment
* Version used: "V2.2.0 Stable with api fix" (same error with "v3.1.0")
* Environment name and version (e.g. Python 2.7): Python 2.7.11
* Operating System and version (desktop or mobile): Mac OS X 10.11.6

Thanks,
Mauricio

**Comment by Darkknightz** [comment]
You will need to download Develop, the releases don't have -ss

You can get it here https://github.com/PokemonGoMap/PokemonGo-Map under clone/download

**Comment by mpena2099** [comment]
Thanks! No reference about ir on https://pgm.readthedocs.io/en/develop/extras/Spawnpoint-Scanning.html
