### ISSUE TITLE
PokemonGo-Map is always replace data in sql?

### ISSUE THREAD

**Issue by artdeb123** [PokemonGoMap/PokemonGo-Map#125]
PokemonGo-Map is always replace data in sql?

## Expected Behavior
If there is a data in sql dont replace it.

## Current Behavior
When working 2 "searchers" (ex. Searcher A and Searcher B) and there is a pokemon in area of Searcher A then he insert data in sql, but if there is the same pokemon in area of Searcher B he replace data.

## Possible Solution
I`m not good in python ( this is only my theory) but.. maybe change in peewee.py 
old line:  upsert_sql = 'INSERT OR REPLACE INTO'

new line:  upsert_sql = 'INSERT INTO'

Maybe this can help in my problem?

## Context
Hello
First sorry for my english ;) and i`m not wizard in python php and bash
I`m creating simple notification in php/bash
I added table in sql database for example called 'notification' with default 0
I have 2 searchers in my city with 1 big database.
When searcher A find a pokemon he insert data in sql.
My notification script selecting all data with 'notification'=0 and notify me.
Then script updating for pokemon table 'notification' = 1

But when searcher B is sometime in area of searcher A and he see a pokemon that i want, he replace
data and set notification = 0 and then i have 2 notification from 1 pokemon :/

## Your Environment
Python 2.7.9
Debian 8

**Comment by marauder37** [comment]
Use a different approach. Add a table to record notifications that have been sent. When you send a notification, insert the encounter_id into your new notifications table. Then write your script to `select * from pokemon where encounter_id not in notifications`. 

Don't try and change the upsert approach we're using in the main code. Allowing an encounter/pokemon to be inserted more than once will cause all kinds of other issues.

**Comment by artdeb123** [comment]
Thank you marauder37 :)
This is good idea.
