### ISSUE TITLE
[Improvement] Spiral-from-center hex search order

### ISSUE THREAD

**Issue by MungeParty** [PokemonGoMap/PokemonGo-Map#1254]
## Expected Behavior
Apologies if this is a repost, but this change allows a hex pattern of search locations spirals out from center.

## Current Behavior
Weird top-half-out, then bottom-half-in, then reorder some from the end to the beginning to frontload just some of the southern area.

## Possible Solution
Here's a version of generate_location_steps that spirals clockwise outward around each full hex ring before moving to the next ring out.

```
def generate_location_steps(initial_loc, step_count, step_distance):
    # Bearing (degrees)
    NORTH = 0
    EAST = 90
    SOUTH = 180
    WEST = 270
    pulse_radius = step_distance         # km - radius of players heartbeat is 70m
    xdist = math.sqrt(3) * pulse_radius  # dist between column centers
    ydist = 3 * (pulse_radius / 2)       # dist between row centers

    results = []

    results.append((initial_loc[0], initial_loc[1], 0))

    if step_count > 1:
        loc = initial_loc
        ring = 1
        while ring < step_count:


            loc = get_new_coords(loc, xdist, WEST)
            results.append((loc[0], loc[1], 0))

            for i in range(ring):
                loc = get_new_coords(loc, ydist, NORTH)
                loc = get_new_coords(loc, xdist / 2, EAST)
                results.append((loc[0], loc[1], 0))

            for i in range(ring):
                loc = get_new_coords(loc, xdist, EAST)
                results.append((loc[0], loc[1], 0))

            for i in range(ring):
                loc = get_new_coords(loc, ydist, SOUTH)
                loc = get_new_coords(loc, xdist / 2, EAST)
                results.append((loc[0], loc[1], 0))

            for i in range(ring):
                loc = get_new_coords(loc, ydist, SOUTH)
                loc = get_new_coords(loc, xdist / 2, WEST)
                results.append((loc[0], loc[1], 0))

            for i in range(ring):
                loc = get_new_coords(loc, xdist, WEST)
                results.append((loc[0], loc[1], 0))

            if (ring > 1):
                for i in range(ring-1):
                    loc = get_new_coords(loc, ydist, NORTH)
                    loc = get_new_coords(loc, xdist / 2, WEST)
                    results.append((loc[0], loc[1], 0))
            
            loc = get_new_coords(loc, ydist, NORTH)
            loc = get_new_coords(loc, xdist / 2, WEST)

            ring += 1

    return results
```

**Comment by Xcelled** [comment]
This scan pattern is by design, see https://github.com/PokemonGoMap/PokemonGo-Map/commit/a9203ed0f65804fcd3950598546ec3a4e9bb5464.

**Comment by MungeParty** [comment]
To be clear, is the only constraint that each consecutive spot is no more than one scan spot away? The furthest this gets is a gap of one extra step when it starts a new ring, but that could be eliminated. 

Aside, my understanding is that when scanning with multiple accounts, individual accounts aren't scanning consecutive points anyway. Is that not right?

**Comment by Xcelled** [comment]
The spiral method also includes a huge teleport when the ring restarts.

Different queues for different workers (consecutive points w/ multiple accounts) is in the works, as the comments on that pull request shows. As they also say, the pokeball scan type is part of the move towards such a system.

The merits of spiral vs pokeball were explored in the comments on the pull request, and it was decided that pokeball was far superior, to the point of making it a default (and the only option).

**Comment by MungeParty** [comment]
Very clear. Thank you!
