### ISSUE TITLE
[Feature Request] Blacklist for parsing certain pokemon into DB

### ISSUE THREAD

**Issue by twoopi** [PokemonGoMap/PokemonGo-Map#1257]
## Expected Behavior

I use spawnpoint scanning to sweep a large area, it'd be great to be able to cut out around 50% of parses by ignoring the ultra common junk.

## Possible Solution

Add in a config option to list pokemon IDs to ignore when scanning

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Python 2.7):
* Operating System and version (desktop or mobile):

**Comment by CtrlAltDefeat94** [comment]
feathub

**Comment by twoopi** [comment]
Not anymore. They changed the readme a while back to not use feathub
