### ISSUE TITLE
[Error] Installation of requirements

### ISSUE THREAD

**Issue by petemat** [PokemonGoMap/PokemonGo-Map#126]
Hi guys, 

i am getting the following error while installing the requirements:

![image](https://cloud.githubusercontent.com/assets/20903996/17478097/c3a211fc-5d69-11e6-913a-dfd16edb7183.png)

Could you help me?

Thanks

**Comment by srotators** [comment]
It already tells you what to do - install 'Microsoft Visual C++ 9.0' from the given link

**Comment by petemat** [comment]
Thanks, i am blind. But needed to search for the MV C++ Compiler. Link is not working
