### ISSUE TITLE
Icon source

### ISSUE THREAD

**Issue by seikur0** [PokemonGoMap/PokemonGo-Map#1261]
Hey,
I'd like to know, where the standard icons come from.

I want to include them as option for my map,  (well I already did just now),
but they're all 65x65 pixels standard size and they look pretty rendered. My map uses 64x64 icons and ideally I'd want them in that size, since some pokemon had some pixel rows cut off from their beautiful icon bodies :(

**Comment by justsomedudeonthenet** [comment]
Please ask questions on our discord #help channel.

**Comment by seikur0** [comment]
I asked in that channel and NGPriest@NGPriest.com couldn't help me. And it's really not some support question, only few people would even know it.
