### ISSUE TITLE
Pokemon Go Map updated to 3.2 

### ISSUE THREAD

**Issue by Bear007** [PokemonGoMap/PokemonGo-Map#1269]
Pokemon Go Map 3.2 updated, it will be great that you can provide the show iv modification for 3.2version.

and also, i would like to ask without showing iv, is that any script is showing the Skills also?

thanks for you help.
![image](https://cloud.githubusercontent.com/assets/22134477/18419572/77098b26-7890-11e6-80ea-39f6c86f5ff3.jpg)

**Comment by Spiritvn** [comment]
IVs & Skill: https://github.com/PokemonGoMap/PokemonGo-Map/pull/1239

Not merged yet, you can try to use his repos
