### ISSUE TITLE
[BUG]Cannot scan for short-term pokemon

### ISSUE THREAD

**Issue by comcaptain** [PokemonGoMap/PokemonGo-Map#1275]
## Expected Behavior

Map should be able to display short-term pokemon(pokemon that will disappear within a short period(e.g. 2 minutes, 3 minutes)after it firstly appears).

## Current Behavior
But it's not showing these short-term pokemons. I'll show you how to reproduce in below section.

## Possible Solution
Not sure... I ever tried option `-msl 0` and `-msl 1` but neither of them works.

## Steps to Reproduce (for bugs)
1. Start a pokemon map server with 6 accounts, 3 steps and location `35.711901, 139.770569`. According to calculation result of [https://github.com/Cor3Zer0/Map-Calculator](Cor3Zer0’s Map Calculator), after a pokemon appears, it should display on map within 30 seconds.

2. Download a pokemon map app `P-GO` from APP store. Open it, then click the right-top button `地図ジャンプ`, in the first input box, type `不忍池`, then click OK.

3. Wait for a while, you'll see short-term Dratini in `P-GO` while cannot see it in `PokemonGoMap`

## Context
I ever tried another pokemon map project: [https://github.com/favll/pogom](pogom). Unluckily, it also does not work.

## Your Environment
* Version used: Both 3.2.0 and 3.1.0 do not work
* Environment name and version (e.g. Python 2.7): Python 2.7
* Operating System and version (desktop or mobile): I run this map in centos 7 and using it in Chrome under win10

**Comment by Spiritvn** [comment]
Short term pokemon ~ Lured Pokemon, you can try this PR: https://github.com/PokemonGoMap/PokemonGo-Map/pull/1079

**Comment by JZ6** [comment]
Cannot provide help with other apps
