### ISSUE TITLE
requirements.txt --upgrade | Flask-CacheBust.git is not upgradeable anymore

### ISSUE THREAD

**Issue by Supsuop** [PokemonGoMap/PokemonGo-Map#1279]
## Expected Behavior
Requirement already up-to-date:

## Current Behavior
```
Collecting flask_cachebust from git+https://github.com/maddhatter/Flask-CacheBust.git@38d940cc4f18b5fcb5687746294e0360640a107e#egg=flask_cachebust (from -r requirements.txt (line 25))
  Cloning https://github.com/maddhatter/Flask-CacheBust.git (to 38d940cc4f18b5fcb5687746294e0360640a107e) to /tmp/pip-build-VTfgnO/flask-cachebust
  Could not find a tag or branch '38d940cc4f18b5fcb5687746294e0360640a107e', assuming commit.
```

## Steps to Reproduce (for bugs)
git pull
sudo -H pip install -r requirements.txt --upgrade

**Comment by Xcelled** [comment]
This... is not an error? That's an informational message telling you that it's checking out commit `38d940cc4f18b5fcb5687746294e0360640a107e`, as opposed to a branch or a tag. This is OK and expected. Unless it's actually saying "error" somewhere you're ok, and this can be closed.

**Comment by FrostTheFox** [comment]
non-error
