### ISSUE TITLE
So i got mine working on digitalcloud but

### ISSUE THREAD

**Issue by phr34k0** [PokemonGoMap/PokemonGo-Map#128]
Is the workers part done? Can't wait for this https://pgm.readthedocs.io/en/develop/extras/workers.html

Noticed the pokemon scans are slow even if it was set to 0.1 . Getting multiple workers might speed that up :)

**Comment by marauder37** [comment]
Done ages ago, that page is old, read the docs for tools/beehive or multiple accounts per worker

For more installation or configuration help please visit https://discord.gg/nXyMej6 . Github issues are only for issues/bugs in the code. Thanks!
