### ISSUE TITLE
Problem viewing map on some Android devices

### ISSUE THREAD

**Issue by ewigg** [PokemonGoMap/PokemonGo-Map#1280]
I have the latest build of the map and I can not view it on some Android devices. 

Dosent work at all on Nexus 6P with Android 7. Tried Chrome, Firefox and Opera. Load 1 out of 100 or so refreshes.

Have tried on a Sony Z3 and it dosent work on any browser.

But it works on a Samsung Galaxy S6 and the pre installed browser.

And on iPhone it works great.

**Comment by jorgebsa** [comment]
That's weird, I'm using a Nexus 6P as well and am able to use the map on Chrome without a problem. It's just a bit slower, but that's because I'm accessing it via ngrok

**Comment by ewigg** [comment]
Solved it. My fault.

I used to comment out things in the map.html I dont want to show, toggles. But I the new updates it breaks the map for some browsers to comment out "Search" and "Change location". 

Instead of comment out these parts you use 

python runserver.py -nsc -fl

Im a bit behind with the new command line options.
