### ISSUE TITLE
Problem with AUTH_SERVICE

### ISSUE THREAD

**Issue by Borys74** [PokemonGoMap/PokemonGo-Map#1284]
Today I installed the map again according to the documentation. When I use google accounts stored in the _config.ini_ file, example:

`auth-service: google`
`username: [user1,user2,user3]`
`password: [pass1,pass2,pass3]`

and run the map command:

`python runserver.py -ss -l "50.000000, 19.000000" -st 20`

map works correctly. Each account has been successfully logged. But…

When I use the google accounts stored in the file _accounts.csv_, example:

`google.user1,pass1`
`google,user2,pass2`
`google,user3,pass3`

and run the map command:

`python runserver.py -ac accounts.csv -ss -l "50.000000, 19.000000" -st 20`

displays an error:

`runserver.py: Error parsing CSV file on line 1. We found 3 fields, so your input should have looked like '<ptc/gmail>,<username>,<password>'`
`But you gave us 'google,user1,pass1', your method was not ptc or gmail instead we got 'google'!`

When I change the setting from "google" on "gmail" and run the map, none of the google accounts can not be loaded. Displays an error:

`Failed to login to Pokemon Go with accounts user1@gmail.com.`
(...)

All accounts are active and yesterday (on the previous installation) everything worked properly. The problem appeared today on the new map installation.

----------
Sorry for my English. I do not know English well and used a translator.

**Comment by HypeZ85** [comment]
you wrote google instead gmail.

**Comment by ChipWolf** [comment]
@HypeZ85 #1283

**Comment by FrostTheFox** [comment]
corrected by 1283
