### ISSUE TITLE
[Feature Request] Show level of gyms on map

### ISSUE THREAD

**Issue by SoonDead** [PokemonGoMap/PokemonGo-Map#1292]
Would be very useful on a map overview.

![gymnumbers](https://cloud.githubusercontent.com/assets/988167/18463444/7666ff78-798a-11e6-8c88-af792c8aa555.png)

The team logos don't provide much information anyway.

I have darkened the yellow a bit as it was hardly readable, but now it looks like dried snot.

**Comment by maddhatter** [comment]
See #782

**Comment by SoonDead** [comment]
@maddhatter ok I should have searched more, this is a duplicate then.
