### ISSUE TITLE
Exception when doing "pip install -r requirements.txt"

### ISSUE THREAD

**Issue by SkyJimmy7** [PokemonGoMap/PokemonGo-Map#1298]
Hello guys, I´m new here. I tried to install PokemonGo-Map several times but I keep getting the same error.

When I go to my folder: https://gyazo.com/b469c3f7d5bae7d5da64581fdfbfbf65

I click on the cmd from folder and type the command (following the Basic Installation instructions) I type "pip install -r requirements.txt". 

Then I get this error: https://gyazo.com/9a0edc518c54a71e2822b272ace16813

People in Discord have suggested me other commands such as forcing reinstall or pip install --upgrade setuptools but I keep getting the same error with all of them.

Phyton is installed and working, followed perfectly all steps before, Phyton added to PATH, the \ was removed, etc... I´m using Windows 10.

Any help? This error keeps getting me away from studying all the spawns in my zone, something I´ve been dreaming on doing for a lot of time...

**Comment by shadi1989** [comment]
Use the Discord #help for help. do not use github.

**Comment by SkyJimmy7** [comment]
But... I tried and people in Discord ignored me, or couldn´t help. I need a solution...

**Comment by shadi1989** [comment]
try again cause ppl want to help but you need to read it :)

**Comment by SkyJimmy7** [comment]
Is there any other place where I can ask for help? It´s a bit confusing there with all the people asking

**Comment by FrostTheFox** [comment]
resolved in discord
