### ISSUE TITLE
Installation issues on Node.JS Step

### ISSUE THREAD

**Issue by Crazy-Clown** [PokemonGoMap/PokemonGo-Map#130]
Following Instructions:  https://pgm.readthedocs.io/en/develop/basic-install/windows.html

Step 6 below screenshot of CMD window:

- Install node.js. That will install the npm command. -[Node.js 6.3.1] (https://nodejs.org/dist/v6.3.1/node-v6.3.1-x64.msi)
- Open an admin command prompt and type npm install -g grunt-cli . This installs Grunt’s command line interface (CLI) globally.
- Once grunt is installed, run it by typing npm install. This will automatically run the grunt build command.

I am receiving the error:

C:\Users\Administrator>npm install
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\Administrator\package.json'
npm WARN Administrator No description
npm WARN Administrator No repository field.
npm WARN Administrator No README data
npm WARN Administrator No license field.

Any help would be appreciated.

Thanks.

**Comment by Infernoman** [comment]
try running npm install in the root directory of PokemonGo-Map instead of C:\Users\Administrator

**Comment by Crazy-Clown** [comment]
Thank you, just did that and it is now running.
