### ISSUE TITLE
Merge Multiple Maps

### ISSUE THREAD

**Issue by weizh888** [PokemonGoMap/PokemonGo-Map#1300]
This is not critical, but it would be great to solve it.
I am running multiple scanners in multiple terminals (since I want to scan several locations). Several ports are used to show the maps, is there a way to use a same port, or merge multiple maps into one map?
I might miss some same issue posted before. If you find, you can refer to it here. Thanks.

**Comment by jossie9** [comment]
Use the first scanner like you're using it now
Every other scanner u start in an other terminal window, add `-ns` to the code. -ns makes it use the same server and port as the first scanner.

I hope this answers your question ?

**Comment by FrostTheFox** [comment]
Mhm, ns mode will start the searcher but not the webserver. If you run them all to the same database, the one webserver instance will display the results from all of them.

**Comment by weizh888** [comment]
@FrostTheFox Would you mind to tell where I can modify to allow saving to the same database from multiple programs (in multiple terminals)? Thanks.

**Comment by aguita** [comment]
@weizh888 If you are using SQLite, it does that automatically if you're running from same location.  If you're using something like mySQL, then put in the user/pass/host/port for each call that you make.   Further discussion on this should be moved to the discord channel, and I'd be happy to walk you through getting it all set up.
