### ISSUE TITLE
[BUG] Exception in search_worker when use socks5 proxy 

### ISSUE THREAD

**Issue by YangSkyL** [PokemonGoMap/PokemonGo-Map#1308]
## Current Behavior

When I try to use Sock5 proxy, it passes proxy check, but when it try to login with proxy, it raise a exception:  TypeError: set_authentication() got an unexpected keyword argument 'proxy_config'

full trackback:
2016-09-15 09:18:38,331 [ search-worker-3][        search][   ERROR] Exception in search_worker: set_authentication() got an unexpected keyword argument 'proxy_config'
Traceback (most recent call last):
  File "/home/pi/PokemonGo-Map/pogom/search.py", line 580, in search_worker_thread
    check_login(args, account, api, step_location)
  File "/home/pi/PokemonGo-Map/pogom/search.py", line 683, in check_login
    api.set_authentication(provider=account['auth_service'], username=account['username'], password=account['password'], proxy_config={'http': account['proxy'], 'https': account['proxy']})
TypeError: set_authentication() got an unexpected keyword argument 'proxy_config'

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used: latest one, I am using git one, not release one
* Environment name and version (e.g. Python 2.7): Python 2.7
* Operating System and version (desktop or mobile): Desktop, Raspbian

**Comment by Badiboy** [comment]
Hi. socks5 proxy are working...
1. Could you plese provide the syntax you use for your proxy (you can replace numbers with xxx.
2. Current search.py in development branch have 680 lines in total, but your trace shows error in line 683. Please, clarify what search.py are you using.

**Comment by YangSkyL** [comment]
1.My proxy: socks5://xxxx:yyyy@zzzz:cccc where xxxx is username, yyyy is password, zzzz is socks5 proxy adress, cccc is port

2. well, I have modified search.py a bit so i can change search steps on UI interface just like change the search location(I want to constribute but I don't know how), but I didn't modified any code about login, proxy or set_authentication() methode. line 680 in my search.py is equals to line 598 in search.py in development branch.

Here is my search.py
[search.zip](https://github.com/PokemonGoMap/PokemonGo-Map/files/475502/search.zip)

**Comment by Badiboy** [comment]
Hmm... Seems something wrong with your pgoapi. But friendly speaking I don't know how you can find this. If you find where pip puts this:
git+https://github.com/PokemonGoMap/pgoapi.git#egg=pgoapi
Take a look there in auth.py for set_authentication function, if there are enough parameters?

**Comment by YangSkyL** [comment]
@Badiboy I have solved the probleem. thank you, set_authentication function is in pgoapi.py.

I have upgrade pgoapi and now I can use socks5 proxy.

**Comment by Badiboy** [comment]
Fine :)
