### ISSUE TITLE
[QUESTION] Do we still need to keep our scanners off?

### ISSUE THREAD

**Issue by daproject85** [PokemonGoMap/PokemonGo-Map#1315]
on the discord we were instructed to keep our scanners off due to possible ban because the new code has not been reviewed. Is it safe to scan now?

**Comment by FrostTheFox** [comment]
You still should keep scanners off. The new API stuff has not been completely REd yet.

**Comment by 3Trace** [comment]
Just use an account you don't care if it get's banned. I haven't stopped and I'm fine. Won't sweat if it happens tho.
