### ISSUE TITLE
A few words of thanks.

### ISSUE THREAD

**Issue by Sydcomebak** [PokemonGoMap/PokemonGo-Map#1317]
This will probably get deleted, but I just wanted to say that I'm not a Python guy, but I appreciate all the effort you guys are putting into this.  Through your code and a couple of tutorials, I have my PC running 7 different step4 accounts simultaneously having used the beehive calculator and using the account creator.

You guys rock.  Thank you for making my wife and my Pokemon hunting experiences together that much better!  Can't wait to see what new features you guys have in store.  I'm really looking forward to an IV filter being implemented.

Thanks again to everyone who contributes from the head coders to the bug reporters.

**Comment by jccwright** [comment]
Seconded... I am not a python guy either. I am a decent programmer and if
anyone needs a code bitch (someone to at least help with a framework or
assist with some mundane aspect) please let me know.

You all have totally amazed me with your talent, wit, insight, and
persistence.

Thank you all for everything you have done.

I know I would be leaving someone out if I tried to thank all the
contributors so just know you are all included but I want to say a special
thanks to @ThunderFox as I have seen him also managing the discord channel
as well as his work on the dev branch. Also @Balthamel and his work
managing the project as well. you guys are rock stars.

Much love!

**Comment by FrostTheFox** [comment]
Much appreciated :) I'm trying my best to manage discord/github since lots of our original team has left, and a few other individuals have been helping me decide what PRs are best to merge and what needs improved.

**Comment by jus10g** [comment]
Plus 1 here.  Thanks for making a tool that makes this game fun again!  And for your patience and time putting together tutorials for us python noobs.

**Comment by FrostTheFox** [comment]
Closing this for now, just to help with keeping the issues down, but feel free to leave further comments in the discord feedback channel, or you can even tweet at me or whatever :)

**Comment by FrostTheFox** [comment]
Trust me, we appreciate it :)
