### ISSUE TITLE
Bug? Pokemon showing in CMD/Phyton - not in map

### ISSUE THREAD

**Issue by Aleeeeeeeex** [PokemonGoMap/PokemonGo-Map#1319]
Using MySQL, some pokemon is showing location in CMD window with time and coordinates, but not on the map. 

Does not apply to all pokemon, just a random selection.

**Comment by beccasafan** [comment]
Please hop in the Discord #help channel, this will be easier to resolve there. If an issue is found, we can reopen this and better document the symptoms/cause/resolution.
