### ISSUE TITLE
nginx proxy_pass css/js include not working

### ISSUE THREAD

**Issue by Zerotask** [PokemonGoMap/PokemonGo-Map#132]
I tried to map port 5000 to /go as it described here: https://pgm.readthedocs.io/en/develop/extras/nginx.html

But I got a bunch of 404s of the css and js files. Is there a way to load them without adding the port in the map.html?

**Comment by marumari** [comment]
If it's running under it's own subdomain, you can do what I do and set the location to `/` instead of `/go/`; that definitely works, although that's not the intent of the documentation.

**Comment by Zerotask** [comment]
No, I don't run it on a subdomain.

**Comment by marauder37** [comment]
I bet you wrote `/go` instead of `/go/` like the example has or screwed up something else backslash related

For more installation or configuration help please visit https://discord.gg/nXyMej6 . Github issues are only for issues/bugs in the code. Thanks!
