### ISSUE TITLE
Database cleaner 

### ISSUE THREAD

**Issue by xslayserx** [PokemonGoMap/PokemonGo-Map#1328]
Database cleaner causes the map to stop working.

After some hours the map stops scanning because python does nothing but clearing the database and i dont know why.

**Comment by ottowayne** [comment]
Are you sure that it's caused by the database cleaner or is the cleaner just the only thing running anymore after a few hours.

**Comment by JerryCoke** [comment]
i have the same Problem :( i start is with "--disbale-cleaner"
but only a workarround
