### ISSUE TITLE
Oops! Something went wrong.

### ISSUE THREAD

**Issue by Placeto303** [PokemonGoMap/PokemonGo-Map#133]
Hello,

I tried to install a second instance of PokemonGo Map on the same server but now, on both web interfaces I've this error "Oops! Something went wrong.". The API is well configured with two separated accounts an API key.

And now I can't fix this issue even with one instance.

Please help !
Thanks

**Comment by marauder37** [comment]
For installation or configuration help please visit https://discord.gg/nXyMej6 . Github issues are only for issues/bugs in the code. Thanks!
