### ISSUE TITLE
Invalid response at xxxx,xxxx (location) abandoning location

### ISSUE THREAD

**Issue by galaxy9999** [PokemonGoMap/PokemonGo-Map#1330]
I run 7 bat files scanning 7 different locations using spawn point scan/poke alarm. I saw scanning at a few location stopped working after a while. the message I saw is "invalid response at xxxxx,xxxx, abandoning location. I was able to close the command window and re-run it. It starts working again. I am using 3.2.0 map and have not updated to Mysql database (database is locked error all over the place) I wonder if that is the problem.

Additional question: Since I am a noob on technical stuff. I cannot quite understand mySQL tutorial on wiki page, especially:
**
One this command prompt screen you’ll want to enter:

CREATE DATABASE pokemongomapdb;
CREATE USER 'pogomapuser'@'localhost' IDENTIFIED BY 'password';
GRANT ALL PRIVILEGES ON pokemongomapdb . * TO 'pogomapuser'@'localhost';
exit 
**
All the first three lines supposed to be enter in one line or they are supposed to be 3 lines and enter in between. 

Thank you very much!
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Python 2.7):
* Operating System and version (desktop or mobile):

**Comment by FrostTheFox** [comment]
3 lines enter between, and for the invalid response at location error, that's normal to happen occasionally.
