### ISSUE TITLE
How can I use private proxy?

### ISSUE THREAD

**Issue by trieuking** [PokemonGoMap/PokemonGo-Map#1334]
## Expected Behavior

It must work with private proxy.
## Current Behavior

I have private proxy included IP, port, username, password. But I can't setup it to config file to make server start. 
I was setting on config.ini as 
proxy:http://username:password@ip:port   
It got error "Failed to connect to proxy http://username:password@ip:port
Proxy was configured but no working proxies was found! We are aborting!"
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Python 2.7):
* Operating System and version (desktop or mobile):

**Comment by MureedSultan** [comment]
Are you sure you've white listed your sever ip with your proxy provider?

**Comment by trieuking** [comment]
I already add server IP to white list with my proxy provider. My setting in config.ini is correct?
gmaps-key:xxxxxxxxxxxxxx             # your Google Maps API key
proxy:http://username:password@ip:port                 # Proxy URL e.g. socks5://127.0.0.1:9050 or a list of proxies e.g. [socks5://127.0.0.1:9050,socks5://127.0.0.1:9050]
#proxy-timeout:         # Timeout before proceeding with next proxy while checking if the proxy works, (default 5)
#proxy-display:         # Used with -ps, full = display complete proxy address. Index = displays just the index for that proxy (default index)
#webhook:               # webhook URL (including http://)
#webhook-updates-only:  # only send updates to webhooks, (excludes gyms & non-lured pokéstops)

**Comment by ChilliHam** [comment]
You should only have ip:port when using your proxy.
