### ISSUE TITLE
Heat Map is not working

### ISSUE THREAD

**Issue by gatomiaurex** [PokemonGoMap/PokemonGo-Map#1342]
Can't access the heat map feature of the map.

## Expected Behavior

Open Map
Click on Full Stats
Click on a Location History
Heatmap should appear

## Current Behavior

Open Map
Click on Full Stats
Click on a Location History
A window with the map but heat map does not appear, this appears on the cmd window

> 2016-09-19 19:18:08,729 [      MainThread][           app][   ERROR] Exception on /raw_data [GET]                                                               Traceback (most recent call last):                                                File "C:\Python27\lib\site-packages\flask\app.py", line 1988, in wsgi_app         response = self.full_dispatch_request()                                       File "C:\Python27\lib\site-packages\flask\app.py", line 1641, in full_dispatch_request                                                                            rv = self.handle_user_exception(e)                                            File "C:\Python27\lib\site-packages\flask\app.py", line 1544, in handle_user_exception                                                                            reraise(exc_type, exc_value, tb)                                              File "C:\Python27\lib\site-packages\flask\app.py", line 1639, in full_dispatch_request                                                                            rv = self.dispatch_request()                                                  File "C:\Python27\lib\site-packages\flask\app.py", line 1625, in dispatch_request                                                                                 return self.view_functions[rule.endpoint](**req.view_args)                    File "C:\PokemonGo-Map-master\pogom\app.py", line 115, in raw_data                request.args.get('last', type=float), selected_duration)                    TypeError: get_appearances() takes exactly 3 arguments (4 given)                

## Steps to Reproduce (for bugs)

Open Map
Click on Full Stats
Click on a Location History

## Context

I can't see where pokemons have previously spawned.

## Your Environment
* Version used: v3.1.0
* Environment name and version: Python 2.7
* Operating System and version (desktop or mobile): Windows 7 / Android Marshmallow

**Comment by FrostTheFox** [comment]
Please update to the latest release.
