### ISSUE TITLE
Position Locating Does not work

### ISSUE THREAD

**Issue by JerryCoke** [PokemonGoMap/PokemonGo-Map#1345]
I have made an Update to IOs 10 and now when i go on the map with safari and klick on My location (locatiing button right bottom) it start Blinking but thats all no position.

On my iPad on ios9 it works - on some android devices ,too but only Some :(

**Comment by mrEyo** [comment]
I believe that geolocation tracking stopped working in Chrome if you aren't using a secure connection. I think the change happened in the latest Chrome update for iOS.

**Comment by FrostTheFox** [comment]
I don't know since I haven't been paying attention to iOS 10, but it is possible as mentioned above that there is an SSL requirement now for location.

**Comment by Imoq** [comment]
It is. Location on non-SSL stopped working after upgrade to iOS 10. [It was bound to happen, anyway](https://developers.google.com/web/updates/2016/04/geolocation-on-secure-contexts-only?hl=en).

**Comment by JerryCoke** [comment]
Okay i can confirm it is the SSL Cert now it is working.
