### ISSUE TITLE
[FEATURE REQUEST] Automate Beehive scan mode

### ISSUE THREAD

**Issue by Supsuop** [PokemonGoMap/PokemonGo-Map#1347]
## Expected Behavior

would it be possible to change the scanning mode to beehive?

like this
https://camo.githubusercontent.com/d65ac33656b410549aadfc9975f2f1a779ae437c/687474703a2f2f693330342e70686f746f6275636b65742e636f6d2f616c62756d732f6e6e3138362f736f6c6563616a756e2f426565686976652532304578706c616e6174696f6e2e706e67

so each worker that we use get his own position and scans an entire radius.

Lets say we have 4 worker. The first worker is always on the spot of the scanning point (our location) and those other workers goes like in the picture to there own spots from 2 until 4 like in the picture.

The current scanning mode scans each location one by one with an new worker and Jump some area. 
My Idea is to avoid those jumps so that each worker has his own path to walk.

**Comment by Slivo-fr** [comment]
Well, it means the farest you are from the center, the slower it will complete the circle

**Comment by Supsuop** [comment]
Yes, but lets say i just use "-st 2" for each worker and i have 7 workers - so my second leap would completely be used. i would have about the same scan range like "-st 5".
so it would not be slower than before. The scanning points would just start at different spots.

**Comment by averylarry** [comment]
#1010

**Comment by Supsuop** [comment]
thats only good for 1 worker. whats about multiple workers? ...

**Comment by Janglinator** [comment]
Check out PR #1367.  Is this what you're looking for?

**Comment by Supsuop** [comment]
yes it is, thank you
