### ISSUE TITLE
Using multiple accounts per worker does not speed up scanning.

### ISSUE THREAD

**Issue by stekern** [PokemonGoMap/PokemonGo-Map#135]
## Expected Behavior

When increasing number of accounts per worker from 1 to e.g. 4, I would expect each worker to complete the scan 4 times faster (or at least much faster than using 1 account per worker).

## Current Behavior

Using multiple accounts per worker does not speed up scanning. When using 73 workers, I get similar results from using 1 account per worker vs. 4 accounts per worker.

*73 workers, 1 acc per worker, 6 steps*
![73 workers, 1 acc per worker, 6 steps](https://cloud.githubusercontent.com/assets/10640491/17479244/a5e051ee-5d71-11e6-9531-c78badff6a80.png)

*73 workers, 4 acc per worker, 6 steps*
![73 workers, 4 acc per worker, 6 steps](https://cloud.githubusercontent.com/assets/10640491/17479250/b4c79aaa-5d71-11e6-8e1f-28e66b4f44f0.png)

## Steps to Reproduce (for bugs)

1. Use multiple workers (I have replicated the behaviour running as little as 5 workers)
2. Use multiple accounts per worker

## Your Environment

I have replicated this behaviour in several environments, among them several Google Compute Engine instances running with 1-8 vCPUs. I get the same result every time.

Before the most recent API change, but after the 10s scan delay was introduced, I was able to run this exact setup with workers and accounts and I got no red or yellow spots on the map. This has led me to believe that a bottleneck has been introduced with the recent changes (maybe with some of the encryption libraries?).

**Comment by ELusiveLPFAN** [comment]
How you register and verified so many accounts?

**Comment by JZ6** [comment]
You are getting throttled by niantic, don't run something so big, or you might get ip banned.
Why would anyone need a map that big for themselves?

**Comment by stekern** [comment]
I'm running a map for the PGO community in my city. 

Are you saying that Niantic recently has implemented new throttling mechanisms? Because this exact same setup worked flawlessly right up until Niantic introduced the unknown6 API change.

**Comment by chintqm03** [comment]
login into all of the accounts and complete tutorial. Also there was a script some where to automatically do that im sure you can find it with a bit of googling. goodluck

**Comment by wenom64** [comment]
This is the script for approve Terms of Service - https://github.com/TachyonRSA/PoGoTos
