### ISSUE TITLE
Failed to download resource "sqlite"

### ISSUE THREAD

**Issue by inakigloo** [PokemonGoMap/PokemonGo-Map#1351]
I am having this error while installing:

==> Downloading https://www.sqlite.org/2016/sqlite-autoconf-3120100.tar.gz

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "sqlite"
Download failed: https://www.sqlite.org/2016/sqlite-autoconf-3120100.tar.gz

I am using OS X 10.12.

**Comment by FrostTheFox** [comment]
Where is curling sqlite coming into the equation?

**Comment by FrostTheFox** [comment]
Closing for now. Please reopen with explanation of where/why you're curling sqlite.
