### ISSUE TITLE
unrecognized arguments:  -l "23.194909,-73.183039"

### ISSUE THREAD

**Issue by gaurav8k** [PokemonGoMap/PokemonGo-Map#1352]
Error while running server: unrecognized arguments: -l 23.194909,-73.183039

**Comment by freakjam** [comment]
Properly use quotes:
-l '23.194909, 73.183039'

**Comment by gaurav8k** [comment]
I have used -l "23.194909, 73.183039". Not working and showing same error.

**Comment by jorgebsa** [comment]
needs a space between comma and longitude, use quotes as well
