### ISSUE TITLE
README.md should not recommend using jelastic

### ISSUE THREAD

**Issue by pasky** [PokemonGoMap/PokemonGo-Map#1354]
jelastic providers (at least the default one dogado) are banned by Niantic as documented e.g. in #971, but README is still recommending it by the way of offering a nice clickable deploy button. I think the button should be just removed so that users aren't confused.

**Comment by FrostTheFox** [comment]
Jelastic providers are not all banned first off, second off, just because there is a button for it doesn't mean that it is recommended. I do think that it should be marked as such, however, but not quite removed. I'll push a fix for it momentarily.
