### ISSUE TITLE
Code License

### ISSUE THREAD

**Issue by LogaRhythmus** [PokemonGoMap/PokemonGo-Map#1355]
Hey everyone, I do not know if I am right asking this question here. If its wrong then you can remove or move this issue. A friend of mine showed me a link of this https://gomap.at/.

 They use this map for several cities in Austria and Germany(not working for me atm) for everyone to use. They take donations for providing this. So I am curious about whether this kind of **usage of the code** is ok or not.

**Comment by Xcelled** [comment]
This project is licensed under GNU GPL 3.0. Here's a quick look at what it allows: http://choosealicense.com/licenses/gpl-3.0/

Notice that modification and commercialization are permitted. This means they're free to change the code (they have) and also to charge for it if they wish (they're not, exactly...). They do need to disclose their changes to the source if asked, though.

Bottom line: this kind of usage is OK.
