### ISSUE TITLE
Occasionally (about 1-2 times per day) I'm getting an error and then the workers stop getting data

### ISSUE THREAD

**Issue by foltincsaba** [PokemonGoMap/PokemonGo-Map#1356]
Occasionally (about 1-2 times per day) I'm getting an error on the screenshot and then the workers stop getting data

## Expected Behavior

Search should run without errors for a long time.

## Steps to Reproduce (for bugs)

1. Start search and wait a lot

## Context

![kepernyofoto 2016-09-21 - 6 05 32 pm](https://cloud.githubusercontent.com/assets/20778409/18719536/0949654e-8028-11e6-9ab9-c7539baa5543.png)

## Your Environment

* Version used: latest commit: 13th september, also ran pip install --upgrade -r requirements.txt on 18th september
* Environment name and version (e.g. Python 2.7):  Python 2.7.
* Operating System and version (desktop or mobile): OSX Sierra,

**Comment by FrostTheFox** [comment]
http://stackoverflow.com/questions/11931530/easy-install-pip-errno-8-nodename-nor-servname-provided-or-not-known

This is pythons way of saying "we don't know what that is.". It's likely a weird OS thing. Try using 127.0.0.1 instead of localhost.

**Comment by FrostTheFox** [comment]
Unless you're not using mysql, in which this is a weird error to be getting.

**Comment by FrostTheFox** [comment]
Closing this for now, please open again if issue persists after the above advice.

**Comment by foltincsaba** [comment]
ok. btw I'm using mysql
