### ISSUE TITLE
Status page showing workers that aren't suppose to be working?

### ISSUE THREAD

**Issue by ChilliHam** [PokemonGoMap/PokemonGo-Map#1357]
## Expected Behavior
To show which accounts are running, and if they have any errors.

## Current Behavior
I currently have my system set up to have 20 workers on each instance. Only 10 workers are suppose to be working at a time on one instance. I have it set to "-w 10" and a "account-search-interval:7200" and "account-rest-interval:5000"
For some reason when I check the process running from the command window, everything seems fine. 10 accounts running, and 10 spare accounts available. But when I look at the /status page, I see that more accounts are active.
For example, it will show me that I have 13 accounts running.

## Your Environment

* Version used:Latest Dev
* Environment name and version (e.g. Python 2.7):Python 2.7
* Operating System and version (desktop or mobile):Desktop-Chrome

**Comment by beccasafan** [comment]
Were all 13 actively scanning? It's possible that you had accounts put on hold and so additional accounts were swapped in. Or possibly you caught it when it was switching based on the search interval.

Please hop in the Discord #help channel, this will be easier to resolve there. If something is found, we can reopen this and document the cause/resolution.
