### ISSUE TITLE
Alternate Pokemon Sprites

### ISSUE THREAD

**Issue by moleeternal** [PokemonGoMap/PokemonGo-Map#136]
I have created an alternate sprite sheet for the application based on the Pokemon Shuffle sprites (Pokescanner used these as default). They are functioning properly on my map.  My problem is that I am terrible at coding and I only know how to replace the default sprites.  I would to to add them to the list of available sprites for folks.  So, the menu would read "Normal", "High-Res" and "Shuffle" under Style Settings>Icons.

I am attaching my sprite file.
![icons-large-sprite-shuffle](https://cloud.githubusercontent.com/assets/17334343/17479655/ad364488-5d41-11e6-9ae9-b7394000c6e0.png)

**Comment by JZ6** [comment]
great stuff! @invisiblek  this could also solve the copyright issues

**Comment by BillyWM** [comment]
@JZ6: They're from Pokemon Shuffle, so they're as infringing as the default set ;)

**Comment by skizotenigma** [comment]
This was actually easy to do... just don't know how to commit it...

**Comment by skizotenigma** [comment]
![image](https://cloud.githubusercontent.com/assets/9896601/17538834/223346e2-5e77-11e6-9a48-d5aa5eadef16.png)

**Comment by invisiblek** [comment]
yea, but you're gonna want to at the very least add an option for this. i prefer the current ones =P

**Comment by skizotenigma** [comment]
oh it is an option. 
![image](https://cloud.githubusercontent.com/assets/9896601/17538867/746a15ee-5e77-11e6-96f5-f1c97e7e4431.png)

**Comment by invisiblek** [comment]
win!

**Comment by moleeternal** [comment]
@skizotenigma Awesome!!!

**Comment by DeastinY** [comment]
Looks great !

**Comment by marumari** [comment]
Those are super cute, but I'd really like to see a creative commons sprite set.  Do any exist anywhere?

**Comment by BaIthamel** [comment]
For feature requests please migrate this to the new feature page
http://feathub.com/PokemonGoMap/PokemonGo-Map/
Thankyou!

**Comment by jaquer** [comment]
@skizotenigma: Can you post your modified files somewhere? I can try and help creating a PR for this.
