### ISSUE TITLE
[Feature Request] Split database into Live and Stats

### ISSUE THREAD

**Issue by Romfrosk** [PokemonGoMap/PokemonGo-Map#1360]
I know me and some with me are getting large databases and i would love to have split the database up in Active data (less than 1 hour old) and move all older data to a separate table.

This way loading the website would be faster.

**Comment by jtp10181** [comment]
I was just coming in here to see if anyone else reported something like this.

What if we archived historical spawnpoint data into a separate table and purged out old pokemon spawns? I would just use the data purge feature but I don't want to loose record of spawn points that I may not have scanned recently.

**Comment by beccasafan** [comment]
Closing as dupe of #1358.
