### ISSUE TITLE
Exception while downloading map

### ISSUE THREAD

**Issue by N0916** [PokemonGoMap/PokemonGo-Map#137]
## Current Behavior
Currently when trying to execute the "runserver.py" script with all options sufficiently in place an exception occurs, preventing Pokemon from being displayed. The server itself runs fine and the notable places can be found, login works sufficiently and I've also agreed to the TOS so they aren't issues.
I've posted on the subreddit since the "issues" wasn't initially available earlier today. The complete output of the command and issue can be seen here: http://pastebin.com/raw/qfNpseBD

## Steps to Reproduce (for bugs)
1. Install all requirements without errors.
2. Run the server script in debian 7 wheezy.
3. Exception occurs.

## Your Environment

* Version used: Latest develop
* Environment name and version (e.g. Python 2.7): Python 2.7
* Operating System and version (desktop or mobile): Linux Debian 7 Wheezy Distribution

**Comment by invisiblek** [comment]
https://github.com/PokemonGoMap/PokemonGo-Map/issues/65

**Comment by N0916** [comment]
The issue persisted after I checked #65 however if anyone else is experiencing this on "Debian 7 Wheezy" then the fix is as follows:
**First bring the current Wheezy up-to-date -**
`sudo apt-get update
sudo apt-get upgrade`
**Then do a backup, edit /etc/apt/sources.list so you replace "wheezy" with "jessie" -**
`sudo cp /etc/apt/sources.list /etc/apt/sources.list.WHEEZY
sudo vi /etc/apt/sources.list`
**Update the package list and install version 4.9 of GCC/G++ -**
`sudo apt-get update
sudo apt-get install gcc-4.9 g++-4.9`
**Then revert to the original package lists -**
`sudo cp /etc/apt/sources.list.WHEEZY /etc/apt/sources.list
sudo apt-get update`

Everything should now work.
