### ISSUE TITLE
[Feature Request] Save favorite pokemon on the server side and notify user though cloud

### ISSUE THREAD

**Issue by tsuncp** [PokemonGoMap/PokemonGo-Map#1371]
Server can notify user though apps notification ,(apns or gcm) which not required the user open app or browser in the background mode. save power and bandwidth.

**Comment by Darkknightz** [comment]
You mean something like webhooks and https://github.com/kvangent/PokeAlarm

**Comment by tsuncp** [comment]
umm. oh yes .. should be like this
