### ISSUE TITLE
flask exceptions thrown when running in only-server mode

### ISSUE THREAD

**Issue by jrallen7** [PokemonGoMap/PokemonGo-Map#1381]
## Expected Behavior
Previously had been running scanner as one process with 8 workers, also running web server (config 1), this configuration works well and I see no errors.

I then chose to separate the scanner and the web server into two processes, with one process running only server (no workers), and one process running only workers (no server) (config 2).

## Current Behavior

When I start the two processes, the worker process appears to work fine, but if I pull up the web page in a browser and hit refresh, Python exceptions are thrown in the screen where the server-only process is running

## Steps to Reproduce (for bugs)

This is the script I use to start the two processes (dummy location and usernames)
#/usr/bin/bash
screen -dmS pokemap bash
screen -S pokemap00 -X stuff "./runserver.py -l XX.01355,-YY.15725 -fl -os $(printf \\r)"
screen -dmS pokemap00 bash
screen -S pokemap00 -X stuff "./runserver.py -l XX.01355,-YY.15725 -fl -ns -j -st 10 -u worker -u worker00 -u worker01 -u worker02 -u worker03 -u worker04 -u worker05 -u worker06 $(printf \\r)"

This is a small snippet of what I see in the server-only process:
[pokeserverlog.txt](https://github.com/PokemonGoMap/PokemonGo-Map/files/491372/pokeserverlog.txt)

## Context
Trying to isolate the worker process from the web server process so that I can kill/restart worker processes without disturbing the web server process 

## Your Environment

* Version used: 70de53c
* Environment name and version (e.g. Python 2.7): Python 2.7
* Operating System and version (desktop or mobile): Ubuntu 16.04.1 on Macbook pro 2.2

**Comment by FrostTheFox** [comment]
iirc you need to increase --db-max_connections for this error.

**Comment by jrallen7** [comment]
What's the default value for that parameter?

**Comment by FrostTheFox** [comment]
5.

**Comment by jrallen7** [comment]
Thanks.  I increased it to 10 and so far, so good.
