### ISSUE TITLE
Unable to install prerequisites

### ISSUE THREAD

**Issue by alex117bdx** [PokemonGoMap/PokemonGo-Map#1384]
Hi,

Prerequisites install doesnt work, here the output

Collecting requests==2.10.0 (from -r requirements.txt (line 23))
  Using cached requests-2.10.0-py2.py3-none-any.whl
Collecting PySocks==1.5.6 (from -r requirements.txt (line 24))
  Using cached PySocks-1.5.6.tar.gz
Collecting flask_cachebust from git+https://github.com/maddhatter/Flask-CacheBust.git@38d940cc4f18b5fcb5687746294e0360640a107e#egg=flask_cachebust (from -r requirements.txt (line 25))
  Cloning https://github.com/maddhatter/Flask-CacheBust.git (to 38d940cc4f18b5fcb5687746294e0360640a107e) to c:\users\alexan~1\appdata\local\temp\2\pip-build-xj15ci\flask-cachebust
  Could not find a tag or branch '38d940cc4f18b5fcb5687746294e0360640a107e', assuming commit.
Collecting protobuf_to_dict==0.1.0 (from -r requirements.txt (line 26))
  Using cached protobuf-to-dict-0.1.0.tar.gz
Collecting cachetools==1.1.6 (from -r requirements.txt (line 27))
  Using cached cachetools-1.1.6-py2.py3-none-any.whl
Collecting future (from s2sphere==0.2.4->-r requirements.txt (line 12))
  Using cached future-0.15.2.tar.gz
Collecting pyproj (from LatLon==1.0.1->-r requirements.txt (line 16))
  Using cached pyproj-1.9.5.1.tar.gz
    Complete output from command python setup.py egg_info:
    nad2bin.c
    nad2bin.c(129) : warning C4244: '=' : conversion from 'double' to 'float', possible loss of data
    nad2bin.c(130) : warning C4244: '=' : conversion from 'double' to 'float', possible loss of data
    nad2bin.c(137) : warning C4244: '=' : conversion from 'double' to 'float', possible loss of data
    nad2bin.c(138) : warning C4244: '=' : conversion from 'double' to 'float', possible loss of data
    nad2bin.c(352) : warning C4244: '=' : conversion from 'double' to 'float', possible loss of data
    nad2bin.c(353) : warning C4244: '=' : conversion from 'double' to 'float', possible loss of data
    pj_malloc.c
    using bundled proj4..
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\alexan~1\appdata\local\temp\2\pip-build-xj15ci\pyproj\setup.py", line 74, in <module>
        cc.link_executable(objects, execname, extra_postargs = [ '/MANIFEST' ] if os.name == 'nt' else  None)
      File "c:\python27\lib\distutils\ccompiler.py", line 700, in link_executable
        debug, extra_preargs, extra_postargs, None, target_lang)
      File "c:\python27\lib\distutils\msvc9compiler.py", line 669, in link
        raise LinkError(msg)
    distutils.errors.LinkError: command 'C:\\Users\\alexandre\\AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0\\WinSDK\\Bin\\mt.exe' failed with exit status -1073741819

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in c:\users\alexan~1\appdata\local\temp\2\pip-build-xj15ci\pyproj\

## Steps to Reproduce (for bugs)
1. type "pip install -r requirements.txt"

**Comment by beccasafan** [comment]
You need to install the Visual C++ Compiler prerequisite.

https://pgm.readthedocs.io/en/develop/basic-install/windows.html

**Comment by alex117bdx** [comment]
Hi, thanks for the reply. Visual C++ compiler was installed. I finally figure out this error, by installing SDK https://www.microsoft.com/download/details.aspx?id=3138
