### ISSUE TITLE
[FEATURE REQUEST] possible integration with pogo++ map.

### ISSUE THREAD

**Issue by elPimps** [PokemonGoMap/PokemonGo-Map#1385]
Using pogo++ for a while and pokemongomap with 30+ workers, i was thinking how to inject into every worker a comunication with the pogo++ map database to see every pokemon scanned also into the pogo++ map.
It would be an awesome feature for the ppl using pogo++ and pokemongomap togheter!

**Comment by FrostTheFox** [comment]
This is probably something more for the poke ++ devs to add.
