### ISSUE TITLE
[Feature Request] Add the possibility to use multiple databases in '-os' mode

### ISSUE THREAD

**Issue by kevdotcom** [PokemonGoMap/PokemonGo-Map#1387]
This would open up a lot of new ways of community work, essentially giving us the ability to show the Pokemon of multiple crowdsourced (crowdscanned? ;)) databases on one single map without the need of database syncing scripts or opening up your main database to all scanning users.

**Comment by EvilLost** [comment]
@kevdotcom  you can currently setup a webhook listener and have the other scanners all hook to your listener, which writes into a single db for the -os instance

is that not functionally (almost) the same? 
Is there a specific reason multi-DB connections would be more beneficial?

**Comment by beccasafan** [comment]
Yeah, I think this should be the other way around. The server is already separated from the workers with `-os/-ns`. The simple configuration is to just have multiple local workers writing to that single database that `-os` reads from, but there's nothing that says it can only be that rather than a more complicated setup.

**Comment by kevdotcom** [comment]
@EvilLost How would I realize this exactly? I didn't see anything about it in the Documentation.

**Comment by boby360** [comment]
I'm really glad someone requested this. Iv been wondering if it was possible or not for quite awhile now. Having separate areas in different databases although wanting a overall map.

**Comment by sebastienvercammen** [comment]
Very old request, but closing now: db mirroring and webhooks do what you want to do, but in a much better way.
