### ISSUE TITLE
[Feature Request] Changelog

### ISSUE THREAD

**Issue by phil0079** [PokemonGoMap/PokemonGo-Map#1388]
## Expected Behavior
Could we implement a changelog? A changelog.md file that includes comments of all changes made and it kept updated as updates are made.

## Current Behavior
Right now, if I wait 5 days to do a pull, I have a difficult time trying to find out what has changed. I can see which files have changed in the git pull output, but no details as to what those changes did. If a file has changed more than once since my last pull, it's almost impossible to see anything other than the most recent change to the file.

## Possible Solution
Can we auto append issue # and comments to a changelog.md file? Might be messy, but it's a step above what we have right now and wouldn't require a lot of extra work to just automatically append the comments.

**Comment by springjools** [comment]
PR #1272 has like 200 comments, of which about 10 deal with the actual code. Would be more productive to include random verses from the bible :)

**Comment by phil0079** [comment]
Yeah, man, that's too much. Well, that sucks for the "automatic" part. The issue still stands that it would be very useful to have a changelog with a list of changes, it would just require more work than just appending descriptions. 
I came back after a week vacation, updated, and I had no idea that spawn point scanning had been implemented as a -ss argument instead of the manual method that existed before. I didn't notice until much later when I was reading about something unrelated on the documentation. :/ I'd like to take advantage of new features, but I don't know when they happen unless it's updated someplace and the documentation doesn't always keep up.

**Comment by primaxius** [comment]
Are you that stupid. Well dont answer that. `git log` or just look at the https://github.com/PokemonGoMap/PokemonGo-Map/commits/develop

**Comment by FrostTheFox** [comment]
Alright, Primax, calm down buddy :P but I don't see a changelog being a thing. Just looking at the commit log shouldn't take that long.

**Comment by phil0079** [comment]
That totally works for me. I was looking for something like that commit log but I could find it when I looked. That's enough for what I was wanting to do. I realize a changelog would be difficult to implement since there's a community of people working on this, unless it could be enabled automatically. We can close this out. Thanks!
