### ISSUE TITLE
More informations about a gym

### ISSUE THREAD

**Issue by slideup-benni** [PokemonGoMap/PokemonGo-Map#139]
## Expected Behavior
When click on gym, you see informations about all pokemons with level and the trainer

## Current Behavior
When click on gym, you only see informations about the arena level and the owner fraction

**Comment by SebCorbin** [comment]
Also it would nice to show if a slot is empty (calculation between prestige and number of pokemons in gym)

**Comment by Cronick** [comment]
@SebCorbin Already shows when a slot is empty with the Uncontested icon
(https://github.com/PokemonGoMap/PokemonGo-Map/blob/develop/static/forts/Uncontested.png)

**Comment by SebCorbin** [comment]
I mean when the gym is owned by your team, say Blue, if its prestige is full (or near ? I don't know) this opens a slot for another pokemon to be gym defender.

**Comment by BaIthamel** [comment]
For feature requests please migrate this to the new feature page
http://feathub.com/PokemonGoMap/PokemonGo-Map/
Thankyou!

**Comment by CoolCanuck** [comment]
@BaIthamel This request needs to be opened again. FeatHub is no longer used. Good riddance.
