### ISSUE TITLE
[Feature Request] Password to access the map

### ISSUE THREAD

**Issue by gatomiaurex** [PokemonGoMap/PokemonGo-Map#1392]
I have a map scanning my city, I gave my IP address to my friends so they could access it, the problem is that sometimes they show the map to other people and they copy the address and my PC ends up being accessed by 100+ people.

## Expected Behavior

Implementing a password option would be nice so people don't access other people's PC's without consent.

example:

1.- Give IP, port and password to friend
2.- they show the map to another person
3.- another person tries to access the map
4.- can't see it because no password and gives up

## Context

My PC is not that powerful to allow access to tons of people.

## Your Environment
* Version used: latest release
* Environment name and version (e.g. Python 2.7): Python 2.7
* Operating System and version (desktop or mobile): Windows 7, Android Marshmallow

**Comment by jorgebsa** [comment]
This type of code most likely won't happen, if you want password protection then you are better off setting up authentication through nginx or httpd, or whatever you are using to serve your server publicly

**Comment by gatomiaurex** [comment]
@jorgebsa 

I just run the workers and give the "http://publicip:port" address to my friends, I tried white listening the IP's but it doesn't seem to work.

**Comment by shadi1989** [comment]
Go use a "front-end"  with iframe to the map. im using a wordpress with user-managment in it and a lot of plugins to manage pages/groups/content

**Comment by gatomiaurex** [comment]
@shadi1989

Could you point me to a guide on how to do that? I do not posses the knowledge to do that.

**Comment by imadummy1** [comment]
@gatomiaurex did you try to `git gud`?

**Comment by gatomiaurex** [comment]
@imadummy1

._. I already did the iframe thing, now I only need to add a password

**Comment by imadummy1** [comment]
@gatomiaurex yes; to bring up the password menu for network configuration go to a command prompt and run `git gud`. It may ask you to install git itself first

**Comment by gatomiaurex** [comment]
@ imadummy1

I am dumb but I am not that dumb, I already did the iframe thing and the password.

Thanks to everybody.
