### ISSUE TITLE
Not enough users with write permission

### ISSUE THREAD

**Issue by Janglinator** [PokemonGoMap/PokemonGo-Map#1394]
I feel like a lot of great ideas/PR's are sitting around because we don't have enough *active* users that can merge pull requests.

I'm not asking for write access, please, for God's sake don't give it to me, because I'm not familiar enough with the project.

But it'd be nice if issues/pr's were addressed in a more organized and timely manner, rather than dying out.

**Comment by mdnpascual** [comment]
They're probably delaying PR's after they RE'd the new API

**Comment by FrostTheFox** [comment]
No, that's not the problem. Reviewing the PRs is what takes the time. They review them, and assign them to me for merge. They have write permission in the event I disappear for some reason.

Also, as mentioned above we're not merging too much because of API.

**Comment by FrostTheFox** [comment]
If it's a big feature, we're going to take more time to review/test.

**Comment by FrostTheFox** [comment]
Also, in case you haven't noticed, we made great work of the PR queue the other day.

**Comment by FrostTheFox** [comment]
Also, we're on limited resources. We have a PR chat open for people to discuss and get their PRs changed to our satisfaction in a more quicker manner.
