### ISSUE TITLE
[BUG] Heat Map Issue

### ISSUE THREAD

**Issue by roflinger** [PokemonGoMap/PokemonGo-Map#1400]
## Expected Behavior
Open Map
Click on Full Stats
Click on a Location History
Heatmap should appear

## Current Behavior

Open Map
Click on Full Stats
Click on a Location History
nothing happens

in console: 
statistics.min.js:5 Uncaught ReferenceError: noLabelsStyle is not defined

## Your Environment

win 10 
chrome Version 53.0.2785.116 m (64-bit)
AND 
IE 11
python 2.7
latest build of the map

**Comment by deirdresm** [comment]
Confirmed on Safari 10.0/Sierra, using Python 2.7.12 and up-to-date unmodified install.

**Comment by roflinger** [comment]
i just reinstalled the whole project
git clone
pip install..
npm install
npm run build

restart.. now it works again

**Comment by deirdresm** [comment]
*facepalm*

I missed that step earlier too, obviously. I didn't reinstall the project, but I apparently missed one of the npm steps. Works for me now, too.

**Comment by beccasafan** [comment]
`npm install` or `npm run build` is required after pulling in updated code.

(`npm install` also runs the build, so if you do `npm install`, you don't also need to do `npm run build`)
