### ISSUE TITLE
Getting notifications of pokemon when they despawn

### ISSUE THREAD

**Issue by SlasherKG** [PokemonGoMap/PokemonGo-Map#1401]
## Expected Behavior
Only get notifications when a Pokémon appears (or ones with longer spawn time are re-scanned).

## Current Behavior
Something in the last few merges has caused it to send 2 notifications when a Pokémon disappears.

## Possible Solution
Not sure which merge caused it.

## Steps to Reproduce (for bugs)
1. Pokémon on the notify list spawns.
2. Map sends notification properly.
3. Spawn time expires and 2 additional notifications are sent while the sprite disappears from the map.

## Context
Annoying but not breaking bug.

## Your Environment
Windows 10
Python 2.7
Latest develop pull

**Comment by irus99** [comment]
I get 6 notifications everything a pokemon on my notification list despawns :/

**Comment by Slivo-fr** [comment]
#1046 maybe ?

**Comment by DiscoTim** [comment]
#1303 when it merges will likely help with this. also check your client time and server time are correct.

**Comment by Darkknightz** [comment]
@SlasherKG #1303 merged, did this solve your issue?

**Comment by SlasherKG** [comment]
It appears to be fixed, thanks!
