### ISSUE TITLE
Change the way of -ss work

### ISSUE THREAD

**Issue by kamieniarz** [PokemonGoMap/PokemonGo-Map#1402]
I see that -ss works like normal scanning but instead of move on to next spawnpoint account waits for pokemon to show up. Wouldn't it be easier to sort out all spawnpoints by it's pokemon appearance and scan them one by one? Couse right now with my configuration (100accs, st 18, 1700 spawnpoints) it is much more efficient to use normal way of scanning (or --skip-empty) than -ss 

Or maybe I'm uninformed and there is a way to make it work like I described :D

**Comment by aldarund** [comment]
Um what? It scan spawnpoint at the time when the pokemon appears there. It obv cant scan before pokemon appear.

**Comment by aguita** [comment]
Look at the status page.  Are you ahead, or are you behind?  That will tell you how effective your -ss is.  IF they're always behind, add more workers.  If they're too far ahead, maybe reduce # of workers.   I'm running several st 16 areas and have no issue.  The workers get to the next spawn point, wait until it spawns and then scans.  The Pokemon usually show up within 10 seconds of spawning.    This is a far more effective method.

**Comment by pir2** [comment]
spawnpoint scanning should be used with st 1 (ONE).  If you set st 18, it's going to walk around in a circle on that one spawnpoint for 18 steps...

The point of ss is to scan the ONE step and move on ;)

**Comment by aldarund** [comment]
@pir2 dont write bullshit please.  Learn how it work before writing such nonsense. st in ss mode can be any and it just limit the scan area, it doesnt work like u desribed.

**Comment by pir2** [comment]
@aldarund apologies :) just reread the docs. the old ss was st 1 only.  you are right oh god like @aldarund 

thank you for your enlightenment :)

**Comment by kamieniarz** [comment]
I mean that my workesr can wait 200sec to scan spawnpoint instead of scanning next one that is ready to scan...

**Comment by aldarund** [comment]
that shouldnt happen. either u have not enough worker so queue fille dwith other points or the point is not ready

**Comment by averylarry** [comment]
@kamieniarz the scheduler hands out the locations to scan in the order of the time they spawn.  If you have a worker waiting 200s for a spawn, then there aren't any other spawnpoints active.  It is working as it should be.

**Comment by kamieniarz** [comment]
@averylarry that's weird couse most of spawnpoints had delay <15sec but I saw some new pokemons that had 5mins instead of over 14.... I asked about that on Discord and someone told me that to have maximum efficiency on map with 1700 spawnpoints I need to have 1700 workers instead of 100...

**Comment by aldarund** [comment]
1700 worker for 1700 spawn points?Lol. thats really stupid. enable status page and check if you are behind or not of queue.

**Comment by kamieniarz** [comment]
@aldarund all of workers busy. most of them over 150s ahead... but it's after 20mins of running. should I wait over an house to stabilize?

**Comment by aldarund** [comment]
if 150s ahead - all is fine.

**Comment by kamieniarz** [comment]
@aldarund ok then... Last question: what about double/triple spawnpoints? Are they re-scanned or pokemon shows up automaticly after first/second 15mins ?

**Comment by kamieniarz** [comment]
I'm nearly sure that double/triple spawnpoints are scanned only once. That's why my area -st 18 in normal scanning has around 300 pokemons but with -ss only 200-250.... It's not efficient at all!

**Comment by arnaudverniers** [comment]
@kamieniarz ; Can you help me? I wanted to use multiple account and i dunno how to do it. Can you briefly explain me? Thank you.

**Comment by aguita** [comment]
@arnaudverniers Please visit the Discord channel.  There are many there that can help you getting this set up.   It is a much more appropriate place to help you.

**Comment by Demokdawa** [comment]
@kamieniarz This is a glitch who exist since few days ! I have that too. I used 26 accs with 6K spawns before, and now i struggle to not be behing with 11K spawns and 130 accs.... ridiculous. Something has broke recently i think

**Comment by kamieniarz** [comment]
@Demokdawa good to know that I'm not alone couse no1 belives me... problem still exists for me. Tomorrow I'll try to reinstall everything and see if it worked as it should be couse efficiency is simply worse than in regular scanning...

**Comment by BaIthamel** [comment]
Right now non 15 minute spawns may be missed in all but their last 15 mins. This is know, a fix is in the works. I'm closing this as it's discussed in more detail elsewhere.
