### ISSUE TITLE
IV Percentage not exactly calculated

### ISSUE THREAD

**Issue by simonbuehler** [PokemonGoMap/PokemonGo-Map#1403]
running git of today and enabled IV Scanning i notice the IV percentage is a bit off and here i have a proove:

i have a  `Eevee 	621	12	14	12	82.00 %	level 21`
in pogomap the 12,14,12 are shown correct but the percentage was said to be 84,4%

who is wrong here , should it calculate to 82,18% or 84,4% ?

**Comment by joekeating87** [comment]
A perfect IV is 15/15/15 or 45/45 combined. your evvee is scoring a total 38/45 which is 84.44444%

**Comment by simonbuehler** [comment]
ok, makes sense, i'll close for now
