### ISSUE TITLE
Inoperative web page

### ISSUE THREAD

**Issue by Pietr** [PokemonGoMap/PokemonGo-Map#1404]
Hi!
I would like to report this broken site bot.
https://zapodaj.net/images/0cc89edce05ec.png
Starting command:
./runserver.py -u login -p pass -l Przemysl -H 185.xxx.xxx.xxx -P 5000 -k  AIzaSyBZ28eZtJxxxxxxxxxxxxxx

Console logs:
http://pastebin.com/PmsVLY7y

Sorry for my English.

**Comment by Becold** [comment]
Use this command (if necessary, use sudo) : 
`grunt build`

**Comment by Pietr** [comment]
Does not help.

**Comment by aguita** [comment]
@Pietr Does not appear to be broken.  While it is not finding a lot of pokemon, there are instances of it finding pokemon.   Without knowing more of the area, and what else is going on not much we can do.   

Right now, you should not be scanning.  See the discord page for more information and help.

2016-09-28 12:28:12,003 [ search-worker-0][        models][    INFO] Parsing found 1 pokemons, 62 pokestops, and 11 gyms
and
2016-09-28 12:26:50,361 [ search-worker-0][        models][    INFO] Parsing found 1 pokemons, 64 pokestops, and 9 gyms

**Comment by deirdresm** [comment]
Are you using any browser add-ons? If so, please try turning them all off then reloading the page.

**Comment by Becold** [comment]
Try to clear your cache. (Ctrl+F5)

**Comment by m3g4mInD** [comment]
#1375  Yeap is the same problem i have before, i have look when when go to download by git not all files are downloading.

**Comment by Pietr** [comment]
@deirdresm I use a lot of browsers. In each the same.
@Becold Does not help.
@m3g4mInD How do I download?

**Comment by BaIthamel** [comment]
This is not a support forum; please see [the discord #help channel](https://discord.gg/npVqkUn) for assistance.
