### ISSUE TITLE
 [Feature Request] Have workers randomly spin pokestops and catch pokemons to disguise themselves

### ISSUE THREAD

**Issue by revlisoft** [PokemonGoMap/PokemonGo-Map#1405]
Right now it's very obvious what the bot accounts are even with all the teleportation/beehive workarounds.  It is those accounts which have logged hundreds and thousands of miles without catching any (except for the 1st in the tutorial) and still level 1 or very low level.  

## Expected Behavior

Having a feature that tells the worker to randomly spin pokestops (to get pokeballs) and attempt to catch (if possible) a pokemon for 1 time on a very very low random rate would help make these accounts stand out a lot less. The spin rate and catch rate should be configurable.

## Current Behavior

Workers walk around in patterns for hundreds and thousands of miles without getting pokestops or attempting or caught any pokemon.

## Possible Solution

Status page should also show the details of each worker.  This is **NOT** meant to be used to power level a worker but to disguise it so it's not that obvious as a future ban target.  The rate can be something along of lines of every X minutes attempt to spin a pokestop and every x minutes attempt to catch a pokemon.

## Steps to Reproduce (for bugs)

1. See above

## Context

An attempt to disguise the workers aimlessly wandering around not actually doing anything.

## Your Environment

* Version used:
* Environment name and version (e.g. Python 2.7):
* Operating System and version (desktop or mobile):
N/A

**Comment by averylarry** [comment]
I don't even like the IV retrieval -- this is definitely way over the line for me.

**Comment by revlisoft** [comment]
The IV retrieval is nice but this solution is not meant to gather items or power level an account.  It's meant as a disguising feature so servers using this can continue to use it and provide folks the map functionality.

**Comment by BrownSlaughter** [comment]
That crosses the line of botting, way way over the line

**Comment by averylarry** [comment]
@revlisoft Sure, but then the next feature request will want to start leveling accounts and then the next feature request . . .  Slippery slope with no current evidence that it would reduce account bans.

Now if in the future it is determined that Niantic does actually use that information to ban accounts . . .

**Comment by FrostTheFox** [comment]
We had long discussions about encounters for the IV, that was something we had to talk about a *LOT.*

I really don't see this happening.

**Comment by revlisoft** [comment]
Fair points all around.  I would suggest putting a hard cap but with source code readily available I can easily see that being worked around.  It was just a suggestion as I'm sure the Niantic folks aren't dumb and I can only imagine after going after teleporting it seemed natural to go after thousands or more level 1 accounts with thousands and thousands of logged miles or very few pokemons.

**Comment by Goldclownfish** [comment]
My main account has over 800k logged almost 10k in pokestops an about 9k in caught Pokemon. Doesn't take a rocket scientist to do a database query an figure out the scanners have that many miles or more an no other stats period. Nobody would walk that far an catch one Pokemon. It is needed to an extent to hide them. Bad enough they don't walk randomly it's always in a pattern with that pattern never changing ever. Same speed there is nothing random about that.

**Comment by aguita** [comment]
Once Niantic has time to banning all the accounts used for scanning  Things like distance logged versus level is an easy indicator.  However, there are many other easy indicators that they'd use first to identify scanning accounts.   At this point in time, I don't see any of the developers as part of this project that would be willing to do this.

**Comment by Goldclownfish** [comment]
Perhaps only catching pidgeys, weedles, an rattata would acceptable an only stops that are in the direct path that is walked. I understand why they don't want this but it is an option for longevity. I just wouldn't put it in the release notes so for the most part the accounts just do it as part of normal operations. As most people would not have a clue as they never log into the scanners to look at them.

**Comment by averylarry** [comment]
I doubt Niantic will waste server resources by recording every past action for who-knows-how-long.  Short-term teleportation/speed bans are relatively easy.  You have to have a lot of data before you can mine the data for some of the types of information being talking about.  Sure there will be something to go on, but it'll be hard for Niantic to differentiate between an account that is only scanning vs. an account that I give my 3 year old so they can watch the pretty things on a phone without actually doing anything while I drive around town.

Regardless, this will come back in the future if it seems Niantic actually does something relevant.  If anyone still cares to do scanning.
