### ISSUE TITLE
Errors after last update

### ISSUE THREAD

**Issue by shudack** [PokemonGoMap/PokemonGo-Map#1409]
Hi,

I got this error when I start the bot:

http://pastebin.com/GpHCpeqQ

I use the commands:

sudo git pull
sudo -H pip install -r requirements.txt --upgrade
sudo npm install
sudo npm run build
sudo grunt build

Best regards,
Shudack

**Comment by BaIthamel** [comment]
This is not a support forum; please see [the discord #help channel](https://discord.gg/npVqkUn) for assistance.
