### ISSUE TITLE
Config/config.ini is always loaded even when another config file is specified

### ISSUE THREAD

**Issue by viliam-jobko** [PokemonGoMap/PokemonGo-Map#1413]
## Expected Behavior
`python runserver -cf config/config-CityName.ini` loads `config/config-CityName.ini`.

## Current Behavior
`python runserver -cf config/config-CityName.ini` loads both `config/config.ini` and `config/config-CityName.ini` causing some option being overwritten.

## Steps to Reproduce (for bugs)

1. create config/config.ini
2. create config/config-new.ini
3. run `python runserver -cf config/config-new.ini`
4. some settings of config-new.ini are overwritten by config.ini

## Context
I am trying to load only config files specified by me.

## Your Environment
* Version used:
* Environment name and version (e.g. Python 2.7): Python 2.7.12
* Operating System and version (desktop or mobile): Ubuntu 14.04

**Comment by Climbgunks** [comment]
Confirmed... and I think this fixes it...but I'll do some more testing, and submit a proper pull request.   Basically, we shouldn't load the default config file in the ArgParser creation..but we need to check for its existance or we'll get file not found errors in the add_argument call since the default can't be found if the file doesn't exist.   This fixes both those issues.

```
mummert@serenity:~/PokemonGo-Map/pogom$ git diff
diff --git a/pogom/utils.py b/pogom/utils.py
index cc27a15..81a9102 100755
--- a/pogom/utils.py
+++ b/pogom/utils.py
@@ -45,8 +45,10 @@ def memoize(function):
 def get_args():
     # fuck PEP8
     defaultconfigpath = os.getenv('POGOMAP_CONFIG', os.path.join(os.path.dirname(__file__), '../config/config.ini'))
-    parser = configargparse.ArgParser(default_config_files=[defaultconfigpath], auto_env_var_prefix='POGOMAP_')
-    parser.add_argument('-cf', '--config', is_config_file=True, help='Configuration file')
+    if not os.path.isfile(os.path.realpath(defaultconfigpath)):
+        defaultconfigpath = None
+    parser = configargparse.ArgParser(auto_env_var_prefix='POGOMAP_')
+    parser.add_argument('-cf', '--config', is_config_file=True, default=defaultconfigpath, help='Configuration file')
     parser.add_argument('-a', '--auth-service', type=str.lower, action='append', default=[],
                         help='Auth Services, either one for all accounts or one per account: ptc or google. Defaults all to ptc.')
     parser.add_argument('-u', '--username', action='append', default=[],
```

**Comment by FrostTheFox** [comment]
#1428
