### ISSUE TITLE
-ss not working properly

### ISSUE THREAD

**Issue by littledimmie** [PokemonGoMap/PokemonGo-Map#1414]
Hey Guys, i hope you can help me. I´m running an instance of Pokemon Go Map on my Computer, scanning my whole town with steplimit 17 and 20 Accounts and Spawnpointscanning. Everything was working fine. Every Pokemon was found 10-20 seconds after spawning, but yesterday night, Windows update decided to restart my computer and since then -ss seems to scan the spawnpoints too late. Before every notification was -14:4x time remaining and now it´s sometimes 08:xx remaining. Any idea, whats going on? Thanks

**Comment by simonbuehler** [comment]
logfiles (-vv) or it didn't happen

**Comment by littledimmie** [comment]
Nevermind. My systemtime was desynced...
