### ISSUE TITLE
Map crashing every 10 or 15 minutes

### ISSUE THREAD

**Issue by gatomiaurex** [PokemonGoMap/PokemonGo-Map#1418]
## Expected Behavior

* map should not break

## Current Behavior

after 10 or 15 minutes i start getting this error

> [2016-09-29 11:28:56,726] ERROR in app: Exception on /search_control [GET]      Traceback (most recent call last):                                                File "C:\Python27\lib\site-packages\flask\app.py", line 1988, in wsgi_app         response = self.full_dispatch_request()                                       File "C:\Python27\lib\site-packages\flask\app.py", line 1641, in full_dispatch_request                                                                            rv = self.handle_user_exception(e)                                            File "C:\Python27\lib\site-packages\flask\app.py", line 1544, in handle_user_exception                                                                            reraise(exc_type, exc_value, tb)                                              File "C:\Python27\lib\site-packages\flask\app.py", line 1637, in full_dispatch_request                                                                            rv = self.preprocess_request()                                                File "C:\Python27\lib\site-packages\flask\app.py", line 1837, in preprocess_request                                                                               rv = func()                                                                   File "C:\Python27\lib\site-packages\playhouse\flask_utils.py", line 165, in connect_db                                                                            self.database.connect()                                                       File "C:\Python27\lib\site-packages\peewee.py", line 3404, in connect             self.initialize_connection(self.__local.conn)                                 File "C:\Python27\lib\site-packages\peewee.py", line 3316, in __exit__            reraise(new_type, new_type(*exc_args), traceback)                             File "C:\Python27\lib\site-packages\peewee.py", line 3402, in connect             **self.connect_kwargs)                                                        File "C:\Python27\lib\site-packages\playhouse\pool.py", line 128, in _connect     conn = super(PooledDatabase, self)._connect(*args, **kwargs)                  File "C:\Python27\lib\site-packages\peewee.py", line 3929, in _connect            return mysql.connect(db=database, **conn_kwargs)                              File "C:\Python27\lib\site-packages\MySQLdb\__init__.py", line 81, in Connect     return Connection(*args, **kwargs)                                            File "C:\Python27\lib\site-packages\MySQLdb\connections.py", line 193, in __init__                                                                                super(Connection, self).__init__(*args, **kwargs2)                          OperationalError: (1040, 'Too many connections')                                2016-09-29 11:28:56,726 [      Thread-196][           app][   ERROR] Exception on /search_control [GET]                                                         Traceback (most recent call last):                                                File "C:\Python27\lib\site-packages\flask\app.py", line 1988, in wsgi_app         response = self.full_dispatch_request()                                       File "C:\Python27\lib\site-packages\flask\app.py", line 1641, in full_dispatch_request                                                                            rv = self.handle_user_exception(e)                                            File "C:\Python27\lib\site-packages\flask\app.py", line 1544, in handle_user_exception                                                                            reraise(exc_type, exc_value, tb)                                              File "C:\Python27\lib\site-packages\flask\app.py", line 1637, in full_dispatch_request                                                                            rv = self.preprocess_request()                                                File "C:\Python27\lib\site-packages\flask\app.py", line 1837, in preprocess_request                                                                               rv = func()                                                                   File "C:\Python27\lib\site-packages\playhouse\flask_utils.py", line 165, in connect_db                                                                            self.database.connect()                                                       File "C:\Python27\lib\site-packages\peewee.py", line 3404, in connect             self.initialize_connection(self.__local.conn)                                 File "C:\Python27\lib\site-packages\peewee.py", line 3316, in __exit__            reraise(new_type, new_type(*exc_args), traceback)                             File "C:\Python27\lib\site-packages\peewee.py", line 3402, in connect             **self.connect_kwargs)                                                        File "C:\Python27\lib\site-packages\playhouse\pool.py", line 128, in _connect     conn = super(PooledDatabase, self)._connect(*args, **kwargs)                  File "C:\Python27\lib\site-packages\peewee.py", line 3929, in _connect            return mysql.connect(db=database, **conn_kwargs)                              File "C:\Python27\lib\site-packages\MySQLdb\__init__.py", line 81, in Connect     return Connection(*args, **kwargs)                                            File "C:\Python27\lib\site-packages\MySQLdb\connections.py", line 193, in __init__                                                                                super(Connection, self).__init__(*args, **kwargs2)                          OperationalError: (1040, 'Too many connections')                                [2016-09-29 11:28:56,730] ERROR in app: Exception on /raw_data [GET]            Traceback (most recent call last):                                                File "C:\Python27\lib\site-packages\flask\app.py", line 1988, in wsgi_app         response = self.full_dispatch_request()                                       File "C:\Python27\lib\site-packages\flask\app.py", line 1641, in full_dispatch_request                                                                            rv = self.handle_user_exception(e)                                            File "C:\Python27\lib\site-packages\flask\app.py", line 1544, in handle_user_exception                                                                            reraise(exc_type, exc_value, tb)                                              File "C:\Python27\lib\site-packages\flask\app.py", line 1637, in full_dispatch_request                                                                            rv = self.preprocess_request()                                                File "C:\Python27\lib\site-packages\flask\app.py", line 1837, in preprocess_request                                                                               rv = func()                                                                   File "C:\Python27\lib\site-packages\playhouse\flask_utils.py", line 165, in connect_db                                                                            self.database.connect()                                                       File "C:\Python27\lib\site-packages\peewee.py", line 3404, in connect             self.initialize_connection(self.__local.conn)                                 File "C:\Python27\lib\site-packages\peewee.py", line 3316, in __exit__            reraise(new_type, new_type(*exc_args), traceback)                             File "C:\Python27\lib\site-packages\peewee.py", line 3402, in connect             **self.connect_kwargs)                                                        File "C:\Python27\lib\site-packages\playhouse\pool.py", line 128, in _connect     conn = super(PooledDatabase, self)._connect(*args, **kwargs)                  File "C:\Python27\lib\site-packages\peewee.py", line 3929, in _connect            return mysql.connect(db=database, **conn_kwargs)                              File "C:\Python27\lib\site-packages\MySQLdb\__init__.py", line 81, in Connect     return Connection(*args, **kwargs)                                            File "C:\Python27\lib\site-packages\MySQLdb\connections.py", line 193, in __init__                                                                                super(Connection, self).__init__(*args, **kwargs2)                          OperationalError: (1040, 'Too many connections')                                2016-09-29 11:28:56,730 [      Thread-197][           app][   ERROR] Exception on /raw_data [GET]                                                               Traceback (most recent call last):                                                File "C:\Python27\lib\site-packages\flask\app.py", line 1988, in wsgi_app         response = self.full_dispatch_request()                                       File "C:\Python27\lib\site-packages\flask\app.py", line 1641, in full_dispatch_request                                                                            rv = self.handle_user_exception(e)                                            File "C:\Python27\lib\site-packages\flask\app.py", line 1544, in handle_user_exception                                                                            reraise(exc_type, exc_value, tb)                                              File "C:\Python27\lib\site-packages\flask\app.py", line 1637, in full_dispatch_request                                                                            rv = self.preprocess_request()                                                File "C:\Python27\lib\site-packages\flask\app.py", line 1837, in preprocess_request                                                                               rv = func()                                                                   File "C:\Python27\lib\site-packages\playhouse\flask_utils.py", line 165, in connect_db                                                                            self.database.connect()                                                       File "C:\Python27\lib\site-packages\peewee.py", line 3404, in connect             self.initialize_connection(self.__local.conn)                                 File "C:\Python27\lib\site-packages\peewee.py", line 3316, in __exit__            reraise(new_type, new_type(*exc_args), traceback)                             File "C:\Python27\lib\site-packages\peewee.py", line 3402, in connect             **self.connect_kwargs)                                                        File "C:\Python27\lib\site-packages\playhouse\pool.py", line 128, in _connect     conn = super(PooledDatabase, self)._connect(*args, **kwargs)                  File "C:\Python27\lib\site-packages\peewee.py", line 3929, in _connect            return mysql.connect(db=database, **conn_kwargs)                              File "C:\Python27\lib\site-packages\MySQLdb\__init__.py", line 81, in Connect     return Connection(*args, **kwargs)                                            File "C:\Python27\lib\site-packages\MySQLdb\connections.py", line 193, in __init__                                                                                super(Connection, self).__init__(*args, **kwargs2)                          OperationalError: (1040, 'Too many connections')                                

## Steps to Reproduce (for bugs)

1. start map
2. map crashes giving internal server error
3. error starts popping out in the CMD window

## Context

I can't run the map because of this, it crashes every 10 or 15 minutes

## Your Environment

* Version used: latest release
* Environment name and version (e.g. Python 2.7): python 2.7
* Operating System and version (desktop or mobile): Windows 7, android

**Comment by aguita** [comment]
@gatomiaurex Please visit the Discord channel, help.   This is an issue with the # of connections to your MySQL database.  We can help you work through those in the Discord channel.

**Comment by gatomiaurex** [comment]
@aguita alright, thank you and sorry
