### ISSUE TITLE
Inserted time in database is wrong

### ISSUE THREAD

**Issue by simarsenault** [PokemonGoMap/PokemonGo-Map#142]
## Expected Behavior
In the SQLite database, the column disappear_time of table pokemon should contain the right time.

## Current Behavior
On my computer, a pokemon found on 2016-08-08 at 09:10:00 AM has the value `2016-07-18 21:53:35.231000`. Seems about 3 weeks off?

## Possible Solution
Not sure...

## Steps to Reproduce (for bugs)
Let me know if you need any details.

## Context
This bug results in pokemons not showing on live map (I see in the application tho).

## Your Environment
Windows 7 64bit pro (Region: Canada/French)
Python 2.7
Using commit bc02e61
Timezone GMT -5

**Comment by simarsenault** [comment]
Seems to be OK now. This is weird. The time was wrong on a pokemon, I kept deleting the link in the database (using SQLite Expert) and it kept reappearing with the wrong time...

**Comment by Brideau** [comment]
This is caused by an issue with the data source. For some reason, every now and then it passes a big, negative "time until hidden" value. The result is that the present time plus the "time until hidden" is always July 18th.

**Comment by chuyskywalker** [comment]
This could be a bug in the pogoapi itself, but I'll leave it open here anyway

**Comment by Fiofant** [comment]
Same problem.
![d5c7b-clip-287kb](https://cloud.githubusercontent.com/assets/5310320/17483773/1a98988e-5d90-11e6-912e-c8414485c6b1.png)

**Comment by schadis** [comment]
is this problem related to my 10gb database on jelastic?
my local one is only 3-5 mb

**Comment by thesandvichisaliar** [comment]
This is tied to #162 . These are greater than the normal 15 minute spawn timers. If you keep scanning the spawnpoint, it will eventually return the correct disappear_time (with the same encounter_id) when it is within 15 minutes of despawn.

**Comment by invisiblek** [comment]
Just to be sure, your client's time IS correct right? Mine was off by 2 minutes for the longest time and I couldn't figure out why pokemon would not be there when the map said they should still be for 2 more minutes.

**Comment by simarsenault** [comment]
I believe it is, logs in console show correct time.
