### ISSUE TITLE
--skip-empty not doing scans

### ISSUE THREAD

**Issue by PenguinsFlyGood** [PokemonGoMap/PokemonGo-Map#1421]
## Expected Behavior

before the latest commit --spawnpoints-only worked fine, now --skip-empty doesn't scan at all for me.

## Current Behavior

--skip-empty doesn't scan at all for me, except for if I only have less than 10 workers.
## Possible Solution

not sure?

## Steps to Reproduce (for bugs)

1. have lots of workers
2. try to do --skip-empty
3. it won't work.
4.

## Context

I miss being able to scan only the spawnpoints without being in -ss mode.

## Your Environment

* Version used: latest commit
* Environment name and version (e.g. Python 2.7): python 2.7 mysql 
* Operating System and version (desktop or mobile): windows 10

**Comment by BaIthamel** [comment]
This is not a support forum; please see [the discord #help channel](https://discord.gg/npVqkUn) for assistance.

**Comment by PenguinsFlyGood** [comment]
Thought this was an issue since it's not only me having it; will try to get assistance on the dc though.
