### ISSUE TITLE
List index beehive

### ISSUE THREAD

**Issue by Bizadon** [PokemonGoMap/PokemonGo-Map#1424]
Starting locationGenerator.py gives me:

Reading usernames/passwords from C:\accounts.csv
Traceback (most recent call last):
  File "location_generator.py", line 55, in <module>
    accounts = [auth_template.format(args.auth, line[0].strip(), line[1].strip()) for line in account_fields]
IndexError: list index out of range

have an accounts.csv file like:
user1,pass
user2,pass
user3,pass
etc...

**Comment by BaIthamel** [comment]
This is not a support forum; please see [the discord #help channel](https://discord.gg/npVqkUn) for assistance.
