### ISSUE TITLE
Empty raw_data

### ISSUE THREAD

**Issue by jorgitoh** [PokemonGoMap/PokemonGo-Map#1425]
Im running the last version of the map with 10000 spawnpoints ( 500~ available accounts ). The console didnt show any error, every seems to works fine, but when I try to get the raw_data I get this:

{
  "gyms": {}, 
  "pokemons": [], 
  "pokestops": [], 
  "scanned": []
}

**Comment by coverslide** [comment]
Mine too, just started 2 hours ago. Is this happening to anyone else?

**Comment by BaIthamel** [comment]
This is not a support forum; please see [the discord #help channel](https://discord.gg/npVqkUn) for assistance.
