### ISSUE TITLE
ERROR: Grunt build

### ISSUE THREAD

**Issue by Nixoriuz** [PokemonGoMap/PokemonGo-Map#143]
## Steps to Reproduce (for bugs)
1. git clone https://github.com/PokemonGoMap/PokemonGo-Map.git
2. Fix config file with Google API
3. python runserver.py -a ptc -u johndoe -p johndoe -l "Secret mansion" -st 5 -H 0.0.0.0 -L en

ERROR: [CRITICAL] Please run "grunt build" before starting the server

4. npm install

ERROR: 
[npm-debug.txt](https://github.com/PokemonGoMap/PokemonGo-Map/files/406895/npm-debug.txt)

## Your Environment
* Python 2.7.12
* VMware (Win8.1)

**Comment by itztq** [comment]
Run:

npm install grunt --save-dev
npm install jshint-stylish
npm install grunt-contrib-uglify
npm install grunt-contrib-jshint 
npm install grunt-contrib-watch
npm install grunt-sass
npm install grunt-contrib-copy
npm install grunt-contrib-clean
npm install grunt-contrib-cssmin
npm install grunt-usemin
npm install grunt-contrib-concat
npm install grunt-html-validation
npm install grunt-babel
npm install grunt-minjson
npm install babel-preset-es2015 --save
npm install babel-preset-react —save
grunt build

**Comment by chuyskywalker** [comment]
```
npm install
npm run build
```

Will be sufficient. I'll also update this error message.

**Comment by itztq** [comment]
@chuyskywalker 

When i run the NPM install and run build, the web interface is only showing the option menu bar but the map is empty of white.

But if i run the commands that i lined up, it works why?

**Comment by chuyskywalker** [comment]
I have no idea, you've probably got some kind of broken environment. `npm install` will install all the things you listed since that's all in `package.json` already. You could be on a bad version of node/npm, or have something from previous installs conflicting somehow. I can't really say.

**Comment by chuyskywalker** [comment]
I've addresses the original problem; lack of clear message, in #166

**Comment by Nixoriuz** [comment]
reinstalled a new VMware with win 8.1 and installed everything that is needed but now i got a different error on line 44.
![d87c4bb0c39946afa88e58026941b11a](https://cloud.githubusercontent.com/assets/20906272/17490291/70123f92-5da2-11e6-946b-38edf2e23a76.png)

**Comment by BaIthamel** [comment]
For support please ask in discord.
