### ISSUE TITLE
no map showing

### ISSUE THREAD

**Issue by Wtcheesecakes** [PokemonGoMap/PokemonGo-Map#1438]
![image](https://cloud.githubusercontent.com/assets/21296476/19022987/70220792-88db-11e6-8de1-7eac9c8c3834.png)
this is all i see im running raspbrian lite with correct version of python and pip and node and npm

**Comment by cyan** [comment]
personnaly 'ive had trouble compiling on raspbian, and had to compil on computer an transfer the folder to the raspbian.
other than that the github isn't for support and you should go to the discord

**Comment by BaIthamel** [comment]
This is not a support forum; please see [the discord #help channel](https://discord.gg/npVqkUn) for assistance.
