### ISSUE TITLE
Geo-locate isn't working

### ISSUE THREAD

**Issue by NullEnt1ty** [PokemonGoMap/PokemonGo-Map#144]
"Scan follows location" doesn't seem to work. Console output below.

## Expected Behavior

Changing the marker position and scanning the area at my position.

## Current Behavior

Won't change the location at all. Console outputs:

`Uncaught TypeError: Cannot read property 'getPosition' of undefined @ map.min.js:formatted:1448`

which is this line: https://github.com/PokemonGoMap/PokemonGo-Map/blob/develop/static/js/map.js#L1903

## Possible Solution

https://github.com/PokemonGoMap/PokemonGo-Map/blob/develop/static/js/map.js#L866

Assign returned value to the marker variable. This fixed it at least for me.

`marker = createSearchMarker()`

## Steps to Reproduce (for bugs)

1. Open map.
2. Activate "Scan follows location" and try to locate your position.

## Your Environment

* Version used: https://github.com/PokemonGoMap/PokemonGo-Map/commit/0566c29226a50c19083ac1235ee16a18c2cf13c4
* Environment name and version (e.g. Python 2.7): Python 2.7.9; Webserver: nginx/1.6.2 (https enabled); OS: Debian Jessie
* Operating System and version (desktop or mobile): OS: Windows 8.1; Browser: Chrome 52

**Comment by snajjar** [comment]
On Google Chrome >= 51, Geolocalisation is blocked if the host website doesn't use HTTPS

**Comment by NullEnt1ty** [comment]
Sorry, I didn't made this clear: I'm using HTTPS. Geolocalisation is working fine, but the marker doesn't update its position and therefore the map still scans an old location.

**Comment by nylocx** [comment]
I'm not a JS expert but the current implementation can't work as NullEnt1ty explained. But I think if creating a global variable is intended there is no need to do it outside of the function. Just removing the var before marker in the function will be enough.

**Comment by rrbailey89** [comment]
Is it possible to make this work without requiring https?

**Comment by nylocx** [comment]
Hopefully not from a programmers point of view ;)
https://developers.google.com/web/updates/2016/04/geolocation-on-secure-contexts-only
But as the document states the google maps api should be uneffected by this change
https://developers.google.com/maps/documentation/geolocation/intro#overview
And localhost based sites are declared as secure too.

**Comment by NullEnt1ty** [comment]
There might be some browsers which will allow sending your location over HTTP, but I'd recommend to get a free certificate (e.g from https://letsencrypt.org/).

**Comment by tkSimon** [comment]
#164 has been merged which should resolve this issue, please update and check again.
