### ISSUE TITLE
Scan locations not updating

### ISSUE THREAD

**Issue by TheNewDarkOne** [PokemonGoMap/PokemonGo-Map#1443]
With todays merge of smarter updates (https://github.com/PokemonGoMap/PokemonGo-Map/pull/1303), scan location circles do not update without manually refreshing. this only happens if it's updating a previously scanned location circle with a new one. Not a fresh scan location. So you need to watch it complete a full scan/steps then when it repeats it'll not update any more scan locations until they expire. It's still scanning and new pokemon are still showing up so it's only a visual bug with the way the new commit tells it not to send scan location data in updates unless it's NEW.

Best way to test it is to use traditional scan not SS scanning which will actually not usually produce bug since it'll never scan SAME location more than once an hour, which is probably how this can easily be overlooked.

**Comment by DiscoTim** [comment]
pr #1444 fixes this issue
