### ISSUE TITLE
'Error - Map parse failed' when running with -wh for PokeAlarm

### ISSUE THREAD

**Issue by SemperPius** [PokemonGoMap/PokemonGo-Map#1448]
## Expected Behavior
Running the map with '-wh http://127.0.0.1:400' should run the map normally and give me messages via PokeAlarm.

## Current Behavior
When I'm running the PokémonGo-Map it runs just fine but once I add '-wh http://127.0.0.1:400' to the bash file so I can get notifications via PokeAlarm, I get the following error for about half the accounts:

2016-10-03 16:30:02,446 [ search-worker-0][        search][   ERROR] Map parse failed at 52.326758,5.114309, abandoning location. Account may be banned.
Traceback (most recent call last):
  File "/home/user/PokemonGo-Map/pogom/search.py", line 510, in search_worker_thread
    parsed = parse_map(args, response_dict, step_location, dbq, whq, api)
  File "/home/user/PokemonGo-Map/pogom/models.py", line 882, in parse_map
    'last_modified': calendar.timegm(pokestops[f['id']]['last_modified'].timetuple()),
KeyError: u'e926ba0ce0da4ae0b74910032dedc641.16'

I can confirm that the accounts are not banned - I've logged in via the Pokémon Go app and without the '-wh' command the map runs without issues. The error has appeared since my last update which added the commits #1303 and possibly #1428.

## Context
I'm trying to run the PokemonGo-Map with PokeAlarm so I can notify the group I play with of new Pokémon spawns. The messages via PokeAlarm still get through but the error causes about half of the spawns to be skipped and thus go unreported.

## Your Environment
* Version used: all commits pulled
* Environment name and version (e.g. Python 2.7): Python 2.7.12
* Operating System and version (desktop or mobile): Ubuntu 16.04

**Comment by Cartman123** [comment]
Running with --webhook-updates-only is working, so you can use that as workaround. It seems the key got changed to 'last_modified_time'.

**Comment by craziplaya21** [comment]
Thank god it wasn't only me. I was pulling hairs out trying to figure out the problem only to have realized it is the -WH that is causing the ban messages a couple hours later.

**Comment by Cartman123** [comment]
I made 30 new accounts before I realized it was just a bug :P

**Comment by SemperPius** [comment]
I've changed -wh to --webhook-updates-only, the scanner works but I don't know how to connect PokeAlarm to the map now since http://127.0.0.1:4000 isn't recognized anymore. What to do?

**Comment by DiscoTim** [comment]
pr #1444 fixes this issue
