### ISSUE TITLE
Running multiple account on Bluemix

### ISSUE THREAD

**Issue by tholuuduc** [PokemonGoMap/PokemonGo-Map#1450]
![image](https://cloud.githubusercontent.com/assets/18677397/19043229/7a7c1618-89b9-11e6-9a5c-aa096fd1e09b.png)

i can not run multiple account on bluemix. it found pokemon but app not running
I try add account to config file or csv file
Using command: python runserver.py -a ptc -u "pokemaphpvn1" -p "1jlzmjjz" 
Or command: python runserver.py -ac accounts.csv
but the same error appear.any ideal ?

**Comment by BaIthamel** [comment]
This is not a support forum; please see [the discord #help channel](https://discord.gg/npVqkUn) for assistance.
