### ISSUE TITLE
Change Location Feature only affects X specific workers

### ISSUE THREAD

**Issue by MikeLeema** [PokemonGoMap/PokemonGo-Map#1454]
I'm quite sure i was not suposed to post stuff like this, but since this is the "closest" to the map contributors i can get here it goes...

I would like to know if it is possible to assign like 5 workers to be in standby until some1 uses the feature of "Change Search Location" and by changing that, the system would send those "standby" accounts, (1 "hexagon" with -st 4 with 5 accounts to scan it fast and on the go), to the new location while all other workers remain spawn scanning only. Is this possible?

Also, is there a difference between setting the "same" start location for all workers, spawn scanning only with a big number set to the -st argument, and setting several locations for a X workers each, seperated to each other? For example... is it better to set 1 location for all workers and let the spawnscan do the job (big jumps may happen) or set several locations for X workers each location in each "corner" of the area i wanna scan?

Sorry for my noob english (Native language is portuguese xD)

Keep up the good work! I love this project

**Comment by BaIthamel** [comment]
This is not a support forum; please see [the discord #help channel](https://discord.gg/npVqkUn) for assistance.
