### ISSUE TITLE
My accounts cant work

### ISSUE THREAD

**Issue by a2323588qq** [PokemonGoMap/PokemonGo-Map#1458]
I setup 8 accounts,but 6 accounts are cooling down,only 2 accounts are scanning. I wanna know how to fix it.

**Comment by Wtcheesecakes** [comment]
im getting the same issue but all of my accounts are getting the invalid response then getting cool down

**Comment by a2323588qq** [comment]
I fixed it after I read this post 
https://github.com/PokemonGoMap/PokemonGo-Map/pull/1383/commits/b973b6f2c3791a54983b27ea9901a3a1f87578e4

**Comment by BaIthamel** [comment]
great :)
