### ISSUE TITLE
Error installing requirements on Windows

### ISSUE THREAD

**Issue by Muryginds** [PokemonGoMap/PokemonGo-Map#146]
While installing requirements.txt i got this error:
``
![1](https://cloud.githubusercontent.com/assets/20901392/17481478/1f326abe-5d86-11e6-8140-c2cdd074dd54.png)

then i tried going strait:
pip install git+https://github.com/keyphact/pgoapi.git#egg=pgoapi 

and got this:
![2](https://cloud.githubusercontent.com/assets/20901392/17481495/2d388274-5d86-11e6-9ff5-f21787b4f8c2.png)

**Comment by invisiblek** [comment]
try installing this: https://www.microsoft.com/en-us/download/details.aspx?id=44266
