### ISSUE TITLE
Accessing MySQL local 

### ISSUE THREAD

**Issue by skerdilajd99** [PokemonGoMap/PokemonGo-Map#1460]
Tried different times and cant seem to make it work

## Steps to Reproduce (for bugs)

1. Followed the guide step by step
2. Ran once on default SQlite
3. Configured the config.ini

## Your Environment

* Python 2.7.12 also downgraded to 2.7.10
* Win 10 x86:

**Comment by jorgitoh** [comment]
OperationalError: (1045, u"Access denied for user 'pogomapuser'@'localhost' (using password: YES)")

Are u using the right password?. If u followed the guide check this:

CREATE USER 'pogomapuser'@'localhost' IDENTIFIED BY 'password'; ( Password is password )

**Comment by skerdilajd99** [comment]
Omg, yes thats it. Been running in circles for quite some hours. thnx
