### ISSUE TITLE
No pokemon showing up when scanning

### ISSUE THREAD

**Issue by johnscancella** [PokemonGoMap/PokemonGo-Map#1461]
## Expected Behavior
Start map, after scanning, pokemon should show up

## Current Behavior
No pokemon showing up, even though other map services says there are pokemon there

## Context
Using map to scan the same  area so I can be alerted when pokemon I care about show up in my neighborhood

## Your Environment

* Version used: df13b8e6c0f238f94608d067fadeaca7d42dc958
* Environment name and version (e.g. Python 2.7): Python 2.7.10
* Operating System and version (desktop or mobile): desktop, Mac os X Sierra

**Comment by johnscancella** [comment]
![screen shot 2016-10-04 at 4 09 09 pm](https://cloud.githubusercontent.com/assets/8711605/19090540/f71adcd4-8a4c-11e6-8645-97f53e0eb678.png)

**Comment by renatosouzadias** [comment]
me too, 
ninatic is banishing my ip all the time

**Comment by johnscancella** [comment]
Yeah, even my phone was acting up until I took it off the wifi.
Is that a permanent ban?

**Comment by bluelatios** [comment]
@Janglinator are you sure that's a temporary ban? Not some api changing or something? I just open up my scanner, and nothing shows up

**Comment by renatosouzadias** [comment]
I wait 3 h and the problem continues. What can I do?

**Comment by Decepticon01** [comment]
I'm dealing with this as well. Accounts are logging in fine, but nothing showing up on the maps. This problem started about 3 hours ago for me. I got a few scans in and then nothing would show up anymore.

**Comment by WalterMagnum** [comment]
If you have recently increased the number of requests you are making (gym info, moves/ivs, etc) that could be the problem.  Other than that,  I think Niantic might have changed their IP ban algorithm.

**Comment by Janglinator** [comment]
Yeah it's looking like @WalterMagnum is onto something.  😞

**Comment by Beri51** [comment]
Just launched an "on-demand" scan with 15 accounts and a small beehive (step 5 or 6).
It actualised the gyms and showed the pokemons (and I stopped manually just after to prevent possible ban).
Maybe they are blocking speed, teleport more accurately right now than before ?

**Comment by Decepticon01** [comment]
It's now working for me. I believe they soft ban when the server is at higher load. I checked out the pogo server status earlier when I had no pokemon showing up and it said server is unstable. so maybe IP traffic is looked at more aggressively during high traffic?

**Comment by Decepticon01** [comment]
It looks like what Beri51 said is what is possibly happening. 1/2 my beehive scanned and the other half scanned with no pokemon.

**Comment by dragonalvaro** [comment]
Parsing found 0 pokemons, 0 pokestops, and 0 gyms.

All the time

**Comment by faketits** [comment]
Static scans works,
But if searchers bounce around the map they get soft ban. it releases after 1 Hour  +\-

**Comment by Decepticon01** [comment]
Beehive or bust basically?

**Comment by Darkknightz** [comment]
No issues here (UTC+2)   (SS mode)
![capture](https://cloud.githubusercontent.com/assets/21358492/19111982/98cb0828-8b02-11e6-9799-03a7d09de82f.JPG)

**Comment by shockler** [comment]
I got ip banned too.
Before I can run 1300 acc with the same IP very well.
Now I have to use proxies, about 60acc/proxy.

**Comment by renatosouzadias** [comment]
How can i do this @shockler ?

**Comment by Jumbs** [comment]
@faketits How does one make a scan static?

My search location is locked, but i still am getting this issue.  Is there an option to make one account get the same spot every time?

**Comment by BaIthamel** [comment]
This is not a support forum; please see [the discord #help channel](https://discord.gg/npVqkUn) for assistance.
