### ISSUE TITLE
Auto-Restart Map Server

### ISSUE THREAD

**Issue by jorgitoh** [PokemonGoMap/PokemonGo-Map#1467]
Im running like 10000~ spawns with 40 workers ( <10s behind ). After 10 or 12 hours Im like 600s behind. I think would be a good feature that we can auto restart the map in this situation. When I check the status page I have like 50% of workers paused.

Your Environment
. Lastest version
. No IV / No Moveset
. 5km^2 area. 10000~ spawns ( after using clustering tool )
. Good I5 with 16GB ram (Low use of cpu, ram and bandwidth )

**Comment by Becold** [comment]
If you run your server on Linux, you can do it yourself with a cron.
http://askubuntu.com/questions/13730/how-can-i-schedule-a-nightly-reboot

**Comment by aduljr** [comment]
i think you could use a few more clients for padding and cases where there is a slow response.

**Comment by jorgitoh** [comment]
Create a job isnt the problem. Every day I start the server from 0800/1000 AM to 0200 AM. The problem is when I cant check the server status. Idk how to code in python, but using another language I can do a task that check If the map is 300ms behind and then restart the process. Im looking a good way to do it using the actual source code.

**Comment by BaIthamel** [comment]
I thought there was a drop task if xxxseconds behind argument...

**Comment by BaIthamel** [comment]
Yup I was right
 parser.add_argument('-msl', '--min-seconds-left',
                        help='Time that must be left on a spawn before considering it too late and skipping it. eg. 600 would skip anything with < 10 minutes remaining. Default 0.',

If you use that thing it will start skipping things if it falls behind.

**Comment by jorgitoh** [comment]
@BaIthamel thank you. If I have the same problem today ill take a picture. Is not about skip or not a spawn, its about that the paused accounts never look for a replacement in the csv list. So after 10 hours the 40 workers drop to 20. Regards.
