### ISSUE TITLE
Is there a way to reduce memory usage running multiple instance (beehive method)?

### ISSUE THREAD

**Issue by sharklab** [PokemonGoMap/PokemonGo-Map#147]
As title says i'm running about 60 Movable object but each of tehm takes about 50MB of memory, I would like to scan other places but right now i'm very ram limited.
Thanks!

**Comment by chuyskywalker** [comment]
This is not a support forum; please see [the discord #help channel](https://discord.gg/npVqkUn) for assistance.

That said, memory optimization is really not at the top of our todo list, sorry.
