### ISSUE TITLE
New security capcha to implant

### ISSUE THREAD

**Issue by bouelcom** [PokemonGoMap/PokemonGo-Map#1471]
So now that Niantic pushed their new security since today with the ingame capcha, how we can implant them into PokemonGo-Map ?

**Comment by marumari** [comment]
Duplicate of #1470, and also it's captcha and implement and please stop yelling.

**Comment by bouelcom** [comment]
no more "yelling" here, and yes of course it seem a duplication issue/thread to resolve this

**Comment by HenrySia** [comment]
capcha -> captcha
implant -> implement

I'm triggered.
