### ISSUE TITLE
Feature Request: Recycle accounts that turn up empty.

### ISSUE THREAD

**Issue by thatsweater** [PokemonGoMap/PokemonGo-Map#1473]
## Expected Behavior
When an account turns up empty cells for some number of consecutive times, it will pull a new account and blacklist the old one. Obviously this is due to the new captcha issue, and PR 1081 does not work with -enc, it also does not permanently not use accounts that turn up empty.

## Current Behavior
There is no method for cycling empty accounts, only failed ones.

## Possible Solution
Use existing PR 1081 and improve this.

**Comment by Bx3mE** [comment]
+1!

**Comment by Samael27** [comment]
+1

**Comment by revlisoft** [comment]
+1

**Comment by BaseCamp888** [comment]
+1
If can add a page to display and solve the captchas for said accounts (like PokeAlert) then I think it would pretty much solve the issue.

**Comment by filippounitn** [comment]
Also requeue scans with errors... otherwise we miss pokemons

**Comment by kvangent** [comment]
Submitted a quick solution in #1477.

**Comment by thatsweater** [comment]
Thank you kvangent! This has been solved!

**Comment by Badiboy** [comment]
Implemented here: https://github.com/PokemonGoMap/PokemonGo-Map/pull/1235
