### ISSUE TITLE
Gyms and map dragging / zooming

### ISSUE THREAD

**Issue by Slivo-fr** [PokemonGoMap/PokemonGo-Map#1474]
Incorrect behavior on mobile
## Expected Behavior

Tooltip only open on a tap, map should be draggable from any poiny
## Current Behavior

Dragging or zooming map on gyms open the tooltip on mobile
## Steps to Reproduce (for bugs)

Load a map with dense gyms markers, try to pinch or drag from a gym marker
## Your Environment

Chrome and firefox on android

**Comment by Rook25** [comment]
Fixed in pull request #1719
