### ISSUE TITLE
ReCaptcha solution for the server

### ISSUE THREAD

**Issue by Bx3mE** [PokemonGoMap/PokemonGo-Map#1475]
When logging in accounts get invalid response

## Expected Behavior
Login -> Request Access Token --> Searching

## Current Behavior
Login -> Request Access Token --> Abandon

## Possible Solution
Login -> Request Access Token --> Pop Up ReCaptcha for user to manually solve Captcha --> Searching

## Steps to Reproduce (for bugs)
Use a suspect account for scanning

## Context
Obvious : D

## Your Environment
Windows - Acc-Creator working with manual ReCaptcha

**Comment by marumari** [comment]
This should probably just be a comment of #1470.

**Comment by Ashex** [comment]
We're dealing with workers that are running multiple accounts so a pop-up would not work for a number of reasons such as:

* You'll get spammed by pop-ups
* Many people run this on headless setups
* lots and lots of accounts

Closing this out in favor of #1470
