### ISSUE TITLE
[Feature request] Pull reCaptchas and forward to statuspage or even frontend user

### ISSUE THREAD

**Issue by Arengo** [PokemonGoMap/PokemonGo-Map#1480]
## Expected Behavior

A worker keeps getting 0,0,0 findings and is being investigated for a reCaptcha while being put into the failed worker list. The reCaptcha is found and it's token is being forwarded to the worker's status page. Those people with access to the server's status page are able to access a solution website and solve the worker's reCaptcha token and the worker will then be added back to the queue. Further, there is a option to let map users solve the reCaptchas - it is used as an access requirement to the map, like a minimum of solving 3 reCaptchas before one may have a look on the map (can be stored in a cookie and renewed i. e. every 6 hours).

## Current Behavior

The worker keeps getting those 0,0,0 results and is not being switched out. A captcha is not accessible without logging in manually with a phone to solve it there. After a manual reCaptcha solution the worker starts to work again. This way is not practicable when you have a of workers.

## Possible Solution

- Identify the worker with 0,0,0 by using a --max-empties flag like there is already one in a recent pull request.
- Put the affected worker on the failed list and flag it for being checked for a reCaptcha.
- Pull the reCaptcha token from the game server, what is currently not possible with the pogoapi we use. Here, we need new methods and a deeper research how to pull a reCaptcha in general and let it being solved from the browser in the easiest way possible.
- Write the token or URL of reCaptcha solution page into the status update for the worker to send it to the server status page. There, it can be clicked to maintain these broken workers actively.
- Find a nice solution to prompt these tokens / URLs to other users front-end and let them be solved from their IP.

**Comment by foltincsaba** [comment]
And it would be also useful if account names and passwords would be stored in database. Thus captcha-d and banned accounts could be handled more easily even if you run multiple instances.

**Comment by Arengo** [comment]
@foltincsaba there are issues when you are sharing your dbs.

**Comment by Ashex** [comment]
This is being discussed in #1470, please submit your proposal there to keep all discussion in one place.
