### ISSUE TITLE
Exception while downloading map: Seems your IP Address is banned or something else went badly wrong...

### ISSUE THREAD

**Issue by Cammo009** [PokemonGoMap/PokemonGo-Map#1481]
Exception while downloading map: Seems your IP Address is banned or something else went badly wrong...

## Expected Behavior

Accounts should be scan for pokemon at set location

## Current Behavior

Purchased a new server and installed Pokemon go. Started up to find this error again first go Exception while downloading the map: Seems your IP Address is banned or something else went badly wrong...  Invalid response at SET LOCATION..  abandoning location

## Possible Solution
I'm not experienced to find the cause but don't think its an IP ban as this server is new and was apparently banned after the first startup

## Steps to Reproduce (for bugs)

1. Purchase server
2. Install PokemonGo Develop 
3. Create 4 accounts 
4. Create Google API key and Launch. Bamm Banned apparently.

## Your Environment

* Python 2.7
* Pip 8.1.2
* Ubuntu 16.04 64bit
* Start command: python runserver.py -a ptc -u account1 -u account2 -u account3 -u account4 -p Password1 -p Password2 -p Password3 -p Password4 -odt 2 -st 10 -k Google-API-Key -l "_111 Something St, City NSW PostCode_" -H _Server_-IP -P _Port_ -L en -sd 10

## Error
User Login Successful.....
2016-10-07 08:30:58,402 [ search-worker-0][        search][ WARNING] Exception while downloading map: Seems your IP Address is banned or something else went badly wrong...
2016-10-07 08:30:58,402 [ search-worker-0][        search][   ERROR] Invalid response at SET LOCATION, abandoning location.

**Comment by HypeZ85** [comment]
i got 2 new virtual servers and.. after the first setup got the same error on both servers. They had similar ip.
A Third one (with a rather far ip) worked with the same configuration.

My guess is that Niantic banned some ip-range related to popular hosting services (and cloud services) so we can just request another ip or get some luck with VPN or proxys..

**Comment by Arengo** [comment]
The most providers of VPS or Proxies are already IP range banned.

**Comment by Cammo009** [comment]
The first server stsrted with 149.52.**.** new on it 158.32.**.**

**Comment by Arengo** [comment]
@Cammo009 so they are probably both IP range banned. Try it out with the same setup on a local IP, I bet it works there.

**Comment by FrostTheFox** [comment]
I mean, the error speaks for itself. Niantic returned a 403 Forbidden, which does mean that the IP address has been banned. Use a VPN or proxy.

**Comment by FrostTheFox** [comment]
Lots of hosts have been banned already by Niantic. It doesn't necessarily require a scanner from an IP for it to be banned, they can ban blocks specifically from server hosts.
