### ISSUE TITLE
[Feature Request] Working Map

### ISSUE THREAD

**Issue by thatsweater** [PokemonGoMap/PokemonGo-Map#1484]
## Expected Behavior
LIke what if you had llike a map that erm talked to niantics guys and got where the cool pokemanz were and then you could like see and go tehre and touch em with ur own phone

## Current Behavior
i cant find the cool guys

## Possible Solution
you coudl use a bunch of shit and get google to give you mappers and get a bunch a python out the snake box and find the pokemanzz

## Steps to Reproduce (for bugs)
ask thunderfox for more memes

## Your Environment
windows xP

**Comment by FrostTheFox** [comment]
good meme, solid 7/10

could use some more example.py though.

**Comment by birdstream** [comment]
Love this!
