### ISSUE TITLE
No pokemon found.

### ISSUE THREAD

**Issue by trieuking** [PokemonGoMap/PokemonGo-Map#1485]
No pokemons / pokestops / gyms found few hours ago. I think have some thing wrong with Niantic API to search.

**Comment by yazman101** [comment]
New API has locked down all scanners. FastPokeMap is down also.

**Comment by huanga** [comment]
Niantic no longer accepts 0.35 API requests. Until the new API have been reverse engineered, and `Pogom` gets updated, `PokemonGo-Map` will not work.

**Comment by MikeMilzz** [comment]
There is a change and most apps / accounts are being shutdown. I logged in with my map account and had to do a captcha and got an alert that this account was showing suspicious activity. I'm hoping there is a way to set scanning to not trigger this alert.

**Comment by yazman101** [comment]
They enforced the Captcha first. Banned all bot accounts. And now have locked down the API. 

Devs have to rev engineer new API. Probably down for days....

**Comment by yazman101** [comment]
There is discussion to keep the scanners confined to a small search area and below a certain travel speed to minimize triggers. Lots to think about in the new dev

**Comment by walaoaaa1234** [comment]
#1470

**Comment by FrostTheFox** [comment]
#1470
