### ISSUE TITLE
is this still working ? 

### ISSUE THREAD

**Issue by lxboy16** [PokemonGoMap/PokemonGo-Map#1489]
I am a new user.  I followed all the step and finally get to load the map . However, there is no pokemon/pokestops showed up. Just wondering if this map is still working ?

**Comment by acsrock** [comment]
Not currently. It's been having a few issues.
The API had been broken by Pokemon and they implemented a capitcha.
Hopefully it will be working again soon.

**Comment by lxboy16** [comment]
Thank you for letting me know . I 've been wasting a couple of days on this :(

**Comment by ultrafunkamsterdam** [comment]
if you have read the issues before, you could have known..

**Comment by BaIthamel** [comment]
This is not a support forum; please see [the discord #help channel](https://discord.gg/npVqkUn) for assistance.
