### ISSUE TITLE
No Pokémon Showing

### ISSUE THREAD

**Issue by blackhattristar** [PokemonGoMap/PokemonGo-Map#1491]
## Expected Behavior

See Pokémon
## Current Behavior

Not showing Pokémon
## Steps to Reproduce (for bugs)

1. I'm using Jelastic. Is anyone having trouble getting their servers to show anything? It was working a few days ago. My accounts are not banned. 
2.
3.
4.

## Your Environment

* Version used: Lastest version
* Environment name and version (e.g. Python 2.7):
* Operating System and version (desktop or mobile):

**Comment by FrostTheFox** [comment]
#1487. .35 API has been cut off.
