### ISSUE TITLE
Gym still update now?

### ISSUE THREAD

**Issue by Bear007** [PokemonGoMap/PokemonGo-Map#1495]
Since the official changed the api, then we can't see the pokemon at the map at this moment.

but i would to like to know, i still can see the GYM on the map, Gym owner and Gym LV, but the last scanned time is 2016/10/7.
We will have a event in Hong Kong, need to confirm the gym data must be correct.

Is that anyway to fix this problem? or other site can provide the correct gym data?

Thanks
Bear

**Comment by arivero** [comment]
I am intrigued with this. Fort Info is still available, but gym fails to me, not sure if my fault or API fault.

**Comment by chowderchow** [comment]
nope, not working.

**Comment by pbrent84** [comment]
It's just showing the old data from DB of last scans you can manually change those DB entries or just flush them. Personally I set them all to Max lvl instinct.;)

**Comment by aguita** [comment]
@Bear007, @arivero No site will have this information until the API is reverse engineered.   This data can not be collected automatically.   You'll have to compile it manually.

**Comment by StairyNight** [comment]
I wonder how I can get the gym locations to be shown on the map when api is not working. In my map, the gym dont show up because the the python program never passes the credential phase. I just want to know the location of the gyms.

**Comment by arivero** [comment]
-os starts the map in "only server" mode. Or is it -so? Whatever, you can check locations in this way.  This is different of the OP issue, which basically asks if get_gym_details is still working (it has some logic, as get_fort_details is working).

**Comment by arivero** [comment]
@aguita @chowderchow just not working with get_map_objects or confirmed to fail too with get_gym_details?

**Comment by aguita** [comment]
@StairyNight start up in -os mode and it'll report everything that you've previously seen.   Reporting what you already have within your database does indeed work.   
@arivero You can not get any new information from the API.  No gym details, no pokemon, no pokestops.   You can start the server up in -os mode and host the data to shown previously captured spawnpoints (and timers, will turn green), gym locations (details if you turned that on, but only as of last scan), and pokestop locations.

**Comment by BaIthamel** [comment]
The gyms are loaded from the DB, same as spawnpoints. They're just really outdated.
