### ISSUE TITLE
Option to share data through a common service - Feature Request

### ISSUE THREAD

**Issue by Axeia** [PokemonGoMap/PokemonGo-Map#1498]
As Niantic has claimed a huge drop in server-load after the first protection against non-pokemon go clients wouldn't it be wise to share data between maps? 

Like for example you might have a thousand people using 50 accounts each to scan New York. That's 50.000 accounts hammering Niantics servers. Could we have some kind of peer 2 peer solution or simply a global server that unites the data of these thousand people with maps? That way the load on the Niantics servers would be greatly lessened, data would be faster if a lot of different people use the map in the same area.

Or alternatively so the global server could be kept simple, just store all spawnpoints there, have the map itself download a list of spawnpoints and then do only spawnpoint scans? Sadly I can only suggest it and not contribute as I have no python knowledge whatsoever.

If there's less load on Niantic servers they might be less inclined into pooring so much resources into banning map accounts.

**Comment by tymosier** [comment]
I like this idea, but wouldn't this require someone constantly maintaining a database and servers for pretty much everyone?

**Comment by TheQL** [comment]
Couldn't you not just use fastpokemap.se in high populated areas then?
What's so charming about your own map is the ability to scan rural areas, scan for IV and use custom alerting based on whatever criteria you like. I can't see how running your own map but sharing gathered data by the workers would work out for everybody and on a technical base.

**Comment by Stuck7hrottle** [comment]
Isn't that what https://openpokemap.pw is trying to do? Or am I mistaken?

**Comment by BaIthamel** [comment]
The scanner contains webhook functionality. It is possible with the map/scanner in its current state to set up this request by sending all scanned data to a central server and accessing a map hosted by that server.
As such I will close this FR.

**Comment by FrostTheFox** [comment]
OpenPokeMap is sort of working to achieve this, you can send them your data, and it will be used on their map. They don't have an automated way to make an API key yet, but they should very soon. As Balth said, this is all possible, just requires someone to make the service.

**Comment by FrostTheFox** [comment]
Also, don't listen to Niantic's bullshit about server loads. Sure, we definitely make up a large part of their traffic, but they have no problem handling such things. They're doing it because they don't like the unofficial API stuff, not because of the servers.
