### ISSUE TITLE
Pokemon Vis Toggle -- Quickly see what's been filtered out

### ISSUE THREAD

**Issue by itztq** [PokemonGoMap/PokemonGo-Map#150]
Sometimes it occurs that there no pokemon on the map because you filtert it to hide. if you want to see the pokemons that you hide you must manualy delete it and insert it back. 

## Possible Solution
Button for hide pokemon
On = turn on the hide filter
Off = turn off the hide filter

**Comment by blindreaper** [comment]
The filter list should be toggleable. Default hides pokemon, click it and it inverses it, shows only pokemon you did not hide.

On mobile its not feasible to hide more than 20 pokemon. Perhaps i only want to show charizard, venusaur and blastoise, i cannot add 149 pokemon to the list.

**Comment by BaIthamel** [comment]
For feature requests please migrate this to the new feature page
http://feathub.com/PokemonGoMap/PokemonGo-Map/
Thankyou!

**Comment by CoolCanuck** [comment]
@BaIthamel This request needs to be opened again. FeatHub is no longer used. Good riddance.
