### ISSUE TITLE
Obey to speed limit or no pokemons are found

### ISSUE THREAD

**Issue by simonbuehler** [PokemonGoMap/PokemonGo-Map#1503]
hi,

with the new method not showing any pokemons when you get the "travelling too fast" popup  [(source)](https://www.reddit.com/r/pokemongodev/comments/57pco4/another_preventive_serverside_measure_aimed_at/) the scanners doing spawnpoint scanning must be limited to not exceed the max speed when hopping to the next spawnpoint.

* clustering seems a must now
* the optimal route for the points should be calculated depending on the numbers of accounts and the coverage that can be archived ( xx of YY spawnpoints can be reached in time, add ZZ accounts to get full coverage)

any ideas?

**Comment by FrostTheFox** [comment]
Yes, there's open PRs for speed limit, etc. It's something we're going to implement asap, but getting things *working* is a priority :)
