### ISSUE TITLE
[Feature request] `--no-scan` mode

### ISSUE THREAD

**Issue by tegob** [PokemonGoMap/PokemonGo-Map#1504]
With Niantic’s recent changes, there is currently no way to scan for Pokémon. However, PokémonGo-Map is still useful if you’ve scanned your area before!

How about adding a `--no-scan` mode, where it doesn’t attempt to log in to any accounts and performs no scanning whatsoever, but just displays the map with the known spawnpoints + spawn times? (A bit like running the script right now, except that it wouldn’t try to log in + scan.)

**Comment by primaxius** [comment]
-ns <--will do just that
