### ISSUE TITLE
Feature Request: Direct url to city

### ISSUE THREAD

**Issue by roflinger** [PokemonGoMap/PokemonGo-Map#1521]
## Expected Behavior
www.mypokemongomap.com:5000/cityofmychoice?=longlat <<-- leads to a direct place

## Current Behavior
not possible afaik - also asked in #help

## Possible Solution
implement it? :D

**Comment by BaIthamel** [comment]
This is not currently in the project remit and probably will never be.

**Comment by bouelcom** [comment]
i have implanted https://github.com/PokemonGoMap/PokemonGo-Map/pull/525/commits/ and working great

**Comment by BaIthamel** [comment]
great i'll close this then
