### ISSUE TITLE
77851 segmentation fault

### ISSUE THREAD

**Issue by serein927** [PokemonGoMap/PokemonGo-Map#1523]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Python 2.7):
* Operating System and version (desktop or mobile):

**Comment by tonygils** [comment]
same problem here.

Segmentation fault: 11

**Comment by FrostTheFox** [comment]
`python -v` output?

**Comment by m3g4mInD** [comment]
Hello,
after 2h ago give me this error:
Exception in search_worker under account xxxxxxxx Exception message: activate_signature is deprecated, binaries compatible with 0.41 API are now required.
 Comment out all calls to activate_signature to let them be autodetected.
Anyone with the same problem?
I Have running 4 days and now stoped
i have reinstall the map by git but still the same.

**Comment by weizh888** [comment]
I was running the latest develop branch on Ubuntu 14.04, and got the error:
segmentation fault (core dumped)
Could you help to solve the issue? Before this update, there wasn't any issue. Thanks.

**Comment by m3g4mInD** [comment]
@weizh888 look at my last comment i put the link

**Comment by serein927** [comment]
@FrostTheFox 
 Python 2.7.9 and on Mac OSX 10.12.1

**Comment by FrostTheFox** [comment]
@serein927 Please try using python 2.7.12. This was apparently an issue with python itself.

**Comment by weizh888** [comment]
@m3g4mInD In your comment, are you referring to the old API version?

**Comment by serein927** [comment]
@FrostTheFox It works now. But I kept finding 0 Pokemon while I did see Pokemon around. Any ideas about it? Thank you!

**Comment by Holzberg** [comment]
Still getting this right after login.  Ubuntu 16.04.1.  I uninstalled and reinstalled pip and its packages, python and nodejs.

**Comment by BaIthamel** [comment]
This is not a support forum; please see [the discord #help channel](https://discord.gg/npVqkUn) for assistance.
