### ISSUE TITLE
linux2 encryption library

### ISSUE THREAD

**Issue by Bear007** [PokemonGoMap/PokemonGo-Map#1531]
When i setup the map with linux, and the error come out.
Any people can help? please.

![whatsapp image 2016-11-12 at 11 45 45 am](https://cloud.githubusercontent.com/assets/22134477/20236277/643cb34e-a8ea-11e6-9261-2d4a9c543e31.jpeg)

**Comment by monkeymalle** [comment]
You can get the missing file(s) here: https://github.com/pokecrypt/pokecrypt-pgoapi?files=1

:-)

**Comment by irus99** [comment]
@monkeymalle I have CentOS6  and I was getting that error. After making the files via these directions

-1
clone this : https://github.com/laverdet/pcrypt-c
run "make" ( in my way i need to do : -std=gnu99 )
and :
cc -fPIC -shared -o libencrypt-centos-x86-64.so pcrypt.c shuffle2.c unshuffle.c unshuffle2.c
-2
clone this : https://gist.github.com/ZeChrales/28373120d41829d8e4cd3bdc959cb275
and :
cc -fPIC -shared -o libniantichash-centos-x86-64.so niahash.c
-3
after this copy them to "/usr/lib/python2.7/site-packages/pgoapi/lib"

got everything working but no pokemon show up. Not sure what to do next.

**Comment by Albert62** [comment]
1. Update to the latest commit.
2. There should be a folder called `pokecrypt-pgoapi` if not, create one.
3. Go to [this link](https://github.com/pokecrypt/pokecrypt-pgoapi/tree/master) and download clone as .zip or just use `git clone`.
4. Copy the files to `pokecrypt-pgoapi`.

**Comment by nomisunrider** [comment]
The error is missing libencrypt-linux-x86-64.so.  
https://github.com/pokecrypt/pokecrypt-pgoapi.git contains lib**p**crypt-linux-x86-64.so but not lib**e**ncrypt...

**Comment by Albert62** [comment]
@nomisunrider it was updated a while ago, the best option would be to get it from the previous commit.
`https://github.com/pokelibs/pgoapi-libs/tree/48cb37f3f584545d37a3192ef3bc8f4827d5a89f`

**Comment by nomisunrider** [comment]
It is located there, however now I just get Invalid Response similar to this other issue: https://github.com/PokemonGoMap/PokemonGo-Map/issues/1534

Something broke in the last few days, as it was working not long ago...

**Comment by nomisunrider** [comment]
https://github.com/PokemonGoMap/PokemonGo-Map/pull/1536 fixed this.

**Comment by BaIthamel** [comment]
This is not a support forum; please see [the discord #help channel](https://discord.gg/npVqkUn) for assistance.
