### ISSUE TITLE
paypal.

### ISSUE THREAD

**Issue by wukken** [PokemonGoMap/PokemonGo-Map#1532]
I made POGO map as jelastic but i want to know where i can implant the html code for the paypal button? anyone?

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Python 2.7):
* Operating System and version (desktop or mobile):

**Comment by ultrafunkamsterdam** [comment]
@wukken are you out of your mind? Using open source code and some free container platform, and you want to make people pay ?? or donate for your hard work?! Damn get a job.

**Comment by wukken** [comment]
Hmm the servers cost money you know..?

Op 12 nov. 2016 8:59 p.m. schreef "Leon" <notifications@github.com>:
