### ISSUE TITLE
Cannot run 'npm build' on MacOS

### ISSUE THREAD

**Issue by chippermist** [PokemonGoMap/PokemonGo-Map#1535]
## Expected Behavior
Should say completed successfully without errors.

## Current Behavior
Throws an error while running npm install
![image](https://cloud.githubusercontent.com/assets/7217791/20243664/7f2c6394-a92f-11e6-933b-d0d1901b81bc.png)

## Steps to Reproduce (for bugs)

1. Run npm install on MacOS

## Context
Trying to install repo

## Your Environment

* Environment name and version (e.g. Python 2.7): Python 2.7
* Operating System and version (desktop or mobile): MacOS 10.12.1

**Comment by FrostTheFox** [comment]
Need more details.

**Comment by alfw** [comment]
@mchristopher What node and npm version do you have installed?

**Comment by BaIthamel** [comment]
Issues are not for support... it says it a LOT of times.
