### ISSUE TITLE
Could not find win32 encryption library

### ISSUE THREAD

**Issue by houky12345** [PokemonGoMap/PokemonGo-Map#1537]
**Can someone help me please?**

I have these problems:

 _

> Traceback (most recent call last):
>   File "runserver.py", line 293, in <module>
>     main()
>   File "runserver.py", line 112, in main
>     encryption_lib_path = get_encryption_lib_path(args)
>   File "C:\Users\Username\Desktop\PokeGO\PokemonGo-Map\pogom\utils.py", line 486, in get_encryption_lib_path
>     raise Exception(err)
> Exception: Could not find win32 encryption library C:\Users\Username\Desktop\PokeGO\PokemonGo-Map\pogom\../pokecrypt-pgoapi\encrypt32.dll

_

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Python 2.7):
* Operating System and version (desktop or mobile):

**Comment by walaoaaa1234** [comment]
Go [Discord ](https://discordapp.com/invite/PWp2bAm) for support.

**Comment by walaoaaa1234** [comment]
```
git pull
pip install --upgrade -r requirements.txt
npm install
```

**Comment by houky12345** [comment]
I fixed it. Move encrypt32.dll and encrypt64.dll from PokemonGO-Map/pogom/libencrypt to PokemonGO-Map/pokecrypt-pgoapi

**Comment by walaoaaa1234** [comment]
update to latest version, no need for submodule

**Comment by BaIthamel** [comment]
This is not a support forum; please see [the discord #help channel](https://discord.gg/npVqkUn) for assistance.
