### ISSUE TITLE
xception while downloading map --- Mac os

### ISSUE THREAD

**Issue by Waterkryx** [PokemonGoMap/PokemonGo-Map#1538]
Hey guys i getting this issue

 search-worker-0][search][ WARNING] Exception while downloading map: dlopen(/usr/local/lib/python2.7/site-packages/pgoapi/lib/libniantichash-osx-64.so, 6): no suitable image found.  Did find:
	/usr/local/lib/python2.7/site-packages/pgoapi/lib/libniantichash-osx-64.so: unknown file type, first eight bytes: 0x62 0x6F 0x6F 0x6B 0x00 0x00 0x00 0x00
2016-11-13 11:46:56,054 [ search-worker-0][        search][   ERROR] Invalid response at 49.555523,15.943666, abandoning location

can anyone help please?

**Comment by BaIthamel** [comment]
This is not a support forum; please see [the discord #help channel](https://discord.gg/npVqkUn) for assistance.
