### ISSUE TITLE
Encryption32bit.dll error

### ISSUE THREAD

**Issue by forsakenzombi** [PokemonGoMap/PokemonGo-Map#154]
Not sure if the api has even been cracked yet but I attempted to install the newest develop build and have successfully ran everything but when i run the command i get the error below.

2016-08-08 10:47:08,111 [      MainThread][         utils][   ERROR] Could not find win32 encryption library C:\PokemonGo-Map-develop\pogom\encrypt32bit.dll
Traceback (most recent call last):
  File "runserver.py", line 55, in <module>
    encryption_lib_path = get_encryption_lib_path()
  File "C:\PokemonGo-Map-develop\pogom\utils.py", line 320, in get_encryption_lib_path
    raise Exception(err)
Exception: Could not find win32 encryption library C:\PokemonGo-Map-develop\pogom\encrypt32bit.dll

I cant find any references to this error. Could anyone help me out?

**Comment by Cronick** [comment]
Have you checked if the encrypt32bit.dll file is in the pogom folder?

**Comment by forsakenzombi** [comment]
no its not there.... didnt come with the download?

**Comment by Cronick** [comment]
Download the latest develop build, and you should be good to go.

**Comment by forsakenzombi** [comment]
i did... ill try again.

**Comment by JZ6** [comment]
perhaps something removed it, a antivirus maybe?

**Comment by forsakenzombi** [comment]
disabled all that. second go around worked though. Thanks
