### ISSUE TITLE
[Feature Request] Сhange the move algorithm to avoid exceeding the speed limit

### ISSUE THREAD

**Issue by he3amo** [PokemonGoMap/PokemonGo-Map#1542]
Сhange the move algorithm to avoid exceeding the speed limit.

## Expected Behavior

Each worker moves in personal zone.

## Current Behavior

Now map works very well, accs not banned or CAPTCHA. But sometimes some workers jumps too far, and not show poke where they are always (like when drive over 40km/h).

## Possible Solution

Change move algorithm, to each worker moves in personal zone, and not teleport too far.

**Comment by m3g4mInD** [comment]
@he3amo  And why you cant do like this?

nohup python runserver.py -os -l 'Latitude,Longitude' &
sleep 0.5;
        
nohup python runserver.py -ns -l 'Latitude,Longitude' -st 5 -u account -p 'password' -u account -p 'password' &
sleep 0.5;
            
nohup python runserver.py -ns -l 'Latitude,Longitude' -st 5 -u account -p 'password' -u account -p 'password' &
sleep 0.5;

I use like that and work fine,the "account" stay in 5 steps not more.

Use this  https://beccasafan.github.io/pgm-multiloc/  :)

**Comment by he3amo** [comment]
@m3g4mInD thx man!!!

**Comment by m3g4mInD** [comment]
@he3amo  Test that and tell us if work like you need 🎱

**Comment by he3amo** [comment]
@m3g4mInD work well. Sometimes returns 0/0/0, set -sp to 11 for best results. With -sp 11 now everything is fine. Step 3, 11 accs.

**Comment by m3g4mInD** [comment]
@he3amo  i use  -st 4 or  -st 5 depende how mucht acc i gonna put ,if +75 acc i use -st 5 or + if not i use 
-st 3 max -st 4.  :)
