### ISSUE TITLE
Empty Map Response - TOS required

### ISSUE THREAD

**Issue by uHDMI** [PokemonGoMap/PokemonGo-Map#1543]
With the update of the PGoApi the script for the accept tos doesn't work anymore.

Has the PogoMap the support for the **mark_tutorial_complete** function for new accounts?

**Comment by filippounitn** [comment]
use pikaptcha for that, pokemongomap purpose is another.

**Comment by BaIthamel** [comment]
This is for Pogomap not acc gen.
