### ISSUE TITLE
Auto enable "Start at user's location"

### ISSUE THREAD

**Issue by fmonts** [PokemonGoMap/PokemonGo-Map#156]
I'm trying to automatically use the position of the user visiting the site. 

## Expected Behavior
When a user visits the page, he expects to see the pokemons in his surroundings. 
There should be a command-line/config.ini parameter to automatically set and scan the user position.
The default location should be used only if he declines the permission to use the device location.

## Current Behavior
When I visit the page from a new device (or incognito window), the map always loads the default location.
I can't find a way to achieve the expected behaviour.

## Your Environment
dev branch pulled few minutes ago

**Comment by JZ6** [comment]
its one click of a button?

**Comment by fmonts** [comment]
The average user doesn't even know that that button exists...

**Comment by darkelement1987** [comment]
Go to /static/dist/js/map.built.js and change the following line:

`  'startAtUserLocation': {
    default: false,
    type: StoreTypes.Boolean

To

  'startAtUserLocation': {
    default: true,
    type: StoreTypes.Boolean`

**Comment by fmonts** [comment]
@darkelement1987 thank you so much.
I've edited the /static/js/map.js instead, so it doesn't get overwritten when I run the update script.
