### ISSUE TITLE
[ READ ME ] - MAJOR SECRITY - [ MAJOR ]

### ISSUE THREAD

**Issue by xZeroMCPE** [PokemonGoMap/PokemonGo-Map#1564]
So here you go, This thing is a scam and it's stealings your informations.

I've installed it, used my google account, after a few mins... My google account was signed off my Googlge Chrome, and it said someone had access to my password, i was able to reset it since my phone was linked to it..

But anyways, DO NOT INSTALL THIS OR USE YOUR GOOGLE ACCOUNT... THE CREATOR OR TEAM MEMBER ARE SCAMMERS....

EDIT: all  that above, was just BULLSHIT.

**Comment by Extrememist** [comment]
Lol, W/e probably got malware <3, works fine here

**Comment by Janglinator** [comment]
It's open source, check for yourself  :)

**Comment by xZeroMCPE** [comment]
Actually, nvm.....

The issue was cause PokemonGoMap uses a poor connection system for connecting to google map api, which means it triggers google map system...


This should be fixed!

**Comment by Janglinator** [comment]
Either way, you probably shouldn't use a legit account for mapping, you risk getting it banned.  Create a BS account, coupled with a BS email, and even if the devs were malicious, you'd have nothing to worry about!

**Comment by k4n30** [comment]
> which means it triggers google map system

I'd hope so

**Comment by FrostTheFox** [comment]
Don't make issues like this without doing proper research.

**Comment by Janglinator** [comment]
Awwww it was fun while it lasted.  Now nobody's gonna see it  :(

**Comment by FrostTheFox** [comment]
In fact, there's issues already created in the past with the same thing.

**Comment by FrostTheFox** [comment]
@Janglinator It looks bad from the issues list and it's pointless, not gonna keep it open lol.

**Comment by xZeroMCPE** [comment]
@FrostTheFox Link me to the issue that was created in the past
