### ISSUE TITLE
Multiple webhooks doesn't work

### ISSUE THREAD

**Issue by rapinou** [PokemonGoMap/PokemonGo-Map#157]
It seems that the feature to configure multiple webhooks does not work.
When i configure two webhooks (in command line or in config.ini ), the only one that works is the last of the line.

**Comment by rapinou** [comment]
If it could help, you can see this issue post on Pokelyzer repo : https://github.com/Brideau/pokelyzer/issues/69

**Comment by Brideau** [comment]
Just for clarification, it _does_ work via the command line, but does not seem to work from the config.ini from my tests.

**Comment by rapinou** [comment]
Thanks for helping.
But on my test, it doesn't work on command line too. But maybe it's my fault.
I type this : runserver.py -wh http://127.0.0.1:4000 -wh http://127.0.0.1:9876
This is right ?

**Comment by rapinou** [comment]
Ok, understood the pb.
The good syntax is : runserver.py -wh http://127.0.0.1:4000 http://127.0.0.1:9876
So it's ok for run 2 webhooks with command line, but not in config.ini.

**Comment by sebastienvercammen** [comment]
Guys, this does work, just quote your webhooks in config.ini:

`webhook: "http://127.0.0.1:4000 http://127.0.0.1:9876"`

This is [a non-issue](http://www.urbandictionary.com/define.php?term=pebkac).

**Comment by cecca00** [comment]
webhook: "http://127.0.0.1:4000 http://127.0.0.1:9876" doesn't work
webhook: http://127.0.0.1:4000 http://127.0.0.1:9876 doesn't work too

**Comment by neutron666** [comment]
This still does not work, as @cecca00 mentioned, both variants in config.ini don't work, if you provide the same via command line switch, it works..

**Comment by cecca00** [comment]
webhook: "http://127.0.0.1:4000 http://127.0.0.1:4001" returns
[    wh-updater-0][       webhook][   DEBUG] No connection adapters were found for '"http://127.0.0.1:4000 http://127.0.0.1:4001"'

webhook: http://127.0.0.1:4000 http://127.0.0.1:4001 returns
[    wh-updater-0][       webhook][   DEBUG] Failed to parse: 127.0.0.1:4000 http:

I also tried with '', [], {}, comma between webhooks and multiple webhook lines, no success
@sebastienvercammen have you tried what you are saying?
@BaIthamel could we please reopen this issue? I really want to put my webhooks in the config file

**Comment by neutron666** [comment]
Same here. Please reopen.

**Comment by neutron666** [comment]
No one interested in this?

**Comment by NHLGames** [comment]
Not sure if people are still having trouble but if you use this syntax in config.ini it works:

webhook: [http://127.0.0.1:4000, http:127.0.0.1:4001]
