### ISSUE TITLE
[Feature Request] Add detailed gym filter on the sidebar

### ISSUE THREAD

**Issue by jabberjabber** [PokemonGoMap/PokemonGo-Map#1574]
alp-bitcoin submitted a PR for this but closed it because he didn't want to maintain it anymore:
https://github.com/PokemonGoMap/PokemonGo-Map/pull/1288

Would appreciate if someone else could pick this up and re-submit it.

![](https://cloud.githubusercontent.com/assets/733852/18771768/1b249d26-8107-11e6-87db-24a709d56352.png)

**Comment by Rook25** [comment]
I'm really keen on this getting re-opened as well.

**Comment by slagell** [comment]
That is really cool.

**Comment by Rook25** [comment]
@jabberjabber I got sick of hoping someone would re-submit it, so I did. #1700 

There were a few little errors that I've fixed up as well. Let me know if you have any suggestions.
