### ISSUE TITLE
Confirm achievements/levelups/popups to prevent captcha's

### ISSUE THREAD

**Issue by obiwankoban** [PokemonGoMap/PokemonGo-Map#1575]
## Expected Behavior
No captcha's appear, but this is too far-fetched. 

## Current Behavior

When a scan account reaches a milestone (like 100km walked, the popup is never clicked and thus after a time the account must fill in a captcha.

## Possible Solution

I've noticed that confirming popup's like achievement achieved and levelup will hold of captcha's.
More thing could be taken into account, but I'm certain that not clicking away an achievement for some time will certainly trigger a captcha.
So solution: if popup appears, confirm the message. (not certain if this can be reproduced by restarting the scanner?

## Steps to Reproduce (for bugs)

1. create new account
2. accept tos, capture 2 pokemons to achieve lvl 2
3. scan until 100 km has achieved
4. keep scanning, observe captcha shortly thereafter.

## Your Environment

* Version used:
* Environment name and version (e.g. Python 2.7):
* Operating System and version (desktop or mobile):

**Comment by Arengo** [comment]
Nope, doesn't help.
https://github.com/PokemonGoMap/PokemonGo-Map/pull/1566/files#diff-541e2b217ba4a7d7859dae2cb443b6b7R826

**Comment by obiwankoban** [comment]
Has anyone tried with accounts that have passed the tutorial already? (lvl 5+, first pokemon & pokestop captured, level bar turned blue instead of green)
