### ISSUE TITLE
[Feature Request] Possibility to use a starting step argument. Allows easy massive scan hexagons.

### ISSUE THREAD

**Issue by kafeijao** [PokemonGoMap/PokemonGo-Map#159]
Adding an -sts (for example) argument to define the starting step. This way with the -st argument I could have a giant Hexagon with multiple instances running, not needing to worry with position change calculations that I have if I use the beehives. It would be as simple as defining for example:

- 1st instance -sts 0 -st 10
- 2nd instance -sts 11 -st 15
- 3rd instance -sts 16 -st 20

So we would have a 20 steps hexagon being scanned by 3 diferent instances.

If we wanted to change location, we just had to change all the locations to the same value.

## Possible Solution

I'd guess it should be easy as adding the argument and when generating the steps only generate certain steps depending on the argument provided... I would implement myself but I never programmed in Python.

## Context

I find it hard to manage multiple hexagons in the beehive formation. I think this would be another way to set up, also gives more flexibility to the scan area.

Thanks is advance if someone could implement this :)

**Comment by sorokyl** [comment]
Um, you don't need to run multiple instances to scan a large area. You just specify multiple accounts and it will run that much faster (10 accounts scan 10 times faster than 1 account)

A normal beehive is completely obsolete now, unless you generate it and then delete some of the hexagons for efficiency.

The feature you request seems useless with the implementation of multiple accounts.

**Comment by kafeijao** [comment]
I might be mistaken, but as far as I understand having only 1 instance running makes the CPU use 1 core at max, while if I have multiple instances running it can use more cores (correct me if I'm wrong please).

Currently I'm scanning a 23 step area, before the API update I could do it within 1 minute tops (using 100 accs), now it takes 6-7minutos. My CPU is limiting it, so I was wondering if I could use this to use the remaining cores of the CPU.

**Comment by sorokyl** [comment]
Please do not do something so greedy as scanning 23 step area every single minute.  That's greedy as hell and that's why we can't have nice things.

**Comment by kafeijao** [comment]
It's not constantly scanning. It does only when requested and scans for 5 minutes.

That's why I need this, I use this large scan around 9-10times / day and during 5 minutes each time. It will be useless if it takes more than 5 minutes to complete as it leaves me no time to reach the place in such big area.

**Comment by BaIthamel** [comment]
For feature requests please migrate this to the new feature page
http://feathub.com/PokemonGoMap/PokemonGo-Map/
Thankyou!

**Comment by CoolCanuck** [comment]
@BaIthamel This request needs to be opened again. FeatHub is no longer used. Good riddance.
