### ISSUE TITLE
[Feature Request] Make it possible to pass latitude/longitude to the map (to use in conjunction with PokeAlarm)

### ISSUE THREAD

**Issue by Imoq** [PokemonGoMap/PokemonGo-Map#1592]
Right now you can have your map on https://www.yourdomain.com/ and no matter where you navigate inside, the URL will always be the same for the map.

[PokeAlarm](https://github.com/kvangent/PokeAlarm), which is very popular notification system currently uses webhooks to identify if a Pokémon has popped, receiving the pop information. Then you can configure it to be notified on different ways (I have set up Telegram and Twitter for now) but it will show you the Pokémon location using Google Maps. It would be very nice if the alerts sent you to your own map instead (something like https://www.yourdomain.com/loc?lat=43.2803852&lon=5.3841092999999995), so you could even see the Pokémon around the rare you found.

I've suggested that on PokeAlarm (https://github.com/kvangent/PokeAlarm/issues/273) as I thought this functionatlity was already built on the map (I use it with -fl) but it looks like it isn't.

Would this be very hard to implement? Thanks!

**Comment by slgphantom** [comment]
https://github.com/kvangent/PokeAlarm/wiki/Webhook-Standard

Actually, your PokeAlarm will receive the lat/lon info from the webhook. What you need to do is just modify the PokeAlarm a bit and allows it show the lat/lon in the alert using something like <lat>,<lon>

**Comment by Imoq** [comment]
Thanks to mew905 on Discord, I learned that adding these lines to near the end of map.js used to work to get this functionality:

```
var match = window.location.search.match(/\?lat=(.*?)&lon=(.*)/);
    if (match != null) {
        var  lat = match[1]
            ,lon = match[2];
        centerMap(lat, lon, 14);
    }
```

And then just access the map with:

http://yoururl.com/?lat=xx.xxxx&lon=xx.xxxxx

But it doesn't seem to work anymore. It could be a good start point, anyway if anybody with the right knowledge could take a look at this :)

**Comment by Imoq** [comment]
Thanks to midadami from Discord who made this work! It's just a matter of putting mew905's code in the right place, on map.js right in this position:

```
  $('#scan-here').on('click', function () {
    var loc = map.getCenter()
    changeLocation(loc.lat(), loc.lng())

    if (!$('#search-switch').checked) {
      $('#search-switch').prop('checked', true)
      searchControl('on')
    }
  })
var match = window.location.search.match(/\?lat=(.*?)&lon=(.*)/);
    if (match != null) {
        var  lat = match[1]
            ,lon = match[2];
        centerMap(lat, lon, 16);
    }
}

function updateLocationMarker (style) {
  if (style in searchMarkerStyles) {
    locationMarker.setIcon(searchMarkerStyles[style].icon)
    Store.set('locationMarkerStyle', style)
  }
  return locationMarker
}
```

After that, just npm install, npm run build and restart the server process and now you can pass any coordinates to your map and be centered there!

Back to PokeAlarm now :)

Thanks, mew905 and midadami! Now it's just a matter to include this on a PR...

**Comment by Imoq** [comment]
This was added (and commited!) here: https://github.com/PokemonGoMap/PokemonGo-Map/pull/1601

Closing request, thank you very much to both Kevin and the Fox! :)
