### ISSUE TITLE
Ditto detection

### ISSUE THREAD

**Issue by AdrienNguyenWorldline** [PokemonGoMap/PokemonGo-Map#1593]
Accoding to Gamepress research capture rate for ditto is way lower then his fake identidy, so by just launching the encounter, 3 or 4 times harder to catch.

When launching encouters to pull IV we have in the response the pokemon level and capture rate.
By cross referencing with base capture rate of that pokemon (pidget, rattata, zubat and magikarp).
We can scan for possible dittos.

source : https://pokemongo.gamepress.gg/ditto-mechanics

**Comment by m3g4mInD** [comment]
@AdrienNguyenWorldline  this is not rue i have already catch 11 dittos and i catch in 1st pokeball ........

**Comment by aguita** [comment]
@AdrienNguyenWorldline Even if it is harder to catch, what is the issue that you are wanting solved?  You don't know it is a ditto until you actually capture it.   The code base only starts the encounter, it doesn't actually capture anything.   As such, you'd never know it was a ditto.

**Comment by WalterMagnum** [comment]
There are 2 android apps that I know of with ditto detection.  They throw balls at every single pidgey, rat, bat, and karp.  It causes massive captchas and IP bans.  It would be easy enough to make the workers throw balls, but I think it is against the spirit of the project.

**Comment by stefanvds1** [comment]
@AdrienNguyenWorldline even IF this were true, and I too believe it would be, when you encounter a ditto, or a pidgey, with a lvl 1 scanner account, the catch rate of both is 1.0 1.0 1.0
so where are you gonna get a bunch of lvl 5? accounts :)

**Comment by 3Trace** [comment]
Anyone know how this android app 'PokeTrack' figured out how to track Ditto? Or at least claimed to. - https://sites.google.com/site/poketrackapps/

**Comment by WalterMagnum** [comment]
@3Trace Look at my previous post.  That is one of the apps I am referring to.

**Comment by AdrienNguyenWorldline** [comment]
@stefanvds1 Thats a good point, I forgot that catch rate was scaling with lvl.
And I had confirmation that poketrack and now pokealert do capture to check if ditto or not.
