### ISSUE TITLE
[Feature Request] Change Location via POST request / via Telegram

### ISSUE THREAD

**Issue by spammer23** [PokemonGoMap/PokemonGo-Map#1594]
## Expected Behavior

it should be possible to change the scan location with a 3rd party programm like PokeAlarm
(It is possible to change the location on the website, so no big deal i think?)

## Current Behavior

I can only change the location on the webpage, i would like to set the location with e.g. Telegram

## Possible Solution

A url which understand a POST request with the new location?

**Comment by birdstream** [comment]
Actually there is already. Try this with curl:

curl "http://localhost:5000/next_loc?lat=${lat}&lon=${lon}" -X POST

where lat and lon is the variables containing the the latitude & longitude, respectively..

**Comment by spammer23** [comment]
Perfect, thanks.
