### ISSUE TITLE
[Feature Request] Ditto Notification

### ISSUE THREAD

**Issue by satrox28** [PokemonGoMap/PokemonGo-Map#1595]
Is it possible to track Ditto as its disguised currently as Rattata or Magikarp or Pidgey.

Any plans to show on the map, it will be very helpful, thanks for all your hard work.
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Python 2.7):
* Operating System and version (desktop or mobile):

**Comment by Maersko** [comment]
Also disguised as zubat.

**Comment by birdstream** [comment]
Maybe pulling the IV from a hidden Ditto would reveal transform/struggle moveset? I don't know. But that would mean you'd have to start an encounter with every rat/bat/pidgey/karp

**Comment by SoonDead** [comment]
Starting an encounter does not reveal it to be ditto. A worker actually needs to catch it.

**Comment by Arengo** [comment]
@FrostTheFox can be closed since only way is "botting" by catching the encounter what strikes against our rules.

**Comment by sebastienvercammen** [comment]
As mentioned, botting will not be implemented.
