### ISSUE TITLE
[Feature Request] A proper manual captcha resolver (my idea)

### ISSUE THREAD

**Issue by lluisd** [PokemonGoMap/PokemonGo-Map#1600]
Some users use that app to be run with few workers (like 10-20) and they don't want to invest on 2captcha for some reason that is out of scope.  Currently there are some PR related to manual captcha resolving but they are not a final solution and they don't join forces to make a single proper manual captcha PR. Both of them only resolves manual captchas when workers are working and I think that this is a waste of time if you cannot resolve it and many times are not solved since you only have 60 seconds and you cannot pay attention 24h on the mobile/computer. 

## Current Behavior
Manual captcha resolver is not implemented. There are some pull requests related to that but each one goes from their own (they don't join forces). One only works if you have a GUI, it's so limited. Also there is no manual captcha queue to be resolved later. Resolving manual captcha when workers are running is not the best behaviour unless you are a monkey.

## Possible Solution
The proposal is:

1. When an account encounters a captcha and you force it to be manual solved "later" (using a new optional argument) it will be put on a queue with a captcha flag. This account won't come back until the captcha is resolve (so rest time is like infinite). So a new account takes its place without waiting 60 seconds. It will be great that the new account starts in the last position but this is out of scope.

2. On /status page you can check the number of accounts that need captcha and the ones still available on each instance to have an overview. A new link/button to start resolving captchas for one instance/some instances/all instances. 

3. When the manual captcha resolver starts sents the url to the webhook and also the results after solve it (solved/failed). So you can resolve it in Desktop, mobile, or where you want by using a webhook app. Also have the possibility to solve them locally by using chrome driver like the PR1582 for people that are running it on machine that has a GUI or any other tricky way if you don't have a GUI.

4. Solved accounts are ready to use after some rest time.

**Comment by m3g4mInD** [comment]
@lluisd 100% agree

**Comment by gauravyadav26** [comment]
So many of Us wants this please consider it

**Comment by kevdotcom** [comment]
I believe some people are working on something like this but it's hard to implement afaik because we can't just click the captcha-link and solve it. 

Though I still wonder how jDownloader does it...

**Comment by Arengo** [comment]
#1567

**Comment by drallieiv** [comment]
I was planning on doing that with an external Java app : 
App listen to log message saying captcha
add blocked accounts captchas to a pool
manual solving 
and either waiting for the account recycler to pass or tell it to ?

But the this is I know that the captcha system needs a correct referer...

**Comment by drallieiv** [comment]
I am almost done, but went a tricky method to populate the list of my banned accounts : 
watch the log file, grabs logins from log, search password in csv files and add to memory storage.

**Comment by sebastienvercammen** [comment]
Feature request are now handled on the feedback forum: http://vote.devkat.org. I've copied over the details for you.
