### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by Holzberg** [PokemonGoMap/PokemonGo-Map#1616]
Today I did a clean checkout of develop and dropped and re-created the database in mysql.

I have 3 instances running.  First is for web only. The other two are searchers only.

The 2 searchers are using this command line:
--no-server --location "x,y" -bh -st 2 -w 19 -speed -kph 25 -j -sd 25 -asi 3600 -ari 900 --no-gyms --no-pokestops --acountcsv "file.csv" --captcha-solving --captcha-key "key" --login-delay 13 --purge-data 0 --disable-clean --fixed-location --gmaps-key "key" --locale en --db-type mysql --db-host 127.0.0.1 --db-name pokemongomapdb --db-user pogomapuser --db-pass mypassword

The csvs each have 115 accounts.

Both instances ran fine until initial scan got to 100% and then one instance started getting exceptions.

When I look in the log I see:
`[search-worker-13][        search][   ERROR] Exception in search_worker under account dfsdas456 Exception message: list index out of range`

The exception started with one account, moved to 4, and 9 out of the 19 get it.  I assume very soon it will be all of them.  The other instance is running fine.  They both use the same code base and the same database.

I tried verbose output and the debug output didn't help.  I don't know why the exception does not output trace info or at least the file and line the exception happened on.  I wish I had more info for you.

## Expected Behavior

There should be no exceptions.

## Current Behavior

I get the exception described above.

## Steps to Reproduce (for bugs)

You can setup your instance the same as I have mine.

## Your Environment

* Version used: develop branch
* Environment name and version (e.g. Python 2.7): Python 2.7
* Operating System and version (desktop or mobile): ubuntu 16.04 server

**Comment by Holzberg** [comment]
I was piecing my command line together so there os a duplicat "--purge-data 0" in there sorry.

**Comment by Holzberg** [comment]
This has to do with combining -bh with -speed.  these exceptions happened after initial.scan was 100%.  once a worker got an exception it would switch account, get the exception and repeat... even on restart.

I am closing this issue as the fix is to not use -bh.  Artifice is working on V2 of Speed Scan that will hopefull addeess this.

**Comment by forcewill** [comment]
I scanned spawn points with -speed first then changed to -bh (since im comparing captcha redution between both) without speed and kph i got one of this errors,
is this due to the change or unrelated to this issue ?
