### ISSUE TITLE
Fresh Develop + SpeedV2 (uncaught exception)

### ISSUE THREAD

**Issue by JoniValles** [PokemonGoMap/PokemonGo-Map#1623]
## Steps to Reproduce (for bugs)

1. git clone https://github.com/PokemonGoMap/PokemonGo-Map
2. git fetch origin pull/1617/head:Speed
3.git merge origin Speed
4. npm install... npm run build
5. python runserver.py -speed -st 10
![error](https://cloud.githubusercontent.com/assets/20915126/21082033/f5295b06-bfd2-11e6-8376-f6d6ac6b4bc8.JPG)
 -w 100 -ac accounts.csv

## Context

db-type: mySQL
Working perfectly in another branch.

Working fine in SQLite but if i use it i get DB Locked

## Your Environment

* Version used:
* Environment name and version (e.g. Python 2.7):
* Operating System and version (desktop or mobile): Windows 10

**Comment by JoniValles** [comment]
All i need it was a EMPTY database.

**Comment by springjools** [comment]
Pull requests have their own issue trackers

**Comment by smc87** [comment]
This is caused when using a database with a PR that updates the schema, and then moving back to dev branch using the same database after dev branch has had further commits that update the database schema, but not in the way the unsupported PR expected.

I dont think this is bug, but more a symptom of moving between PR's on one database.

**Comment by JoniValles** [comment]
As i said 11 days ago, "All i need it was an empty database"...

**Comment by springjools** [comment]
At least it's not a bug with the clean development version.

**Comment by sebastienvercammen** [comment]
Caused by user error. Closed.
