### ISSUE TITLE
[Frontend] Transform move missing, sidebar not working

### ISSUE THREAD

**Issue by walaoaaa1234** [PokemonGoMap/PokemonGo-Map#1625]
## Expected Behavior
As expected?

## Current Behavior
When click on gym with ditto inside, gym sidebar is not working/gym sidebar view the last gym information click recently.

## Possible Solution
Add transform move to "/static/data/moves.json".

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Python 2.7):
* Operating System and version (desktop or mobile):

**Comment by walaoaaa1234** [comment]
#1628

**Comment by sebastienvercammen** [comment]
#1628 merged
