### ISSUE TITLE
IndexError: list index out of range exception in pogom/proxy.py

### ISSUE THREAD

**Issue by birdstream** [PokemonGoMap/PokemonGo-Map#1627]
## Expected Behavior

Proxy rotation should work

## Current Behavior

It doesn't, unless i chose to use 'random' proxy rotation

## Possible Solution

Submitted a PR: #1626 

## Steps to Reproduce (for bugs)

1. Run map with proxy with 'round' or 'none' proxy rotation
2.
3.
4. IndexError exception...

**Comment by sebastienvercammen** [comment]
Fixed with merge of #1619.
