### ISSUE TITLE
[Bug?] Deadlock found when trying to get lock; try restarting transaction

### ISSUE THREAD

**Issue by slideup-benni** [PokemonGoMap/PokemonGo-Map#163]
## Expected Behavior
work normally

## Current Behavior
get messages like:

`2016-08-08 17:43:44,689 [ search_worker_0][        models][ WARNING] (1213, u'Deadlock found when trying to get lock; try restarting transaction')... Retrying`

or

`2016-08-08 17:51:15,032 [ search_worker_0][        models][ WARNING] (1205, u'Lock wait timeout exceeded; try restarting transaction')... Retrying`

## Possible Solution
make sql locks in the same order? maybe?

## Context
running multiple instances with mysql  Ver 15.1 Distrib 10.0.23-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2 

## Your Environment
* Version used: commit ed4d9465a772ceed7bd92437de23f20d6b02d1f6
* Operating System and version (desktop or mobile): Debian

**Comment by slideup-benni** [comment]
Sorry guys, this was my mistake. My SQL-Trigger done some weird

**Comment by DeviantEng** [comment]
@slideup-benni Care to elaborate what you did to resolve this?  I'm starting to get these errors when using a large number of accounts.

**Comment by slideup-benni** [comment]
that has nothing to do with this code here. I have add some triggers and that caused the problem
