### ISSUE TITLE
christmas pikachu

### ISSUE THREAD

**Issue by quixfz** [PokemonGoMap/PokemonGo-Map#1630]
i've made a nice icon of pikachu with the hat. made from a screenshot from the game. looks fine on the map.

here is is:
[http://pg.festzeit.ch/static/icons/25c.png](http://pg.festzeit.ch/static/icons/25c.png)

i've hardcoded it inside the js, so it adds the 'c' when pokemon_id is 25. dont replace the old 25.png, caching we'll load the old version for some users.

one could add a date-check and only load this icon until december 29th or so.

**Comment by GyselAnimatioon** [comment]
Very nice Icon :3

**Comment by pbrent84** [comment]
This works out a lot better no need to hardcode anything and just revert afterwards!

Drop in "\PokemonGo-Map\static\" replacing icons-sprite.png&icons-large-sprite.png respectfully.

![icons-sprite](https://cloud.githubusercontent.com/assets/21188643/21174830/661ba630-c1ad-11e6-93ab-3c1e1facfe22.png)
![icons-large-sprite](https://cloud.githubusercontent.com/assets/21188643/21174831/661e8990-c1ad-11e6-913a-198825013402.png)

**Comment by divnotded** [comment]
For those using slack with PokeAlarm I substituted the Santachu file you can point the Slack_alarm.py icon url to here and it will put Santachu into the feed. https://raw.githubusercontent.com/divnotded/PokeAlarm/master/icons/<id>.png
Then just revert it back after event

**Comment by Hydrargyrum-Wells** [comment]
Wild Raichu wear Santa hats, too.

**Comment by Arengo** [comment]
I will leave the shuffled version here
![icons-shuffle-sprite](https://cloud.githubusercontent.com/assets/22680515/21442256/07450790-c89d-11e6-9a19-bdaa90724840.png)

**Comment by sebastienvercammen** [comment]
This is not what Github issues are for.
