### ISSUE TITLE
[Feature Request] Search for gym members

### ISSUE THREAD

**Issue by jane0815** [PokemonGoMap/PokemonGo-Map#1635]
It would be nice if we could search for pokemons in gyms to could find gyms with new pokemons to fill our pokedex. We could at least get the grey pokedex entry for the pokemons that currently are only available in eggs for example.

**Comment by sebastienvercammen** [comment]
Feature request are now handled on the feedback forum: http://vote.devkat.org. I've copied over the details for you ("Filter gyms").
