### ISSUE TITLE
[BUG-important] Weebhooks sometimes don't work as intended

### ISSUE THREAD

**Issue by filippounitn** [PokemonGoMap/PokemonGo-Map#1644]
## Expected Behavior
All webhooks are sent to another program like PokeAlarm. If an error occurs pokemongomap double checks
## Current Behavior
Some webhooks are lost.
If an error occurs PGM ignores it.
From pokealarm: https://github.com/kvangent/PokeAlarm/issues/281
"kvangent commented 8 minutes ago
So essentially the problem is that PokemonGo-Map doesn't check to make sure that the target server actually received the webhook, or even check to make sure it was accepted correctly. Also, due to the way the error catching is set up, if anything bad happens Pokemon-Go Map just ignores it.

What needs to happen is PokemonGo-Map needs to have the webhook portion rewritten to be more robust."

## Steps to Reproduce (for bugs)
1. start map
2. set webhooks
3. set pokealarm
4. not all pokemons are sent.

## Your Environment

* Version used: latest
*Python 2.7
* windows server 2012

**Comment by midadami** [comment]
I can confirm I have been having this problem for more than a month.

**Comment by sebastienvercammen** [comment]
Fixed by #1666, needs review.
