### ISSUE TITLE
-Speed Initial Scan constantly retrying on 0/0/0 Scans

### ISSUE THREAD

**Issue by bbdoc** [PokemonGoMap/PokemonGo-Map#1669]
## Expected Behavior

Speedscan Initial Scan should be able to recognize that some zones simply have no stops/pokemons/gyms, which frequently happens in rural areas. After a few 0/0/0 scans, initial scan should consider the cell as empty. 

## Current Behavior

At the moment, it simply puts the cell back in queue and rescans.

Example : 

```
Bad scan. Parsing found 0/0/0 pokemons/pokestops/gyms
Common causes: captchas, IP bans, or using -ng and -nk arguments
Putting back step 284 in queue
```

## Steps to Reproduce (for bugs)

Scan new zones with lots of empty spots

## Context

Trying to scan a rural area with lots of 0/0/0 zones. Initial Scan is being stuck and takes forever for a few %.

## Your Environment

Using latest dev.

**Comment by walaoaaa1234** [comment]
+1

**Comment by TheNewDarkOne** [comment]
+1. Although I'm not sure what solution is, except maybe give up on a cell after x failures and move on?

**Comment by Zyrix** [comment]
Having the same behavior.

**Comment by vlalo001** [comment]
+1 Getting this error when scanning various st's (tested with -st 20 and -st 25). The problem is, bad scans are added back into queue and then are re-tried infinitely until the instance stops working. Therefore, initial scanning cannot complete unless we define something like a MAX_BAD_SCAN until the step is no longer added back into queue. Although a better solution is always welcome. Thanks for the help

**Comment by bbdoc** [comment]
@vlalo001 How do you define a MAX_BAD_SCAN ?

**Comment by vlalo001** [comment]
I wish you could. It's merely one of my suggestions at a fix.

**Comment by Zyrix** [comment]
Here is a quick fix that I'm using:
`
# If we had a 0/0/0 scan, then unmark as done so we can retry, and save for Statistics
elif parsed['bad_scan']:
                self.scans_missed_list.append(cellid(item['loc']))
                item['done'] = None
                if item.get('retry') is None:
                    item['retry'] = 1
                    log.info('Putting back step %d in queue, retry %d', item['step'], item['retry'])
                elif item['retry'] < 3:
                    item['retry'] += 1
                    log.info('Putting back step %d in queue, retry %d', item['step'], item['retry'])
                else:
                    item['done'] = 'Missed'
                    log.info('Giving up on step %d after 3 retries', item['step'])
`

If I have some time tonight I will create a proper parameter for this and create a pull request.

**Comment by jagauthier** [comment]
I am still having this problem.  I tried PR 1672 and this one.  Eventually my initial scan goes into the 90%s and good scans goes to 0%.  This was with an -st of around 12.  I moved my -st to 4, and was able to get 100/100. It's is definitely area specific.

**Comment by sclo012** [comment]
This should definitely be a priority, as many scans will simply be wasted while still contributing to captchas.

**Comment by sebastienvercammen** [comment]
With all recent changes, the only remaining bad scans should be IP or account bans, all other cases are handled properly.

To get the latest version:
```
git pull
pip uninstall pgoapi
pip uninstall protobuf_to_dict
pip uninstall protobuf3-to-dict
pip install -r requirements.txt --upgrade
```
