### ISSUE TITLE
Full Stats page - last seen time "wrong"?

### ISSUE THREAD

**Issue by Sejadis** [PokemonGoMap/PokemonGo-Map#167]
## Expected Behavior

last seen time should tell me when the pokemon spawned the last time or at least the last time it was scanned

## Current Behavior

the last seen time on the full stats page currently is the time of the last despawn

**Comment by BaIthamel** [comment]
For feature requests please migrate this to the new feature page
http://feathub.com/PokemonGoMap/PokemonGo-Map/
Thankyou!

**Comment by CoolCanuck** [comment]
@BaIthamel This request needs to be opened again. FeatHub is no longer used. Good riddance.
