### ISSUE TITLE
Read web hooks from a file [feature request]

### ISSUE THREAD

**Issue by bluemode** [PokemonGoMap/PokemonGo-Map#1673]
## Expected Behavior
an added command and config flag that would load a list of web hooks

## Current Behavior
Currently, you must either type in each web hook in to command line or config. When dealing with a large amount of web hooks, this becomes a chore. 

## Possible Solution
similar to proxy file vs proxy 

## Steps to Reproduce (for bugs)
1. Type in 200 web hooks into 6 -ns with each one needing different web hooks
2. Gently sob

## Context
Motivation= Laziness 

## Your Environment
Current dev
Python 2.7 
Desktop PC/Mac
Neutrals with a splash of color in the area rug and kitchen

**Comment by sebastienvercammen** [comment]
Feature request are now handled on the feedback forum: http://vote.devkat.org. I've copied over the details for you.
