### ISSUE TITLE
[Bug?] Only empty scans after 1 hour - Captchas and IPs are fine

### ISSUE THREAD

**Issue by minim8** [PokemonGoMap/PokemonGo-Map#1681]
Win10
Python 2.7.12
pip 8.1.1
node v6.9.4
npm 3.10.10

Worked fine yesterday but as of today I started to receive almost solely empty results after about 1 hour of correct scanning. Restarting solves this problem but again works only for roughly an hour. 
Captchas are solved correctly and the IP seems fine. I also tried a set of different accounts but ran into the same issue. 

Also tried it with a small area with -speed, -j, -st7, -sd29 and it still happens.. I would really appreciate help on this matter since I don't know what else to do.

**Comment by cydine** [comment]
Maybe try a `pip install -r requirements.txt --upgrade --force-reinstall`

**Comment by JoniValles** [comment]
Because your accounts are in a -ng,-np,-nk loop. Try this: https://github.com/PokemonGoMap/PokemonGo-Map/pull/1672

**Comment by minim8** [comment]
@JoniValles thank you, this seems like it could be the reason for my problems! will try it out asap

**Comment by sebastienvercammen** [comment]
With #1672 merged and all of our latest changes, this issue should no longer exist. Any continuous "bad scans" that still occur, are only related to captcha'd accounts (which will also be handled properly, especially with recent changes) or to an IP/account ban.

To get the latest version:
```
git pull
pip uninstall pgoapi
pip uninstall protobuf_to_dict
pip uninstall protobuf3-to-dict
pip install -r requirements.txt --upgrade
```
