### ISSUE TITLE
[Feature Request] Passsword protect the map

### ISSUE THREAD

**Issue by tokar86a** [PokemonGoMap/PokemonGo-Map#1687]
I would like to see some sort of simple user system so you need to be able to sign in to view the map or enter some sort of password.

**Comment by pve83** [comment]
make it with work reverse proxy and httacces

**Comment by m3g4mInD** [comment]
Nginx   https://pgm.readthedocs.io/en/develop/extras/nginx.html

**Comment by sebastienvercammen** [comment]
As mentioned by others, using a non-dev (Flask) webserver with authentication support is the best route to go. Closing this PR.
