### ISSUE TITLE
Got problem with Api key

### ISSUE THREAD

**Issue by dachoj** [PokemonGoMap/PokemonGo-Map#1698]
Hey guys,

I just started using this great scanner but documentation is a bit outdated and I can't make my scaner to work. This is one of the errors that I get in console:
![bez tytulu](https://cloud.githubusercontent.com/assets/2480262/21822491/aa101d3c-d777-11e6-9bca-58115e2a9d01.png)

Besides of that I get "-speed" error frequently when scanning. I appreciate all the help, thanks in advance!

**Comment by sebastienvercammen** [comment]
Github is not a customer support platform. You can always try asking more specific questions in [our Discord's #help channel](https://discord.gg/PWp2bAm).
