### ISSUE TITLE
[Feature Request] Allow the user to choose if they want to see the weight and size of Pokemon

### ISSUE THREAD

**Issue by zenoncrow** [PokemonGoMap/PokemonGo-Map#1704]
Allow the user to choose if they want to see the weight and size of Pokemon.

## Expected Behavior
Pull the weight and size of Pokemon and show it alongside IVs and moveset.

## Current Behavior
For now the map doesn't show the size and weight of a Pokemon.

## Context
I know for sure that pulling the weight and height along with IVs and moveset is possible, so why not make it an option?
Seeing the exact weight of Magicarp would help catch those big enough for the Fisherman medal. Seeing the exact size of the Rattata would help catching those small enough for Youngster medal.
Granted the medals don't do anything for now, but this options might help completionists such as myself, and I still believe these medals will come in handy just like the type-medals did. 
Without this feature it's harder to plan a hunting route (epsecially now, in sub-zero temperatures) since there are dozens of Rattata and there aren't many little ones (I have around a thousand Rattata caught since day 1 of playing and only around a 100 of them are tiny and therefore are suited for the medal).

**Comment by quixfz** [comment]
this also went through my head... i'll try to hack something together... the medals are based on weight, rattatas have to be under 2.5kg and magikarps over 13.6kg.

sources:
- https://www.reddit.com/r/TheSilphRoad/comments/57kayh/youngster_medal_help/
- several posts about magikarp, but none looks as good and confident as the rattata one

**Comment by zenoncrow** [comment]
@quixfz thanks, that would be very neat! Although I'm still unsure about the requirements. I caught a lot of XS weighted Rattata yesterday (under 2.5kg) but none counted towards the medal. Instead the ones that counted were Rattata with the XS size. On the other hand, Magikarp counted with XL weight. I'm gonna have a break from work in an hour and try to research this matter.

**Comment by quixfz** [comment]
alright, as i was encountering magikarps anyway, i added this code right after the encounter:
`                if p['pokemon_data']['pokemon_id']==129 and pokemon_info['weight_kg']>13.59:
                    pokemon_info['move_2']=pokemon_info['move_1']`
this then gets handled in javascript on the map. magikarp has only one moveset, and no one cares about it anyway.

**Comment by zenoncrow** [comment]
@quixfz so, I squeezed my lunch break a little earlier, and I was lucky to already find these:
2.44kg XS Rattata I caught didn't count towards the medal, but 2.31kg XS Rattata did. I didn't get any XS sized Rattata though.
Thanks for the code! Now I at least have and idea on how this works.

**Comment by quixfz** [comment]
the code is a very dirty hack. it encodes the XL magikarp as having 2 same moves. 
this is running on the top left big region on this site: http://pg.festzeit.ch/index2.php
XL magikarps are yellow instead of orange.

**Comment by zenoncrow** [comment]
@quixfz wow, that's a very nice map you've got there!
btw I believe one doesn't necessarily need to make it have the same moves? How is it possible to make it look like yours? Like different color if weight is something or the other and a bigger sprite if IVs are high enough?

**Comment by quixfz** [comment]
i'm encding it that way. otherwise one would have to add a additional column to the database... much more work and i wouldn't want a bigger db for something like this.

it's a completly different frontend... i'm using a different icon when id==129 and move1==move2

**Comment by zenoncrow** [comment]
@quixfz I see, your map resembles pogom very much. I'm not a python programmer, I only used to learn php and mysql long ago, so I might not have a very good idea of what's getting from what in here. I can't understand where is the code that uses db queries (as I believe the api is used to store all the data in the DB and then it gets extracted from a DB to draw a map in the browser). 
Wouldn't it be possible to make it like:

`if p['pokemon_data']['pokemon_id']==129 and pokemon_info['weight_kg']>13.59: pokemon_info['move_1']='big_karp'`

And then get to the map drawing part to assign a code like
`if pokemon_info['move_1']='big_karp';
use a url to a new icon instead of a standart one`
?

**Comment by sebastienvercammen** [comment]
Feature request are now handled on the feedback forum: http://vote.devkat.org. I've copied over the details for you.
