### ISSUE TITLE
runserver.py issue - windows

### ISSUE THREAD

**Issue by DrTeej** [PokemonGoMap/PokemonGo-Map#173]
C:\Users\Mr Fluffy Pants\Desktop\PokeMap\PokemonGo-Map-MAIN>runserver.py
Traceback (most recent call last):
  File "C:\Users\Mr Fluffy Pants\Desktop\PokeMap\PokemonGo-Map-MAIN\runserver.py
", line 45, in <module>
    from pogom.app import Pogom
  File "C:\Users\Mr Fluffy Pants\Desktop\PokeMap\PokemonGo-Map-MAIN\pogom\app.py
", line 17, in <module>
    from .models import Pokemon, Gym, Pokestop, ScannedLocation
  File "C:\Users\Mr Fluffy Pants\Desktop\PokeMap\PokemonGo-Map-MAIN\pogom\models
.py", line 19, in <module>
    from .customLog import printPokemon
  File "C:\Users\Mr Fluffy Pants\Desktop\PokeMap\PokemonGo-Map-MAIN\pogom\custom
Log.py", line 5, in <module>
    args = get_args()
  File "C:\Users\Mr Fluffy Pants\Desktop\PokeMap\PokemonGo-Map-MAIN\pogom\utils.
py", line 150, in get_args
    num_usernames = len(args.username)
TypeError: object of type 'NoneType' has no len()

## Steps to Reproduce (for bugs)
I've completely removed pip. Reinstalled pip and setuptools. Re-run the requirements install. Still can't get this working. Just pops this error.

## Your Environment

* Version used: 2.2.0?
* Environment name and version (e.g. Python 2.7): Python 2.7
* Operating System and version (desktop or mobile): Windows

**Comment by DrTeej** [comment]
I think I got it working.

**Comment by talok** [comment]
How did you make it work? solution?

**Comment by coffman34** [comment]
I love it when people fix something without letting others know what they did to fix it...

**Comment by DrTeej** [comment]
Grumpy Grumpy.

I don't know how I fixed it. It wasn't running properly. I kept testing different strings of commands and it ended up working.

I didn't really change much - just what I was giving in the commands themselves.

**Comment by talok** [comment]
I figured it out. My problem is the single quotes are not the same. 

For example, 
`python ./runserver.py -a google -u ’USERNAME' -p ‘PASSWORD'`

as you can see, there are two types of single quote ’', just use only this one ' and it works.
