### ISSUE TITLE
Error installing requirement. 

### ISSUE THREAD

**Issue by AlooshXP** [PokemonGoMap/PokemonGo-Map#174]
Im getting an error while trying to install the requirement. and this is the error:

Collecting pgoapi from git+https://github.com/keyphact/pgoapi.git#egg=pgoapi (from -r requirements.txt (line 18))
  Cloning https://github.com/keyphact/pgoapi.git to c:\users\ali\appdata\local\temp\pip-build-tkiqea\pgoapi
  Error [Error 2] The system cannot find the file specified while executing command git clone -q https://github.com/keyphact/pgoapi.git c:\users\ali\appdata\local\temp\pip-build-tkiqea\pgoapi
Cannot find command 'git'

I have tried uninstall python and reinstalling it but i can't seem to find a solution for this. i hope you can help :)

## Your Environment

* Version used: Latest
* Environment name and version (e.g. Python 2.7):
* Operating System and version (desktop or mobile): Windows 10

**Comment by DeviantEng** [comment]
> Cannot find command 'git'

That's you're problem.

https://git-scm.com/download/win

**Comment by MatoC9** [comment]
I had same problem, after installing git and trying to install requirements I get this error:
```
Collecting pyproj (from LatLon==1.0.1->-r requirements.txt (line 17))
  Using cached pyproj-1.9.5.1.tar.gz
    Complete output from command python setup.py egg_info:
    using bundled proj4..
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\admin\appdata\local\temp\pip-build-div0s2\pyproj\setup.py", line 72, in <module>
        objects = cc.compile(['nad2bin.c', 'src/pj_malloc.c'])
      File "c:\python27\lib\distutils\msvc9compiler.py", line 473, in compile
        self.initialize()
      File "c:\python27\lib\distutils\msvc9compiler.py", line 383, in initialize
        vc_env = query_vcvarsall(VERSION, plat_spec)
      File "c:\python27\lib\site-packages\setuptools\msvc.py", line 173, in msvc9_query_vcvarsall
        return EnvironmentInfo(arch, ver).return_env()
      File "c:\python27\lib\site-packages\setuptools\msvc.py", line 1107, in return_env
        [self.VCIncludes,
      File "c:\python27\lib\site-packages\setuptools\msvc.py", line 815, in VCIncludes
        return [os.path.join(self.si.VCInstallDir, 'Include'),
      File "c:\python27\lib\site-packages\setuptools\msvc.py", line 553, in VCInstallDir
        raise distutils.errors.DistutilsPlatformError(msg)
    distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 9.0 is required. Get it from http://aka.ms/vcpython27

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in c:\users\admin\appdata\local\temp\pip-build-div0s2\pyproj\
```

**Comment by chuyskywalker** [comment]
This is not a support forum; please see [the discord #help channel](https://discord.gg/npVqkUn) for assistance.

And, seriously, read the error messages. They literally telling you what's wrong.
