### ISSUE TITLE
Installation error: unable to access pgoapi.git; command git clone failed with error code 128 in None

### ISSUE THREAD

**Issue by FlauschRara** [PokemonGoMap/PokemonGo-Map#177]
I can't pass the pip install -r requirements.txt stage.
I have been following the wiki and installed the required stuff, but when I try the command I just posted, I get the following error message:

```
Cloning https://github.com/keyphact/pgoapi.git to c:\dokume~1\stefan\lokale~1\temp\pip-build-b3rmsp\pgoapi
fatal: unable to access 'https://github.com/keyphact/pgoapi.git/': error setting certificate verify locations:
CAfile: C:/Programme/Git/mingw32/libexec/ssl/certs/ca-bundle.crt
CApath: none

Command "git clone -q https://github.com/keyphact/pgoapi.git  c:\dokume~1\stefan\lokale~1\temp\pip-build-b3rmsp\pgoapi" failed with error code 128 in None
```

I'm sorry, I don't know the first thing about any of this, so I'm pretty lost.

**Comment by chuyskywalker** [comment]
This is not a support forum; please see [the discord #help channel](https://discord.gg/npVqkUn) for assistance.

That said, it looks like your SSL certificate store isn't up-to-date enough to talk to github. That's the problem you should start googling up.
