### ISSUE TITLE
How do I run multiple searchers per instance?

### ISSUE THREAD

**Issue by Guiaki** [PokemonGoMap/PokemonGo-Map#178]
## Expected Behavior
Sum of all pokemon founds in the multiple accounts shown on the map.

## Current Behavior
Only shows the first instance of the server opened.

## Possible Solution
Something that allows multiple points by giving several accounts.

## Context
I would like to add multiple points on the map to be scanned, if possible multiple accounts in different locations, i'm trying to spread the website to some friends and live in different places.
If you change the Location Settings, all the scan will be done only in that place, that is very bad for multiple users.

## Your Environment

* Latest version
* Python 2.7
* Windows 10

**Comment by Infernoman** [comment]
There are arguments to start multiple scanners with one webserver, Please read the documentation before opening an issue. "-ns" will start the scanner but not the server. "-os" will start just the webserver.

**Comment by chuyskywalker** [comment]
To be fair, we don't have a good wiki on how to run multiple searchers. Going to change this request to be more about that.

**Comment by darkdefiled** [comment]
You can use -fl to set "Fixed Location" automatically Disabling the Search location option on the frontend

also: in Tools/Hex-Beehive-Generator, is just what ur seeking for there is actually a guide on how to set it up in the WIKI

**Comment by HardTacos** [comment]
Using multiple threads (accounts) like this:

In your config file:

`username: ['user1', 'user2', ... ]`
`password: ['pass1', 'pass2', ... ]`

**Comment by AndrewYoungs** [comment]
@HardTacos But is there a way to make multiple accounts search over multiple locations since each account can only be tied to three locations at once effectively. 

So for example if I have a bat script set up to do this: for %%a in (%lista%) do start pythonw runserver.py -u <user> -p <pass> -st 6 -l %%a -ld 1 & timeout 1

If you try to run too many separate instances you get this.

[http://imgur.com/a/sqJDO](url)

**Comment by Infernoman** [comment]
You need to create more accounts, to run a larger scan area. Or to scan more than one area at a time. You shouldn't be trying to run more than one script with the same worker as another.

**Comment by AndrewYoungs** [comment]
@Infernoman I have 17 accounts running as workers at once.

**Comment by Infernoman** [comment]
And i have over 500 running on multiple servers. as long as you dont re use a workers username in password in any of the other scripts you should be just fine.

**Comment by AndrewYoungs** [comment]
>Multiple servers

This is a single server though.

**Comment by Infernoman** [comment]
i have over 500 split between 2 servers, 100+ accounts on each of them. you need to associate more accounts with your scripts. not just a single user. and you CANNOT re use workers like you are right now

**Comment by AndrewYoungs** [comment]
Ok didn't know about not being able to re-use workers because in previous releases you could have up to three threads per worker (i.e. scanning 3 different locations) Will give your idea a go and spend some time making more accounts. Nnnngh if only there was an easier way to do that.

**Comment by dnalloheoj** [comment]
I am getting the same error messages as AndrewYoungs's screenshot, but have all accounts separated (0-5, 6-10, 11-15) in three locations. 

Two locations seem to work OK, but when trying to start the third location I also receive those error messages. http://imgur.com/a/qbShl

**Comment by dnalloheoj** [comment]
Accounts had not accepted the TOS yet, upon accepting, things work great. 

Just gonna leave this here in case someone else has the same errors. Apologies if unrelated to original topic/issue.

**Comment by AndrewYoungs** [comment]
Holy crap that's amazing to know. *logs in to all the accounts to accept*

**Comment by AndrewYoungs** [comment]
@dnalloheoj Actually hey, there's no TOS prompt on the site. How did you work around this?

**Comment by dnalloheoj** [comment]
Login to the game itself, or: https://github.com/TachyonRSA/PoGoTos

**Comment by AndrewYoungs** [comment]
@dnalloheoj That's brilliant, cheers!

**Comment by dudeman999** [comment]
Was there a definitive answer on how to run multiple accounts that a common user can follow?

**Comment by Bart274** [comment]
What is the best way to increase the tracking done on one single location:
- increase the number of accounts that scan that single location
- increase the number of threads for that instance (but still with one account)
- increase the number of accounts and the number of threads?

**Comment by darkdefiled** [comment]
didn't they remove the -t argument? so multiple threads aint working anymore right?

**Comment by Crazy-Clown** [comment]
For me, the best way if you have id say under 30 accounts is to create a batch file that calls other batch files (in Windows) and run separate instances of the runserver script but with the -ns argument for no server. I have 15 batch files with all CMd windows running separately. I also created a file that terminates all Python.exe and cmd.exe processes for an easy clean up/stop of the webserver instead of closing multiple windows. 

So three shortcuts in total on your desktop, 1) a run server shortcut with the actual runserver.py script to start things off, 2) a batch script that calls several others (with a delay between each launch) and 3) a kill script to kill cmd and Python processes.

**Comment by AndrewYoungs** [comment]
Multiple threads are working but you have to feed one account in to your command line multiple times i.e. -u user -u user -u user

**Comment by myristica** [comment]
can someone help us out with the creating of the batch files?
