### ISSUE TITLE
Display more helpful error when account has not accepted ToS

### ISSUE THREAD

**Issue by Zaye61** [PokemonGoMap/PokemonGo-Map#180]
Hello, i get this error message for 20 minutes now : 

2016-08-08 19:21:29,384 [ search_worker_7][        search][   ERROR] Exception in search_worker: sequence index must be integer, not 'str'
Traceback (most recent call last):
  File "/Users/Musa/Documents/PokemonGo-Map/pogom/search.py", line 242, in search_worker_thread
    parsed = parse_map(response_dict, step_location)
  File "/Users/Musa/Documents/PokemonGo-Map/pogom/models.py", line 296, in parse_map
    cells = map_dict['responses']['GET_MAP_OBJECTS']['map_cells']
TypeError: sequence index must be integer, not 'str'

Can someone help me?
I have the lattest version and run it on MacOs.

**Comment by Frozen-byte** [comment]
accept tos MANY duplicates here.

**Comment by Zaye61** [comment]
i downloaded a script to accept tos and did it for alle the accounts.

**Comment by forsakenzombi** [comment]
same issue

**Comment by NeGroid** [comment]
Most likely the same issue on recently reinstalled everything including the entire system:
```
2016-08-08 21:55:25,638 [ search_worker_0][search][ERROR] Search step 1 map parsing failed, retrying request in 10 seconds
Traceback (most recent call last):
  File "/Users/negroid_gg/PokemonGo-Map/pogom/search.py", line 242, in search_worker_thread
    parsed = parse_map(response_dict, step_location)
  File "/Users/negroid_gg/PokemonGo-Map/pogom/models.py", line 296, in parse_map
    cells = map_dict['responses']['GET_MAP_OBJECTS']['map_cells']
KeyError: 'map_cells'
```

**Comment by Infernoman** [comment]
https://github.com/TachyonRSA/PoGoTos Please close this duplicate issue.

**Comment by Zaye61** [comment]
@Infernoman i had a different script for this, but i downloaded yours and did it again for all my accounts. But i still get the same error.
Furthermore, he fails to login with several other Accounts....

**Comment by SchwarzwaldFalke** [comment]
I'm using accounts which I created 2 weeks ago (m.e older accounts are not affected by the ToS change) and still get the same error message.
Nevertheless:
It would be really helpful for debugging if the error message could include the username which causes the error.

**Comment by BaIthamel** [comment]
Actually I agree outputting the username would really help with being able to purge broken accounts.

**Comment by AndrewYoungs** [comment]
Solution here: https://github.com/PokemonGoMap/PokemonGo-Map/issues/178#issuecomment-238399886

**Comment by crvfts** [comment]
I am getting this error as well. I used a seasoned account that has had communications (ie. not new), and I did accept TOS. I followed directions from the readthedocs site. Everything is enabled where it needs to be in google API.

What could possibly be going on?

**Comment by BaIthamel** [comment]
For feature requests please migrate this to the new feature page
http://feathub.com/PokemonGoMap/PokemonGo-Map/
Thankyou!

**Comment by CoolCanuck** [comment]
@BaIthamel This request needs to be opened again. FeatHub is no longer used. Good riddance.
