### ISSUE TITLE
who dumb developer delete example.py?

### ISSUE THREAD

**Issue by AHAAAAAAA** [PokemonGoMap/PokemonGo-Map#182]
stupid shit, doesn't work.

**Comment by HardTacos** [comment]
lol

**Comment by Crazy-Clown** [comment]
example.py was removed a long time ago in one of the first builds (before this fork).  If you'd read the instructions to run the Map, you would have known that.

**Comment by AHAAAAAAA** [comment]
fuck reading, why can't you just save to java and make .exe?

**Comment by Frozen-byte** [comment]
@AHAAAAAAA have you tried to show hidden files?

**Comment by Crazy-Clown** [comment]
> fuck reading, why can't you just save to java and make .exe?
What about this one?  https://github.com/mchristopher/PokemonGo-DesktopMap/releases

**Comment by dirkpoetter** [comment]
is it really you ? :dancer:

**Comment by BillyWM** [comment]
Can someone with collaborator status ban this noob?

**Comment by chuyskywalker** [comment]
Make a gui in visual basic and backtrack the ip, quick!

**Comment by marumari** [comment]
@AHAAAAAAA, have you thought about making your own fork and working on the project?  It comes from some pretty rough origins, but since moving to this repo it seems to be getting cleaned up nicely.

**Comment by HenrySia** [comment]
@AHAAAAAAA thanks for your great work! I'm glad that you're having a good laugh even after the C&D notice you got. We all truly appreciate your time, dedication and effort.

**Comment by AHAAAAAAA** [comment]
@marumari original repo had example.py and worked. this one doesn't. Quality of project is going 📉

**Comment by FrostTheFox** [comment]
@AHAAAAAAA https://github.com/PokemonGoMap/PokemonGo-Map/commit/1c27962f63cc6e7b9b41bcd819a1f03f722f6e42 ur welcome

**Comment by razorasadsid** [comment]
guys who do i ask to take a shit on grunt?

**Comment by marumari** [comment]
@AHAAAAAAA That may be true, but the original repo belonged to somebody whose nickname made me feel like I was getting laughed at loudly.  😭

**Comment by invisiblek** [comment]
@razorasadsid please direct all requests to 'take a shit on grunt' to /dev/null

**Comment by BillyWM** [comment]
@AHAAAAAAA Maybe we can add 6 or 7 flags for example.py as an optional feature?

**Comment by BillyWM** [comment]
@marumari I'm confused, isn't this the original owner? https://www.youtube.com/watch?v=8X_Ot0k4XJc

**Comment by BaIthamel** [comment]
Okay I love this, but I'm closing it anyway because I'm going to keep the issues under 100!

**Comment by BillyWM** [comment]
y dum developer close? I stil can't run example.py!!!!!!! PLZ FIX

**Comment by BillyWM** [comment]
**elitist tools!**

**Comment by JZ6** [comment]
damn too late to the party
