### ISSUE TITLE
Multiple Webhook help

### ISSUE THREAD

**Issue by kinderoth** [PokemonGoMap/PokemonGo-Map#184]
I have one webhook setup for pokelyzer and i was trying to setup a second webhook for the pokealarm. I tried doing "-wh *pokelyzer* -wh *pokealarm*" when I run my scanner but when I did that neither webhook received any data, is there a way to get 2 seperate webhooks to work simultaneously or am I messing something up? 

They do work when I use them individually though.

## Your Environment
* Version used: Dev
* Environment name and version (e.g. Python 2.7): Python 2.7
* Operating System and version (desktop or mobile): Windows 7 Desktop

**Comment by chuyskywalker** [comment]
I believe you do `-wh address1 address2`

**Comment by kinderoth** [comment]
looks like that did the trick thank you very much!

**Comment by j16sdiz** [comment]
duplicate of #157

**Comment by khag7** [comment]
Someone should update the docs, I just read today that I was to do -wh address1 -wh address2

**Comment by neutron666** [comment]
-wh address1 address2 works, but config.ini does not work:

webhook: http://127.0.0.1:7000 http://127.0.0.1:7001
webhook: "http://127.0.0.1:7000 http://127.0.0.1:7001"

both variant's don't work

**Comment by roadfox** [comment]
i think you have to declare it as array:
webhook: [proxy, proxy]

see the doc for multi accounts in config.ini here: https://pgm.readthedocs.io/en/develop/extras/multi-account.html?highlight=config

**Comment by neutron666** [comment]
Does not work either :(

webhook:                [http://127.0.0.1:7000, http://127.0.0.1:7001]

runserver.py: error: webhook can't be set to a list '[http://127.0.0.1:7000, http://127.0.0.1:7001]' unless its action type is changed to 'append'
