### ISSUE TITLE
best code for multiple accounts?

### ISSUE THREAD

**Issue by dirkpoetter** [PokemonGoMap/PokemonGo-Map#185]
So basicly my code is like this atm:

"C:\Python27\python.exe" runserver.py -a ptc -u Username1 -u Username2 -u UN3 -u UN4 -u UN5 -u UN6 -u UN7 -u UN8 -u UN9 -u UN10 -p Password1 -p Password2 -p PW3 -p PW4 -p PW5 -p PW6 -p PW7 -p PW8 -p PW9 -p PW10 -l "MyCity, MyCountry" -st 15 -H 0.0.0.0 -L en -k myapikey -sd 10 -ld 1

Is it still standard to run with sd 10? and ld 1 for multiple accounts? i feel like st 15 is the max you can go with this code, i even run st 10 right now, cause i feel like i get pokemons nearby kinda late then.

any improvements to the code?

**Comment by interbiznw** [comment]
-sd 10 is default and you don't really need to specify it.. The more workers per runserver.py the faster its gonna be

**Comment by dirkpoetter** [comment]
okay, but shouldn't go to low on sd to not get detected or suspecious? And what about the ld?

**Comment by interbiznw** [comment]
Any lower than -sd 10 you will come up with less Pokemon than there actually are.. Niantic will return blank values for some. So I would just leave it at default and I do not have any -ld set, just running 10 usernames per scan

It scans 10 cells at a time, every 10 seconds... Its fairly fast on a -st 10

**Comment by chuyskywalker** [comment]
This is not a support forum; please see [the discord #help channel](https://discord.gg/npVqkUn) for assistance.
