### ISSUE TITLE
ReadTimeOut Exception when adding a webhook

### ISSUE THREAD

**Issue by remcotroost** [PokemonGoMap/PokemonGo-Map#186]
I am having an issue adding a webhook. When running the PokemonGo-Map I get the following exception on each of my workers due to the webhook:

```
2016-08-08 19:54:07,715 [ search_worker_0][        search][   ERROR] Exception in search_worker: 'module' object has no attribute 'ReadTimeout'
Traceback (most recent call last):
  File "/home/remco/pokemap/PokemonGo-Map-3.0.0/pogom/search.py", line 236, in search_worker_thread
    parsed = parse_map(response_dict, step_location)
  File "/home/remco/pokemap/PokemonGo-Map-3.0.0/pogom/models.py", line 326, in parse_map
    send_to_webhook('pokemon', webhook_data)
  File "/home/remco/pokemap/PokemonGo-Map-3.0.0/pogom/utils.py", line 283, in send_to_webhook
    except requests.exceptions.ReadTimeout:
AttributeError: 'module' object has no attribute 'ReadTimeout'
```

I've checked that my PokeAlarm is listening on that port and it's running correcly (I'm getting an activated message on telegram). I've tried running the webhook as a parameter and through the config.ini, both with the same exception. Changing 127.0.0.1 to localhost also didn't fix the issue.

As far as I know, the ReadTimeOut exception has something to do with the connection between the Go-Map and my PokeAlarm. 

Anybody had this issue before or can help me solve it? 
## Your Environment
- Version used: PokemonGo-Map-3.0.0
- Environment name and version (e.g. Python 2.7): Python 2.7
- Operating System and version (desktop or mobile): Ubuntu 14.04.05 LTS

**Comment by sebastienvercammen** [comment]
Reviewed: requests does have `requests.exceptions.ReadTimeout` ([source](http://docs.python-requests.org/en/master/_modules/requests/exceptions/#ReadTimeout)).

Either user error, or outdated modules.
