### ISSUE TITLE
Docker build fails because node-sass does not support Alpine/musl

### ISSUE THREAD

**Issue by tyscorp** [PokemonGoMap/PokemonGo-Map#195]
## Expected Behavior
`docker build` should work.

## Current Behavior
`docker build` fails on `npm install` with `node-sass`.

## Possible Solution
1. Switch from Alpine Linux.
2. Switch from node-sass.
3. Fix Alpine/musl support in node-sass.

## Steps to Reproduce (for bugs)
1. Attempt to build the docker image.

## Context
The issue sass/node-sass#1589 explains the problem.

I believe this is the same issue as in #93.

## Your Environment

* Version used: d95014acf7a83dd8f1648db60f0f3efc2ce91dc4
* Environment name and version (e.g. Python 2.7): docker 
* Operating System and version (desktop or mobile): Ubuntu 16.04

**Comment by chuyskywalker** [comment]
I have node-sass working just fine in the dev dockerfile. Let me try to rebuild the full container

**Comment by chuyskywalker** [comment]
```
$ docker build -t pgm .
# ...lots of stuff output here...
Successfully built d0c126294733

$ docker run -ti --rm --entrypoint=sh pgm -c 'ls -alh static/dist/css/'
total 108
drwxr-xr-x    2 root     root        4.0K Aug  8 18:09 .
drwxr-xr-x   10 root     root        4.0K Aug  8 18:09 ..
-rw-r--r--    1 root     root       47.7K Aug  8 18:09 app.built.css
-rw-r--r--    1 root     root       34.8K Aug  8 18:09 app.min.css
-rw-r--r--    1 root     root        1.1K Aug  8 18:09 mobile.built.css
-rw-r--r--    1 root     root         828 Aug  8 18:09 mobile.min.css
-rw-r--r--    1 root     root        2.0K Aug  8 18:09 statistics.built.css
-rw-r--r--    1 root     root        1.4K Aug  8 18:09 statistics.min.css
```

So...what's not working?

**Comment by tyscorp** [comment]
I am able to successfully build the image on my Docker for Windows VM running v1.12.0 and a SLES 12 server running v1.6.2, but not on a DigitalOcean Ubuntu 16.04 server running docker v1.11.2.

On the Ubuntu server it gives me the following error:
```
The command '/bin/sh -c apk add --no-cache build-base nodejs  && npm install -g grunt-cli  && npm install  && npm run-script build  && npm uninstall -g grunt-cli  && rm -rf node_modules  && apk del build-base nodejs' returned a non-zero code: 137
```

**Comment by chuyskywalker** [comment]
If you change:

```


RUN apk add --no-cache build-base nodejs \
 && npm install -g grunt-cli \
 && npm install \
 && npm run-script build \
 && npm uninstall -g grunt-cli \
 && rm -rf node_modules \
 && apk del build-base nodejs
```

To

```


RUN apk add --no-cache build-base nodejs
RUN npm install -g grunt-cli
RUN npm install
RUN npm run-script build
RUN npm uninstall -g grunt-cli
RUN rm -rf node_modules
RUN apk del build-base nodejs
```

And post the relevant part of the build log, we could understand more specifically where this breaks.

**Comment by tyscorp** [comment]
It's during the `npm install`. I can reproduce by changing `npm install` to `npm install node-sass@3.8.0`

**Comment by chuyskywalker** [comment]
Now, hold on, I'm building this image on an Ubuntu 16.04 machine and it's working fine.

Even if that's the case, I don't think this is a problem with the image or using alpine as a base, so I'm not really sure it's something to be tackled here.

**Comment by ahammond** [comment]
I reported the same problem in #355 
Applied the Dockerfile change suggested by @chuyskywalker and got the following:

```bash
root@pmap:~/PokemonGo-Map# docker build -t pokemongo-map .

... snip ...

Step 14 : RUN npm install
 ---> Running in 89f5fec8d82a
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
Killed
The command '/bin/sh -c npm install' returned a non-zero code: 137

root@pmap:~/PokemonGo-Map# npm --version
3.5.2
```

**Comment by ahammond** [comment]
@tyscorp are you running the smallest instance available in DO? Because I am, and I just realized that this was probably because of OOM. I added swap following https://www.digitalocean.com/community/tutorials/how-to-add-swap-space-on-ubuntu-16-04 and now have a working docker build.

**Comment by tyscorp** [comment]
Yes, I'm running the smallest instance. Adding the swap fixed the problem. Thanks!
