### ISSUE TITLE
Error 2 installing requirements 

### ISSUE THREAD

**Issue by Navheff** [PokemonGoMap/PokemonGo-Map#196]
![capture](https://cloud.githubusercontent.com/assets/20912249/17492276/0ebd8f54-5d79-11e6-82da-ba701fc464f4.PNG)

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Python 2.7):
* Operating System and version (desktop or mobile):

**Comment by marumari** [comment]
You should install git.

**Comment by Navheff** [comment]
I do have it installed

**Comment by marumari** [comment]
No, git.  You need to make sure that git is in your path.

**Comment by Navheff** [comment]
How do I go about doing that? 
Sorry I'm new to the whole programming thing

**Comment by invisiblek** [comment]
https://github.com/PokemonGoMap/PokemonGo-Map/wiki

**Comment by Navheff** [comment]
Video guide is not up to date and should be removed then

**Comment by marumari** [comment]
What video guide?

**Comment by Navheff** [comment]
In the READme.md then under 'How to Install' there is a link to a youtube video

**Comment by marumari** [comment]
Looking at the video guide, it has you install git as well.  Looks like you just skipped that step.

**Comment by Navheff** [comment]
well fuck me hahah
