### ISSUE TITLE
npm WARN deprecated minimatch@0.2.14 & other errors.

### ISSUE THREAD

**Issue by MarkDiddams** [PokemonGoMap/PokemonGo-Map#205]
I am running the below and seem to be getting these issues please can you help

npm install && npm run build
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN lifecycle pogomap@0.1.0~postinstall: cannot run in wd %s %s (wd=%s) pogomap@0.1.0 grunt build /root/PoGoMap
- graceful-fs@1.1.14 node_modules/grunt/node_modules/rimraf/node_modules/graceful-fs
pogomap@0.1.0 /root/PoGoMap
├─┬ eslint@3.2.2
│ └─┬ file-entry-cache@1.3.1
│   └─┬ flat-cache@1.2.1
│     └── graceful-fs@4.1.5 
├── graceful-fs@4.1.5  extraneous
├─┬ grunt@0.4.5 
│ ├── exit@0.1.2 
│ ├─┬ findup-sync@0.1.3
│ │ └── lodash@2.4.2 
│ ├── getobject@0.1.0 
│ ├─┬ grunt-legacy-log@0.1.3 
│ │ ├─┬ grunt-legacy-log-utils@0.1.1 
│ │ │ ├── lodash@2.4.2 
│ │ │ └── underscore.string@2.3.3 
│ │ ├── lodash@2.4.2 
│ │ └── underscore.string@2.3.3 
│ ├── grunt-legacy-util@0.2.0 
│ └── rimraf@2.2.8 
├─┬ grunt-sass@1.2.0
│ └─┬ node-sass@3.8.0
│   ├─┬ meow@3.7.0
│   │ └─┬ read-pkg-up@1.0.1
│   │   └─┬ read-pkg@1.1.0
│   │     ├─┬ load-json-file@1.1.0
│   │     │ └── graceful-fs@4.1.5 
│   │     └─┬ path-type@1.1.0
│   │       └── graceful-fs@4.1.5 
│   └─┬ node-gyp@3.4.0
│     ├─┬ fstream@1.0.10
│     │ └── graceful-fs@4.1.5 
│     └── graceful-fs@4.1.5 
├── gulp@3.9.1  extraneous
├── minimatch@3.0.3 
└── node.js@0.0.0  extraneous

npm WARN enoent ENOENT: no such file or directory, open '/root/PoGoMap/node_modules/grunt-legacy-util/package.json'

> pogomap@0.1.0 build /root/PoGoMap
> grunt build

sh: 1: grunt: not found

npm ERR! Linux 4.4.0-31-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! pogomap@0.1.0 build: `grunt build`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the pogomap@0.1.0 build script 'grunt build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the pogomap package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     grunt build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs pogomap
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls pogomap
npm ERR! There is likely additional logging output above.

**Comment by DanielBallaSZTE** [comment]
Yeah I get npm error too:

npm ERR! node-sass@3.8.0 install: `node scripts/install.js`
npm ERR! Exit status 127
npm ERR!
npm ERR! Failed at the node-sass@3.8.0 install script.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.16.0-4-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/pokemon/PokemonGo-Map
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pokemon/PokemonGo-Map/npm-debug.log
npm ERR! not ok code 0

**Comment by danimorelo** [comment]
similar issue here with the node-sass module running in a raspberry pi

> 22102 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "node-sass"
22103 error node v4.4.4
22104 error npm  v2.15.1
22105 error code ELIFECYCLE
22106 error node-sass@3.8.0 postinstall: `node scripts/build.js`
22106 error Exit status 1
22107 error Failed at the node-sass@3.8.0 postinstall script 'node scripts/build.js'.
22107 error This is most likely a problem with the node-sass package,
22107 error not with npm itself.
22107 error Tell the author that this fails on your system:
22107 error     node scripts/build.js
22107 error You can get information on how to open an issue for this project with:
22107 error     npm bugs node-sass
22107 error Or if that isn't available, you can get their info via:
22107 error
22107 error     npm owner ls node-sass
22107 error There is likely additional logging output above.
22108 verbose exit [ 1, true ]
22109 verbose unbuild node_modules/node-sass
22110 info preuninstall node-sass@3.8.0
22111 info uninstall node-sass@3.8.0

**Comment by chuyskywalker** [comment]
This is not a support forum; please see [the discord #help channel](https://discord.gg/npVqkUn) for assistance.

All of the above issues look like environment problems not directly tied to this project. The rPi is notoriously difficult to get to compile code used out in the big wide linux world because of the ARM architecture.

**Comment by BillyWM** [comment]
I believe node-sass would be a compiled code issue, as it uses libsass. Sass is only required for processing the stylesheets. For an rPi, I would recommend giving it a release version with the styles and JS pre-built.

For the grunt build issues, make sure you have installed grunt *globally* by running "npm install -g grunt" per the instructions on the wiki.

**Comment by chuyskywalker** [comment]
> For the grunt build issues, make sure you have installed grunt globally by running "npm install -g grunt" per the instructions on the wiki.

This is not required anymore, and is preferred to not be used in fact. `npm install && npm run build` is better.

**Comment by BillyWM** [comment]
Hmm...it was moved into the local dependencies? Were people having PATH issues?

**Comment by chuyskywalker** [comment]
It's _been_ in the local deps for a while now, but people kept trying to type `grunt something` and didn't have the global grunt-cli package installed breaking things. With the `npm run` hook, it automatically looks for the one installed in `node_modules/.bin` first.

**Comment by Sterkoel** [comment]
Have you tried using the 0.12.0 version of npm instead of the 0.10.29?

I found a [pre-compiled version for rPi](http://conoroneill.net/download-compiled-version-of-nodejs-0120-stable-for-raspberry-pi-here/).

`wget https://s3-eu-west-1.amazonaws.com/conoroneill.net/wp-content/uploads/2015/02/node-v0.12.0-linux-arm-pi.tar.gz
tar -zxvf node-v0.12.0-linux-arm-pi.tar.gz
cd node-v0.12.0-linux-arm-pi
sudo cp -R * /usr/local/`

**Comment by danimorelo** [comment]
@Sterkoel thanks!

before i was trying with node 4.4.4 and the latest 4.4.7 for armv6l without luck

still i had work to install and compile node-sass individually
`sudo npm install --unsafe-perm  node-sass`

does your webapp look ok? my elements were not loading fine, neither the map
I ended up going for the release-2.2.0 instead of the dev branch and it worked flawlessly

**Comment by Sterkoel** [comment]
@danimorelo Yes everything works perfectly on my RaspberryPi 2 with the precompiled nodejs v0.12.0.
