### ISSUE TITLE
"No Labels" style setting only removes POI's but not street names

### ISSUE THREAD

**Issue by Crazy-Clown** [PokemonGoMap/PokemonGo-Map#206]
When selecting the map style, the NO LABELS option does not remove street names, only Points of Interest on the map.

## Expected Behavior
All street names and POI's (Essentially all text should be removed and just display the map itself)

## Current Behavior
If style of map selected is "No Labels" only POI's are removed from map (the labels), not the street names.

## Steps to Reproduce (for bugs)
1. Run server
2. Change style from OPTIONS menu on top left, to No Labels

## Your Environment

* Version used: latest develop build
* Python 2.7, Server 2008 R2, x64, Firefox Browser (latest version)
* Desktop

**Comment by justsomedudeonthenet** [comment]
This appears to be fixed now.
