### ISSUE TITLE
no pokemon found

### ISSUE THREAD

**Issue by lmmackenzie26** [PokemonGoMap/PokemonGo-Map#210]
I followed the video guide, did everything it said but not finding any pokemon.

**Comment by Crazy-Clown** [comment]
Try asking in the Pokemon Dev Reddit forums as the Git page is not really for technical support.
https://www.reddit.com/r/pokemongodev/

**Comment by marauder37** [comment]
For installation or configuration help please visit https://discord.gg/nXyMej6 . Github issues are only for issues/bugs in the code. Thanks!
