### ISSUE TITLE
error code -11?

### ISSUE THREAD

**Issue by calfun** [PokemonGoMap/PokemonGo-Map#213]
I'm getting this after running requirements.txt, Homebrew already installed. Can anyone help?

Error [Errno 2] No such file or directory while executing command git clone -q https://github.com/keyphact/pgoapi.git /private/tmp/pip-build-RB4Rh2/pgoapi
Cannot find command 'git'

Python 2.7
Mac OSX 10.7

**Comment by nsttu** [comment]
Looks like you dont have git installed.

Maybe this can help:
https://git-scm.com/book/en/v2/Getting-Started-Installing-Git

**Comment by calfun** [comment]
Thank you, I thought I already install git after running 

> brew install git python protobuf

I followed your link and have it installed, but I'm getting this:

> Command "git clone -q https://github.com/keyphact/pgoapi.git /private/tmp/pip-build-q2t6Ko/pgoapi" failed with error code -11 in None

Any ideas?

**Comment by marauder37** [comment]
For installation or configuration help please visit https://discord.gg/nXyMej6 . Github issues are only for issues/bugs in the code. Thanks!
