### ISSUE TITLE
Beehive Broken?

### ISSUE THREAD

**Issue by darkdefiled** [PokemonGoMap/PokemonGo-Map#214]
## Expected Behavior
Running 28 scanner accounts normally

## Current Behavior
as soon as the second scanner gets up. it trows this at me:

2016-08-08 22:35:15,938 [ search_worker_0][        search][   ERROR] Search step 1 map parsing failed, retrying request in 5 seconds
Traceback (most recent call last):
  File "C:\Users\Danny\Documents\PokemonGo-Map\pogom\search.py", line 242, in search_worker_thread
    parsed = parse_map(response_dict, step_location)
  File "C:\Users\Danny\Documents\PokemonGo-Map\pogom\models.py", line 296, in parse_map
    cells = map_dict['responses']['GET_MAP_OBJECTS']['map_cells']
KeyError: 'map_cells'

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context
Not being able to setup multiple scanners

## Your Environment
Python 2.7 with all installed, Node NPM Pip etc etc

Windows 10

**Comment by forsakenzombi** [comment]
login to the accounts via the actual app and accept the TOS

**Comment by darkdefiled** [comment]
I've had a program do that already.

**Comment by g5bEM6RpSbQF** [comment]
https://www.reddit.com/r/pokemongodev/comments/4wk3e4/psa_new_pogo_accounts_have_to_accept_tos_ingame/

**Comment by g5bEM6RpSbQF** [comment]
This script will do it for you, from its documentation

https://github.com/scottstamp/pgoapi/blob/master/scripts/accept-tos.py

**Comment by darkdefiled** [comment]
as i said, my account's have already accepted TOS i already had a program do that for me :p

**Comment by darkdefiled** [comment]
i'll run the python one to be sure, and will check after it.

**Comment by darkdefiled** [comment]
Apperently the other program did not work, my accs are up and running now thank you!
