### ISSUE TITLE
Notification spam on Pokemon (10+ alerts)

### ISSUE THREAD

**Issue by marumari** [PokemonGoMap/PokemonGo-Map#215]
## Expected Behavior

I should just get a single notification, and only if the spawn is still on the map.
## Current Behavior

I will frequently get 10+ notifications for the same Pokemon, and often it isn't even on the map.  It makes me a bit crazy.

This is a carry-over from the previous repo where others had experienced it:

https://webcache.googleusercontent.com/search?q=cache:SmWKHiHTeLsJ:https://github.com/AHAAAAAAA/PokemonGo-Map/issues/2478+&cd=1&hl=en&ct=clnk&gl=us

https://github.com/AHAAAAAAA/PokemonGo-Map/pull/2950
## Possible Solution

Lets look into the PR above, maybe it has some stuff we need.
## Steps to Reproduce (for bugs)

1. Just set an alert for a Pokemon; sometimes, but not always, it will alert frequently.  I believe it may be due to a lured Pokemon bug.
   2.
   3.
   4.
## Context

I'll have to get screenshots next time it happens!
## Your Environment

- Version used: HEAD on develop branch
- Environment name and version (e.g. Python 2.7): Python 2.7
- Operating System and version (desktop or mobile): Ubuntu 16.04.1 (server)

**Comment by norecha** [comment]
Happens to me all the time. I think it starts to spam when pokemon disappears.

**Comment by DiscoTim** [comment]
I hacked a fix in mine in the map js. seems to happen after they disappear with me.

Changed:

if (notifiedPokemon.indexOf(item.pokemon_id) > -1) {

To:

var now = new Date();
if ((notifiedPokemon.indexOf(item.pokemon_id) > -1) && (item.disappear_time >= now)) {

**Comment by marumari** [comment]
@norecha: you're totally right -- it happened just now, and the notifications all repeatedly happened after it despawned.

**Comment by marumari** [comment]
The above patch seems to be working fine, but I'll keep testing it for the next few days.

**Comment by MrStu82** [comment]
Is this related to the pokemon that appear for 15 minutes and then also for an extra 15 minutes? I find that for the first 15 minutes it the expiration time is set in the past which messes things up. It is there, so you might not want to filter it out. The second 15 minutes will show a correct expiration time.

I guess the question is. Have you checked the pokemon is there or not?

**Comment by norecha** [comment]
@marumari above patch does not work fine. i have been using it for 2 days. best case it only pops up 1 more time when it expires. so still twice for same pokemon. worst case, same pop-up spam still happens, although it is more rare.

**Comment by marumari** [comment]
Drats, that's frustrating.  :\

**Comment by marumari** [comment]
map.js is absurdly hard to read -- I've made a couple patches. We'll see if that helps!

```diff
diff --git a/static/js/map.js b/static/js/map.js
index f127aea..8c724cc 100644
--- a/static/js/map.js
+++ b/static/js/map.js
@@ -1461,14 +1461,14 @@ function processLuredPokemon (i, item) {
     return
   }

-  if (!mapData.lurePokemons[item2['pokestop_id']] && item2['lure_expiration']) {
+  if (!mapData.lurePokemons[item2['pokestop_id']] && item2['lure_expiration'] > new Date().getTime()) {
     // if (item.marker) item.marker.setMap(null)
     if (!item2.hidden) {
       item2.marker = setupPokemonMarker(item2)
       mapData.lurePokemons[item2['pokestop_id']] = item2
     }
   }
-  if (mapData.lurePokemons[item['pokestop_id']] && item2['lure_expiration'] && item2['active_pokemon_id'] !== mapData.lurePokemons[item2['pokestop_id']].activePokemonId) {
+  if (mapData.lurePokemons[item['pokestop_id']] && item2['lure_expiration'] > new Date().getTime() && item2['active_pokemon_id'] !== mapData.lurePokemons[item2['pokestop_id']].activePokemonId) {
     // if (item.marker) item.marker.setMap(null)
     mapData.lurePokemons[item2['pokestop_id']].marker.setMap(null)
     if (!item2.hidden) {
```

**Comment by shivampaw** [comment]
This is still happening. Can someone make a PR for it?

**Comment by amaltson** [comment]
@marumari did your patch work?

**Comment by marumari** [comment]
I've tried a number of them, and it still happens occasionally.  So if there is a patch to fix it, it's more complicated than changing just a couple lines, or maybe they need to be both changed.

**Comment by shivampaw** [comment]
@marinari if you git pull the change would be overwritten

**Comment by shivampaw** [comment]
@marumari ^

**Comment by Darkknightz** [comment]
@primaxius I think this should be closed, alot has changed since this has been reported. I think its not relevant anymore. #1046 (#1303) should have fixed it.

**Comment by sebastienvercammen** [comment]
As reported, fixed in previous merged edits.
