### ISSUE TITLE
Webhook per discovered pokemon is inefficient

### ISSUE THREAD

**Issue by chuyskywalker** [PokemonGoMap/PokemonGo-Map#216]
In [models.py](https://github.com/PokemonGoMap/PokemonGo-Map/blob/develop/pogom/models.py#L326) you can see that we're triggering the webhook endpoint for each pokemon found _individually_. This is craaaaazy. It should, 100% definitely wrap the pokemon structure up into a singular hook and push that out. Something like `cell-scan-complete` or something. Or, if we really want to be granular, `pokemon`, `gyms`, and `pokestops` -- one for each "set" of data found per loop. Not for every individual find.

**Comment by marumari** [comment]
Yep, no reason why it can't be:

```json
{
  "gyms": [],
  "pokemon": [],
  "stops": []
}
```

That gets posted to the webhook.

**Comment by martinsweitzer** [comment]
A fun other bug is that every single worker is sending duplicate pokestop data. (e.g. thread 0 scans in node 0 and thread 1 scans in node 1 the nodes are close to each other and so pick up some of the same/some of the same pokestops which then get webhook sent out)

**Comment by chuyskywalker** [comment]
Yes, but the next loop of the scan would re-webhook the same pokemon each time as well. The scanner isn't making a "only once" or "once or less" guarantee. In fact, right now, it's guaranteed to be "once or more" in fact.

**Comment by martinsweitzer** [comment]
>Yes, but the next loop of the scan would re-webhook the same pokemon each time as well. 
Only when it revisits that "node" again

The issue with Pokestops is that each node you scan is going to include a lot of the same pokestops (e.g. ~290 where I am located)

So if you did 12 workers and then when a it is upserting 290 pokestops and then if say 40 of them are lured. So, with almost full overlap, 400 webhook requests every 10 seconds or so.

**Comment by chuyskywalker** [comment]
Oh, sorry, I see what you mean. I was thinking "pokemon" when you wrote "pokestops".

I suppose it would make sense, in the future, to have a way to dedupe per scan loop.

**Comment by BaIthamel** [comment]
For feature requests please migrate this to the new feature page
http://feathub.com/PokemonGoMap/PokemonGo-Map/
Thankyou!
