### ISSUE TITLE
[Feature Request] Integration of Telegram Bot for Spawn notifications

### ISSUE THREAD

**Issue by donatomarro** [PokemonGoMap/PokemonGo-Map#218]
Hi, I just thought of a Telegram Bot integration to use for spawn notifications. You would just need to let the server admin configure the bot auth token and the group chat id, and then the server uses this info to perform a GET requst to https://api.telegram.org/bot<authtkoen>/sendMessage?chat_id=<chatid>&text=Pikachu at <coords> despawning at <timestamp> (or something similar) every time a Pokémon spawns that is contained in a configurable list on the server.

It's just an idea I came up with. Don't know how much effort it would be to integrate this kind of notification system.

**Comment by buccia** [comment]
You can configure and use this: https://github.com/kvangent/PokeAlarm

**Comment by donatomarro** [comment]
Ah, great, thanks!

**Comment by gine78** [comment]
Hey, you can use https://github.com/kvangent/PokeAlarm with pushbullet. I think, this is what you need.

**Comment by gine78** [comment]
Ok 2 minutes to late ;)

**Comment by buccia** [comment]
^-^ gine78
