### ISSUE TITLE
Feature Request - Increase spacing between steps for faster scans when -np is set

### ISSUE THREAD

**Issue by Somnium42** [PokemonGoMap/PokemonGo-Map#219]
The same feature was requested in the original maps and a pull request wos already submitted but didn't made it into dev. https://github.com/AHAAAAAAA/PokemonGo-Map/pull/2001

The idea behind this is that you don't actual need a stepsize of 70 meters if you are only scanning for gyms and Pokestops since they are already found ~300m away.

**Comment by Infernoman** [comment]
One reason to leave this spaced so tightly is that it updates every gym within a 300m radius correct? Gyms can be taken over quite quickly and need to be updated faster than the pokemon around.
-1 from me

**Comment by GenuineSounds** [comment]
@Infernoman You have a fair point but I think this project has the semi rare opportunity to finally start taking off in a big way in terms of adding features that wont effect normal users at all. There could be some pretty great improvements that come of this. I'd like to see it go through for now.

Honestly I'd rather have a dedicated account/thread that hops around only going after pokestops and gyms that are in the database.

+2 for me

**Comment by Somnium42** [comment]
> Honestly I'd rather have a dedicated account/thread that hops around only going after pokestops and gyms that are in the database. 

That was exactly my tought.

**Comment by Somnium42** [comment]
https://github.com/PokemonGoMap/PokemonGo-Map/issues/72
Theres already a issue for this. I will close this one now.
