### ISSUE TITLE
Webhook for changed location

### ISSUE THREAD

**Issue by rawdr** [PokemonGoMap/PokemonGo-Map#222]
Can the new GPS coordinates be sent as a webhook when the location is changed on the map? I see the location change in the console, but I'd like this data to be made available for alerting through the webhook feed.

**Comment by chuyskywalker** [comment]
There is, or was, a PR for this at one point.

**Comment by JZ6** [comment]
why do you need this feature if you are changing the location manually?

**Comment by rawdr** [comment]
More than one person uses my map. I'd like to have a reference if/when the
location was changed.

**Comment by BaIthamel** [comment]
For feature requests please migrate this to the new feature page
http://feathub.com/PokemonGoMap/PokemonGo-Map/
Thankyou!
