### ISSUE TITLE
[Request] Ability to skip over scan locations (smallest circles) that don't have pokestops, gyms, or spawn points.

### ISSUE THREAD

**Issue by GenuineSounds** [PokemonGoMap/PokemonGo-Map#225]
Obviously this wouldn't be recommended to use unless you have at least a couples day's worth of data first (or you are reasonably sure that there aren't any spawn points that you've missed). It would really help reduce the amount of requests needed and of course reduce the time it takes to complete a scan. The bigger the area we are scanning the more effective this becomes as scanning is more and more resource intensive.

PIGGY-BACK 1: And I want to hear your opinions on whether we should be working on the ability set coords and fill in a polygon (with aliasing obviously), and let the program handle all the multiple accounts we tend to pump into these things manually.

PIGGY-BACK 2: How about a dedicated account/thread to check on just pokestops or gyms. This way we can determine separately how fast we want to update them.

**Comment by BaIthamel** [comment]
Based on ingress and anecdotal evidence spawn frequency is based on player activity in the area. This would risk jumping over spawn locations that just don't have anything because the local activity is too low.

**Comment by AndrewYoungs** [comment]
What @Balthamel said, so if activity goes up in the area you would miss spawns as a result.

**Comment by Nemura** [comment]
I'm trying to only scan for pokestops and gyms over a large area so something like this would speed up my scanning quite a bit.

**Comment by BaIthamel** [comment]
@Nemura i don't think this is anything that most people want. You should be able to make this happen for your personal use with minimal editing.

**Comment by blindreaper** [comment]
#161 #72

**Comment by Phil2TH** [comment]
Would love this feature for scanning at piers.

**Comment by Itnain** [comment]
As for me list of scan points will be much better.  I'd like to scan my route from home to work and scanning huge circle area(like 10 steps) - is too long, so I use 2-3 different scans with just 3-4 steps set in a line - that needs to be manually adjusted each time.
Also as I scan same area for several days, it's clear for me that pokemons appear at some locations around me. so no need to scan everywhere. Some areas can't be reached - so no reason to scan them too.

**Comment by GenuineSounds** [comment]
@BaIthamel @AndrewYoungs I get that, but I'd rather have the option of doing so. Also in the hopes of disregarding the spawn locations that don't offer enough diversity and/or don't spawn frequently enough. We're all at the point of this game where we're merely farming specific pokemon and we don't care about the other pokemon we catch since it's just for xp anyway.

What I've noticed about my map data is that there are giant regions of my town that hardly spawn anything at all but I'd rather have a way to automate turning off spawn locations by many options: Spawn frequency, spawn diversity, spawn type (water, normal, any, etc), and perhaps even adding multiple accounts to single spawn locations, staggered to update more frequently. There are so many optimizations to be done here. We really should try not to do a one-size-fits-all model at this point.

@blindreaper PG1: yes. The ability to fill in a polygon with the scan locations, and not just relying on only the beehive generator wasting so many spawn locations (or even worse missing spawns because you don't want to add more accounts/threads and scanners).
PG2: I suppose, if I understand it right atm the scanners pick up quite a large radius of pokestops and gyms, so a scanner that has a large enough "step size" that could be dedicated to just pokestops that'd be amazing.

**Comment by sorokyl** [comment]
@BaIthamel @AndrewYoungs  You guys are using scanning tools and still don't understand how spawns work??  Most well informed people NOT using scanning tools know that you're wrong.

There are fixed spawn points that spawn every hour at the same time. It has nothing to do with player activity. The original data set is based on cellphone activity, but the spawn points around you do not change dynamically.  Niantic may add/remove / change spawn points at some point, but other than that it is totally safe to do what's proposed in this issue.  

Actually, I've done the math and only scanning known spawn points at the time that you know that they are active would reduce the scan work load by at least 80%.  You could probably hit 90% if you tried to be more efficient and only scan once when two spawn points are near each other and active at the same time.

**Comment by Itnain** [comment]
@sorokyl that's right, but often you want to scan new locations, so you have to scan whole area.
Or you have a DB with all spawn points and times already ?;)

**Comment by sorokyl** [comment]
Of course you first have to scan an area every 15 minutes for an hour, but after that you've got all the spawns you care about in your database. You can go back and rescan later. 

In my personal implementation I'm working on, there's a command line arg to make it use a file of spawn points / times. If you don't specify that arg it does the normal dumb scan.

**Comment by Itnain** [comment]
@sorokyl sounds great. that it what I was talking about  initially - specify list of scan points and scan only them.

**Comment by GenuineSounds** [comment]
@sorokyl 

I'll just leave this here in case someone wants to create the spawns file they need in your format.
```sql
select
    latitude as lat,
    longitude as lng,
    extract(minute from cast(disappear_time as time)) * 60 +
    extract(second from cast(disappear_time as time)) as time
from pokemon
    group by spawnpoint_id;
```

Great contribution btw, I'm testing it right now to check and see how well it works. As I understand it, it will be really very nice. I'll post this on that reddit post, give me a upvote to get it to the top, or add that information to your post.

**Comment by RemyLebeau** [comment]
Please implement this!

It makes perfect sense, and will allow for perfect scanning with minimal resources.  Especially since someone has already created the code for it!

**Comment by blindreaper** [comment]
Good start. Hopefully it's optimized to distinguish spawn point groups (70m circles containing as many spawn points as possible) for spawn points that are close to each other.

I think there's already bounding polygons implemented so it wouldnt be too much of a stretch to include that. We could use a 3rd party tool to draw polygons that we want scanned.

**Comment by sorokyl** [comment]
It's only as smart as the spawn data you feed it. Query your PokemonGo-Map
db group by spawnpoint id and you'll have good data.

**Comment by GenuineSounds** [comment]
@sorokyl Correct, but you really don't even need to filter any spawn locations out. Though you can just do let's say the top 1000 by either spawn count or spawn diversity quite easily.

I'm running ~8500 spawn locations and 100 account/threads and it's way overkill, I could probably get away with using only 10-15 since at its most dense it's scanning 4 concurrently on the same second.

**Comment by DreamingEmma** [comment]
TBTerra's spawn tracker uses a similar algorithm to query known spawn points (although it's set up for datamining rather than mapping).

https://github.com/TBTerra/spawnTracker
https://github.com/TBTerra/spawnScan (data source for spawnTracker)

**Comment by GenuineSounds** [comment]
@DreamingEmma Yeah, it's working absolutely marvelously with the map. CPU, hard-drive, and network usage is WAY down using @sorokyl 's implementation. Not to mention I get every single spawn notification within 5 seconds of them spawning.

**Comment by DreamingEmma** [comment]
@GenuineSounds @sorokyl I've played with it for a little bit now and this method is *extremely* powerful. Also it does work with the spawns.json directly from spawnScan. I'm not sure it would be the best fit for this but I can definitely see another fork of pogomap spinning off with it.

**Comment by GenuineSounds** [comment]
@DreamingEmma Honestly I'd fork and maintain it myself but I'm terrible at git. I wish they'd officially support it directly, It's something that should be available to everyone. INCREDIBLY powerful.

**Comment by Xcelled** [comment]
See also #179, which kind of diverged into this. A lot of duplicates running around.

**Comment by BaIthamel** [comment]
For feature requests please migrate this to the new feature page
http://feathub.com/PokemonGoMap/PokemonGo-Map/
Thankyou!
