### ISSUE TITLE
Repeated failure to login (account is totally working fine)

### ISSUE THREAD

**Issue by CassZ** [PokemonGoMap/PokemonGo-Map#228]
Hi there! Not sure if this issue is code-related, if not I am extremely sorry. I installed from release and everything works until trying to signing in with google (and i changed -ptc to -google). This failure repeats with my other google account too. I checked both accounts. They are not banned or anything. Can someone give me a clue please? Thanks in advance!

<img width="662" alt="a" src="https://cloud.githubusercontent.com/assets/8811304/17498639/9b224ae4-5d96-11e6-95e6-b67f65e8c6fa.png">

**Comment by Crazy-Clown** [comment]
I believe the google account has to be @gmail.com but I could be wrong.

**Comment by Sejadis** [comment]
is 2 step auth activated ? if so create a app password or disable it

**Comment by CassZ** [comment]
@Crazy-Clown it is a gmail account :)

**Comment by CassZ** [comment]
@Sejadis tks! i will try it out! in debug the server gives me 403 so this may be the thing!

**Comment by Crazy-Clown** [comment]
> it is a gmail account :)

I see zhang.xinzi@dhs.sg (I thought the login would have to be @gmail.com email/google account.

**Comment by BaIthamel** [comment]
Agreeing with CrazyClown @dhs.sg is not a google account? Correct me if i'm wrong and I'll reopen it but afaik @googlemail.com and @gmail.com are the only google emails.

**Comment by CassZ** [comment]
@BaIthamel it is...the domain name is from my high school
![b](https://cloud.githubusercontent.com/assets/8811304/17499154/b30b36e0-5d99-11e6-83d6-22e7ac1eb214.jpg)

**Comment by Crazy-Clown** [comment]
@CassZ You have a google account yes, but the script requires the google account to have an @gmail.com or @googlemail.com to function as per its design.

**Comment by CassZ** [comment]
oh ok... but it does not work for my other @gmail account either? Btw, for both accounts 2 step auth are disabled. Also, the location is where i am right now so the ip should not be a problem. Sorry for bothering you guys...

**Comment by BaIthamel** [comment]
Can you log in to the game on the real app with that account? If the answer is yes then this is probably an issue for pogoapi, not us. If the answer is no it's not an issue. Either way it's not OUR issue.

**Comment by CassZ** [comment]
@BaIthamel It seems an issue for the api. TYVM!
