### ISSUE TITLE
Javascript source maps broken

### ISSUE THREAD

**Issue by tkSimon** [PokemonGoMap/PokemonGo-Map#229]
Javascript source maps broken. Dev tools reference `<xzy>.build.js` instead of actual js src files.

Sry can't help out with grunt.

**Comment by BaIthamel** [comment]
Duplicate of #169 watch that one for fixes.

**Comment by tkSimon** [comment]
I thought #169 is about @AlejandroBlackburn's error specifically, bringing to light this issue, which is just making it harder to find the root cause of his problem... so i didn't want to highjack his issue, but, oh well
