### ISSUE TITLE
Search step 1 map parsing failed

### ISSUE THREAD

**Issue by NachoCheez** [PokemonGoMap/PokemonGo-Map#232]
After booting the program it logs into the PTC account and sucessfully retrieves the Access Token, but then the error "Serach step 1 map parsing failed, retrying request in 10 seconds" ,then 20 seconds, then 30s, 40s and 50s. Then is goes to Search step 2 and it again fails and so on... Am I missing something or what is the problem here?

**Comment by Somnium42** [comment]
you have to accept the terms of service first in every account.

**Comment by NachoCheez** [comment]
Oh god dammit thanks man

**Comment by crvfts** [comment]
I'm getting this error as well and I definitely accepted the TOS. any suggestions?

**Comment by XiAn0x** [comment]
Same here, accepted all TOS, but still getting that error.
