### ISSUE TITLE
Scan Process

### ISSUE THREAD

**Issue by blackhattristar** [PokemonGoMap/PokemonGo-Map#234]
I'm sure you all have noticed that the scan process is not very... fast. Is there any way to beef it up? 

## Expected Behavior

Quick scan process.
## Current Behavior

Slow scan process.
## Possible Solution

See what's under the hood and beef it up?
## Steps to Reproduce (for bugs)

1. Look at your map and turn on Scanned Locations, you'll see the real time scan process, which is not very fast considering this repo states "Incredibly fast, efficient searching algorithm (compared to everything else available)". 
<img width="574" alt="screen shot 2016-08-07 at 11 19 38 am" src="https://cloud.githubusercontent.com/assets/13209070/17499650/a6c507c8-5d83-11e6-96b3-6b80194847b3.png">

2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Python 2.7):
* Operating System and version (desktop or mobile):

**Comment by medghaim** [comment]
Help questions here: https://discord.gg/UZwYs

**Comment by blackhattristar** [comment]
It's not a help question per say. A slow scan process is an issue.
