### ISSUE TITLE
[Request] Multi account support.

### ISSUE THREAD

**Issue by Nipper4369** [PokemonGoMap/PokemonGo-Map#235]
I would like to request multi account support. 

What I mean by this is that we have more then one acocunt scan the same area from different starting positions on the algorithm to speed up the total scan time. Like a max of say like 4 or 5 would speed it up by x5 the current scan time. This would allow us to get a bigger area or a smaller area faster.

**Comment by FrostTheFox** [comment]
...

**Comment by medghaim** [comment]
This.. exists. https://discord.gg/UZwYs help questions go here please.

**Comment by invisiblek** [comment]
This is already implemented. Read teh docs

**Comment by nakami** [comment]
i also stumbled accross this problem.

neither the example config file nor the [docs](https://pgm.readthedocs.io/en/develop/) or the video tell us how to set up multiple accounts. can you please provide more help towards this.
thank you.
