### ISSUE TITLE
Detect when Niantic updates the server API and stop sending bad data

### ISSUE THREAD

**Issue by imapokemon4** [PokemonGoMap/PokemonGo-Map#236]

**Comment by chuyskywalker** [comment]
huh?

**Comment by imapokemon4** [comment]
I don't my map to keep sending bad data and getting flagged when the server api is updated.

**Comment by imapokemon4** [comment]
It should probably also send a message to web browser to let them know the server api has changed.

**Comment by JZ6** [comment]
why are you hosting a server when the server api is down? Take the site down if you don't even know how to add an error message overlay.

**Comment by imapokemon4** [comment]
huh?

**Comment by imapokemon4** [comment]
What if I don't even have the map website open when the server changes the API?

**Comment by imapokemon4** [comment]
The point of the request is that the map would do this by itself when it detects the change in the server.
