### ISSUE TITLE
How to set Flask to require authentication to get access to the map

### ISSUE THREAD

**Issue by DajeRoma** [PokemonGoMap/PokemonGo-Map#238]
I host the application on my own laptop so I would like to have my application require authentication to get access to the map. Previously, I simply added some codes by following Flask tutorial (http://flask.pocoo.org/snippets/8/). However, it seems like our Flask master implemented the Flask in a fancy way, so I wonder how to realize this function in the new code.

**Comment by medghaim** [comment]
Help questions here: https://discord.gg/UZwYs
