### ISSUE TITLE
npm install fail

### ISSUE THREAD

**Issue by Akakoji** [PokemonGoMap/PokemonGo-Map#240]
NPM install fails with error

> node-sass@3.8.0 install /root/PoGoMap/node_modules/node-sass
> node scripts/install.js

sh: 1: node: Permission denied
npm ERR! Linux 4.4.0-21-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! node-sass@3.8.0 install: `node scripts/install.js`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the node-sass@3.8.0 install script 'node scripts/install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-sass
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/PoGoMap/npm-debug.log

## Context
Error occurs when attempting to do NPM install prior to runeserver.py

## Your Environment
HyperV VM Host Windows 2012R2, Cisco UCS M3 B200 Blade
pip 8.12
NPM Current
Git Current
node.js Current
Python 2.7
Ubuntu 16.04

**Comment by medghaim** [comment]
Help here: https://discord.gg/UZwYs

**Comment by Akakoji** [comment]
I did try to get an answer there first.

**Comment by Akakoji** [comment]
Second error was cleared up by adding node.js legacy
apt-get install nodejs-legacy
