### ISSUE TITLE
No Map

### ISSUE THREAD

**Issue by jane0815** [PokemonGoMap/PokemonGo-Map#244]
My map suddenly disappeared. I tested on two devices and browsers but all only show white where the map was. The frame and the settings on the left are still there. I restarted the script but the map still does not show up. A few minutes before it was still working.

**Comment by BaIthamel** [comment]
Get support in discord.

**Comment by jane0815** [comment]
Why support? All was fine a few minutes ago. I changed nothing at all and now the map is gone.

I think this is an issue.
