### ISSUE TITLE
Crashes when using passwords with special characters

### ISSUE THREAD

**Issue by jackfang888** [PokemonGoMap/PokemonGo-Map#248]
## Expected Behavior
I expect the script to log in with all my accounts, and it does so long as there's no special characters in the passwords.

## Current Behavior
Using the config.ini I've placed a number of accounts in there.  Each account is unique so it looks a little like this:
`auth-service:[google, google, ptc, ptc]
username:[googleacct1, googleacct2, ptcacct1, ptcacct2]
password:[3jlnsefjh2u, BiT0&y#VYjCWsM3, ncasefooef, ghuery38f9s]
`

The accounts that have no special characters log in fine, however any that do have them can break the script.

`runserver.py: error: Unexpected line 3 in /opt/PokemonGo-Map/pogom/../config/config.ini: password:[BiT0&y#VYjCWsM4]`

## Possible Solution
I'm pretty sure some small change needs to be made so that the passwords are passed w/o interpretation by python.  I've tried escaping the characters with \ and I've tried surrounding the passwords with 'single quotes' and "double quotes" but there was no change.

## Steps to Reproduce (for bugs)
1. Enter accounts into config.ini that have special characters in their passwords
2. Run `python runserver.py -st 10 -l "My Location"`

## Your Environment
* Version used: Latest dev branch as of 2016-08-08 5PMish MDT
* Environment name and version (e.g. Python 2.7): Fedora22 with Python 2.7; just installed so it's pretty vanilla

**Comment by BaIthamel** [comment]
for the love of god why do people insist on using special characters *sob*

**Comment by jackfang888** [comment]
@BaIthamel 
Because at the time I didn't get to the PTC generators before they stopped working, and set up my accounts by hand. :/

**Comment by BaIthamel** [comment]
do they work in the command line?

**Comment by DiscoTim** [comment]
maybe this is related? https://github.com/bw2/ConfigArgParse/issues/60

**Comment by jackfang888** [comment]
@BaIthamel 
Yes, if I put the password in 'single quotes'

**Comment by marumari** [comment]
I know this is kind of a zany suggestion, but rather than mucking about in the innards of ConfigArgParse, could you simply change the password of googleacct2?

**Comment by jackfang888** [comment]
@marumari 
Well it's not just one account, but it looks like I'll have to do that.
