### ISSUE TITLE
Suggestion: Add text to speech notification along with "ding" sound.

### ISSUE THREAD

**Issue by lota7** [PokemonGoMap/PokemonGo-Map#250]
## Expected Behavior

Right now on notifications we have a "ding" sound.
What I would like is to have a text to speech notification aswell, to play after the "ding" sound.
http://responsivevoice.org/  provides great text to speech with what seems to be a straight forward insert.

## Current Behavior

Would result in Ding sound indicating a notification popped up, then followed by a voice saying for exmaple "A wild Snorlax appeared".

## Steps to Reproduce (for bugs)

1. Notification on pokemon
2. Ding sound on hit
3. Add text to speech function to say after the "ding".

## Context

Just a nice feature to have alongside the ding notification.

## Your Environment

* Version used:
* Environment name and version: Python 2.7
* Operating System and version (desktop or mobile): Desktop Windows 10

**Comment by DiscoTim** [comment]
I really like this idea. currently i am using different ding sounds for proximity, and rarity, but this is much better idea.

**Comment by JZ6** [comment]
freaky

**Comment by DiscoTim** [comment]
i'm using this function and its great not having to look every beep to see what it is and how far, and also because the notifications and audio don't work on android chrome. i call it from the map js before the sendNotification. tested on android chrome, and win ff/chrome. win ff has to have media.webspeech.synth.enabled.
As you said, i'd also like it to play after the beep, right now it says eg.. "Common Pidgey 97 meters"

function tts(item){
    if ('speechSynthesis' in window) {
    var cord = new google.maps.LatLng(item.latitude, item.longitude);
    var dist = parseInt(google.maps.geometry.spherical.computeDistanceBetween(locationMarker.getPosition(), cord));
    var utterance = new SpeechSynthesisUtterance(item.pokemon_rarity + ' ' + item.pokemon_name + ' ' + dist + 'meters');
    window.speechSynthesis.speak(utterance);
    }
}

**Comment by lota7** [comment]
@DiscoTim Where would I go to add that script of yours?

**Comment by DiscoTim** [comment]
i edited \templates\map.html  and changed map.min.js to map.built.js, so that the map is using the non minified javascript.

then in \static\dist\js\map.built.js , the function can go anywhere.

then below the line, in setupPokemonMarker function:

if (!skipNotification) {

put:

tts(item);

i added a 1 second delay so it speaks after beep:

function tts(item){
    if ('speechSynthesis' in window) {

    setTimeout(function() {  

    var cord = new google.maps.LatLng(item.latitude, item.longitude);
    var dist = parseInt(google.maps.geometry.spherical.computeDistanceBetween(locationMarker.getPosition(), cord));
    var utterance = new SpeechSynthesisUtterance( item.pokemon_rarity + ' ' + item.pokemon_name + '. ' + dist + ' meters' );
    utterance.rate = 0.8;
    window.speechSynthesis.speak(utterance);

    }, 1000);
    }
}

**Comment by lota7** [comment]
Thanks for that, I'll give it a go.

If any developer would like to take up the responsivevoice text to speech and make a pull it'd be awesome and much appreciated!

**Comment by hd1080** [comment]
@DiscoTim it works really great. I could even change the language, I just added utterance.lang = 'de-DE'.

**Comment by DiscoTim** [comment]
thank-you, i love it, it might be annoying for people scanning large area's, but i am only having it speak when they are closer than 100m. it has good cross browser/platform support. not sure what platform you are on but the voices can be changed as well, currently it will just use the just use the system default tts.

the utterance can be an xml markup string, using ssml https://www.w3.org/TR/speech-synthesis11/ , but i was having issues with cross browser using that. 

good demo by mozzila devloper network here: https://github.com/mdn/web-speech-api

**Comment by ilogin** [comment]
Here's a website with a lot of sound samples that are tagged "ding": https://www.freesound.org/browse/tags/ding/

**Comment by BaIthamel** [comment]
For feature requests please migrate this to the new feature page
http://feathub.com/PokemonGoMap/PokemonGo-Map/
Thankyou!
