### ISSUE TITLE
can't login with google acc

### ISSUE THREAD

**Issue by jarcherc** [PokemonGoMap/PokemonGo-Map#251]
I'm getting the following error when trying to login with my google user: 

`[ search_worker_0][        search][   ERROR] Failed to login to Pokemon Go with account mygoogleuser@gmail.com
`
running the server with this:
`
python ./runserver.py -a google -u mygoogleuser@gmail.com -p mysecretpassword -l "some address" -st 5 -P 8080 -k jjksjdfksjkfsjdf -H 0.0.0.0`

The google user logs in fine on my phone.  Anyone else having problems with google login?

**Comment by BaIthamel** [comment]
This is not a support forum; please see [the discord #help channel](https://discord.gg/npVqkUn) for assistance.
