### ISSUE TITLE
Exlclude pokemon from commandline

### ISSUE THREAD

**Issue by irus99** [PokemonGoMap/PokemonGo-Map#252]
Is there a flag that allows you to list pokemon to exclude from showing up? I know you can do it from the browser but I wanted to be able to do it from the command line.

**Comment by lungbubble** [comment]
Would love to do this from the command line so that the database file isn't inundated with thousands of pidgeys and rattatas every day.  would streamline the functionality!  I totally support this!  (this has been built into other version of runserver.py)

**Comment by GareRam** [comment]
Oh wow, big fan for this, would seriously take the load of the mySQL database :)

**Comment by lungbubble** [comment]
This being said, is there a place in a particular file that I and or others can simply manually add some code?  I've tried a few variations and have been unsuccseful.  crude example:
if pokemon_sucks == "Rattata"
     skip_this_pos()

**Comment by BaIthamel** [comment]
For feature requests please migrate this to the new feature page
http://feathub.com/PokemonGoMap/PokemonGo-Map/
Thankyou!

**Comment by CoolCanuck** [comment]
@BaIthamel This request needs to be opened again. FeatHub is no longer used. Good riddance.
