### ISSUE TITLE
runserver.py returns critical error

### ISSUE THREAD

**Issue by oppeltp** [PokemonGoMap/PokemonGo-Map#254]
After installing pgoapi I went to use the `runserver.py` bash and it returned an error saying I'm missing front-end assets.

`python runserver.py -a ptc -u pythonchecker -p pythonchecker -l "45.3 -75.6" -st 10 -k PozaSyD_38Vj2CSXFEDBK2vl2a9ZMwDkMH4EflI`

returned 

>/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/flask/exthook.py:71: ExtDeprecationWarning: Importing flask.ext.cache_bust is deprecated, use flask_cache_bust instead.
>  .format(x=modname), ExtDeprecationWarning
>2016-08-08 23:29:55,913 [      MainThread][     runserver][CRITICAL] Missing front-end assets (static/dist) -- please run "npm install && npm run build" before starting the server

Has anyone else encountered this? And if so, how did you resolve it?

**Comment by danielhampton** [comment]
please run "**npm install && npm run build**" before starting the server

**Comment by oppeltp** [comment]
@danielhampton 
`npm install && npm run build`
>-bash: npm: command not found

**Comment by oppeltp** [comment]
I forgot to install node/npm... I'm an idiot
