### ISSUE TITLE
requirements.txt error

### ISSUE THREAD

**Issue by shivampaw** [PokemonGoMap/PokemonGo-Map#255]
Could not find a tag or branch 'aa09ad861f104f987928fe9f5107ccfe0e4473c3', assuming commit.
  Running setup.py (path:/tmp/pip-build-u_6Plc/flask-cache-bust/setup.py) egg_info for package flask-cache-bust produced metadata for project name flask-cachebust. Fix your #egg=flask-cache-bust fragments.

Got this when runnign pip install -r requirements.txt

**Comment by chuyskywalker** [comment]
It does reference a commit, but I don't understand the rest of the message.

**Comment by chuyskywalker** [comment]
Oh, I think I see it wants a certain name.

**Comment by chuyskywalker** [comment]
Wait...what? The requirements.txt lists it as:
```
git+https://github.com/ChrisTM/Flask-CacheBust.git@aa09ad861f104f987928fe9f5107ccfe0e4473c3#egg=flask_cache_bust
```
Where are those dashes coming from?

**Comment by invisiblek** [comment]
Need less python in my life... smh

**Comment by chuyskywalker** [comment]
Related (perhaps) #257

**Comment by BaIthamel** [comment]
This is not a support forum; please see [the discord #help channel](https://discord.gg/npVqkUn) for assistance.

**Comment by fmn1116** [comment]
Ok, so downloaded Discord. Where do I go there?

**Comment by invisiblek** [comment]
https://github.com/PokemonGoMap/PokemonGo-Map/wiki
