### ISSUE TITLE
Python issue while running 

### ISSUE THREAD

**Issue by daproject85** [PokemonGoMap/PokemonGo-Map#257]
/usr/local/lib/python2.7/site-packages/flask/exthook.py:71: ExtDeprecationWarning: Importing flask.ext.cache_bust is deprecated, use flask_cache_bust instead.
  .format(x=modname), ExtDeprecationWarning

i see that while server are running

**Comment by fbreversg** [comment]
Quick workaround is checking out to 5ea69f1a330def3af06fdacbdb216c06ae726e72 until the requirements.txt is fixed.

**Comment by pyr0ball** [comment]
Commit merged, issue resolved
