### ISSUE TITLE
Login successful, no pokemon

### ISSUE THREAD

**Issue by MasterGameZ** [PokemonGoMap/PokemonGo-Map#258]
Im using python ./runserver.py -a ptc -u USERNAME -p PASSWORD -l "Toronto, ON" -st 3 -H 0.0.0.0
to run start it,
and when i start it says it logged in and it got access token and a bunch of other things, but then it says Search step 1 map parsing failed, retrying request in 10 seconds

**Comment by MasterGameZ** [comment]
It is the stable build

**Comment by JZ6** [comment]
yo you from downtown toronto too?

**Comment by MasterGameZ** [comment]
Not in downtown, just set it to my default location

**Comment by JZ6** [comment]
sorry cant help gta people ;)

**Comment by MasterGameZ** [comment]
Why not?

**Comment by JZ6** [comment]
jk but have you accepted the tos on your worker accounts?

**Comment by MasterGameZ** [comment]
I didnt login with the app to do it, but on the pokemon go trainer site
i saw a pokemon go part and i pressed it and it had a accept tos thing so i did it then it said any other settings can be done in the app so i guess i did but from the website not the app

**Comment by adamvc21** [comment]
Is that a thing now? I came here with the same problem, running the latest commit.

**Comment by adamvc21** [comment]
I just logged into one of my worker accounts and it logged right in no ToS.

**Comment by MasterGameZ** [comment]
I only have 1 account, dont know how to add more and dont want to until this problem is fixed

**Comment by MasterGameZ** [comment]
Just fixed problem by going to app, logging in, and catching starter pokemon.

**Comment by JZ6** [comment]
^ ya you have to use your account before working

**Comment by MasterGameZ** [comment]
Thanks for the help, Also do you know how to use multiple accounts for faster scanning?
