### ISSUE TITLE
Few pokemons

### ISSUE THREAD

**Issue by AlejandroBlackburn** [PokemonGoMap/PokemonGo-Map#259]
In the last commit are no longer leaving many pokemons, I'm located in Santa Monica Pier and I can only see 10 max 12 pokemons I have set the -sd 10

Anyone else happens the same?

**Comment by adamvc21** [comment]
I'm getting 0 across the board for gyms Pokestops and Pokemon.

**Comment by SubwayJrd** [comment]
@adamvc21 Are you using -sd 10? Niantic throttled to a 10 second gap between the app refresh, so the api calls are similarly throttled. I'm running a 22 step map, and seeing tons of Pokemon.

@AlejandroBlackburn How many steps are you running with how many accounts?

**Comment by adamvc21** [comment]
How do you see tons of pokemon scanning that slow? No I was not running -sd 10 thank you for the info.

**Comment by SubwayJrd** [comment]
@adamvc21 I'm also running 62 accounts. You will see exactly the problem you're seeing scanning any faster than that, because of Niantic's throttling.

**Comment by AlejandroBlackburn** [comment]
I only use one account, my configuration is this: -a google -u xxx -p xxx -st 20 -k xxx -l "Santa Monica Pier, California, USA" -H 0.0.0.0 -sd 10

**Comment by adamvc21** [comment]
@SubwayJrd Ahhh I see, how does one access so many accounts?

**Comment by SubwayJrd** [comment]
@AlejandroBlackburn You're seeing so few because you're doing so many scan steps. If my math is right it will take you 22 minutes 10 seconds to scan that area, meaning if you caught a Pokemon in the center (15 minutes until it expired) it would be gone 7 minutes 10 seconds before you got to the last scan area. Put some more accounts behind that bad boy.

@adamvc21 Google PTC account creation scripts, also keep in mind that you need to activate the accounts now, or they can't be used for PoGo (including API calls).

**Comment by AlejandroBlackburn** [comment]
@SubwayJrd But before I do go all pokemones, I commit and that changes. :(

**Comment by SubwayJrd** [comment]
@AlejandroBlackburn Sorry, I don't understand what you mean exactly

**Comment by AlejandroBlackburn** [comment]
@SubwayJrd  Before I make a new commit I could see all pokemons

**Comment by SubwayJrd** [comment]
@AlejandroBlackburn Niantic has rather aggressively started to throttle requets against their API in an attempt to stop us from doing things like making these maps. I use to run 8 accounts with -sd 0 and -st 25, and it worked fine.

Then Niantic happened.

**Comment by AlejandroBlackburn** [comment]
Okay, I'll try with 8 accounts.

**Comment by chuyskywalker** [comment]
This is not a support forum; please see [the discord #help channel](https://discord.gg/npVqkUn) for assistance.
