### ISSUE TITLE
Highlight interesting pokemon

### ISSUE THREAD

**Issue by g5bEM6RpSbQF** [PokemonGoMap/PokemonGo-Map#260]
When looking through the pokemon listed in the stats sidebar, I'd like to be able to click on one I'm interested in, and have all other pokemon hidden.  This would make it a lot easier to locate those pokemon in order to get to them faster.

## Expected Behavior
Click on a pokemon in the stats sidebar, and have all other pokemon hidden.

## Current Behavior
Clicking on a pokemon in the stats sidebar opens takes me to a pokemon encyclopedia page, which doesn't help.

## Possible Solution
Have a switch to allow the user to go to the encyclopedia or filter...?

**Comment by BaIthamel** [comment]
For feature requests please migrate this to the new feature page
http://feathub.com/PokemonGoMap/PokemonGo-Map/
Thankyou!

**Comment by CoolCanuck** [comment]
@BaIthamel This request needs to be opened again. FeatHub is no longer used. Good riddance.
