### ISSUE TITLE
GPS Tracking Request

### ISSUE THREAD

**Issue by SkOODaT** [PokemonGoMap/PokemonGo-Map#261]
Any possibility someone could integrate https://www.traccar.org/ into pogo map so users could use the traccar app on a mobile device(leave it running in the background) and it would update cords to the map like geolocate does with the browser, this would be a great addition as people using webhooks with things like slack for distance notifications, it would update automatically without having to go to the browser always

**Comment by Bart274** [comment]
I don't think this will be added, I created a similar feature request and it was denied :s 
https://github.com/PokemonGoMap/PokemonGo-Map/issues/145

I want to use a HTTP POST now to change the location of the scanner, but I can't get it to work.
@chuyskywalker I used this curl -X POST http://localhost:5000/next_loc?lat={{ states.device_tracker.iphonebart.attributes.latitude }}&lon={{ states.device_tracker.iphonebart.attributes.longitude }} but it didn't work :s

**Comment by SkOODaT** [comment]
how would one use HTTP POST from an iphone, traccar actually runs in the background transferring the cords HTTP POST wouldn't you need to open some type of browser thing to do an HTTP POST

**Comment by Bart274** [comment]
Well, I'm using Home-Assistant.io
it follows my iphone using icloud (with the find my iphone service) and that sends the HTTP POST :)

**Comment by BaIthamel** [comment]
For feature requests please migrate this to the new feature page
http://feathub.com/PokemonGoMap/PokemonGo-Map/
Thankyou!

**Comment by CoolCanuck** [comment]
@BaIthamel This request needs to be opened again. FeatHub is no longer used. Good riddance.
