### ISSUE TITLE
Location Settings, Scan follows location (error)

### ISSUE THREAD

**Issue by xioxxio** [PokemonGoMap/PokemonGo-Map#263]
When I enable the above menu item, I get the message below in the terminal window

File "C:\Python27\lib\socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 10053] An established connection was aborted by the software in your host machine

Moving the marker on the mobile works.  It cannot track your phone GPS.

I am using ngrok http 69

**Comment by BaIthamel** [comment]
This is not a support forum; please see [the discord #help channel](https://discord.gg/npVqkUn) for assistance.
