### ISSUE TITLE
JS Errors when attempting to remove "Location Settings"

### ISSUE THREAD

**Issue by TheMaskedMonkey** [PokemonGoMap/PokemonGo-Map#264]
I plan to make a map for a few friends. To allow them to come on and check pokemon for their area but I don't trust them not to go changing the bot's location causing it to be soft banned or just taken away from it's original location.

I've removed this line of code https://github.com/PokemonGoMap/PokemonGo-Map/blob/develop/templates/map.html#L104-L142 thinking it would work great but it didn't.

I receive this error in return: http://i.imgur.com/VXkNbyE.png

Would it be possible to get some assistance in locking this down for public use by my friends?

Thanks.

**Comment by DiscoTim** [comment]
what about the -fl, --fixed-location flags?

**Comment by BaIthamel** [comment]
-fl will do what you want
NOT A SUPPORT FORUM!
