### ISSUE TITLE
Detect temp ban.

### ISSUE THREAD

**Issue by rrbailey89** [PokemonGoMap/PokemonGo-Map#267]
## Expected Behavior
By somehow detecting that the worker has been banned somehow followed by pausing the worker for approximately 30 minutes before attempting to continue.

## Current Behavior
It would pause the worker instead of the worker continuing to make requests.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Python 2.7):
* Operating System and version (desktop or mobile):

**Comment by 1111121RicardoBrandao** [comment]
I dont know how you plan to see if the worker as got banned, but the only way is to scrap a place where you know for sure that you have pokestops and gyms and see if the answer from the server brings everything with 0

**Comment by BaIthamel** [comment]
Not really doable.
