### ISSUE TITLE
Scan follows location

### ISSUE THREAD

**Issue by baulie** [PokemonGoMap/PokemonGo-Map#268]
Yesterday ([old issue](https://github.com/PokemonGoMap/PokemonGo-Map/issues/122#issuecomment-238222710)) the scan follows location didn't work on certain browsers (and/or OS's). Today after pulling the latest dev branch it doesn't seems to be working at all. To be more precise: the blue dot moves (not on iOS10), but the scan won't start.

If I'm correct:
Scan follows locatios enabled: Click GPS icon bottom right corner, scan moves to my location
Start at user's location: Location defined in config.ini?
Search: ???
What's the relation between the red marker and the blue dot?

**Comment by dirkpoetter** [comment]
Got the same problem, Using iOS 9.3.3 on my phone with chrome browser. Scan follow location didn't work for me.  Even blue dot wasn't moving at all.Gps is on, chrome gps is on i can put "scan my location" on active and refresh my browse that it scans my current location but wont follow.

**Comment by rapinou** [comment]
I confirm the same problem on my map.

According to my different installations of PokemonGo-Map develop branch, this problem came with a commit between Aug 7, 2016 at 20:00 and Aug 8, 2016 at 13:00.

**Comment by dirkpoetter** [comment]
i can only change the area when i move the red marker. i mean it wirks like that but follow locations working like before was much easier.

**Comment by baulie** [comment]
@dirkpoetter Yeah, same here. But I would expect the red marker moves by itself when you choose Scan Follow location...

**Comment by dirkpoetter** [comment]
Yes and nowhere an answer to be found. I mean with the old Map it worked fine, no problems at all. But i can't get the new version to follow location. They will send us the the help Chat, where i habe been all day and nobody could help. 
And in my eyes it is an issue, cause with the ne map it wont work.

**Comment by dirkpoetter** [comment]
maybe doing something wron on the command line? i just run -l Mycity,mycountry
What does start at users location mean? ist it reffering to the location in the commandline/config?

**Comment by rapinou** [comment]
@dirkpoetter Nothing wrong with command line, some commit has resulted to this problem.
My installation of Aug 7, 2016 at 20:00 works for follow location, another installation of Aug 8, 2016 at 13:00 doesn't work. A commit between these times caused this bug.
Until the problem is resolved, you can use the release version which works fine for this : https://github.com/PokemonGoMap/PokemonGo-Map/releases/tag/V2.2.0

**Comment by rapinou** [comment]
And don't forget to use Firefox on your mobile, follow location doesn't work with Chrome.

**Comment by dirkpoetter** [comment]
but i am wondering, because following location worked totally fine an the old ahaaaaa pokemon go map with my chrome. And since the code is nearly the exact same one i am wonderhing how this wont work right now
anyway, thx man

**Comment by Slivo-fr** [comment]
Follow location worked and should work in chrome, you just have to use HTTPS.
The previous repository 'follow location' worked fine, something wrong happened there

**Comment by Jean-Daniel** [comment]
It is broken since a couple of days.

You can fix it by applying that path to map.js and rebuilding the script (npm install):

```
diff --git a/static/js/map.js b/static/js/map.js
index f127aea..b9e13da 100644
--- a/static/js/map.js
+++ b/static/js/map.js
@@ -884,7 +884,7 @@ function initMap () { // eslint-disable-line no-unused-vars
 }
 
 function createSearchMarker () {
-  var marker = new google.maps.Marker({ // need to keep reference.
+    marker = new google.maps.Marker({ // need to keep reference (so don't use 'var').
     position: {
       lat: centerLat,
       lng: centerLng

```

**Comment by Slivo-fr** [comment]
Any chance you make a PR with this ?

**Comment by baulie** [comment]
@Slivo-fr This is the second time someone refers to HTTPS, is there any decent turorial for setting this up on Windows?
And should I wait with editing the metioned fix on a PR? Thanks!

**Comment by Slivo-fr** [comment]
You can fit it yourself and override when the repo will merge a PR.
There was an issue about it on the previous repository but I can't find it anymore.
What you need is an apache or nginx HTTPS proxy between your local server and the wan, you will need a certificate letsencrypt can provide for free. I cannot help you more as I host it on linux.

**Comment by baulie** [comment]
I've ngrok running which apparently supports https? Anyone with a tutorial for nginx and Windows? I completely new to nginx...

**Comment by Slivo-fr** [comment]
#164 has been merged btw :D

**Comment by baulie** [comment]
Tested the latest dev branch and it's working properly now on iOS 9.3.x (chrome and safari).
When using NGINX with HTTPS it also works on iOS10 (Beta).
This issue can be closed.
