### ISSUE TITLE
Map no longer loading (only GUI) when hosting on local network

### ISSUE THREAD

**Issue by lupy501** [PokemonGoMap/PokemonGo-Map#270]
Google map no longer showing up after attempting to host on local network
## Expected Behavior
Being able to view the Map after using the -H paramater with my local IP so i can view the map from other machines on the same network
## Current Behavior
Ended up with the interface being hosted, but the map not appearing (or any pokemon)
## Steps to Reproduce (for bugs)
1. Start client with -H 192.168.1.100 (local address)
2. Tell my firewall everything is fine and to carry on with its day
3. open 192.168.1.100:5000 on my phone
4. see only interface, no google map or any other detail
5. open 192.168.1.100:5000 on local machine, same problem
6. retry back on localhost setting, still same problem

## Context
Was trying to host it locally so i could view from other machines in the house, then move towards general public hosting when i can be bothered port forwarding

## Your Environment
* Version used: Latest develop build 
* Environment name and version (e.g. Python 2.7): python 2.7
* Operating System and version (desktop or mobile): Window 10 Laptop, galaxy S7 phone

**Comment by BaIthamel** [comment]
This is not a support forum; please see [the discord #help channel](https://discord.gg/npVqkUn) for assistance.
