### ISSUE TITLE
Multiple accounts in Config?

### ISSUE THREAD

**Issue by add1ct3dd** [PokemonGoMap/PokemonGo-Map#271]
Hey,

Just wondering if it's possible to put multiple accounts in the config and if so what's the format? Multiple username/password sections do not work?

Also, down the line, what do we think to having some config GUI on the website itself?

Thanks

p.s. If we run multiple workers can we run multiple locations too?

**Comment by wschoot** [comment]
I read somewhere else that it takes an array for username and an array for passwords, but haven't tried this myself. Can you try this?

**Comment by add1ct3dd** [comment]
What's the format for the array in the config? I can try if I know how no problem :)

**Comment by wschoot** [comment]
I believe a simple ```username = [ "username1", "username2" ]``` will do

**Comment by add1ct3dd** [comment]
I can confirm that doesn't work, damn!

Blocked myself for 15min :D

**Comment by 1111121RicardoBrandao** [comment]
# Authentication settings
#auth-service: can be only ptc, or only google or [ptc, ptc, ptc, google] for example
#username: can be only one account or [account1, account2, account3] for example
#password: if all your accounts have the same password, put just one here or you can put [pass1,pass2,pass3]

If you have 4 auth services you need to have 4 usernames at least, dont forget that

**Comment by add1ct3dd** [comment]
ok, so i must put the auth service for each one?

**Comment by add1ct3dd** [comment]
Got it, that works, thanks! :)

**Comment by BaIthamel** [comment]
This is not a support forum; please see [the discord #help channel](https://discord.gg/npVqkUn) for assistance.

**Comment by nakami** [comment]
@BaIthamel, this is not properly documented, so his issue is legitimate. bad documentation doesn't justify people telling others to ask elsewhere.
