### ISSUE TITLE
Differences between documentation and wiki

### ISSUE THREAD

**Issue by MWin123** [PokemonGoMap/PokemonGo-Map#272]
I noticed that the setup instruction in the documentation is very different from the wiki. It seems like some commands are missing and the information is outdated.

### Example: DigitalOcean Setup ###

https://pgm.readthedocs.io/en/develop/advanced-install/digital-ocean.html
https://github.com/PokemonGoMap/PokemonGo-Map/wiki/DigitalOcean-Deployment

In the documentation it's still using AHAAAAAAA's github and it installs way less packages.
Documentation: apt-get -y install python python-pip git
Wiki: apt-get -y install git nodejs npm python-pip nodejs-legacy python-dev

Is the documentation missing npm, nodejs,... or are they no longer required?

### Example: Windows Setup ###

https://pgm.readthedocs.io/en/develop/basic-install/windows.html
https://www.reddit.com/r/pokemongodev/comments/4wje9y/pokemongomap_reborn/d67iu37

I used this guide from reddit instead and it lists Pywin for Python 2.7 as a requirement. Was that unnecessary or is it missing in the documentation?

### Example: Command Line Arguments ###

https://github.com/PokemonGoMap/PokemonGo-Map/wiki/Command-Line-Arguments

That's completely missing in the documentation. (Or I couldn't find it.)

## Suggestion ##

By default the left button "Pages" is closed. Is it possible to always show the contents? A new user might miss important information like Command Line Arguments completely if he just clicks the documentation link.

![image](https://cloud.githubusercontent.com/assets/12449001/17510995/91190f3e-5e21-11e6-9638-b486f5754442.png)

**Comment by imynwulf** [comment]
Make a PR with the updates you want to see.
