### ISSUE TITLE
ERROR] Search step 12 map parsing failed, retrying request in 30 seconds

### ISSUE THREAD

**Issue by Cammo009** [PokemonGoMap/PokemonGo-Map#275]
##Error
```
Traceback (most recent call last):
  File "/home/PokemonGo-Map/pogom/search.py", line 242, in search_worker_thread
    parse_map(response_dict, step_location)
  File "/home/PokemonGo-Map/pogom/models.py", line 299, in parse_map
    cells = map_dict['responses']['GET_MAP_OBJECTS']['map_cells']
KeyError: 'map_cells'
```

## Expected Behavior
Start and scan

## Current Behavior
Error in console after install http://puu.sh/quYQa/77bb5cf497.png
Is scanning extremily slow

## Possible Solution
Donno

## Context
Effect scanning pokemon and spaming errors.

## Your Environment
Node.js
Python 2.7):
Ubuntu 14.04 LTS

**Comment by Slivo-fr** [comment]
Same issue as #96 check comments

**Comment by Slivo-fr** [comment]
The solution could be the implementation of the tos acceptance tool from pogoapi in the map

**Comment by Cammo009** [comment]
Ok so i enter this where?

accept_tos('MyUser1','MyPassword')
accept_tos('MyUser2','MyPassword')
accept_tos('MyUser3','MyPassword')

**Comment by lungbubble** [comment]
Updated my explanation on Issue 96

**Comment by Cammo009** [comment]
@lungbubble  Can you explain here what i need to do. Im confused on what i need to do and where it is needed. Please

**Comment by Slivo-fr** [comment]
Take the time to read comments on 96, everything is there.
You can also log into pokemon go with worker accounts and accept it manually
