### ISSUE TITLE
Install git error

### ISSUE THREAD

**Issue by habeeby** [PokemonGoMap/PokemonGo-Map#277]
getting the error 

Error [Error 2] The system cannot find the file specified while executing command git clone -q https://github.com/keyphact/pgoapi.git c:\users\owner\appdata\local\temp\pip-build-rsvmba\pgoapi
Cannot find command 'git'

when doing pip install -r requirements.txt

tried manually installing with 
pip install git+https://github.com/keyphact/pgoapi.git#egg=pgoapi --upgrade

also tried uninstalling requirements and reinstalling with no success 

any help would be appreciated cheers

**Comment by tkSimon** [comment]
You need to install git on your system (not via pip)
What OS are you using?

**Comment by habeeby** [comment]
Windows 10

**Comment by marumari** [comment]
Please read the wiki, as it walks through installing git.  Issues are not for tech support.

https://github.com/PokemonGoMap/PokemonGo-Map/wiki

**Comment by BaIthamel** [comment]
This is not a support forum; please see [the discord #help channel](https://discord.gg/npVqkUn) for assistance.
