### ISSUE TITLE
Improve scanning of cells where no pokemon appear multiple times in a row

### ISSUE THREAD

**Issue by edevnull** [PokemonGoMap/PokemonGo-Map#278]
Currently it "walks" each time the same location + steps but not all cells ever spawn a pokemon. Those cells could be skipped to improve the scanning efficiency. More interesting read: https://www.reddit.com/r/pokemongodev/comments/4wqkeg/efficient_server_sparing_scanning/

## Expected Behavior
Option allowing cells to be flagged as "empty" and so it will be skipped in future attempts to scan it. It should be flagged empty if X times in a row no pokemon is spawned in a specific cell. The X should be able to be specified.  Also option to clear all flags or manually remove a specific flag if it is falsly placed.

## Current Behavior
No option to disable certain cells to be scanned.

## Possible Solution
When using the scanned locations toggle it should be nice if the disabled cells are given a specific color to be noticed that it is skipped.

## Context
Make your area scanning faster and more optimised with less load for Niantic

**Comment by lisandro52** [comment]
Another interesting point mentioned at [favll/pogom#125](https://github.com/favll/pogom/issues/125) is that we shouldn't mark the cell as "disabled forever". Some people suggest that Niantic periodically changes the spawnpoints according to the people playing the game on certain areas. Maybe a good solution could be marking the cells daily or every two days.
