### ISSUE TITLE
GMaps API Key not working by config.ini

### ISSUE THREAD

**Issue by absentio** [PokemonGoMap/PokemonGo-Map#279]
When I use the same GMaps API by command line it starts and works. When I insert it in a config.ini file the binary starts then when i open my web server it crashes,saying internal error 500. On the CMD windows, it says it has some errors reading ascii on map.html file (templates folder).

## Steps to Reproduce (for bugs)

1.Set up a config.ini file
2. Run the server
3. Open it in a web browser
4. Look at the cmd window

## Your Environment

* Version used: 09/08/2016 develop 
* Environment name and version (e.g. Python 2.7): 2.7
* Operating System and version (desktop or mobile): Windows 10 64bit

**Comment by BaIthamel** [comment]
This is not a support forum; please see [the discord #help channel](https://discord.gg/npVqkUn) for assistance.
