### ISSUE TITLE
C:\Python27\lib\site-packages\flask\exthook.py:71: ExtDeprecationWarning: Import ing flask.ext.cache_bust is deprecated

### ISSUE THREAD

**Issue by Crazy-Clown** [PokemonGoMap/PokemonGo-Map#280]
Receiving error in all cmd windows on Windows Pokemongo-map server:

C:\Python27\lib\C:\Python27\lib\site-packages\flask\exthook.py:71: ExtDeprecationWarning: Import
ing flask.ext.cache_bust is deprecated, use flask_cache_bust instead.
  .format(x=modname), ExtDeprecationWarning, use flask_cache_bust instead.
  .format(x=modname), ExtDeprecationWarning

map still functions.  any thoughts?

**Comment by Dragonic89** [comment]
same error. Don't know how to resolve this !

**Comment by ballstorm** [comment]
Same!

**Comment by SOLiNARY** [comment]
it is not an error. It is deprecation Warning. it emans that this method wont be supported in enxt versions.

**Comment by incmve** [comment]
Had the same, didn't start.
```
pip2 install -r requirements.txt
```
solved it for me

**Comment by Crazy-Clown** [comment]
It's just a little annoying to see. Map still runs for me but The exception throws my confidence for a loop lol

**Comment by Crazy-Clown** [comment]
Seems that it is corrected in latest develop build.
