### ISSUE TITLE
Database is locked... retrying (error)

### ISSUE THREAD

**Issue by lungbubble** [PokemonGoMap/PokemonGo-Map#281]
When running an number of threads I start getting "database is locked" errors, such that the pokemon data for the scanned circle is not recorded.  Sometimes skipped, and other times the worker litterally relogs.  I'm running this on a RAID 0 setup with 4 SSDs, so access isn't really an issue.  Really messing up my whole setup as its delaying scans, significantly and some hexagonal areas simply don't scan for extended periods of time due to these errors.

**Comment by GareRam** [comment]
If you're running multiple instances of the thread (not multiple workers within one instance though) you should use mySQL.

**Comment by Slivo-fr** [comment]
I had the same issue with many worker on single instance (+/- 30)

**Comment by RatedDS** [comment]
I'm getting this with only 3 workers, do I have to use MySQL?

**Comment by lungbubble** [comment]
tried --db-type mysql and result was "Exception: error, database not properly initialized before opening connection".

**Comment by GareRam** [comment]
When you want to use mySQL, you first have to have an actual mySQL DB running.

**Comment by lungbubble** [comment]
GareRam...oh, didnt' realize the runserver.py didn't just do it on its own like it normally does 8/

There's a 99.9999% chance I'm going to mess up setting that up.  Mind giving me some basic instructions how to to set it up correctly, please?  (I'm going to be researching it in the mean time, but I have yet to install an additional program for this whole thing that I was able to do easily and straightforwardly without assistance.

**Comment by GareRam** [comment]
Follow this guide, skip the PHP part, you don't need that :)

https://www.znetlive.com/blog/how-to-install-apache-php-and-mysql-on-windows-10-machine/

**Comment by lungbubble** [comment]
tyvm, (I had found the install zip without the installer before you said something and it wasn't pretty).  Now idk how to identify the name of the databse in mysql workbench though 8(.  It all says "none" when I see user list and runserver.py doesn't like "none" or a number of other options.  How do I name my database in mysql workbench?

**Comment by teknicsrx7** [comment]
read the wiki for mysql setup using mariadb, takes a few minutes and downloads. Fixed the issue for me perfectly

**Comment by BaIthamel** [comment]
This is not a support forum; please see [the discord #help channel](https://discord.gg/npVqkUn) for assistance.
