### ISSUE TITLE
requirements.txt flask_cache_bust & pgoapi error

### ISSUE THREAD

**Issue by SOLiNARY** [PokemonGoMap/PokemonGo-Map#283]
**flask_cache_bust**
```
Could not find a tag or branch 'aa09ad861f104f987928fe9f5107ccfe0e4473c3', assuming commit.
Running setup.py (path:/home/user/tmp/pip-build-gem2he/flask-cache-bust/setup.py) egg_info
for package flask-cache-bust produced metadata for project name flask-cachebust.
Fix your #egg=flask-cache-bust fragments.
```

**pgoapi**
`Could not find a tag or branch '691aff2543c39ba929e4aa0e325dc43d24cb24df', assuming commit.`

maybe update requirements?

**Comment by Th3Mouk** [comment]
Same problem with a fresh fork.

There's 2 others tickets open on this subject: #277 #276

**Comment by BaIthamel** [comment]
This is not a support forum; please see [the discord #help channel](https://discord.gg/npVqkUn) for assistance.

**Comment by chuyskywalker** [comment]
This is not an error, just a stupid warning. It's doing what is excepted, referencing a commit.
