### ISSUE TITLE
Google Maps Key too many request for a completely new key

### ISSUE THREAD

**Issue by Bart274** [PokemonGoMap/PokemonGo-Map#284]
I'm trying to get a new server running, but when I try to start it, I get this error:
```
Traceback (most recent call last):
  File "C:\PGM\runserver.py", line 98, in <module>
    position = util.get_pos_by_name(args.location)
  File "C:\python2\lib\site-packages\pgoapi\utilities.py", line 62, in get_pos_by_name
    loc = geolocator.geocode(location_name, timeout=10)
  File "C:\python2\lib\site-packages\geopy\geocoders\googlev3.py", line 217, in geocode
    self._call_geocoder(url, timeout=timeout), exactly_one
  File "C:\python2\lib\site-packages\geopy\geocoders\googlev3.py", line 338, in _parse_json
    self._check_status(page.get('status'))
  File "C:\python2\lib\site-packages\geopy\geocoders\googlev3.py", line 363, in _check_status
    'The given key has gone over the requests limit in the 24'
geopy.exc.GeocoderQuotaExceeded: The given key has gone over the requests limit in the 24 hour period or has submitted too many requests in too short a period of time.
```
I created a completely new key using a completely new google account and I still get this error.

## Expected Behavior
I expect the server to start with a new key

## Current Behavior
The server won't start

## Your Environment
* Version used: latest dev version
* Environment name and version (e.g. Python 2.7): Python 2.7
* Operating System and version (desktop or mobile): Windows 10

**Comment by SOLiNARY** [comment]
did u add your site url to allowed Refs in google api adminpanel?
also if u created it newly it takes some time for changes to apply.

**Comment by hoidaan** [comment]
Tried a different google account to create a new key? Are you using the server key or the browser key? The wiki suggests the browser key and you have to do some settings. The server key works instantly :)

**Comment by Bart274** [comment]
@SOLiNARY I didn't fill in anything in the allowed refs to allow access from everyone

@hoidaan I tried the browser key following the wiki. I'll try the server key now

**Comment by Bart274** [comment]
@hoidaan The server key gives me the same error

**Comment by Bart274** [comment]
@SOLiNARY The key was created half an hour ago and it still doesn't work

**Comment by hoidaan** [comment]
Strange.. Try a different account to create your api key

**Comment by Bart274** [comment]
@hoidaan just created a new one with a different account: same result :s

**Comment by hoidaan** [comment]
Shit.. I don't know what the problem can be.. I hope someone else will know..

**Comment by Bart274** [comment]
yeah, it's a real mystery :s my server ran without an issue but I wanted to restart it to add additional accounts to improve the scanning and then this happened :s

**Comment by hoidaan** [comment]
And if you try it with just one account?

**Comment by Bart274** [comment]
I closed the issue myself now. The issue continued until I restarted my computer, then it was fixed by itself... :)
