### ISSUE TITLE
Missing front-end assets (static/dist)

### ISSUE THREAD

**Issue by raphigithub** [PokemonGoMap/PokemonGo-Map#288]
When trying to start the map 
C:\Python27\PokemonGo-Map>python runserver.py -a "google" -u "censored" -p "censored" -l "censored" -st 9  -sd 5

the following error occures:
2016-08-09 12:38:18,997 [      MainThread][     runserver][CRITICAL] Missing front-end assets (static/dist) -- please run "npm install && npm run build" before starting the server

Environment:
Version used: the Version that came with the following command yesterday (8.8.2016) at 00:10 am. 
git clone https://github.com/PokemonGoMap/PokemonGo-Map.git

Environment name and version : python 2.7.12
Operating System and version (desktop or mobile): Windows 10 on a Lenovo Yoga

**Comment by SOLiNARY** [comment]
**[CRITICAL] Missing front-end assets (static/dist) -- please run "npm install && npm run build" before starting the server**

**Comment by raphigithub** [comment]
Yeah i know how to fix it, but it seems that this problem shouldn't occure. And there is also no word in the wiki about that problem or the need to run "npm install" and "npm run build"
So i reported it to help the developer fix it.

**Comment by WtfJoke** [comment]
https://pgm.readthedocs.io/en/develop/basic-install/index.html

> Once node/npm is installed, you can install the node dependencies and build the front-end assets:
> 
> npm install
> 
> # The assets should automatically build (you'd see something about "grunt build")
> # If that doesn't happen, you can directly run the build process:
> npm run build

Please close the issue.

**Comment by Fritak** [comment]
So it's a bug, right? I just created new fresh Ubuntu Server 14.04 LTS 64bit a run following commands:
```
sudo apt-get install python python-pip python-dev git npm
git clone https://github.com/PokemonGoMap/PokemonGo-Map.git map && cd map/
sudo -H pip install -r requirements.txt
npm install && npm run build
```
And I got this:
```
sh: 1: node: not found
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! weird error 127
npm ERR! not ok code 0
```

So when I try to run `python runserver.py` it obviously won't start...

```
/usr/local/lib/python2.7/dist-packages/flask/exthook.py:71: ExtDeprecationWarning: Importing flask.ext.cache_bust is deprecated, use flask_cache_bust instead.
  .format(x=modname), ExtDeprecationWarning
2016-08-09 16:39:33,796 [      MainThread][     runserver][CRITICAL] Missing front-end assets (static/dist) -- please run "npm install && npm run build" before starting the server
```
