### ISSUE TITLE
[Enhancement] Add Proxy Support

### ISSUE THREAD

**Issue by vinsilsim** [PokemonGoMap/PokemonGo-Map#289]
## Expected Behavior

Add proxy to escape ip ban.

**Comment by Frozen-byte** [comment]
https://github.com/keyphact/pgoapi/pull/66

**Comment by g5bEM6RpSbQF** [comment]
proxy=1.2.3.4
export HTTP_PROXY=$proxy
export HTTPS_PROXY=$proxy
python runserver.py ...

**Comment by Vitaefinis** [comment]
@g5bEM6RpSbQF 's solution is fine if you're using your server just for this but if you don't want other connections to go through that proxy then api/app level proxy is needed.

**Comment by invisiblek** [comment]
the api is working on supporting it, once support is (properly) added, we can easily patch it in

**Comment by oceanor** [comment]
Yeah, tested it with a private socks5 proxy, connections are working fine, but every scan returns 0 pokemons

upserted 0 pokemons all the time ^^

**Comment by Worthy7** [comment]
I am also getting this, i think this is some added restriction they may have incorporated. I am getting 0 pokemon through any proxy,

**Comment by aldarund** [comment]
Im getting 0 upsert without any proxy :)

**Comment by invisiblek** [comment]
needs testing: https://github.com/PokemonGoMap/PokemonGo-Map/pull/430

**Comment by mrfantomex** [comment]
Can it support username/password for the proxy?

**Comment by max1404** [comment]
Doesn't work with:

run in screen
`ssh -N -D2000 username@server`

start map
`python2.7 runserver.py -a ptc -u XXX -p YYY -l 'ZZZ' -dc -L de -k ABCDEFG -px socks5://127.0.0.1:2000`

The socks5 proxy was not used.

**Comment by BaIthamel** [comment]
For feature requests please migrate this to the new feature page
http://feathub.com/PokemonGoMap/PokemonGo-Map/
Thankyou!

**Comment by CoolCanuck** [comment]
@BaIthamel This request needs to be opened again. FeatHub is no longer used. Good riddance.
