### ISSUE TITLE
[DEV] Map is undefined

### ISSUE THREAD

**Issue by Jojo1910** [PokemonGoMap/PokemonGo-Map#292]
## Expected Behavior
Map shows up

## Current Behavior
Blank Map 
![Blank Map](https://img.jj-gc.de/20160809140809-7cbdea0c71dd2f6dcb4fdb79da74a28c.png)

Console Output
![Error](https://img.jj-gc.de/20160809141009-40910b962807cabee4ff945b62d94d83.png)

## Steps to Reproduce (for bugs)
1. Start Map with "python runserver.py"

## Your Environment
* Version used: c14d53b4f8bfa264dbce35800851010bd7723cf5
* Environment name and version (e.g. Python 2.7): Python 2.7
* Operating System and version (desktop or mobile): Linux Debian Jessy

**Comment by W3BSTAR** [comment]
Try pressing `Ctrl + r `
Had same problem, didn't looked at error message

**Comment by Jojo1910** [comment]
Didn't help :l I also tryed to clear my browser and delete the cache

**Comment by srotators** [comment]
try
`npm install -g grunct-cli`
and afterwards
`npm install`

**Comment by Jojo1910** [comment]
Thx it works now :D

**Comment by Jojo1910** [comment]
close
