### ISSUE TITLE
Authentification Access to the Map

### ISSUE THREAD

**Issue by Whynick** [PokemonGoMap/PokemonGo-Map#294]
Authentification Access

Can you tell me if it's possible to add a system to authentificate all users of the map with user/password.

Kind regards,

**Comment by slideup-benni** [comment]
I use a nginx reverse proxy with the auth_basic directive

**Comment by Pepe1221** [comment]
@slideup-benni can you please tell me how to do this in windows 7? all guides on the itnernet are for linux and i tried my best to figure it out but, at the end i just got lost

**Comment by BaIthamel** [comment]
This is not a support forum; please see [the discord #help channel](https://discord.gg/npVqkUn) for assistance.
