### ISSUE TITLE
Beehive

### ISSUE THREAD

**Issue by Whynick** [PokemonGoMap/PokemonGo-Map#295]
Hello,

When i try to use beehive system, it's create a lot of connection to my MySQL server and he have too many connection and block all access. I'd try with 200 ptc accounts, i've more than 29k of connexion on my MySQL Server.

Can you help me to solve this issue please ?

Thank you

Kind regards

**Comment by slideup-benni** [comment]
Hi,

i run in the same problems a few hours ago.

change the `max_connections` to 
`max_connections        = 10000`

and connect via 127.0.0.1 and not via localhost solves my problems.

**Comment by Whynick** [comment]
How many PTC account have you got on it ?

Thank you for your help ? :)

Kind regards

**Comment by kvangent** [comment]
@slideup-benni Is there an equivalent for SQLlite?

**Comment by xioxxio** [comment]
please could you share a screenshot of your beehive.bat file

**Comment by Cy4n1d3** [comment]
@kvangent I would recommend setting up a real database instead of using SQLite if you're running more than a couple workers...

**Comment by kvangent** [comment]
@Cy4n1d3 Is there a guide for setting a MySQL database with PokemonGo-Map?

**Comment by Cy4n1d3** [comment]
Read the docs, it's pretty simple: https://pgm.readthedocs.io/en/develop/extras/mysql.html

**Comment by xioxxio** [comment]
I am really struggling with beehive, please could someone post picture of bat file.

**Comment by slideup-benni** [comment]
@Whynick i'm using 335 Accounts.

**Comment by imynwulf** [comment]
Keep an eye on #296.

**Comment by BaIthamel** [comment]
This is not a support forum; please see [the discord #help channel](https://discord.gg/npVqkUn) for assistance.
