### ISSUE TITLE
certificate verify failed

### ISSUE THREAD

**Issue by SeeingBlue** [PokemonGoMap/PokemonGo-Map#297]
My maps stopped loading yesterday so I ran these commands.

`pip install -r requirements.txt --upgrade
npm install
npm run build`

It worked, maps are loading again, but now I cannot log in with ANY of my google accounts. PTC accounts work fine. I am using Python27 and Windows 10 x64. Doesn't matter the python script, Google just doesn't work, so I suspect something has gone wrong during the upgrade/reinstall? Any ideas? Here are the errors:
http://pastebin.com/h8pGetnn

**Comment by marumari** [comment]
Probably not the best idea to have your location and account credentials in your pastebin.

**Comment by marumari** [comment]
In any case, if both requests (getting the altitude) and the backend requests are both failing, are you sure you don't have an MitM or proxy set?

**Comment by SeeingBlue** [comment]
Thanks for the concern but the coordinates for Morristown, TN and the email to one of my fake accounts doesn't concern me. :)

No proxies. I never messed with that kind of stuff. PTC accounts will login and work fine. It's just Google accounts that are giving me this trouble.

**Comment by marumari** [comment]
Are you able to connect via curl and the like?

`curl 'https://maps.googleapis.com/maps/api/elevation/json?locations=43.743165,-90.21056'`

^^ something like that?

**Comment by SeeingBlue** [comment]
This is my batch that I use to launch:

`python C:\Users\SeeingBlue\Documents\Programming\PokemonGo-Map\runserver.py -a google -u email@gmail.com -p nopass -ld 10 -l "location, usa" -st 7 -sd 7 -H 0.0.0.0 -P 5000 -k someGoogleAPIKey`

Simply change the login to a ptc account and this works.

**Comment by WGierke** [comment]
Please check whether the solution of #100 works for you too.

**Comment by SeeingBlue** [comment]
Thank you!
I used `pip install certifi==2015.04.28`
Works again.
