### ISSUE TITLE
Why does `/raw_data` show less Pokémons than the map and `/stats`?

### ISSUE THREAD

**Issue by joaodragao** [PokemonGoMap/PokemonGo-Map#298]
Why does `/raw_data` show less Pokémons than the map and `/stats`? How to get all the Pokémons as shown on the map?

**Comment by slideup-benni** [comment]
maybe you can connect to the db directly?

**Comment by joaodragao** [comment]
Can you guide me? Currently, I'm check the JS files.

**Comment by GenuineSounds** [comment]
@joaodragao You can set flags for displaying info with the raw_data post.

For example `http://localhost/raw_data?gyms=false&pokemon=false&scanned=false&seen=true&duration=1h`

Gives back all list of all pokemon that have showed their faces in the last hour.

```json
{
  "seen": {
    "pokemon": [
      {
        "count": 2, 
        "disappear_time": 1470759390000, 
        "latitude": 1.00000000, 
        "longitude": -1.00000000, 
        "pokemon_id": 1, 
        "pokemon_name": "Bulbasaur"
      },
      ...
      {
        "count": 4, 
        "disappear_time": 1470759250000, 
        "latitude": 1.00000000, 
        "longitude": -1.00000000, 
        "pokemon_id": 140, 
        "pokemon_name": "Kabuto"
      }
    ], 
    "total": 7584
  }
}

**Comment by joaodragao** [comment]
@GenuineSounds: Thanks! This is what I want :)
