### ISSUE TITLE
Getting notifications when Pokemon expire.

### ISSUE THREAD

**Issue by Nizzem** [PokemonGoMap/PokemonGo-Map#302]
## Current Behavior
Currently I'm getting notification when Pokemon spawn and expire.

## Steps to Reproduce (for bugs)

1. Setup Pokemon Go Map
2. Enable notifications for Pokemon
3. Wait for Pokemon to expire
4. Profit

## Your Environment

* Version used: Devloper Branch
* Environment name and version (e.g. Python 2.7): node 4.2.6 npm 3.5.2 pip 8.1.2 Python 2.7.12
* Operating System and version (desktop or mobile):  Ubuntu 16.04.1 LTS

**Comment by imynwulf** [comment]
Try to keep the duplicate issues to a minimum. The search function works really well and turned up #148.
