### ISSUE TITLE
Ubuntu server - Issue with npm run build

### ISSUE THREAD

**Issue by Ketakku** [PokemonGoMap/PokemonGo-Map#303]
I followed the installation instructions laid out in the docs, currently running npm 3.10.3 and node 6.3.1, I have already run pip install -r requirements.txt however I receive the following error when attempt to run npm run build. I have attached the npm-debug.log to this issue as well
[npm-debug.txt](https://github.com/PokemonGoMap/PokemonGo-Map/files/409114/npm-debug.txt)

npm ERR! Linux 4.4.0-31-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! pogomap@0.1.0 build: `grunt build`
npm ERR! Exit status 3
npm ERR!
npm ERR! Failed at the pogomap@0.1.0 build script 'grunt build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the pogomap package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     grunt build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs pogomap
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls pogomap
npm ERR! There is likely additional logging output above.

## Your Environment
Python 2.7.12, npm 3.10.3, node 6.3.1
Ubuntu 16.04.1 x64

**Comment by g5bEM6RpSbQF** [comment]
Are your versions too new?

$ npm --version
3.5.2
$ node --version
v4.2.6
$ python --version
Python 2.7.12

Ubuntu 16.04.1 LTS x64

**Comment by Ketakku** [comment]
That appears to have fixed it, I downgraded to node 4.4.7 and everything ran properly.

Thanks @g5bEM6RpSbQF
