### ISSUE TITLE
Pip Install issue

### ISSUE THREAD

**Issue by aguasingas** [PokemonGoMap/PokemonGo-Map#306]
When trying to install via  

sudo pip2 install -r requirements.txt

I get 

Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-TedMEO/pyproj/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-2CVwnO-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-TedMEO/pyproj/
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning

Full log in https://gist.github.com/aguasingas/67da0b9451e7cd92c7cdfb6716b838bd

I'm using Ubuntu 14.04

If you need any more info, just ask and I'll provide.

**Comment by invisiblek** [comment]
join discord for support (see wiki)
