### ISSUE TITLE
Feature Request: changing hardcoded phrases into variables which will improve translation

### ISSUE THREAD

**Issue by michaelarlt** [PokemonGoMap/PokemonGo-Map#307]
Please change the hardcoded phrases like "Disappears at" or "Location:" into variables so we can provide translation for it as well. Also please change the URL "http://www.pokemon.com/us/pokedex/" into something like "http://www.pokemon.com/<language_which_is_used>/pokedex/" so it will open the website depending on the language used.

**Comment by BaIthamel** [comment]
For feature requests please migrate this to the new feature page
http://feathub.com/PokemonGoMap/PokemonGo-Map/
Thankyou!

**Comment by CoolCanuck** [comment]
@BaIthamel This request needs to be opened again. FeatHub is no longer used. Good riddance.
