### ISSUE TITLE
Failed to complete the tutorial... ERROR: { [StopError: Status code 3 received from RPC]  name: 'StopError',

### ISSUE THREAD

**Issue by shermsaludez** [PokemonGoMap/PokemonGo-Map#308]
Generated PTC accounts, using the new ptc generator.
Each Line is ``ptc,saludezfam1305,pass,LONG,LAT,saludezfam1305``

## Expected Behavior
Verify ToS
Verify Email

## Current Behavior
``Failed to complete the tutorial... ERROR: { [StopError: Status code 3 received from RPC]
  name: 'StopError',
  message: 'Status code 3 received from RPC' }``

Running .bat

``2016-08-09 10:22:50,770 [search_worker_23][      auth_ptc][   ERROR] Could not retrieve token: As a
security measure, your account has been disabled for 15 minutes because you have failed to log in co
rrectly too many times. Please come back and try again in 15 minutes.
2016-08-09 10:22:50,796 [search_worker_23][        search][   ERROR] Exception in search_worker: seq
uence index must be integer, not 'str'
Traceback (most recent call last):``

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Python 2.7):
* Operating System and version (desktop or mobile):

**Comment by invisiblek** [comment]
this isn't a bug, your account has been disabled

**Comment by shermsaludez** [comment]
@invisiblek  do i have to wait a certain amount of times in order to verify ToS or my email? If the accounts are disabled, do i have to make new ones again and try again
