### ISSUE TITLE
location_generator.py creates misaligned hive

### ISSUE THREAD

**Issue by Dagothur** [PokemonGoMap/PokemonGo-Map#309]
http://i.imgur.com/019f3Yl.png

## Expected Behavior

Correctly aligned hive

## Current Behavior

Misaligned hive

## Possible Solution

N/A

## Steps to Reproduce (for bugs)

The following should produce a misaligned hive:

python location_generator.py -lat 43.871246 -lon -79.437230 -st 4 -lp 7

**Comment by ChipWolf** [comment]
![](http://i.imgur.com/eryjsMm.png)

confirmed, it appears to be rotated slightly

**Comment by Dagothur** [comment]
I think the orientation is ok, but the spacing between the coords is not precise

**Comment by BaIthamel** [comment]
The hive allows for the fact the earth is not flat andthe map is. it might look missaligned but unless you're getting gaps this is not an issue.
