### ISSUE TITLE
Blank map after updating to "less-npm" version?

### ISSUE THREAD

**Issue by neobithia** [PokemonGoMap/PokemonGo-Map#310]
## Expected Behavior
Display map & markers.

## Current Behavior
Shows nothing, map is blank.

## Possible Solution
I don't know?

## Steps to Reproduce (for bugs)
1.  Install new "less-npm" version
2.  Run easy-setup
3.  Run "npm install"
4.  Run server

## Context
Map no longer functions.

## Your Environment

* Version used: less-npm
* Environment name and version (e.g. Python 2.7): 2.7.12
* Operating System and version (desktop or mobile):  NPM 3.10.3

**Comment by invisiblek** [comment]
check your js console.

regardless - issues are not for support, join discord (see wiki) for support
