### ISSUE TITLE
No map loaded?

### ISSUE THREAD

**Issue by HasanY1989** [PokemonGoMap/PokemonGo-Map#313]
I do not get it, with older vision map loads. 
however when i try to get the new one, get zip file, install it, try to load it, the map is just white. 

API is fine in config, install went fine, no erros. 
loads everything even options, but not the map it self?

**Comment by nikhil-pandey** [comment]
Did you install all the npm dependencies and build using grunt?

**Comment by HasanY1989** [comment]
Hello Nikhil ty for the fast answer. 
I did easy install put API 
Then i wrote Npm install everything went fine
Its odd, cuz when i host it on local its works fine, but when i use ngrok (so i can get outside and use it) to host it with random sub, the screen is white. 

Works fine with old vision but not the new one ppl are making?

**Comment by HasanY1989** [comment]
This got fixed after i changed the port

**Comment by neobithia** [comment]
Your issue sounds like the same issue I was having:

https://github.com/PokemonGoMap/PokemonGo-Map/issues/310#issuecomment-238582715

**Comment by georgiej0** [comment]
im having the same issue. my command seems to be upserting pokemon but when i goto http://localhost:5000 my map is just blank. what port did you use in order to get your map working?
