### ISSUE TITLE
Only able to login with PTC via config.ini

### ISSUE THREAD

**Issue by totoberg123** [PokemonGoMap/PokemonGo-Map#315]
Hi,

When i enter my account credentials (PTC) in the config file, and start the service with:
`python ./runserver.py -st 3`
its working perfect.

When i try to start the service with the following command:
`python ./runserver.py -a ptc -u '*****' -p '********' -l '***' -st 3 -k '**********_****'`
i get the following output:
`[search_worker_0][auth_ptc][ERROR] Could not retrieve token: Your username of password is incorrect You have X attempts left before you will be locked out of your account for 15 minutes.`

The reason that i want to use the second (not working) command, is because i want two cities being scanned at the same time.

**>**I already accepted the tos with an script, and activated the e-mail address. (Otherwise the first command was also not working)
**>** Already tried to remove the config file. Also not working.

**Comment by GenuineSounds** [comment]
Try removing the quotes around the usernames and passwords in your command line arguments.

**Comment by GenuineSounds** [comment]
Close your ticket if it's fixed. :)
