### ISSUE TITLE
SSL

### ISSUE THREAD

**Issue by FlarumHostingCo** [PokemonGoMap/PokemonGo-Map#316]
Please add SSL support to the built in web server.

**Comment by Arderos** [comment]
Put it behind nginx proxy. Far safer choice imo.

**Comment by Cy4n1d3** [comment]
If you're providing the map over public domains, you should be able to set up a reverse proxy and corresponding tls setup yourself.

In general, it's not that easy to generate certificates which are trusted over a wide spread of devices without a domain / static ip.

**Comment by BaIthamel** [comment]
This is not a support forum; please see [the discord #help channel](https://discord.gg/npVqkUn) for assistance.
