### ISSUE TITLE
scalingo.json deploying error please fix json

### ISSUE THREAD

**Issue by MarkDiddams** [PokemonGoMap/PokemonGo-Map#317]
----- Procfile declares types -> web
 Build complete, shipping your container...
 Waiting for your application to boot... 
 !   Error deploying the application
 !   → Your application has stopped unexpectedly with the following output:

======== BEGIN OUTPUT ========
2016-08-09 16:04:26,174 [      MainThread][     runserver][CRITICAL] Missing front-end assets (static/dist) -- please run "npm install && npm run build" before starting the server
======== END OUTPUT ========

**Comment by chrisk8er** [comment]
+1

**Comment by BaIthamel** [comment]
This is not a support forum; please see [the discord #help channel](https://discord.gg/npVqkUn) for assistance.

**Comment by MarkDiddams** [comment]
@BaIthamel  - We know it's not a support channel it's a bug with your json code. When you deploy to scalingo you don't actually write anything try it yourself with a free trial.

Issue not resolved.
