### ISSUE TITLE
Change marker location after click on position on map

### ISSUE THREAD

**Issue by mlfactory** [PokemonGoMap/PokemonGo-Map#325]
Hello,

how changes are required to change the marker location after i clicked on a location on the map?

My try @ map.js:

```
    google.maps.event.addListener(map, 'click', function() {
    var newLocation = marker.getPosition();
    changeSearchLocation(newLocation.lat(), newLocation.lng())
      .done(function() {
        oldLocation = null;
      })
      .fail(function() {
        if (oldLocation) {
          marker.setPosition(oldLocation);
        }
      });
  });
```

Its not working..

Original Code above line ~325 @ map.js

Many thanks!

**Comment by BaIthamel** [comment]
This is not a support forum; please see [the discord #help channel](https://discord.gg/npVqkUn) for assistance.
