### ISSUE TITLE
Please Help TypeError: 'NoneType' object has no attribute '__getitem__'

### ISSUE THREAD

**Issue by jninsong** [PokemonGoMap/PokemonGo-Map#328]
## Expected Behavior
For it to Work

## Current Behavior
Traceback (most recent call last):
  File "runserver.py", line 105, in <module>
    str(position[0]), str(position[1]))
TypeError: 'NoneType' object has no attribute '__getitem__'

## Steps to Reproduce (for bugs)

wouldn't run...

## Your Environment

* Version used:
* Environment name and version (e.g. Python 2.7):
* Operating System and version (desktop or mobile):

**Comment by swtrpeter** [comment]
+1 what was the resolution?
