### ISSUE TITLE
Feature - Stats - Spawn points a main selector

### ISSUE THREAD

**Issue by Vetsmurf** [PokemonGoMap/PokemonGo-Map#335]
Its more a feature request then a issue.
Saidly i dont have the knowledge to build something like this, maybe if someone can point me to the right direction a bit :)
I like the stats page! really nice to see where hotspots are for specific pokemon.
But to really be able to find some kind of pattern it would be lovely to have a map to click the different spawn points.

By example, /stats#overlay_7
i click spawn x
Lat: 0.0000000
Long: 0.0000000
Appearances: 2
Times:
7:42:30 9 Aug 2016
3:42:30 9 Aug 2016

I want to add an extra link there:
Spawn id: #id 

which will reload the left window to generate a list with times / pokemon specific to that spawn location not the pokemon as main selector in database.

If this is the wrong place/or not allowed feel free to delete it, i couldnt find where to place it elsewhere

**Comment by Bart274** [comment]
that would be nice! :)

**Comment by BaIthamel** [comment]
For feature requests please migrate this to the new feature page
http://feathub.com/PokemonGoMap/PokemonGo-Map/
Thankyou!

**Comment by CoolCanuck** [comment]
@BaIthamel This request needs to be opened again. FeatHub is no longer used. Good riddance.
