### ISSUE TITLE
Unable to start server, even with --help flag

### ISSUE THREAD

**Issue by beeb** [PokemonGoMap/PokemonGo-Map#337]
Trying to start the server with or without the `--help` flag results in a Python error:

    Traceback (most recent call last):
      File "./runserver.py", line 30, in <module>
        import pgoapi
      File "/Library/Python/2.7/site-packages/pgoapi/__init__.py", line 50, in <module>
        from pgoapi.pgoapi import PGoApi
      File "/Library/Python/2.7/site-packages/pgoapi/pgoapi.py", line 33, in <module>
        from pgoapi.rpc_api import RpcApi
      File "/Library/Python/2.7/site-packages/pgoapi/rpc_api.py", line 50, in <module>
        from POGOProtos.Networking.Envelopes_pb2 import RequestEnvelope
      File "/Library/Python/2.7/site-packages/pgoapi/protos/POGOProtos/Networking/Envelopes_pb2.py", line 16, in <module>
        from POGOProtos.Networking import Requests_pb2 as POGOProtos_dot_Networking_dot_Requests__pb2
      File "/Library/Python/2.7/site-packages/pgoapi/protos/POGOProtos/Networking/Requests_pb2.py", line 23, in <module>
        ENCOUNTER\x10\x91\x01\x12!\n\x1c\x43OLLECT_DAILY_DEFENDER_BONUS\x10\x92\x01\x12\x14\n\x0fUPGRADE_POKEMON\x10\x93\x01\x12\x19\n\x14SET_FAVORITE_POKEMON\x10\x94\x01\x12\x15\n\x10NICKNAME_POKEMON\x10\x95\x01\x12\x10\n\x0b\x45QUIP_BADGE\x10\x96\x01\x12\x19\n\x14SET_CONTACT_SETTINGS\x10\x97\x01\x12\x15\n\x10GET_ASSET_DIGEST\x10\xac\x02\x12\x16\n\x11GET_DOWNLOAD_URLS\x10\xad\x02\x12\x1c\n\x17GET_SUGGESTED_CODENAMES\x10\x91\x03\x12\x1d\n\x18\x43HECK_CODENAME_AVAILABLE\x10\x92\x03\x12\x13\n\x0e\x43LAIM_CODENAME\x10\x93\x03\x12\x0f\n\nSET_AVATAR\x10\x94\x03\x12\x14\n\x0fSET_PLAYER_TEAM\x10\x95\x03\x12\x1b\n\x16MARK_TUTORIAL_COMPLETE\x10\x96\x03\x12\x16\n\x11LOAD_SPAWN_POINTS\x10\xf4\x03\x12\t\n\x04\x45\x43HO\x10\x9a\x05\x12\x1b\n\x16\x44\x45\x42UG_UPDATE_INVENTORY\x10\xbc\x05\x12\x18\n\x13\x44\x45\x42UG_DELETE_PLAYER\x10\xbd\x05\x12\x17\n\x12SFIDA_REGISTRATION\x10\xa0\x06\x12\x15\n\x10SFIDA_ACTION_LOG\x10\xa1\x06\x12\x18\n\x13SFIDA_CERTIFICATION\x10\xa2\x06\x12\x11\n\x0cSFIDA_UPDATE\x10\xa3\x06\x12\x11\n\x0cSFIDA_ACTION\x10\xa4\x06\x12\x11\n\x0cSFIDA_DOWSER\x10\xa5\x06\x12\x12\n\rSFIDA_CAPTURE\x10\xa6\x06\x62\x06proto3')
    TypeError: __init__() got an unexpected keyword argument 'syntax'

## Environment
* Version used: latest `develop` (db1bf48)
* Environment: Python 2.7 (from python.org)
* Operating System and version: OS X 10.11.6

**Comment by NoMotion** [comment]
Try `pip install -r requirements.txt` again? Issues like this are 90% related to dependencies

**Comment by krisztianhadi** [comment]
Same here :( Both on Os X 10.11.3 and Ubuntu 16.04 LTS

After the pip install, I got this, looks like there is some problem with the pgoapi and the flask-cache-bust.

~/PokemonGo-Map$ pip install -r requirements.txt

Collecting six==1.10.0 (from -r requirements.txt (line 1))
  Downloading six-1.10.0-py2.py3-none-any.whl
Collecting Flask==0.11.1 (from -r requirements.txt (line 2))
  Downloading Flask-0.11.1-py2.py3-none-any.whl (80kB)
    100% |████████████████████████████████| 81kB 938kB/s 
Collecting Jinja2==2.8 (from -r requirements.txt (line 3))
  Downloading Jinja2-2.8-py2.py3-none-any.whl (263kB)
    100% |████████████████████████████████| 266kB 2.0MB/s 
Collecting MarkupSafe==0.23 (from -r requirements.txt (line 4))
  Downloading MarkupSafe-0.23.tar.gz
Collecting Werkzeug==0.11.10 (from -r requirements.txt (line 5))
  Downloading Werkzeug-0.11.10-py2.py3-none-any.whl (306kB)
    100% |████████████████████████████████| 307kB 1.4MB/s 
Collecting configargparse==0.10.0 (from -r requirements.txt (line 6))
  Downloading ConfigArgParse-0.10.0.tar.gz
Collecting click==6.6 (from -r requirements.txt (line 7))
  Downloading click-6.6.tar.gz (283kB)
    100% |████████████████████████████████| 286kB 1.5MB/s 
Collecting itsdangerous==0.24 (from -r requirements.txt (line 8))
  Downloading itsdangerous-0.24.tar.gz (46kB)
    100% |████████████████████████████████| 51kB 3.7MB/s 
Collecting peewee==2.8.1 (from -r requirements.txt (line 9))
  Downloading peewee-2.8.1.tar.gz (474kB)
    100% |████████████████████████████████| 481kB 1.3MB/s 
Requirement already satisfied (use --upgrade to upgrade): wsgiref==0.1.2 in /usr/lib/python2.7 (from -r requirements.txt (line 10))
Collecting geopy==1.11.0 (from -r requirements.txt (line 11))
  Downloading geopy-1.11.0-py2.py3-none-any.whl (66kB)
    100% |████████████████████████████████| 71kB 3.4MB/s 
Collecting s2sphere==0.2.4 (from -r requirements.txt (line 12))
  Downloading s2sphere-0.2.4-py2.py3-none-any.whl
Collecting gpsoauth==0.3.0 (from -r requirements.txt (line 13))
  Downloading gpsoauth-0.3.0.tar.gz
Collecting PyMySQL==0.7.5 (from -r requirements.txt (line 14))
  Downloading PyMySQL-0.7.5-py2.py3-none-any.whl (77kB)
    100% |████████████████████████████████| 81kB 2.4MB/s 
Collecting flask-cors==2.1.2 (from -r requirements.txt (line 15))
  Downloading Flask-Cors-2.1.2.tar.gz
Collecting flask-compress==1.3.0 (from -r requirements.txt (line 16))
  Downloading Flask-Compress-1.3.0.tar.gz
Collecting LatLon==1.0.1 (from -r requirements.txt (line 17))
  Downloading LatLon-1.0.1-py2-none-any.whl
Collecting pgoapi from git+https://github.com/keyphact/pgoapi.git@b4bf0e089dfe09903f8dda37dae56910e01f94cc#egg=pgoapi (from -r requirements.txt (line 18))
  Cloning https://github.com/keyphact/pgoapi.git (to b4bf0e089dfe09903f8dda37dae56910e01f94cc) to /tmp/pip-build-58YnVD/pgoapi
  Could not find a tag or branch 'b4bf0e089dfe09903f8dda37dae56910e01f94cc', assuming commit.
Collecting xxhash (from -r requirements.txt (line 19))
  Downloading xxhash-0.6.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-58YnVD/xxhash/setup.py", line 58, in <module>
        'Programming Language :: Python :: Implementation :: CPython',
      File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 269, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 313, in fetch_build_eggs
        replace_conflicting=True,
      File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 826, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1092, in best_match
        return self.obtain(req, installer)
      File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1104, in obtain
        return installer(requirement)
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 380, in fetch_build_egg
        return cmd.easy_install(req)
      File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 651, in easy_install
        not self.always_copy, self.local_index
      File "/usr/lib/python2.7/dist-packages/setuptools/package_index.py", line 615, in fetch_distribution
        return dist.clone(location=self.download(dist.location, tmpdir))
      File "/usr/lib/python2.7/dist-packages/setuptools/package_index.py", line 531, in download
        found = self._download_url(scheme.group(1), spec, tmpdir)
      File "/usr/lib/python2.7/dist-packages/setuptools/package_index.py", line 772, in _download_url
        return self._attempt_download(url, filename)
      File "/usr/lib/python2.7/dist-packages/setuptools/package_index.py", line 778, in _attempt_download
        headers = self._download_to(url, filename)
      File "/usr/lib/python2.7/dist-packages/setuptools/package_index.py", line 678, in _download_to
        fp = self.open_url(strip_fragment(url))
      File "/usr/lib/python2.7/dist-packages/setuptools/package_index.py", line 728, in open_url
        % (url, v.reason))
    distutils.errors.DistutilsError: Download error for https://pypi.python.org/packages/58/a5/0dc93c3ec33f4e281849523a5a913fa1eea9a3068acfa754d44d88107a44/nose-1.3.7.tar.gz#md5=4d3ad0ff07b61373d2cefc89c5d0b20b: [Errno 104] Connection reset by peer
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-58YnVD/xxhash/

**Comment by hack3rjack** [comment]
Not sure if the admins would agree with all of this, but since the error you are having is most likely caused by a dependency issue or by incompatibility, try to upgrade to Python 2.7.10-2.7.12 and then rerun through the setup with a fresh pull of the repository: 

(FROM EXPLORER) 
  \Tools\Easy Setup\setup.bat
(FROM GIT/CMD)
  cd  C:\[PATHTOPOKEMONGOMAP]
  pip install -r requirements.txt
  npm install -g grunt-cli
  npm install
  npm run-script build
  
Warnings on version don't seem to matter, but running these from cmd will make them go away:  
  npm update -g minimatch@3.0.2
  npm update -g graceful-fs@^4.0.0
  npm update -g node-gyp@3.4.0

**Comment by NoMotion** [comment]
`[Errno 104] Connection reset by peer` this is an Internet connection issue. Try again

**Comment by BaIthamel** [comment]
This is not a support forum; please see [the discord #help channel](https://discord.gg/npVqkUn) for assistance.

**Comment by beeb** [comment]
I'm on Python 2.7.12, the install is fresh and I checked again my dependencies. Pip installed everything without error, except `six` that I had to remove from the requirements because it's already installed by Apple, and when pip tries to uninstall it, it fails (because of SIP, see https://github.com/pypa/pip/issues/3165 ). But six is installed, I can `import` it without issue from python, so all dependencies should be met.

@krisztianhadi your issue is unrelated, please make your own issue or go to the discord channel

@BaIthamel as far as I'm concerned this could well be an issue with PokemonGo-Map
