### ISSUE TITLE
[Bug] Cannot display pokemon popup

### ISSUE THREAD

**Issue by Slivo-fr** [PokemonGoMap/PokemonGo-Map#338]
Sometime on chrome mobile, clicking on pokemon does not display the popup.

## Expected Behavior
Clicking on the pokemon should display the popup

## Current Behavior
Sometime, on a specific pokemon, on chrome mobile, popup don't show.
A darker square is shown while I click on the pokemon, and the popup does not show up.
Refreshing the page does not solve the problem, and the popup still won't pop up !

## Steps to Reproduce (for bugs)
1.display map on mobile
2.Check pokemon
3.Background chrome to use the app
4.Come back to check map
5.repeat.

## Your Environment
Using a debian hosted map, on chrome mobile latest version.

## Context
Might happens when the same pokemon spawn in the same location multiple times in a row.

**Comment by NoMotion** [comment]
Is there an issue with Chrome on desktop?

**Comment by Slivo-fr** [comment]
Nope,  it often (always)  happens when chrome was in the background for some time. And allais on the pokemon I want to check, maybe the first I try to click

**Comment by Slivo-fr** [comment]
Important point I forgot, adding it to the original thread : the problem is still there if I refresh the webpage !

**Comment by desource90** [comment]
Does this bug only occur for pokemon you've included on your notify list?

**Comment by Slivo-fr** [comment]
Might be the case yeah, didn't think about it

**Comment by tkSimon** [comment]
Probably related to #418

**Comment by Studio-XP** [comment]
Yes, currently notifications break the page on Chrome for Android.

**Comment by beccasafan** [comment]
Caused by #418. Closing in favor of leaving that one open.
