### ISSUE TITLE
Is there a guide on running multiple accounts to increase scan area/speed?

### ISSUE THREAD

**Issue by dudeman999** [PokemonGoMap/PokemonGo-Map#340]
I'm running this through windows 10.

Ive set up this scanner and mchristophers desktop scanner. Currently, I've opened about 20 windows with separate accounts using the desktop scanner app trying to cover a wide radius around my home, but I've found it will never be useful for mobile scanning when out around town.

Using this Scanning map, is there a way that everyone is using to run multiple accounts on one screen? I've checked the wiki and there is no mention of how to do so. Is there a user friendly step by step on how to achieve this?

**Comment by Crazy-Clown** [comment]
You're probably best to ask in the Pokemon Go Dev Reddit:  https://www.reddit.com/r/pokemongodev

**Comment by joostsijm** [comment]
You are problebly looking for this. There is a text file explaing how it works: https://github.com/PokemonGoMap/PokemonGo-Map/tree/develop/Tools/Hex-Beehive-Generator

Again, the issue tracker is not for support request

**Comment by lmjustic** [comment]
```
python runserver.py -a ptc -u NAME1 -u NAME2 -u NAME3 -u NAME4 -u NAME5 -p PASS1 -p PASS2 -p PASS3 -p PASS4 -p PASS5 -H 0.0.0.0 -P 5000 -ld 1 -l "LOCATION" -st 12
```
I believe something like this is what you are looking for.
