### ISSUE TITLE
Deployment to Scalingo Failing

### ISSUE THREAD

**Issue by matiszac** [PokemonGoMap/PokemonGo-Map#342]
# Deployment to Scalingo Failing.

## Expected Behavior

Successful deployment to scalingo.

## Current Behavior

npm install and npm run build is required to be run before the application could be started on scalingo

OUTPUT:
2016-08-09 18:48:19,868 [      MainThread][     runserver][CRITICAL] Missing front-end assets (static/dist) -- please run "npm install && npm run build" before starting the server

## Possible Solution

It seems the 'scalingo.json' file is out of date.
Update the manifest file.

## Steps to Reproduce (for bugs)

Try to deploy to scalingo.

## Your Environment

scalingo.io

**Comment by BaIthamel** [comment]
This is not a support forum; please see [the discord #help channel](https://discord.gg/npVqkUn) for assistance.
