### ISSUE TITLE
No Pokemons find after 2 Hours

### ISSUE THREAD

**Issue by PegasusExe** [PokemonGoMap/PokemonGo-Map#345]
No Pokemons find after 2 Hours

## Expected Behavior
Find Pokemons or stops or Gyms

## Current Behavior
Task doesn't find any Pokemons or stops or Gyms after ~ 2 Hours
I already tried -st 8 -sd 2 and -st 3 -sd 6 and -st 3 -sd 15...
And i tried 3 tasks with every task 5 accs and other ports.
![issue](https://cloud.githubusercontent.com/assets/19635059/17533241/31b5d2d0-5e84-11e6-8090-b36f0a7bd545.PNG)

## Possible Solution
Don't know

## Steps to Reproduce (for bugs)
All Datas got changed so that are not my data...
1. Install map on Ubuntu Server
2. start with this map:
screen -dmS map1

screen -r -S map1
source pokemon/bin/activate
python runserver.py -u acc10 -u acc11 -u acc12 -u acc13 -u acc14 -u acc0 -u acc1 -u acc2 -u acc3 -u acc4 -u acc5 -u acc6 -u acc7 -u acc8 -u acc9 -p pwforall -st 8 -sd 2 -k google_api_key  -l "0.0000 0.0000" -H 0.0.0.0 -P 5000

[CTRL] + A [CTRL] + D to detach

3. Wait some time and then it says in every COnsole that he find 0 Pokemons or Stops or Gyms

## Context
restart every 10 min the map via script and wait 5 min and then start it again

## Your Environment
Version used: 2.2.0 and tryed Develope from git
Environment name and version (e.g. Python 2.7): Python 2.7
Operating System and version (desktop or mobile): Server Ubuntu

**Comment by schristmann** [comment]
anything less then -sd 10 is going to give you trouble these days.

**Comment by PegasusExe** [comment]
Sry forgot i tried -sd 15 too edites first post

**Comment by brettgus** [comment]
Maybe let it cool off and try -sd 10 in a while?
