### ISSUE TITLE
[Bug] search_control 500

### ISSUE THREAD

**Issue by vinsilsim** [PokemonGoMap/PokemonGo-Map#348]
## Current Behavior

chrome debug show this error:

search_control 500 (INTERNAL SERVER ERROR)send @ jquery.min.js:4ajax @ jquery.min.js:4r.(anonymous function) @ jquery.min.js:4getJSON @ jquery.min.js:4updateSearchStatus @ map.min.js:5
jquery-migrate.min.js?ver=1.4.1:1 JQMIGRATE: Migrate is installed, version 1.4.1

http://prnt.sc/c3p35v

**Comment by invisiblek** [comment]
need a server log, but this is working fine for me.....

**Comment by Xcelled** [comment]
Mine does the same thing, and also for raw requests. It seems to happen randomly. I did, however, notice this only when trying to access the server through my remote IP. If I use my local IP, this doesn't show up. Also, remote IP seems to load a lot slower than local.

![image](https://cloud.githubusercontent.com/assets/5599341/17535630/d51ebfd0-5e5d-11e6-9737-2527d139e355.png)

**Comment by vinsilsim** [comment]
@Xcelled same here!

**Comment by Xcelled** [comment]
This is still only happening when I use my external IP. It's throwing timeout errors:

>jquery.min.js:4 GET http://xxx.xxx.xxx.xxx:5000/search_control net::ERR_CONNECTION_TIMED_OUT

**Comment by Xcelled** [comment]
Not seeing this _at all_ on local IP. Wondering if it could be a router thing. @vinsilsim what router do you have?

**Comment by Xcelled** [comment]
Now I'm seeing it locally too, but much more infrequently.
