### ISSUE TITLE
Setup?

### ISSUE THREAD

**Issue by Matsu16** [PokemonGoMap/PokemonGo-Map#350]
I created alot of ptc accounts 200+ i dont want to use beehive. Just want to run one big circle in my town. -st 30. I thought making alot of accounts would make it fast, but it seems its not running faster now. 

Whats the best setup to run this. Am i missing commands in my script?. 

Running on windows 10 on my localhost:500

**Comment by BaIthamel** [comment]
This is not a support forum; please see [the discord #help channel](https://discord.gg/npVqkUn) for assistance.
