### ISSUE TITLE
error during installation of requirements.txt - pogoapi

### ISSUE THREAD

**Issue by twistednipple** [PokemonGoMap/PokemonGo-Map#352]
during installation of requirements.txt i get this error at last line:

 Cloning https://github.com/keyphact/pgoapi.git (to b4bf0e089dfe09903f8dda37dae56910e01f94cc) to c:\users\zalman2\appdata\local\temp\pip-build-gsc6o9\pgoapi
  Error [Error 2] The system cannot find the file specified while executing command git clone -q https://github.com/keyphact/pgoapi.git c:\users\zalman2\appdata\local\temp\pip-build-gsc6o9\pgoapi
Cannot find command 'git'

**Comment by NoMotion** [comment]
Install git

**Comment by paraloxy** [comment]
https://git-for-windows.github.io/

Install from there :)

**Comment by twistednipple** [comment]
thank you, that is done and it does not error at this stage anymore, however now it still produces other errors - 
 Failed building wheel for PyYAML 
 Failed building wheel for xxhash

p.s. can someone update wiki with git nwo being a mandatory requirement (it was working fine on pre new api versions of maps without git)

**Comment by jerkball** [comment]
Removing whole directory (copying configs to a syfe place before) and reclone the git repository worked here....
Had the same issue by changing git fetch url from old to new repository...

**Comment by BaIthamel** [comment]
This is not a support forum; please see [the discord #help channel](https://discord.gg/npVqkUn) for assistance.
