### ISSUE TITLE
MySQL Issues

### ISSUE THREAD

**Issue by DeviantEng** [PokemonGoMap/PokemonGo-Map#354]
I know we're all aware that MySQL isn't 100% perfect with the current develop build.  I'm running a dedicated web server (frontend), with 6 servers running scan activity for a largish region (~250 users).  In total I probably have ~75 search commands, using a total of ~750-1000 ptc users.

I'm finding that I have to restart my mariadb instance every so often to make sure things are working.  The biggest problem is mysql connections aren't closing cleanly, or closing at all.

For example,
`select * from information_schema.processlist where command = 'Sleep';`
Shows 831 processes in the Sleep state.

`select * from information_schema.processlist where command != 'Sleep';`
Shows 64 processes NOT in the Sleep state.

That means I have 895 current mysql processes, where 831 of those are `Sleep` processes.  This is causing database locking issues.

My mariadb process has been up for 5h 53m, and my oldest `Sleep` process has a process id of `183` and a `TIME_MS` of `19039266.023`, which is about 5h 18m.

At this point scanning has basically stopped (~5-6 hours in).  Restarting mariadb, but not my scanners, seems to make things happy again...for what I assume is only going to be another 4-6 hours.  Even though I just restarted mariadb, I am still getting a few messages like this on my scanners:
`[ WARNING] (1213, u'Deadlock found when trying to get lock; try restarting transaction')... Retrying`

Until a fix, I am using a cron task to restart my db every 3 hours.

**Comment by BaIthamel** [comment]
if you have 750-1000 accounts i would expect to see a similar number of connections.

**Comment by DeviantEng** [comment]
Why did you close this issue, @BaIthamel?  There should not be 750-1000 active processes on the database at all times, nor should there be a Sleep process that's been running for 5h+.  Once a process is finished, it should close from the app side and that doesn't appear to be happening.

Regardless, I am having database lock issues that are killing the scans until I restart stuff.
