### ISSUE TITLE
Move away from Landscape.io

### ISSUE THREAD

**Issue by Chlodochar** [PokemonGoMap/PokemonGo-Map#356]
Landscape.io is flaky. Now that flake8 configuration is in the repo and develop doesn't contain any linting issues anymore, I think it's time to move to another linting method for PRs.

We can run flake8 inside Travis. That outputs the issues with the file and line number, not the context of the issues.

SideCI can run the linter and comments the issues on Github itself in the changed files. It will result in an easy to read list of open issues. It also works for both eslint and flake8, so it lints Python as well as Javascript. See here for an example with an old PR that was based on code full of already existing issues: https://github.com/Chlodochar/PokemonGo-Map/pull/1

I suggest to disable Landscape.io, give SideCI a try, if it works it works. If it doesn't move linting to Travis.

## Current Behavior

Flaky Landscape.io.

**Comment by Chlodochar** [comment]
I do not have the option to enable SideCI for PokemonGoMap, so someone else should take a look at that.

**Comment by FrostTheFox** [comment]
landscape has been ded for a little while so closing
