### ISSUE TITLE
Not all pokemon get removed when you turn off "Pokemon"

### ISSUE THREAD

**Issue by TheMaskedMonkey** [PokemonGoMap/PokemonGo-Map#358]
Pressing "Pokemon" on the options to turn them off only removes a couple of Pokemon

## Expected Behavior
The map is supposed to remove all pokemon.

## Current Behavior
It will only remove around half.

## Possible Solution
I'm not sure the cause of this so I can not provide a solution.

## Steps to Reproduce (for bugs)
1. Go to https://pokemap.eptic.me/
2. Press options
3. Disable Pokemon
4. ???
5. Profit

## Your Environment
* Version used: Latest git pull
* Environment name and version (e.g. Python 2.7): Python 2.7. Beehive kind of setup. Default sqlite DB

**Comment by BaIthamel** [comment]
That's really odd. +1 as a real issue i think

**Comment by TheMaskedMonkey** [comment]
Could it be down to the amount of pokemon I'm possibly finding? I mean, there's A LOT in NYC.

**Comment by thesandvichisaliar** [comment]
It's just like a billion lured pokestops. I'm jealous. Pokemon info from lures is tied to pokestops, though I agree I would expect these pokemon to be removed from the map as well.

**Comment by MisterJokerS** [comment]
How did you do to make several different scan at the same time ?

**Comment by darkelement1987** [comment]
I guess multiple instances with fixed locations using the same db.
