### ISSUE TITLE
List of startup flags missing from io wiki

### ISSUE THREAD

**Issue by maaim** [PokemonGoMap/PokemonGo-Map#360]
## Expected Behavior
Re-add list of startup flags to wiki

## Current Behavior
No listing

## Possible Solution
re-add

## Steps to Reproduce (for bugs)
1. na
2.
3.
4.

## Context
makes me feel kind of icky.  I'm lost without my list...

## Your Environment
Win10
* Version used: dev
* Environment name and version (e.g. Python 2.7):
* Operating System and version (desktop or mobile):

**Comment by chuyskywalker** [comment]
`python runserver.py -h`

**Comment by maaim** [comment]
Thank you
