### ISSUE TITLE
pgoapi - Cannot find command 'git' while doing pip install -r requirements.txt

### ISSUE THREAD

**Issue by Keyvandabar** [PokemonGoMap/PokemonGo-Map#361]
C:\Users\Administrator\Downloads\PokemonGo-Map-develop>pip install -r requirements.txt
Collecting six==1.10.0 (from -r requirements.txt (line 1))
  Using cached six-1.10.0-py2.py3-none-any.whl
Collecting Flask==0.11.1 (from -r requirements.txt (line 2))
  Using cached Flask-0.11.1-py2.py3-none-any.whl
Collecting Jinja2==2.8 (from -r requirements.txt (line 3))
  Using cached Jinja2-2.8-py2.py3-none-any.whl
Collecting MarkupSafe==0.23 (from -r requirements.txt (line 4))
Collecting Werkzeug==0.11.10 (from -r requirements.txt (line 5))
  Using cached Werkzeug-0.11.10-py2.py3-none-any.whl
Collecting configargparse==0.10.0 (from -r requirements.txt (line 6))
Collecting click==6.6 (from -r requirements.txt (line 7))
Collecting itsdangerous==0.24 (from -r requirements.txt (line 8))
Collecting peewee==2.8.1 (from -r requirements.txt (line 9))
Collecting wsgiref==0.1.2 (from -r requirements.txt (line 10))
Collecting geopy==1.11.0 (from -r requirements.txt (line 11))
  Using cached geopy-1.11.0-py2.py3-none-any.whl
Collecting s2sphere==0.2.4 (from -r requirements.txt (line 12))
  Using cached s2sphere-0.2.4-py2.py3-none-any.whl
Collecting gpsoauth==0.3.0 (from -r requirements.txt (line 13))
Collecting PyMySQL==0.7.5 (from -r requirements.txt (line 14))
  Using cached PyMySQL-0.7.5-py2.py3-none-any.whl
Collecting flask-cors==2.1.2 (from -r requirements.txt (line 15))
Collecting flask-compress==1.3.0 (from -r requirements.txt (line 16))
Collecting LatLon==1.0.1 (from -r requirements.txt (line 17))
  Using cached LatLon-1.0.1-py2-none-any.whl
Collecting pgoapi from git+https://github.com/keyphact/pgoapi.git@b4bf0e089dfe09903f8dda37dae56910e01f94cc#egg=pgoapi (from -r requirements.txt (line 18))
  Cloning https://github.com/keyphact/pgoapi.git (to b4bf0e089dfe09903f8dda37dae56910e01f94cc) to c:\users\admini~1\appdata\local\temp\pip-build-1q_fkw\pgoapi
  Error [Error 2] The system cannot find the file specified while executing command git clone -q https://github.com/keyphact/pgoapi.git c:\users\admini~1\appdata\local\temp\pip-build-1q_fkw\pgoapi
Cannot find command 'git'

The above wall of text is what I receive when I try to: pip install -r requirements.txt
I have done this: pip uninstall -r requirements.txt
Then reinstalled - Same issue
I have deleted any old folders that may conflict.
Please help,
Keyvan

**Comment by marcmicalizzi** [comment]
You need to have git installed and in the PATH variable.

**Comment by Keyvandabar** [comment]
How does one do this? @marcmicalizzi

**Comment by Keyvandabar** [comment]
Solved with https://www.youtube.com/watch?v=2ACJHCNZ3ow
