### ISSUE TITLE
It seems `pgoapi` is not installed. You must run pip install -r requirements.txt again

### ISSUE THREAD

**Issue by swaggaswag** [PokemonGoMap/PokemonGo-Map#365]
Hi,

I downloaded the latest release today and installed using the basic installation guide here: https://pgm.readthedocs.io/en/develop/basic-install/index.html

OS: OSX El Capitan

Followed all the steps installed homebrew, then the tools needed, after getting the error also tried to upgrade using "pip install --upgrade pip setuptools" - didn't work.

Any suggestions?

Thanks in advanced.

EDIT:
Tried some of the solution suggested here https://github.com/PokemonGoMap/PokemonGo-Map/issues/124 by uninstalling & reinstalling prodobuf and then requirements then reinstalling it, got the errors below:

Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/site-packages/pip/commands/install.py", line 317, in run
    prefix=options.prefix_path,
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_set.py", line 736, in install
    requirement.uninstall(auto_confirm=True)
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_install.py", line 742, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_uninstall.py", line 115, in remove
    renames(path, new_path)
  File "/usr/local/lib/python2.7/site-packages/pip/utils/__init__.py", line 267, in renames
    shutil.move(old, new)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 300, in move
    rmtree(src)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 252, in rmtree
    onerror(os.remove, fullname, sys.exc_info())
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 250, in rmtree
    os.remove(fullname)
OSError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/site-packages/pgoapi-1.1.6-py2.7.egg-info/dependency_links.txt'

**Comment by SethG911** [comment]
Install https://www.microsoft.com/en-us/download/details.aspx?id=48145

**Comment by swaggaswag** [comment]
On OSX?

**Comment by SethG911** [comment]
Hehe, sorry missed that crucial part of your message. I had this issue before on windows and just assumed you were having the same issue.

**Comment by swaggaswag** [comment]
Thought i'm missing something myself lol.. thanks anyway :)

**Comment by methoman** [comment]
Usually you get this error if you try to do the installation as a non-privileged user.
Are you admin/root when running this command?

**Comment by swaggaswag** [comment]
Yes i noticed the last one saying "Permission Denied", don't know why and how to check that, but i think that has nothing to do with the primary issue of the server unable to find 'pgoapi'.

At any case, can i somehow make sure i'm admin when running the command or that 'admin' will have the permissions needed? kinda' newbie with this

**Comment by joacimd** [comment]
I had the same issue yesterday. Have you used an older version of PokemonGo-Map before?

Try `pip show pgoapi`. If "Location" is showing an old project, just delete that folder and run `sudo -H pip install -r requirements.txt` again in your new project location.

**Comment by swaggaswag** [comment]
Nope, never used another one that's a first ;(
No one seems to have the solution yet

**Comment by joacimd** [comment]
use 'sudo -H' when installing the requirements. I.e `sudo -H pip install -r requirements.txt`. This will give you root/admin rights.

**Comment by swaggaswag** [comment]
Just did it again, still doesn't seem to find pgoapi ..

I'm thinking something though; does everything has to be in the same directory ?
My 'pgoapi' is in: /usr/local/lib/python2.7/site-packages
My PGmap release directory is on my desktop, which is where i install/run requirements.txt .

Should i move site-packages to the pgmap release directory or vice-versa then retry ?

**Comment by EdenGottlieb** [comment]
pgoapi is installed just like any other pip pacakage to your python directory. It doesn't like to be in the project folder

**Comment by swaggaswag** [comment]
Right, thanks.. so no solution i guess

**Comment by ps-gunkie** [comment]
I had the exact same issue yesterday. The thing that ended up working for me was to uninstall Python, remove everything left over in the install folder, reinstall Python and reinstalling the requirements.txt entries.

**Comment by brianjob** [comment]
are you running python through nohup?

Try running without
