### ISSUE TITLE
Pokemon Scan Going Very Slooooooow

### ISSUE THREAD

**Issue by prophezzy** [PokemonGoMap/PokemonGo-Map#369]
The version before this when we didnt need a google maps key my scans would go very fast and as well as covering a vaster surface area now it is going slow. Im not sure if this is normal for everyone I am using the developers version I downloaded this version of Node.js Current version: v6.3.1 (includes npm 3.10.3). And this is what im typing in terminal (Im using * just to block some of my info). Is there anything i should add or exclude to make the searches go faster? the screenshot is how much pokes i found in like 15-20minutes before in 20 minutes i would have a much bigger surface area scanned

python ./runserver.py -a google -u swag*****@gmail.com -p ******** -k AIzaSyCtkyvL******tynRjfcbRHwBp4 -l "2*****052 -80.3****48"

![screen shot 2016-08-09 at 8 02 11 pm](https://cloud.githubusercontent.com/assets/11812311/17537638/5752fbac-5e6c-11e6-97dc-58a9ffd03adc.png)

**Comment by aldarund** [comment]
Api delay is 10sec. You cant scan faster than once in 10 sec with one account. Only adding more account will make it faster

**Comment by prophezzy** [comment]
how can i add more accounts?

**Comment by imynwulf** [comment]
Add -u and -p multiple times and specify different accounts each time.

Remember that issues are not for support. Get support on discord or from reddit.
