### ISSUE TITLE
Duplicate pokemon spawn bug?

### ISSUE THREAD

**Issue by aldarund** [PokemonGoMap/PokemonGo-Map#375]
Not really sure if it a map bug or something from niantic api.
Have this situation several times .
Rare pokemon spawns at a place like Nidokings, Gengar, etc. I go catch him.   ~10 minutes later at the exact same place map show that this pokemon spawns again. Im going there again and there indeed pokemon, but not the one that map shows, but a usual one like drowzee etc.

**Comment by Viper2k4** [comment]
I can approve this. Yesterday a Gyarados spawned. And like @aldarund said 10min later it spawned again at the same position with new despawn-timer and so on. But he does not spawn.

**Comment by myrdyr** [comment]
There exists double-spawns like this. A Pokemon will spawn for 15 minutes, disappear for 15 minutes, then come back again for 15 minutes. The next cycle will have a new Pokemon. Both of the spawns will have the exact same encounter_id, so if you caught it or had it run from you, then it will not show up again for you.

**Comment by filippounitn** [comment]
If you caught it the 1st time you cannot catch it the 2nd time. Anyway if some1 didn't catch it the 1st time, he can catch it the second time.
Not a bug, just the same pokemon disappearing then respawning.
Happened to me with a snorlax. Caught the 1st time, then the 2nd time didn't pop up for me but a friend of mine managed to catch it :dancers:

**Comment by springjools** [comment]
I also experienced this and I caught the first pokemon, and then the second one never appeared. I don't think we can filter out spawns like these, nor is it probably desired.

**Comment by BaIthamel** [comment]
This is not a support forum; please see [the discord #help channel](https://discord.gg/npVqkUn) for assistance.

**Comment by aldarund** [comment]
@Balthamel it wssnt a support request. It was report for possible bug, because this behaviour cant be caused by api results or by incorrect logic in processing api results where wrong pokemon inserted. So your remark about help channel not in place imo.
