### ISSUE TITLE
JSLine Semi Colons

### ISSUE THREAD

**Issue by chuyskywalker** [PokemonGoMap/PokemonGo-Map#378]
Quick Stupid Vote, react with your choice

http://eslint.org/docs/rules/semi
```
  "rules": {
    "semi": 0
  }
```

:confused: Leave as is, allow mixed semi-colons
:-1: Disallow semi-colons
:+1: Enforce semi-colons

**Comment by Chlodochar** [comment]
Oops, that should've been already removed. So I guess :-1:. I'd like to follow a fully documented style guide, no individual rules in eslintrc. This makes documenting the style much easier as well:

> We're using StandardJS

Instead of:

> We're using StandardJS, except for the semicolons, those should be added.

**Comment by chuyskywalker** [comment]
Huh, so the logic, basically, goes "you're stuck with ASI forever, so suck it up butter cup and learn it cause you're not about to start writing JS code with *no line breaks*." Which makes a certain amount of sense.

I'll turn on the "disallowed enforcement".

**Comment by Chlodochar** [comment]
Just to clarify, I'm for removing the `"rules": { ... }` part, so that it fully inherits StandardJS as its ruleset. The StandardJS ruleset has it set to disallow semi-colons: https://github.com/feross/eslint-config-standard/blob/master/eslintrc.json#L130 http://eslint.org/docs/rules/semi#never

**Comment by chuyskywalker** [comment]
Fine by me; go a head and do so.
