### ISSUE TITLE
Add pokestop/gym info to popup

### ISSUE THREAD

**Issue by CoolCanuck** [PokemonGoMap/PokemonGo-Map#380]
would be great if the Pokestop info (place name) could be (optionally) added to the info popup.

**Comment by schwtyl** [comment]
It'd also be great to be able to list the usernames & levels! ...then it'd be possible to show a local leaderboard ^_^

**Comment by Yossi** [comment]
pictures and descriptions too.

**Comment by CoolCanuck** [comment]
Important: if someone is creating a feature to include photos, PLEASE rewrite photo URL's to httpS://. Otherwise, any map server over https can't load images. http versions of the map can load https without issue. BUT not https loading http. Thanks very much.

**Comment by Yossi** [comment]
You can just do ://<url here> and it will use whatever protocol it was loaded on

**Comment by BaIthamel** [comment]
For feature requests please migrate this to the new feature page
http://feathub.com/PokemonGoMap/PokemonGo-Map/
Thankyou!

**Comment by CoolCanuck** [comment]
Yossi it's // not :// :)

**Comment by prusswan** [comment]
Pokestop details require a separate request and will slow down the workers. However, a link and endpoint can be added to each pokestop info popup to fetch such information on demand only.

**Comment by CoolCanuck** [comment]
@BaIthamel This request needs to be opened again. FeatHub is no longer used. Good riddance.

**Comment by CoolCanuck** [comment]
@BaIthamel This request needs to be opened again. FeatHub is no longer used. Good riddance.
