### ISSUE TITLE
Using multiple accounts requires unnecessarily duplicated config values

### ISSUE THREAD

**Issue by Wirewraith** [PokemonGoMap/PokemonGo-Map#381]
## Expected Behavior
Prior to my pull this afternoon, I was able to omit the auth-service and password lists  in lieu of a single value that would be assumed to be the default value for all usernames passed in. This was A Neat Way of doing this. For example:
```
#auth-service:          # ptc (default) or google
username: [foo1, foo2, foo3, foo4, foo5, foo6, foo7, foo8, foo9, foo10]
password: foobar
```

## Current Behavior
Now, lists the same length as the usernames one is required, even if the values are all the same. For example:
```
auth-service: [ptc, ptc, ptc, ptc, ptc, ptc, ptc, ptc, ptc, ptc]
username: [foo1, foo2, foo3, foo4, foo5, foo6, foo7, foo8, foo9, foo10]
password: [foobar, foobar, foobar, foobar, foobar, foobar, foobar, foobar, foobar, foobar]
```

Edit: Somehow forgot to note down the error I got:
```
Traceback (most recent call last):
  File "runserver.py", line 47, in <module>
    from pogom.app import Pogom
  File "[snip]/pogom/app.py", line 17, in <module>
    from .models import Pokemon, Gym, Pokestop, ScannedLocation
  File "[snip]/pogom/models.py", line 18, in <module>
    from .customLog import printPokemon
  File "[snip]/pogom/customLog.py", line 5, in <module>
    args = get_args()
  File "[snip]/pogom/utils.py", line 181, in get_args
    args.accounts.append({'username': username, 'password': args.password[i], 'auth_service': args.auth_service[i]})
IndexError: list index out of range
```

## Possible Solution
Just change it back to how it was.

## Your Environment

* Version used: As-of commit: 74b630a
* Environment name and version: Python 2.7.9, pip 8.1.2, npm 3.10.3
* Operating System and version: Debian 8 (jessie)

**Comment by FrostTheFox** [comment]
Just downloaded latest version, put in mutliple usernames, and defined auth-service as PTC ONCE, and password as password ONCE, and it worked as intended. Cannot reproduce.

**Comment by Wirewraith** [comment]
Aaaaaand I just tried it like you said and it works (the difference is the single auth-service field). This is what I get for not thinking of all test cases. You may doth ignore this yonder moron.

**Comment by FrostTheFox** [comment]
:)
