### ISSUE TITLE
Make a different scan for different user connect on serveur map

### ISSUE THREAD

**Issue by MisterJokerS** [PokemonGoMap/PokemonGo-Map#384]
Hi!

All First, thank you for all is an exellent project!

I come to you , whether it is possible to make different scan depending on the user connect to the server ?
?
example, if I am connected with my phone and my computer , I see the scans done the other device.

and if I change position it stops the scan of the other.
 
thank you for helping me.

P.S.: Sorry, for my bad English..

**Comment by CoolCanuck** [comment]
Mod: please tag as [Feature Request]

**Comment by chuyskywalker** [comment]
No, this can't be done right now and we've specifically avoided multi-user features like this before.
