### ISSUE TITLE
No module named requests

### ISSUE THREAD

**Issue by Squirrel94** [PokemonGoMap/PokemonGo-Map#389]
After run the "runserver.py", I get these error message:

Traceback (most recent call last):
  File "./runserver.py", line 10, in <module>
    import requests
ImportError: No module named requests

Can anyone help me? thanks

**Comment by jaquer** [comment]
Have you performed `pip install -r requirements.txt`, as per the documention?

**Comment by Gitspree** [comment]
python runserver.py -a ptc -u user -p password -l "400 Broad St, Seattle, WA 98109, USA" -st 5 -h 0.0.0.0

also tryed with -k (api) and with number coords 45.421170, -75.6933830

Traceback (most recent call last):
File "runserver.py", line 15, in <module>
     from queue import queue
ImportError: No module named queue

Did run the pip install -r requirements.txt

Running wserver 2012 btw :)

and i followed the video: https://www.youtube.com/watch?v=2ACJHCNZ3ow

Hope you someone can help me :)

**Comment by Squirrel94** [comment]
For sure I install requirements. and here is result:
Successfully installed Flask-0.11.1 Jinja2-2.8 LatLon-1.0.1 MarkupSafe-0.23 PyMySQL-0.7.5 Werkzeug-0.11.10 click-6.6 configargparse-0.10.0 flask-compress-1.3.0 flask-cors-2.1.2 geopy-1.11.0 gpsoauth-0.3.0 itsdangerous-0.24 peewee-2.8.1 pgoapi-1.1.6 recommonmark-0.4.0 requests-2.10.0 s2sphere-0.2.4 six-1.10.0 sphinx-1.4.5 sphinx-autobuild-0.6.0 sphinx-rtd-theme-0.1.9 xxhash-0.6.1

 and then, still cannot get that output after runserver.py
