### ISSUE TITLE
pip install requirement error could not find a tag or a branch

### ISSUE THREAD

**Issue by MistSummer** [PokemonGoMap/PokemonGo-Map#391]
when run cmd at git bash
pip install -r requirements.txt
there are errors occur

Collecting pgoapi from git+https://github.com/keyphact/pgoapi.git@b4bf0e089dfe09903f8dda37dae56910e01f94cc#egg=pgoapi (from -r requirements.txt (line 18))
  Cloning https://github.com/keyphact/pgoapi.git (to b4bf0e089dfe09903f8dda37dae56910e01f94cc) to c:\users\admini~1\appdata\local\temp\3\pip-build-4jh4qd\pgoapi
  Could not find a tag or branch 'b4bf0e089dfe09903f8dda37dae56910e01f94cc', assuming commit.

 Could not find a tag or branch 'aa09ad861f104f987928fe9f5107ccfe0e4473c3', assuming commit.
  Running setup.py (path:c:\users\admini~1\appdata\local\temp\3\pip-build-4jh4qd\flask-cache-bust\setup.py) egg_info for package flask-cache-bust produced metadata for project name flask-cachebust. Fix your #egg=flask-cache-bust fragments.
Collecting future (from s2sphere==0.2.4->-r requirements.txt (line 12))
  Downloading future-0.15.2.tar.gz (1.6MB)
Collecting pycryptodomex>=3.0 (from gpsoauth==0.3.0->-r requirements.txt (line 13))
  Downloading pycryptodomex-3.4.2-cp27-cp27m-win32.whl (7.4MB)
Collecting pyproj (from LatLon==1.0.1->-r requirements.txt (line 17))
  Downloading pyproj-1.9.5.1.tar.gz (4.4MB)
    Complete output from command python setup.py egg_info:
    nad2bin.c
    nad2bin.c(129) : warning C4244: '=' : conversion from 'double' to 'float', possible loss of data
    nad2bin.c(130) : warning C4244: '=' : conversion from 'double' to 'float', possible loss of data
    nad2bin.c(137) : warning C4244: '=' : conversion from 'double' to 'float', possible loss of data
    nad2bin.c(138) : warning C4244: '=' : conversion from 'double' to 'float', possible loss of data
    nad2bin.c(352) : warning C4244: '=' : conversion from 'double' to 'float', possible loss of data
    nad2bin.c(353) : warning C4244: '=' : conversion from 'double' to 'float', possible loss of data
    pj_malloc.c
    using bundled proj4..
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\admini~1\appdata\local\temp\3\pip-build-4jh4qd\pyproj\setup.py", line 74, in <module>
        cc.link_executable(objects, execname, extra_postargs = [ '/MANIFEST' ] if os.name == 'nt' else  None)
      File "c:\python27\lib\distutils\ccompiler.py", line 700, in link_executable
        debug, extra_preargs, extra_postargs, None, target_lang)
      File "c:\python27\lib\distutils\msvc9compiler.py", line 669, in link
        raise LinkError(msg)
    distutils.errors.LinkError: command 'C:\\Users\\Administrator\\AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0\\WinSDK\\Bin\\mt.exe' failed with exit status -1073741819

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in c:\users\admini~1\appdata\local\temp\3\pip-build-4jh4qd\pyproj\
You are using pip version 8.1.1, however version 8.1.2 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

## Steps to Reproduce (for bugs)
pip install -r requirements.txt

**Comment by smithen85** [comment]
i have the same problem. Try millon things. Nothing seems to work

**Comment by schwtyl** [comment]
"Could not find a tag or branch ..., assuming commit" isn't an error, it's a warning/notice that it's pointing to a specific commit, rather than a tag or branch (EVERYBODY is getting this message, as it's expected behavior). Your problem lies elsewhere...

**Comment by chuyskywalker** [comment]
This is not a support forum; please see [the discord #help channel](https://discord.gg/npVqkUn) for assistance.

**Comment by cefasheli** [comment]
same error, no solution...
