### ISSUE TITLE
Bug: Webhook renders multiple workers useless

### ISSUE THREAD

**Issue by cheezy64** [PokemonGoMap/PokemonGo-Map#394]
## Expected Behavior

The latest develop branch creates a thread for each account.  Each account scans a cell.  If you have 10 accounts, 10 cells will scan simultaneously.  When you connect to a webhook, the behavior should be the same.
## Current Behavior

When connecting to a webhook, only one cell is scanned at a time.  At scan 1, worker_0 scans cell, and pushes to webhook.  At scan 2, worker_1 scans next cell, and pushes to webhook, etc.  For each scan, a single worker scans a single cell
## Possible Solution

Haven't looked at code, but possibly implement a thread-safe queue that all workers can queue pokemon findings into
## Steps to Reproduce (for bugs)

Install Pokealarm (https://github.com/kvangent/PokeAlarm)
Run Pokealarm with your choice of service on http://localhost:4000
runserver.py -u1 -u2 -u3 -p password -wh "http://localhost:4000"
Observe that only one cell scans at a time
## Context

Many people (myself included) prefer to be alerted of Pokemon rather than having to look at a map constantly.  Pogomaps works well on desktop with notifications, but this is not a suitable usecase for mobile clients
## Your Environment
- Version used: 7c45a1e 
- Develop branch
- Python 2.7.12 64-bit
- Windows 7 64-bit

**Comment by cheezy64** [comment]
Hmm, odd.  This morning I ran it again with the same arguments (without updating) and now it scans multiple cells at a time.  Yesterday, I tried multiple times and it did not.  So, the behavior is pretty inconsistent for whatever reason...

**Comment by Zooksey** [comment]
I may be wrong, but I think this is caused by the send_to_webhook method being called inside lock(). So, depending on latency, the call to the webhook can significantly reduce performance.

**Comment by martinsweitzer** [comment]
Don't use http://localhost:4000    use http://127.0.0.1:4000

I had the same issue.  I was on windows 10.  I tried turning off IPv6 also.    If you look up flask and localhost slow  on google you can find more on it.      

But changing to 127.0.0.1  fixed it being supremely slow

**Comment by j16sdiz** [comment]
`send_to_webhook` inside `parse_lock` is inefficient . 
Why do we need a lock for `parse_map` ?
Can we move the webhook to separate thread?

**Comment by sebastienvercammen** [comment]
No longer relevant: webhooks are on separate threads.
