### ISSUE TITLE
--clear-db not working with mysql

### ISSUE THREAD

**Issue by Infernoman** [PokemonGoMap/PokemonGo-Map#395]
## Expected Behavior
the database should be dropped and continue to start the server.

## Current Behavior
Hangs on clearing the database and doesnt start the webserver or clear the database.

## Steps to Reproduce (for bugs)
1. start the server with "-os --clear-db".

## Context
clear the database remotely and locally. neither are working currently

## Your Environment
ubuntu 14.04 trusty tahr
mysql

**Comment by Infernoman** [comment]
had this issue occur a few times now, I want to say this wasnt my environment but until i can test more i cant be sure, I had to restart the webserver a few times with --clear-db to get it to clear correctly

**Comment by invisiblek** [comment]
i've used this many times, haven't seen a problem with it

**Comment by Infernoman** [comment]
Seems to happen after running for a long time usually when the server loses connection to the mysql database while a lock is in place.

**Comment by grayblack** [comment]
You can make a cron job to truncate the database periodically. Alternatively (and probably better), use the mySQL event scheduler.
