### ISSUE TITLE
KeyError: 'map_cells'

### ISSUE THREAD

**Issue by raywhitehouse** [PokemonGoMap/PokemonGo-Map#402]
When I run python ./runserver.py, I'm getting a response that says 

search step x map parsing failed, retrying request in 40 seconds
File "/Users/whitehouse/PokemonGo-Map/pogom/search.py", line 245, in search_worker_thread
    parse_map(response_dict, step_location)
  File "/Users/whitehouse/PokemonGo-Map/pogom/models.py", line 299, in parse_map
    cells = map_dict['responses']['GET_MAP_OBJECTS']['map_cells']
KeyError: 'map_cells'

When I go to localhost:5000, no pokemon are showing up on the map. 

Any ideas?

![screen shot 2016-08-10 at 3 30 10 am](https://cloud.githubusercontent.com/assets/20944610/17547172/3e0b9bb0-5eab-11e6-8915-c9a7f5c0a6c0.jpg)

**Comment by cichacz** [comment]
Did you have it working before?

**Comment by raywhitehouse** [comment]
No. Just set it up.

**Comment by lungbubble** [comment]
#96

**Comment by raywhitehouse** [comment]
Thanks so much!

**Comment by Seestali** [comment]
I have the same problem, worked before

**Comment by raywhitehouse** [comment]
Check out @lungbubble's comment. Should solve it. Alternatively, if you log in to the account you just created and start a game, you should be good.
