### ISSUE TITLE
Missing modules while trying to run the map

### ISSUE THREAD

**Issue by janglin666** [PokemonGoMap/PokemonGo-Map#404]
Hello.
I followed [this tutorial](https://www.youtube.com/watch?v=2ACJHCNZ3ow), but when I tried to run the map with this command `

> python runserver.py -k api key -a ptc -u login -p password -l "coordinates" -st 5 

it said that   

>  File "runserver.py", line 10, in <module>
>     import requests
> ImportError: No module named requests

After this I tried to setup it all again and used Easy-Setup tool.
Now I get

> 
>   File "runserver.py", line 16, in <module>
>     from flask_cors import CORS
> ImportError: No module named flask_cors

Is there any solution? I see many people have the same issue.
pls send help

`

**Comment by W3BSTAR** [comment]
install the requirements again
then npm install again
and it should work

**Comment by SimplyArmin** [comment]
Its not an issue of PokemonGo-Map. its an issue because u did something wrong. So i would say it does not belong here.

**Comment by janglin666** [comment]
Can you explain to me what I did wrong? I followed the steps from wiki and from video tutorial, still won't work.

**Comment by imynwulf** [comment]
There are heaps of people that have this working. This is a support issue and doesn't belong here.

That being said, you need to install requirements, then do an npm install again.

**Comment by SimplyArmin** [comment]
1. Delete everything and start from new.
2. [Prerequirement](https://pgm.readthedocs.io/en/develop/basic-install/windows.html)  Step-by-Step
3. Open Git Bash ( If you dont have git go to Step 2 and DO Everything)
4. `git clone https://github.com/PokemonGoMap/PokemonGo-Map.git`
5. `pip install -r requirements.txt`
6. `npm install`
7. `npm run build`
8. `python ./runserver.py -a ptc -u 'USERNAME_HERE' -p 'PASSWORD_HERE' \
 -l 'a street address or lat/lng coords here' -st 3 -k 'maps key here'`
9. Done

I took everything fron the [wiki page](https://pgm.readthedocs.io/en/develop/basic-install/index.html) in less than 30 secs.

**Comment by chuyskywalker** [comment]
This is not a support forum; please see [the discord #help channel](https://discord.gg/npVqkUn) for assistance.
