### ISSUE TITLE
Problem with module flask_cache_bust

### ISSUE THREAD

**Issue by leetcat** [PokemonGoMap/PokemonGo-Map#408]
//Forgive me for bad english
1.
 I already installed this application and it worked fine for the past two days.
Today, I updated the application but it showed me an error when I tried to run `runserver.py`

> Traceback (most recent call last):
>   File "./runserver.py", line 17, in <module>
>     from flask_cache_bust import init_cache_busting
> ImportError: No module named flask_cache_bust
> 

2.
I tried to solve this issue by reinstalling the application again.
When I run this command `pip install -r requirements.txt` , it shows

>   Could not find a tag or branch 'aa09ad861f104f987928fe9f5107ccfe0e4473c3', ass
> uming commit.
>   Running setup.py (path:c:\users\leetca~1\appdata\local\temp\pip-build-la2z6a\f
> lask-cache-bust\setup.py) egg_info for package flask-cache-bust produced metadat
> a for project name flask-cachebust. Fix your #egg=flask-cache-bust fragments.
> 

3.
Then, I run the `runserver.py` again with no luck. The same error appeared.

> Traceback (most recent call last):
>   File "./runserver.py", line 17, in <module>
>     from flask_cache_bust import init_cache_busting
> ImportError: No module named flask_cache_bust
>

**Comment by TheOssi** [comment]
Run pip install -r requirements.txt

**Comment by timlinde** [comment]
I had to do this `pip install -r requirements.txt --ignore-installed`

**Comment by invisiblek** [comment]
https://github.com/PokemonGoMap/PokemonGo-Map/pull/400 merged

**Comment by leetcat** [comment]
1.
@timlinde I have the latest version of the project.The [#400](https://github.com/PokemonGoMap/PokemonGo-Map/pull/400) workaround solved my issue for this error message:-

> Running setup.py (path:c:\users\leetca~1\appdata\local\temp\pip-build-la2z6a\f
> lask-cache-bust\setup.py) egg_info for package flask-cache-bust produced metadat
> a for project name flask-cachebust. Fix your #egg=flask-cache-bust fragments.

Thank you @timlinde .

2.
However, the same python error appeared when I run the `runserver.py`.

> Traceback (most recent call last):
> File "./runserver.py", line 17, in 
> from flask_cache_bust import init_cache_busting
> ImportError: No module named flask_cache_bust

So, I decided to take a look and solved it myself by downloading and placing [flask_cache_bust](https://github.com/ChrisTM/Flask-CacheBust) folder into PokemonGo-Map folder.

**SOLVED!**

**Comment by lexcode** [comment]
Hi @leetcat, 

After I placed the flash_cache_bust I got other error.

Traceback (most recent call last):
  File "runserver.py", line 21, in <module>
    from pogom.app import Pogom
  File "/Users/SayMyName/PokemonGo-Map/pogom/app.py", line 9, in <module>
    from flask_compress import Compress
ImportError: No module named flask_compress

**Comment by FloteFuertes** [comment]
Hi, 
First of all my OS is windows, I just simply copy the requirements.txt to the python directory where pip resides mine is c:\python27\scripts  I paste it there and open a command prompt with the correct path to my python27\script and issue pip install -r requirements.txt. This works for me it installs everything. I have one issue when I run the runserver it looks for gmaps KEY. I'm clueless where I can get the KEY

**Comment by RocketRaccoon7** [comment]
@FloteFuertes you need to setup a google api key here: https://console.developers.google.com/

**Comment by mickeyboss123** [comment]
After I placed the flash_cache_bust folder into PokemongGo-Map I got another error.

Traceback (most recent call last):
  File "./runserver.py", line 22, in <module>
    from pogom.app import Pogom
  File "/root/PokemonGo-Map/pogom/app.py", line 17, in <module>
    from .models import Pokemon, Gym, Pokestop, ScannedLocation, MainWorker, WorkerStatus
  File "/root/PokemonGo-Map/pogom/models.py", line 19, in <module>
    from cachetools import TTLCache
ImportError: No module named cachetools

**Comment by vikkka** [comment]
@mickeyboss123 same error after placing the falsh_cache_bust folder into PokemongGo-Map

**Comment by hectorarreolaq** [comment]
I too get the error ImportError: No module named cachetools

Were you able to fix it?

**Comment by DavidStenstroem** [comment]
@hectorarreolaq To solve your problem, just go to terminal (if you're on Mac) and execute 'pip install cachetools'
