### ISSUE TITLE
Pokemon being upserted but not appearing on map

### ISSUE THREAD

**Issue by xdtrammell** [PokemonGoMap/PokemonGo-Map#409]
## Expected Behavior
The pokemon should be displayed on the map since it says they are being upserted.

## Current Behavior
The app will not display any of the pokemon on the map even though they can be found in the stats. [How the map appears.](http://i.imgur.com/htBZCKz.png) [Stats Page](http://i.imgur.com/PfSkdly.png)

## Possible Solution
I believe it is due to an error that is causing it to relogin over and over. [screenshot](http://i.imgur.com/tMYtpRG.png)

## Your Environment
Running app on Windows Server 2012
Hosted on virmach (I was able to create PTC Account)
Works fine on my home pc running Windows 10 with the same config.

**Comment by Kruptein** [comment]
This is possibly related to your local system time.  Can you see what `new Date();` returns in a javascript console in your browser?

**Comment by xdtrammell** [comment]
@Kruptein Wed Aug 10 2016 10:43:06 GMT-0700 (Pacific Daylight Time)

**Comment by Kruptein** [comment]
An other test: Do the scanned location circles appear ? (they are also time sensitive)
If you click on the All Locations for a certain pokemon, do they appear on the map ?

**Comment by Kruptein** [comment]
Yeah that clock is not correct, its 10:34:06 GMT+0000 right now.

This is related to my pull request #372

**Comment by Kruptein** [comment]
You could try the following although I cannot guarantee it will work as of now:

If you replace your static/js/map.js file with this one https://github.com/AchielC/PokemonGo-Map/blob/7687d72fd21e3a66ef9b09953e6de52568ba411e/static/js/map.js  (Keep the old file somewhere).
and rerun `grunt build`

does this fix it ?  If not, revert your file.

**Comment by xdtrammell** [comment]
@Kruptein All I did was change my clock to the right time and it worked instantly.
