### ISSUE TITLE
missing pokemon lure spawn

### ISSUE THREAD

**Issue by budiebudum** [PokemonGoMap/PokemonGo-Map#410]
Hello, 
I'm not a programmer, just user to this PokemonGO-Map,
I want to ask my experience using this map :

yesterday and days before : 

I can see pokemon spawn inside and some (kinda alot too I think ) outside scanned area,
This include normal spawn pokemon (14mins spawn) and lured pokestop spawn ( 3mins only ),
so I can see alot pokemons spawn in my map, inside + ouside area, normal + lured spawn.

but since today, 
I can see only pokemon inside my scanned area and I think all of them are normal spawn ( 14mins +)
The outside scan area and the lured spawn pokemon not showing anymore.

Are this only my map anomaly, or something change with the map?
*I used old version ( download august 9th) till today I experience some change,
then I think might be my outdated version, so I download the new (latest version), but still have problem like I wrote

*Sorry for bad english

Thank You
I hope someone can tell me / show me my map problem.

**Comment by Itnain** [comment]
#398 duplicate

**Comment by budiebudum** [comment]
ohh.. sorry for my stupidity :(,
just make this account to ask this and didn't know someone else already have the answer.
