### ISSUE TITLE
Scalingo deploy fails

### ISSUE THREAD

**Issue by rcoenen** [PokemonGoMap/PokemonGo-Map#411]
See below:

2016-08-10 11:03:49,886 [      MainThread]
[     runserver]
[CRITICAL] Missing front-end assets (static/dist) -- please run "npm install && npm run build" before starting the server

**Comment by Kruptein** [comment]
Did you do what the error message politely asked you ?

**Comment by Kruptein** [comment]
And a fix in a PR #405
