### ISSUE TITLE
Not possible scan multiuser

### ISSUE THREAD

**Issue by nicktan147** [PokemonGoMap/PokemonGo-Map#412]
I have the pokemon map running now... just that when i share it to my friends, it doesn't update one of us. Example:

User A search place A
User B search place B

So it will overwrite User A search and leave User A place not updated and continue to update User B's location. Anyway to solve this issue?

**Comment by iMagooo** [comment]
Multiple servers on different ports. Unfortunately the location aspect of this map is very rigid. Would be nice if you could POST new locations to the server from the client, like [https://github.com/favll/pogom](this map).

**Comment by imynwulf** [comment]
Issues are not for support. If you want a change made, fork the repo and make a PR.

**Comment by chuyskywalker** [comment]
We don't have multi-user support right now.
