### ISSUE TITLE
Full data is empty all of a sudden, when I have more than 7000 results from yesterday.

### ISSUE THREAD

**Issue by BradPat** [PokemonGoMap/PokemonGo-Map#413]
How can I get the full data page to show me the old data again? Switching to "Map Lifetime" does not work either. The data needs to be somewhere I think. Problem is that it is on Jelastic.

**Comment by Viper2k4** [comment]
https://github.com/PokemonGoMap/PokemonGo-Map/issues/397

?

**Comment by BradPat** [comment]
No, I have new pokemons being uploaded, I just cannot see the ones that have been scanned in the past days.

**Comment by SethG911** [comment]
What DB format are you using?

**Comment by BradPat** [comment]
I have used the DB-parameters in the command line to save the data to my own mysql db on my webspace. But the ones that were saved to the pogom.db before, are not shown in the full stats page now.

**Comment by scooterpsu** [comment]
You told it to use a different database, it's not going to read the old one...

**Comment by Bart274** [comment]
is it possible to import the old database somehow?
I used to run 5 servers with an individual database, now they use one combined database, but I was wondering if I could somehow import the previous 5 old databases as well

**Comment by chuyskywalker** [comment]
This is not a support forum; please see [the discord #help channel](https://discord.gg/npVqkUn) for assistance.
