### ISSUE TITLE
Saving locations and portable settings

### ISSUE THREAD

**Issue by Okloks** [PokemonGoMap/PokemonGo-Map#415]
1. That would be great if I could save some locations in DB and could quickly move beetween them without too long typing of address.

2. Need to transfer scanner settings between machines. Included/excluded pokemons, saved places (see above), and other settings. Is there possible way to do this?

**Comment by imynwulf** [comment]
Issues are not for support or feature requests. 
Make a PR with the changes you wish to see.

**Comment by MWin123** [comment]
@imynwulf Why do you comment almost every issue and tell people to make a PR? If someone has the time and knowledge to submit a PR, they would probably do that.

Also it says in the issue template: "If you're suggesting a change/improvement, tell us how it should work".

**Comment by JZ6** [comment]
planned feature

**Comment by BaIthamel** [comment]
For feature requests please migrate this to the new feature page
http://feathub.com/PokemonGoMap/PokemonGo-Map/
Thankyou!

**Comment by Okloks** [comment]
So, as you returned back to github, I open this request again.

**Comment by CoolCanuck** [comment]
@BaIthamel This request needs to be opened again. FeatHub is no longer used. Good riddance.
