### ISSUE TITLE
Problem with multiple workers

### ISSUE THREAD

**Issue by totoberg123** [PokemonGoMap/PokemonGo-Map#416]
Hello,

I try to create a region with multiple workers like the [image ](https://pgm.readthedocs.io/en/develop/_images/soznlqc.png)on the [wiki](https://pgm.readthedocs.io/en/develop/extras/workers.html).

I used the [Sheet ](http://goo.gl/X81fZq)from the wiki, and entered my long, lat and steps. When i start the scanners, there is blank space between the regions.. (used 2 regions for example)

See here: [my sheet](https://docs.google.com/spreadsheets/d/1pdTX7LHthW2Uqcy33YROmz0i8_CmI62KEbuqDgLBcw4/pub?gid=1601909872&single=true&output=pdf)
And: [the map](http://prntscr.com/c3yfur/direct)

**Comment by thomasmoors** [comment]
are the steps correct (`-st`)?

**Comment by imynwulf** [comment]
Issues are not for support. That doc page clearly says that it's still a work in progress.

**Comment by totoberg123** [comment]
@thomasmoors Im using (`-st 3`), its the same as in the sheet (3)

**Comment by ktravelet** [comment]
I'm in the same boat.  I tried -st 7 and its pretty far off.  A new sheet would be wonderful.

**Comment by BaIthamel** [comment]
This is not a support forum; please see [the discord #help channel](https://discord.gg/npVqkUn) for assistance.
