### ISSUE TITLE
Show all previously spawned pokemons on chosen spawn point.

### ISSUE THREAD

**Issue by Tuumi** [PokemonGoMap/PokemonGo-Map#417]
## Expected Behavior
Link/Button/whathaveyou on information pane to show all spawned pokemons on current spawn point

## Current Behavior
Currently after chosing pokemon's spawn locations to be shown at map from full stats. It does just that. When hovering over certain spawn point - it shows all chosen pokemons spawn times (and amount) in that selected location.

## Possible Solution
Adding here a link/button/configurable option/something to show all pokemons that have spawned in this location and their spawn times and not just the selected one.

## Context
We all love to catch that one pokemon, but as a curious being - We like to know more. And I personally would love to see what other pokemons spawns in the spot where majority of the time it's Pidgeys.

**Comment by Bart274** [comment]
I would also love this feature

**Comment by weshardee** [comment]
Additionally it would be nice to be able to see inactive spawn points and their expected spawn time and history.

**Comment by snapper67** [comment]
Something like this? ![screen shot 2016-08-11 at 11 08 16 am](https://cloud.githubusercontent.com/assets/7116542/17593473/fa1f44e2-5fb3-11e6-92a4-a099dfbeb520.jpg)

**Comment by Bart274** [comment]
that would be nice! :)
maybe in the info popup also put the last 5 times a pokemon has spawned there so users can guess when the next one should spawn there?

**Comment by khag7** [comment]
@snapper67 how'd you get that map?

**Comment by Tuumi** [comment]
@snapper67 -- well why not.. 

Any extra information from certain spawn point would be welcome :-)

**Comment by BaIthamel** [comment]
For feature requests please migrate this to the new feature page
http://feathub.com/PokemonGoMap/PokemonGo-Map/
Thankyou!

**Comment by CoolCanuck** [comment]
@BaIthamel This request needs to be opened again. FeatHub is no longer used. Good riddance.
