### ISSUE TITLE
No Pokemon on MAP

### ISSUE THREAD

**Issue by Ekz0r** [PokemonGoMap/PokemonGo-Map#423]
Hi there,

have someone now a solution for scanning pokemon again?
My map wont work atm. :/

Please help me

**Comment by aldarund** [comment]
issues are not for support. use discord

**Comment by Arthok** [comment]
First there is no support here.
And you could post more informations at least ...

**Comment by Ekz0r** [comment]
Where can i get Support ?

And The issue is 0 pokestops , 0 gyms and 0 Pokémon but i can Login so i dont have an ip ban i think

**Comment by CtrlAltDefeat94** [comment]
I dont think it's an issue on his side, many on discord are reporting that it's not working

**Comment by hoidaan** [comment]
@Ekz0r  https://discord.gg/uAmEkcu :)

**Comment by loki17** [comment]
I asked the same question 7 times on discord yesterday explaining the problem clearly. Not even single response. And this is definitely an issue. Even after doing everything the right way the map stops showing pokemon at some point without any errors.

**Comment by aldarund** [comment]
you have ip soft ban. Gz

**Comment by loki17** [comment]
I figured that 40 hours back and have been using ip rotation since then. Even after changing ip the map doesn't work  some times if it stops once (at least for me). Which makes me think that this is not only soft ip ban and this is also something related to the source code we are using.

**Comment by aldarund** [comment]
free tip -> wait for ip ban to lift off or use new ip and set sd to 12+.

**Comment by Ekz0r** [comment]
@hoidaan thank you :) but no one response to my bug

Thank you to all of you :)
