### ISSUE TITLE
Niantic starting to ban account using API illegally?

### ISSUE THREAD

**Issue by nicktan147** [PokemonGoMap/PokemonGo-Map#424]
The script was working all this long, all in a sudden I got this error message popping out:-

```
root@nickydev:~/PoGoMap# python runserver.py 
Traceback (most recent call last):
  File "runserver.py", line 99, in <module>
    position = util.get_pos_by_name(args.location)
  File "/usr/local/lib/python2.7/dist-packages/pgoapi/utilities.py", line 62, in get_pos_by_name
    loc = geolocator.geocode(location_name, timeout=10)
  File "/usr/local/lib/python2.7/dist-packages/geopy/geocoders/googlev3.py", line 217, in geocode
    self._call_geocoder(url, timeout=timeout), exactly_one
  File "/usr/local/lib/python2.7/dist-packages/geopy/geocoders/base.py", line 160, in _call_geocoder
    raise GeocoderServiceError(message)
geopy.exc.GeocoderServiceError: HTTP Error 500: Internal Server Error
```

Then I tried creating a new account afresh try again, it works for first time, then I terminate the python runserver script and rerun it back and I receive similar error. Is this softban or what?

**Comment by aldarund** [comment]
its not even niantic...its a error from google.

**Comment by nicktan147** [comment]
@aldarund It shouldn't be... It has been working fine all long, and as I mentioned, when I created a new account and tested, it works fine, but after re-run the script it became this error.

**Comment by aldarund** [comment]
its not even remotely connected to niantic. its a problem with decoding location you passed to google.

**Comment by nicktan147** [comment]
@aldarund Not sure why, it is working now. Thanks anyway
