### ISSUE TITLE
[FEATURE REQUEST] Telegram-API Integration

### ISSUE THREAD

**Issue by stappjno** [PokemonGoMap/PokemonGo-Map#427]
It would be nice to get Telegram-Notifications for nearby pokemons out of the DB. If you scan a City everyone could sign up for your bot and everyone can access your informations on one channel. If anyone else is interested in this, please let me know, i'm a webdev and could help with the production of this!

**Comment by NGPriest** [comment]
Use the webhook...?

**Comment by Wesleyl89** [comment]
https://github.com/kvangent/PokeAlarm

**Comment by stappjno** [comment]
@Wesleyl89 thx! That's what I was looking for!
