### ISSUE TITLE
No module named queue

### ISSUE THREAD

**Issue by Gitspree** [PokemonGoMap/PokemonGo-Map#433]
python runserver.py -a ptc -u user -p password -l "400 Broad St, Seattle, WA 98109, USA" -st 5 -h 0.0.0.0

also tryed with -k (api) and with number coords 45.421170, -75.6933830

Traceback (most recent call last):
File "runserver.py", line 15, in 
from queue import queue
ImportError: No module named queue

Did run the pip install -r requirements.txt

Running wserver 2012 btw :)

and i followed the video: https://www.youtube.com/watch?v=2ACJHCNZ3ow

Hope you someone can help me :)

**Comment by BaIthamel** [comment]
This is not a support forum; please see [the discord #help channel](https://discord.gg/npVqkUn) for assistance.
