### ISSUE TITLE
Updated to last version, using MySQL, no pokemons on the map

### ISSUE THREAD

**Issue by LIJE** [PokemonGoMap/PokemonGo-Map#434]
Hi,

Was working with early versions. I just updated pokegomap.

Command line: python runserver.py -u aaa -p aaa -st 12 -k AIzaSyCrjs6f51sdf7DNHxseqfTTE5YXZk -l "18.583453, 4.745959" -H 92.222.222.222 -P 80 -L fr -sd 1 -ns --db-name pokemongomapdb --db-user root --db-pass mypwd--db-host localhost

![Image](http://img4.hostingpics.net/pics/697267errr.jpg)

Something has changed?

I wasnt using sql earlier, it might be the problem?
Also, database is empty:

mysql> use pokemongomapdb
Database changed
mysql> show tables;
Empty set (0.00 sec)

is it normal?

**Comment by topher-au** [comment]
Scan delay is too fast, set it to -sd 10 minimum or you won't get any results.

**Comment by LIJE** [comment]
This is not an issue. Never had any problem with sd. Tried with 10, doesnt change anything.

Im running pokegomap or multiple servers. One of them is using the old map with sd 1 and its working well.

**Comment by LIJE** [comment]
Hm, anyway to know if the ip is banned?

**Comment by LIJE** [comment]
Soft ban ip I guess. Sd must too low.

**Comment by visusnet** [comment]
Same issue here. Stopped working half an hour ago. sd has always been set to 10.

**Comment by tccurkendall** [comment]
I am also getting this issue. About a half hour ago as well. -sd was 8 for me but had been working fine

**Comment by Akivas** [comment]
Same issue here, it worked like a charm yesterday, but no more pokemons.
The symptoms are the same as when Niantic put Unknown6 in use.

**Comment by tccurkendall** [comment]
I have a bot that is still working however so I do not believe this is the same issue as Unknown6

**Comment by MichalCerny** [comment]
https://github.com/PokemonGoMap/PokemonGo-Map/issues/397

**Comment by jorio2311** [comment]
hmm , my bots are still working

**Comment by LIJE** [comment]
masse wave of ban. mounted another server, working again.

**Comment by BaIthamel** [comment]
This is not a support forum; please see [the discord #help channel](https://discord.gg/npVqkUn) for assistance.
