### ISSUE TITLE
Feature request: Allow coordinates in URI

### ISSUE THREAD

**Issue by rjes** [PokemonGoMap/PokemonGo-Map#435]
Hi!

Another feature request from me, hope this isn't rejected :-)
I'm running 3 instances with one frontend server, two of the instances scan the same area (some offset in the coordinates) and one instance is scanning there I work.
I run the server with fixed-location and no-search-control so it would be nice to be able to jump to right coordinates by enter: server.tld/pokemon-map/#lat,lon

//Robert

**Comment by jorio2311** [comment]
I got a similiar setup and I modified the app.py in the pogom dir. Remove the content from the next_loc method, but dont remove `return "ok"` (IMPORTANT). Now Im enabled the search control and disabled the fixed location.

Now you can change the location via the UI without to change the fixed points from the frontend server

**Comment by CoolCanuck** [comment]
Shouldn't be an issue, but devs should test for XSS vulnerabilities. Doubt there will be any, but for the number of users, doesn't hurt ;)

**Comment by BaIthamel** [comment]
This is not a support forum; please see [the discord #help channel](https://discord.gg/npVqkUn) for assistance.

**Comment by CoolCanuck** [comment]
@BaIthamel  This needs to be reopened. He's not asking for support, it's a feature request, and they are permitted to do so.
