### ISSUE TITLE
Launching Issues-example.py file not found

### ISSUE THREAD

**Issue by whitedeuce22** [PokemonGoMap/PokemonGo-Map#437]
Trainers, 

When I imput the final command to launch (python example.py -a google -u rbarr26@hotmail.com -p outlaw22 -l "Brunnenweg 2, 92249 Vilseck, Germany" -st 5 -ar 10) i receive an error that says example.py cannot be found. 

Any ideas?

**Comment by Kruptein** [comment]
The file to run is 'runserver.py' since version 2.0

Also, Next time don't show your password here ;)

**Comment by whitedeuce22** [comment]
Thanks Kruptein, obviously this is my first time!
