### ISSUE TITLE
Installation Issue: downloaded release version, extracted it, now what

### ISSUE THREAD

**Issue by whitedeuce22** [PokemonGoMap/PokemonGo-Map#440]
I downloaded the release version because I wasn't capable of doing it the other, python could never find the files. Anyway, how do I launch the release version once I extract it?

**Comment by Crazy-Clown** [comment]
@whitedeuce22 unfortunately this is not a technical support forum, you should probably go over to the Pokemongo Dev Reddit threads and ask there;   https://www.reddit.com/r/pokemongodev/

**Comment by whitedeuce22** [comment]
Sorry.
