### ISSUE TITLE
Scan Time

### ISSUE THREAD

**Issue by blackhattristar** [PokemonGoMap/PokemonGo-Map#441]
I've got the map running on a nice fast server but the scan time seems to take forever. Is there any way to speed up the scan process? Even if it misses a Pokémon, I'd rather that than waiting for it to scan for as long as I do. 

Thanks!
## Expected Behavior

Quick scan
## Current Behavior

Slow scan
## Possible Solution

Beef up the scan process
## Steps to Reproduce (for bugs)

1. 
2.
3.
4.

## Context

Don't we all notice that the scan is a little slower than it could be? Don't we all want the scan process to be robust? I feel like this should be at the top of the list rather than thinking about added fun features. Let's beef it up a bit and make it work as good as it could.
## Your Environment

* Version used:
* Environment name and version (e.g. Python 2.7):
* Operating System and version (desktop or mobile):

**Comment by CoolCanuck** [comment]
-sd # 
in command or 
config.ini file scan-delay: #

eg -sd 15
eg scan-delay: 15

**IMPORTANT: Scanning below a 15 second delay (the game's default, used to be 10s), risks getting IP/account blocked, and your map will be unusable using that specific IP.**

1 = 1 second. 
In the future, please seek help on our discord chat or /r/pokemongodev. Thank you.

**Comment by BaIthamel** [comment]
This is not a support forum; please see [the discord #help channel](https://discord.gg/npVqkUn) for assistance.

**Comment by blackhattristar** [comment]
@CoolCanuck Thank you! You're cool! (I'm also a Canuck) Of course it would take a Canadian to give me a great reply and not just close my issue :p Thank you again!

For example, would I add the `-sd` to my code in terminal like this?

`python ./runserver.py -a google -u email -p password -st 10 -k "zTIjnyMk78" -l "34.101547, -118.338729" -sd 1`
