### ISSUE TITLE
[Feature Request] [Minor] Add a comment on issue template notifying user correct place for assistance.

### ISSUE THREAD

**Issue by CoolCanuck** [PokemonGoMap/PokemonGo-Map#443]
Add a <!--- comment

to the template notifying users not to seek help here.. rather discord chat or /r/pokemongodev. 

The user will see this note and hopefully refrain from seeking help via individual support problems.

**Comment by invisiblek** [comment]
i got this

**Comment by CoolCanuck** [comment]
assign yourself .. sir pls

**Comment by invisiblek** [comment]
https://github.com/PokemonGoMap/PokemonGo-Map/pull/446
