### ISSUE TITLE
Sometimes pokemons appear with a big delay

### ISSUE THREAD

**Issue by EmpowerZ** [PokemonGoMap/PokemonGo-Map#447]
For me full scan cycle takes ~60 seconds (sd=0, num_accounts=2, st=8).

But if I look at some pokemons right after they appear they already have really low timeleft, even like 2-3 minutes. This happens even if is the pokemon is in notification list.

## Expected Behavior
If the scan cycle takes 1minute, than pokemons should appear in 1-2 minutes after they are spawned. Making them possible to catch.

## Steps to Reproduce (for bugs)
1. Make sure you have a low scan cycle interval
2. Keep looking into the map and checking the timeleft of newly appeared pokemons
3. Some of them are really low

## Environment
Python 2.7 ; Ubuntu 14.04 ; Chrome PC

**Comment by lungbubble** [comment]
No way full scan of 8 steps takes 60 seconds.  Should have a 10 second delay between scans (-sd 10).  sd 0 likely resulting in your requests to pokemon server for pokemon location information being denied.  so in the off chance that they accept one of your requests, you only finally see the pokemon when its got a few minutes left.  and st 8 is way too big;  at 10 seconds, pokemon will probably already have despawned by the time the spawn restarts.  I've been doing -st 4, would prefer -st 3 but would be too many accounts.

**Comment by EmpowerZ** [comment]
Thanks.
So if that is the case, can we use this bug to retry on those bad requests? Or at least to log them as bad so it is possible to adjust -sd in the best way possible.

**Comment by itztq** [comment]
@lungbubble True story same here..

**Comment by lungbubble** [comment]
Probably, probably a rescan, but I wouldn't even bother.  Just change to -sd 10 and lower your steps.  Bear in mind, 10 steps is not 10 times greater than 1 step, or 5 times greater than 2 steps, its a lot more. 2 to 4 is not double, its more than double.  just check your "scanned locations", if it goes through the whole scan and some areas go from red to nothing, your steps are too big. 

if you *really* want to do rescan, then do "runserver.py --help" and it'll give you some info, i don't remember which command it is.  But i would, still, argue its not worth worrying about it.

**Comment by necre** [comment]
my -st 8 -sd15 with 14 accts works great, green all the time, been up for 2 days straight now :) thanks for the great map tool!

**Comment by BaIthamel** [comment]
This is not a support forum; please see [the discord #help channel](https://discord.gg/npVqkUn) for assistance.
