### ISSUE TITLE
Exit in a cleaner way when worker can't parse map

### ISSUE THREAD

**Issue by springjools** [PokemonGoMap/PokemonGo-Map#448]
Currently the search.py calls parse_map in models.py, but even if there is a try and except for keyError, I still keyerror when a worker doesn't work. Issue is likely not having accepted ToS. This is my output:

> 2016-08-10 22:26:23,084 [ search_worker_0][      auth_ptc][    INFO] PTC Access Token successfully retrieved.
> 2016-08-10 22:26:23,592 [ search_worker_0][        search][   ERROR] Search step 1 map parsing failed, retrying request in 20 seconds
> Traceback (most recent call last):
>   File "U:\bin\github\PokemonGo-Map\pogom\search.py", line 245, in search_worker_thread
>     parse_map(response_dict, step_location)
>   File "U:\bin\github\PokemonGo-Map\pogom\models.py", line 299, in parse_map
>     cells = map_dict['responses']['GET_MAP_OBJECTS']['map_cells']
> KeyError: 'map_cells'

However, the exception is caught here: https://github.com/PokemonGoMap/PokemonGo-Map/blob/develop/pogom/search.py#L249

Why is it not working? Should we send accounts['username'] to models.py and catch it there? I can submit PR if you wish...

Also, I think it would be nice to log all failed usernames to a file, does someone agree? 

Edit: and I just pulled from git develop, the commit fixing worker name in exception should be included.

**Comment by FrancisVarga** [comment]
`Traceback (most recent call last):
  File "/root/PoGoMap/pogom/search.py", line 520, in search_worker_thread
    findCount = parse_map(args, response_dict, step_location, dbq, whq)
  File "/root/PoGoMap/pogom/models.py", line 383, in parse_map
    cells = map_dict['responses']['GET_MAP_OBJECTS']['map_cells']
KeyError: 'map_cells'`

I pulled from the latest develop i have still the error.

**Comment by springjools** [comment]
Yes but now I proposed to fix it this way instead: https://github.com/PokemonGoMap/PokemonGo-Map/pull/895

The issue you refer to and that I commented about 10 days ago is fixed in the latets dev, but you still get that error because the parse_map function is still called with an invalid map, but now you at least have the account name printed in console.
