### ISSUE TITLE
Webhooks doesn´t work 

### ISSUE THREAD

**Issue by jorio2311** [PokemonGoMap/PokemonGo-Map#452]
Hi,

i tried to use Webhooks, but it seems not to work.

python ./runserver.py -a ptc -u "ASD" -p "PWD" -k "asdasdasd" .. -wh "https://push.pokedmap.de"

Is it my fault or the webhooks does not work?

LG Oliver ~ Germany

**Comment by chuyskywalker** [comment]
This is not a support forum; please see [the discord #help channel](https://discord.gg/npVqkUn) for assistance.

**Comment by jorio2311** [comment]
Why Support? The worker does not send any requests to my POST server? This is pretty sure a bug
