### ISSUE TITLE
On-demand mode instead of always scanning

### ISSUE THREAD

**Issue by jtp10181** [PokemonGoMap/PokemonGo-Map#453]
It would be nice to have the application launch with the web interface available, but have an option on the web interface to start/stop the actual scanning. Then it could be used only when wanted without having the launch the script and terminate it when done.

Setting an inactivity timeout would go nice along with this also, so if it is turned on and then not used for X minutes it turns itself off.

**Comment by tkSimon** [comment]
Check out this screenshot: http://imgur.com/a/24LtQ
see the "Search" toggle? i guess that's what you are looking for...

**Comment by jtp10181** [comment]
Ok I saw that, I could not figure out what it was doing. I was thinking it would do something to the search bar in that section. I will check it out later.
