### ISSUE TITLE
Rarity based selection box for rarity notifications is empty

### ISSUE THREAD

**Issue by mtonks** [PokemonGoMap/PokemonGo-Map#454]
pulled down the rarity notification change with glee, but was sad to find the selection box empty. Tried on Chrome windows 10, iOS 9 safari and OSX Safari/Chrome all with the same result.  I see in the page source where it tries to add common/uncommon etc to the selection box but the box is empty. (just have a scroll bar on some browsers, and just an empty box on some)

## Expected Behavior
Selection box should have all the rarity types in it

## Current Behavior
Selection box is empty

## Steps to Reproduce (for bugs)
1. git pull
2. open options menu and look at notifications area

## Your Environment
* Version used: Issue still occurs in #head of Develop as of the writing of this issue
* Environment name and version (e.g. Python 2.7): Python 2.7, Ubuntu (issue also present when server was run in windows10)
![bug_screenshot](https://cloud.githubusercontent.com/assets/20670015/17571310/69455998-5eeb-11e6-87d0-20311846cf76.png)

**Comment by CoolCanuck** [comment]
just did a git pull minutes ago. Issue isn't present on Windows 10 - Chrome browser.

**Comment by mtonks** [comment]
Hmm.. screenshot was taken on windows 10 chrome browser.  I have #head with 0 modifications other than config file.

**Comment by johnkernke** [comment]
did you `npm run build` after pulling the new changes from git?

**Comment by mtonks** [comment]
repulled, reran npm run build and issue went away. Sorry for bad report.
