### ISSUE TITLE
Feature Request: config option for excluding specific Pokemon (or excluding all except specific Pokemon)

### ISSUE THREAD

**Issue by DoktorJ** [PokemonGoMap/PokemonGo-Map#455]
Currently, the config has a "no-pokemon" option that disables displaying and inserting (into DB) Pokemon. I would like to see a config option like "ignore-pokemon" that takes a comma- or space-delimited list of Pokemon names or IDs (should be case-insensitive for names, to minimize support anguish from noobs who put in "WEEDLE" and get errors). Names would be better for readability, but if it's substantially more difficult to implement, the IDs should be sufficient.

Pokemon specified in the option should be completely ignored upon scanning; they should not appear on the map, should not be upserted, and any webhooks should not be called for them.

In addition to the immediately obvious benefit of making the map cleaner without having to have a mile-long list of exclusions in the interface (that you have to duplicate on each device you view the map from), this also provides a server-side benefit of reducing CPU, memory, and disk usage because the Pokemon are not touching the DB. Network usage and CPU/memory usage on remote servers is also reduced because fewer webhook calls are being made too.

**ADDITION**: Some people may only be looking for a few specific Pokemon; having a companion "only-pokemon" setting would improve readability so instead of ignoring 140 Pokemon they could use this list to have it only display/upsert/hook for the 10 Pokemon they're interested in.

The only caveat with this would be defining the behavior if something is specified for both lists. I think failing gracefully is an acceptable option here, e.g. quitting with a message. Another option would be that the "only-pokemon" option takes precedence, so if anything is specified for it the "ignore-pokemon" list gets ignored. You could also just accept the first/last option based on order in the config, but this would make troubleshooting more difficult.

**Comment by CoolCanuck** [comment]
Nice idea.

**Comment by craywong** [comment]
definitely wanted. I'm actually only showing very few types of pokemon right now. It'd be great to get rid of all the other pokemons at the very beginning.

**Comment by Zentriert** [comment]
I love the idea of this for efficiency reasons and reducing the amount of API calls to Niantic, would it be possible to make it so we can do the same easily (maybe even from the web frontend) to disable scanning of Gyms and Pokestops for the same reasoning? (disabling this would kill the ability to know about lured Pokemon too correct?)

**Comment by DoktorJ** [comment]
@Zentriert actually I don't think it'll reduce the amount of API calls to Niantic; the only way to find out *if* there's a desired Pokemon in a given location is to scan it. If you have webhooks though (Pokelyzer, etc) it will reduce calls to those.

Similarly, if you have an external MySQL database (for example, I'm giving Google's CloudSQL a spin), reducing the ingress/egress traffic to it is a win.

**Comment by DoktorJ** [comment]
I tested on a local branch; adding the following to `pogom/models.py` seems to achieve the desired effect:

after `def parse_map(map_dict, step_location)`, put the following code _immediately_ below `for p in cell.get('wild_pokemons', []):`
```
                ignores = [10,11,12,13,14,15,16,17,18,19,20,21,22,41,42,43,44,45,46,47,48,49,54,55,96,97]
                if p['pokemon_data']['pokemon_id'] in ignores:
                    continue
```

Of course my list here is hard-coded, but it should be trivial to pass a list to parse_map that's ultimately defined in the config.ini. It skips the loop before the pokemons{} or webhook_data{} dictionaries are populated (and bypasses the `send_to_webhook()` call altogether) so the ignored Pokemon are never populated into the DB or passed to the webhook.

**Comment by irus99** [comment]
@DoktorJ This worked for me. Thanks

**Comment by DoktorJ** [comment]
BTW if you don't want git to whine at you about the change, do the following in the PokemonGo-Map directory prior to making changes:

```
git branch ignorelist
git branch --set-upstream-to=origin/develop ignorelist
git checkout ignorelist
```

I haven't tested it myself, but the second command should allow you to continue taking changes from the develop branch without git whining that models.py has uncommitted changes.

**Comment by BaIthamel** [comment]
For feature requests please migrate this to the new feature page
http://feathub.com/PokemonGoMap/PokemonGo-Map/
Thankyou!

**Comment by CoolCanuck** [comment]
@BaIthamel This request needs to be opened again. FeatHub is no longer used. Good riddance.
