### ISSUE TITLE
Request throttling seems to fail for a period after search has been stopped and restarted

### ISSUE THREAD

**Issue by nnpoke** [PokemonGoMap/PokemonGo-Map#456]
After the implementation of spreading workers out evenly over the scan delay time then if you stop the search in the location settings UI and later re-enable the search, the worker threads are not throttled for some time.

## Expected Behavior
When disabling and re-enabling search the worker threads should be throttled according to scan delay

## Current Behavior
After re-enabling search a lot of search requests are fired in a very short time which might give you errors saying you have to slow down

## Possible Solution
Make sure workers are throttled when search is activated from the UI

## Steps to Reproduce (for bugs)
1. Disable search from the UI
2. Wait a few minutes
3. Enable search from the UI
4. Notice how fast the search grid is executed. You can also see how fast the console output is generated

## Context
I'm affraid it can cause IP bans

## Your Environment
Server running on Ubuntu and using latest PokemonGo-Map

**Comment by nnpoke** [comment]
The problem is located in search.py:

 sleep_delay_remaining = loop_start_time + (args.scan_delay * 1000) - int(round(time.time() * 1000))
 if sleep_delay_remaining > 0:
     time.sleep(sleep_delay_remaining / 1000)

 loop_start_time += args.scan_delay * 1000

Loop_start_time should be set to current time instead of just adding scan_delay. If you have paused your worker threads for a long time then it will loop without sleeping until loop_start_time has caught up to the actual time.

So my suggestion is to change the last line of code to:
 loop_start_time = int(round(time.time() * 1000))

**Comment by ocoot** [comment]
still have the problem :|

**Comment by chuyskywalker** [comment]
@invisiblek you broke'd it!

**Comment by invisiblek** [comment]
^

**Comment by Cy4n1d3** [comment]
Happens for me aswell, ssh tunnel lost connection and after reconnent all workers are speeding up their efforts quite a bit, which results in heavy throttling :)

**Comment by RiberoD07** [comment]
still having a similar issue not sure if it warrants opening a separate issue for it but when toggling scan follows location or when using the auto locate button near the zoom tools console says thread search paused and nothing happens after that.. I tried toggling it off, refresh page, playing with the other settings, moving the pin on the map and it never started populating again. I had to kill the script and restart. Is there any solution?

**Comment by nnpoke** [comment]
I have solved the problem with this code in pogom/search.py. Find the last line and place the code before that line... Then it will resume threads evenly and reset the loop_start_time.


# Create delay after resume search
if len(args.accounts) > 1:
    sleep_resume_delay = loop_start_time + (args.scan_delay * 1000) - int(round(time.time() * 1000))
    if sleep_resume_delay < 0:
        loop_start_time += (int(math.ceil(-sleep_resume_delay / (args.scan_delay * 1000))) + 1) * (args.scan_delay * 1000)
        log.info('Sleeping for %.2f seconds before resuming', sleep_resume_delay)
        time.sleep(sleep_resume_delay)

log.info('Search step %d beginning (queue size is %d)', step, search_items_queue.qsize())

**Comment by nnpoke** [comment]
Sorry posted wrong code to begin with... It is correct now.

**Comment by Cy4n1d3** [comment]
#530

**Comment by Racle** [comment]
@nnpoke solution seems to be working very well. Atleast for me and with 5 accounts.
