### ISSUE TITLE
[Bug] Website requests for pokestops even with the switch off

### ISSUE THREAD

**Issue by Romfrosk** [PokemonGoMap/PokemonGo-Map#459]
Looking through the requests the site is doing it seems like the switch Pokestop has no function.
The website still does the following with pokestop switch off.

pokemon and pokestops both turn on/off when you switch "pokemon" on of in the marker setting

http://pokemaps.no/raw_data?pokemon=true&pokestops=true&gyms=false&scanned=false&swLat=60.386181633194234&swLng=5.322651772460972&neLat=60.39587164586607&neLng=5.329518227539097&_=1470864839415

Scanned and Gyms works as intended

## Expected Behavior
Marker Settings:
Pokemon [on]
Pokestops [off]

http://pokemaps.no/raw_data?pokemon=true&pokestops=false&gyms=false&scanned=false&swLat=60.386181633194234&swLng=5.322651772460972&neLat=60.39587164586607&neLng=5.329518227539097&_=1470864839415

## Current Behavior
Marker Settings:
Pokemon [on]
Pokestops [off]

http://pokemaps.no/raw_data?pokemon=true&pokestops=true&gyms=false&scanned=false&swLat=60.386181633194234&swLng=5.322651772460972&neLat=60.39587164586607&neLng=5.329518227539097&_=1470864839415

## Steps to Reproduce (for bugs)
1. Open site
2. Open Developer Tools for your browser
3. Open Network  (edited)
4. look at the requests being sent and play with the switches under Marker Settings

## Context
This issue makes the site slower than needed when not asking for Pokestops

Additional info:

The icons for pokestops vanishes when clicking the button. but the website still request the data. making the site slower than needed

## Your Environment
* Version used: dev (Commit 812)
* Environment name and version (e.g. Python 2.7): Python 2.7.12
* Operating System and version (desktop or mobile): Windows Server 2012 R2 . Desktop

**Comment by LordRad** [comment]
AFAIK interface (localhost) switch only hides the pokestops on the map overlay, if you want the script to not scan pokestops you have to put a switch in the runserver.py arguments

**Comment by Romfrosk** [comment]
Indeed. but the map overlay should not  pull pokestop data from the server when the switch is off.

the website does not pull these data for scanned locations, gyms or pokemons when they are switched off.

It seems like when pokemon switch is on the website automatically requests both pokestop and pokemon data

**Comment by ChrisbeChicken** [comment]
@Romfrosk can i contact you via email or something else, i saw your map and it works awesome on your way maybe you have time to help me to set my map up to get a result like your map.

**Comment by Xcelled** [comment]
You can see this in the JS here: https://github.com/PokemonGoMap/PokemonGo-Map/blob/d3eaf307d3e8ccade3ae633ce7be1b02e28a250f/static/js/map.js#L1356

It looks pretty deliberate, and my guess is that lured pokemon are sent only to with their pokestop. In order to show lured pokemon along with normal spawns, it retrieves pokestop data even when pokestops are off.

Tracking back through the history, it appears the line was introduced in [c810747](https://github.com/PokemonGoMap/PokemonGo-Map/commit/c810747155aea40660a9c2272770ad42120cdab6) which says "fix pokestops with no lured pokemon".

Given that, I'd say this isn't a bug, but rather a poor implementation of a bugfix. The cleanest thing to do would be to put the lured pokemon in with the rest of them, but that might require some extended API reshuffling.

**Comment by Xcelled** [comment]
Traced back a little further to here: https://github.com/PokemonGoMap/PokemonGo-Map/commit/83956f01f96133909a77be5a5c20e147035cbb97

That's where the conditional for lured pokemon was introduced originally, and you can see the comment beside it says

> lured mons need pokestop data

**Comment by chuyskywalker** [comment]
It's a fair request to get this refactored/fixed.

**Comment by BaIthamel** [comment]
For feature requests please migrate this to the new feature page
http://feathub.com/PokemonGoMap/PokemonGo-Map/
Thankyou!

**Comment by CoolCanuck** [comment]
@BaIthamel This request needs to be opened again. FeatHub is no longer used. Good riddance.
