### ISSUE TITLE
Ideas for the Map

### ISSUE THREAD

**Issue by thelionroars89** [PokemonGoMap/PokemonGo-Map#460]
This is re post- I think that everyone would agree, that if it were possible for you to create either a way for multi pin drops for scan locations, Also selecting different radius scans after login, for each pin drop as well. Each pin drop can be from a single account or multiple accounts. For instance, each pin before selecting it, you can select from a drop box of which user account you want to use. It can be the same account, or another account. (I have had success running 3 instances on one account with the current update.) When the pin is dropped, you can then adjust the radius settings under Example: Pin 1. Settings, Pin 2 settings, Pin 3 settings, Pin 4 settings. Each pin has settings that would allow each pin to do specific things. Also, please note that the colors in my opinion would be amazing if they went from green to blue to green to blue, so we know that certain area is indeed being scanned for sure. First circle green, second blue, third green and so on... The reason for this is because if any pins get moved by chance, it causes an ugly overlay that is very difficult for us to see what we are scanning and if it is still scanning.
I think it would a really great idea if you could put in a feature that would allow a change from a circle pattern to a block pattern. a line that goes across, and then down and then across and so on. Lastly It would be amazing if the scanned area would turn to yellow after 10 seconds, instead of us waiting for color changes for too long. Just to let us know that the area was scanned and that the rest is being scanned. After the first scan, it would be very nice that all the colors drop off the map as soon as the scan starts up again. It would look much cleaner. These are my ideas please feel free to have input. -TLR

**Comment by Studio-XP** [comment]
I don't have an answer to everything, but here I go:

In regards to the circle pattern to a block pattern... the way the game and app works is that it searches in a circle around your current location.

The "honeycomb" way of searching the map is actually very effective. It starts from your starting location and gradually searches further and further out, while also showing how long ago the location was scanned (green > yellow > red > back to green when it searches at that location again). If you're concerned with cleanliness, you can toggle Scanned Locations in the options menu
