### ISSUE TITLE
[Request] Change step size via web interface.

### ISSUE THREAD

**Issue by Nipper4369** [PokemonGoMap/PokemonGo-Map#465]
I would like to request a way to change stepsize of the scanning via webinterface if we can. I know oyu can pause it but just having stepsize to make it smaller or bigger would be nice.

**Comment by Studio-XP** [comment]
By step size, do you mean how wide the little circles are in Scanned Locations/honeycomb? If so, it's coded that way due to how the game operates. It only shows Pokemon within that range. If you make the radius larger, it will miss Pokemon on the edge of the circles.
