### ISSUE TITLE
Ngrok and Local Tunnel URL Kicking Me Out After Several Minutes

### ISSUE THREAD

**Issue by MJ869** [PokemonGoMap/PokemonGo-Map#466]
## Expected Behavior

After linking ngrok or localtunnel with localhost address on desktop and creating URL, map should continue to display and scan should continue to run.

## Current Behavior

After several minutes, scan freezes. Upon refreshing URL, error returned in browser "Too many connections! The tunnel session '###' has violated the rate-limit policy of 20 connections per minute. Please decrease your inbound connection volume or upgrade to a paid plan for additional capacity. ERR_NGROK_702" 

OR 

Using localtunnel, scan freezes, and git bash returns error "Error: connection refused: localtunnel.me:##### (check your firewall settings)"

## Possible Solution

This issue may be _similar_ to closed issue #296 although when I change pogom/models.py to the code suggested, git bash returns the error "NameError: name 'db' is not defined"

## Steps to Reproduce (for bugs)

1. python runserver.py -a ptc -u [login] -p [pw]-st 13 -sd 3 -ld 1 -k [api key] -l "[location]" -H 0.0.0.0 -L en
2.Open gnrok and run: ngrok http 5000
3.Access URL, works fine for a couple minutes, then freezes and error is returned
4.

## Context

View PokemonGo-Map via URL from my Android device

## Your Environment

* Version used: commit modified 8/10/2016 1:37PM EST
* Environment name and version (e.g. Python 2.7): Python 2.7
* Operating System and version (desktop or mobile): Windows 10 64-bit & Android 6.0.1

**Comment by Lionir** [comment]
If this is to view on your mobile phone, simply find out your public IP by googling "What's my IP?" Then from any device, you can simply go to http://PublicIP:port if I'm not mistaking.

**Comment by MJ869** [comment]
Would also want to _manipulate the settings_ via mobile such as marker, location, notification, style, etc; basically everything you could manipulate via desktop, and can currently do via ngrok and local tunnel.

**Comment by Studio-XP** [comment]
Anything that you can modify from within the options on the map can be edited on mobile as well. By doing what @Lionir said, finding out what your public IP address is, forwarding port 5000 in your firewall/router and accessing it by going to http://publicIP:5000, you get the same map on your phone as you do on your desktop. You could even go a step further and sign up for a free dynamic dns service, such as no-ip so you can access it by an easy to remember web address instead of a dynamic IP address.

**Comment by MJ869** [comment]
That seems to have worked! Thank you!
