### ISSUE TITLE
Cannot get npm install to work - PLEASE HELP!

### ISSUE THREAD

**Issue by weiguken** [PokemonGoMap/PokemonGo-Map#473]
For some reason I cannot get npm install to work correctly and I keep receiving the following message:
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8
npm ERR! code ELIFECYCLE
npm ERR! pogomap@3.5.2 postinstall: `grunt build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pogomap@3.5.2 postinstall script 'grunt build'.
npm ERR! This is most likely a problem with the pogomap package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     grunt build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs pogomap
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls pogomap
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\ste\Desktop\PokemonGo-Map-develop\npm-debug.log

To my knowledge, I have done everything else correctly. Updated requirements.txt is installed etc. PLEASE HELP!

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Python 2.7):
* Operating System and version (desktop or mobile):

**Comment by LIJE** [comment]
pip install -r requirements.txt
pip install --upgrade pip
npm install --unsafe-perm
npm install -g grunt-cli
npm install node-sass
npm update
npm run build

**Comment by ocoot** [comment]
@LIJE i got this error after updating the repo. how to fix this?

$ npm install
$ npm WARN lifecycle pogomap@0.1.0~postinstall: cannot run in wd %s %s (wd=%s) pogomap@0.1.0 grunt build /root/PokemonGo-Mapa

**Comment by LIJE** [comment]
easy_install pip and redo ?

**Comment by ocoot** [comment]
wha do you mean? i don't get it

**Comment by herculys** [comment]
same error, cant get PoGo-map to work.

**Comment by elvquant** [comment]
Likely https://github.com/PokemonGoMap/PokemonGo-Map/issues/470 ?

**Comment by herculys** [comment]
just to advise, in windows my versions are (and are up to date i think):
`node --version
v4.4.7
npm --version
2.15.8`

the wiki show a very higher versions: [here](https://pgm.readthedocs.io/en/develop/basic-install/index.html)

`$ node --version
v4.7.0
$ npm --version
3.8.9`

**Comment by weiguken** [comment]
@herculys Yeah i thought it was a problem with the npm version, but every time I try to update it goes to 2.15.8. is there anyway to get it to 3.8?

**Comment by xordinx** [comment]
use this https://nodejs.org/en/

**Comment by weiguken** [comment]
@xordinx i have and it installs 4.4.7 but npm is still 2.15.8

**Comment by xordinx** [comment]
there is other version on right side..it's 6.3.1

**Comment by weiguken** [comment]
@xordinx i tried that too. doesnt work.

**Comment by xordinx** [comment]
@weiguken last try..after installing 6.3.1 use this command
npm install -g npm

**Comment by BaIthamel** [comment]
This is not a support forum; please see [the discord #help channel](https://discord.gg/npVqkUn) for assistance.

**Comment by herculys** [comment]
we are 3 with same problem, i tried help in discord and just got ignored.
