### ISSUE TITLE
Map parsing fails when more than one account is used

### ISSUE THREAD

**Issue by borring** [PokemonGoMap/PokemonGo-Map#474]
## Expected Behavior

search_workers function normally even with multiple accounts

## Current Behavior

Map parsing fails when multiple accounts are specified in `config.ini`

## Steps to Reproduce (for bugs)

1. Add at least 2 google accounts to config  
2. Launch pogom  

## Context

Tried to speed up scanning. Adding another account ended up slowing it down
significantly. Map parsing fails very often.

## Your Environment

* Version used:
* Environment name and version: Python 2.7.11
* Operating System and version: (linux) Desktop

[pogom.txt](https://github.com/PokemonGoMap/PokemonGo-Map/files/412667/pogom.txt)

**Comment by hansbonini** [comment]
Same problem

**Comment by elit3ge** [comment]
From what I remember you can't have multiple accounts in the config. You can however have multiple account in the terminal.

**Comment by Kryzek** [comment]
Yes you can have multiple accounts in the config:
username: [acc1,acc2,acc3]
password: [pass1,pass2,pass3]

**Comment by elit3ge** [comment]
Do you need to include the []?

**Comment by Fohdeesha** [comment]
yes

**Comment by PhobosMX** [comment]
If your account is new, it will fail... You need to login from the original app first.

**Comment by sn0opy** [comment]
@PhobosMX what? That must be new then.

**Comment by Fohdeesha** [comment]
they started making new accounts accept the TOS in the app for them to be able to be used, but you can get around it by using a tos accepting script such as https://github.com/TachyonRSA/PoGoTos

**Comment by Akivas** [comment]
You can use this script to accept Terms of Services : 
(it's a draft, be sure to modify the auth, username and password at the end of the file)

```
#!/usr/bin/python
# -*- coding: utf-8 -*-

"""accept-tos.py: Example script to accept in-game Terms of Service"""

from pgoapi import PGoApi
from pgoapi.utilities import f2i
from pgoapi import utilities as util
from pgoapi.exceptions import AuthException
import pprint
import time
import threading

def accept_tos(auth, username, password):
        api = PGoApi()
        api.set_position(40.7127837, -74.005941, 0.0)
        api.login(auth, username, password)
        time.sleep(2)
        req = api.create_request()
        req.mark_tutorial_complete(tutorials_completed = 0, send_marketing_emails = False, send_push_notifications = False)
        response = req.call()
        print('Accepted Terms of Service for {}'.format(username))
        print('Response dictionary: \r\n{}'.format(pprint.PrettyPrinter(indent=4).pformat(response)))

accept_tos('auth', 'username', 'password')
```

PS: You can also add `import sys` and replace the last line by `accept_tos(sys.argv[1], sys.argv[2], sys.argv[3] )` in order to pass arguments to the script in command line)

**Comment by matpag** [comment]
i have accepted the tos with the script above for every account but seems to not working.
(accounts were created before the last api change)

**Comment by aididhaiqal** [comment]
Thanks!Using 1000 acc now haha...Scan like OP

**Comment by Melorne** [comment]
aididhaiqal:   How did you create 1000 accounts?  Were they Google or PTC?

**Comment by aididhaiqal** [comment]
PTC i use a script for it

**Comment by BaIthamel** [comment]
This is not a support forum; please see [the discord #help channel](https://discord.gg/npVqkUn) for assistance.
