### ISSUE TITLE
[Feature Request] import old pogom.db

### ISSUE THREAD

**Issue by Bart274** [PokemonGoMap/PokemonGo-Map#477]
## Expected Behavior
when switching from the old pogom.db to mysql, the data is lost, it would be great if the data could be imported at startup if the pogom.db file exists but isn't used and if that file gets deleted after the import

## Current Behavior
when switching from the old pogom.db to mysql, all the old data gets lost

## Possible Solution
import the pogom.db file if it exists and delete it after the import

**Comment by R0adRunn3r** [comment]
You can do it manually for now.. there are tools online for this! or take a look at this guide http://asmuth.com/~paul/blog/migrate_sqlite_to_mysql/ :)
