### ISSUE TITLE
'Your Location' not working with Chrome (GeoLocation requires secure origin)

### ISSUE THREAD

**Issue by iainfm** [PokemonGoMap/PokemonGo-Map#480]
## Expected Behavior

Clicking/tapping the 'Your Location' icon (bottom right) in browser should request location access (if applicable), read user's location, then centre map to it.

## Current Behavior

Works in IE - a request to access user's location is generated. Accepting this centres the map as expected.

Does not work in Chrome (desktop and Android) - no access request is generated, the location is not set, and the icon just flashes.

Chrome developer console reports:

**getCurrentPosition() and watchPosition() no longer work on insecure origins. To use this feature, you should consider switching your application to a secure origin, such as HTTPS. See https://goo.gl/rStTGz for more details.**

## Possible Solution

Implement https connectivity

## Steps to Reproduce (for bugs)
1. Open browser and navigate to map URL
2. Tap 'Your Location' icon (cross-hairs, bottom right)

## Context
Trying to centre map around current location in Chrome (desktop or mobile). Location services are on and allowed within the browser.

## Your Environment

Chrome 52 (desktop, Windows 7)
Chrome 52 (Android, Cyanogenmod 13)
Windows 7 host
Python 27
Latest git pull today (11 Aug)

Apologies if this is a re-post. Great work guys! :)

**Comment by Slivo-fr** [comment]
You can use an apache web proxy to manage HTTPS untill it's (maybe) implemented

**Comment by DiscoTim** [comment]
the error is exactly what it says, it needs ssl for geolocation. easiest way is nginx for windows, setup as a proxy, with a https://letsencrypt.org/ cert.

**Comment by Slivo-fr** [comment]
Well, the issue is asking for HTTPS handling with the shipped flask web server, the HTTPS proxy is a workaround

**Comment by DiscoTim** [comment]
very true :)

**Comment by iainfm** [comment]
Thanks for the replies. Used nginx for a reverse proxy, with a LetsEncrypt cert, and all is splendid :)

**Comment by iainfm** [comment]
Afterthought: Given that Chrome trusts localhost for location, it may be possibly just to run a reverse proxy that just redirects port 80 (say) to port 5000 (or whatever), with no need for https/certs...

**Comment by BaIthamel** [comment]
This is not a support forum; please see [the discord #help channel](https://discord.gg/npVqkUn) for assistance.

**Comment by Slivo-fr** [comment]
Well, it's not a support thread, he's asking for HTTPS implementation
