### ISSUE TITLE
[Enhancement] Stop the worker if it finds 0 pokestop and gyms too many times

### ISSUE THREAD

**Issue by R0adRunn3r** [PokemonGoMap/PokemonGo-Map#482]
I think that add a feature for automatically shut down the worker if it finds more than X times 0 pokestops and 0 gyms would help for preventing IP ban!  

and maybe send a communication through the webhook  before shutting down

What do you guys think?

**Comment by Romfrosk** [comment]
Sounds like a plan. Also restart them every 15 minutes after that to se if the ban has cleared.

**Comment by crckdns** [comment]
I thought the same today in the morning! Great, I'm not alone

**Comment by h3k1ru** [comment]
I'm supporting this. But don't forget some people disable pokestops or gyms data to reduce database load. So you must be able to choose between what to check, pokestops **or/and** gyms or none.

**Comment by marumari** [comment]
It should probably be zero upserts entirely (Pokemon, Gyms, and Pokestops).

@h3k1ru: I believe the search threads still see the gyms and pokestops; they just don't insert it into the database if you disable them.  But I could be wrong!

**Comment by marcmicalizzi** [comment]
0 upserts for all 3 on a worker for a certain number of iterations would be ideal, and possibly rather than 15 minutes, have it be specifiable, and probably increasing too. i.e. if after 15 minutes worker is still getting 0 0 0, then wait for 30 minutes, and so on.

**Comment by R0adRunn3r** [comment]
Maybe must be implemented like an option from command line/config file so the user can be able to activate or not this function (think about rural areas without any pokestop or gyms)

I'm not confident with python.. I use other languages. Who can try to implement this?

**Comment by BaIthamel** [comment]
This is not a support forum; please see [the discord #help channel](https://discord.gg/npVqkUn) for assistance.

**Comment by marcmicalizzi** [comment]
@Balthamel what part of this ticket was asking for support? It's a feature request?

**Comment by R0adRunn3r** [comment]
I was not asking for support i'm proposing a feature for addition

**Comment by h3k1ru** [comment]
@BaIthamel It's a valuable feature request, reopen please.

**Comment by R0adRunn3r** [comment]
@marcmicalizzi reopened this #506

**Comment by marcmicalizzi** [comment]
@R0adRunn3r and now reworded and reopened as #569
