### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by shane17** [PokemonGoMap/PokemonGo-Map#483]
When i run the following command (trying to install) 
I get the following error

$ pip install -r requirements.txt

Collecting pyproj (from LatLon==1.0.1->-r requirements.txt (line 17))
  Using cached pyproj-1.9.5.1.tar.gz
    Complete output from command python setup.py egg_info:
    nad2bin.c
    nad2bin.c(129) : warning C4244: '=' : conversion from 'double' to 'float', possible loss of data
    nad2bin.c(130) : warning C4244: '=' : conversion from 'double' to 'float', possible loss of data
    nad2bin.c(137) : warning C4244: '=' : conversion from 'double' to 'float', possible loss of data
    nad2bin.c(138) : warning C4244: '=' : conversion from 'double' to 'float', possible loss of data
    nad2bin.c(352) : warning C4244: '=' : conversion from 'double' to 'float', possible loss of data
    nad2bin.c(353) : warning C4244: '=' : conversion from 'double' to 'float', possible loss of data
    pj_malloc.c
    using bundled proj4..
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\shane\appdata\local\temp\pip-build-rkqbqx\pyproj\setup.py", line 74, in <module>
        cc.link_executable(objects, execname, extra_postargs = [ '/MANIFEST' ] if os.name == 'nt' else  None)
      File "c:\python27\lib\distutils\ccompiler.py", line 700, in link_executable
        debug, extra_preargs, extra_postargs, None, target_lang)
      File "c:\python27\lib\distutils\msvc9compiler.py", line 669, in link
        raise LinkError(msg)
    distutils.errors.LinkError: command 'C:\\Users\\shane\\AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0\\WinSDK\\Bin\\x64\\mt.exe' failed with exit status 31

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in c:\users\shane\appdata\local\temp\pip-build-rkqbqx\pyproj\

## Expected Behavior

Installs smoothly without any errors :D

## Current Behavior

Installation exits with error msg.

## Possible Solution

fix or install something . that will enable em to install  pyproj-1.9.5.1

## Steps to Reproduce (for bugs)

1. pip install -r requirements.txt  (in correct directory)
2.
3.
4.

## Context

Unable to install map

## Your Environment

Dev branch, https://github.com/PokemonGoMap/PokemonGo-Map/commit/3737cdc13420f95fb287397cdab71939b561ed74
Phyton 2.7
Microsoft Visual C++ Compiler for Python 2.7 
windows 10 64-bit

**Comment by baulie** [comment]
Did you install [Microsoft Visual C++ Compiler for Python 2.7](https://www.microsoft.com/en-us/download/details.aspx?id=44266)?

**Comment by shane17** [comment]
yes, installed. 

and then uninstalled, and reinstalled ~ just to make sure it wasn't causing the problem ..

**Comment by BaIthamel** [comment]
This is not a support forum; please see [the discord #help channel](https://discord.gg/npVqkUn) for assistance.

**Comment by javimoya** [comment]
same problem here... windows 10 :(
