### ISSUE TITLE
Not many pokemon are showing on the map

### ISSUE THREAD

**Issue by praneetsingh** [PokemonGoMap/PokemonGo-Map#485]
Not showing much pokemon as compare to the first time i installed the map it is showing much much less pokemon now

  ISSUES ARE NOT FOR SUPPORT!!!

  ISSUES ARE NOT FOR SUPPORT!!!
  ISSUES ARE NOT FOR SUPPORT!!!
  ISSUES ARE NOT FOR SUPPORT!!!
  ISSUES ARE NOT FOR SUPPORT!!!
  ISSUES ARE NOT FOR SUPPORT!!!

  Join discord (channel: #help) for support at this link: https://discord.gg/PWp2bAm

-->

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Python 2.7):
* Operating System and version (desktop or mobile):

**Comment by crckdns** [comment]
What does the console say?

**Comment by iainfm** [comment]
Turn on 'scanned locations' in marker settings, and check your scan area is satisfactory. Too many steps, or too long a step delay will cause you to miss pokemon.

**Comment by aldarund** [comment]
ISSUES ARE NOT FOR SUPPORT!!! -> i guess its pretty clear message but still seems u cant read it :)

**Comment by praneetsingh** [comment]
consol says 0pokemon 0stops 0gym
On second it add very few pokemon and so on

**Comment by BaIthamel** [comment]
This is not a support forum; please see [the discord #help channel](https://discord.gg/npVqkUn) for assistance.
