### ISSUE TITLE
[Feature Request] Implement 'Learning Mode' and 'Low Volume Scan' mode

### ISSUE THREAD

**Issue by Dagothur** [PokemonGoMap/PokemonGo-Map#487]
-Learning Mode: the map as it is now
-Low Volume Scan mode: implement this scanning algorithm https://www.reddit.com/r/pokemongodev/comments/4wxteh/i_implemented_tbterras_spawntracker_into/

> Create a file spawns.json that looks like this (spawn time in seconds):
> [{"lat": 41.293736266182, "lng": -62.1513092230657, "time": 849}, {"lat": 41.2947454801168, "lng": -62.1534389705451, "time": 1286}]
> Run runserver.py with "-st 1". Each location in the file will be scanned at the designated time. It works exactly as intended, every scan picks something up, no wasted scans. You need to manually balance the number of workers (users) with the number of locations to scan.

Concerns:

-~~Would this result in accounts getting softbanned as the algorithm will have them jumping all over the place? (Possible solution: divide up accounts between lat/long quadrants?)~~

**Comment by Cronick** [comment]
Even with softbanned accounts, it should be no problem to use them.

**Comment by Dagothur** [comment]
@Cronick Do softbanned accounts still return data to upsert?

**Comment by BaIthamel** [comment]
actually yes, since you can "see" the pokemon when sofbanned it just runs away instantly.

**Comment by DoktorJ** [comment]
Possibly related to #225 ?

**Comment by Xcelled** [comment]
Also #179

**Comment by GenuineSounds** [comment]
@DoktorJ Correct.

**Comment by BaIthamel** [comment]
For feature requests please migrate this to the new feature page
http://feathub.com/PokemonGoMap/PokemonGo-Map/
Thankyou!

**Comment by CoolCanuck** [comment]
@BaIthamel This request needs to be opened again. FeatHub is no longer used. Good riddance.
