### ISSUE TITLE
Full Stats for more than 24h

### ISSUE THREAD

**Issue by l4v4l4mp3** [PokemonGoMap/PokemonGo-Map#489]
From my end it would be really helpfull, to have "full stats" page available not only for last 24hours scaned pokemon.

I would like to have an option for a week, or maybe at least alltime (maybe with a clear database) option.

## Current Behavior
The full stats page shows all pokemon from last 24hours scanned

## Possible Solution
All time display option would be great

**Comment by lota7** [comment]
On the full stats page, click Options

**Comment by l4v4l4mp3** [comment]
Oh damn we are sitting here three people and no one has chekce dthis before. so my fault - can be closed
