### ISSUE TITLE
Feature request: A tiny hint of user friendliness

### ISSUE THREAD

**Issue by bmeucci** [PokemonGoMap/PokemonGo-Map#490]
Is it really that much to ask for a pre-compiled executable? Can't someone who has already comiled it just drop it here? Is there something weird with python that it can't produce programs the average system can run? This is so extremely odd.

I despise installing crap on my already horrifically unstable windows 10 machine that I don't need. Each installation brings me one step closer to a full system re-install.

Do I really have to go get a compiler, or development environment or whatever it was in in the install instructions and install all that just to install this app? I've got to be missing something.

**Comment by jorio2311** [comment]
There is a release version ^^

**Comment by evispo** [comment]
https://github.com/mchristopher/PokemonGo-DesktopMap/releases

This man made what you need ^

**Comment by bmeucci** [comment]
Okay that's cool but now I'm confused. Maybe my feature request should be about the way this site works?

How the devil is that release linked to this code? When I go to releases from here, it gives me source code releases and the link you've given me is also a release under a path that looks like a particular site user's files or something.

How would I have found that myself from here?

(thanks for the help by the way!)

**Comment by krummrey** [comment]
This is the Python version. The Desktop Map is a bundled project that packaged it all into one app.
They are two different projects, one building upon the other.

**Comment by BaIthamel** [comment]
This is not a support forum; please see [the discord #help channel](https://discord.gg/npVqkUn) for assistance.
