### ISSUE TITLE
[Feature Request] Skype notifications

### ISSUE THREAD

**Issue by lota7** [PokemonGoMap/PokemonGo-Map#491]
## Expected Behavior

Send to skype is config available only to the admin, where admin inputs information on the skype account to be used, and to send to which user and/or Group, along with starting point of scan, and the size of it.
.
**Multi user/group support** would be great, so multiple starting locations and radiuses can be set and each would notify to a certain Group. 

Messages limited to existing friends on that given skype account.
Message should include 
• Name of Pokemon
• Location (Either lat/lon and/or nearest address)
• Time to Expire (eg 21.20 or 09.20pm)
• Time before spawn expires (eg 12:23 mins left)
• Google Maps link to take one directly to the location should the link be clicked.

## Current Behavior

Currently no Skype notifications available.

## Possible Solution

Add fields to config.ini requiring 
• Skype username
• Password
• Api
• Which user AND/OR Group to send to
• Starting point of notification radius (so we only get notification for the pokemon close to us)
• Size of notification radius in meter

Starting point of notification and size are multiple location based, so multiple groups can be alerted depending on settings. (This to avoid having Group X be notified of a spawn thats too far for them).

## Context

Me and my friends run a small map for our town.
Since skype is widely used, we'd like to have the notification to also send to Skype.
Also multi group/user implementation would enable Person X to only be notified of spawns near person X and not be notified by Spawns eg. 10km away, while Person Y would.

## Your Environment

* Version used: Dev
* Environment name and version: Python 2.7
* Operating System and version (desktop or mobile): Desktop Windows 10

**Comment by krummrey** [comment]
Could that be done in a more generic way so that you could use Twitter, IFFT, Telegram ... ?

**Comment by daaaaa** [comment]
For notification service ask/use: https://github.com/kvangent/PokeAlarm

**Comment by BaIthamel** [comment]
This is not a support forum; please see [the discord #help channel](https://discord.gg/npVqkUn) for assistance.

**Comment by lota7** [comment]
How was my post a support issue?
