### ISSUE TITLE
NOT NULL constraint failed: pokestop.encounter_id... Retrying

### ISSUE THREAD

**Issue by jonathanwcrane** [PokemonGoMap/PokemonGo-Map#494]
## Expected Behavior

I run runserver.py and the threads find pokemon and display them on the map...messages like upserted X pokemon, etc

## Current Behavior

Whether I run it with 1, 3, or 10 accounts, I get a slew of messages like
[ search_worker_0][        models][ WARNING] NOT NULL constraint failed: pokestop.encounter_id... Retrying

## Steps to Reproduce (for bugs)

1. docker run -p 32770:5000 -d -P --name pokemongo-map -e "POKEMON_USERNAME=blah" -e "POKEMON_PASSWORD=blahblah" -e "POKEMON_LOCATION=whereIgo" -e "POKEMON_STEP_LIMIT=6" -e "POKEMON_GMAPS_KEY=SUPERSECRET" ashex/pokemongo-map:develop
2. docker logs pokemongo-maps
3.
4.

## Context

Running in a docker container on Mac, trying to get a small map

## Your Environment

* Version used: lastest development branch as of this issue
* Environment name and version (e.g. Python 2.7): 
* Operating System and version (desktop or mobile): boot2docker
see https://github.com/Ashex/pokemongo-map-docker

**Comment by invisiblek** [comment]
argh, this is my fault, one sec....

**Comment by invisiblek** [comment]
https://github.com/PokemonGoMap/PokemonGo-Map/commit/442dc528d95e843117f14bfcc95a5b09bb474355

Try re-syncing. You may need to drop your Pokestop table too (sorry about this)

Spent way too much time getting migrations from old db -> new db working that I slipped up and missed this bug on new database creation.

**Comment by SimplyArmin** [comment]
Also  gettings this error. Thought im doing something wrong :+1:

**Comment by romainhe** [comment]
I have the same issue...

Running on debian

**Comment by Damananth** [comment]
I had the same issue

How do i resynching?

**Comment by jonathanwcrane** [comment]
Thanks man, saw the latest commit.  Trying to re-run the container now (the docker image always pulls from the latest commit of the develop branch).

**Comment by jonathanwcrane** [comment]
Working again!  Thanks!

**Comment by jonathanwcrane** [comment]
I will say that the colors on the map for the search location circles are all wonky though.  Looks like autumn with all the yellows, oranges, and reds.  Not sure if it's related to recent changes,  probably should be a new issue.

Anyway the issue this #494 is about is solved.
