### ISSUE TITLE
cant find tag or branch - flask-cachebust.git

### ISSUE THREAD

**Issue by supradoc227** [PokemonGoMap/PokemonGo-Map#497]
Cloning https://github.com/ChrisTM/Flask-CacheBust.git (to aa09ad861f104f987928fe9f5107ccfe0e4473c3) to c:\users\xxx\appdata\local\temp\pip-build-jl__2w\flask-cachebust
  Could not find a tag or branch 'aa09ad861f104f987928fe9f5107ccfe0e4473c3', assuming commit.

I thought this was fixed but I still cant pull it from the requirements.txt. Catastrophic for me because I never had the old version so I cant run.

**Comment by marcmicalizzi** [comment]
That's not actually an error. Every time I have pip pull from git I get the exact same message but it's still fine.

**Comment by BaIthamel** [comment]
This is not a support forum; please see [the discord #help channel](https://discord.gg/npVqkUn) for assistance.
