### ISSUE TITLE
[Feature Request] 'Scanned Location' decay rate option

### ISSUE THREAD

**Issue by gyhughes** [PokemonGoMap/PokemonGo-Map#499]
I think that there should be an option to have the scanned locations change from color green to red a lot quicker. I usually scan small areas (radius 3) and it is all green all the time. I think that adding this feature would help trainers visualize their location better.

## Expected Behavior

Have dropdown/slider option in Options->Marker Settings->Scanned Locations. This would give the option to decay the circles using time limits other than the default 15min.

## Current Behavior

Default behavior has the scanned locations circles despawn after 15 minutes. The circles stay green for over 5 minutes. This feature would allow the user to speed these times up.

## Possible Solution

Inside `/static/js/map.js` ...
 - Add 'Decay Rate' range under 'Scanned Locations' UI option so the user can change the decay rate of the circles.
 - Modify `getColorByDate` function to use the value selected in the 'Decay Rate' range.

**Comment by DiscoTim** [comment]
even if it is just a config arg, I'm currently always changing this to 2 minutes.

**Comment by BaIthamel** [comment]
For feature requests please migrate this to the new feature page
http://feathub.com/PokemonGoMap/PokemonGo-Map/
Thankyou!
