### ISSUE TITLE
Loading "babel.js" tasks...ERROR

### ISSUE THREAD

**Issue by simple-lad** [PokemonGoMap/PokemonGo-Map#500]
I get an error when trying to run npm install.  I have windows 7, run cmd as administrator
Whats wrong?
```
Loading "babel.js" tasks...ERROR
>> Error: Cannot find module './_an-object'
```

**Comment by BaIthamel** [comment]
This is not a support forum; please see [the discord #help channel](https://discord.gg/npVqkUn) for assistance.
