### ISSUE TITLE
NOT NULL constraint failed: pokestop.encounter_id... Retrying

### ISSUE THREAD

**Issue by Damananth** [PokemonGoMap/PokemonGo-Map#501]
Just intalled a new dev build and after git pull the new update i am still getting the same error

2016-08-11 10:46:32,573 [ search_worker_0][ models][ WARNING] NOT NULL co
nstraint failed: pokestop.encounter_id... Retrying
2016-08-11 10:46:32,582 [ search_worker_0][ models][ WARNING] NOT NULL co
nstraint failed: pokestop.encounter_id... Retrying
2016-08-11 10:46:32,591 [ search_worker_0][ models][ WARNING] NOT NULL co
nstraint failed: pokestop.encounter_id... Retrying
2016-08-11 10:46:32,599 [ search_worker_0][ models][ WARNING] NOT NULL co
nstraint failed: pokestop.encounter_id... Retrying
2016-08-11 10:46:32,607 [ search_worker_0][ models][ WARNING] NOT NULL co

**Comment by jonathanwcrane** [comment]
See https://github.com/PokemonGoMap/PokemonGo-Map/issues/494

Please search existing issues first before opening a new one.  Thanks.

**Comment by Damananth** [comment]
I did look at it, see my comment in there.

I git pull it for the new updates and rerun it again but it still gave me the same error.

Did i skip a step or did something wrong?

**Comment by jonathanwcrane** [comment]
Did you pull the develop branch?  You might want to blow it away and try a new git clone.

**Comment by Damananth** [comment]
I will try a new git clone and see if it works

**Comment by Damananth** [comment]
Closed got it to work after creating a new git clone
