### ISSUE TITLE
Scanned locations colors too opaque/too red

### ISSUE THREAD

**Issue by jonathanwcrane** [PokemonGoMap/PokemonGo-Map#503]
## Expected Behavior
I expect the scanned location circles to be see-through light green and slowly fade to yellow, then orange->red over 15 minutes or so and to be able to see all map features through them (street names, etc)

## Current Behavior

The circles are very opaque and the color scheme has dark oranges in it in unexpected places

## Steps to Reproduce (for bugs)

1. docker run -p 32770:5000 -d -P --name pokemongo-map -e "POKEMON_USERNAME=blah" -e "POKEMON_PASSWORD=blahblah" -e "POKEMON_LOCATION=whereIgo" -e "POKEMON_STEP_LIMIT=6" -e "POKEMON_GMAPS_KEY=SUPERSECRET" ashex/pokemongo-map:develop

2.  Go to served web page
3.
4.

## Context
Running in a docker container on Mac, trying to get a small map

## 

Your Environment

Version used: lastest development branch as of this issue
Environment name and version (e.g. Python 2.7):
Operating System and version (desktop or mobile): boot2docker see https://github.com/Ashex/pokemongo-map-docker

**Comment by BaIthamel** [comment]
This is not a support forum; please see [the discord #help channel](https://discord.gg/npVqkUn) for assistance.

**Comment by jonathanwcrane** [comment]
![pokemongocolors](https://cloud.githubusercontent.com/assets/6143363/17595643/ca80d784-5fbb-11e6-963d-42563a0882d8.jpg)

**Comment by jonathanwcrane** [comment]
To be clear, this is a new issue that has come up due to recent updates to this repo; not a custom setting or anything.

**Comment by jonathanwcrane** [comment]
To report back, stopping and restarting the container fixed it.

**Comment by jonathanwcrane** [comment]
NVM after it runs for a while, the circles get more and more opaque.  @BaIthamel @invisiblek I truly believe this is a bug.  The issue is in the right format.  Can you confirm it's not a bug?  Thanks.

**Comment by antiroot** [comment]
This seems to be a result of commit 9203689, the scanned_id field of scannedlocation used to be a concat of latitude+longitude and this is used as a key for the circle markers on the map. After this commit this field is now an auto incrementing primary key and the map just keeps appending new markers because all of the keys are unique now

**Comment by jonathanwcrane** [comment]
Thanks @antiroot good fine.  I hope @BaIthamel and/or @invisiblek would re-open since this all but confirms it's a bug.

**Comment by invisiblek** [comment]
fml

**Comment by jonathanwcrane** [comment]
Having a bad day, @invisiblek ?  👿

**Comment by invisiblek** [comment]
its just adding new records forever, not updating the old =/

**Comment by jonathanwcrane** [comment]
Yeah which is fine for the first pass or so, but as they start adding up it gets so opaque you can't see the map under it.

I'd love to know why some of them turn orange, but as long as you fix it I'll be happy.  😄

**Comment by invisiblek** [comment]
i'm not really in love with this patch...there should be an easier way to handle this...

https://github.com/PokemonGoMap/PokemonGo-Map/pull/511
