### ISSUE TITLE
Feature request : possibility to delete scanned zone

### ISSUE THREAD

**Issue by alachmann** [PokemonGoMap/PokemonGo-Map#510]
Hi
It will be nice if we can erase scanned zone since when you move, it becomes unreadable
Thanks

**Comment by acanuto** [comment]
Yes please

**Comment by BaIthamel** [comment]
Unreadable how? do you turn off show scanned locations? Those green/red circles are more of a debug tool.
I'm going to say please see [the discord #help channel](https://discord.gg/npVqkUn) for assistance.
There's probably a solution you can do that doesn't involve adding a feature the rest of us don't want.
