### ISSUE TITLE
jquery post 404 error

### ISSUE THREAD

**Issue by kwabbernoot** [PokemonGoMap/PokemonGo-Map#512]
## Expected Behavior
When i insert a location in Location Settings by: "scan location" is should move the scanner to the given location or with Scan follows location, Start at user's location on.

## Current Behavior
Got an error in Chrome console:
![](http://i.imgur.com/VH45BBl.png)
And nothing happens when i insert a location by scan location, even when i turn Scan follows location or Start at user's location on.
Search also not working. (also 404 jquery error)

## Steps to Reproduce (for bugs)

1. python runserver.py
2. Open browser to map
3. Insert by scan location a location, or turn Scan follows location,Start at user's location or search on.
4. jquery post error 404

## Your Environment

* Version used: Develop branch
* Python version:  2.7
* Server software: Centos 7
* problem found with: safari for ios (with gps), firefox for windows (without gps), google chrome for windows (without gps).

**Comment by BaIthamel** [comment]
This is not a support forum; please see [the discord #help channel](https://discord.gg/npVqkUn) for assistance.
