### ISSUE TITLE
(fix provided) active_fort_modifier - referenced before assignment

### ISSUE THREAD

**Issue by g5bEM6RpSbQF** [PokemonGoMap/PokemonGo-Map#515]
Getting this error on git commit 83fab06

2016-08-11 19:20:13,832 [ search_worker_0][ search][ ERROR] Exception in search_worker: local variable 'active_fort_modifier' referenced before assignment. Username: xxxxxx
Traceback (most recent call last):
File "/home/ubuntu/PokemonGo-Map/pogom/search.py", line 247, in search_worker_thread
parse_map(response_dict, step_location)
File "/home/ubuntu/PokemonGo-Map/pogom/models.py", line 367, in parse_map
'active_fort_modifier': active_fort_modifier,
UnboundLocalError: local variable 'active_fort_modifier' referenced before assignment

**Comment by g5bEM6RpSbQF** [comment]
This fixes the issue:

$ git diff
diff --git a/pogom/models.py b/pogom/models.py
index 0355dd2..e18d050 100755
--- a/pogom/models.py
+++ b/pogom/models.py
@@ -345,11 +345,12 @@ def parse_map(map_dict, step_location):
                 if 'active_fort_modifier' in f:
                     lure_expiration = datetime.utcfromtimestamp(
                         f['last_modified_timestamp_ms'] / 1000.0) + timedelta(minutes=30)
+                    active_fort_modifier = f['active_fort_modifier']
                     webhook_data = {
                         'latitude': f['latitude'],
                         'longitude': f['longitude'],
                         'last_modified_time': f['last_modified_timestamp_ms'],
-                        'active_fort_modifier': f['active_fort_modifier'],
+                        'active_fort_modifier': active_fort_modifier,
                         'is_lured': True
                     }
                     send_to_webhook('pokemon', webhook_data)

**Comment by austinxw** [comment]
Could you provide the steps that how to fix this problem exactly?

"Exception in search_worker: local variable 'active_fort_modifier' referenced before assignment"

**Comment by daproject85** [comment]
will this be checked in?

**Comment by jonathanwcrane** [comment]
I'm getting this error intermittently, like maybe every 30 scans or so, with 10 accounts.

**Comment by ftheman2** [comment]
"C:\Python27\python.exe" runserver.py -a ptc -u xxxx -p xxxx -l "-33.87020868443789 151.2025669003497" -st 5 -H 0.0.0.0 -k xxxxx

"C:\Python27\python.exe" runserver.py -a ptc -u xxxx -p xxxx -l "-33.930495086361276 151.1240677055552" -st 5 -H 0.0.0.0 -k xxxxx


It happens  when I try the location number 1 but not with location number 2...
so it should be linked to specific locations or objects within those locations.
