### ISSUE TITLE
Scan fails with KeyError 'map_cells'

### ISSUE THREAD

**Issue by jbogatchenko** [PokemonGoMap/PokemonGo-Map#517]
Getting following error, map shows but no pokemon( or anything)

2016-08-11 15:29:22,561 [ search_worker_0][        search][   ERROR] Search step
 1 map parsing failed, retrying request in 50 seconds
Traceback (most recent call last):
  File "F:\PokemonGomap\pogom\search.py", line 247, in search_worker_thread
    parse_map(response_dict, step_location)
  File "F:\PokemonGomap\pogom\models.py", line 311, in parse_map
    cells = map_dict['responses']['GET_MAP_OBJECTS']['map_cells']
KeyError: 'map_cells'

Env. Windows 7 64 bit desktop, Python 2.7

**Comment by RatedDS** [comment]
You need to accept the TOS for the account(s) you're using.

**Comment by ilendemli** [comment]
Check your accounts, they may be expired, accepting TOS is not enough and will only last 2 days. You have to active them too through the mail you receive when you create the account.

**Comment by ovkhan** [comment]
not TOS related, downloaded latest version (with lure pokestop fix) and got the same problem.
Old version, with exact same command line ... no problems.

**Comment by cdhowie** [comment]
Tried on fresh accounts, accepted TOS + email verified, also getting this error.

**Comment by schwtyl** [comment]
Last night, fresh PTC accounts worked after email verification and accepting TOS. However, any new accounts I create today do not work (though last night's accounts are still working fine). I suspect they added an additional check today...

**Comment by jbogatchenko** [comment]
Thanks for help. I accepted TOS and played through the intro. Logged out and now the map works. Btw, I have python 2.7.3 and it is fine.

**Comment by schwtyl** [comment]
Update:

Last night, I'd accepted the TOS via PokemonGo-DesktopMap, and it worked.  Today, I tried some through there, and some through the Pokemon Trainer Club website - neither was successful (though marked the TOS as complete, i.e. the website no longer let me accept it)

However, I was able to get them working just now using https://github.com/Infernoman/PoGoTos - super simple, hooray!
