### ISSUE TITLE
Cannot find command 'git'

### ISSUE THREAD

**Issue by MaxGriswald** [PokemonGoMap/PokemonGo-Map#524]
## Current Behavior
Collecting pgoapi from git+https://github.com/keyphact/pgoapi.git#egg=pgoapi (from -r requirements.txt (line 18))
  Cloning https://github.com/keyphact/pgoapi.git to c:\users\xxxxxx\appdata\local\temp\pip-build-vqhlyf\pgoapi
  Error [Error 2] The system cannot find the file specified while executing command git clone -q https://github.com/keyphact/pgoapi.git c:\users\xxxxxx\appdata\local\temp\pip-build-vqhlyf\pgoapi
Cannot find command 'git'

## Context
Trying to run "pip install -r requirements.txt"

## Your Environment
Version 2.2.0 (Supposed to be the latest stable version)
Python 2.7
Windows 10

**Comment by jtp10181** [comment]
Did you install git? See the requirements

https://pgm.readthedocs.io/en/develop/basic-install/windows.html

**Comment by MaxGriswald** [comment]
I'm an idiot.  I downloaded the .exe but forgot to run the installation.  Got sidetracked when it started to rain :(  Can I remove this issue?

**Comment by aldarund** [comment]
Do you read issue template? Its not a support forum. Go discord

**Comment by jabberjabber** [comment]
Read the wiki

**Comment by Yossi** [comment]
git exists between keyboard and chair

**Comment by BaIthamel** [comment]
This is not a support forum; please see [the discord #help channel](https://discord.gg/npVqkUn) for assistance.
