### ISSUE TITLE
Getting Christmas Tree Look In Latest DEV.

### ISSUE THREAD

**Issue by rrbailey89** [PokemonGoMap/PokemonGo-Map#533]
## Expected Behavior

In previous versions the christmass tree has not been seen. Each circle should appear green in color when using -st 3 and 3 accounts per worker. 
## Current Behavior

See screenshot below
![](http://i.imgur.com/lYxaQIg.png)

## Possible Solution

I honestly dont know im not a coder.
## Steps to Reproduce (for bugs)

1.Run latest dev with -st 3 and 2 or 3 accounts per worker

## Context

It appears on the map as if scans are super old and not updated. Not sure if its actually scanning those areas.
## Your Environment

* Version used: lateest dev
* Environment name and version (e.g. Python 2.7): Python 2.7
* Operating System and version (desktop or mobile): Windows Desktop and Android 7 Mobile

**Comment by johnkernke** [comment]
see #503
