### ISSUE TITLE
config.ini password cannot handle semi-colons

### ISSUE THREAD

**Issue by Hackswell** [PokemonGoMap/PokemonGo-Map#534]
## Expected Behavior
PGM should log the user into their PTC account regardless of what special characters are in their password.  For users with special chars, it's easier to put them in the .ini file rather than on command line (and more secure)

## Current Behavior
My PTC account has a password with semi-colons in it [ ; ]. When logging in, I get the following error:
runserver.py: error: Unexpected line 4 in /data/home/woody/tmp/PokemonGo-Map/pogom/../config/config.ini: password: XYZZY;;YZZYX/.,

## Possible Solution
Escape special punctuation characters.

## Steps to Reproduce (for bugs)
1. in config.ini file: (for ptc user/password)
password: XYZZY;;YZZYX/.,
2. Run runserver.py
3. Error starting the script:
runserver.py: error: Unexpected line 4 in /data/home/woody/tmp/PokemonGo-Map/pogom/../config/config.ini: password: XYZZY;;YZZYX/.,
4. No Profit.

## Context
Trying to log-in with a brand new PTC account with strong password.

## Your Environment

* Version used: HEAD on git repos. (2016-08-11)
* Environment name and version (e.g. Python 2.7): python 2.7.12
* Operating System and version (desktop or mobile): linux ubuntu 16.04 desktop

**Comment by ZankerZCT** [comment]
Did you put double quote on password?

**Comment by DiscoTim** [comment]
it's a limitation of ConfigArgParse, the file can't contain # or ; except as comments.

https://github.com/bw2/ConfigArgParse/issues/60
