### ISSUE TITLE
Pokemon is not appearing on scanned maps.

### ISSUE THREAD

**Issue by ZankerZCT** [PokemonGoMap/PokemonGo-Map#537]
It seems to be similar issue when Niantic updated the API or something. Can anyone confirm this?

**Comment by delenca** [comment]
Seems they IP ban for running either too fast scans or too many. For 5 workers mine get banned in around 3 mins.

**Comment by Dagothur** [comment]
@delenca how many accounts per worker and what is -sd?

**Comment by FrostTheFox** [comment]
This is not an API issue. For support, please use the discord server at https://discord.gg/uAmEkcu

**Comment by delenca** [comment]
@FrostTheFox SD and multiple accounts per workers don't work for me since the new api.
They just give constant parsing errors.
