### ISSUE TITLE
[Feature Request] Spawnpoint analysis

### ISSUE THREAD

**Issue by khag7** [PokemonGoMap/PokemonGo-Map#538]
Currently the best "analysis" option is to look at heatmaps for individual pokemon.

A feature which will actually be more useful is to calculate the weighted table of pokemon at each spawnpoint or for a group of spawnpoints in a certain area.

For example: I want to be able to select 3 spawnpoints within reach of my home and see something like:
60% Pidgey, 20% Weedle, 10% Ratatta, etc.

Once this is implemented we could take it a step further and say "Show me spawnpoints with unusually disproportionate distribution" which would show things like spawnpoints which spawn Squirtle 25% of the time or points which spawn a higher percentage of "rare" pokemon. 

Of course, these percentages will only be useful after several days of scanning over the same spawnpoints. And the majority of spawns will have similar weighted tables. But the important part will be the ability to highlight those spawnpoints which deviate the most from the others.

I know this type of analysis is not the main goal of this project, but as this is the most used mapping app there are many people who would benefit from this feature.

**Comment by hannahbanana** [comment]
There are already a few apps that do this - I use Pokelyzer
 https://github.com/Brideau/pokelyzer

**Comment by khag7** [comment]
@hannahbanana I disagree. Pokelyzer is just a database. PokemonGoMap already has a database. Pokelyzer doesn't do any analysis whatsoever. Tableau and Power Bi can do analysis of data, and work great with the pokelyzer database, but pokelyzer itself does no analysis, and I'm not too savvy with the tools and tutorials I've read on how to use pokelyzer to get more information.

I don't need another database option. I was thinking it would be cool if there was a report page in PokemonGoMap that used this database and ran some sort of analysis that pointed out spawnpoints which are clearly weighted differently than the rest. Data like this would make it as obvious as saying, "hey yo check out this park its got so many spawnpoints weighted differently than anywhere else in your area"

**Comment by snapper67** [comment]
I have added a pull request that I think addresses this.
https://github.com/PokemonGoMap/PokemonGo-Map/pull/571

**Comment by FrostTheFox** [comment]
Please direct feature requests to http://feathub.com/PokemonGoMap/PokemonGo-Map

**Comment by khag7** [comment]
Thanks @snapper67 

@FrostTheFox  where is this documented? never saw that link before.

**Comment by math1985** [comment]
https://github.com/math1985/pokemon-go-tools is a first step towards doing analysis based on PokemonGoMap.
