### ISSUE TITLE
Webhook Endpoint

### ISSUE THREAD

**Issue by khag7** [PokemonGoMap/PokemonGo-Map#542]
Would it be useful to have the PokemonGo-Map web server act as an endpoint to receive data from other mapping applications? I was thinking of trying out TBTerra's spawnTracker but it has no visualization options. There is a PR on that repo that is for webhook support, so assuming that gets merged I want to test his scanning method out and put the data into my existing PokemonGo-Map database. If we added an incoming webhook that would make it easy to do.

**Comment by antiroot** [comment]
It might just be me, but allowing third parties to insert data into your database sounds like a huge security concern. Even with a white list only setup, there's no guarantee that their data is actually valid

**Comment by khag7** [comment]
Well yeah. I'm not asking so I can give it to strangers. I was just thinking it might be nice to try out some other map scanners for performance tests. I can run those scanners and just lose that data, or I can have it fed to PokemonGo-Map and it will be saved.

For now I'm using pokelyzer as well to collect data, so its not a total loss, but I'd rather ditch pokelyzer and just use the db from this project since you guys have heatmaps built in. 

I think the big picture here is that you should stop seeing yourselves as a scanner only. You also have a database and a heatmap viewer. Some people might want to use other scanners and only use your webserver for the viewing portion of things.

**Comment by BaIthamel** [comment]
For feature requests please migrate this to the new feature page
http://feathub.com/PokemonGoMap/PokemonGo-Map/
Thankyou!
