### ISSUE TITLE
Old vs new search algorithm: New one not picking up all Pokemon

### ISSUE THREAD

**Issue by larsschwarz** [PokemonGoMap/PokemonGo-Map#544]
I have multiple servers running for the same area. Some of them still use an older version (the one with the lure bug). Comparing both version shows that the old algorithm (circle steps) finds more Pokemon than the newer one. For an "all green" area of st 14 the difference is like 130 for the old algorithm vs 70 for the new algorithm. 

Even when I start both scans at the same time, looking at the currently scanned steps/areas there is a difference. 

There doesn't seem to be a pattern, it's completely mixed. Even within currently scanned 70m radius the one scanner finds two Spearow where the new algorithm only finds one for example. But also single occurrences are different (some Pokemon only visible once in the scanned area do not appear in the new version).

Comparing this for a few hours new sometimes the difference is huge (new version only finds half of the number the older version finds). 

I'd love an option that allows switching the scanning algorithms so you could validate this is an issue with the new algorithm or not. 

What would be a good way to track down the differences in both versions (no code-wise, but scanning results-wise)?

**Comment by BaIthamel** [comment]
Screenshots? Server logs? Document your stuff.

**Comment by GenuineSounds** [comment]
@BaIthamel Nah, we don't do that here...

**Comment by larsschwarz** [comment]
GenuineSounds: What do you expect those screenshots to show? Probably that what I wrote? One showing 70 Pokemon the other 130 for the same area, time and scan positions. That would help I guess. What "server logs"? Search worker cli output? How would that help?

**Comment by blump** [comment]
same feeling

**Comment by brettgus** [comment]
@larsschwarz Are you sure that this isn't related to some of the throttling that Ninantic has been doing?

**Comment by mdnpascual** [comment]
From what I observed, the new algorithm does not show pokemon that are spawned by lured pokestops that's why it feels it showing less pokemons

**Comment by Newbiehere2** [comment]
I ve experienced the same, normally i scan a urban place, always around 50-60 pokemon in that scan and with this algorithm, it ways faster but its showing about 20-30 pokemons (50%) after some time like 10 min it shows pokemons(60%ich) which are 2 minutes froms despawn.
