### ISSUE TITLE
Bot error speed 

### ISSUE THREAD

**Issue by Tagada22** [PokemonGoMap/PokemonGo-Map#545]
Hello 

I have problems with my config.

when i launch bot i have speed text with many error non stop. I paste a copy 

_ssl.c:504: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed. Username: lxxxx@gmail.com
Traceback (most recent call last):
��File "/home/PokemonGo-Map/pogom/search.py", line 230, in search_worker_thread
  ��check_login(args, account, api, step_location)
��File "/home/PokemonGo-Map/pogom/search.py", line 283, in check_login
����api.set_authentication(provider=account['auth_service'], username=account['username'], password=account['password'])
��File "/usr/local/lib/python2.7/dist-packages/pgoapi/pgoapi.py", line 89, in set_authentication
  ��self._auth_provider.user_login(username, password)
��File "/usr/local/lib/python2.7/dist-packages/pgoapi/auth_google.py", line 55, in user_login
����user_login = perform_master_login(username, password, self.GOOGLE_LOGIN_ANDROID_ID)
��File "/usr/local/lib/python2.7/dist-packages/gpsoauth/__init__.py", line 66, in perform_master_login
  ��return _perform_auth_request(data)
��File "/usr/local/lib/python2.7/dist-packages/gpsoauth/__init__.py", line 22, in _perform_auth_request
  ��headers={'User-Agent': useragent})
��File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 111, in post
����return request('post', url, data=data, json=json, **kwargs) 
��File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 57, in request
  ��return session.request(method=method, url=url, **kwargs)
��File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 475, in request
  ��resp = self.send(prep, **send_kwargs)
��File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 585, in send
  ��r = adapter.send(request, **kwargs)
��File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 477, in send
����raise SSLError(e, request=request)
SSLError: [Errno 1] _ssl.c:504: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
2016-08-12 09:08:31,176 [ search_worker_0][��������search][    INFO] Search step 343 beginning (queue size is 798)
2016-08-12 09:08:31,176 [ search_worker_0][   auth_google][

I'm completely lost and i don't know how to fix that.

Have you got an idea please ? 

Thanks

**Comment by Yossi** [comment]
you probably want to remove your email from that log, or that account is toast. if it isn't already.

**Comment by Tagada22** [comment]
My email are good i have 30 account and its working yesterday

**Comment by Foxbond** [comment]
@Tagada22 remove e-mail from log or ur accounts will be banned in few hours

**Comment by Tagada22** [comment]
Ok i test my account and not banned 

I enter new account so ?

**Comment by Tagada22** [comment]
So i fix this problems now i have other 


] PTC User Login successful.
2016-08-12 15:38:23,788 [search_worker_27][      auth_ptc][    INFO] Request PTC Access Token...
2016-08-12 15:38:23,928 [search_worker_27][      auth_ptc][    INFO] PTC Access Token successfully retrieved.
2016-08-12 15:38:23,938 [search_worker_27][        search][ WARNING] Exception while downloading map: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.14' not found (required by /home/PokemonGo-Map/pogom/libencrypt/libencrypt-linux-x86-64.so)
2016-08-12 15:38:23,938 [search_worker_27][        search][   ERROR] Search step 28 area download failed, retrying request in 20 seconds
