### ISSUE TITLE
[Feature Request] Add hide or notify pokemon in config.ini

### ISSUE THREAD

**Issue by adiramardiani** [PokemonGoMap/PokemonGo-Map#546]
I think is very usefull if a feature hide or notify pokemon added in configuration
Maybe with pokemon code or pokemon name

Like 

# Search settings
hide-pokemon : [10, 13, 16]
notify-pokemon : [26, 115]

**Comment by HeyItsJono** [comment]
This would be a great feature to see, it would save me having to type out the list of almost all the Pokemon on each of my devices.
