### ISSUE TITLE
Google Maps locate button

### ISSUE THREAD

**Issue by nicktan147** [PokemonGoMap/PokemonGo-Map#550]
Is there something wrong with google maps locate button? I tried clicking it, it doesn't locate my location, I have to search via search box. Any idea why?

**Comment by johnkernke** [comment]
You need a secure connection to be able to use this (meaning you need https://).

**Comment by nicktan147** [comment]
@johnkernke Thank. I will try then update here later.

**Comment by totoberg123** [comment]
How can you install a SSL Certificate on this ?

**Comment by johnkernke** [comment]
#480 or http://pgm.readthedocs.io/en/develop/extras/nginx.html

**Comment by nicktan147** [comment]
@johnkernke Any guide to install lets encrypt for apache?

**Comment by johnkernke** [comment]
http://lmgtfy.com/?q=install+lets+encrypt+for+apache

**Comment by nicktan147** [comment]
@johnkernke I did... just that when I try to setup it doesn't work well.
You can try access via both these links

https://pokeaware.com
http://pokeaware.com

Both are showing different contents

**Comment by johnkernke** [comment]
You need to setup a reverse proxy from Apache to the maps under the HTTPS section, just like you would have for the regular HTTP.

Also I haven't used Apache in years (nginx is a lot better), so I probably wont be able to help you much. But it might be nice to post your configs (please use \`\`\` around them to display it nicely) and then others might be able to help.

**Comment by BaIthamel** [comment]
This is not a support forum; please see [the discord #help channel](https://discord.gg/npVqkUn) for assistance.
