### ISSUE TITLE
Request: change notify option to switch on pokemon 'infocard' on map

### ISSUE THREAD

**Issue by UwV2000** [PokemonGoMap/PokemonGo-Map#551]
Not sure what i should call it so i will refer to it as  'infocard'
meaning the popup when hovering over clicking a pokemon on the map.

## Expected Behavior

It would be nice if the notify on the infocard  would be a on/off switch

## Current Behavior
Notify  on infocard works as on switch only

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

Would be nice to have

**Comment by sLoPPydrive** [comment]
If it was a toggle switch and you would turn notifications for this Pokémon off you might still get notifications because you have "notify by rarity" enabled, so it would confuse users ("why doesn't this work?").

Wouldn't vote for it.

**Comment by UwV2000** [comment]
@ sLoPPydrive 
that all depends on how its implemented.
i see no reason why it cant be made so it will work. 
like you say .. "you might still get.. "   i guess.. if done right we won't.   so vote for it already ;)

**Comment by BaIthamel** [comment]
For feature requests please migrate this to the new feature page
http://feathub.com/PokemonGoMap/PokemonGo-Map/
Thankyou!
