### ISSUE TITLE
Errors when install the requirements

### ISSUE THREAD

**Issue by xie-qianyue** [PokemonGoMap/PokemonGo-Map#553]
I have the following error when runing the command `sudo -H pip install -r requirements.txt`, in Ubuntu

Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-Uc4aD7/pyproj/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-3vEMZy-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-Uc4aD7/pyproj/

Here is a part of the error logs, because it's too long, I don't get all of the logs here.

    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Isrc -I/usr/include/python2.7 -c src/pj_ellps.c -o build/temp.linux-x86_64-2.7/src/pj_ellps.o
    In file included from src/projects.h:292:0,
                     from src/pj_ellps.c:3:
    src/proj_api.h:147:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
     projFileAPI *pj_get_default_fileapi();
     ^
    In file included from src/pj_ellps.c:3:0:
    src/projects.h:486:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
     void pj_deallocate_grids();
     ^
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Isrc -I/usr/include/python2.7 -c src/PJ_sts.c -o build/temp.linux-x86_64-2.7/src/PJ_sts.o
    In file included from src/projects.h:292:0,
                     from src/PJ_sts.c:5:
    src/proj_api.h:147:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
     projFileAPI *pj_get_default_fileapi();
     ^
    In file included from src/PJ_sts.c:5:0:
    src/projects.h:486:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
     void pj_deallocate_grids();
     ^
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Isrc -I/usr/include/python2.7 -c src/PJ_ocea.c -o build/temp.linux-x86_64-2.7/src/PJ_ocea.o
    In file included from src/projects.h:292:0,
                     from src/PJ_ocea.c:9:
    src/proj_api.h:147:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
     projFileAPI *pj_get_default_fileapi();
     ^
    In file included from src/PJ_ocea.c:9:0:
    src/projects.h:486:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
     void pj_deallocate_grids();
     ^
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Isrc -I/usr/include/python2.7 -c src/PJ_omerc.c -o build/temp.linux-x86_64-2.7/src/PJ_omerc.o
    In file included from src/projects.h:292:0,
                     from src/PJ_omerc.c:29:
    src/proj_api.h:147:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
     projFileAPI *pj_get_default_fileapi();
     ^
    In file included from src/PJ_omerc.c:29:0:
    src/projects.h:486:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
     void pj_deallocate_grids();
     ^
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Isrc -I/usr/include/python2.7 -c src/PJ_ob_tran.c -o build/temp.linux-x86_64-2.7/src/PJ_ob_tran.o
    In file included from src/projects.h:292:0,
                     from src/PJ_ob_tran.c:6:
    src/proj_api.h:147:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
     projFileAPI *pj_get_default_fileapi();
     ^
    In file included from src/PJ_ob_tran.c:6:0:
    src/projects.h:486:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
     void pj_deallocate_grids();
     ^
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Isrc -I/usr/include/python2.7 -c src/PJ_robin.c -o build/temp.linux-x86_64-2.7/src/PJ_robin.o
    In file included from src/projects.h:292:0,
                     from src/PJ_robin.c:2:
    src/proj_api.h:147:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
     projFileAPI *pj_get_default_fileapi();
     ^
    In file included from src/PJ_robin.c:2:0:
    src/projects.h:486:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
     void pj_deallocate_grids();
     ^
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Isrc -I/usr/include/python2.7 -c src/pj_gridcatalog.c -o build/temp.linux-x86_64-2.7/src/pj_gridcatalog.o
    In file included from src/projects.h:292:0,
                     from src/pj_gridcatalog.c:30:
    src/proj_api.h:147:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
     projFileAPI *pj_get_default_fileapi();
     ^
    In file included from src/pj_gridcatalog.c:30:0:
    src/projects.h:486:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
     void pj_deallocate_grids();
     ^
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Isrc -I/usr/include/python2.7 -c src/pj_log.c -o build/temp.linux-x86_64-2.7/src/pj_log.o
    In file included from src/projects.h:292:0,
                     from src/pj_log.c:28:
    src/proj_api.h:147:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
     projFileAPI *pj_get_default_fileapi();
     ^
    In file included from src/pj_log.c:28:0:
    src/projects.h:486:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
     void pj_deallocate_grids();
     ^
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Isrc -I/usr/include/python2.7 -c src/PJ_lsat.c -o build/temp.linux-x86_64-2.7/src/PJ_lsat.o
    In file included from src/projects.h:292:0,
                     from src/PJ_lsat.c:6:
    src/proj_api.h:147:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
     projFileAPI *pj_get_default_fileapi();
     ^
    In file included from src/PJ_lsat.c:6:0:
    src/projects.h:486:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
     void pj_deallocate_grids();
     ^
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Isrc -I/usr/include/python2.7 -c src/pj_datums.c -o build/temp.linux-x86_64-2.7/src/pj_datums.o
    In file included from src/projects.h:292:0,
                     from src/pj_datums.c:30:
    src/proj_api.h:147:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
     projFileAPI *pj_get_default_fileapi();
     ^
    In file included from src/pj_datums.c:30:0:
    src/projects.h:486:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
     void pj_deallocate_grids();
     ^
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Isrc -I/usr/include/python2.7 -c src/PJ_bonne.c -o build/temp.linux-x86_64-2.7/src/PJ_bonne.o
    In file included from src/projects.h:292:0,
                     from src/PJ_bonne.c:8:
    src/proj_api.h:147:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
     projFileAPI *pj_get_default_fileapi();
     ^
    In file included from src/PJ_bonne.c:8:0:
    src/projects.h:486:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
     void pj_deallocate_grids();
     ^
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Isrc -I/usr/include/python2.7 -c src/PJ_sterea.c -o build/temp.linux-x86_64-2.7/src/PJ_sterea.o
    In file included from src/projects.h:292:0,
                     from src/PJ_sterea.c:33:
    src/proj_api.h:147:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
     projFileAPI *pj_get_default_fileapi();
     ^
    In file included from src/PJ_sterea.c:33:0:
    src/projects.h:486:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
     void pj_deallocate_grids();
     ^
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Isrc -I/usr/include/python2.7 -c src/PJ_poly.c -o build/temp.linux-x86_64-2.7/src/PJ_poly.o
    In file included from src/projects.h:292:0,
                     from src/PJ_poly.c:5:
    src/proj_api.h:147:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
     projFileAPI *pj_get_default_fileapi();
     ^
    In file included from src/PJ_poly.c:5:0:
    src/projects.h:486:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
     void pj_deallocate_grids();
     ^
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Isrc -I/usr/include/python2.7 -c src/PJ_putp4p.c -o build/temp.linux-x86_64-2.7/src/PJ_putp4p.o
    In file included from src/projects.h:292:0,
                     from src/PJ_putp4p.c:4:
    src/proj_api.h:147:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
     projFileAPI *pj_get_default_fileapi();
     ^
    In file included from src/PJ_putp4p.c:4:0:
    src/projects.h:486:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
     void pj_deallocate_grids();
     ^
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Isrc -I/usr/include/python2.7 -c src/pj_fwd.c -o build/temp.linux-x86_64-2.7/src/pj_fwd.o
    In file included from src/projects.h:292:0,
                     from src/pj_fwd.c:3:
    src/proj_api.h:147:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
     projFileAPI *pj_get_default_fileapi();
     ^
    In file included from src/pj_fwd.c:3:0:
    src/projects.h:486:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
     void pj_deallocate_grids();
     ^
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Isrc -I/usr/include/python2.7 -c src/PJ_somerc.c -o build/temp.linux-x86_64-2.7/src/PJ_somerc.o
    In file included from src/projects.h:292:0,
                     from src/PJ_somerc.c:4:
    src/proj_api.h:147:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
     projFileAPI *pj_get_default_fileapi();
     ^
    In file included from src/PJ_somerc.c:4:0:
    src/projects.h:486:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
     void pj_deallocate_grids();
     ^
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Isrc -I/usr/include/python2.7 -c src/PJ_tcc.c -o build/temp.linux-x86_64-2.7/src/PJ_tcc.o
    In file included from src/projects.h:292:0,
                     from src/PJ_tcc.c:5:
    src/proj_api.h:147:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
     projFileAPI *pj_get_default_fileapi();
     ^
    In file included from src/PJ_tcc.c:5:0:
    src/projects.h:486:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
     void pj_deallocate_grids();
     ^
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Isrc -I/usr/include/python2.7 -c src/PJ_august.c -o build/temp.linux-x86_64-2.7/src/PJ_august.o
    In file included from src/projects.h:292:0,
                     from src/PJ_august.c:2:
    src/proj_api.h:147:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
     projFileAPI *pj_get_default_fileapi();
     ^
    In file included from src/PJ_august.c:2:0:
    src/projects.h:486:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
     void pj_deallocate_grids();
     ^
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Isrc -I/usr/include/python2.7 -c src/PJ_laea.c -o build/temp.linux-x86_64-2.7/src/PJ_laea.o
    In file included from src/projects.h:292:0,
                     from src/PJ_laea.c:13:
    src/proj_api.h:147:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
     projFileAPI *pj_get_default_fileapi();
     ^
    In file included from src/PJ_laea.c:13:0:
    src/projects.h:486:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
     void pj_deallocate_grids();
     ^
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Isrc -I/usr/include/python2.7 -c src/PJ_hatano.c -o build/temp.linux-x86_64-2.7/src/PJ_hatano.o
    In file included from src/projects.h:292:0,
                     from src/PJ_hatano.c:2:
    src/proj_api.h:147:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
     projFileAPI *pj_get_default_fileapi();
     ^
    In file included from src/PJ_hatano.c:2:0:
    src/projects.h:486:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
     void pj_deallocate_grids();
     ^
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Isrc -I/usr/include/python2.7 -c src/PJ_lagrng.c -o build/temp.linux-x86_64-2.7/src/PJ_lagrng.o
    In file included from src/projects.h:292:0,
                     from src/PJ_lagrng.c:7:
    src/proj_api.h:147:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
     projFileAPI *pj_get_default_fileapi();
     ^
    In file included from src/PJ_lagrng.c:7:0:
    src/projects.h:486:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
     void pj_deallocate_grids();
     ^
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Isrc -I/usr/include/python2.7 -c src/PJ_urmfps.c -o build/temp.linux-x86_64-2.7/src/PJ_urmfps.o
    In file included from src/projects.h:292:0,
                     from src/PJ_urmfps.c:4:
    src/proj_api.h:147:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
     projFileAPI *pj_get_default_fileapi();
     ^
    In file included from src/PJ_urmfps.c:4:0:
    src/projects.h:486:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
     void pj_deallocate_grids();
     ^
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Isrc -I/usr/include/python2.7 -c src/PJ_gins8.c -o build/temp.linux-x86_64-2.7/src/PJ_gins8.o
    In file included from src/projects.h:292:0,
                     from src/PJ_gins8.c:2:
    src/proj_api.h:147:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
     projFileAPI *pj_get_default_fileapi();
     ^
    In file included from src/PJ_gins8.c:2:0:
    src/projects.h:486:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
     void pj_deallocate_grids();
     ^
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Isrc -I/usr/include/python2.7 -c src/PJ_mbt_fps.c -o build/temp.linux-x86_64-2.7/src/PJ_mbt_fps.o
    In file included from src/projects.h:292:0,
                     from src/PJ_mbt_fps.c:2:
    src/proj_api.h:147:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
     projFileAPI *pj_get_default_fileapi();
     ^
    In file included from src/PJ_mbt_fps.c:2:0:
    src/projects.h:486:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
     void pj_deallocate_grids();
     ^
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Isrc -I/usr/include/python2.7 -c src/PJ_vandg2.c -o build/temp.linux-x86_64-2.7/src/PJ_vandg2.o
    In file included from src/projects.h:292:0,
                     from src/PJ_vandg2.c:6:
    src/proj_api.h:147:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
     projFileAPI *pj_get_default_fileapi();
     ^
    In file included from src/PJ_vandg2.c:6:0:
    src/projects.h:486:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
     void pj_deallocate_grids();
     ^
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Isrc -I/usr/include/python2.7 -c src/PJ_merc.c -o build/temp.linux-x86_64-2.7/src/PJ_merc.o
    In file included from src/projects.h:292:0,
                     from src/PJ_merc.c:2:
    src/proj_api.h:147:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
     projFileAPI *pj_get_default_fileapi();
     ^
    In file included from src/PJ_merc.c:2:0:
    src/projects.h:486:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
     void pj_deallocate_grids();
     ^
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Isrc -I/usr/include/python2.7 -c src/pj_open_lib.c -o build/temp.linux-x86_64-2.7/src/pj_open_lib.o
    In file included from src/projects.h:292:0,
                     from src/pj_open_lib.c:32:
    src/proj_api.h:147:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
     projFileAPI *pj_get_default_fileapi();
     ^
    In file included from src/pj_open_lib.c:32:0:
    src/projects.h:486:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
     void pj_deallocate_grids();
     ^
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Isrc -I/usr/include/python2.7 -c src/PJ_eck2.c -o build/temp.linux-x86_64-2.7/src/PJ_eck2.o
    In file included from src/projects.h:292:0,
                     from src/PJ_eck2.c:2:
    src/proj_api.h:147:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
     projFileAPI *pj_get_default_fileapi();
     ^
    In file included from src/PJ_eck2.c:2:0:
    src/projects.h:486:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
     void pj_deallocate_grids();
     ^
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Isrc -I/usr/include/python2.7 -c src/pj_gridinfo.c -o build/temp.linux-x86_64-2.7/src/pj_gridinfo.o
    In file included from src/projects.h:292:0,
                     from src/pj_gridinfo.c:31:
    src/proj_api.h:147:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
     projFileAPI *pj_get_default_fileapi();
     ^
    In file included from src/pj_gridinfo.c:31:0:
    src/projects.h:486:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
     void pj_deallocate_grids();
     ^
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Isrc -I/usr/include/python2.7 -c src/pj_initcache.c -o build/temp.linux-x86_64-2.7/src/pj_initcache.o
    In file included from src/projects.h:292:0,
                     from src/pj_initcache.c:28:
    src/proj_api.h:147:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
     projFileAPI *pj_get_default_fileapi();
     ^
    In file included from src/pj_initcache.c:28:0:
    src/projects.h:486:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
     void pj_deallocate_grids();
     ^
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Isrc -I/usr/include/python2.7 -c src/adjlon.c -o build/temp.linux-x86_64-2.7/src/adjlon.o
    In file included from src/projects.h:292:0,
                     from src/adjlon.c:3:
    src/proj_api.h:147:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
     projFileAPI *pj_get_default_fileapi();
     ^
    In file included from src/adjlon.c:3:0:
    src/projects.h:486:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
     void pj_deallocate_grids();
     ^
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Isrc -I/usr/include/python2.7 -c src/pj_inv.c -o build/temp.linux-x86_64-2.7/src/pj_inv.o
    In file included from src/projects.h:292:0,
                     from src/pj_inv.c:3:
    src/proj_api.h:147:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
     projFileAPI *pj_get_default_fileapi();
     ^
    In file included from src/pj_inv.c:3:0:
    src/projects.h:486:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
     void pj_deallocate_grids();
     ^
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Isrc -I/usr/include/python2.7 -c src/pj_mutex.c -o build/temp.linux-x86_64-2.7/src/pj_mutex.o
    In file included from src/projects.h:292:0,
                     from src/pj_mutex.c:39:
    src/proj_api.h:147:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
     projFileAPI *pj_get_default_fileapi();
     ^
    In file included from src/pj_mutex.c:39:0:
    src/projects.h:486:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
     void pj_deallocate_grids();
     ^
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Isrc -I/usr/include/python2.7 -c src/pj_mlfn.c -o build/temp.linux-x86_64-2.7/src/pj_mlfn.o
    In file included from src/projects.h:292:0,
                     from src/pj_mlfn.c:1:
    src/proj_api.h:147:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
     projFileAPI *pj_get_default_fileapi();
     ^
    In file included from src/pj_mlfn.c:1:0:
    src/projects.h:486:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
     void pj_deallocate_grids();
     ^
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Isrc -I/usr/include/python2.7 -c src/PJ_gn_sinu.c -o build/temp.linux-x86_64-2.7/src/PJ_gn_sinu.o
    In file included from src/projects.h:292:0,
                     from src/PJ_gn_sinu.c:5:
    src/proj_api.h:147:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
     projFileAPI *pj_get_default_fileapi();
     ^
    In file included from src/PJ_gn_sinu.c:5:0:
    src/projects.h:486:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
     void pj_deallocate_grids();
     ^
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Isrc -I/usr/include/python2.7 -c src/PJ_loxim.c -o build/temp.linux-x86_64-2.7/src/PJ_loxim.o
    In file included from src/projects.h:292:0,
                     from src/PJ_loxim.c:6:
    src/proj_api.h:147:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
     projFileAPI *pj_get_default_fileapi();
     ^
    In file included from src/PJ_loxim.c:6:0:
    src/projects.h:486:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
     void pj_deallocate_grids();
     ^
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Isrc -I/usr/include/python2.7 -c src/PJ_putp3.c -o build/temp.linux-x86_64-2.7/src/PJ_putp3.o
    In file included from src/projects.h:292:0,
                     from src/PJ_putp3.c:4:
    src/proj_api.h:147:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
     projFileAPI *pj_get_default_fileapi();
     ^
    In file included from src/PJ_putp3.c:4:0:
    src/projects.h:486:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
     void pj_deallocate_grids();
     ^
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Isrc -I/usr/include/python2.7 -c src/bchgen.c -o build/temp.linux-x86_64-2.7/src/bchgen.o
    In file included from src/projects.h:292:0,
                     from src/bchgen.c:2:
    src/proj_api.h:147:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
     projFileAPI *pj_get_default_fileapi();
     ^
    In file included from src/bchgen.c:2:0:
    src/projects.h:486:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
     void pj_deallocate_grids();
     ^
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Isrc -I/usr/include/python2.7 -c src/pj_ell_set.c -o build/temp.linux-x86_64-2.7/src/pj_ell_set.o
    In file included from src/projects.h:292:0,
                     from src/pj_ell_set.c:2:
    src/proj_api.h:147:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
     projFileAPI *pj_get_default_fileapi();
     ^
    In file included from src/pj_ell_set.c:2:0:
    src/projects.h:486:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
     void pj_deallocate_grids();
     ^
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Isrc -I/usr/include/python2.7 -c _proj.c -o build/temp.linux-x86_64-2.7/_proj.o
    _proj.c:4:20: fatal error: Python.h: Aucun fichier ou dossier de ce type
     #include "Python.h"
                        ^
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

The information of my environment:
Python version: 2.7.8
Pip version: 8.1.2
Ubuntu: 14.10

**Comment by methoman** [comment]
Do you have the package python-dev installed?

**Comment by xie-qianyue** [comment]
@methoman Thank you for your hint. python-dev isn't installed. But I have quite a lots of problem when installing python-dev, especially the mismatch of the version of python. I will try it later.

**Comment by BaIthamel** [comment]
This is not a support forum; please see [the discord #help channel](https://discord.gg/npVqkUn) for assistance.
