### ISSUE TITLE
Handle 15 minute ban

### ISSUE THREAD

**Issue by blindreaper** [PokemonGoMap/PokemonGo-Map#559]
I don't know what causes it but some of my accounts end up with the 15 minute ban, the thread will only wait 10 seconds before trying again, try for login-retries and then wait login-delay seconds and keep trying over and over (IIRC).

The account needs to be removed from rotation for 15 minutes.

**Comment by jonathanwcrane** [comment]
Aren't 15 minute bans for logging in with the wrong password too many times?  Or are there other reasons for 15 minute bans?

**Comment by blindreaper** [comment]
i only have one password so it's definitely right, it may be related to this: https://github.com/keyphact/pgoapi/issues/87

May be PTC servers, may be ToS, dont know.
