### ISSUE TITLE
OSM - Selfhosted maps - Future request

### ISSUE THREAD

**Issue by AlexHjelm** [PokemonGoMap/PokemonGo-Map#560]
Would it be easy to implent the use of OSM? its nice to be able to not depend on googles API.
https://switch2osm.org/serving-tiles/

**Comment by tkSimon** [comment]
Still need google for the places api, maps api for determining altitude, right

**Comment by BaIthamel** [comment]
For feature requests please migrate this to the new feature page
http://feathub.com/PokemonGoMap/PokemonGo-Map/
Thankyou!

**Comment by CoolCanuck** [comment]
@BaIthamel This request needs to be opened again. FeatHub is no longer used. Good riddance.
