### ISSUE TITLE
Lured Pokestops not showing Pokemons ?

### ISSUE THREAD

**Issue by DataDrug** [PokemonGoMap/PokemonGo-Map#561]
I thought that after upgrading to the latest dev version would fix this, I can only see what pokestops are lured / not lured.

Is it just me ?

**Comment by Allheria** [comment]
I have the same problem :/

**Comment by invisiblek** [comment]
See my comment here: https://github.com/PokemonGoMap/PokemonGo-Map/issues/148#issuecomment-239449456

**Comment by DataDrug** [comment]
Oh damn. Is anyone working to fix this ? I'll be at lab all weekend with past due work :|
