### ISSUE TITLE
[Feature Request] Change location locally instead of globally

### ISSUE THREAD

**Issue by CtrlAltDefeat94** [PokemonGoMap/PokemonGo-Map#562]
## Expected Behavior
As I scan 2 towns that are quite far away from each other and host my map publicly I'd like it to be possible to set the locations box to change the location only locally instead of globally. This way a user can change the town being viewed, without changing it for the other users.

## Current Behavior
Setting a different location in the locations box changes the location globally

**Comment by ImAnOwl** [comment]
If you want it right now:

Go to pogom/app.py
Look for def next_loc
Delete all content until return "ok"

Now you are done :D

**Comment by BaIthamel** [comment]
This is not a support forum; please see [the discord #help channel](https://discord.gg/npVqkUn) for assistance.

**Comment by CtrlAltDefeat94** [comment]
This is a feature request, not asking for support.
Why are issues even enabled if literally nothing fits the bill?
