### ISSUE TITLE
[BUG] scannedLocations does not work correctly

### ISSUE THREAD

**Issue by ImAnOwl** [PokemonGoMap/PokemonGo-Map#563]
Hi,

if you turn on the scannedocations switch, it show up only one circle instead of showing all locations,

LG Oliver ~ Germany

**Comment by crckdns** [comment]
![image](https://cloud.githubusercontent.com/assets/787954/17633310/e385bf3a-60cc-11e6-8e9d-76f3a31d805e.png)

works fine with latest dev~
any errors in console? are the locations in the database?

**Comment by CtrlAltDefeat94** [comment]
Same issue, no log

**Comment by ImAnOwl** [comment]
No Errros and using latest develop, are you sure @crckdns that oy usue the latest develop?

**Comment by Dajen** [comment]
I am having the same issue. Just one cirle instead od all. I am running the latest develop version.
No errors in the log, but it seems that the workers are throttled quite a lot (but that is another issue).

**Comment by crckdns** [comment]
@ImAnOwl yeah pretty sure, because I had to stop/restart all workers due to database change. All scanned locations were deleted on update. Have done the update like 45 minutes ago.

**Comment by ImAnOwl** [comment]
@crckdns hmm did the same, why we got different results ...

**Comment by BaIthamel** [comment]
This is not a support forum; please see [the discord #help channel](https://discord.gg/npVqkUn) for assistance.
