### ISSUE TITLE
[Feature request] stats-map exclude 1-times appearance.

### ISSUE THREAD

**Issue by crckdns** [PokemonGoMap/PokemonGo-Map#564]
Something I do for now locally and export to a heatmap generator could be done officially in the statistics-heatmap.
For now every single appearance is shown on map, even it was only one time. Doesn't help a lot in searching for a hotspot / nest.

## Expected Behavior
I go into stats, select full stats, click on "all locations", see on map every spawnpoint_id where the pokemon was at least twice (configurable), voila, possible spot found.

## Current Behavior
I see every single spot of the pokemon where it appeared once, does good job but it doesn't help in any way. I have to search and zoom around in heatmap to find a spot where it appeared more than one time.

## Possible Solution
I do locally on my database a query like this:
`SELECT spawnpoint_id,latitude,longitude,pokemon_id,count(pokemon_id) FROM c1pogo1.pokemon where disappear_time >= curdate()-10 and pokemon_id not in(10,13,16,17,19,21,41,96) group by spawnpoint_id,pokemon_id having count(spawnpoint_id) >=5 order by count(pokemon_id) desc, pokemon_id;`
you get the idea, I guess.  I see only pokemon which appeared more than 4 times in same location and show then this "filtered" result for further mapping.
This way I even can tell a pidgey hotspot, try that with current system, your browser will crash after reaching 4GB of memory.

## Steps to Reproduce (for bugs)
1. go to full stats
2. click to see locations of a pokemon
3. cry because no filtering of once-appeared pokemon

## Context
it would be great just to have a tick-box or even selector to choose how many times the pokemon should've been appeared in one spot to be shown in the heatmap

## Your Environment
* Version used: latest dev
* Environment name and version (e.g. Python 2.7): python 2.7
* Operating System and version (desktop or mobile): debian root

**Comment by FrostTheFox** [comment]
Please direct feature requests to http://feathub.com/PokemonGoMap/PokemonGo-Map
