### ISSUE TITLE
Pause threads/accounts for a specified period of time when only getting softbanned.

### ISSUE THREAD

**Issue by marcmicalizzi** [PokemonGoMap/PokemonGo-Map#569]
> After speaking with @BaIthamel I was advised to open a new ticket for this after the previous ticket was closed due to the wording conveying something different than I meant.

It would be valueable (to avoid full ip soft/hard bans) to pause threads/accounts for a specified and/or configurable period of time, possibly ramping up if after that time the softban is still active, if they receive a certain number of 0, 0, 0 upserts.

The rational behind this is that I have found that if an account is softbanned, and then it keeps running while the softban is active, it leads to a longer and longer ban until the worker is stopped, even possibly a permanent ban and/or ip ban.

The past 2 days I haven't had any softbans at all (running 3 servers [on separate ips] each with 6, 7 and 8 `-st 10 -sd 10` processes each running with 10 accounts), but prior to that (with no configuration changes) after running the processes for 1.5-2 hours accounts would slowly get softbanned. Shutting down the maps for 15 minutes when 30-40% of the accounts were softbanned seemed to result in the ban being lifted by then, however when it was kept running until all the accounts on that ip were banned, it resulted in a full ip ban for 2-3 hours. 

Other people have reported that even with a single worker at default settings, they get softbans, so a feature like this could mitigate bans a lot. 

Ideally I think the feature should be enableable/disableable, the amount of time configurable, and number of consecutive 0,0,0's needed configurable.

Without this feature, it becomes potentially dangerous to run the map with the output unmonitored, unless the actual banning mechanism is/becomes different than what I have observed.

**Comment by Albert62** [comment]
How where yo able to add up 10 accounts?

**Comment by BaIthamel** [comment]
For feature requests please migrate this to the new feature page
http://feathub.com/PokemonGoMap/PokemonGo-Map/
Thankyou!

**Comment by CoolCanuck** [comment]
@BaIthamel This request needs to be opened again. FeatHub is no longer used. Good riddance.
