### ISSUE TITLE
[Feature Request] Add a WAVE_DELAY parameter -wd

### ISSUE THREAD

**Issue by LurkerLurks** [PokemonGoMap/PokemonGo-Map#570]
## Requested Behavior

Setting WAVE_DELAY (-wd) in seconds will delay the start of the next wave of scanning once the max scan track has been reached. 

For example, you want to scan your immediate area once every 5 minutes and you have 7 accounts setup you can set STEP_LIMIT to 2 and scan your immediate area all at once and then have WAVE_DELAY postpone the next wave for 300 seconds. Alternatively, if you are scanning a larger area The scan would wait until the cooldown has passed before restarting the scan. 

OPTION A: Have the WAVE_DELAY start once the STEP_LIMIT has been reached.

OPTION B: The count for WAVE_DELAY begins right before the first step is scanned. Once STEP_LIMIT has been reached the next step is delayed until the WAVE_DELAY has been reached. If the STEP_LIMIT is not reached after the WAVE_DELAY expires then it simply restarts the scan immediately once the STEP_LIMIT is reached. 

The default value would be 0.

## Context

This would be useful for people who are spawn mapping and people who want to scan all day for nearby notifications but don't need/want a constant scan running in the background.

## Current Behavior

Setting STEP_DELAY only scans an area slowly it does not delay the scanning process. 

## Status: Planning

I am brand new to NodeJS have no formal coding experience. I have some very basic scripting experience but that is it.   I might have some time to study it this weekend and might figure something out in the next week or so. If anyone else knows how implement this quickly, wants mentor me through the process or could point me in the right direction I am all ears.

**Comment by FrostTheFox** [comment]
Please direct feature requests to http://feathub.com/PokemonGoMap/PokemonGo-Map

**Comment by LurkerLurks** [comment]
@FrostTheFox - Implementing Option A ended up being a lot easier than I thought. It looks like a delay was already in place in the last line of the search_overseer_thread of the search.py (~line 176).  I added the --wave-delay entry to the utils.py and it looks like that worked. I have submitted the change in pr #591.
