### ISSUE TITLE
[Request] thread queue Implementation

### ISSUE THREAD

**Issue by vinsilsim** [PokemonGoMap/PokemonGo-Map#573]
One problem I have with respect to this fork is that when someone changes the brand "Address Change" and a new search point is told he interrupts the old place to start to look at the new point. My idea is to create a row for only when the old point is sought by complete it will really make a search in the new point. Of course with many workers we could quickly get an average area. Or simply divide workers for every new search, thus performing the search everywhere at the same time without the old point is stopped. Another thing that I think would improve the performance would limit the marking in a marking every 1 minute per user, thus preventing the server overcrowding. I really do not know if these changes is the desire of all and not have the technical capability to do something. I apologize for my ignorance, and I hope that those who agree with my ideas to join me until someone capable to do it! Sorry for bad english!

**Comment by BaIthamel** [comment]
For feature requests please migrate this to the new feature page
http://feathub.com/PokemonGoMap/PokemonGo-Map/
Thankyou!
