### ISSUE TITLE
scanning point

### ISSUE THREAD

**Issue by Yuk111** [PokemonGoMap/PokemonGo-Map#575]
Sorry for my English
I use Google translator

Is it possible to make a few points of moving the scan?

**Comment by BaIthamel** [comment]
This is not a support forum; please see [the discord #help channel](https://discord.gg/npVqkUn) for assistance.

**Comment by Yuk111** [comment]
https://goo.gl/photos/ivNM8vJLa4oAuFki7

I can not enter
