### ISSUE TITLE
[Request] Add Option to set defaults on the Webpage

### ISSUE THREAD

**Issue by mugabemkomo** [PokemonGoMap/PokemonGo-Map#576]
For example I would like to hide Pokestops from the default view (first launch) also if possible hide certain pokemon by default, so the user does not have to enter them manually. 
So basicly preflip the switch Pokestops and prefill the hide Pokemon values.
I don't want to stop gathering info in the database.

**Comment by FrostTheFox** [comment]
Please direct feature requests to http://feathub.com/PokemonGoMap/PokemonGo-Map
