### ISSUE TITLE
Specified key was too long

### ISSUE THREAD

**Issue by g5bEM6RpSbQF** [PokemonGoMap/PokemonGo-Map#577]
After clearing the database (I'm using mariadb (mysql)) I get this error:

/usr/local/lib/python2.7/dist-packages/pymysql/cursors.py:161: Warning: Specified key was too long; max key length is 767 bytes
  result = self._query(query)

Latest git develop branch + issue 595

**Comment by BaIthamel** [comment]
This is not a support forum; please see [the discord #help channel](https://discord.gg/npVqkUn) for assistance.
