### ISSUE TITLE
[Request] Only show specific Pokemon

### ISSUE THREAD

**Issue by g5bEM6RpSbQF** [PokemonGoMap/PokemonGo-Map#578]
We have an option to hide specific pokemon.  I'd like an option to show specific pokemon.

## Expected Behavior
If the show specific pokemon field is populated, then the map will only show those pokemon.

## Current Behavior
Option does not exist.

## Context
If your quickly looking for a specific pokemon, right now you have to exclude everything else.  This takes time.

## Your Environment
Latest develop branch.

**Comment by FrostTheFox** [comment]
Please direct feature requests to http://feathub.com/PokemonGoMap/PokemonGo-Map
