### ISSUE TITLE
[Request] Pinning Sidebars

### ISSUE THREAD

**Issue by g5bEM6RpSbQF** [PokemonGoMap/PokemonGo-Map#579]
I'd like to see a 'pinning' icon at the top of each side bar.  By default, this icon would be 'unpinnned' and the sidebar would collapse when it looses focus (the current behaviour).  If the user clicks the icon, it switches to 'pinned' mode and the sidebar would not collapse when it looses focus.

This is very useful when excluding lots of Pokemon (as you don't have to keep re-opening the sidebar.

## Your Environment
Latest develop branch

**Comment by FrostTheFox** [comment]
Please direct feature requests to http://feathub.com/PokemonGoMap/PokemonGo-Map
