### ISSUE TITLE
[Bug] google auth

### ISSUE THREAD

**Issue by vinsilsim** [PokemonGoMap/PokemonGo-Map#580]
[ search_worker_0][        search][   ERROR] Exception in search_worker: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:765).
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 477, in send
    raise SSLError(e, request=request)
SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:765)

**Comment by BaIthamel** [comment]
This is not a support forum; please see [the discord #help channel](https://discord.gg/npVqkUn) for assistance.
