### ISSUE TITLE
Incorrect use of OAuth?

### ISSUE THREAD

**Issue by huanga** [PokemonGoMap/PokemonGo-Map#584]
Looks like the `check_login` concept is misusing OAuth, which in turn may be causing us to cycle authentication continuously, and can raise flags on Niantic side.

## Expected Behavior
After exchanging the `code` for `access_token` with Google, Google should return 4 pieces of information: `access_token`, `refresh_token`, `expires_in`, and `token_type`. For example:

```
{
  "access_token":"1/fFAGRNJru1FTz70BzhT3Zg",
  "expires_in":3920,
  "token_type":"Bearer",
  "refresh_token":"1/xEoDL4iW3cxlI7yDbSRFYNG01kVKM2C-259HOF2aQbI"
}
```

As `access_token` approaches the future `expires_in` time, client should use the `refresh_token` to get a new `access_token` to continue to work with the same session. This can be done by sending a request to `https://www.googleapis.com/oauth2/v4/token` per instructions outlined here: https://developers.google.com/identity/protocols/OAuth2WebServer#refresh

## Current Behavior
Currently, `check_login` attempts to be pre-emptive, and requests a new access_token: https://github.com/PokemonGoMap/PokemonGo-Map/blob/develop/pogom/search.py#L272

The behaviour is incorrect per OAuth spec. On Niantic side, it would appear that we are repeatedly re-logging in every time the token reaches its expiry.

## Possible Solution
Fortunately, PGOAPI handles this for us already: https://github.com/keyphact/pgoapi/blob/master/pgoapi/auth_google.py#L71 

If we are using the correct version of PGOAPI, the logics in check_login can simply be altered such that it only performs the authentication for the first time, and let PGOAPI handle that aspect of the token management.

## Context
My scanner in the cloud just got IP banned. This got me reviewing the console output for tell tale signs that we can attempt to eliminate. Upon scrolling through the log, I was able to notice very quickly that there was a recurring re-logging activity, which lead me to this discovery. I do not believe this is what gave it away, as there are always other things (consistent altitude, even after the change in #171 / #75 for example; always hitting the exact same coordinates within a fixed interval for example; etc. etc. etc.). However, I'm always in the camp of giving out minimal signal to stay under the radar, and every little bit counts.

## Your Environment
Ubuntu 14.04 VM running Docker image.

**Comment by BaIthamel** [comment]
Looks like you know what you're talking about, make a PR? :)

**Comment by chuyskywalker** [comment]
So, call `api.set_authentication` once and then just stop doing that?

**Comment by huanga** [comment]
@BaIthamel > Few reasons... But, not gonna lie, mainly because my cloud IP range is banned, and I don't have another provider to test with yet. Other excuses include: I was going on a walk with the wifey; I'm still confirming that PGOAPI will handle everything for us; etc. etc. etc. 😛 

@chuyskywalker > I think so. I'm still verifying it from reviewing PGOAPI. From what I can see: PGOAPI's [`PGoApiRequest .call` function](https://github.com/keyphact/pgoapi/blob/master/pgoapi/pgoapi.py#L206) handles it, so if `PokemonGo-Map` isn't doing anything fancy to override that behaviour, you'd be correct in that we'd just need to call [`PGoApi.login` function](https://github.com/keyphact/pgoapi/blob/master/pgoapi/pgoapi.py#L161) once and be good.

**Comment by chuyskywalker** [comment]
the `login()` is deprecated, form what I can tell (hence why we switched) so perhaps the new one effectively works the same. IE: if we called it, when it needs the token it'll just go fetch one based on the fact that we set it up to do so.

**Comment by huanga** [comment]
You're right; it looks like `login()` is deprecated and no longer necessary -- it just proxies `set_authentication` for the most part. 

And, also appears that as long as the API calls are routed through `call()` function (which it does, as [`get_map_objects()`](https://github.com/PokemonGoMap/PokemonGo-Map/blob/develop/pogom/search.py#L307) call triggers magic function [`__getattr__()`](https://github.com/keyphact/pgoapi/blob/master/pgoapi/pgoapi.py#L129), which creates a request and calls the `call()` function), we should be covered automatically.

I'm not a Python developer by any fetch, so please do correct me if I'm not reading this correctly.

**Comment by huanga** [comment]
Note: I do like the `app_simulation_login()` that `login()` performs... It adds absolutely zero value to the map scanner, but it puts us under the radar a little bit more (if we're not already calling that).
