### ISSUE TITLE
database is locked... Retrying error message

### ISSUE THREAD

**Issue by weiguken** [PokemonGoMap/PokemonGo-Map#586]
I have 37 accounts running right now and when I finished starting the last ones, the first ones are now getting the message "database is locked... Retrying" error message and its causing them to not work. Any known cause of this. Any solution?

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Python 2.7):
* Operating System and version (desktop or mobile):

**Comment by hklcf** [comment]
I/O problem

**Comment by hklcf** [comment]
the best solution is change the db type to mysql

**Comment by BaIthamel** [comment]
if you are not on mysql switch.
