### ISSUE TITLE
[REQUEST] ISSUES ARE NOT FOR SUPPORT

### ISSUE THREAD

**Issue by invisiblek** [PokemonGoMap/PokemonGo-Map#59]

**Comment by JZ6** [comment]
Open the flood gates

**Comment by FrostTheFox** [comment]
bang lure pls

**Comment by prtsh716** [comment]
how to solve this error


![capture](https://cloud.githubusercontent.com/assets/20891909/17469163/91b03254-5d4c-11e6-9589-28f9415a65d7.PNG)

**Comment by prtsh716** [comment]
how to solve this  




![capture](https://cloud.githubusercontent.com/assets/20891909/17469187/1230e298-5d4d-11e6-8283-f9254a3e11a5.PNG)

**Comment by invisiblek** [comment]
![](https://media.giphy.com/media/GhXo8hSjQhCBq/giphy.gif)
