### ISSUE TITLE
error "python setup.py egg_info" failed with error code 1

### ISSUE THREAD

**Issue by rriixx** [PokemonGoMap/PokemonGo-Map#593]
i'm executing "pip install -r requirements.txt" and getting the following error

"Command 'python setup.py egg_info' failed with error code 1 in c:/users/xxx/appdata/local/temp/pip-build-agch8t/pyproj/

**Comment by BaIthamel** [comment]
This is not a support forum; please see [the discord #help channel](https://discord.gg/npVqkUn) for assistance.
