### ISSUE TITLE
Scan locations no longer show up on the map

### ISSUE THREAD

**Issue by Qualimiox** [PokemonGoMap/PokemonGo-Map#599]
So previously I've been using a version from about 3 days ago until now. I just updated to the current dev branch to fix the 280+hour-bug. I'm running one server and 14 workers in no-server mode. 

In the old version, when I'd activate "scanned locations" on the map, it'd show all scans from all workers. Now, when I click it, it seems to only show a single scan from the last worker started. Instead of the entire beehive-pattern, I'm seeing a single circle at the position of my last worker. This circle doesn't update its position either. Disabling and re-enabling the checkbox for scanned locations doesn't seem to help. Weirdly, the circle even changes its color when zooming in and out. 

All workers are still working fine, finding Pokemon and displaying them on the map. It's just the scan locations no longer showing up.

## Your Environment

* Version used: Current dev branch
* Environment name and version: Python 2.7
* Operating System: Windows 10

**Comment by itztq** [comment]
Im using chrome browser, sometimes you need to clear the cache of the browser history ect..

**Comment by Qualimiox** [comment]
Thanks, that solved my issue! Should've thought of doing that...
