### ISSUE TITLE
Error in windows installation

### ISSUE THREAD

**Issue by AlejandroBlackburn** [PokemonGoMap/PokemonGo-Map#60]
I followed the installation steps of the wiki and still I get the following error:

> 2016-08-07 21:36:23,346 [      MainThread][     runserver][CRITICAL] It seems `pgoapi` is not installed. You must run pip install -r requirements.txt again

But, when I run pip install -r requirements.txt I get this: 

> Requirement already satisfied (use --upgrade to upgrade): six==1.10.0 in c:\python27\lib\site-packages (from -r requirements.txt (line 1))
> Requirement already satisfied (use --upgrade to upgrade): Flask==0.11.1 in c:\python27\lib\site-packages (from -r requirements.txt (line 2))
> Requirement already satisfied (use --upgrade to upgrade): Jinja2==2.8 in c:\python27\lib\site-packages (from -r requirements.txt (line 3))
> Requirement already satisfied (use --upgrade to upgrade): MarkupSafe==0.23 in c:\python27\lib\site-packages (from -r requirements.txt (line 4))
> Requirement already satisfied (use --upgrade to upgrade): Werkzeug==0.11.10 in c:\python27\lib\site-packages (from -r requirements.txt (line 5))
> Requirement already satisfied (use --upgrade to upgrade): configargparse==0.10.0 in c:\python27\lib\site-packages (from -r requirements.txt (line 6))
> Requirement already satisfied (use --upgrade to upgrade): click==6.6 in c:\python27\lib\site-packages (from -r requirements.txt (line 7))
> Requirement already satisfied (use --upgrade to upgrade): itsdangerous==0.24 in c:\python27\lib\site-packages (from -r requirements.txt (line 8))
> Requirement already satisfied (use --upgrade to upgrade): peewee==2.8.1 in c:\python27\lib\site-packages (from -r requirements.txt (line 9))
> Requirement already satisfied (use --upgrade to upgrade): wsgiref==0.1.2 in c:\python27\lib\site-packages (from -r requirements.txt (line 10))
> Requirement already satisfied (use --upgrade to upgrade): geopy==1.11.0 in c:\python27\lib\site-packages (from -r requirements.txt (line 11))
> Requirement already satisfied (use --upgrade to upgrade): s2sphere==0.2.4 in c:\python27\lib\site-packages (from -r requirements.txt (line 12))
> Requirement already satisfied (use --upgrade to upgrade): gpsoauth==0.3.0 in c:\python27\lib\site-packages (from -r requirements.txt (line 13))
> Requirement already satisfied (use --upgrade to upgrade): PyMySQL==0.7.5 in c:\python27\lib\site-packages (from -r requirements.txt (line 14))
> Requirement already satisfied (use --upgrade to upgrade): flask-cors==2.1.2 in c:\python27\lib\site-packages (from -r requirements.txt (line 15))
> Requirement already satisfied (use --upgrade to upgrade): flask-compress==1.3.0 in c:\python27\lib\site-packages (from -r requirements.txt (line 16))
> Requirement already satisfied (use --upgrade to upgrade): LatLon==1.0.1 in c:\python27\lib\site-packages (from -r requirements.txt (line 17))
> Requirement already satisfied (use --upgrade to upgrade): pgoapi from git+https://github.com/keyphact/pgoapi.git#egg=pgoapi in c:\python27 (from -r requirements.txt (line 18))
> Requirement already satisfied (use --upgrade to upgrade): xxhash in c:\python27\lib\site-packages (from -r requirements.txt (line 19))
> Requirement already satisfied (use --upgrade to upgrade): sphinx==1.4.5 in c:\python27\lib\site-packages (from -r requirements.txt (line 20))
> Requirement already satisfied (use --upgrade to upgrade): sphinx-autobuild==0.6.0 in c:\python27\lib\site-packages (from -r requirements.txt (line 21))
> Requirement already satisfied (use --upgrade to upgrade): recommonmark==0.4.0 in c:\python27\lib\site-packages (from -r requirements.txt (line 22))
> Requirement already satisfied (use --upgrade to upgrade): sphinx_rtd_theme==0.1.9 in c:\python27\lib\site-packages (from -r requirements.txt (line 23))
> Requirement already satisfied (use --upgrade to upgrade): future in c:\python27\lib\site-packages (from s2sphere==0.2.4->-r requirements.txt (line 12))
> Requirement already satisfied (use --upgrade to upgrade): pycryptodomex>=3.0 in c:\python27\lib\site-packages (from gpsoauth==0.3.0->-r requirements.txt (line 13))
> Requirement already satisfied (use --upgrade to upgrade): requests in c:\python27\lib\site-packages (from gpsoauth==0.3.0->-r requirements.txt (line 13))
> Requirement already satisfied (use --upgrade to upgrade): pyproj in c:\python27\lib\site-packages (from LatLon==1.0.1->-r requirements.txt (line 17))
> Requirement already satisfied (use --upgrade to upgrade): protobuf>=3.0.0a3 in c:\python27\lib\site-packages (from pgoapi->-r requirements.txt (line 18))
> Requirement already satisfied (use --upgrade to upgrade): docutils>=0.11 in c:\python27\lib\site-packages (from sphinx==1.4.5->-r requirements.txt (line 20))
> Requirement already satisfied (use --upgrade to upgrade): snowballstemmer>=1.1 in c:\python27\lib\site-packages (from sphinx==1.4.5->-r requirements.txt (line 20))
> Requirement already satisfied (use --upgrade to upgrade): alabaster<0.8,>=0.7 in c:\python27\lib\site-packages (from sphinx==1.4.5->-r requirements.txt (line 20))
> Requirement already satisfied (use --upgrade to upgrade): Pygments>=2.0 in c:\python27\lib\site-packages (from sphinx==1.4.5->-r requirements.txt (line 20))
> Requirement already satisfied (use --upgrade to upgrade): imagesize in c:\python27\lib\site-packages (from sphinx==1.4.5->-r requirements.txt (line 20))
> Requirement already satisfied (use --upgrade to upgrade): colorama>=0.3.5; sys_platform == "win32" in c:\python27\lib\site-packages (from sphinx==1.4.5->-r requirements.txt (line 20))
> Requirement already satisfied (use --upgrade to upgrade): babel!=2.0,>=1.3 in c:\python27\lib\site-packages (from sphinx==1.4.5->-r requirements.txt (line 20))
> Requirement already satisfied (use --upgrade to upgrade): PyYAML>=3.10 in c:\python27\lib\site-packages (from sphinx-autobuild==0.6.0->-r requirements.txt (line 21))
> Requirement already satisfied (use --upgrade to upgrade): port-for==0.3.1 in c:\python27\lib\site-packages (from sphinx-autobuild==0.6.0->-r requirements.txt (line 21))
> Requirement already satisfied (use --upgrade to upgrade): watchdog>=0.7.1 in c:\python27\lib\site-packages (from sphinx-autobuild==0.6.0->-r requirements.txt (line 21))
> Requirement already satisfied (use --upgrade to upgrade): pathtools>=0.1.2 in c:\python27\lib\site-packages (from sphinx-autobuild==0.6.0->-r requirements.txt (line 21))
> Requirement already satisfied (use --upgrade to upgrade): livereload>=2.3.0 in c:\python27\lib\site-packages (from sphinx-autobuild==0.6.0->-r requirements.txt (line 21))
> Requirement already satisfied (use --upgrade to upgrade): argh>=0.24.1 in c:\python27\lib\site-packages (from sphinx-autobuild==0.6.0->-r requirements.txt (line 21))
> Requirement already satisfied (use --upgrade to upgrade): tornado>=3.2 in c:\python27\lib\site-packages (from sphinx-autobuild==0.6.0->-r requirements.txt (line 21))
> Requirement already satisfied (use --upgrade to upgrade): commonmark<=0.5.4 in c:\python27\lib\site-packages (from recommonmark==0.4.0->-r requirements.txt (line 22))
> Requirement already satisfied (use --upgrade to upgrade): setuptools in c:\python27\lib\site-packages (from protobuf>=3.0.0a3->pgoapi->-r requirements.txt (line 18))
> Requirement already satisfied (use --upgrade to upgrade): pytz>=0a in c:\python27\lib\site-packages (from babel!=2.0,>=1.3->sphinx==1.4.5->-r requirements.txt (line 20))
> Requirement already satisfied (use --upgrade to upgrade): singledispatch in c:\python27\lib\site-packages (from tornado>=3.2->sphinx-autobuild==0.6.0->-r requirements.txt (line 21))
> Requirement already satisfied (use --upgrade to upgrade): certifi in c:\python27\lib\site-packages (from tornado>=3.2->sphinx-autobuild==0.6.0->-r requirements.txt (line 21))
> Requirement already satisfied (use --upgrade to upgrade): backports-abc>=0.4 in c:\python27\lib\site-packages (from tornado>=3.2->sphinx-autobuild==0.6.0->-r requirements.txt (line 21))

What it's wrong?

**Comment by alucarddelta** [comment]
The Wiki has been changed to the old one, which is missing some details on installation.

**Comment by AlejandroBlackburn** [comment]
Uhmm, this wiki (https://pgm.readthedocs.io/en/develop/index.html) is outdated?

**Comment by alucarddelta** [comment]
As per https://github.com/PokemonGoMap/PokemonGo-Map/pull/57

> Going to clean up the new wiki that has all old pages somehow

**Comment by BaIthamel** [comment]
ask for help in the discord #help
