### ISSUE TITLE
Very Rare pokemon not showing

### ISSUE THREAD

**Issue by nicktan147** [PokemonGoMap/PokemonGo-Map#600]
Recently, I notice certain pokemon doesn't show up properly, for example, DragonNite (The orange dragon), today I was roaming around my neighbourhood, I found other pokemon around it but just that pokemon (DragonNite) doesn't show. Also, Snorlax doesn't come up either, but it was 1 week back. Any reason why?

**Comment by BaIthamel** [comment]
It does show. They both do.
This is not a support forum; please see [the discord #help channel](https://discord.gg/npVqkUn) for assistance.
