### ISSUE TITLE
Despawn timer wrong values

### ISSUE THREAD

**Issue by Foxbond** [PokemonGoMap/PokemonGo-Map#603]
As title says. I cant trace error location, logs are useless.
![err1](https://cloud.githubusercontent.com/assets/752127/17643120/5ee83d36-6160-11e6-9c55-55cdfba588bf.PNG)
![err2](https://cloud.githubusercontent.com/assets/752127/17643122/6432e642-6160-11e6-8495-444dbe746a96.PNG)

Ubuntu (i cant provide version)
Latest map version
MySQL 5.6.31
Python 2.7.12
Modules according to requirements.txt

Running 6 workers "python runserver.pyc -ns -l 'xxx' -st 6" and server "python runserver.pyc -os" on same machine, mysql serwer on another (<50ms latency)

**Comment by itztq** [comment]
allready fixed #601 #602 just download the latest branch
