### ISSUE TITLE
[Feature request] Show pokemon in gyms with cp and player name

### ISSUE THREAD

**Issue by JohanJu** [PokemonGoMap/PokemonGo-Map#605]
A list of all the Pokemon in a gym when hovering over that gym. 

In the future it would be nice to have:
Notification when a gym is attacked.
A trend arrow for the prestige for gyms.
Filter out gyms in your team with empty places/close to next level.
What team attacks what team.
What time most battles take place both per gym and over larger area.
Path and time for player movment (maybe this will detect spoofers, do we want that?) (Only in backend so that not everyone can find spoofers?)
What pokemon a player have.

**Comment by slideup-benni** [comment]
There is already a feature request:
http://feathub.com/PokemonGoMap/PokemonGo-Map/+10
