### ISSUE TITLE
Resuming after pausing search thread is causing a burst of requests

### ISSUE THREAD

**Issue by ilendemli** [PokemonGoMap/PokemonGo-Map#607]
If you pause the searcher and wait a few moments, then start it again will cause the workers to do a burst of request which can cause a ban or throttle the connection.

## Expected Behavior
Starting the workers with delays

## Current Behavior
Resumes all search threads immediatelly

## Steps to Reproduce (for bugs)
1. Run script
2. Let it log in, obtain tokens and search for pokemon
3. Pause it by using the switch in the webinterface
4. Wait a few moments, maybe go make tea or coffee
5. Resume the script using the switch
6. Check the script resuming the working thread instantly

## Context
Caused soft bans or got throttled (returns 0/0/0)

## Your Environment
* Version used: current develop branch, last commit: [f56f3f42efe550495492a0231865467ac96e4305](https://github.com/PokemonGoMap/PokemonGo-Map/commit/f56f3f42efe550495492a0231865467ac96e4305)
* Environment name and version (e.g. Python 2.7): Python 2.7.12
* Operating System and version (desktop or mobile): Ubuntu 16.04.1

**Comment by jtp10181** [comment]
I think this is fixed by https://github.com/PokemonGoMap/PokemonGo-Map/pull/530
Works for me anyway

**Comment by ProfessorPokes** [comment]
I am having a similar issue. If I stop the search partway through my scan then restart it it will gather the completed spawnpoints list and log in my workers, it then speed runs through a list of requests. Either in an effort to catch up to where it was before, or to catch up to the time it took to gather the spawn point locations.

Results in warnings to slow down, but there is nothing I can do.

**Comment by SlasherKG** [comment]
I have the same issue.
I normally pause (by toggling the search switch in the browser).
Then when I get to my new location, I set the location and toggle it back on.
This seems to cause a flood of built up scans that should have been simply discarded instead of run.

Along this same thought, is there a way to start the server but not have it start a search (basically start paused)?

**Comment by ultrafunkamsterdam** [comment]
Maybe that could be a reason for banning too.

For safety reasons, i'm now implementing a little modification to map.js that pauses automatically when moving the marker, and starting when marker is set. Then the amount of pending requests will be reduced.

`
   return google.maps.event.addListener(a, "dragstart", function() {
		searchControl('off');    //turns off search control on dragging start
		console.log('Marker drag start : search=off'); //for testing.
        b = a.getPosition()
    }), google.maps.event.addListener(a, "dragend", function() {
        var c = a.getPosition();
        changeSearchLocation(c.lat(), c.lng()).done(function() {
		searchControl('on');  //turns on search control on dragging end
		console.log('Marker drag end : search=on'); //for testing.
            b = null
        }).fail(function() {
            b && a.setPosition(b)
        })
    }), a
}
`

**Comment by justsomedudeonthenet** [comment]
This is resolved now.
