### ISSUE TITLE
Showing spawn points breaks map display

### ISSUE THREAD

**Issue by tboyce1** [PokemonGoMap/PokemonGo-Map#611]
## Expected Behavior
Showing spawn points should work

## Current Behavior
Using a MySQL database, turning on spawn points doesn't work and stops the map display from updating.

I get the following error in the output:
```
2016-08-13T13:45:14.644151916Z app[web.1]:   File "/app/.scalingo/python/lib/python2.7/site-packages/pymysql/err.py", line 120, in raise_mysql_exception
2016-08-13T13:45:14.644158031Z app[web.1]:     _check_mysql_exception(errinfo)
2016-08-13T13:45:14.644163330Z app[web.1]:   File "/app/.scalingo/python/lib/pyt
hon2.7/site-packages/pymysql/err.py", line 115, in _check_mysql_exception
2016-08-13T13:45:14.644169244Z app[web.1]:     raise InternalError(errno, errorv
alue)
2016-08-13T13:45:14.644175329Z app[web.1]: InternalError: (1055, u"Expression #1
 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'pog
omap.t1.latitude' which is not functionally dependent on columns in GROUP BY cla
use; this is incompatible with sql_mode=only_full_group_by")
```

## Steps to Reproduce (for bugs)
1. Use a MySQL database
2. Turn on spawn point display

## Context
Can't view spawn points.

## Your Environment
* Version used: f56f3f42
* Operating System and version (desktop or mobile): Ubuntu 16.04.1

**Comment by tboyce1** [comment]
Now, I understand this could be resolved by disabling only_full_group_by, but is there any way to make the query work with the default MySQL settings?

**Comment by DragorWW** [comment]
this problem with sql_mod only_full_group_by.
only_full_group_by enabled in MySQL >= 5.7

**Comment by Xcelled** [comment]
Would using a distinct query here instead work better?

**Comment by Xcelled** [comment]
Looks like distinct would work better for MySQL... but Sqlite doesn't support it.

Give this version a try: https://github.com/Xcelled/PokemonGo-Map/tree/spawnpoint_groupby

Let me know if that fixes it. I don't have a MySQL server installed to test on.

**Comment by hemsleyk** [comment]
MySQL 5.7 is so unstable their official Docker image doesn't follow its own documentation for environment variables. Might just want to pin to 5.6 or even better use MariaDB as a drop-in or even implement PostGres support.

**Comment by hightechstl** [comment]
simply login to mysql, select your database and run SET sql_mode = '';
