### ISSUE TITLE
Scanned Locations green rings not working

### ISSUE THREAD

**Issue by jtp10181** [PokemonGoMap/PokemonGo-Map#613]
## Expected Behavior
Scanned location rings to work like they used to

## Current Behavior
Scanned location rings seem to only show the last one when the server was shut down last. No new updates are shown.
I checked my pip requirements
Ran npm cache clean and npm update
I cleared the DB
Issue still persists

## Steps to Reproduce (for bugs)

1. Run a scan with showing Scanned Locations enabled

## Your Environment

* Version used: https://github.com/PokemonGoMap/PokemonGo-Map/commit/f56f3f42efe550495492a0231865467ac96e4305
* Environment name and version (e.g. Python 2.7): Python 2.7
* Operating System and version (desktop or mobile): Windows 7

**Comment by jtp10181** [comment]
I went back to this commit and it works here: https://github.com/PokemonGoMap/PokemonGo-Map/commit/018eaa8fb611079078e8ac42c085640825d99919

Now I just have to merge the pause thread PR in and I will be up and running again

**Comment by DeeFox** [comment]
Were you able to identify the commit that broke this feature? I just cant find it :(

**Comment by moggd** [comment]
Same issue

**Comment by StevasaurousREX** [comment]
I have the same issue and my last pull was c5e0970

**Comment by justsomedudeonthenet** [comment]
I too am seeing the same issue on f541ac564e57cf737974427d499582a170c9f50f

**Comment by demesg** [comment]
On Windows you can run this:
npm run build

**Comment by moggd** [comment]
Anything else I need to do after that?  Still not working after grunt build

**Comment by StevasaurousREX** [comment]
Just did a fresh pull (brand new folder) using SQLite there is no issue with the scanned locations showing up.

In my actual map (where the issue occurs) I use MySQL, can anyone else confirm they are using MySQL and getting this issue?

**Comment by Stupefy** [comment]
Same issue, only one bubble ever shows up (bubble selected to show changes based on visible area)

**Comment by kev007** [comment]
After my pull I ran:
```
pip install -r requirements.txt --upgrade
npm install
npm run build
```
and got the scanned locations to show up correctly.

**Comment by DeeFox** [comment]
Yup, I think this can be closed. I just forgot to rebuild the distributed javascript files via
`npm run build`.
This obviously has to be done after every pull that involved new js files 👍

**Comment by Morkai-bde** [comment]
Thanks, it works now, Being quite lazy I added it to a batch file :P

**Comment by XiAn0x** [comment]
Still running into the same issue. Tried to rebuild and all but no success

**Comment by jtp10181** [comment]
I will try that out when I get home. I didn't know run build was needed
after an update.

**Comment by christiancoleman** [comment]
Running 'npm install' after retrieving the latest pull just fixed it for me. Thank you!

**Comment by 360bladez** [comment]
I tried everything suggested and seem to be having the same issue :(

**Comment by moggd** [comment]
I got mine to work after trying everything here and not having any success.  Here is what I needed to do.

I had my lat/lon location in my .bat script like this "39.xxxxx, -77.xxxxx".  Removing the comma so it was like "39.xxxxx -77.xxxxx" allowed it to work again.

**Comment by jtp10181** [comment]
Ok I updated my develop branch again, and ran the following:

```
pip install -r requirements.txt --upgrade
npm cache clean
npm update
```

It is now working fine, not sure what changed
I also then ran "npm run build" and it still works after that.

@moggd - I had the GPS saved in my config file with the comma, I took it out and it worked, I put it back in and it still worked. So I dont think thats what really fixed it.

Seems like a clean install should fix it.

Anyone else having issues? Otherwise I am going to close this tomorrow.

**Comment by 360bladez** [comment]
Yes I am still having this issue.

**Comment by jtp10181** [comment]
Make sure you have a clean version of develop, and also you could try to delete the "node_modules" directory and then run "npm install" again which will rebuild that folder.

The the last thing I can think of to try.

**Comment by olieske** [comment]
I had the same problem and did all the suggested steps.
It did not work until I reloaded the map in the browser!
