### ISSUE TITLE
[      MainThread][     runserver][CRITICAL] It seems `pgoapi` is not up-to-date. You must run pip install -r requirements.txt again

### ISSUE THREAD

**Issue by shiznewski** [PokemonGoMap/PokemonGo-Map#615]
2016-08-13 11:06:06,294 [      MainThread][     runserver][CRITICAL] It seems `pgoapi` is not up-to-date. You must run pip install -r requirements.txt again

I ran git pull a few minutes ago so i could ge tthe update to fix the 594 hours problem. And now i get this. i have ran git pull, pip install -r requirements.txt and npm install, grunt build server times. i can't get it to work.

any idea?

**Comment by jtp10181** [comment]
Try:
`pip install -r requirements.txt --upgrade`

**Comment by shiznewski** [comment]
Thanks. i tried it and it looks like it updated everything still same problem. I won't tie up the issues area. i'll try to get on discord.

**Comment by shiznewski** [comment]
i switched the pgoapi line in requirements.txt to whats below. then ran pip. and it created a /src folder that wasn't there and now it works.
-e git://github.com/keyphact/pgoapi.git@60096ccfea0a97e5358be1d32283ebbfb853b00a#egg=pgoapi
