### ISSUE TITLE
[      MainThread][     runserver][CRITICAL] It seems `pgoapi` is not up-to- date. You must run pip install -r requirements.txt again 

### ISSUE THREAD

**Issue by Slowmoney** [PokemonGoMap/PokemonGo-Map#617]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Python 2.7):
* Operating System and version (desktop or mobile):

**Comment by jtp10181** [comment]
This is not for support questions

**Comment by chuyskywalker** [comment]
#615
