### ISSUE TITLE
Got banned IP , how to run proxy HideMyAss command? example account "acc" pass "pass".

### ISSUE THREAD

**Issue by lacyleo** [PokemonGoMap/PokemonGo-Map#618]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Python 2.7):
* Operating System and version (desktop or mobile):

**Comment by chuyskywalker** [comment]
This is not a support forum; please see [the discord #help channel](https://discord.gg/npVqkUn) for assistance.
