### ISSUE TITLE
Steps to perform "grunt build" properly

### ISSUE THREAD

**Issue by lungbubble** [PokemonGoMap/PokemonGo-Map#62]
[           MainThread][      runserver][CRITICAL] Please run "grunt build" before starting the server
I can't find what folder I'm supposed to do that in.  I am not aware of any particular step by step process to go through this such that I can actually type "grunt build" and get it to work.  Its not in the wiki.  Anyone who can help me go through this process?

**Comment by andrewda** [comment]
Just run `grunt build` from the repository's main directory.

**Comment by lungbubble** [comment]
....ummm....that doesn't work....ming reopening please?

**Comment by lungbubble** [comment]
Umm...is that some kind of joke?

**Comment by andrewda** [comment]
@lungbubble Use the discord server for support. Issues are for PokemonGo-Map-related issues only.

**Comment by Sejadis** [comment]
well it should probably be added to the wiki as it is really not clear what to do where if you get this error message  - so its kinda a issue
