### ISSUE TITLE
595 Hour Expiration on PokeSTOPS as well

### ISSUE THREAD

**Issue by jameson167** [PokemonGoMap/PokemonGo-Map#620]
Thank you for all the great work on the pogom as well as a speedy fix on the 595hour pokemon expiration bug. I have updated my systems to use the latest commit https://github.com/PokemonGoMap/PokemonGo-Map/commit/f541ac564e57cf737974427d499582a170c9f50f as of 2-hours ago. 

![image](https://cloud.githubusercontent.com/assets/20566412/17644386/20d00e8c-613a-11e6-923b-30262e693521.png)

## Current Behavior
All the stacked 595hr pokemon have been removed from the map and that issue seems fixed. However I am still stuck with many 500hr+ pokestops. 

## Possible Solution
Is this just a matter of the old ones needing to be manually removed from the database or do we still need a fix in the code as well?

## Your Environment

* Version used: 3.1.0 develop updated as of 2-hours ago
* Environment name and version (e.g. Python 2.7): Python 2.7
* Operating System and version (desktop or mobile): Windows Server 2012

**Comment by maaim** [comment]
Try stopping the scan.  Delete the pogom.db file if you're using the default DB and restart the scan.  That should clear the 595+ locations.

**Comment by jameson167** [comment]
I have a MariaSQL database setup called pokemongomapdb. I can delete the entries from there but have they already resolved the issue that would cause new occurrences from happening?

**Comment by angrymoose** [comment]
They have stated its been fixed in the update logs.
