### ISSUE TITLE
Uncaught TypeError: $(...).accordion is not a function

### ISSUE THREAD

**Issue by hklcf** [PokemonGoMap/PokemonGo-Map#622]
![image](https://cloud.githubusercontent.com/assets/410302/17644654/1b595956-61bf-11e6-8336-2cd55e0b4304.png)

http://server_ip/stats

**Comment by Studio-XP** [comment]
It's caused by jQueryUI not being loaded into that page. Not sure if it needs to be added though, because it's not being utilized from within the page itself (just being referenced within the map.min.js)

**Comment by DiscoTim** [comment]
i think its caused by #nav-accordian not being in the stats page. i changed the map js like this

if ( $( "#nav-accordion" ).length ) {
  $("#nav-accordion").accordion({
    active: false,
    collapsible: true
  });
