### ISSUE TITLE
Manifest.yml deployment not pulling latest updates

### ISSUE THREAD

**Issue by elitraminsky** [PokemonGoMap/PokemonGo-Map#624]
deployment that work with cloudfoundry based PaaS (ie Jelastic, Scalingo) doesn't seem to be pulling latest pogom. Maps not functioning.

**Comment by yannski** [comment]
Scalingo is not based on Cloudfoundry and does not read the Manifest.yml file.

**Comment by BaIthamel** [comment]
This is not a support forum; please see [the discord #help channel](https://discord.gg/npVqkUn) for assistance.
