### ISSUE TITLE
scanning point #575

### ISSUE THREAD

**Issue by Yuk111** [PokemonGoMap/PokemonGo-Map#630]
> This is not a support forum; please see the discord #help channel for assistance.
https://goo.gl/photos/ivNM8vJLa4oAuFki7
I can not enter

Google translator
The invitation has expired or has an error.

Please give the correct link :(

**Comment by Yuk111** [comment]
sorry :(

**Comment by Becold** [comment]
https://discord.gg/YJgTz 24h link

**Comment by Yuk111** [comment]
https://goo.gl/photos/Uk1z13uL2watn9pM8 
does not work
I can be blocked on the channel?
please unlock me

**Comment by Yuk111** [comment]
https://goo.gl/photos/fPyuc4nVjLzJSQmDA
and so does not go

**Comment by FrostTheFox** [comment]
What is your username on discord?

**Comment by Yuk111** [comment]
user0000001 or user#0157

**Comment by FrostTheFox** [comment]
Try now.

**Comment by Yuk111** [comment]
big thank 
everything worked out
