### ISSUE TITLE
how to undo the update

### ISSUE THREAD

**Issue by puredota** [PokemonGoMap/PokemonGo-Map#631]
I updated using git pull and pip install -r requirements.txt --upgrade

How can I undo this update?

**Comment by kev007** [comment]
`$ git reset --hard $SHA1`
Use the SHA of the commit to reset to that specific code version.
![image](https://cloud.githubusercontent.com/assets/3058438/17646116/336d59ec-61bb-11e6-88cd-99278b4cb8c4.png)

**Comment by puredota** [comment]
This cause problem. 
$ git reset --hard a2d12ec
HEAD is now at a2d12ec Built assets
Then all the scan is warning: table pokestop has no column name active pokemon id......

**Comment by kev007** [comment]
Try deleting your database (*.db file)

**Comment by puredota** [comment]
It works!

Thank you very much.

**Comment by kev007** [comment]
Nice. Don't forget to close the issue.
