### ISSUE TITLE
Where is the documentation supposed to be?

### ISSUE THREAD

**Issue by Chlodochar** [PokemonGoMap/PokemonGo-Map#635]
I expected a link to the documentation in `README.md`. There wasn't.

~~Then I expected the documentation to be linked on the home page. It wasn't.~~

~~Then I expect `docs/` to contain documentation that is navigable on Github. It wasn't.~~

Where should people find the documentation?
Was is hosted on readthedocs before, but was removed due to the move? I'm not sure what the intended way to read the documentation is. If I know that I can take steps to fix the problem.

**Comment by MWin123** [comment]
There is a link to the documentation under "Wiki".

Linking it in README.md is a good idea.

**Comment by Chlodochar** [comment]
#636 fixes this issue.

**Comment by FrostTheFox** [comment]
readd the twitter pleb
