### ISSUE TITLE
Pokemon Disappear-Counter shows large numbers

### ISSUE THREAD

**Issue by zideshowbob** [PokemonGoMap/PokemonGo-Map#647]
## Current Behavior
Pokemons show a loooong time (500 hrs)

http://imgur.com/Lfb2Qdq

Is this normal? Did not have the chance to check it out...

**Comment by clifford2006** [comment]
Did you try updating to latest version v3.1.0? It has already been fixed for me after updating not long ago.

**Comment by secondhandnudes** [comment]
Could you please provide link to this latest version? I'm on 0.2.1 and don't see a newer one out there

**Comment by clifford2006** [comment]
Here you go https://github.com/PokemonGoMap/PokemonGo-Map/releases/tag/v3.1.0

**Comment by secondhandnudes** [comment]
Thank you so much! Sorry for what is probably another dumb question, but when I download this, I'm not seeing the exe file to run this. What do I need to do in order to get this one running?

**Comment by clifford2006** [comment]
Thats weird, I wonder how you install your previous version but they did provide a video tutorial in thier link: https://www.youtube.com/watch?v=2ACJHCNZ3ow , and thats the only way I currently know.

**Comment by secondhandnudes** [comment]
I originally installed it via this download: https://pokemon-go-updater.mike.ai/download

From this github: https://github.com/mchristopher/PokemonGo-DesktopMap

Just downloaded the file and followed a couple easy steps. I guess maybe I need to wait for that one to update to newest in order to keep doing it that way

**Comment by clifford2006** [comment]
These two are completely different project and I think you got the wrong place in search of solution. You should go back to their project and ask for solution there.

**Comment by eluarca1971** [comment]
C:\Users\<UserName>\AppData\Roaming\ there delete the Folder: "Pokemon Go Live Map" there is where the app stores the Access data and the log of pokemon located in the time. once that, reinstall the app and input your acces data (Google Key and coordinates) Note: BEFORE the uninstall be sure that you have write down at least your Google Key) I know that this is a not programming soultion, but at least that give you tme to find the real solution. I hope that this can help you.

**Comment by eluarca1971** [comment]
Hi, as a temporal solution: uninstall Pokemon go Live map. Don't reinstall yet, ho to: C:\Users<UserName>\AppData\Roaming\ there delete the Folder: "Pokemon Go Live Map" there is where the app stores the Access data and the log of pokemon located in the time. once that, reinstall the app and input your acces data (Google Key and coordinates) Note: BEFORE the uninstall be sure that you have write down at least your Google Key) I know that this is a not programming soultion, but at least that give you tme to find the real solution. I hope that this can help you.

**Comment by eluarca1971** [comment]
Hi, as a temporal solution: uninstall Pokemon go Live map. Don't reinstall yet, go to: C:\Users<UserName>\AppData\Roaming\ there delete the Folder: "Pokemon Go Live Map" there is where the app stores the Access data and the log of pokemon located in the time. once that, reinstall the app and input your acces data (Google Key and coordinates) Note: BEFORE the uninstall be sure that you have write down at least your Google Key) I know that this is a not programming soultion, but at least that give you tme to find the real solution. I hope that this can help you.

**Comment by BaIthamel** [comment]
This is not a support forum; please see [the discord #help channel](https://discord.gg/npVqkUn) for assistance.

This SHOULD be fixed
python runserver.py -cd
SHOULD fix it if you still have database entries
it was the 595 bug for a reason, all these 470's suggest old 595's that have been sitting in your database for a few days.
