### ISSUE TITLE
Frontend really slow when > 30 users connected

### ISSUE THREAD

**Issue by mugabemkomo** [PokemonGoMap/PokemonGo-Map#649]
On my server when more than 30 users are connected the loading of new Pokemon takes from 10s to 30s. The writing to the mysql database is fast (from search.py), but the web front end takes forever. 
The CPU/RAM is definitely not the bottleneck.
I use mysql and run the webserver seperatly with runserver.py -pd 24 -os --db-max_connections 100
I have about 12k spawn points in my spawns.jason.

**Comment by TachyonRSA** [comment]
You running a reverse proxy or just straight?

**Comment by mugabemkomo** [comment]
Apache2 with reverse proxy port 80, no redirect.
I can try direct when i am back home.

**Comment by mugabemkomo** [comment]
It does not matter, I tried with -H 0.0.0.0 it is just as slow.

**Comment by chuyskywalker** [comment]
This is not a support forum; please see [the discord #help channel](https://discord.gg/npVqkUn) for assistance.

**Comment by Pokeme5005** [comment]
mugabemkomo, did you ever find a solution to your problem? I have about 50 users -- all friends family, co-workers using my map that covers the entire city. The more people that connect, the longer it takes for pokemon to populate on the map. I thought #1303 would have fixed it -- it helped, but still getting the same problem. I best guess is, I I think the webserver is not designed for this many users with that many spawnpoints, am I correct? Need to switch to websockets or something?
