### ISSUE TITLE
scan delay

### ISSUE THREAD

**Issue by Zerotask** [PokemonGoMap/PokemonGo-Map#650]
What is the best scan delay you can use right now? a scan delay of 10 is really slow

**Comment by Linwood-WP** [comment]
I have 5 it's work, i found pokemons

**Comment by CtrlAltDefeat94** [comment]
@Linwood-WP but not all. as AFAIK only one request per 7 seconds(per account) gets through

**Comment by chuyskywalker** [comment]
This is not a support forum; please see [the discord #help channel](https://discord.gg/npVqkUn) for assistance.
