### ISSUE TITLE
Update to new version on jelastic

### ISSUE THREAD

**Issue by fasteX89** [PokemonGoMap/PokemonGo-Map#652]
Hi, I'm using jelastic to ost this scanner but there is still the bug with the long disappear time and the scanner cant show spawn points how do i update the scanner?

**Comment by HardTacos** [comment]
Jelastic is most likely being IP banned. This is probably your issue

**Comment by fasteX89** [comment]
No its not scanning still works but its the old version of pokemongo-map not the new one. There is still the bug where pokemons wont disappear and there is no option to show spawn points etc

**Comment by BradPat** [comment]
Can you please update the jelastic release for the latest version? I really would like to use the spawnpoint scanning on jelastic, but it is not working right now.
