### ISSUE TITLE
Could not install requirements lib

### ISSUE THREAD

**Issue by trungp** [PokemonGoMap/PokemonGo-Map#653]
Hi,

I faced a issue when installing, I follow the steps in this tutorial:  https://pgm.readthedocs.io/en/develop/basic-install/index.html

I use Mac OSX El Capitan 10.11.4
Python 2.7.10
pip 8.1.2 from /Library/Python/2.7/site-packages (python 2.7)

Here it the logs trace, the failure always occurred on step 27:

    Downloading https://pypi.python.org/packages/f5/47/2e39972c41eb988d551bb2da25c4ee16ea78492ec1b6ffdf09f50cd09b92/coverage-4.2.zip#md5=9841c9e1ddc862144fda3fd7e5ba5106
    Processing coverage-4.2.zip
    Writing /tmp/easy_install-K5Eofe/coverage-4.2/setup.cfg
    Running coverage-4.2/setup.py -q bdist_egg --dist-dir /tmp/easy_install-K5Eofe/coverage-4.2/egg-dist-tmp-nF5w81
    warning: no previously-included files found matching 'ci/appveyor.token'
    no previously-included directories found matching 'doc/_build'
    no previously-included directories found matching 'tests/eggsrc/build'
    no previously-included directories found matching 'tests/eggsrc/dist'
    no previously-included directories found matching 'tests/eggsrc/*.egg-info'
    warning: no previously-included files matching '*.py[co]' found anywhere in distribution
    
    Installed /private/tmp/pip-build-0tNj92/protobuf-to-dict/coverage-4.2-py2.7-macosx-10.11-intel.egg
    Searching for nose>=1.0
    Reading https://pypi.python.org/simple/nose/
    Best match: nose 1.3.7
    Downloading https://pypi.python.org/packages/58/a5/0dc93c3ec33f4e281849523a5a913fa1eea9a3068acfa754d44d88107a44/nose-1.3.7.tar.gz#md5=4d3ad0ff07b61373d2cefc89c5d0b20b
    Processing nose-1.3.7.tar.gz
    Writing /tmp/easy_install-7_68LW/nose-1.3.7/setup.cfg
    Running nose-1.3.7/setup.py -q bdist_egg --dist-dir /tmp/easy_install-7_68LW/nose-1.3.7/egg-dist-tmp-7A8DKb
    no previously-included directories found matching 'doc/.build'
    
    Installed /private/tmp/pip-build-0tNj92/protobuf-to-dict/nose-1.3.7-py2.7.egg
    Searching for protobuf>=2.3.0
    Reading https://pypi.python.org/simple/protobuf/
    Best match: protobuf 3.0.0
    Downloading https://pypi.python.org/packages/e7/ff/df198f342f1b6e71be00a4601973297c0399f112327e8d5e48595ba95fe9/protobuf-3.0.0-py2.7.egg#md5=a2aa47b202784121a3d8ea17daee5e25
    Processing protobuf-3.0.0-py2.7.egg
    creating /private/tmp/pip-build-0tNj92/protobuf-to-dict/protobuf-3.0.0-py2.7.egg
    Extracting protobuf-3.0.0-py2.7.egg to /private/tmp/pip-build-0tNj92/protobuf-to-dict
    
    Installed /private/tmp/pip-build-0tNj92/protobuf-to-dict/protobuf-3.0.0-py2.7.egg
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/tmp/pip-build-0tNj92/protobuf-to-dict/setup.py", line 25, in <module>
        'Topic :: Software Development :: Libraries :: Python Modules',
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/dist.py", line 239, in __init__
        self.fetch_build_eggs(attrs.pop('setup_requires'))
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/dist.py", line 263, in fetch_build_eggs
        parse_requirements(requires), installer=self.fetch_build_egg
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 580, in resolve
        raise VersionConflict(dist,req) # XXX put more info here
    pkg_resources.VersionConflict: (six 1.4.1 (/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python), Requirement.parse('six>=1.9'))
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-build-0tNj92/protobuf-to-dict/

Could anyone help me to resolve this isssue?

**Comment by skylightning** [comment]
Have you tried with "sudo -H" ?

**Comment by itsmabus** [comment]
I am getting the same error, even when running it with sudo -H

**Comment by heliosfa** [comment]
Read the last line as it tells you what the issue is - you have an old version of six installed.

Try removing it or passing the -U flag to pip to trigger an upgrade.

**Comment by felixvd** [comment]
Discord mentioned that OS X does not allow upgrading six so you'll have to set up a virtual environment.

**Comment by ingtellect** [comment]
It happened to me also. I removed six from requirements.txt and manually upgraded six by 
`pip install --ignore-installed six`

**Comment by akc2267** [comment]
use:

sudo easy_install six
will upgrade six.

reason:

mac already have six module in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/six.py,

when use pip, six module will install in /Library/Python/2.7/site-packages,

use the easy_install will change the lib path for six.
