### ISSUE TITLE
scanned locations are not shows

### ISSUE THREAD

**Issue by korchevskiy** [PokemonGoMap/PokemonGo-Map#655]
map does not show all scanned locations, currently it show only one: http://bit.ly/2bh2pRR
it does not work on mobile, chrome, ff.
db: mysql.
version(git commit): d77a7024e312de59089b41105bd8f2c076eccb07 
there is no errors in the logs.

maybe there is just need to add some field to mysql tables. Please let me know how I can resolve this issue.

**Comment by jtp10181** [comment]
Check this thread out
https://github.com/PokemonGoMap/PokemonGo-Map/issues/613

**Comment by hightechstl** [comment]
issue resolved in #613 by simply running npm run build

tested and confirmed it to fix mine also

**Comment by korchevskiy** [comment]
thanks. it works.
