### ISSUE TITLE
not using the -dc option but still displaying found pokemon in console

### ISSUE THREAD

**Issue by UwV2000** [PokemonGoMap/PokemonGo-Map#663]
## Expected Behavior

no dsiplay of found pokemon when not using the -dc option
## Current Behavior

displaying found pokemon in concole while not using the -dc option
## Steps to Reproduce (for bugs)

1.  run runserver.py  without -dc

## Your Environment

develop branch
Python 2.7
desktop W10 x64

**Comment by Zegorax** [comment]
I'm running the server without -dc and everything is working fine

**Comment by imynwulf** [comment]
Include a log or screenshot?

**Comment by UwV2000** [comment]
my bad .. 
 I just remembered .. the flag is still enabled in my .config 
 didn't open it since using a .bat to call instances ..  so all instances where showing found pokemon now .
NO ISSUE ..
