### ISSUE TITLE
Pokestop incorrect lure time

### ISSUE THREAD

**Issue by nicktan147** [PokemonGoMap/PokemonGo-Map#665]
Pokestops lure showing incorrect timing. I'm at the pokestop shown on the map but the map shows incorrect pokemap lure time expire. I tried clearing my db, but still the same. Anyone has the issue like me?
![12](https://cloud.githubusercontent.com/assets/7764638/17650156/20fc7f36-6279-11e6-9c50-dfa2b6ab3629.jpg)

**Comment by rrbailey89** [comment]
I just checked. Mine showed expired, then I refreshed the page and got what seem to be correct times. I was unable to test but it looked good. 

I notice your icons are different than whats in the repo, did you change them or are you possibly on a much older version?

**Comment by nicktan147** [comment]
@rrbailey89 I just change those icons, nothing else change.

**Comment by FroznArrow** [comment]
#555 
Apply this fix, worked for me

**Comment by nicktan147** [comment]
@FroznArrow I tried, doesn't work.
