### ISSUE TITLE
[Question/Feature Request] Scan Multiple Location

### ISSUE THREAD

**Issue by Lionir** [PokemonGoMap/PokemonGo-Map#668]
Is it possible to scan multiple locations and if so, how? If not, please make it a feature.

**Comment by felixvd** [comment]
Call the script again with the parameter -ns and a different username and location. This will start an additional search process without a webserver.

**Comment by mugabemkomo** [comment]
Or just use this like everyone :)
https://www.reddit.com/r/pokemongodev/comments/4wxteh/i_implemented_tbterras_spawntracker_into/?sort=new

**Comment by Lionir** [comment]
@felixvd so basically, I run multiple instances but add -ns?

**Comment by Lionir** [comment]
@mugabemkomo I want to scan locations which are very far apart but I'm already using Spawnpoints only, thanks for the recommendation though.

**Comment by mugabemkomo** [comment]
Maybe you should consider putting the accounts not in the config but in the command line to avoid bans if they are like "jumping" from one place to another. You can just run multiple instances yes -ns only starts the worker

**Comment by Lionir** [comment]
@mugabemkomo Seems fair. We can close this now. It should be in the documentation though.

**Comment by Lionir** [comment]
"Database is locked...", Why does it do that?

**Comment by Cy4n1d3** [comment]
SQLite?

**Comment by Lionir** [comment]
@Cy4n1d3 Well, that's the default, right? If so, yeah.

**Comment by Cy4n1d3** [comment]
Yes, that's the default. If you are running more than a couple of workers, the SQLite database is choking.
You might have to consider switching to MySQL.
