### ISSUE TITLE
npm install not working

### ISSUE THREAD

**Issue by Maximus0205** [PokemonGoMap/PokemonGo-Map#673]
when i try to do "npm install" the console putting out this: C:\Users\magnus\PokemonGo-Map>npm install
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Users\magnus\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js" "install"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.6
npm ERR! file C:\Users\magnus\AppData\Roaming\npm-cache\es6-iterator\2.0.0\package\package.json
npm ERR! code EJSONPARSE

npm ERR! Failed to parse json
npm ERR! Unexpected token '\u0000' at 1:1
npm ERR!
npm ERR! ^
npm ERR! File: C:\Users\magnus\AppData\Roaming\npm-cache\es6-iterator\2.0.0\package\package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR!
npm ERR! This is not a bug in npm.
npm ERR! Tell the package author to fix their package.json file. JSON.parse

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\magnus\PokemonGo-Map\npm-debug.log
[npm-debug.pdf](https://github.com/PokemonGoMap/PokemonGo-Map/files/417244/npm-debug.pdf)

**Comment by StevasaurousREX** [comment]
Try `npm cache clean`

**Comment by andyw1123** [comment]
i have the same issue, that hasnt solved it

**Comment by Maximus0205** [comment]
Oh think i find the error. Just run the node cmd as administrator and it should work :)
