### ISSUE TITLE
Won't run on Mac with installation guide

### ISSUE THREAD

**Issue by martinverup** [PokemonGoMap/PokemonGo-Map#675]
It seems like something is missing in the installation guide for Mac users.
I get this error when running runserver.py

> Traceback (most recent call last):
>   File "./runserver.py", line 10, in <module>
>     import requests
>   File "/usr/local/lib/python2.7/site-packages/requests/__init__.py", line 60, in <module>
>     from .packages.urllib3.exceptions import DependencyWarning
>   File "/usr/local/lib/python2.7/site-packages/requests/packages/__init__.py", line 29, in <module>
>     import urllib3
>   File "/usr/local/lib/python2.7/site-packages/urllib3/__init__.py", line 8, in <module>
>     from .connectionpool import (
>   File "/usr/local/lib/python2.7/site-packages/urllib3/connectionpool.py", line 35, in <module>
>     from .connection import (
>   File "/usr/local/lib/python2.7/site-packages/urllib3/connection.py", line 15, in <module>
>     from httplib import HTTPConnection as _HTTPConnection
>   File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 80, in <module>
>     import mimetools
>   File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/mimetools.py", line 6, in <module>
>     import tempfile
>   File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/tempfile.py", line 32, in <module>
>     import io as _io
>   File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/io.py", line 51, in <module>
>     import _io
> ImportError: dlopen(/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_io.so, 2): Symbol not found: __PyCodecInfo_GetIncrementalDecoder
>   Referenced from: /usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_io.so
>   Expected in: flat namespace
>  in /usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_io.so

It seems like this is caused by a difference in requests installed by pip vs apt-get

**Comment by klamouri** [comment]
Did you run : `pip install -r requirements.txt --upgrade` ?

**Comment by f3st3r113** [comment]
@klamouri I have run the pip install -r raquirements.txt --upgrade and still get an error message `from flask_compress import Compress
ImportError: No module named flask_compress`

**Comment by klamouri** [comment]
Try `python --version` and `pip --version` and post result. Does the flask error occur during the installation of the requirements or with runserver ?

**Comment by f3st3r113** [comment]
Python Version
`Python 2.7.12`

PIP Version
`pip 8.1.2 from /usr/local/lib/python2.7/site-packages (python 2.7)`

I experience this when trying runserver.

**Comment by dontfight** [comment]
are you using https for webhook?
check python openssl version
`python -c "import ssl; print ssl.OPENSSL_VERSION"`

make sure it's up to date. and you will be go to go.

**Comment by f3st3r113** [comment]
`OpenSSL 0.9.8zh 14 Jan 2016`

So how do I update?

**Comment by HutchCreative** [comment]
I'm having a similar issue on Macbook Pro, but I've got it working perfectly on PC.

When I run the command `python runserver.py` I get the following error:
`!ng: event not found`

**Comment by HutchCreative** [comment]
I'm having a similar issue. This is the error i get when I do the run command:

`Traceback (most recent call last):
  File "runserver.py", line 24, in <module>
    from pogom.search import search_overseer_thread, fake_search_loop
  File "/Users/o0omeggsyo0o/Documents/PokemonGo-Map/pogom/search.py", line 29, in <module>
    from pgoapi import PGoApi
  File "/usr/local/lib/python2.7/site-packages/pgoapi/__init__.py", line 50, in <module>
    from pgoapi.pgoapi import PGoApi
  File "/usr/local/lib/python2.7/site-packages/pgoapi/pgoapi.py", line 34, in <module>
    from pgoapi.rpc_api import RpcApi
  File "/usr/local/lib/python2.7/site-packages/pgoapi/rpc_api.py", line 50, in <module>
    from POGOProtos.Networking.Envelopes_pb2 import RequestEnvelope
  File "/usr/local/lib/python2.7/site-packages/pgoapi/protos/POGOProtos/Networking/Envelopes_pb2.py", line 16, in <module>
    from POGOProtos.Networking import Requests_pb2 as POGOProtos_dot_Networking_dot_Requests__pb2
  File "/usr/local/lib/python2.7/site-packages/pgoapi/protos/POGOProtos/Networking/Requests_pb2.py", line 23, in <module>
    ENCOUNTER\x10\x91\x01\x12!\n\x1c\x43OLLECT_DAILY_DEFENDER_BONUS\x10\x92\x01\x12\x14\n\x0fUPGRADE_POKEMON\x10\x93\x01\x12\x19\n\x14SET_FAVORITE_POKEMON\x10\x94\x01\x12\x15\n\x10NICKNAME_POKEMON\x10\x95\x01\x12\x10\n\x0b\x45QUIP_BADGE\x10\x96\x01\x12\x19\n\x14SET_CONTACT_SETTINGS\x10\x97\x01\x12\x15\n\x10GET_ASSET_DIGEST\x10\xac\x02\x12\x16\n\x11GET_DOWNLOAD_URLS\x10\xad\x02\x12\x1c\n\x17GET_SUGGESTED_CODENAMES\x10\x91\x03\x12\x1d\n\x18\x43HECK_CODENAME_AVAILABLE\x10\x92\x03\x12\x13\n\x0e\x43LAIM_CODENAME\x10\x93\x03\x12\x0f\n\nSET_AVATAR\x10\x94\x03\x12\x14\n\x0fSET_PLAYER_TEAM\x10\x95\x03\x12\x1b\n\x16MARK_TUTORIAL_COMPLETE\x10\x96\x03\x12\x16\n\x11LOAD_SPAWN_POINTS\x10\xf4\x03\x12\t\n\x04\x45\x43HO\x10\x9a\x05\x12\x1b\n\x16\x44\x45\x42UG_UPDATE_INVENTORY\x10\xbc\x05\x12\x18\n\x13\x44\x45\x42UG_DELETE_PLAYER\x10\xbd\x05\x12\x17\n\x12SFIDA_REGISTRATION\x10\xa0\x06\x12\x15\n\x10SFIDA_ACTION_LOG\x10\xa1\x06\x12\x18\n\x13SFIDA_CERTIFICATION\x10\xa2\x06\x12\x11\n\x0cSFIDA_UPDATE\x10\xa3\x06\x12\x11\n\x0cSFIDA_ACTION\x10\xa4\x06\x12\x11\n\x0cSFIDA_DOWSER\x10\xa5\x06\x12\x12\n\rSFIDA_CAPTURE\x10\xa6\x06\x62\x06proto3')
TypeError: __init__() got an unexpected keyword argument 'syntax'`

**Comment by charlie5188** [comment]
same here, 
`Python 2.7.12` 
`pip 8.1.2 from /usr/local/lib/python2.7/site-packages (python 2.7)`
`OpenSSL 1.0.2g  1 Mar 2016`

**Comment by cvharris** [comment]
After installing the prereqs and following the installation instructions it was still necessary for me to log out of my terminal and log back in for changes to `python` to take effect. Try this if you were stuck like me 😄
