### ISSUE TITLE
Bluemix wiki guide is garbage

### ISSUE THREAD

**Issue by rrbailey89** [PokemonGoMap/PokemonGo-Map#676]
## Expected Behavior

The ability to follow a step by step guide and get a successful distribution setup and running
## Current Behavior

The current wiki setup leaves things to be desired. It seems that it is missing steps or outdated. The instructions are unclear and need to be adjusted or rewritten.
## Possible Solution

Rewrite the guide so that it can be easily followed.
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Python 2.7):
* Operating System and version (desktop or mobile):

**Comment by itztq** [comment]
try to rewrite it yourself or use the simple one on https://github.com/mchristopher/PokemonGo-DesktopMap

**Comment by FrostTheFox** [comment]
Thats... why it's a wiki. Anyone can go and improve on it.

**Comment by medghaim** [comment]
This issue is garbage.

**Comment by rrbailey89** [comment]
@itztq @FrostTheFox I would happily rewrite it myself if I could figure out how to get it working on bluemix. As I said the wiki leaves things unclear and the average use is unable to get this working there following the wikis tutorial. The purpose of this issue was to bring this to lite and hopefully someone with the proper experience would see the issue and fix the wiki.

**Comment by FrostTheFox** [comment]
@rrbailey89 alright, but the issues here are meant for bugs. someone with the appropriate knowledge can submit a PR and fix it. This issue will just get buried soon and wouldn't help much.
