### ISSUE TITLE
Can't run server? Error inside. (Solved)

### ISSUE THREAD

**Issue by Cindrum** [PokemonGoMap/PokemonGo-Map#685]
C:\Users\Me\Desktop\Poekmon Maps Test\PokemonGo-Map-develop>runserver.py
Traceback (most recent call last):
  File "C:\Users\Me\Desktop\Poekmon Maps Test\PokemonGo-Map-develop\runserver
.py", line 18, in <module>
    from flask_cache_bust import init_cache_busting
ImportError: No module named flask_cache_bust

**Comment by g5bEM6RpSbQF** [comment]
Did you re-run 'sudo pip install -r requirements.txt --upgrade'?

**Comment by Cindrum** [comment]
Thank you! For my last question to apply the patch for " 595+ hour pokemon "

https://github.com/PokemonGoMap/PokemonGo-Map/pull/572          <------ This one. Do I just copy and paste it straight over my old "models.py" file save and run?
