### ISSUE TITLE
Where to go for help

### ISSUE THREAD

**Issue by irus99** [PokemonGoMap/PokemonGo-Map#69]
So before the api update I had this working find with little to no issues even updating the develop branch every time there was an update I would completely redue everything with no issues. But now it seems I just get error after error. I tried to ask but they just closed the issue :/ is there anywhere I can go for help. I would really like to get the map backup before they change the API again :( Thanks for any help you can provide me.

**Comment by invisiblek** [comment]
https://github.com/PokemonGoMap/PokemonGo-Map/blob/develop/README.md

**Comment by andrewda** [comment]
> is there anywhere I can go for help

The discord server.

**Comment by irus99** [comment]
Thanks
