### ISSUE TITLE
[Feature Request] Route requests through TOR network

### ISSUE THREAD

**Issue by Zerotask** [PokemonGoMap/PokemonGo-Map#695]
I saw this PR in the old repo. Would be very nice if you could route automatically all requests through the TOR network (instead of using multiple proxies).

**Comment by elit3ge** [comment]
http://feathub.com/PokemonGoMap/PokemonGo-Map/+43

**Comment by Worthy7** [comment]
No point, tor is basically blocked im speaking from experience (try "sudo torify python runserver")
Sorry, but this is most likely NG.

**Comment by invisiblek** [comment]
This is already possible. Use the --proxy flag after setting up tor.

**Comment by cbig6464** [comment]
Just curious - did anyone actually test if any TOR exit nodes are working with PoGO? Usually TOR exit nodes are among the first IPs to get blocked in any massive online app.
