### ISSUE TITLE
Theres A Mario Sprite

### ISSUE THREAD

**Issue by angrymoose** [PokemonGoMap/PokemonGo-Map#697]
## Summary 

Theres a Mario≠Ash≠Red sprite that does not belong in Pokemon Go. 

Update: Mario≠Ash≠Red has replaced the old marker denoting the area the scan has begun from.

Update2: Appears it's an Ash sprite, makes more sense now.

Update3: Added another name "Red", name will not be changed again as it does not really effect current bug or undocumented change.

## Current Behavior

Mario≠Ash≠Red appears for an unknown reason.

## Possible Solution

Remove Mario≠Ash≠Red or clarify that he is the new marker for scan location.

## Steps to Reproduce (for bugs)

Pull from dev & deploy.

## Context

There is a Mario≠Ash≠Red sprite that appears and has no clear purpose. Affected to the extent of writing a bug report.

## Your Environment

* Version used:
* Environment name and version (e.g. Python 2.7):
* Operating System and version (desktop or mobile):

Ubuntu 16.04 LTS
python 2.7 default ubuntu
Latest pull from dev as of 1:00 pm gmt.

**Comment by Viper2k4** [comment]
Mario tztztz thats ASHE!!!!

**Comment by angrymoose** [comment]
I'll update my post for accuracy, but he's to blurry to really make out.

**Comment by Worthy7** [comment]
lol.

**Comment by aagulto** [comment]
WT...lol
![image](https://cloud.githubusercontent.com/assets/20647076/17665708/94d9e942-62ca-11e6-95d5-5238ea02c37a.png)

**Comment by angrymoose** [comment]
@Worthy7  I've updated the post to reflect the name change once again.

**Comment by cfsamet** [comment]
I would very much like to see the old marker icon back.   Or make this new one optional.   I honestly don't see the point of the new icon.

**Comment by Spacehug** [comment]
@cfsamet I don't see the point of having a marker at all -_-

**Comment by scooterpsu** [comment]
I agree with @Spacehug, there's no point in having one. 

If this leads to an option, please include a "None" to the dropdown.

**Comment by SethG911** [comment]
@Spacehug @scooterpsu There is a point to have one, since you can click on it and drag it around to move the scan location without typing an address. But I really don't like this graphic, please switch it back or add an option.

**Comment by Studio-XP** [comment]
#661 I'll work on a pull request to select from "None", "Default" and "Ash"

**Comment by Spacehug** [comment]
@Studio-XP I humbly request a smaller version (0.5 of the current marker), blue, yellow, and their smaller versions :)

**Comment by HiImMrSalty** [comment]
LOL Mario, did you never play the original pokemon games?

**Comment by hklcf** [comment]
https://www.google.com/search?q=gameboy+pokemon+ash&tbm=isch

**Comment by angrymoose** [comment]
@HiImMrSalty I haven't played pokemon in about a decade..

**Comment by hklcf** [comment]
![image](https://cloud.githubusercontent.com/assets/410302/17732118/e68dfd58-64a2-11e6-9b02-91e2d4f1a2c6.png)
Mario...
