### ISSUE TITLE
500h+ spawn time bug #601 still here

### ISSUE THREAD

**Issue by Raphiki44** [PokemonGoMap/PokemonGo-Map#698]
I delete pogom.db file, run **pip install -r requierement.txt** to clear my map but on new scan, it still appears 500h+ spawn time pokemons. I'm on the latest dev.

![Image](https://cloud.githubusercontent.com/assets/20911989/17665080/e83dc6c0-62f8-11e6-9f61-666af714cd17.png)

## Your Environment
* Version used: Latest dev
* Environment name and version (e.g. Python 2.7): Python 2.7
* Operating System and version (desktop or mobile): Windows 10

**Comment by Worthy7** [comment]
True, it is not fixed, I've noticed this too.

**Comment by Zerotask** [comment]
I have the same with Pokestops.

**Comment by mdnpascual** [comment]
530 hours? Looks like you didn't clear your database. New scans should be 590+ hours

**Comment by Raphiki44** [comment]
No it seems that is a fixed date time that is recorded. I had 590 hours 3 days ago and 530 this afternoon. I just clear my database again, starting a new scan and now I have 524 hours spawn time pokemons. Those who bugs have the same disapear time (see the picture).

**Comment by Raphiki44** [comment]
No it seems that it's a fixed date time for each bugged spawn time. I had 590 hours 3 days ago and 530 this afternoon. I just clear my database again, starting a new scan and now I have 524 hours spawn time pokemons. Those who bugs have the same disapear time (see the picture).

**Comment by Raphiki44** [comment]
EDIT : The pokemons who appear with a 500h+ spawn date time disapear at their own. I couldn't wait and watch my map until they disapear so I couldn't get how long they stay.
Actually I have no 500h+ pokemons on my map, keep in touch.

**Comment by cris11368** [comment]
I am having this same problem. Any fix for this yet?

**Comment by laraoz** [comment]
You can clean all those buggy pokemons from the db adding this to clean_database() on models.py
```
    query = (Pokemon
             .delete()
             .where((Pokemon.disappear_time >
                    (datetime.utcnow() + timedelta(hours=24)))))
    query.execute()
```

**Comment by BaIthamel** [comment]
If you continue to get this issue go to the discord. I had 595 pokes. i now don't have 595 pokes. I'm pretty damn confident they're gone.
