### ISSUE TITLE
Scanning spawnpoints instead of all map

### ISSUE THREAD

**Issue by kamieniarz** [PokemonGoMap/PokemonGo-Map#699]
Hello! I'm a completly newbie so I hope someone can explain or redirect me to the topic I'm interested in. Right now I have a problem with PTC accounts - I used to use bot creating accounts but they're expired due to no email confirmation. Now bot doesn't work couse of captcha so I'm using just a few accounts instead of 50 :( My scan time changed from 2min to over 15min so that sucks.

I wanted to use method using spawn points instead of whole area. I hope that it's familiar to you. Is it available in this map? Or is there any step by step instruction how to implement this method to this map?

**Comment by hagehg** [comment]
it's implemented in the latest dev build. If you allready scanned the whole area for some time (so the spawnpoints are in your pogom.db) then just run the script with the  --spawnpoints-only parameter
