### ISSUE TITLE
[Idea] Proxy list cycling on search exception

### ISSUE THREAD

**Issue by Schwaitz** [PokemonGoMap/PokemonGo-Map#701]
Hello there,

I used this technique for a seperate python project a long while ago. I scraped a list of about 30,000 proxies, checked them for 1000ms timeouts, took those and ran them for a while through a script which made sure that they actually could get data from a source, and added them to a text file. Then, I would run my actual script with that list, cycling through each proxy whenever an exception occured.

The basic pseudo code looks like this:

    list = [] //read proxy list
    proxyIndex = 0

    def grabData:
        while(true):
            try:
                setProxy(list[proxyIndex]) //made up method
                pullData() //made up method
            except:
               proxyIndex++
               grabData()

    grabData()

This would make running servers on AWS / Rackspace / Heroku / etc a lot easier.

Thoughts?

**Comment by Nik0lashka** [comment]
@Schwaitz check this #644

**Comment by Schwaitz** [comment]
@Nik0lashka, looks exactly like what I need. Know when it was forked though? How far behind is it?

**Comment by Nik0lashka** [comment]
@Schwaitz i don't know, we need to wait, but you can test it already if you type in terminal two separate commands:

cd blabladirectorywithPokemonGoMap
git pull https://github.com/PokemonGoMap/PokemonGo-Map refs/pull/644/head

and then do like described here http://stackoverflow.com/a/14046177
