### ISSUE TITLE
ChangeLog

### ISSUE THREAD

**Issue by irus99** [PokemonGoMap/PokemonGo-Map#704]
I know this is not an issue but I didn't know where else to ask. I can't find the updated change log. Do we have an updated one that gets changed every time a new build is pushed? TIA

**Comment by invisiblek** [comment]
No, you'll have to look through the git history (its like an automatic changelog)

**Comment by irus99** [comment]
Thanks for your reply. Where is the git history. I also feel like I may not be using this correctly. I have been just downloading the zip and manually installing everything every time but is there a way to just run git update or something? Sorry for the stupid questions, I am just not very familiar with git.

**Comment by DragorWW** [comment]
+1, please add semver, release and changelog

**Comment by JoshuaGarrison27** [comment]
See here... [https://github.com/PokemonGoMap/PokemonGo-Map/commits/develop](https://github.com/PokemonGoMap/PokemonGo-Map/commits/develop)
