### ISSUE TITLE
[REQUEST] Pokestop & Gym scanning only

### ISSUE THREAD

**Issue by SeeingBlue** [PokemonGoMap/PokemonGo-Map#705]
Can we develop a method to efficiently scan a large area for just Pokestops and Gyms?

**Comment by invisiblek** [comment]
https://github.com/PokemonGoMap/PokemonGo-Map/blob/develop/pogom/utils.py#L115-L117

**Comment by SeeingBlue** [comment]
Great! That's a start. Now how can we setup an EFFICIENT real-time scan over a large area? Beehive is designed for 70m. We need something designed for 700m and I don't think simply changing the radius  is enough to be considered efficient.

**Comment by SeeingBlue** [comment]
Thanks for the help, @BaIthamel
