### ISSUE TITLE
Chrome error while scanning

### ISSUE THREAD

**Issue by kamieniarz** [PokemonGoMap/PokemonGo-Map#706]
Screen: https://s4.postimg.org/9bkn079nx/error.jpg

It says that sth went wrong. See JavaScript console to see details... What to do now?

**Comment by DiscoTim** [comment]
has it ever worked?

in chrome go to more tools > developer tools, and under the console tab, and paste the error in here.

**Comment by kamieniarz** [comment]
Ok I'm a moron :D I copiet wrong gmap api
