### ISSUE TITLE
It doesn't delete old Pokestop and Gym data

### ISSUE THREAD

**Issue by Zerotask** [PokemonGoMap/PokemonGo-Map#707]
I see old Gym icons with "undefined" on my map and Pokestops with undefined time or a huge time like 30h+. It's from previous scans.

**Comment by Schwaitz** [comment]
Why would you want to delete logged gyms / pokestops? Just eases the load on Niantic's servers to not have to scan for 'em.

You can run with the flag --pd (Purge Data).

>   -pd PURGE_DATA, --purge-data PURGE_DATA
>                         Clear pokemon from database this many hours after they
>                         disappear (0 to disable)

**Comment by Zerotask** [comment]
I forgot to say that I've meant lured Pokestops and below the gym info I see "undefined".

**Comment by BaIthamel** [comment]
Broken pokestops is a known issue i'm sure there's another thread about it around here somewhere
