### ISSUE TITLE
Worker sometimes fails "Exceeded maximum connections"

### ISSUE THREAD

**Issue by BaIthamel** [PokemonGoMap/PokemonGo-Map#71]
Will fill this out tomorrow.

![image](https://cloud.githubusercontent.com/assets/10753531/17469148/9f8dc42a-5d26-11e6-9167-e1a5f0b7ad67.png)

![image](https://cloud.githubusercontent.com/assets/10753531/17469262/869d5334-5d28-11e6-9bfe-ea41412a438b.png)

## Steps to Reproduce (for bugs)

1.Run a worker
2.Wait

## Your Environment

* Version used:
* Environment name and version (e.g. Python 2.7):
* Operating System and version (desktop or mobile):
* rPi linux Jessie
* mariadb

**Comment by Infernoman** [comment]
I can concur this happens when using sqlite or there is not enough database connections set on the mysql database.

**Comment by JZ6** [comment]
use mysql

**Comment by invisiblek** [comment]
This happens with mysql as well

**Comment by BaIthamel** [comment]
I am using mariadb mysql

**Comment by JZ6** [comment]
dont use mysql

**Comment by FrostTheFox** [comment]
lel

**Comment by FlarumHostingCo** [comment]
in utlis.py   I edited it to 200 and works fine now with 50 workers.

 parser.add_argument('--db-max_connections', help='Max connections for the database', type=int, default=200)

I'm using MariaDB 10.1 on Ubuntu16.04

**Comment by JZ6** [comment]
>I'm using MariaDB 10.1 on Ubuntu16.04
dont use  MariaDB 10.1 on Ubuntu16.04

**Comment by invisiblek** [comment]
rofl

**Comment by FlarumHostingCo** [comment]
LOL     You missed I said --->  works fine now <----

**Comment by FrostTheFox** [comment]
> JZ6 commented 2 minutes from now: dont use mysql
>JZ6 commented 2 minutes from now: dont use mysql

perfect

**Comment by JZ6** [comment]
jokes i m just scared of issues piling up, gonna close them asap

**Comment by JZ6** [comment]
.remindme comment dont use mysql at 12:32 am

**Comment by invisiblek** [comment]
@FlarumHostingCo even at 200, I think its masking a real issue. I'd be willing to bet you'll hit a point where it'll start failing again.

**Comment by FlarumHostingCo** [comment]
Should make it a PR after every merge

**Comment by marauder37** [comment]
use the feckin manual
`    parser.add_argument('--db-max_connections', help='Max connections for the database', type=int, default=5)`

**Comment by FlarumHostingCo** [comment]
Yeah prolly so invisiblek.  I'll watch for it tomorrow.  Atleast it happens less often.  Bandaid atleast for now.

**Comment by invisiblek** [comment]
Bandaid would be to cronjob restarting your workers every few hours. This is more like giving aspirin for a broken leg. 😜

**Comment by BaIthamel** [comment]
@JZ6 i'll close and merge issues as my main contribution. Keep them from piling up too much.

**Comment by JZ6** [comment]
@FrostTheFox  dont use mysql

**Comment by JZ6** [comment]
@BaIthamel i better not see 600 issues by the end of the week....

**Comment by FrostTheFox** [comment]
@JZ6 use mysql

**Comment by FlarumHostingCo** [comment]
What about MongoDB?

**Comment by FrostTheFox** [comment]
@FlarumHostingCo No.

**Comment by Infernoman** [comment]
can we switch to redis?

**Comment by Infernoman** [comment]
the amount of requests going in with a large map it would make sense

**Comment by JZ6** [comment]
fuck i just got that error too, should ve listended to my own words

**Comment by andrewda** [comment]
@JZ6 dont use mysql

**Comment by valmedia** [comment]
Yes any chance of redis alternative?

**Comment by invisiblek** [comment]
setting db-max_connections insanely high (200) does seem to make the issue...

**Comment by Infernoman** [comment]
also not increasing the default mysql number of connections will do this. I'm at a point now where i also need to increase the open file limit on the server, to increase the mysql connections anymore.

**Comment by BaIthamel** [comment]
@Infernoman check my mytop output definitely not hitting the max of 200 connections on the server.

**Comment by invisiblek** [comment]
Its not connections to your mysql server, its connections from the client (peewee)

https://github.com/coleifer/peewee/blob/master/playhouse/pool.py#L133

I think we need to up our connections, or possibly use something like args.db-max_connections * num_accounts

**Comment by BaIthamel** [comment]
Ah what does max connections default to?

**Comment by invisiblek** [comment]
5. I'm at 100, but its probably overkill. Haven't had an issue since though

**Comment by invisiblek** [comment]
try this: https://github.com/PokemonGoMap/PokemonGo-Map/pull/239

**Comment by BaIthamel** [comment]
OMG default is 5!

**Comment by invisiblek** [comment]
https://github.com/PokemonGoMap/PokemonGo-Map/pull/296

**Comment by SimonTellsAll** [comment]
As mine was a copy #305 - I believe it to be an issue with Flask itself. Rather than anything database related, as my database runs perfectly (mysql) and inserts everything as expected. I'm assuming Flask can only handle a certain amount of concurrent connections at one time. I may be exceeding this significantly.

**Comment by marumari** [comment]
@SimonTellsAll: You should look into these for your purposes then:

http://flask.pocoo.org/docs/0.11/deploying/#deployment

uWSGI should be able to handle significantly higher loads than running Flask directly.

**Comment by MJ869** [comment]
Is this related to the same issue I'm having with ngrok and local tunnel trying to create a URL to my localhost map? Want to make sure I'm not duplicating issues.

Getting this error from ngrok a couple minutes after generating a new URL: "Too many connections! The tunnel session '###' has violated the rate-limit policy of 20 connections per minute. Please decrease your inbound connection volume or upgrade to a paid plan for additional capacity. ERR_NGROK_702"

Amd getting this error from local tunnel a couple minutes after generating a new URL: "no active client for ###"

**Comment by razorasadsid** [comment]
got this error twwwo i['m baaaaad

**Comment by vrgomes** [comment]
This error is related to Flask when there are many connections and has nothing to do with database.
Still happening is the latest builds.
Anyone has a fix for this?

**Comment by Slivo-fr** [comment]
Same error happened today, after updating. I'm using mysql, no worker running, only webserver displaying gyms.
```shell
2016-09-29 11:33:42,852 [     Thread-7235][           app][   ERROR] Exception on /static/016db14/dist/js/map.min.js [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1637, in full_dispatch_request
    rv = self.preprocess_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1837, in preprocess_request
    rv = func()
  File "/usr/local/lib/python2.7/dist-packages/playhouse/flask_utils.py", line 165, in connect_db
    self.database.connect()
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 3402, in connect
    **self.connect_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/playhouse/pool.py", line 127, in _connect
    raise ValueError('Exceeded maximum connections.')
ValueError: Exceeded maximum connections.
```
