### ISSUE TITLE
More testing

### ISSUE THREAD

**Issue by medghaim** [PokemonGoMap/PokemonGo-Map#714]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Python 2.7):
* Operating System and version (desktop or mobile):

**Comment by FrostTheFox** [comment]
10/10

**Comment by medghaim** [comment]
RUBOT PLS

**Comment by medghaim** [comment]
![image](https://cloud.githubusercontent.com/assets/7801031/17677419/add3e8cc-6300-11e6-8e12-90b68a7d7dc9.png)
