### ISSUE TITLE
Showing very few Pokemons

### ISSUE THREAD

**Issue by tolinwei** [PokemonGoMap/PokemonGo-Map#716]
After staring up this web service, the browser only shows very few Pokemons. I used [original project](https://github.com/AHAAAAAAA/PokemonGo-Map/) half month ago, it should show far more than these:

**location**: south of Golden Gate Bridge

<img width="881" alt="screen shot 2016-08-15 at 1 47 03 pm" src="https://cloud.githubusercontent.com/assets/2353407/17679130/f5d45f7e-62ee-11e6-96a2-c6b222c53e75.png">

I'm guessing if this map scanner is causing some soft ban to prevent it from scanning further Pokemons. Can someone please give me some idea? Thanks!

## Your Environment

* Version used: macOS 10.11.6
* Environment name and version (e.g. Python 2.7):
* Operating System and version (desktop or mobile):

**Comment by lighter857** [comment]
yeah you most likely have some accounts that have been banned.
I just lost 2 and it causes the scanner to appear broken

**Comment by tolinwei** [comment]
@lighter857 thanks!
