### ISSUE TITLE
Cannot push app to Bluemix

### ISSUE THREAD

**Issue by MrFlumk** [PokemonGoMap/PokemonGo-Map#720]
The steps I've taken so far are:
1. git clone dev-branch
2. create Bluemix account and download CF CLI
Now I'm stuck. The next step is to push the app, but I'm not sure what exactly I'm pushing. Should I push the PokemonGo-Map directory? 
After successfully logging in using cf login, I tried:
$ cf push PokemonGo-Map
FAILED
auth request failed: Error performing request: Post https://login.ng.bluemix.net/UAALoginServerWAR/oauth/token: dial tcp: i/o timeout
TIP: If you are behind a firewall and require an HTTP proxy, verify the https_proxy environment variable is correctly set. Else, check your network connection.

Has anyone successfully uploaded to Bluemix? I'm on Linux with Python 2.7, if that matters here.

**Comment by diegobrandao** [comment]
I'm also having issues with Bluemix, but in my case it's "Disk quota exceeded". Even after setting the quota to 2GB.

**Comment by rrbailey89** [comment]
Y'all have both made it farther than me. I couldn't even figure out how to login... Cf login kept resulting in it asking me for an api.

**Comment by diegobrandao** [comment]
Try this tutorial:
https://console.ng.bluemix.net/docs/starters/install_cli.html

The push works for me, but I get "disk quota exceeded" during the staging...

**Comment by x3rx** [comment]
Bluemix IPs are blocked, I get this Error:
`2016-08-17 10:02:46,782 [ search_worker_0][ search][ WARNING] Exception while downloading map: Seems your IP Address is banned or something else went badly wrong...`
see also [reddit](https://www.reddit.com/r/pokemongodev/comments/4vhygk/vps_providers_banned_from_accessing_apis/)
