### ISSUE TITLE
example.py not reading user input

### ISSUE THREAD

**Issue by FrostTheFox** [PokemonGoMap/PokemonGo-Map#726]
It doesn't read responses properly.
## Expected Behavior

It should respond based on user input

## Current Behavior

Just spits "you have been banned lol" every time

## Steps to Reproduce (for bugs)

1. python example.py
2. you have been banned lol

## Your Environment

* Version used: latest
* Environment name and version (e.g. Python 2.7): Python 2.7.12
* Operating System and version (desktop or mobile): Windows 10

**Comment by Becold** [comment]
Blame commit 72a4577f09b7c90d4f03d1986e05146509e18e35

**Comment by FrostTheFox** [comment]
stupid shit, doesn't work.

**Comment by Becold** [comment]
Did you RTFM ?

**Comment by FrostTheFox** [comment]
100%. doesn't work

**Comment by Becold** [comment]
you have been banned lol

**Comment by slideup-benni** [comment]
This is not a support forum; please see the discord #help channel for assistance.

**Comment by FeikoWielsma** [comment]
It appeared it got broken here: https://github.com/PokemonGoMap/PokemonGo-Map/commit/72a4577f09b7c90d4f03d1986e05146509e18e35 Please do the needful and change it back

**Comment by FrostTheFox** [comment]
'poon bang lure pls'

**Comment by FrostTheFox** [comment]
is fixed
