### ISSUE TITLE
Scan not picking anything. 0 pokemon, 0 pokestops, 0 Gyms.

### ISSUE THREAD

**Issue by Freeque** [PokemonGoMap/PokemonGo-Map#727]
Expected Behavior:
There should be pokemon showing up on the map.

 Current Behavior:
0 pokemon, 0 pokestops, 0 Gyms is showing while scanner is running, few hours ago everything was fine

Possible Solution
No idea.

 Version used: Yesterday develop branch
Environment: Python 2.7:
Operating System and version Windows 7:

**Comment by Freeque** [comment]
![bug](https://cloud.githubusercontent.com/assets/21049217/17685704/d5f8282a-6366-11e6-8768-c26f5888ccb5.PNG)

**Comment by slideup-benni** [comment]
what are the arguments?

**Comment by slideup-benni** [comment]
look at https://github.com/PokemonGoMap/PokemonGo-Map/issues/554

**Comment by Freeque** [comment]
-st 12 -sd 10

**Comment by Freeque** [comment]
ok it is workong now, seems like a throttling issue. i lowered down sd to 12 and waited few hours and now it is working again.
