### ISSUE TITLE
Multi user front end

### ISSUE THREAD

**Issue by Infernoman** [PokemonGoMap/PokemonGo-Map#73]
## Expected Behavior
Possibility to run a mock server that stores multiple user locations 

## Current Behavior
Would like for the ability for each user visiting the website to be able to use the "Start at user's location", "Scan follows location", and "Search" functions on the website. WITHOUT affecting one another. 

## Possible Solution
This server wouldn't control the background scanning but rather act similar to pokevision with a wider area of use. And allow for users to open their mobile device without scrolling to their location. This shouldn't affect scanning therefore it may need an extra argument to have it enabled. Or only enable it when running with "-ns".

## Context
Trying to create a multi user system that allows for more than one user to add to a database. And tracks the individual users without affecting one another.

**Comment by JZ6** [comment]
We do not recommend people host servers for multiple people, as it is much safer to run local copies, as such we can not condone this.

**Comment by Infernoman** [comment]
Completely understandable. Would it be possible to put a bounty on this subject? I can explain a bit more. As I think this could also help reduce load on the front end and database. While keeping the complete database, it would allow you to only show the Pokemon within a defined or user defined radius of the user. Which could also decrease load times on the frontend, data usage for mobile carriers, and queries on the database if I'm not mistaken.

**Comment by Infernoman** [comment]
Something similar is already implemented into the notify/hide feature. When one user wants to hide or notify different Pokemon it's saved to the local cache from what I can tell. And it allows each individual user to select different Pokemon to hide, or notify without affecting any of the other users on the server.

**Comment by Infernoman** [comment]
https://github.com/PokemonGoMap/PokemonGo-Map/pull/36
going to need to be implemented if we want this to work for multiple users.
