### ISSUE TITLE
No Scanned Locations being shown/logged after updating

### ISSUE THREAD

**Issue by schwtyl** [PokemonGoMap/PokemonGo-Map#731]
## Expected Behavior
Each time a 70m radius is scanned, a scannedlocation entry is logged, and it appears on the map.

## Current Behavior
The scannedlocation table is untouched, and Scanned Locations do not appear on the map. To clarify: this issue is specifically related to working scanners, that are populating pokemon/pokestops/gyms, but not scanned locations (so I can't see where it's scanned, other than seeing Pokemon there)

## Context
It's helpful to see where the scanners are at, and to quickly diagnose issues (i.e. scanners running slow, stopped, skipping/holes, etc).  I'd also be curious to see which areas are being skipped with the spawn-location-only setting.

## Your Environment

Raspberry Pi 3

**Comment by tolvaly** [comment]
Same here!

This error is shown:
![2016-08-16 09_47_16-root radxa_ _home_pokemon_repo_pokemongo-map2](https://cloud.githubusercontent.com/assets/20593548/17690341/8cdb5bb4-6396-11e6-9245-b2de52566315.png)

**Comment by lnguyen7git** [comment]
Getting the same error. It appears that the accounts with the errors are banned. Is Niantic getting detecting scans and banning the accounts or is there something else going on here?

**Comment by cont1nuity** [comment]
My old scan account was blocked and I could not login to the game.
Seems like they are blocking scans with new accounts which have not completed the tutorial (got their starter) as well.
To bypass this, I created a new account, verified the email, logged into the game, got a starter and restarted the server using this account.

**Comment by tolvaly** [comment]
I have done that Friday, my scanner wasn't running until this morning. I have updated the source code, and it started with the error. So my scanner user is over the tutorial and the starter pokemon also. I tried to log in with that user, and it says the servers are overloaded.

**Comment by cont1nuity** [comment]
With my old account (which was verified but did not complete the tutorial) I get some server error when logging in.
Have you verified the email address? The account usage is down to two days without the mail verification.

**Comment by tolvaly** [comment]
Yes i do! I will make a new account, and will try with that one!

**Comment by McMoert** [comment]
Had the same error. I've created a new account, completed the tutorial and now it's working again

**Comment by tolvaly** [comment]
Yes, it's ok with a new account, so it means, they are blocking old accounts.

**Comment by victoryotje** [comment]
Does this mean that new scripts to generate random accounts are pointless?
Because I know of one which works with the new Captcha. But as long as you have to login
the account and choose begin pokemon and verify email it is pointless?

I am now running my server with accounts I randomly created but loged in with to choose starter pokemon. The emails I used were not existing so can't verify them. Will this also mean that the accounts will stop working in 2 days?

**Comment by schwtyl** [comment]
To clarify: this issue is specifically related to working scanners, that are populating pokemon/pokestops/gyms, but not scanned locations (so I can't see where it's scanned, other than seeing Pokemon there)

**Comment by rstankey** [comment]
Not sure if this is a new change, but also on iOS "Paste" is disabled so one has to manually type usernames and passwords, making the process even more tedious.

**Comment by charroc1** [comment]
I am having the same issue on a raspberry pi 2. No errors are seen in my nohup.out file (just warnings about sqlite being locked). I have read another thread that claimed that running 'npm i & npm run build' would fix the issue, but it has not helped the least bit for me. There are no errors in Chrome console, so it doesn't appear to be a JavaScript error. Was this feature removed?

**Comment by schwtyl** [comment]
It seems to be working for me with spawnpoints-only disabled, though I don't dare test with spawnpoints-only again, because it was generating WAY too many connections, already lost a handful of accounts due to bans since I updated the code :-/

Also, be sure to update your date/time on the raspberry pi - that's caused issued related to Scanned Locations in the past.

**Comment by charroc1** [comment]
Ahhh, updating the time worked. Strange that the time gets unsynced over time on a rpi. Thanks.
