### ISSUE TITLE
Map stays blank, have to refresh (F5) multiple times

### ISSUE THREAD

**Issue by victoryotje** [PokemonGoMap/PokemonGo-Map#733]
When I go to my server to check out the map I should expect to see the map with pokemon and stops etc.

Current behavior is that sometimes the map part stays grey or the google map shows up but I dont see any stops and pokemon.
To fix this I have to refresh (F5) the page multiple times.

## Your Environment

* Version used: Latest DEV branch
* Environment name and version: Python 2.7:
* Operating System and version: Desktop Windows 10

**Comment by Studio-XP** [comment]
You don't happen to have an ad blocker installed do you? If you do, try temporarily disabling it and see if the issue persists. Also if you're using chrome, check the console (ctrl + shift + I) to see if there's any messages
