### ISSUE TITLE
Errors during scanning

### ISSUE THREAD

**Issue by itztq** [PokemonGoMap/PokemonGo-Map#734]
getting errors during scanning why?
------------------------------------------

2016-08-16 11:52:08,159 [ search_worker_4][        search][   ERROR] Search step 5 map parsing failed, retrying request in 5 seconds. Username: xx@gmail.com
Traceback (most recent call last):
  File "/home/usr/Desktop/PokemonGo-Map/pogom/search.py", line 281, in search_worker_thread
    parse_map(response_dict, step_location)
  File "/home/usr/Desktop/PokemonGo-Map/pogom/models.py", line 330, in parse_map
    cells = map_dict['responses']['GET_MAP_OBJECTS']['map_cells']
KeyError: 'map_cells'
2016-08-16 11:52:08,692 [ search_worker_0][        search][   ERROR] Search step 30 map parsing failed, retrying request in 1 seconds. Username: xx1@gmail.com
Traceback (most recent call last):
  File "/home/usr/Desktop/PokemonGo-Map/pogom/search.py", line 281, in search_worker_thread
    parse_map(response_dict, step_location)
  File "/home/usr/Desktop/PokemonGo-Map/pogom/models.py", line 330, in parse_map
    cells = map_dict['responses']['GET_MAP_OBJECTS']['map_cells']
KeyError: 'map_cells'
2016-08-16 11:52:08,866 [ search_worker_6][        search][   ERROR] Search step 7 map parsing failed, retrying request in 5 seconds. Username: xx3@gmail.com
Traceback (most recent call last):
  File "/home/usr/Desktop/PokemonGo-Map/pogom/search.py", line 281, in search_worker_thread
    parse_map(response_dict, step_location)
  File "/home/usr/Desktop/PokemonGo-Map/pogom/models.py", line 330, in parse_map
    cells = map_dict['responses']['GET_MAP_OBJECTS']['map_cells']
KeyError: 'map_cells'

**Comment by ghvanderweg** [comment]
Most likely cause is that the those accounts have been banned by Niantic.

**Comment by itztq** [comment]
@ghvanderweg temp ban or 30 min ban?

**Comment by ghvanderweg** [comment]
Mine are still banned, so my money's on a permanent ban for these accounts.

**Comment by majuss** [comment]
Yep seems to be a perma ban. If you create knew ones I would suggest to go through the tutorial and catch a starter. This COULD decrease the chance of banning.

**Comment by ghvanderweg** [comment]
@majuss What's a safe way of doing that? I don't want to log in to any throwaway accounts from my phone, or my home IP.

**Comment by majuss** [comment]
Use the the phone from a friend/family member whos not playing pongo seems to be the best option ;)

**Comment by simple-lad** [comment]
I have the same. every day more accounts are banned. how to avoid it?

**Comment by ghvanderweg** [comment]
Stop scanning ;)

But seriously, accounts bans are something we can only expect to increase over time. I guess pressure is on the devs to try to mimic real player behaviour with scanners.

**Comment by ultrafunkamsterdam** [comment]
I created 7 accounts yesterday to create a new hive. They were all getting this message. You first have to logon to your phone with the accounts, choose outfit, nick, and catch a starter pokemon. Best is to walk around a little to get a pidgey, so  become level 2. 
After i did this everything worked flawless.

**Comment by SethG911** [comment]
Even then my accounts I've done the tutorial with are getting banned. I think part of it might be when an account moves from the edge of a scan area back to the center. If your scan area is too wide, it might be being flagged as moving too far too fast. Try making your scan radius smaller. I didn't notice this happening until after I moved my scan radius from 10 to 13, even though my delay was 10.5.

**Comment by ghvanderweg** [comment]
That's the reason why I am hesitant to implement TBTerra's spawnTracker in my scanner. Won't it make accounts jump all over the place, resulting in faster bans?

**Comment by SethG911** [comment]
Yes! Yes! Yes! Even using the spawnpoints-only option built into this projects dev branch will cause bans to go up. That is actually when I first started having it happen.

**Comment by crckdns** [comment]
Can't be the Spawnpoint scan..not only.
Got 10 accounts banned in past 4 days. Few of them were pre-ToS, others after ToS system. All are scanning with -st 5 -sd 8 .. all are same ip, running about 20 scanner instances.

**Comment by Bulgran** [comment]
I had 12 accounts with -st 8 and -sd 13 yesterday, when I woke up today I got 3 of those accounts banned (this error). Haven't used spawnpointscan at all.
All my accounts went through the tutorial and catched the starter.

**Comment by clifford2006** [comment]
Anyone got any ideas on how they detect those? because they seems to be unable to track and ban all at once. Something must have hit their system autoban.

**Comment by SethG911** [comment]
Perhaps it has something to do with too many requests coming from a single IP? I am going to try moving my scan down to -st 6 -sd 12. We'll see how that fairs.

**Comment by Superdrac** [comment]
I got the same problems.. But only with the bot, i can play with fresh account on bluestacks but it don't work on the bot. (ptc & google) 

It seems that it's only an ip ban..  (the python server is on another ip) I must try this on my raspberry just to see.
