### ISSUE TITLE
Not the right place for this but not sure where :/

### ISSUE THREAD

**Issue by irus99** [PokemonGoMap/PokemonGo-Map#738]
Sorry I do realize this is not really the right place for this but I have googled and was not able to find anything and it seems that niantic is really cracking down on creating new accounts even manually. I was wondering if anyone knew of a reliable way to auto create accounts. For me it seems that after 5 accounts it will stop sending me email verifications. Any advice would be greatly appreciated. TIA

**Comment by clifford2006** [comment]
ptc or google? I think google accounts is not having this problem. Need clarification thou.

**Comment by irus99** [comment]
sorry ptc accounts

**Comment by BaIthamel** [comment]
Discord is where

**Comment by irus99** [comment]
if anyone else is wondering where Discord is its here ( https://discord.gg/PWp2bAm )
