### ISSUE TITLE
xxhash Installation Error

### ISSUE THREAD

**Issue by cmachikas** [PokemonGoMap/PokemonGo-Map#74]
When installing on a fresh Linux environment, xxhash installation errors will cause `pip install -r requirements.txt` to crash. This may result in errors such as (excuse the paraphrasing) "pgoapi is not installed", "please update to protobuf3" or similar. 

Installing python-dev packages with `apt-get install python-dev` prior to installing requirements.txt allows xxhash to compile correctly, allowing the dependencies to install normally. 

In the Discord, about a dozen people were stuck on this single error tonight, and a simple documentation acknowledgement could alleviate a lot of requests on this matter. 

Python2.7 on Ubuntu 14.04 VPS, fresh install.

**Comment by EdenGottlieb** [comment]
I also managed to solve a xxhash installation error (not being able to include python.h) by installing Python-dev.

**Comment by cmachikas** [comment]
@EdenGottlieb the errors are one in the same.

**Comment by chuyskywalker** [comment]
Thanks, will have linux docs updated accordingly.

**Comment by nicktan147** [comment]
Apparently windows are also facing the same issue. Anyone have any idea how to solve it?

**Comment by invisiblek** [comment]
@nicktan147 try installing this: https://www.microsoft.com/en-us/download/details.aspx?id=44266
