### ISSUE TITLE
Weird -ss behavior with low steps/spawn points

### ISSUE THREAD

**Issue by xPersei** [PokemonGoMap/PokemonGo-Map#744]
## Expected Behavior
The scan should take into consideration the spawn points collected from its corresponding area and loop through them based on the predefined steps/spawn time.

## Current Behavior
For some reason, in areas with very low spawn points count, the scan just derps adding an enormous amount of steps.

## Steps to Reproduce (for bugs)
1. Start "Movable19" /d C:\PokemonGo-Map /MIN C:\Python27\Python.exe C:\PokemonGo-Map\runserver.py -a ptc -u x -p y -ns -l "z" -st 6 -ng -nk -ss
2. http://i.imgur.com/j1Ff6jA.png

## Context
CPU and RAM usage go through the roof, having to kill the worker/workers to fix it.

## Your Environment
* Version used: latest as of e94acb6
* Environment name and version: Python 2.7.12
* Operating System and version: Microsoft Windows [Version 10.0.10586]

**Comment by TBTerra** [comment]
best geuss, is that its got somthing to do with it trying to frind the next point, but its so far in the future (1800 secs) that it thinks its in the past and so it adds it again and again, and so on

**Comment by xPersei** [comment]
> best geuss, is that its got somthing to do with it trying to frind the next point, but its so far in the future (1800 secs) that it thinks its in the past and so it adds it again and again, and so on

This is the generated JSON corresponding that worker:

`[{"lat":` 10.498869077719206, "lng": -73.2629446862829, "spawnpoint_id": "8e8ab83b619", "time": 3480}, {"lat": 10.498524909165129, "lng": -73.26285253821814, "spawnpoint_id": "8e8ab83b643", "time": 720}, {"lat": 10.498614674679873, "lng": -73.2629446862829, "spawnpoint_id": "8e8ab83b66b", "time": 600}, {"lat": 10.49797142480648, "lng": -73.26202320391182, "spawnpoint_id": "8e8ab83b769", "time": 240}, {"lat": 10.498061189512983, "lng": -73.26211535232127, "spawnpoint_id": "8e8ab83b76d", "time": 1260}, {"lat": 10.497263241042022, "lng": -73.26147031265096, "spawnpoint_id": "8e8ab83ba15", "time": 60}]
