### ISSUE TITLE
cannot reach map on cloud VPS

### ISSUE THREAD

**Issue by Sornoril** [PokemonGoMap/PokemonGo-Map#746]
After walk trough the installation everything works fine on my server, python is running, data is coming flawlessly. The one problem is that I cannot see the map in my far (not on running server) browser on the specified port. What did I made wrong?

Thanks

**Comment by totoberg123** [comment]
Portforward?

**Comment by FeikoWielsma** [comment]
Use -H 0.0.0.0 probably. Otherwise it doesn't bind on external IP.

**Comment by Sornoril** [comment]
@FeikoWielsma good point ... that was what I forgot. Many thanks!
