### ISSUE TITLE
No pokemon

### ISSUE THREAD

**Issue by busyface21** [PokemonGoMap/PokemonGo-Map#759]
My script seems to be working fine, 

![image](https://cloud.githubusercontent.com/assets/21071003/17721386/a414f63a-63de-11e6-87d0-7521cfea6d0c.png)

As in , it will upsert pokemon.

at the moment i have been using PTC but i have the same response from a google account.

However when accessing the map, this is what i see:

![image](https://cloud.githubusercontent.com/assets/21071003/17721416/dd53fdec-63de-11e6-9133-ec76a3bb22f7.png)

not a single pokemon on the map.

I am using a brandnew downloaded installation, but i ran the update and the npm installation and built again.

Forgot to say that i am able to see the rest in real time.

![image](https://cloud.githubusercontent.com/assets/21071003/17721474/4541e28e-63df-11e6-85bc-6d1fae75b22e.png)

just no pokemon

**Comment by justsomedudeonthenet** [comment]
Just to be sure...you haven't turned off Pokemon under Options -> Markers, have you?

**Comment by busyface21** [comment]
![image](https://cloud.githubusercontent.com/assets/21071003/17721552/df6ff878-63df-11e6-9a3e-df164d1a829f.png)
 

no, this is the default set up i have

**Comment by justsomedudeonthenet** [comment]
Try running npm install again to recreate all the javascript files.

**Comment by busyface21** [comment]
just did again, same issue

**Comment by jccwright** [comment]
Are you accessing from server or client?

**Comment by skos91** [comment]
Having the same issue, my setup is a VPS running the server and also a small movable spiral scan, with an RPI feeding into a mysql database running on the VPS. Just ran git pulls on them so I could stop using the hacked together spawnpointscanner I was using, and now only pokemon from the spiral scanner are showing up

**Comment by busyface21** [comment]
I have it on a VPS.  I havent configured any DB Settings im just using the basic installation guide provided

**Comment by busyface21** [comment]
Skos could you potentially give an idea of what was affecting your script?

**Comment by Albert62** [comment]
Your IP could be banned from Niantic's server temporarily.
I have a server running at home, I've had to lower down the **Scan Delay** to default again because I've got 3 IPs banned already.
As soon as I release the IP and get a new one everything works again flawlessly.

**Comment by billymwlei** [comment]
You need to be specific , how many account you are using and what is the step and speed you scan?

**Comment by skos91** [comment]
@busyface21 Yeah mine was actually just straight up failure on my part, I have a startup script called start_worker.sh and I parse out my command arguments for the runserver command by line. I forgot to include the " \" at the end of the line with the --spawnpoint-scan option and it just didn't register any arguments after that so it was logging to a local SQLite DB rather than my remote mySQL server

**Comment by Made123** [comment]
Before my code was turned with SD=0.5, since the last night i can see in the terminal:
login succesfull
0 pokemon, 0 pokestop, 0 gym -> and just 1 line per 50 have a result. So you can imagine the large scan with green circle but totally empty...


I was played with the scan and up it to 5 seconds, and seems to work better. I suspect a NIA update about to much request from the same IP.

**Comment by slideup-benni** [comment]
@Made123 5 is too fast. you should use 8+, recommend (and default) is 10.

**Comment by albjon10** [comment]
I have the same issue on my vps. it was working fine and then it just didnt show any, then for some minutes it showed all then down again. 

python runserver.py -a ptc -u *** -p ***  -l "***" -st 15 -k *** -H *** -P *** -sd 10 -fl

**Comment by BaIthamel** [comment]
This is not a support forum; please see [the discord #help channel](https://discord.gg/npVqkUn) for assistance.

**Comment by busyface21** [comment]
C:\Python27\python.exe runserver.py -a google -u "account@gmail.com" -p "pass" -l "xxxx, xxx" -st 7 -k "xxx" -sd 8
