### ISSUE TITLE
cannot update

### ISSUE THREAD

**Issue by puredota** [PokemonGoMap/PokemonGo-Map#76]
$ git pull origin master
error: Pull is not possible because you have unmerged files.
hint: Fix them up in the work tree, and then use 'git add/rm <file>'
hint: as appropriate to mark resolution and make a commit.
fatal: Exiting because of an unresolved conflict.

**Comment by Nicknack1234** [comment]
You modified the files, Now those files are updated, GIT is trying to stop you from losing your changes.

**Comment by chuyskywalker** [comment]
Also, `master` doesn't exist anymore. That withstanding...

This is not a support forum; please see [the discord #help channel](https://discord.gg/npVqkUn) for assistance.
