### ISSUE TITLE
Scanning is slow when a webhook is defined, but doesn't exist

### ISSUE THREAD

**Issue by brandonshults** [PokemonGoMap/PokemonGo-Map#762]
## Expected Behavior
Workers continue scanning at the specified scan delay regardless of the presence or absence of a webhook server.

## Current Behavior
If a webhook is defined but not reachable, workers will take ~1 minute between "search" and "upsert," even if the scan delay is set to 10.  Even though certain exceptions are handled in the code, they either aren't the right exceptions or aren't being thrown in this case so the user gets no indication that this is the problem.

## Possible Solution
I can think of three possible solutions all revolving around this line: https://github.com/PokemonGoMap/PokemonGo-Map/blob/c36d1acb144e96f81c70fecc41ff89ba4ff317cd/pogom/utils.py#L317

1.  Change the tuple to include a timeout for the connection instead of "None."  Would a potential good value be args.scan_delay - 1.5?
2.  Make the post request asynchronously so that it doesn't block the worker.  This would probably require another dependency, and potentially hurt overall performance by spawning twice as many threads?  From the requests documentation: "If you are concerned about the use of blocking IO, there are lots of projects out there that combine Requests with one of Python's asynchronicity frameworks. Two excellent examples are [grequests](https://github.com/kennethreitz/grequests) and [requests-futures](https://github.com/ross/requests-futures)."
3.  Actually display an error when the webhook is unavailable so that the user knows why their workers are slow.

## Steps to Reproduce (for bugs)
1.  Define a webhook server, I used my local IP address with a port that wasn't being listened on and did it through config.ini
2.  Start runserver.py
3.  Observe the time in between a worker's request and upsert.
4.

## Context
I was affected by this issue and had no idea what was happening.  It was kind of hard to track down and I believe that many others are experiencing slow scans and have no idea why.

## Your Environment

* Version used: The latest develop branchhttps://github.com/PokemonGoMap/PokemonGo-Map/commit/7cdb8c1ec3af5eda258dadc9f8c6f2095988f202
* Environment name and version (e.g. Python 2.7): Python 2.7
* Operating System and version (desktop or mobile): Windows 10

**Comment by Toetje585** [comment]
Same here, just to confirm.

**Comment by TheQL** [comment]
Can't reproduce, but probably because my hooks never get delivered. Wrong place to ask, but if you can pinpoint me to a solution I would be happy. Hookserver is running in debug mode, never logs any connection attempt from PokemonGo Maps. Configured via config.ini and via commandline, same behaviour, dev-branch from git oder release 3.1.0 behave the same.

**Comment by justinkwaugh** [comment]
The webhook call is inside parse_lock, unnecessarily I believe.  Passing the lock into parse map instead and using it just around the db calls would remove the webhook from the lock.

**Comment by justsomedudeonthenet** [comment]
I don't believe this is an issue anymore, after the rewrites that have been done to this section of the code.  If it is, please reopen.
