### ISSUE TITLE
Create_Tables Error

### ISSUE THREAD

**Issue by jasonfoy21** [PokemonGoMap/PokemonGo-Map#77]
Installs but unable to start instance

![image](https://cloud.githubusercontent.com/assets/6747534/17470269/2f7e953e-5cf8-11e6-8030-060300629998.png)

**Comment by chuyskywalker** [comment]
`disk I/O error` doesn't look like a problem with PokemonGo-Map itself but more likely a problem in your environment or setup.

Please reopen if you find it to be a problem in this codebase, though.

**Comment by jasonfoy21** [comment]
You're right, it was an issue with vagrant and access issues, Once i moved the files from /vagrant/app to ~/app, it worked perfectly.

Thanks @chuyskywalker
