### ISSUE TITLE
Server Memory Issue

### ISSUE THREAD

**Issue by blackhattristar** [PokemonGoMap/PokemonGo-Map#773]
My server decided to stop running the task due to memory issues. 
## Expected Behavior

No memory issues
## Current Behavior

Memory issues
## Possible Solution

Clustering the PokéStops and Gyms.
## Steps to Reproduce (for bugs)

1. Run scans all over the globe.

The PokéStops and Gyms do not have an expiration time such as the Pokémon do

## Context

My server can't handle remembering the PokéStops and Gyms from where you have scanned all over the globe.
## Your Environment

* Version used:
* Environment name and version (e.g. Python 2.7):
* Operating System and version (desktop or mobile):

**Comment by chuyskywalker** [comment]
But more ram.
