### ISSUE TITLE
SQL column optimization

### ISSUE THREAD

**Issue by Zerotask** [PokemonGoMap/PokemonGo-Map#778]
Table: gym
gym_id -> VARCHAR(35)
team_id -> TINYINT(1) UNSIGNED
guard_pokemon_id -> SMALLINT(3) UNSIGNED
gym_points -> SMALLINT(5) UNSIGNED

Table: pokemon
encounter_id -> VARCHAR(28)
spawnpoint_id -> VARCHAR(11)
pokemon_id -> SMALLINT(3) UNSIGNED

Table: pokestop
pokestop_id -> VARCHAR(35)

I'm not sure if 35 is the max length for the IDs. Maybe a dev can prove that.

More info here: http://dev.mysql.com/doc/refman/5.7/en/integer-types.html

**Comment by Xcelled** [comment]
Also some indexes could be dropped as they're not used.

**Comment by justsomedudeonthenet** [comment]
I would really recommend against changing the existing schema unless there is a big performance increase.  A lot of people have are using their own various tools to import and export data, and do analytics on it.  Changing the existing fields may break them.  

If there is a noticeable performance increase however, by all means break people's tools, we'll adapt.

**Comment by Zerotask** [comment]
I changed it without noticing any problems.

**Comment by Xcelled** [comment]
A larger issue is that this needs peewee support. This means finding or making the right model field classes.

**Comment by Zerotask** [comment]
Sure, but this shouldn't be a problem.

**Comment by BaIthamel** [comment]
also this is not really an *issue* either make a PR with the tweak or make a feathub request.

**Comment by Xcelled** [comment]
Tinyint isn't supported by peewee. Best we could do is smallint: http://docs.peewee-orm.com/en/latest/peewee/models.html#field-types-table

Unsigned is likewise unsupported: https://github.com/coleifer/peewee/issues/542

For both of these, we'd have to implement a custom field. Do some tests first to measure the performance.
