### ISSUE TITLE
[Feature Request] Hide/notify list of pokèmon at the same time

### ISSUE THREAD

**Issue by Romfrosk** [PokemonGoMap/PokemonGo-Map#78]
Would love to be able to hide lists of Pokèmon based on their "spawnrate" (uncommon, common, rare ++)

Also have the same possibility with Notify.

**Comment by tegob** [comment]
How could that even work? Spawn rate heavily depends on your location.

**Comment by Romfrosk** [comment]
I meant that we can use the same classification as used in the "tooltip" when you hover or click on a pokèmon

**Comment by Faskill** [comment]
The devs could probably create a file in the pokegomap folder in which the user would input (either manually or through the api) the names of pokemon he defines as common and rare (like in the poke radar app ) and then they would be shown or not accordingly

**Comment by JZ6** [comment]
noted
