### ISSUE TITLE
Location passline

### ISSUE THREAD

**Issue by yermandu** [PokemonGoMap/PokemonGo-Map#788]
> python runserver.py --help

```
File "/opt/pokemon-go-map/pogom/utils.py", line 129
    print sys.argv[0] + ': error: arguments -l/--location is required'
```

Please how we can pass the location paramether? like eg

runserver.py -l "-16.533,-68.093"

? 

Regards

**Comment by xtop** [comment]
Did you try "lat: -16.533, lon: -68.093"?

**Comment by BaIthamel** [comment]
This is not a support forum; please see [the discord #help channel](https://discord.gg/npVqkUn) for assistance.
