### ISSUE TITLE
New PTC accounts doesn't work without activate them..

### ISSUE THREAD

**Issue by gateseee** [PokemonGoMap/PokemonGo-Map#790]
Hy. 

I found out, that new PTC accounts won't work without "activate" them on the mobile phone or bluestacks etc. 

There will be a "map parsing error" until you login, accept the terms, catch the first pokemon and give your player a name. 

Is there a way to integrate this procedure for new accounts, a workaround, or a script on github which does this for new accounts?

Br

**Comment by BaIthamel** [comment]
NOT AN ISSUE FOR US!

**Comment by slideup-benni** [comment]
@gateseee you could ask 
https://github.com/Kitryn/PTCAccount2 or
https://github.com/TachyonRSA/PoGoTos or
https://github.com/jepayne1138/PTCAccount
