### ISSUE TITLE
Expired lured pokestops are shown forever

### ISSUE THREAD

**Issue by Moussa** [PokemonGoMap/PokemonGo-Map#793]
Expired lured stops are shown as lured forever on the map

## Expected Behavior

Lured stops should show as normal stops after expiring

## Current Behavior

Stops show as lured forever instead, with an `(expired)` after the expiry time

## Steps to Reproduce (for bugs)

1. Scan area with lured stop
2. Observe stop never goes back to being normal stop

## Context

Don't want all stops to show up as lured eventually.

## Your Environment

* Version used: 7729aab526913db84b6e967c47e8c1c13828e125
* Environment name and version (e.g. Python 2.7): Docker image
* Operating System and version (desktop or mobile): Ubuntu server

**Comment by clifford2006** [comment]
If a pokestop does not disappear after "expired" is shown, try refreshing your browser and see if the pokestop have timer again. If it does, it means its a known bug since last pokestop update. You can refer and do a temporary fix as suggested in PR #555 which works up until now.

**Comment by Moussa** [comment]
@clifford2006 Refreshing the browser doesn't change anything, they're still there and no timer appears. They just have text like `Lure expires at 09:41:29 (expired)` on all of them. I've been manually removing the lure with a sql query but I'm wondering why no one else has reported this bug before.

**Comment by BaIthamel** [comment]
Cos I assumed it was part of the known issue he referenced, which it probably is.

**Comment by Moussa** [comment]
I don't think this is related to that issue at all. It's not that the expiration times on the pokestops are wrong, it's that the expiration time passes and the `lure_expiration` column for that pokestop in the db is not being set back to `NULL` after.

**Comment by clifford2006** [comment]
@moussa probably something wrong with the latest commit since I'm just using the latest stable version v3.1.0
