### ISSUE TITLE
Deploy to Jelastic button links to another repository (sync74)

### ISSUE THREAD

**Issue by Itnain** [PokemonGoMap/PokemonGo-Map#795]
## Expected Behavior
Deploy branches of this repo

## Current Behavior
Deploys develop branch of Sync74 repo

## Possible Solution
Edit/create manifest to deploy to Jelastic

## Steps to Reproduce (for bugs)
Click on Jelasic button at the main page

**Comment by FrostTheFox** [comment]
has been fixed recently
