### ISSUE TITLE
Permaban

### ISSUE THREAD

**Issue by grahovam** [PokemonGoMap/PokemonGo-Map#796]
I just got a Permaban for using this. Careful, guys.

**Comment by roflinger** [comment]
on your main or on the account for the map?

**Comment by grahovam** [comment]
Just the account for the map

**Comment by roflinger** [comment]
ok so no big deal :D

**Comment by Xcelled** [comment]
Time to add the veryserious label to this issue, I think!

**Comment by Dagothur** [comment]
pretty much expected .. the accounts used are teleporting around and the unknown6 implementation is, from what i understand, simply the bare minimum to get responses

it would be surprising if niantic doesn't eventually run a simple ban wave that hits 99% of people's scanning accounts

**Comment by grahovam** [comment]
Here's the mail I got
![bildschirmfoto 2016-08-18 um 10 05 36](https://cloud.githubusercontent.com/assets/10942360/17766431/66044280-652b-11e6-923e-ddea51d65af3.png)

**Comment by roflinger** [comment]
also got this one for my botaccount

**Comment by aldarund** [comment]
Big news here. Bot accounts got banned. Wow. Noone expected this.

**Comment by angrymoose** [comment]
This is not a bug and in the old documents there was a warning not to use your main account. Though  it should probably be stated in the projects readme / repos info page.

**Comment by BaIthamel** [comment]
Well you're hacking an account and spoofing locations, we do say don't use it on your main i mean WHAT why would you do that?

**Comment by grahovam** [comment]
Why are you calling me stupid? Is this really necessary?

**Comment by ChipWolf** [comment]
@grahovam To put this in perspective, we generate 1000 accounts and loose the majority of them to bans, every single day.
