### ISSUE TITLE
Save Spawnpoints independent from Pokemon

### ISSUE THREAD

**Issue by Mumpitz** [PokemonGoMap/PokemonGo-Map#797]
I just setup this Repo on my Server where https://github.com/AHAAAAAAA/PokemonGo-Map was running before.

After looking through the new Features, i found the very nice Full Stats Page. My problem there is now, that my old DB entries show the spawns before they changed the pokemon spawns.

Therefore i would like to erase the old pokemon from the DB, preserving their spawn points.

I would need to do such a cleanup every time they change the pokemon spawns.

Another way to have a clean, reliable heatmap, would be to set a date from wich on the heatmap takes the spawns into account.

**Comment by BaIthamel** [comment]
This is not a support forum; please see [the discord #help channel](https://discord.gg/npVqkUn) for assistance.
