### ISSUE TITLE
Long time to location change

### ISSUE THREAD

**Issue by roflinger** [PokemonGoMap/PokemonGo-Map#799]
when you change the scan location with the icon it takes up to 15 seconds until the location changes. it goes on scanning on the old location
## Expected Behavior
direct change as before
## Current Behavior
see above
## Possible Solution
dunno
## Steps to Reproduce (for bugs)

start map
change location with the icon

## Context
everything double explained?

## Your Environment
pyth 2.7
pokealarm
pokemap current version
win10 64bit

**Comment by jnovack** [comment]
This concept is going away in future versions.

**Comment by roflinger** [comment]
which concept? to be able to change the position marker?

**Comment by jnovack** [comment]
Yes. It is meant to be a multi-user webpage, and thus you can't have multiple people scanning at their leisure.

**Comment by roflinger** [comment]
mh i don´t get it :D i use it alone but on a big range where i change the position always... 

so that won´t be possible anymore? instead it will be for multiple users? but that would inlcude this option too, not?

**Comment by pyr0ball** [comment]
Just curious, but do you happen to have a scan delay set? Perhaps a scan delay of 10-15 seconds?

**Comment by roflinger** [comment]
not a scan delay but a change position delay. for example: i set the marker too location 1, it scans without any problem. while i am walking around the city i need to replace the marker to location 2. on this point it scans 15-20 seconds on location 1 instead of switching directly to location 2.

i have 7 accounts running and they do all go on scanning on the old position for the 15-20 seconds.

i usually use the setting with -sd 10.

on an older version i do not have those problems. it changes the position right after i set the marker and starts to scan from the new position.

**Comment by pyr0ball** [comment]
@roflinger I ask because it takes a few seconds to parse your new location, then there's your scan delay before it will start querying, then maybe another second or two before upserts get shown on the map. In other words, this is expected behavior. Cool your boots and wait for the scan to display
