### ISSUE TITLE
Database gets corrupt on SIGTERM

### ISSUE THREAD

**Issue by EmpowerZ** [PokemonGoMap/PokemonGo-Map#800]
When I gracefully reboot my PC or just kill the runserver.py process gracefully (SIGTERM). Database sometimes get corrupt. Stats, spawnpoints etc. act like if they are empty:

> 2016-08-18 13:46:50,980 [   search_thread][        search][ WARNING] No spawnpoints found in the specified area! (Did you forget to run a normal scan in this area first?)
2016-08-18 13:46:50,981 [   search_thread][        search][ WARNING] Nothing to scan!

Sometimes deleting pogom.db-journal after issue appears helps. And sometimes this helped:
`sqlite3 mydata.db ".dump" | sqlite3 new.db`

However the correct solution seems to close db connection on sigterm

**Comment by jnovack** [comment]
sqlite3 is notoriously simple and inelegant. Not meant for production use.  It is meant for testing and development.

Please consider using mySQL.

**Comment by BaIthamel** [comment]
pretty much the only answer you're going to get to this. Solution is provided in code. Going to close this as a non-issue.
