### ISSUE TITLE
Small Javascript Bug & Stale Content.

### ISSUE THREAD

**Issue by angrymoose** [PokemonGoMap/PokemonGo-Map#802]
Summary:

When running the map via a nginx reverse proxy there are several bugs. I have not tested with other web servers or under its own server.

Bug #1 

When using firefox or intenet explorer 11 go to stats click location and you'll be redirected towards javascript:showOverlay(13);
replace number with the pokemons number. If you click back it takes you to the proper page.

Bug #2  

When using nginx with the default ssl config the page often fails to updated under chrome. But works fine with firefox on any os. This can often be triggered by changing the default options in the web browser. Such as hiding pokemon, pokestops etc. Clearing the cache or opening a new incognito tab will bypass the issue.

## Expected Behavior

Bug #1:

Be taken to the link that was clicked.

Bug #2: 

Refresh page when content updated.

## Possible Solution

Bug#1

Fix the javascript file to click properly.

Bug #2 

Host the javascript files locally rather then pull them from third parties.

## Steps to Reproduce (for bugs)

deploy stable branch.
deploy nginx ssl reverse proxy.
Use firefox & chrome to trigger different bugs.

## Context

Small annoyances caused by small bugs.

## Your Environment

Ubuntu 16.04 LTS
Python 2.7 default
Version 3.1.0 stable
Nginx 1.10

Update:

 Currently trying to debug the chrome bug, will update if I find a solution.

Update 2:

Problem number two is related to a secure nginx policy refusing to load third party content even if its served over ssl. Cloudflare should not be hosting javascript files for internal sites. Its both wasteful and harmful as we are not hosting a public website there is no speed benefit.  While cloudflare can be considered secure and stable there is no need to introduce another point of failure

I'll sort out a pull request later to address the issue.

**Nginx Policy**  That caused issues.

 add_header X-Frame-Options DENY;
 add_header X-Content-Type-Options nosniff;

Update 3:

After testing through the built in web server the error still occurs. It definitely appears to be in the code. It also occurs on Internet Explorer 11, but does not occur on chrome.

**Comment by Christian-X** [comment]
I'm running the map behind a nginx reverse proxy, and didn't notice strange bugs - using chrome on windows, linux and android...

**Comment by angrymoose** [comment]
I am not sure if its to due with ssl, are you by any chance using ssl ?

**Comment by DiscoTim** [comment]
a couple of javascript errors were fixed with the stats page yesterday, is your app current?

**Comment by angrymoose** [comment]
@DiscoTim 

I am using the current stable, I'll check out the dev branch later to see if it's been fixed.

**Comment by pyr0ball** [comment]
@angrymoose checking in, issue resolved?

**Comment by angrymoose** [comment]
@pyr0ball all the bugs past stale content are fixed and that only occurs with nginx so it's an issue on my end.
