### ISSUE TITLE
different accounts per hive

### ISSUE THREAD

**Issue by irus99** [PokemonGoMap/PokemonGo-Map#807]
I have 14 accounts I am currently using I was wondering if there Is a way to assign 7 accounts to 1 hive and 7 to another hive? 

<img width="568" alt="screen shot 2016-08-18 at 11 05 47 am" src="https://cloud.githubusercontent.com/assets/20796010/17780985/5f2662f8-653b-11e6-87e2-5704181a85d8.png">

**Comment by BaIthamel** [comment]
Yes
This is not a support forum; please see [the discord #help channel](https://discord.gg/npVqkUn) for assistance.

**Comment by irus99** [comment]
I did and no one there knew :/ Please don't close this is the best way for support.
