### ISSUE TITLE
Suggestion: Add Login / Password

### ISSUE THREAD

**Issue by lota7** [PokemonGoMap/PokemonGo-Map#81]
Add a login prompt for accessing the service?

## Expected Behavior

I run a server for a group of friends, mapping our small town.
I therefore try to limit access to just us, but there's always bound to be "leaks" of the adress and now we are suspecting it has been spread to alot of people, resulting in slowdowns on server.
We also see the scan pointer being moved all the time to far away locations, suggseting there's a lot of people using the location search.

## Current Behavior

As of now, everyone can access the site.

## Possible Solution

Add a login/password prompt where I assign these logins for my users to use only.
Would be great if a log would record given users login timestamps and IP.

## Context

Server being slow due to lots of unwanted traffic.

## Your Environment

* Version used: Developer
* Environment name and version: . Python 2.7
* Operating System and version (desktop or mobile): desktop win 10.

**Comment by cmachikas** [comment]
Was thinking of throwing it behind a Gunicorn WSGI auth to do this. Will post more if I decide to sink time into it.

**Comment by Ashex** [comment]
For now throw it behind a web server. Since you're on windows you could just use Apache HTTPD with an auth file that would contain a list of credentials for each person.

**Comment by cmachikas** [comment]
@Ashex I don't believe you can do a httpd auth, as you're not serving it through a HTTP webserver directly, you're serving it through Flask. You have to throw it behind a WSGI auth.

**Comment by Ashex** [comment]
Yes, that is why you put it behind a Web server and do a reverse proxy.


-- 

-
Ahmed

**Comment by lota7** [comment]
@cmachikas , If you do, that would be most appreciated! :+1: 
@Ashex , Thanks for the suggestion. I'm fairly new at this but I'll read up and see what I can accomplish :)

**Comment by JZ6** [comment]
@lota7 we dont recommend hosting public servers, but if you must, follow @Ashex's instructions. No further support will be provided for server side requests.

**Comment by lota7** [comment]
@JZ6 , I dont quite follow you.
I am not trying to host a public server. It's a private one where I wish to keep it private, but since leaks within our group has occured I wish to limit access from outside our group by having a login/password authentication.
This way I can keep track of who is leaking and close it.

**Comment by lota7** [comment]
@Ashex , I tried the reverse proxy. While I did get it to redirect correctly to the Map, it seems the Map cant fully load. See attached.

![screen](https://cloud.githubusercontent.com/assets/20760362/17477531/0e440c96-5d66-11e6-8240-1a02c4ce7dd1.JPG)

**Comment by cmachikas** [comment]
I was able to get Ashex s suggestion to work with less work. I'll update documents later with my solution and conf.d file.

**Comment by lota7** [comment]
Wonderful! Much appreciated :+1:

**Comment by cmachikas** [comment]
@lota7 Please see my pull request here: #221
