### ISSUE TITLE
Can't disable search using -ss FILE.json

### ISSUE THREAD

**Issue by mrfantomex** [PokemonGoMap/PokemonGo-Map#810]
When I disable the search in the UI, it keeps searching.

**Comment by pyr0ball** [comment]
-ss flag does not disable search, it switches to spawnpoint only scanning (AKA TBTerra's scan implementation).

**Comment by gkuiper** [comment]
You mean that there is no way of generating a json file containing spawnpoints while NOT enabling the searcher?

**Comment by mrfantomex** [comment]
In the UI there is a switch to turn off searching. Essentially its a "pause" button. This works in spiral-beehive mode, but doesn't pause spawnpoint scanning.

**Comment by pyr0ball** [comment]
@gkuiper use this to dump your existing database to json: [set.py](https://gist.githubusercontent.com/cramk/c0e0b0e8466b28141033ba14d4a1b88e/raw/2521665ef45f669aaaa36fd264361def71e2b4fc/set.py)

**Comment by mrfantomex** [comment]
Based on commit log I doubt this was fixed.

**Comment by mrfantomex** [comment]
What does that have to do with this bug? Did you post in the wrong bug?

**Comment by gkuiper** [comment]
It will be fixed once #901 is merged.
