### ISSUE TITLE
Make "Scan Locations" coincide with pokemon's Depsawn time

### ISSUE THREAD

**Issue by r3pek** [PokemonGoMap/PokemonGo-Map#813]
## Expected Behavior

when using -ss, the Scanned Location circles still remain after the pokemon despawn time happens. The suggestion is to make it coincide with the despawn time. 

## Current Behavior

Instead of showing a red circle of scanned locations without a pokemon in it, just remove it after despawn time

## Steps to Reproduce (for bugs)

1. start a worker with -ss
2. activate "Scaned Locations"

**Comment by slideup-benni** [comment]
the circles has nothing to do with the found pokemons. they only visualize the last scan.

For example, when anybody update the search-script to find multiple pokemons at once, the position of the circle won't be the position of the spawned pokemon, and this makes your request obsolete.

But if you want to add a feature request you should add it here: http://feathub.com/PokemonGoMap/PokemonGo-Map

as @BaIthamel likes to say: issues are not for help or feature requests
