### ISSUE TITLE
Cant run on port 80

### ISSUE THREAD

**Issue by AndreasEnemyr** [PokemonGoMap/PokemonGo-Map#815]
The website just loading, but when i change to 81 it works perfectly

**Comment by FlarumHostingCo** [comment]
service apache2 stop

**Comment by Baklap4** [comment]
you're probably having some other service running on port 80. One of the cases can be Skype which defaults ports are 80 and 443. 

On windows type:
netstat -aon | findstr :80

and then kill the process using it with your task manager ;)

**Comment by sebastienvercammen** [comment]
To add to @Baklap4's comment: Teamviewer also uses ports 80 and 443 by default.

**Comment by Zoruk** [comment]
And also skype use port 80 and 443

**Comment by BaIthamel** [comment]
This is not a support forum; please see [the discord #help channel](https://discord.gg/npVqkUn) for assistance.
