### ISSUE TITLE
Exception while downloading map

### ISSUE THREAD

**Issue by daveaspinall** [PokemonGoMap/PokemonGo-Map#82]
On a fresh server with a brand new Google Maps API key I'm getting the following exception when running my server:

```
[ search_worker_1][      auth_ptc][    INFO] PTC Access Token successfully retrieved.
[ search_worker_3][      auth_ptc][    INFO] PTC Access Token successfully retrieved.
[ search_worker_0][      auth_ptc][    INFO] PTC Access Token successfully retrieved.
[ search_worker_2][      auth_ptc][    INFO] PTC Access Token successfully retrieved.
[ search_worker_4][      auth_ptc][    INFO] PTC Access Token successfully retrieved.
[ search_worker_5][      auth_ptc][    INFO] PTC Access Token successfully retrieved.
[ search_worker_1][        search][ WARNING] Exception while downloading map: Seems your IP Address is banned or something else went badly wrong...
[ search_worker_1][        search][   ERROR] Search step 4 area download failed, retrying request in 5.5 seconds
```

## Expected Behavior
Search should complete successfully.

## Current Behavior
Search returns an exception stating my IP address is banned or something else went badly wrong.

## Steps to Reproduce (for bugs)
1. Start server
2. Returns exception

## Your Environment
* Version used: Latest develop branch
* Environment name and version: Python 2.7
* Operating System and version: Ubuntu LTS 16.04

Any ideas where to look?

**Comment by FrostTheFox** [comment]
This is telling you that you have been 403 Forbidden'd. This is usually due to an IP ban. If you're running from a cloud provider, there's a chance that it has been banned.

**Comment by daveaspinall** [comment]
Thanks for the quick response!

Right so the issue does lie with the IP. It's on a Google Cloud server which I literally just spun up. Might try stopping it and rebooting to get a new IP and see if that solves the issue.

**Comment by cmachikas** [comment]
Niantic often bans entire blocks of IPs from common Cloud Hosts.

**Comment by FrostTheFox** [comment]
Correct, they may have banned a block of IP's from GC, or even all IP's assigned to Google Cloud.

**Comment by FrostTheFox** [comment]
Usually it's a block or single IPs.

**Comment by daveaspinall** [comment]
Yep, seems any IP Google give me when restarting the instance is banned. Thanks for the help guys. I'll look to switch providers or try a static IP.

**Comment by FrostTheFox** [comment]
kk
