### ISSUE TITLE
IP Address Banned

### ISSUE THREAD

**Issue by blackhattristar** [PokemonGoMap/PokemonGo-Map#822]
I was wondering why I wasn't seeing Pokémon and thought maybe my account was banned, so I logged into Pokémon GO and noticed my account was not banned. That brought me to my server where I saw it spitting out this error message. 

`[ search_worker_0][        search][ WARNING] Exception while downloading map: Seems your IP Address is banned or something else went badly wrong...`

Now I've gone ahead and created 3 different serves all with new IP addresses and I am stilling receiving this error message. If it is the IP address, why would it say the IP address is banned?
## Current Behavior

It's working on my localhost:5000 but not my digital ocean server no matter how many servers I create it says the IP address may be banned.
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Python 2.7):
* Operating System and version (desktop or mobile):

**Comment by FlarumHostingCo** [comment]
All of DO is banned

**Comment by blackhattristar** [comment]
@FlarumHostingCo Is this recent? Because my server was working that last time I checked it which was just an hour or so ago. Maybe less.

**Comment by FrostTheFox** [comment]
It's been banned for quite a while, some regions reported still kinda working. What region was your server on?

**Comment by blackhattristar** [comment]
@FrostTheFox I have heard some people report that DO wasn't working but I've had mine working for about a month or so if not more on the San Fran 2 server. I've tried San Fran 1, 2, Frankfurt, New York. All of them seem to be banned now. How can they even ban any and all IP addresses coming from DO?

Do you recommend somewhere I can move to that is working?

**Comment by FrostTheFox** [comment]
Yep, US west seems to have been recently hit by another wave. Another user reported US West regions to be banned to me as well. I heard OVH is still working, not 100% on that though.

They have probably identified one IP address belonging to a DO server and banning the block of IP addresses it's in.

**Comment by FlarumHostingCo** [comment]
They can look up all IP ranges owned by a provider at www.arin.net

**Comment by blackhattristar** [comment]
@FrostTheFox Any way we could add OVH instructions to the Wiki?

**Comment by FrostTheFox** [comment]
I don't think OVH has a way like DigitalOcean, so it would likely just follow the linux instructions.

**Comment by blackhattristar** [comment]
@FrostTheFox If you don't mind me asking, which way are you running it?

**Comment by Cammo009** [comment]
I have a server from OVH and i have this message too. I Purchased another IP and added to the network and some reason its still staying this. Surely my second ip didnt get banned first go. It must be something else. 

@FrostTheFox Purchase a IP the in terminal do `ifconfig eth0:1 **YOUR-NEW-IP** up` 
This will add another ip to your network.
