### ISSUE TITLE
Map Stopped working 

### ISSUE THREAD

**Issue by Deathgem** [PokemonGoMap/PokemonGo-Map#829]
using the stardard release and it has been working great for several days but today I am now getting this error  - I uploaded a screen shot of my cmd screen below with my username and password removed

![image](https://cloud.githubusercontent.com/assets/21119698/17802193/89adc904-658a-11e6-9f8d-b9f614e0810c.png)

Search Step 1 map parsing failed
I checked and my PTC username and password are still good so the account isnt banded.  
I am really a newbie with this so aside form erasing every thing a couple times and running through the whole process of compiling it again - which did not work -  I am at a loss of what to do.

**Comment by Akraev** [comment]
I can confirm. Getting the same error on my end as well: _KeyError: 'map_cells'_

**Comment by angrymoose** [comment]
Your account has been banned whether it is a soft,hard  or ip ban I am not sure. That specific error states you failed to retrieve data from the server. Having run multiple accounts scanning thats what happens when they perform a ban. Though if it allows you to log in to the game its probably a soft ban.

**Comment by HusbandoMax** [comment]
I usually loose a few account everyday on my maps had up to 20 banned in a day. just make new ones as long as you're not ip banned.

**Comment by Deathgem** [comment]
I made a new account and tried that still no luck - how can you tell if you are IP banned?  does it matter if I get a new map key?

**Comment by angrymoose** [comment]
The map key is from google and they do not care what you are doing with it. The only way to check for an ip ban is to try with a different ip. But new accounts must accept the terms of service before they can pull data. Have you agreed to the terms of service on the newly created account ?

**Comment by HusbandoMax** [comment]
Are you confirming the tos in game?

**Comment by BaIthamel** [comment]
This is not a support forum; please see [the discord #help channel](https://discord.gg/npVqkUn) for assistance.
