### ISSUE TITLE
can't install on debian

### ISSUE THREAD

**Issue by professorswag123** [PokemonGoMap/PokemonGo-Map#831]
i always get this error when i run sudo -H pip install -r requirements.txt on 
PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
NAME="Debian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"

Command python setup.py egg_info failed with error code 1 in /tmp/pip-build-G9P7zH/protobuf-to-dict
Storing debug log for failure in /root/.pip/pip.log

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip-build-G9P7zH/protobuf-to-dict
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 290, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1230, in prepare_files
    req_to_install.run_egg_info()
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 326, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/usr/lib/python2.7/dist-packages/pip/util.py", line 716, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command python setup.py egg_info failed with error code 1 in /tmp/pip-build-G9P7zH/protobuf-to-dict

pip-build-G9P7zH doesnt even exist

**Comment by angrymoose** [comment]
This is not a bug you do not have pip installed.

**Comment by professorswag123** [comment]
$ pip --version
pip 1.5.6 from /usr/lib/python2.7/dist-packages (python 2.7)

**Comment by angrymoose** [comment]
hmm then easy setup tools isn't installed.

apt-get install python-setuptools
easy_install pip

**Comment by professorswag123** [comment]
# easy_install pip
Searching for pip
Best match: pip 1.5.6
Adding pip 1.5.6 to easy-install.pth file
Installing pip script to /usr/local/bin
Installing pip2.7 script to /usr/local/bin
Installing pip2 script to /usr/local/bin

Using /usr/lib/python2.7/dist-packages
Processing dependencies for pip
Finished processing dependencies for pip


$ apt-get install python-setuptools
python-setuptools ist schon die neueste Version. (is up to date)

**Comment by pyr0ball** [comment]
It's much more complicated than this. You need to build python 2.7.12 from source, then use get-pip.py to upgrade your pip to 8.1.2.

Debian 8's sources lists are horribly out of date.

**Comment by professorswag123** [comment]
i go try on ubuntu
