### ISSUE TITLE
Scanned locations don't work anymore

### ISSUE THREAD

**Issue by Mwisho** [PokemonGoMap/PokemonGo-Map#834]
Since a few days i can't see the scanned locations anymore, i scan with -st 12 but it only shows one green circle in the bottom left corner...

Any idea how i can fix this or what i'm doing wrong?

**Comment by stylefabrik** [comment]
same here

**Comment by pyr0ball** [comment]
Debug terminal output, configuration, number of workers/accounts? Very difficult to diagnose an issue without any information.

Also please keep in mind, this is a bug issue tracker, not a support forum. Please get support from the #help channel on discord. Closing for now. If you identify a bug you can re-open the issue with details.
