### ISSUE TITLE
Done two little extensions ... You are interest in?

### ISSUE THREAD

**Issue by elvquant** [PokemonGoMap/PokemonGo-Map#836]
1. Additional to webhook I have implement an push-notification based on prowl (iOS) and NotifyMyAndroid. Defining type and apikey, I can define rarity and/or Pokemon number, which should make an push notification. The notification includes notification type (Rarity/Pokemon), Name (language based), hide time and date, distance (metric) and direction (wind rose and degree). It is made very compact so it perfect displayed on my pebble. If western longitude and southern latitude are negative, the distance/direction should by calculated right. Only at -180-/180-longitude a problem exists.
1a. Added pokemon name and rarity to json data for the webhook call ...

2. Additional search definition (I called it step-orientation). On horizontal type it made additional quarter circle left and right to the hexagon. On vertiacal on the upper and lower side.

I made it in the version from 2016-08-12, I think. You are interest in theses features and code review, so I can a context-diff.

**Comment by angrymoose** [comment]
It sounds interesting, do you have any screenshots ?

**Comment by ghvanderweg** [comment]
Why not open a pull request?

**Comment by elvquant** [comment]
@ghvanderweg I want to do it, but I'm failed. Possible, I'm mobile ... Back home in about 6 hours.

@angrymoose 
[https://picload.org/image/rridwolo/image.jpg](url)
[https://picload.org/image/rridwoop/image.jpg](url)
[https://picload.org/image/rridwolg/image.jpg](url)
[https://picload.org/image/rridwold/image.jpg](url)

**Comment by roflinger** [comment]
pokealarm uses a nice config file - why don´t u also try this instead of a hell of parameter

**Comment by justsomedudeonthenet** [comment]
I think it would be better to leave notifications to a separate webhook program.

If prowl gets added, why not Slack, email, irc, discord, msn messenger, etc.  Leaving that all separate makes more sense to me.  Plus I can change alert settings without restarting the scanner.

**Comment by elvquant** [comment]
@justsomedudeonthenet you are right, but I was much to lazy to made a separate webhook service. Additional there are not all information given in json-data to the webhook. Name and Rarity are easy to add, because the information are available directly at create the data structure. Not as easy is it to get a reference location (you position, marker sign) to calculate distance and direction ...

I only ask for interest ... ;-)

**Comment by elvquant** [comment]
I think about to make an webhook 

@roflinger all Parameters can also put into config.ini ;-)
