### ISSUE TITLE
Change map style and search marker

### ISSUE THREAD

**Issue by realbunny** [PokemonGoMap/PokemonGo-Map#838]
Cant find this on the wiki, and tried to search for it here(with no luck).

How can i change the map style(pogo map style) and search marker(none) as default? I'm sharing my map, so i want it to be a default for everybody that access it.

EDIT: Just to clarify, is there any arguments you use?

**Comment by hklcf** [comment]
@realbunny you need to edit map.js inside static/js and run `npm install` again

**Comment by pyr0ball** [comment]
This is not a forum for posting help requests, it's for tracking bugs and issues with the repo's code. Please get support from #help in the discord chat. Closing
