### ISSUE TITLE
No module named flask_cache_bust

### ISSUE THREAD

**Issue by xyc1993** [PokemonGoMap/PokemonGo-Map#842]
I've set up the application according to instructions, everything proceeded with no errors but when I run it for the frist time using:
`python ./runserver.py --help`

I get the following error:
```
Traceback (most recent call last):
  File "./runserver.py", line 19, in <module>
    from flask_cache_bust import init_cache_busting
ImportError: No module named flask_cache_bust
```
What should I do in order to make it work?

**Comment by Newbiehere2** [comment]
have you done this before : install -r requirements.txt    ?

**Comment by xyc1993** [comment]
Here:
[](https://pgm.readthedocs.io/en/develop/basic-install/index.html)
It's written to use this command:
`sudo -H pip install -r requirements.txt`
So I did, followed further instructions and it didn't work BUT when instead I used:
`pip install -r requirements.txt`
And followed further instructions it began to work. I don't know why is that :/

**Comment by Zentriert** [comment]
Sudo is a unix command so if you're on Windows it won't work ..

**Comment by xyc1993** [comment]
I am using Ubuntu 14.04 LTS so...

**Comment by pyr0ball** [comment]
Closing. Glad you got it fixed, but please get support from #help in the discord chat in future, as this is for tracking issues with code.
