### ISSUE TITLE
Webhook queue is > 50 ?

### ISSUE THREAD

**Issue by rrbailey89** [PokemonGoMap/PokemonGo-Map#853]
## Expected Behavior

Not to receive this error
## Current Behavior

Using brand new accounts and scanning in a new location while webhook is enabled I receive this 

```
2016-08-19 10:17:14,553 [    wh-updater-0][       webhook][ WARNING] Webhook queue is > 50 (@714); try increasing --wh-threads
2016-08-19 10:17:15,568 [    wh-updater-0][       webhook][ WARNING] Webhook queue is > 50 (@713); try increasing --wh-threads
2016-08-19 10:17:16,572 [    wh-updater-0][       webhook][ WARNING] Webhook queue is > 50 (@712); try increasing --wh-threads
2016-08-19 10:17:17,575 [    wh-updater-0][       webhook][ WARNING] Webhook queue is > 50 (@711); try increasing --wh-threads
2016-08-19 10:17:18,585 [    wh-updater-0][       webhook][ WARNING] Webhook queue is > 50 (@710); try increasing --wh-threads
2016-08-19 10:17:19,592 [    wh-updater-0][       webhook][ WARNING] Webhook queue is > 50 (@709); try increasing --wh-threads
```
## Steps to Reproduce (for bugs)

1. Create new accounts
2. Scan new area
3.
4.

## Context

I am able to scan just fine in an area I have scanned before with old accounts, While scanning with new accounts I receive this error. I closed my webhook server and still received the error, it only went away after commenting the line in config.ini.
## Your Environment

* Version used: Latest Dev
* Environment name and version (e.g. Python 2.7): Python 2.7
* Operating System and version (desktop or mobile): Windows 10

**Comment by pyr0ball** [comment]
Can you confirm the status of your accounts? are they activated, ToS accepted, pokemon caught, and tutorial finished?

**Comment by rrbailey89** [comment]
@pyr0ball First Screenshot is with webhooks enabled in config.ini 

![](http://i.imgur.com/5ZPNwqq.png)

Webhooks commented out in config.ini

![](http://i.imgur.com/JGxSP9S.png)

I litterally just created these accounts today and used ptc-acc-gen to do so I witnessed the ToS script in action and as you can see from the second screenshot they do upsert results.

**Comment by jnovack** [comment]
Holy shitballs.  346 Pokestops at 32.7187/-117.1630?? 

That's part of the problem.  Massive queue of pokestops.

Are the requests getting fired?? Do you see them coming in??

**Comment by rrbailey89** [comment]
@jnovack im not sure i understand your question. the webhook im using is pokealarm. it only pushes pokemon. I get that error whether or not i actually have the webhook server running unless i comment the line in config.ini

**Comment by jnovack** [comment]
0 (pokemans) + 346 (pokestops) + 16 (gyms) = 362.

COINCIDENTALLY, your web-hook queue is `@361` after processing.  Methinks that it's processing ALL webhooks, at 1 per second.

**Comment by rrbailey89** [comment]
@jnovack how would I fix this? Is it a bug or do I need to do something?

**Comment by jnovack** [comment]
FIX this? Learn python, diagnose error, submit pull-request

Do you need to do something? Probably not, the issue seems valid on the surface, someone who knows Python will look at this at their leisure.

**Comment by rrbailey89** [comment]
@jnovack very well

**Comment by porcoRedwood** [comment]
@rrbailey89 Add this line to your config.ini:
```
webhook-updates-only:   true
# only sendeupdates to webhooks, (excludes gyms & non-lured pokéstops)
```
With this recent commit #742 , by default pokéstop data is sent to webhook, which is a lot more data than before. The author kindly provided a flag to limit the data flow, to "only sendeupdates to webhooks, (excludes gyms & non-lured pokéstops)".

Alternatively, you could also follow the suggestion for the log itself: "try increasing --wh-threads"

**Comment by chuyskywalker** [comment]
Optimizing webhooks and deprecating the "hook per <item>" setup is high on my shit list for the way the app works.

**Comment by rrbailey89** [comment]
@porcoRedwood thank you. While it did not eliminate all occurrences of this error, your help did make it possible for me to scan a new area.
