### ISSUE TITLE
error search.py - model.py

### ISSUE THREAD

**Issue by Whynick** [PokemonGoMap/PokemonGo-Map#860]
16-08-19 20:53:48,657 [   ss-worker-522][        search][   ERROR] Exception in search_worker: sequence index must be integer, not 'str'
Traceback (most recent call last):
  File "/prod/PokemonGo-Map/pogom/search.py", line 557, in search_worker_thread_ss
    findCount = parse_map(args, response_dict, step_location, dbq, whq)
  File "/prod/PokemonGo-Map/pogom/models.py", line 383, in parse_map
    cells = map_dict['responses']['GET_MAP_OBJECTS']['map_cells']
TypeError: sequence index must be integer, not 'str'

## Expected Behavior

After few minutes, the error appear and the webserver crash but some workers make the work.
## Your Environment

* Version used:
* Environment name and version (e.g. Python 2.7):
Python 2.7
commit 903 of pokemon go map
work with -ss option and spawns.json
* Operating System and version (desktop or mobile):
Ubuntu 16.04 for the server

**Comment by pyr0ball** [comment]
You've got a banned account there buddy
