### ISSUE TITLE
Request: Additional Infos for Webhook-Data

### ISSUE THREAD

**Issue by elvquant** [PokemonGoMap/PokemonGo-Map#871]
Hi,

it is possible to add some more informations to web hook data?
Pokemonname and Rarity are easy to add in "parse_map" (models.py)
But the location of the "current marker" is not as easy (need for calculation distance and direction)

Webhook for … https://github.com/PokemonGoMap/PokemonGo-Map/issues/836

```
                pokemon_id = p['pokemon_data']['pokemon_id']
                webhook_data = {
                    'encounter_id': b64encode(str(p['encounter_id'])),
                    'spawnpoint_id': p['spawn_point_id'],
                    'pokemon_id': pokemon_id,
                    'latitude': p['latitude'],
                    'longitude': p['longitude'],
                    'disappear_time': calendar.timegm(d_t.timetuple()),
                    'last_modified_time': p['last_modified_timestamp_ms'],
                    'time_until_hidden_ms': p['time_till_hidden_ms'],
                    'name': get_pokemon_name(pokemon_id),
                    'rarity': get_pokemon_data(pokemon_id)['rarity']
                }

```

**Comment by elvquant** [comment]
Webhook for … https://github.com/PokemonGoMap/PokemonGo-Map/issues/836#event-761658098

**Comment by intelunlimited** [comment]
I'd also like to add the request to bring back the removed information if a pokemon was lured or not. That was helpful. Thank you.

**Comment by BaIthamel** [comment]
Feathub is for feature requests please.

**Comment by elvquant** [comment]
I have tried it, but I'm failed ...
