### ISSUE TITLE
map is undefined after git pull

### ISSUE THREAD

**Issue by jeremydevos** [PokemonGoMap/PokemonGo-Map#88]
## Expected Behavior
ReferenceError: center_lat is not defined
map.min.js (ligne 5, col. 529)

TypeError: map is undefined
map.min.js (ligne 5, col. 29638)

## Steps to Reproduce (for bugs)
Show and open url map

## Context
develop

**Comment by Romfrosk** [comment]
Download a fresh copy of the Templates\*.html files and it will work again

**Comment by jeremydevos** [comment]
I still have the same error even recovering files to the git, I see that there was a commit that modifies a lot of thing. The # 61 v3.0.0

**Comment by balrok** [comment]
run `npm install` - same as #169
