### ISSUE TITLE
-ss not behaving as expected

### ISSUE THREAD

**Issue by mrfantomex** [PokemonGoMap/PokemonGo-Map#882]
This might just be a documentation issue but I suspect not:

`python runserver.py -ss -l YOURLOCATION -st STEPS`

I expect this to run in spawn mode using all spawn points in my DB (the ones that show up on my map) that are withing -st STEPs from -l. That is not what happens. What happens instead is it uses a set of spawn points from some unknown source (maybe cached from previous dump) and ignores recent spawn points.

`python runserver.py -ss YOURFILE.json -l YOURLOCATION -st STEPS --dump-spawnpoints`

I expect this to be essentially the same command as above, only it also dumps the spawns into the json file. This command actually fixes the above problem in that it picks up my new spawn points. For example, the first command said I had ~500 spawn points. But when I run this command with same -l and -st, I see 1600 spawn points. There were no beehive scans between the two commands.

The problem with this command is it doesn't respect -st. Its taking my entire DB of spawn points and searching over it. With an -st of 50 its scanning nearly 100 st away.

**Comment by pyr0ball** [comment]
This is a configuration issue. you need to call out the source of your spawns: `-ss spawns.json`

Please post in the support forum, or seek assistance on Discord. The issue tracker is for bugs only.

**Comment by mrfantomex** [comment]
Like I said maybe its a documentation issue, but the application is not behaving as specified which is a bug.

I'm clearly calling out the source of the spawns. I'm not sure you read the entire bug here.
