### ISSUE TITLE
Parsing No Pokemon

### ISSUE THREAD

**Issue by auisgold** [PokemonGoMap/PokemonGo-Map#886]
Expected Behavior
Pokemon should be parsed onto the map as usual 

 Current Behavior
After updating to the latest commit now pokemon do not show up and are not parsed

Possible Solution
 Don't know if Niantic decided to change their api today or something weird on this end

## Steps to Reproduce (for bugs)

1. Run server with -st 10 -sd 15 any location
2. Looks at what is being parsed
3.
4.

## Your Environment

* Version used: latest version
* Environment name and version (e.g. Python 2.7): Python 2.7
* Operating System and version (desktop or mobile): Windows 10 64-bit

**Comment by LIJE** [comment]
Same issue.

**Comment by angrymoose** [comment]
The servers are currently very flaky with all versions of the map & the legit client. It's been happening all day. But to be certain I pulled the latest dev and checked for the problem on my end and it works fine,

**Comment by pyr0ball** [comment]
Probably not a bug, configuration or server issue. Please seek assistance on discord or the support forums: http://pokemongo-map.me
