### ISSUE TITLE
wh-updater errors: Webhook queue is > 50 (@51); try increasing --wh-threads

### ISSUE THREAD

**Issue by neskk** [PokemonGoMap/PokemonGo-Map#888]
You guys seem to break a couple of things whenever you change anything, will stop updating so often...
## Expected Behavior

I had 3 workers posting to 3 different webhooks (they don't overlapse) and everything was working great.

## Current Behavior

Since the update of the supervisor/thread manager/whatever all of the three workers constantly spam:
```
[wh-updater-5][webhook][ WARNING] Webhook queue is > 50 (@51); try increasing --wh-threads
```
## Possible Solution

Tried to increase the --wh-threads to 5 and then 10, but it didn't help at all.

## Steps to Reproduce (for bugs)

1. Install PokemonGo-Map
2. Launch 3 workers to 3 different webhooks
3. Run workers
4. Watch the swarm of dumb errors appear.

## Context

I want to report to different webhooks based on the location of the workers it seems that there's no out-of-the-box solution for this so I'm using https://github.com/kvangent/PokeAlarm to listen the webhook.

## Your Environment

* Version used: Latest
* Environment name and version (e.g. Python 2.7): 2.7
* Operating System and version (desktop or mobile): Ubuntu 16.04 server

**Comment by zorq** [comment]
add cmd arg --webhook-updates-only, it'll lower the number of things sent.

**Comment by pyr0ball** [comment]
Not a bug, please get configuration help on discord or the support forum: http://pokemongo-map.me/

**Comment by neskk** [comment]
LOL nice 1990's forum, having to do another account to have support... such a good job pyr0ball.

**Comment by neskk** [comment]
LOL 1990's support forum, that will be a blast :-P
Thanks for the --wh-updates-only tip, it seems to have worked. Any chance I can put this in config.ini?

**Comment by jane0815** [comment]
I have the same problem. When i set webhook-updates-only: true i don't get alerts (for gyms) anymore.
