### ISSUE TITLE
Workers crashes : AttributeError

### ISSUE THREAD

**Issue by Slivo-fr** [PokemonGoMap/PokemonGo-Map#89]
The worker throw an exception "AttributeError"

## Expected Behavior
Map work fine :P

## Current Behavior
Each worker crash with an exception

> 2016-08-08 10:07:41,618 [      MainThread][     runserver][    INFO] Parsed location is: 43.6184/3.9145/0.0000 (lat/lng/alt)
> 2016-08-08 10:07:41,621 [      MainThread][        models][    INFO] Connecting to local SQLite database
> 2016-08-08 10:07:41,621 [      MainThread][     runserver][    INFO] Clearing database
> 2016-08-08 10:07:44,066 [   search_thread][        search][    INFO] Search overseer starting
> 2016-08-08 10:07:44,066 [   search_thread][        search][    INFO] Starting search worker threads
> 2016-08-08 10:07:44,070 [   search_thread][        search][    INFO] New location caught, moving search grid
> 2016-08-08 10:07:44,070 [ search_worker_0][        search][    INFO] Search step 1 beginning (queue size is 1)
> 2016-08-08 10:07:44,071 [ search_worker_2][        search][    INFO] Search step 2 beginning (queue size is 2)
> 2016-08-08 10:07:44,071 [ search_worker_1][        search][    INFO] Search step 3 beginning (queue size is 2)
> 2016-08-08 10:07:44,071 [ search_worker_2][        search][   ERROR] Exception in search_worker:
> Traceback (most recent call last):
>   File "/home/pokemap/pogom/search.py", line 219, in search_worker_thread
>     check_login(args, account, api, step_location)
>   File "/home/pokemap/pogom/search.py", line 266, in check_login
>     api.set_authentication(provider = account['auth_service'], username = account['username'], password = account['password'])
>   File "/home/pokemap/src/pgoapi/pgoapi/pgoapi.py", line 89, in __getattr__
>     raise AttributeError
> AttributeError

## Context
I'm on debian x64, python 2.7, running the exact same command line than the previous repository.
The old version run fine (but does not got any information from server ofc)
I tried to update the old local repo with the new URL, and to checkout a brand new clone, both fail same way

**Comment by lix7** [comment]
I had the same issue but not sure how I fixed it but it works now. 
1. Get latest copy from github
2. Copy pip, pip2.7, pip2 (not sure if all is needed but it worked for me) from the python folder into the root folder of the app
3. Do "pip install -r requirements.txt --upgrade"
4. npm install

**Comment by duchoang** [comment]
For me, I don't need the step 2, step 3 is more important with `--upgrade` param

**Comment by lix7** [comment]
That's good to hear duchoang. I was assuming that was the major step too. Might have something that was installed wrong or missing during my previous pip installs

**Comment by Bart274** [comment]
thanks for the advice you guys this did the trick for me indeed:
```
pip install -r requirements.txt --upgrade
npm install
```

**Comment by Slivo-fr** [comment]
Does not solve the problem for me

**Comment by maximal** [comment]
Same issue for me.

```
pip install -r requirements.txt --upgrade
npm install
```
does not solve the problem. Still have:
```
2016-08-08 12:21:37,627 [ search_worker_0][        search][    INFO] Search step 270 beginning (queue size is 1)
2016-08-08 12:21:37,627 [ search_worker_0][        search][   ERROR] Exception in search_worker: 
Traceback (most recent call last):
  File "/home/yunx/sites/gdepokemongo.ru/www/map/.bel.new2/pogom/search.py", line 219, in search_worker_thread
    check_login(args, account, api, step_location)
  File "/home/yunx/sites/gdepokemongo.ru/www/map/.bel.new2/pogom/search.py", line 266, in check_login
    api.set_authentication(provider = account['auth_service'], username = account['username'], password = account['password'])
  File "/home/yunx/sites/gdepokemongo.ru/www/map/.bel.new/src/pgoapi/pgoapi/pgoapi.py", line 89, in __getattr__
    raise AttributeError
AttributeError
```

**Comment by Slivo-fr** [comment]
starting from scratch, with a new folder cloning the repository again worked with pip install -r requirements.txt --upgrade

**Comment by maximal** [comment]
Give it one more try, and deleted old directory. It works for now, thanks.
But there is no items on the map: no pokestops, no gyms, no monsters… :-(
