### ISSUE TITLE
How'd you guys managed to register tons of accounts?

### ISSUE THREAD

**Issue by craywong** [PokemonGoMap/PokemonGo-Map#898]
Seems like we can only register 5 or 6 gmails using one phone number right? How come some of you could have thousands of accounts?

**Comment by Maveryy** [comment]
You don't need any phone number to register a account. What are you talking about?

**Comment by justinkwaugh** [comment]
You can also use services like mailinator.com (except that they just stopped allowing those, but there are others that work)

**Comment by iwes** [comment]
https://github.com/FrostTheFox/ptc-acc-gen

**Comment by pyr0ball** [comment]
The is an issue tracker for bugs, not a support forum. Please visit the #help channel on discord or the actual support forum: http://pokemongo-map.me/
