### ISSUE TITLE
[Feature Request] Statistics search for Pokémon

### ISSUE THREAD

**Issue by Zerotask** [PokemonGoMap/PokemonGo-Map#902]
It would be comfortable if you could search for Pokémon instead of searching them manually / using ctrl + f.

**Comment by ItsCEED** [comment]
You have the stats on the right site and its really clear. There is no need of search option for something that is easy to done with your eyes only.

**Comment by ItsCEED** [comment]
Oops, uou are talking about /stats.

Why dont you make a small php script and make all the stats you want and you need?

**Comment by BaIthamel** [comment]
Feathub
