### ISSUE TITLE
Circle sizes and clearing scanned locations

### ISSUE THREAD

**Issue by N1F2H3** [PokemonGoMap/PokemonGo-Map#909]
I deployed project to jelastic and I have couple of questions, thanks in advance!
Is it possible to make the circles bigger while scanning?
and how can i clear scanned data? for example completely clear scanned locations

**Comment by darkelement1987** [comment]
I would actually like to make them smaller and give them less opacity.

**Comment by MatthiasDING** [comment]
use -cd to clear all scanned locations

**Comment by darkelement1987** [comment]
Would be nice if it was possible from the client

**Comment by N1F2H3** [comment]
-cd I have that command but it aint working, will try with pogom.db.
I want to make the circle bigger to make it scan only 1 time. for example make it scan one big area near me and stop.

**Comment by hagehg** [comment]
@N1F2H3 The game's servers only report Pokemon near your location up untill a certain distance. That's why the circles are the size they are. Making them bigger would return no Pokemon

**Comment by angrymoose** [comment]
ISSUES ARE NOT FOR SUPPORT!!!

  Join discord (channel: #help) for support at this link: https://discord.gg/PWp2bAm
