### ISSUE TITLE
New Error Message

### ISSUE THREAD

**Issue by blackhattristar** [PokemonGoMap/PokemonGo-Map#910]
I've got the map running on Jelastic and I've seen this error message once or twice. 

`2016-08-21 16:24:59,438 [ search_worker_0][ search][ INFO] Search step 7 beginning (queue size is 54) Exception in thread Thread-18522: Traceback (most recent call last): File "/usr/local/lib/python2.7/threading.py", line 801, in __bootstrap_inner self.run() File "/usr/local/lib/python2.7/threading.py", line 754, in run self.__target(*self.__args, **self.__kwargs) File "/usr/local/lib/python2.7/SocketServer.py", line 599, in process_request_thread self.handle_error(request, client_address) File "/usr/local/lib/python2.7/SocketServer.py", line 596, in process_request_thread self.finish_request(request, client_address) File "/usr/local/lib/python2.7/SocketServer.py", line 331, in finish_request self.RequestHandlerClass(request, client_address, self) File "/usr/local/lib/python2.7/SocketServer.py", line 654, in __init__ self.finish() File "/usr/local/lib/python2.7/SocketServer.py", line 713, in finish self.wfile.close() File "/usr/local/lib/python2.7/socket.py", line 283, in close self.flush() File "/usr/local/lib/python2.7/socket.py", line 307, in flush self._sock.sendall(view[write_offset:write_offset+buffer_size]) error: [Errno 32] Broken pipe`

Also, I'm getting this error message too.

`[2016-08-21 16:28:39,631] ERROR in app: Exception on /raw_data [GET] Traceback (most recent call last): File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app response = self.full_dispatch_request() File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request rv = self.handle_user_exception(e) File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception reraise(exc_type, exc_value, tb) File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request rv = self.dispatch_request() File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request return self.view_functions[rule.endpoint](**req.view_args) File "/usr/src/app/pogom/app.py", line 100, in raw_data neLng) File "/usr/src/app/pogom/models.py", line 306, in get_recent for s in query: File "/usr/local/lib/python2.7/site-packages/peewee.py", line 2967, in __iter__ return iter(self.execute()) File "/usr/local/lib/python2.7/site-packages/peewee.py", line 2960, in execute self._qr = ResultWrapper(model_class, self._execute(), query_meta) File "/usr/local/lib/python2.7/site-packages/peewee.py", line 2656, in _execute return self.database.execute_sql(sql, params, self.require_commit) File "/usr/local/lib/python2.7/site-packages/peewee.py", line 3492, in execute_sql self.commit() File "/usr/local/lib/python2.7/site-packages/peewee.py", line 3316, in __exit__ reraise(new_type, new_type(*exc_args), traceback) File "/usr/local/lib/python2.7/site-packages/peewee.py", line 3485, in execute_sql cursor.execute(sql, params or ()) OperationalError: database is locked 2016-08-21 16:28:39,631 [ Thread-18658][ app][ ERROR] Exception on /raw_data [GET] Traceback (most recent call last): File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app response = self.full_dispatch_request() File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request rv = self.handle_user_exception(e) File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception reraise(exc_type, exc_value, tb) File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request rv = self.dispatch_request() File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request return self.view_functions[rule.endpoint](**req.view_args) File "/usr/src/app/pogom/app.py", line 100, in raw_data neLng) File "/usr/src/app/pogom/models.py", line 306, in get_recent for s in query: File "/usr/local/lib/python2.7/site-packages/peewee.py", line 2967, in __iter__ return iter(self.execute()) File "/usr/local/lib/python2.7/site-packages/peewee.py", line 2960, in execute self._qr = ResultWrapper(model_class, self._execute(), query_meta) File "/usr/local/lib/python2.7/site-packages/peewee.py", line 2656, in _execute return self.database.execute_sql(sql, params, self.require_commit) File "/usr/local/lib/python2.7/site-packages/peewee.py", line 3492, in execute_sql self.commit() File "/usr/local/lib/python2.7/site-packages/peewee.py", line 3316, in __exit__ reraise(new_type, new_type(*exc_args), traceback) File "/usr/local/lib/python2.7/site-packages/peewee.py", line 3485, in execute_sql cursor.execute(sql, params or ()) OperationalError: database is locked [2016-08-21 16:28:39,830] ERROR in app: Exception on /raw_data [GET] Traceback (most recent call last): File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app response = self.full_dispatch_request() File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request rv = self.handle_user_exception(e) File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception reraise(exc_type, exc_value, tb) File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request rv = self.dispatch_request() File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request return self.view_functions[rule.endpoint](**req.view_args) File "/usr/src/app/pogom/app.py", line 100, in raw_data neLng) File "/usr/src/app/pogom/models.py", line 306, in get_recent for s in query: File "/usr/local/lib/python2.7/site-packages/peewee.py", line 2967, in __iter__ return iter(self.execute()) File "/usr/local/lib/python2.7/site-packages/peewee.py", line 2960, in execute self._qr = ResultWrapper(model_class, self._execute(), query_meta) File "/usr/local/lib/python2.7/site-packages/peewee.py", line 2656, in _execute return self.database.execute_sql(sql, params, self.require_commit) File "/usr/local/lib/python2.7/site-packages/peewee.py", line 3492, in execute_sql self.commit() File "/usr/local/lib/python2.7/site-packages/peewee.py", line 3316, in __exit__ reraise(new_type, new_type(*exc_args), traceback) File "/usr/local/lib/python2.7/site-packages/peewee.py", line 3485, in execute_sql cursor.execute(sql, params or ()) OperationalError: database is locked 2016-08-21 16:28:39,830 [ Thread-18663][ app][ ERROR] Exception on /raw_data [GET] Traceback (most recent call last): File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app response = self.full_dispatch_request() File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request rv = self.handle_user_exception(e) File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception reraise(exc_type, exc_value, tb) File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request rv = self.dispatch_request() File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request return self.view_functions[rule.endpoint](**req.view_args) File "/usr/src/app/pogom/app.py", line 100, in raw_data neLng) File "/usr/src/app/pogom/models.py", line 306, in get_recent for s in query: File "/usr/local/lib/python2.7/site-packages/peewee.py", line 2967, in __iter__ return iter(self.execute()) File "/usr/local/lib/python2.7/site-packages/peewee.py", line 2960, in execute self._qr = ResultWrapper(model_class, self._execute(), query_meta) File "/usr/local/lib/python2.7/site-packages/peewee.py", line 2656, in _execute return self.database.execute_sql(sql, params, self.require_commit) File "/usr/local/lib/python2.7/site-packages/peewee.py", line 3492, in execute_sql self.commit() File "/usr/local/lib/python2.7/site-packages/peewee.py", line 3316, in __exit__ reraise(new_type, new_type(*exc_args), traceback) File "/usr/local/lib/python2.7/site-packages/peewee.py", line 3485, in execute_sql cursor.execute(sql, params or ()) OperationalError: database is locked [2016-08-21 16:28:40,731] ERROR in app: Exception on /raw_data [GET] Traceback (most recent call last): File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app response = self.full_dispatch_request() File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request rv = self.handle_user_exception(e) File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception reraise(exc_type, exc_value, tb) File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request rv = self.dispatch_request() File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request return self.view_functions[rule.endpoint](**req.view_args) File "/usr/src/app/pogom/app.py", line 90, in raw_data d['pokemons'] = Pokemon.get_active(swLat, swLng, neLat, neLng) File "/usr/src/app/pogom/models.py", line 101, in get_active for p in query: File "/usr/local/lib/python2.7/site-packages/peewee.py", line 2967, in __iter__ return iter(self.execute()) File "/usr/local/lib/python2.7/site-packages/peewee.py", line 2960, in execute self._qr = ResultWrapper(model_class, self._execute(), query_meta) File "/usr/local/lib/python2.7/site-packages/peewee.py", line 2656, in _execute return self.database.execute_sql(sql, params, self.require_commit) File "/usr/local/lib/python2.7/site-packages/peewee.py", line 3492, in execute_sql self.commit() File "/usr/local/lib/python2.7/site-packages/peewee.py", line 3316, in __exit__ reraise(new_type, new_type(*exc_args), traceback) File "/usr/local/lib/python2.7/site-packages/peewee.py", line 3485, in execute_sql cursor.execute(sql, params or ()) OperationalError: database is locked 2016-08-21 16:28:40,731 [ Thread-18664][ app][ ERROR] Exception on /raw_data [GET] Traceback (most recent call last): File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app response = self.full_dispatch_request() File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request rv = self.handle_user_exception(e) File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception reraise(exc_type, exc_value, tb) File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request rv = self.dispatch_request() File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request return self.view_functions[rule.endpoint](**req.view_args) File "/usr/src/app/pogom/app.py", line 90, in raw_data d['pokemons'] = Pokemon.get_active(swLat, swLng, neLat, neLng) File "/usr/src/app/pogom/models.py", line 101, in get_active for p in query: File "/usr/local/lib/python2.7/site-packages/peewee.py", line 2967, in __iter__ return iter(self.execute()) File "/usr/local/lib/python2.7/site-packages/peewee.py", line 2960, in execute self._qr = ResultWrapper(model_class, self._execute(), query_meta) File "/usr/local/lib/python2.7/site-packages/peewee.py", line 2656, in _execute return self.database.execute_sql(sql, params, self.require_commit) File "/usr/local/lib/python2.7/site-packages/peewee.py", line 3492, in execute_sql self.commit() File "/usr/local/lib/python2.7/site-packages/peewee.py", line 3316, in __exit__ reraise(new_type, new_type(*exc_args), traceback) File "/usr/local/lib/python2.7/site-packages/peewee.py", line 3485, in execute_sql cursor.execute(sql, params or ()) OperationalError: database is locked [2016-08-21 16:28:42,230] ERROR in app: Exception on /raw_data [GET] Traceback (most recent call last): File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app response = self.full_dispatch_request() File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request rv = self.handle_user_exception(e) File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception reraise(exc_type, exc_value, tb) File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request rv = self.dispatch_request() File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request return self.view_functions[rule.endpoint](**req.view_args) File "/usr/src/app/pogom/app.py", line 90, in raw_data d['pokemons'] = Pokemon.get_active(swLat, swLng, neLat, neLng) File "/usr/src/app/pogom/models.py", line 101, in get_active for p in query: File "/usr/loc`

`2016-08-21 16:52:31,141 [ search_worker_0][ models][ WARNING] database is locked... Retrying`

I'm not sure if it affects my map at all because It's still running and doing its thing but I figured I would mention it incase it means something. Any info would be greatly appreciated!
## Expected Behavior

No error message
## Current Behavior

Throwing Error Messages
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used: Latest Development Version running on Jelastic
* Environment name and version (e.g. Python 2.7):
* Operating System and version (desktop or mobile):

**Comment by ardeaf** [comment]
Are you using sqlite or mysql?

**Comment by BaIthamel** [comment]
Database is locked is a known issue. It's being worked on elsewhere.
