### ISSUE TITLE
Statistics page last seen -1 month

### ISSUE THREAD

**Issue by Zerotask** [PokemonGoMap/PokemonGo-Map#914]
The last seen flag of the Pokemon in the statistics page is 1 month in the past.

**Comment by angrymoose** [comment]
Is your system clock accurate ?  My first guess is either the system clock is off or at some point the data was inserted into the database with the wrong date. Also are you using mysql or sqlite ?

**Comment by Zerotask** [comment]
NTP is set up properly and I'm using MariaDB.

**Comment by angrymoose** [comment]
If your system time is correct this shouldn't be happening. Are you using the dev branch or stable ?

**Comment by BaIthamel** [comment]
This is not a support forum; please see [the discord #help channel](https://discord.gg/npVqkUn) for assistance.

**Comment by Zerotask** [comment]
For me it looks like an programm issue, not like a support issue.
