### ISSUE TITLE
"Regular database cleaning complete" - is it default now?

### ISSUE THREAD

**Issue by crckdns** [PokemonGoMap/PokemonGo-Map#916]
Just noticed after the update, it says now in console, it clears something! I never opted in to flee anything, I'm running a statistics scanner, I need the "old" data. I thought, the cleaning would happen only with some args added..

## Expected Behavior
I start the scanner, it accumulates the data without altering the existing data.
## Current Behavior
.....Regular database cleaning complete
## Possible Solution
let old data alone
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used: current dev
* Environment name and version (e.g. Python 2.7):
* Operating System and version (desktop or mobile): debian

**Comment by justsomedudeonthenet** [comment]
I believe this is only cleaning the scanned_locations table it uses to draw the scanned area circles.  Without doing that the table grows insanely large.

It doesn't delete any useful information.

**Comment by Cronick** [comment]
As far as I know. the standard "Regular database cleaning" is just cleaning old scanned locations, as they are not valid anymore, so there is no need to store these rows, where the bots has been previously.

**Comment by echo465** [comment]
If you have 5 scanning instances, do all 5 of them need to be cleaning?

**Comment by crckdns** [comment]
I run 19 instances + several webserver-only (with fixed location flag) .. and even the webserver instance spams the cleaning message..

**Comment by angrymoose** [comment]
@justsomedudeonthenet it has the downside of causing the scanner to crash on rare occasions. I'll wait till the next stable to further debug the issue as the dev branch is changing quite a lot and the bugs hard to trigger.

**Comment by chuyskywalker** [comment]
This database clearing has _always_ been occurring, the log message is all that's new. In fact, it happens _less frequently_ now (30 second timer, I think). It used to happen after _every_ database interaction.

This is not a bug.
