### ISSUE TITLE
Can't use Webhooks after update

### ISSUE THREAD

**Issue by sharklab** [PokemonGoMap/PokemonGo-Map#917]
I recently updated PokemonGo_Map but now i'm not able to send a single webhook, i just tried both the config.ini and the -wh "http://requestb.in/xxxx" methods. Is there something new? Here's my call

Python C:\PokemonGo-Map-3.1.0\runserver.py -a ptc -l "lat, long" -wh "http://requestb.in/yslwoeys" -st 50 -sd 5 -u user -p pass

Thanks!

**Comment by justsomedudeonthenet** [comment]
Webhooks are working just fine.

Your 5 second scan delay is probably making scans fail.  Needs to be 10 seconds.

Post debug logs (run with -d) if you still believe there is an issue, but I am using them just fine.

**Comment by sharklab** [comment]
yeah switching the -sd from 5 to 10 did the trick! Thanks
