### ISSUE TITLE
Map Cells arent parsing on the live map view

### ISSUE THREAD

**Issue by flightcoin** [PokemonGoMap/PokemonGo-Map#919]
## Current Behavior
Not scanning area and showing errors on my console (look below), map runs fine, but nothing is going on it, tried a few fresh install VMs and I get the same errors. I also have used 2 accounts and is still not working at all.

## Steps to Reproduce (for bugs)

1.Fresh install

## Context
  File "C:\Users\Administrator\Desktop\PokemonGo-Map-developwin\pogom\search.py"
, line 247, in search_worker_thread
    parse_map(response_dict, step_location)
  File "C:\Users\Administrator\Desktop\PokemonGo-Map-developwin\pogom\models.py"
, line 310, in parse_map
    cells = map_dict['responses']['GET_MAP_OBJECTS']['map_cells']
KeyError: 'map_cells'
2016-08-21 19:52:33,851 [ search_worker_0][        search][   ERROR] Search step
 1 map parsing failed, retrying request in 20 seconds. Username: SGECapBio1
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\PokemonGo-Map-developwin\pogom\search.py"
, line 247, in search_worker_thread
    parse_map(response_dict, step_location)
  File "C:\Users\Administrator\Desktop\PokemonGo-Map-developwin\pogom\models.py"
, line 310, in parse_map
    cells = map_dict['responses']['GET_MAP_OBJECTS']['map_cells']
KeyError: 'map_cells'

## Your Environment

* Version used: Latest
* Environment name and version: Server 2012 r2, Python 2.7
* Operating System and version (desktop or mobile): Desktop, Windows server 2012 r2

**Comment by BaIthamel** [comment]
This is not a support forum; please see [the discord #help channel](https://discord.gg/npVqkUn) for assistance.

**Comment by elvquant** [comment]
I got the same error overnight. Yesterday the PG-Map was working fine!

**Comment by flightcoin** [comment]
I believe this is a bug, not sure why it's not working. But I'll contact them anyway.

**Comment by elvquant** [comment]
The problem is, that the accounts are blocked by Niantic, a new account helps. But it is a bug (in thinking of robustness), because the data-structure should be checked before using it and give a better error message, to prevent bug-issues here!

**Comment by flightcoin** [comment]
I actually made a brand new account and it is still giving me the issue, thought that was pretty strange too. It didn't fix the problem at all.
