### ISSUE TITLE
TypeError Issue at startup : got an unexpected keyword argument 'syntax'

### ISSUE THREAD

**Issue by Outpox** [PokemonGoMap/PokemonGo-Map#92]
I cloned the repo, installed python modules, installed grunt globally, installed nodes modules.  
When I start the app with `python ./runserver.py --help` I've got the following error :  

```
> python ./runserver.py --help
Traceback (most recent call last):
  File "./runserver.py", line 29, in <module>
    import pgoapi
  File "/usr/local/lib/python2.7/dist-packages/pgoapi/__init__.py", line 50, in <module>
    from pgoapi.pgoapi import PGoApi
  File "/usr/local/lib/python2.7/dist-packages/pgoapi/pgoapi.py", line 34, in <module>
    from pgoapi.rpc_api import RpcApi
  File "/usr/local/lib/python2.7/dist-packages/pgoapi/rpc_api.py", line 50, in <module>
    from POGOProtos.Networking.Envelopes_pb2 import RequestEnvelope
  File "/usr/local/lib/python2.7/dist-packages/pgoapi/protos/POGOProtos/Networking/Envelopes_pb2.py", line 16, in <module>
    from POGOProtos.Networking import Requests_pb2 as POGOProtos_dot_Networking_dot_Requests__pb2
  File "/usr/local/lib/python2.7/dist-packages/pgoapi/protos/POGOProtos/Networking/Requests_pb2.py", line 23, in <module>
    ENCOUNTER\x10\x91\x01\x12!\n\x1c\x43OLLECT_DAILY_DEFENDER_BONUS\x10\x92\x01\x12\x14\n\x0fUPGRADE_POKEMON\x10\x93\x01\x12\x19\n\x14SET_FAVORITE_POKEMON\x10\x94\x01\x12\x15\n\x10NICKNAME_POKEMON\x10\x95\x01\x12\x10\n\x0b\x45QUIP_BADGE\x10\x96\x01\x12\x19\n\x14SET_CONTACT_SETTINGS\x10\x97\x01\x12\x15\n\x10GET_ASSET_DIGEST\x10\xac\x02\x12\x16\n\x11GET_DOWNLOAD_URLS\x10\xad\x02\x12\x1c\n\x17GET_SUGGESTED_CODENAMES\x10\x91\x03\x12\x1d\n\x18\x43HECK_CODENAME_AVAILABLE\x10\x92\x03\x12\x13\n\x0e\x43LAIM_CODENAME\x10\x93\x03\x12\x0f\n\nSET_AVATAR\x10\x94\x03\x12\x14\n\x0fSET_PLAYER_TEAM\x10\x95\x03\x12\x1b\n\x16MARK_TUTORIAL_COMPLETE\x10\x96\x03\x12\x16\n\x11LOAD_SPAWN_POINTS\x10\xf4\x03\x12\t\n\x04\x45\x43HO\x10\x9a\x05\x12\x1b\n\x16\x44\x45\x42UG_UPDATE_INVENTORY\x10\xbc\x05\x12\x18\n\x13\x44\x45\x42UG_DELETE_PLAYER\x10\xbd\x05\x12\x17\n\x12SFIDA_REGISTRATION\x10\xa0\x06\x12\x15\n\x10SFIDA_ACTION_LOG\x10\xa1\x06\x12\x18\n\x13SFIDA_CERTIFICATION\x10\xa2\x06\x12\x11\n\x0cSFIDA_UPDATE\x10\xa3\x06\x12\x11\n\x0cSFIDA_ACTION\x10\xa4\x06\x12\x11\n\x0cSFIDA_DOWSER\x10\xa5\x06\x12\x12\n\rSFIDA_CAPTURE\x10\xa6\x06\x62\x06proto3')
TypeError: __init__() got an unexpected keyword argument 'syntax'
```

## Environment

* Version used: Latest commit (78fee4a440c3ce24eac2b66a10953f15a684197e) 
* Environment name and version:  
  * Debian (Jessie)
  * Python 2.7.9
  * Pip 1.5.6  
  * NPM 3.3.12
  * Node 5.1.0

##Solution  
On debian: 
`sudo apt-get autoremove python-protobuf`  
`pip install -r requirements.txt`

**Comment by GareRam** [comment]
Exact same problem running the map on OSX 10.11.6. It appears protobuf has an issue, but that's all I can make of it.

**Comment by pokephreak** [comment]
I was getting this on Ubuntu, I removed protobuf, re-run pip install -r requirements.txt and it worked. Hope this helps.

**Comment by Outpox** [comment]
Yep that's what I've just done and it solved the issue.  
Editing main post to add the solution.

**Comment by FranManre** [comment]
on windows ive done:
```
pip uninstall -r requirements.txt
pip install -r requirements.txt
npm install
```
It worked like a charm, hope it helps someone

**Comment by bulldozier** [comment]
This worked for me on Mac:

brew rm protobuf
sudo -H install -r requirements.txt --upgrade

**Comment by charlie5188** [comment]
> sudo -H install -r requirements.txt --upgrade
should be 
`sudo -H pip install -r requirements.txt --upgrade`, right?

**Comment by Outpox** [comment]
Indeed, he missed `pip` in his command.

**Comment by bulldozier** [comment]
Thanks @charlie5188 and @Outpox ; I fixed the comment and put it in a code block.

**Comment by brunchboy** [comment]
Hmm, I am not willing to uninstall the homebrew version of Protobuf because it is a critical component of my own light show software open source project, which is frankly more important to me. I guess until they can coexist, I will give up on trying to install this tool, cool though it looks.
