### ISSUE TITLE
error during installation: "python setup.py egg_info" failed with error code 1"

### ISSUE THREAD

**Issue by danieleserra** [PokemonGoMap/PokemonGo-Map#923]
I have windows 7, and the release 3.1.0
When i try to install with the command "pip install -r requirements.txt"
Ive this output: 

Command "python setup.py egg_info" failed with error code 1 in C:\Users\Roxas\Ap                                   pData\Local\Temp\pip-build-k4etg5nl\wsgiref\

I searched for the error, but i cant solve it.
Please help me.

**Comment by aldarund** [comment]
Does it look like a support forum or whatever?  Did u read the placeholder when u opened this issue? Read first before opening such issues.

**Comment by danieleserra** [comment]
Im sorry

**Comment by aldarund** [comment]
Join discord (channel: #help) for support at this link: https://discord.gg/PWp2bAm

**Comment by pyr0ball** [comment]
Please post issues like this on the [Support Forum](jhttp://pokemongo-map.me) or on Discord
