### ISSUE TITLE
Getting the pokestop and gym locations from the database

### ISSUE THREAD

**Issue by ingr3ss** [PokemonGoMap/PokemonGo-Map#925]
Hi,

Anyone has a script or ways to extract all the pokestop and gym locations from the database and convert it into Google Maps KML file?

Thanks.

**Comment by jnovack** [comment]
No, but it would be nice!  Here's some assistance getting started. https://developers.google.com/kml/articles/phpmysqlkml

**Comment by angrymoose** [comment]
ISSUES ARE NOT FOR SUPPORT!!!

  Join discord (channel: #help) for support at this link: https://discord.gg/PWp2bAm

**Comment by BaIthamel** [comment]
This is not a support forum; please see [the discord #help channel](https://discord.gg/npVqkUn) for assistance.
