### ISSUE TITLE
[Bug] Significantly Late Spawn Scans

### ISSUE THREAD

**Issue by chriskellydev** [PokemonGoMap/PokemonGo-Map#931]
## Expected Behavior
When spawn scanning, scans should result in Pokemon with ~12-13 minutes expiration time (variance attributed to peak "spawn minutes" w/ low worker counts).

## Current Behavior
Pokemon scans are resulting in less Pokemon overall/more Pokemon with extremely low expiration times. Primarily times less than 5 minutes upon initial scan.

## Steps to Reproduce (for bugs)
This isn't really a "step by step" guide due to the nature of it, but here is what I've been doing to track these late spawns.

1. Set up a server-only instance.
2. Set up a 5 worker -ss spawns.json instance
  * spawns.json generated via spawnScan for a 5 sq. km area
  * Set up a webhook.
3. Set up a 5 worker -ss -st 10 instance using pogom.db
  * pogom.db contains weeks of beehive scans so has plenty of spawn information.
  * location centered on area using 10 steps covers the spawns.json file above.
  * Set up a webhook.
4. Set up a webhook reader that prints spawns with timestamps.
5. Wait for something to spawn w/ a significantly low timer.
6. Check spawns.json "time" attribute for spawn point.
7. Check pogom.db "time" attribute for spawn point.
8. Check webhook reader timestamp.

The purpose of having a spawnScan spawns.json instance running as well as a -ss -st 10 instance is to check time consistency (make sure one of them doesn't contain a bogus time). The webhook reader is to check that you should be getting spawn information at roughly the same time.

## Recent Example

I had a Kingler show up recently with < 5 minutes remaining (this isn't the worst scenario I've encountered, just the most recent I remembered to take a screenshot of),

Here's the screenshot of the information box on the map.
![image](https://cloud.githubusercontent.com/assets/4634288/17861531/6f3a0bbe-685f-11e6-809e-3726ff747393.png)

Here's the time from my spawnScan spawns.json. This indicates the spawn to be around hh:13 which matches up with the expiration time of hh:28.
```
{"time": 789}
```

Here's the entry in pogom.db. Matches the map data of course.

![image](https://cloud.githubusercontent.com/assets/4634288/17861899/edf1cc20-6860-11e6-97a0-455574006ff1.png)

And here are the log lines from a quick Webhook implementation indicating that it received information about the hh:13 Kingler at hh:23 (10 minutes after the spawn).
```
HH:23:19.403 DEBUG WebhookWriter        - Received pokemon spawn information. [Kingler]
HH:23:19.945 DEBUG WebhookWriter        - Received pokemon spawn information. [Kingler]
```

Now I waited hour waiting for the exact same spawn:

23 minutes after the hour I have nothing:

![image](https://cloud.githubusercontent.com/assets/4634288/17862681/47c80234-6864-11e6-816c-6114548c51fb.png)

A few seconds later (sorry, I redacted this one a little too much, but it is the same as the screenshot above)...
![image](https://cloud.githubusercontent.com/assets/4634288/17862482/704cdafa-6863-11e6-9de5-fe83539a5b35.png)

And the Webhook data:
```
HH:23:19.632 DEBUG WebhookWriter        - Received pokemon spawn information. [Bellsprout]
HH:23:19.900 DEBUG WebhookWriter        - Received pokemon spawn information. [Bellsprout]
```

Also, the workers are constantly idle. My area has 420/530 spawn points (my -st 10 instance has a little bit less area than my spawns.json instance). I could probably get away with 3 works just by looking at how often they get work. Here's a screenshot of a 7 worker thread status print out that has been running for a few hours.

![image](https://cloud.githubusercontent.com/assets/4634288/17862190/32ef1ab6-6862-11e6-9544-71e09f7061d8.png)

## Your Environment
* Tested on Windows 10 Pro / Fedora 24 Server
* Python 2.7

**Comment by justsomedudeonthenet** [comment]
I am working on a fix to this issue as we speak.  Don't worry :)

**Comment by BaIthamel** [comment]
Update to the latest version and try again.

**Comment by justsomedudeonthenet** [comment]
This happens if your workers get too far behind.  See https://github.com/PokemonGoMap/PokemonGo-Map/pull/932 which lets you specify how far behind you want to allow it to go before skipping spawns to catch up.

**Comment by chriskellydev** [comment]
Read my report. The workers aren't behind, they're idle. I  just updated to the search refactor commit (that was committed while I was typing this up). I'll check to see if my XX:13 spawn actually gets scanned at an appropriate time.

**Comment by chriskellydev** [comment]
Just passed by my XX:13 spawn and as expected, nothing showed up. However, at around ~XX:23 the thread status screen gave me:

```
Worker 003 | <stats> |45s early for location <insert my spawn point's lat/long>
```

**Comment by BaIthamel** [comment]
i'm going to assume there's a none code related issue so; This is not a support forum; please see [the discord #help channel](https://discord.gg/npVqkUn) for assistance.

**Comment by chriskellydev** [comment]
Thanks for closing a valid issue. I'm not asking for support, I'm informing you that your search queue isn't properly inserting items based on time. I spent a few hours checking these points to give you guys as much information as possible but instead you just close it without any investigation.

My spawn points/time are proper. I have more than enough workers. And this point (among others) is consistently inserted into the search queue late.
