### ISSUE TITLE
Multiple instances + Cleaning database

### ISSUE THREAD

**Issue by Lionir** [PokemonGoMap/PokemonGo-Map#934]
I have 4instances and one is always cleaning database instead of scanning...

**Comment by rrbailey89** [comment]
@Lionir is it the server window? Also this is not the place for support of this nature. Please post either on the support forums at pokemongo-map.me or in the Discord help chat.

**Comment by BaIthamel** [comment]
This is not a support forum; please see [the discord #help channel](https://discord.gg/npVqkUn) for assistance.
