### ISSUE TITLE
-ss not "finding" all the spawnpoints -- is it spawnpoint compression?

### ISSUE THREAD

**Issue by averylarry** [PokemonGoMap/PokemonGo-Map#939]
## Expected Behavior

Beehive scan shows n spawnpoints.  Using -ss should equally find n spawnpoints.
## Current Behavior

Using -ss "finds" fewer spawnpoints than exist in beehive.
## Steps to Reproduce (for bugs)

Is spawnpoint scanning compression on by default for -ss scanning?  #765 doesn't seem to have made it into dev branch.
In a small area, after clearing the database, I ran a -st 2 beehive for 2 hours:
runserver.py -l "my location" -st 2 -j -nk -ng

![capture](https://cloud.githubusercontent.com/assets/21130007/17869241/ff7f9fe6-6877-11e6-8f8b-a87c58f4e122.JPG)

There are 26 spawnpoints inside the beehive.  If you are conservative with edges, there are still at least 23 spawn points inside the beehive.  (Note the spawnpoints outside the scanned locations are from running -ss for a short period of time.)

When I then start a -ss session (without dumping a .json file), I get 17 spawn points to track:
runserver.py -l "my location" -st 2 -j -nk -ng
. . .
2016-08-22 14:07:18,375 [ search-overseer][        models][    INFO] Finding spawn points 2 steps away
2016-08-22 14:07:18,405 [      db-cleaner][        models][    INFO] Regular database cleaning complete
2016-08-22 14:07:18,469 [ search-overseer][        search][    INFO] Total of 17 spawns to track

If I increase to -st 3 (I read somewhere to +1 the steps for edge cases), I still only get 21 spawnpoints:
runserver.py -l "my location" -st 3 -j -nk -ng -ss
. . .
2016-08-22 14:11:52,065 [ search-overseer][        models][    INFO] Finding spawn points 3 steps away
2016-08-22 14:11:52,158 [ search-overseer][        search][    INFO] Total of 21 spawns to track

If I dump to a .json file it shows 17 or 21 depending on the step size, matching the above.

If not compression, could it be related to jitter?  I don't really know how since increasing to 3 steps should eliminate that as a possibility.  Plus it is consistent.  I always get 17 or 21.  I even tried -st 54 and it still only returned 21.
## Your Environment

* Version used: 0448f93
* Operating System and version (desktop or mobile): win7

**Comment by averylarry** [comment]
I did specify the same location each time -- I just formatted it wrong for displaying here.

**Comment by MonjoNL** [comment]
Haven't noticed this in a pre #901 build.
But not sure if this is broken now. I will test as well.

**Comment by MonjoNL** [comment]
I did re-generate a json with the pre #901 build and found 186 spawns for comparison reasons.
Then I upgraded to the latest build and generated the same json with the same location and steps and database and only found 134 spawns . So something doesn't look right, although the new code looks much better at first glance.
Definitely related to the latest build.

**Comment by lota7** [comment]
@MonjoNL When you did your testing, did you also see if you got upserts on initial login?
#901 was supposed to fix that but since you're having these issues also with #901, it's led me to believe alot got broken when merged.

**Comment by MonjoNL** [comment]
No just generated the json with the old and new version.
Focussing on that now.
I want to re-aply #787 before I start scanning again.

**Comment by averylarry** [comment]
Yes, that code will produce duplicates.  The original code messes up because it skips checking the next spawnpoint  everytime a spawnpoint is found because the next spawnpoint gets shifted into the list location (index) just vacated by the spawnpoint found and removed by pop.

Try this instead:

for hl in hex_locations:
            for sp in reversed(s):
                if geopy.distance.distance(hl, (sp['lat'], sp['lng'])).meters <= 70:
                    filtered.append(sp)
                    s.remove(sp)

**Comment by MonjoNL** [comment]
@averylarry I'm down to 134 again with your suggestion somehow.

If I add this code instead of removing sp form s I get 180 spawns. 6 less then pre #901 build.
But I think it is correct because the old code wasn't as precise as this code.
I will create a PR for it to get it into the develop branch.

        noDupes = []
        [noDupes.append(i) for i in filtered if not noDupes.count(i)]
        return noDupes

**Comment by averylarry** [comment]
#951 fixed.
