### ISSUE TITLE
Full stats page total number change

### ISSUE THREAD

**Issue by aldarund** [PokemonGoMap/PokemonGo-Map#940]
Just opened stats page, it no options changed. The total number keep jumping from 97k to 116-120k back and forward constantly. Can be like every 5 sec or every 30 sec dont have specific interval. 
Expected it to stay +- same , not going back and forward for 20k entries.

**Comment by Zerotask** [comment]
I have the same problem. I got 3 different numbers: ~ 700k, 800k, 900k

it's based on the data received by

`function loadRawData () {
  return $.ajax({
    url: 'raw_data',
    type: 'GET',
    data: {
      'pokemon': false,
      'pokestops': false,
      'gyms': false,
      'scanned': false,
      'seen': true,
      'duration': document.getElementById('duration').options[document.getElementById('duration').selectedIndex].value
    },
    dataType: 'json',
	cache: false,
    beforeSend: function () {
      if (rawDataIsLoading) {
        return false
      } else {
        rawDataIsLoading = true
      }
    },
    complete: function () {
      rawDataIsLoading = false
    }
  })
}`

**Comment by aldarund** [comment]
Its caused by 
https://github.com/PokemonGoMap/PokemonGo-Map/blob/18a4401d001497ae91b08228d65daa2d4aace941/pogom/models.py#L145
Pokemon.get_seen return duplicate results for the same pokemons, like for example Ratata. So double ratata in resulting json -> another 20k pokemons added

**Comment by aldarund** [comment]
Fixed by #988
