### ISSUE TITLE
Exception in search worker

### ISSUE THREAD

**Issue by jorgdebont** [PokemonGoMap/PokemonGo-Map#943]
I receive the following (really long) error when running: 
> python ./runserver.py -a ptc -u "xxxx" -p "xxxx" -l "xxxx" -st 6 -k "xxxx"

> 2016-08-22 21:56:03,818 [ search_worker_0][        search][   ERROR] Exception in search_worker: ConstraintsIntersection(ConstraintsIntersection(), ValueSizeConstraint(1, 64)) failed at: "ValueSizeConstraint(1, 64) failed at: "SubjectAltName().setComponents(GeneralName(componentType=NamedTypes(NamedType('otherName', AnotherName(componentType=NamedTypes(NamedType('type-id', ObjectIdentifier('<no value>')), NamedType('value', Any(tagSet=TagSet((), Tag(tagClass=128, tagFormat=32, tagId=0))))), tagSet=TagSet((), Tag(tagClass=128, tagFormat=32, tagId=0)))), NamedType('rfc822Name', IA5String(tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=1)))), NamedType('dNSName', IA5String(tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=2)))), NamedType('directoryName', Name(componentType=NamedTypes(NamedType('', RDNSequence())), tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=4)))), NamedType('uniformResourceIdentifier', IA5String(tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=6)))), NamedType('iPAddress', OctetString(tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=7)))), NamedType('registeredID', ObjectIdentifier('<no value>')))).setComponents(None, None, IA5String('support3.cdnetworks.net', tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=2)))), GeneralName(componentType=NamedTypes(NamedType('otherName', AnotherName(componentType=NamedTypes(NamedType('type-id', ObjectIdentifier('<no value>')), NamedType('value', Any(tagSet=TagSet((), Tag(tagClass=128, tagFormat=32, tagId=0))))), tagSet=TagSet((), Tag(tagClass=128, tagFormat=32, tagId=0)))), NamedType('rfc822Name', IA5String(tagSet=TagSet((), Tag(tagClass=128, tagFormat=0, tagId=1)))),

## Expected Behavior

This results in no scans being done. The application functioned yesterday but broke upon first use today.

## Your Environment

* Version used: 0448f930832be8123d658bf5e38f77fe86708c40
* Environment name and version (e.g. Python 2.7): Python 2.7.6
* Operating System and version (desktop or mobile): Linux machine 3.13.0-37-generic #64-Ubuntu SMP Mon Sep 22 21:28:38 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

>

**Comment by pyr0ball** [comment]
Please post in the Support Forums or on Discord Chat. This is not a bug. Looks like an issue with your database

**Comment by 3shirts** [comment]
Did you ever fix this? I have the same issue and I'm banging my head against a wall!

**Comment by jorgdebont** [comment]
@3shirts No have I never fixed it, I stopped trying. I only used  the machine on which I got this error during my vacation, after that I used my desktop which didnt face this problem.
