### ISSUE TITLE
syntax terror when launching

### ISSUE THREAD

**Issue by dotheknifefight** [PokemonGoMap/PokemonGo-Map#944]
## Expected Behavior
After installing all requirements and ensuring APIs are enabled, I expect the service to launch.

## Current Behavior
http://imgur.com/Qkf8DTO

## Context
I also tried using coords with the same luck. Is there a config file I can manually enter these values into?

## Your Environment
* Version used: 3.1.0
* Environment name and version (e.g. Python 2.7): up to date Python and pip
* Operating System and version (desktop or mobile): OSX 10.11.6

**Comment by pyr0ball** [comment]
Please post in the [Support Forum](http://pokemongo-map.me) or on Discord. This is not a bug, but a dependency or installation issue
