### ISSUE TITLE
List of banned accounts.

### ISSUE THREAD

**Issue by DrKinSlayeR** [PokemonGoMap/PokemonGo-Map#950]
Hi,

When you have a lot of workers. It's hard to see, which workers are banned or not. That's possible to add names of workers who are potentially banned in a file (ex: acc_bans) to see rapidly a list of banned accounts ?

Thanks

(Sorry for my English. I do my best to be understandable :D)

**Comment by BaIthamel** [comment]
This is not a support forum; please see [the discord #help channel](https://discord.gg/npVqkUn) for assistance.
(aka this can be done already!)
