### ISSUE TITLE
Error 10053 - Connection aborted

### ISSUE THREAD

**Issue by intopuddles** [PokemonGoMap/PokemonGo-Map#953]
I have 100 or so scanners going with around 5000 spawnpoints. Scanners will run fine for about 10min, and then I start seeing the following. I have also tried starting from scrap, using less workers, setting a database with MySQL, tried changing things like max db connections allowed, forwarded ports, DMZ'd, disabled firewall/AV, etc..

> Exception in thread Thread-7072:
> Traceback (most recent call last):
>   File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner
>     self.run()
>   File "C:\Python27\lib\threading.py", line 754, in run
>     self.__target(*self.__args, **self.__kwargs)
>   File "C:\Python27\lib\SocketServer.py", line 599, in process_request_thread
>     self.handle_error(request, client_address)
>   File "C:\Python27\lib\SocketServer.py", line 596, in process_request_thread
>     self.finish_request(request, client_address)
>   File "C:\Python27\lib\SocketServer.py", line 331, in finish_request
>     self.RequestHandlerClass(request, client_address, self)
>   File "C:\Python27\lib\SocketServer.py", line 654, in __init__
>     self.finish()
>   File "C:\Python27\lib\SocketServer.py", line 713, in finish
>     self.wfile.close()
>   File "C:\Python27\lib\socket.py", line 283, in close
>     self.flush()
>   File "C:\Python27\lib\socket.py", line 307, in flush
>     self._sock.sendall(view[write_offset:write_offset+buffer_size])
> **error: [Errno 10053] An established connection was aborted by the software in your host machine**

**Comment by intopuddles** [comment]
Disabled firewall in modem (I had only disabled the router one), and it appears to be working better now.

**Comment by pyr0ball** [comment]
This is not a bug, but a configuration issue. Please post this on the [Support Forum](http://pokemongo-map.me) or on Discord
