### ISSUE TITLE
Changed Default position 'lockmarker' get's ignored

### ISSUE THREAD

**Issue by darkelement1987** [PokemonGoMap/PokemonGo-Map#955]
I want mobile users of my map to change the position of the marker by default without moving the slider in the options menu, after changing the following files the slider stays activated no matter what.

After changing the default position of lockMarker in static/js/map.js and rebooting server, my map remembers every default sliders position i've changed except for the lockMarker.

Changed File and line: /static/js/map.js

> },
  'lockMarker': {
    default: false, // default to true if touch device
    type: StoreTypes.Boolean

Changed File and line: /static/dist/js

> lockMarker:{default:!1,type:StoreTypes.Boolean}`

Changed File and line: /static/dist/js/map.built.js

>   'lockMarker': {
    default: false, // default to true if touch device
    type: StoreTypes.Boolean

I'm testing @ Incognito modus @ Chrome for Android

**Comment by angrymoose** [comment]
This is not an issue with the program, and you failed to read when you created this issue.

>   ISSUES ARE NOT FOR SUPPORT!!!
> 
>   Join discord (channel: #help) for support at this link: https://discord.gg/PWp2bAm
>

**Comment by pyr0ball** [comment]
You can also post support issues on the [Forum](http://pokemongo-map.me)
