### ISSUE TITLE
PGO 0.35

### ISSUE THREAD

**Issue by PeshBG** [PokemonGoMap/PokemonGo-Map#956]
what is the plan for the new security measures?

**Comment by ingr3ss** [comment]
What are those new security measures? My scanner is still working fine.

**Comment by peshetoman** [comment]
uk6 was changed and capcha will be added when the server detects 2 many requests from the same account. http://www.i4u.com/2016/08/114581/pokemon-go-bots-and-pokemon-trackers-stop-working-new-pokemon-go-app-update

**Comment by MichalCerny** [comment]
Actually I'm using 120 workers and for past 2 hours I get 0/0/0 only from ~80 workers. They are not banned and worked ok this morning.

**Comment by ingr3ss** [comment]
Mine is still working fine, but I only use 1 worker though.

**Comment by DiscoTim** [comment]
hasn't rolled out yet, possibly looks grim.

**Comment by PeshBG** [comment]
http://pokemongo.nianticlabs.com/en/post/ver-update-082216/ there will be update for sure. I hope map survives.. without her tracking pokemon is impossible

**Comment by dayshiers** [comment]
if you limit how much scanning you are doing you should be fine, but if you plan on running beehive you will be seeing this error a lot

2016-08-22 19:50:04,050 [ search_worker_0][        models][ WARNING] Exceeded maximum connections.... Retrying
2016-08-22 19:50:04,050 [ search_worker_0][        models][ WARNING] Exceeded maximum connections.... Retrying
2016-08-22 19:50:04,050 [ search_worker_0][        models][ WARNING] Exceeded maximum connections.... Retrying
2016-08-22 19:50:04,050 [ search_worker_0][        models][ WARNING] Exceeded maximum connections.... Retrying
2016-08-22 19:50:04,050 [ search_worker_0][        models][ WARNING] Exceeded maximum connections.... Retrying
2016-08-22 19:50:04,050 [ search_worker_0][        models][ WARNING] Exceeded maximum connections.... Retrying
2016-08-22 19:50:04,050 [ search_worker_0][        models][ WARNING] Exceeded maximum connections.... Retrying
2016-08-22 19:50:04,050 [ search_worker_0][        models][ WARNING] Exceeded maximum connections.... Retrying

**Comment by PeshBG** [comment]
@dayshiers  how do you limit the scanning? st 1 ? or some other setting

**Comment by ingr3ss** [comment]
There you go, I got now 0/0/0, with only 1 worker :(

It was working fine minutes ago.

**Comment by Saprophator** [comment]
All my Accounts were banned over the last night. I was spawn scanning about 64 km² with 5000 Spawn Points.

**Comment by dayshiers** [comment]
increase your scan delay and only scan the minimum locations.

**Comment by Techgoduk** [comment]
I have 4 scanners running with 10 accounts each. 2 scanners have now failed the other 2 are currently working but expecting them to go down soon too.

**Comment by PeshBG** [comment]
were you able to get the new app from the store?

**Comment by hedqvist** [comment]
Have been running 3500 spawnpoints with 30 accounts, with a scan delay of 12 seconds, was working fine 6 hours ago, until about about 12.00 GMT+1 then account after account started to go down. Now 22 accounts of the 30 have been banned. Stopped scanning for now.

**Comment by thisismohitgupta** [comment]
I was running a scanner with 50 accounts and all have been banned

**Comment by jonathanwcrane** [comment]
Note that the banning is separate from the title of this issue.

**Comment by hemsleyk** [comment]
100 all done around the same time, unless the map parse failed is just the UK6 change being applied to those accounts (staggered update).

**Comment by BradPat** [comment]
I have 0 0 0 problem, is that also because of new update?

**Comment by slideup-benni** [comment]
Someone on reddit said he looses his accounts when they traveled 1000km. Maybe a new limitation?
I didn't loose much accounts until now. I'm running -st 6 -ss -sd 18 with up to 5 accounts.

https://www.reddit.com/r/pokemongodev/comments/4z3o8a/lost_10_accounts_today_after_going_all_weekend/d6swhv2

**Comment by hemsleyk** [comment]
Think the issue is captcha.

**Comment by khag7** [comment]
These accounts probably aren't banned. I can still log in using the real app with any of my scanning accounts and see and capture spawns just fine. Those accounts are working fine. On the scanner, though, I get the "search area download failed" repeatedly until 2 hour sleep "account is probably banned".

This suggests that they changed unk6 and we're no longer communicating "properly" with their api, so they return no data to us.

**Comment by slideup-benni** [comment]
@hemsley yes, but the question ja, when will it shown

**Comment by FlarumHostingCo** [comment]
Have the changes gone in effect yet?   I have accounts still running fine using a  30 scan delay

**Comment by sebastienvercammen** [comment]
This is all speculation. The FastPokeMap dev even specifically said he added the captcha himself, it's not the actual content of the modal window in 0.35.

Anything at this point is only speculation, so let it rest for now. We'll deal with whatever will come; an unk6 update being very possible.

**Comment by FrostTheFox** [comment]
> Can we close this? It's irrelevant, just random assumptions about something that hasn't launched yet, and the captcha was just manually added by someone in the 0.35 modal - it's not the actual in-game HTML content.
