### ISSUE TITLE
[Question] Is that legal to use pokemon icons found here ?.

### ISSUE THREAD

**Issue by v3ss0n** [PokemonGoMap/PokemonGo-Map#957]
Is that legal to use icons from PokemonGo-Map in an app , that going to distribute over google-play store?
Are those icons : https://github.com/PokemonGoMap/PokemonGo-Map/tree/develop/static/icons
extracted directly from pokemon-go app?

**Comment by angrymoose** [comment]
This is not an issue with the program and as such should be closed. Furthermore what is "legal" varies country to country and varies even regional depending on jurisdiction. To add to that what is "legal" and what is allowed under the google playstore are once again different. Simply put if you need legal advice consult an attorney or solicitor depending on your jurisdiction. If you want a rough answer no google will not allow you to use some one elses registered trademark's or copyrighted assets in your application if the trademark owner complains.  This has been demonstrated by multiple cease and desists noticed that have been issued by Niantic and google has pulled all apps that have received such notices.

**Comment by v3ss0n** [comment]
Thanks , closing  , so even fan-made icons , they can pull it down right?

**Comment by FlarumHostingCo** [comment]
Correct if it is life like..  Same goes for names too

**Comment by v3ss0n** [comment]
Wow , i was about to ask if those icons from old pokemon games or fan made . https://github.com/PokemonGoMap/PokemonGo-Map/tree/develop/static/pixel_icons

But i guess if i use them on playstore they can pull it down too? i am developing a pokemon community app where trainers can chat and share pokemon locations (totally user contributed) oppose to using niantic services.

**Comment by angrymoose** [comment]
@v3ss0n yes they can and most likely will issue a cease and desist order. It does not matter if they are fan made and licensed under the gpl, bsd, mit etc license schemes. The characters are copyrighted as are there names and any depictions of said characters are legal trademarks owned by GameFreak & Nintendo. Nintendo has well earned reputation for attacking anything that uses there trademarks & copyrights whether its youtube streams, user created content even if it greatly improves the enjoyment of there products and is free to the user. 

As you are located in a country outside of the USA you may not be sued, however google will pull the application as soon as Nintendo or its agents complain. If you are determined to proceed you will be forced to distribute the app outside of the playstore long term. You would be better off building a website and hosting it outside the USA. Overall I wouldn't proceed with an android application but that's entirely up to you.

DISCLAIMER : 

I am not a solicitor & the above does not constitute legal advice.

**Comment by v3ss0n** [comment]
Thanks a lot for details reply !
Ok i will try my luck , I will try to avoid any mention of their trademarks and use icons like skiplagged does.
