### ISSUE TITLE
Distance question

### ISSUE THREAD

**Issue by FlarumHostingCo** [PokemonGoMap/PokemonGo-Map#958]
I'm not really sure on how the real distance to steps works..  So how much distance do I cover using  setting step-limit: 4 ?

**Comment by Zentriert** [comment]
Each step is a 70 meter circle .. so you can base it off that.

**Comment by FlarumHostingCo** [comment]
So step limit starts a que of 34, so at step limit 4 I'm doing 70 meters x 34?

**Comment by sebastienvercammen** [comment]
```
1 step = 70m radius = x
Step limit = 34 steps = y

Total radius = x * y = 70m * 34 steps = 2380m
Surface of circle = radius^2 * π = 2380m^2 * π = 1.78×10^7 m²
```

Aside from the math, GitHub issues is really not the place for this kind of thing. This is not a discussion board; join Discord if you really want to.

**Comment by FrostTheFox** [comment]
non-issue
