### ISSUE TITLE
Keep getting "KeyError: 'map_cells'

### ISSUE THREAD

**Issue by lungbubble** [PokemonGoMap/PokemonGo-Map#96]
states [ search_worker_0][       search][      ERROR] Search Step 7 map parsing failed, retrying request in ** seconds"

Traceback(most recent call last):
file "c:\...pogom\search.py" line 236 in search_worker_thread parsed = parse_map(response_dict, step_location)
file "C:\...pogom\models.py", line 296, in parse_map cells = map_dict['responses']['GET_MAP_OBJECTS']['map_cells]
KeyError: 'map_cells'

This happens when running multiple threads (with different usernames), -sd is set to 13.

**Comment by Bart274** [comment]
I get the same error now:
```
2016-08-08 11:20:54,397 [ search_worker_0][        search][   ERROR] Search step 1 map parsing failed, retrying request in 30 seconds
Traceback (most recent call last):
  File "C:\PGM3\pogom\search.py", line 236, in search_worker_thread
    parsed = parse_map(response_dict, step_location)
  File "C:\PGM3\pogom\models.py", line 296, in parse_map
    cells = map_dict['responses']['GET_MAP_OBJECTS']['map_cells']
KeyError: 'map_cells'
```

I'm running the same version of this repo in two other instances as well and they work fine

**Comment by LuxusElg** [comment]
Same here, running multiple threads with different users.
This is the response_dict from the crashing requests:
`{'responses': {'GET_MAP_OBJECTS': {}}, 'status_code': 3, 'auth_ticket': {'expire_timestamp_ms': 1470650036016L, 'start': 'd5EUluPcC+dR0629qR/wd0dSur5SV4HtfZIyDpLZcMmiXYBg8XYKL8CimAoP+9ZGyVk/7d02UZO/JCrZFxkZr2RxOye6Jhvyzc/KBdO0EHg=', 'end': 'oGVkZLJjlQ7f7CzwbmlMGg=='}, 'request_id': 347145643987324303L}
`

**Comment by lungbubble** [comment]
I'm not sure if this is the script having a hard time with everything that's going on (like too many threads etc) or if its the servers refusing to provide data in some context.  Even if it were the latter, I'd think it'd just respond with the previous "no, there's no pokemon there".  

LuxusElg, ur info seems to suggest a problem with the token that's being generated.....which could be an issue with the API or, again, with the scripts having a hard time with all the threads.  idk, who knows, maybe i'm entirely wrong in my theories.

**Comment by Bart274** [comment]
@lungbubble I don't think it will be an error with the number of threads, I'm running 3 different instances with each their own account login and start location and they all use just one thread

**Comment by lungbubble** [comment]
Bart274 may I ask what your command line is?  I use a batch file with a number of lines.  This error seems to occur after about 60+.  And, to be fair, its not normal threads, but each one is its own console window.

**Comment by patgi** [comment]
I got this same error when I start the script...

**Comment by Bart274** [comment]
@lungbubble my login credentials and the start location are in the config.ini files.
I just have 3 copies of the PokemonGoMap repo and I start the servers in 3 different cmd windows with the command `runserver.py -st 5 -dc`

**Comment by LuxusElg** [comment]
after running this script for all my workers, i stopped getting the error:
https://github.com/scottstamp/pgoapi

**Comment by patgi** [comment]
Its working after I complete the tutorial (i used bluestark to do this)...

**Comment by Bart274** [comment]
@LuxusElg thanks for the tip, I tried running the script and it worked for me as well :)

**Comment by fytte** [comment]
where do you run the the scipts or is there something I forget when it does not work

**Comment by Bart274** [comment]
@fytte I just copied the script from the linked repo and adjusted the 'username' and 'password' in the python file and than it doesn't matter where you run it from :)

**Comment by fytte** [comment]
haha in line 25

**Comment by Bart274** [comment]
indeed :)

**Comment by Slivo-fr** [comment]
I cannot run the script you shared on my own :/

> ImportError: No module named pgoapi

**Comment by LuxusElg** [comment]
clone the entire pgoapi repo i linked, then run the script from its subfolder

**Comment by Slivo-fr** [comment]
Still the same importError :/
Thanks for your help

**Comment by engmsaleh** [comment]
Thanks for @LuxusElg  It works now for me

**Comment by Slivo-fr** [comment]
Got it, still for some map_cell error once accepting ToS for all workers :/

**Comment by lungbubble** [comment]
did not work for me, and yes, it does appear to be worker specific

**Comment by lungbubble** [comment]
someone mind reopening this, as the matter was never resolved.  I even made new accounts and did the "accept-tos.py" and it didn't change anything.

**Comment by Slivo-fr** [comment]
Did you try to spot the faulty workers and remove them ? It did the job on my side.
It was always the two same worker that crashed, finding and removing the related account made it

**Comment by lungbubble** [comment]
Yes, but then creating a new account still had the same issue.  It seems any account made before a particular date (a few weeks ago) is fine, but any account made since then has this problem even if you do the accept-tos.py (I even tried a new account and did the accept-tos.py before trying to use the account as a scanner; it changed nothing).  This occurs on a window by window basis,  My old accounts work fine, but I can't have a single account scanning 10 different hexagonal areas either.

**Comment by Slivo-fr** [comment]
My account are 2 day old, and works for most of them. Maybe you are scanning to fast with the same accounts, or something else. It's not on the map side anyway, it's account related, dev can't do anything about it

**Comment by lungbubble** [comment]
Is it though?  or is it that some newer accounts have different info being sent?  I made the new account less than an hour ago, same problem.

**Comment by Slivo-fr** [comment]
This issue has been raised with the API change, it's probably some changes / validation server side from niantic.

**Comment by lungbubble** [comment]
In that situation, wouldn't that draw attention from the devs to re-adjust something?

**Comment by Slivo-fr** [comment]
If it's about account validation / ToS acceptation or something like that, it's cannot really do something about it

**Comment by lungbubble** [comment]
But how sure are we that that is the case?  If most and or all newer accounts have this problem, this will be a bigger issue; all the more reason to begin discussion of it now I would think.  Even if it was a TOS acceptation then the accept-tos.py would be the solution which was something added by developers

**Comment by Slivo-fr** [comment]
You're right, it it's only tos related, it could be handled by the project. I don't know if it's exactly that or something else btw

**Comment by lungbubble** [comment]
Just used bluestacks, I can confirm, accepting TOS on a newer account in blustacks is ALL that is needed....doing nothing else (okay, maybe I clicked ONCE on the "professor text" screen stuff), but it started working.....that one account.  Too bad there's not an easy way to switch between accounts in the app, have to uninstall the whole app and re-install, 8(.....wish that tos acceptance.py thing worked.

**Comment by Slivo-fr** [comment]
On android you can logout using the setting pannel. The tos acceptance Py worked on my side.

**Comment by lungbubble** [comment]
maybe i typed it in wrong.  accept-tos.py MyUser MyPassword  is that the format?

**Comment by Slivo-fr** [comment]
Yup, you only have to edit line 25.
I wish I could provide an array :D

**Comment by lungbubble** [comment]
Edit line 25?  so its not just command line?

**Comment by Slivo-fr** [comment]
accept_tos('YOUR_USER', 'YOUR_PASSWORD') is the only thing you should change

**Comment by lungbubble** [comment]
......holy crap and a half, it worked.  SEE! this is why this shouldn't have been closed out so quickly, now I know why it didn't work for me and now others can know why it didn't work for them.

So, Solution is Thus: 
You must use accept-tos.py.  Typing in your username/password in command line like "accept-tos.py MyUser MyPassword" does NOT work.

You MUST edit the .py yourself such that the final line reads:
"accept_tos('MyUser','MyPassword')"

without the quotations, but the apostrophe's before and after the user name and before and after the password MUST be retained!

To do many, simply copy and paste the line with differnent username and passowrd like 

accept_tos('MyUser1','MyPassword')
accept_tos('MyUser2','MyPassword')
accept_tos('MyUser3','MyPassword')

Thanks for chatting with me Slivo-fr, you helped solve it!

**Comment by Slivo-fr** [comment]
I'm glad you found a solution. I would be neat to automate this inside the map tool.

**Comment by lungbubble** [comment]
Yes, upon the mentioned error for it to default to doing that to resolve it instead of spitting out said error.

**Comment by Jackdepancake** [comment]
I am encountering this issue, I have old google accounts and have run the script and still receiving this error on restart of scanning. Should I make new ones?

**Comment by shiznewski** [comment]
Even if i used accept-tos.py and it said successful, it didn't seem to be. I downloaded nox player and logged into the game accepted the tos, went throw the stupid intro and it works now. had to do it with each account

**Comment by lungbubble** [comment]
shizneewski I had that problem when I didn't edit the accept_tos.py file.  It doesn't work in command line, you MUST edit the file, that got it working for me.

Jackdepancake, you may want to read my instructions I wrote for the accept_tos.py again, just to make sure.  I was very specific to address any misunderstandings (as I had previously had such misunderstandings to the point at which it did not work).  To be fair, though, none of mine were google accounts, so idk if that makes the difference with that script.

**Comment by timodadashvand** [comment]
Thank you! @LuxusElg The script worked for me aswell. I just ran the script with python once and the map started working so thank you very much.

**Comment by curtisblack2004** [comment]
Running that script with my ptc credentials didn't work for me. :(
