### ISSUE TITLE
Error: `Traceback` (most recent call last):   File "runserver.py", line 228, in <module> ....

### ISSUE THREAD

**Issue by vervsdvgwegfeg** [PokemonGoMap/PokemonGo-Map#966]
I get this error when I run runserver..py
This is a fresh install of the map.

`Traceback` (most recent call last):
  File "runserver.py", line 228, in <module>
    main()
  File "runserver.py", line 108, in main
    str(position[0]), str(position[1]))
TypeError: 'NoneType' object has no attribute '__getitem__'

![fix](https://cloud.githubusercontent.com/assets/20638796/17911575/7bf9c0e4-698e-11e6-8bda-f4db3dde82fb.png)

**Comment by pyr0ball** [comment]
your configuration is incomplete. Either missing GMAPS api key, account information, or something else. Check your configs and run again. Also this is a BUG TRACKER not a support channel. Please post on the [Support Forums](http://pokemongo-map.me) or on Discord
