### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by mtsxd** [PokemonGoMap/PokemonGo-Map#967]
![cmd_2016-08-23_19-07-30](https://cloud.githubusercontent.com/assets/21208222/17913287/55311eea-696f-11e6-9241-ea6b25718420.png)

> pogomap@0.1.0 build C:\Users\Matheus\PokemonGo-Map
> grunt build

Running "clean:build" (clean) task
>> 0 paths cleaned.

Running "newer:babel" (newer) task

Running "newer:babel:dist" (newer) task
Loading "babel.js" tasks...ERROR
>> Error: Cannot find module 'babel-runtime/helpers/typeof'
Warning: Task "babel:dist" failed. Use --force to continue.

Aborted due to warnings.

npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Matheus\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v6.0.0
npm ERR! npm  v3.10.6
npm ERR! code ELIFECYCLE
npm ERR! pogomap@0.1.0 build: `grunt build`
npm ERR! Exit status 3
npm ERR!
npm ERR! Failed at the pogomap@0.1.0 build script 'grunt build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the pogomap package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     grunt build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs pogomap
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls pogomap
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Matheus\PokemonGo-Map\npm-debug.log

**Comment by maaim** [comment]
Do you have node.js installed?

**Comment by mtsxd** [comment]
yea, i have the 4.4.7 version one

**Comment by pyr0ball** [comment]
You need to run as "sudo".

this is not a bug, and issue tracker is not for support. Please post in the [Support Forum](http://pokemongo-map.me/viewforum.php?f=3) or on Discord
