### ISSUE TITLE
Trying to install pip requirements [error]

### ISSUE THREAD

**Issue by Xrecon420** [PokemonGoMap/PokemonGo-Map#968]
I have followed every single step and i have tried to reinstall and everything, and can only get the desktop mode to work for me at the moment.

Im getting these two errors when running "pip install -r requirements.txt". 

"
 Could not find a tag or branch 'aa09ad861f104f987928fe9f5107ccfe0e4473c3', assuming commit."

AND -

"
Command "python setup.py egg_info" failed with error code 1 in c:\users\sebast~1\appdata\local\temp\pip-build-nnh5ml\pyproj\"

Anyone know what's going on? 

Thanks.

**Comment by sebastienvercammen** [comment]
@Xrecon420 You're missing part of the error. Post a screenshot or an entire paste.

**Comment by Xrecon420** [comment]
C:\Users\Sebastian\Downloads\PokemonGo-Map-develop\PokemonGo-Map-develop>pip install -r requirements.txt
Collecting six==1.10.0 (from -r requirements.txt (line 1))
  Using cached six-1.10.0-py2.py3-none-any.whl
Collecting Flask==0.11.1 (from -r requirements.txt (line 2))
  Using cached Flask-0.11.1-py2.py3-none-any.whl
Collecting Jinja2==2.8 (from -r requirements.txt (line 3))
  Using cached Jinja2-2.8-py2.py3-none-any.whl
Collecting MarkupSafe==0.23 (from -r requirements.txt (line 4))
  Using cached MarkupSafe-0.23.tar.gz
Collecting Werkzeug==0.11.10 (from -r requirements.txt (line 5))
  Using cached Werkzeug-0.11.10-py2.py3-none-any.whl
Collecting configargparse==0.10.0 (from -r requirements.txt (line 6))
  Using cached ConfigArgParse-0.10.0.tar.gz
Collecting click==6.6 (from -r requirements.txt (line 7))
  Using cached click-6.6.tar.gz
Collecting itsdangerous==0.24 (from -r requirements.txt (line 8))
  Using cached itsdangerous-0.24.tar.gz
Collecting peewee==2.8.1 (from -r requirements.txt (line 9))
  Using cached peewee-2.8.1.tar.gz
Collecting wsgiref==0.1.2 (from -r requirements.txt (line 10))
  Using cached wsgiref-0.1.2.zip
Collecting geopy==1.11.0 (from -r requirements.txt (line 11))
  Using cached geopy-1.11.0-py2.py3-none-any.whl
Collecting s2sphere==0.2.4 (from -r requirements.txt (line 12))
  Using cached s2sphere-0.2.4-py2.py3-none-any.whl
Collecting PyMySQL==0.7.5 (from -r requirements.txt (line 13))
  Using cached PyMySQL-0.7.5-py2.py3-none-any.whl
Collecting flask-cors==2.1.2 (from -r requirements.txt (line 14))
  Using cached Flask-Cors-2.1.2.tar.gz
Collecting flask-compress==1.3.0 (from -r requirements.txt (line 15))
  Using cached Flask-Compress-1.3.0.tar.gz
Collecting LatLon==1.0.1 (from -r requirements.txt (line 16))
  Using cached LatLon-1.0.1-py2-none-any.whl
Collecting pgoapi from git+https://github.com/PokemonGoMap/pgoapi.git#egg=pgoapi (from -r requirements.txt (line 17))
  Cloning https://github.com/PokemonGoMap/pgoapi.git to c:\users\sebast~1\appdata\local\temp\pip-build-nnh5ml\pgoapi
Collecting xxhash (from -r requirements.txt (line 18))
  Using cached xxhash-0.6.1.tar.gz
Collecting sphinx==1.4.5 (from -r requirements.txt (line 19))
  Using cached Sphinx-1.4.5-py2.py3-none-any.whl
Collecting sphinx-autobuild==0.6.0 (from -r requirements.txt (line 20))
  Using cached sphinx_autobuild-0.6.0-py2-none-any.whl
Collecting recommonmark==0.4.0 (from -r requirements.txt (line 21))
  Using cached recommonmark-0.4.0-py2.py3-none-any.whl
Collecting sphinx_rtd_theme==0.1.9 (from -r requirements.txt (line 22))
  Using cached sphinx_rtd_theme-0.1.9-py2-none-any.whl
Collecting requests==2.10.0 (from -r requirements.txt (line 23))
  Using cached requests-2.10.0-py2.py3-none-any.whl
Collecting PySocks==1.5.6 (from -r requirements.txt (line 24))
  Using cached PySocks-1.5.6.tar.gz
Collecting flask_cachebust from git+https://github.com/ChrisTM/Flask-CacheBust.git@aa09ad861f104f987928fe9f5107ccfe0e4473c3#egg=flask_cachebust (from -r requirements.txt (line 25))
  Cloning https://github.com/ChrisTM/Flask-CacheBust.git (to aa09ad861f104f987928fe9f5107ccfe0e4473c3) to c:\users\sebast~1\appdata\local\temp\pip-build-nnh5ml\flask-cachebust
  Could not find a tag or branch 'aa09ad861f104f987928fe9f5107ccfe0e4473c3', assuming commit.
Collecting protobuf_to_dict==0.1.0 (from -r requirements.txt (line 26))
  Using cached protobuf-to-dict-0.1.0.tar.gz
Collecting future (from s2sphere==0.2.4->-r requirements.txt (line 12))
  Using cached future-0.15.2.tar.gz
Collecting pyproj (from LatLon==1.0.1->-r requirements.txt (line 16))
  Using cached pyproj-1.9.5.1.tar.gz
    Complete output from command python setup.py egg_info:
    using bundled proj4..
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\sebast~1\appdata\local\temp\pip-build-nnh5ml\pyproj\setup.py", line 72, in <module>
        objects = cc.compile(['nad2bin.c', 'src/pj_malloc.c'])
      File "c:\python27\lib\distutils\msvc9compiler.py", line 473, in compile
        self.initialize()
      File "c:\python27\lib\distutils\msvc9compiler.py", line 383, in initialize
        vc_env = query_vcvarsall(VERSION, plat_spec)
      File "c:\python27\lib\site-packages\setuptools\msvc.py", line 173, in msvc9_query_vcvarsall
        return EnvironmentInfo(arch, ver).return_env()
      File "c:\python27\lib\site-packages\setuptools\msvc.py", line 1118, in return_env
        [self.VCIncludes,
      File "c:\python27\lib\site-packages\setuptools\msvc.py", line 826, in VCIncludes
        return [os.path.join(self.si.VCInstallDir, 'Include'),
      File "c:\python27\lib\site-packages\setuptools\msvc.py", line 564, in VCInstallDir
        raise distutils.errors.DistutilsPlatformError(msg)
    distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 9.0 is required. Get it from http://aka.ms/vcpython27

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in c:\users\sebast~1\appdata\local\temp\pip-build-nnh5ml\pyproj\

C:\Users\Sebastian\Downloads\PokemonGo-Map-develop\PokemonGo-Map-develop>

**Comment by pyr0ball** [comment]
Please check the [support forum](http://pokemongo-map.me/viewtopic.php?f=6&t=20). This is not a bug, it's an issue with your system not havin all the proper dependency software

**Comment by Xrecon420** [comment]
Thanks didnt know about support forum, very helpful!
