### ISSUE TITLE
The clock is incorrect

### ISSUE THREAD

**Issue by lykkelille** [PokemonGoMap/PokemonGo-Map#970]
The clock on my map is about 10 minutes too fast, is there a way to change this? I am not very expirienced so i may need a detailed step by step explanation..

**Comment by sLoPPydrive** [comment]
Did you check the clock on your computer? You might need something like ntp to always get the correct time on your computer.

**Comment by BaIthamel** [comment]
This is not a support forum; please see [the discord #help channel](https://discord.gg/npVqkUn) for assistance.
