### ISSUE TITLE
No pokemons/pokestops/gyms

### ISSUE THREAD

**Issue by alexandre1984** [PokemonGoMap/PokemonGo-Map#971]
I am using jelastic but it does not show any pokemon/gym/pokestop. I tryed with latest, develop and master version. The ptc account is not banned.

**Comment by LordNeoZ** [comment]
Not scanned (0/0/0) or it does scan but is not displayed?
Any log from the console?

**Comment by Asafffff** [comment]
Your IP might be banned. try restarting your modem

**Comment by LordNeoZ** [comment]
@Asafffff I'm getting results from the scan but pokemons are not displayed on the map, only Gym and Pokestops

**Comment by Asafffff** [comment]
@LordNeoZ Yeah I know, it happens. try doing it cause it helped me a few times

**Comment by LordNeoZ** [comment]
@Asafffff I've got the 0/0/0 softban (or IP ban) and switching the VPN IP get it done, but now I am getting results (3/40/5) but I'm not getting any pokemon icon marker on the map. Pokestops (lured and normal) and gyms are updating just fine. I updated to the last commit and ran pip --upgrade and npm install/run build but nothing worked.

**Comment by alexandre1984** [comment]
Its not my IP. I am on my Mobile Phone. Web site is Gusmasgusmas.jc.neen.it

**Comment by alexandre1984** [comment]
@LordNeoZ 0/0/0

**Comment by LordNeoZ** [comment]
@alexandre1984 then you're softbanned. Try to switch IP or wait an hour.

**Comment by alexandre1984** [comment]
I used jelastic to deploy and the account is not banned. I logged in a few minutes.  Here is a short view of the log console 
016-08-24 14:37:51,236 [ db-cleaner][ models][ INFO] Regular database cleaning complete 2016-08-24 14:37:52,216 [ search-worker-0][ search][ INFO] Searching at 37.071585,-8.100926 2016-08-24 14:37:52,407 [ search-worker-0][ models][ INFO] Parsing found 0 pokemons, 0 pokestops, and 0 gyms 2016-08-24 14:38:02,418 [ search-worker-0][ search][ INFO] Searching at 37.070639,-8.100244 2016-08-24 14:38:02,571 [ search-worker-0][ models][ INFO] Parsing found 0 pokemons, 0 pokestops, and 0 gyms 2016-08-24 14:38:12,581 [ search-worker-0][ search][ INFO] Searching at 37.069693,-8.100926 2016-08-24 14:38:12,753 [ search-worker-0][ models][ INFO] Parsing found 0 pokemons, 0 pokestops, and 0 gyms 2016-08-24 14:38:22,764 [ search-worker-0][ search][ INFO] Searching at 37.068747,-8.101607 2016-08-24 14:38:22,915 [ search-worker-0][ models][ INFO] Parsing found 0 pokemons, 0 pokestops, and 0 gyms 2016-08-24 14:38:32,920 [ search-worker-0][ search][ INFO] Searching at 37.068747,-8.102971 2016-08-24 14:38:33,146 [ search-worker-0][ models][ INFO] Parsing found 0 pokemons, 0 pokestops, and 0 gyms 2016-08-24 14:38:43,156 [ search-worker-0][ search][ INFO] Searching at 37.068747,-8.104334 2016-08-24 14:38:43,332 [ search-worker-0][ models][ INFO] Parsing found 0 pokemons, 0 pokestops, and 0 gyms 2016-08-24 14:38:51,296 [ db-cleaner][ models][ INFO] Regular database cleaning complete 2016-08-24 14:38:53,343 [ search-worker-0][ search][ INFO] Searching at 37.069693,-8.105016 2016-08-24 14:38:53,546 [ search-worker-0][ models][ INFO] Parsing found 0 pokemons, 0 pokestops, and 0 gyms 2016-08-24 14:39:03,556 [ search-worker-0][ search][ INFO] Searching at 37.070639,-8.105698 2016-08-24 14:39:03,728 [ search-worker-0][ models][ INFO] Parsing found 0 pokemons, 0 pokestops, and 0 gyms 2016-08-24 14:39:13,738 [ search-worker-0][ search][ INFO] Searching at 37.071585,-8.105016 2016-08-24 14:39:13,985 [ search-worker-0][ models][ INFO] Parsing found 0 pokemons, 0 pokestops, and 0 gyms 2016-08-24 14:39:23,995 [ search-worker-0][ search][ INFO] Searching at 37.072531,-8.104334 2016-08-24 14:39:24,166 [ search-worker-0][ models][ INFO] Parsing found 0 pokemons, 0 pokestops, and 0 gyms

**Comment by LordNeoZ** [comment]
The 0/0/0 is typical of the softban, you're able to login but will not show any pokemon, pokestop or anything. Try to use a VPN

**Comment by alexandre1984** [comment]
Soft Ban from the jelastic, correct?

**Comment by LordNeoZ** [comment]
There is a lot of providers that are already softbaned. You were softbaned from Niantic servers, it's not an account ban, it's not permanent. If you switch IP you will be able to scan just fine, so do yourself a favor and get a VPN/proxy running.

**Comment by yusuf2703** [comment]
alexandre i am using jelasting and since 2 days nothing work anymore . I created so much google apis or ptc acc with real email adresses and played the acc a little bit. But jelastic dont want to show me the google map on the website...
Am i doing something wrong , should i reconnect my router ? And to create a new jelastic acc is difficult because the mobile number i used 3 private numbers and online all are used.

**Comment by alexandre1984** [comment]
I think jelastic is banned from niantic, so we wont be able to use it :( bad news, as scalingo is also banned. Someone should do something to solve this, maybe another provider

**Comment by thisismohitgupta** [comment]
You cant rely on the providers IP since IP bans are really too often. Just buy a VPN service and use it dont rely on free ones too

**Comment by aldarund** [comment]
Wow. another help  in the issues. I wonder why people cant read issue template where its repeated several times in CAPS thats issues are not for support.

**Comment by creatingwake** [comment]
I have exact same issue, began a few hours ago.  Running on a private dokku server, not trivial to change my ip.  Will wait few hours and retry.

**Comment by BaIthamel** [comment]
This is not a support forum; please see [the discord #help channel](https://discord.gg/npVqkUn) for assistance.
