### ISSUE TITLE
Scan successfull but Map doesn't show Pokemons

### ISSUE THREAD

**Issue by LordNeoZ** [PokemonGoMap/PokemonGo-Map#972]
## Expected Behavior
If scan is successfull, the map should show the icon marker of the Pokemon

## Current Behavior
Getting 3/45/5 but without any marker on the map for Pokemons

## Possible Solution
Not a clue

## Steps to Reproduce (for bugs)
1. Clone repo and Install
2. Scan an area known to get pokemons
3. Check the scan does throw results
4. Check the map and there should be markers for pokestops and gyms but not for pokemon

## Context
Switching the IP with VPN gets same results (3/45/5), but the map isn't showing the pokemon markers.
Tried the last commit (git pull, then pip install -r requirements.txt --upgrade, then npm install, npm run build) without any change.

## Your Environment
Windows 7 Pro
Python 2.7
Same setup worked fine till 7 hours ago, I went to sleep, turned on the machine and nothing.

**Comment by r3pek** [comment]
Check your clock, it may be of.

Also, this isn't really an issue. Go to discord and ask for some help there

**Comment by LordNeoZ** [comment]
@r3pek Thanks, that was it. I was on discord...
