### ISSUE TITLE
It's Pokémon, not pokemons

### ISSUE THREAD

**Issue by vpzomtrrfrt** [PokemonGoMap/PokemonGo-Map#973]
## Expected Behavior
The proper plural "Pokémon" should be used in UI and console output

## Current Behavior
It says "pokemons"

## Context
The map works great, this is the most annoying issue I've found.

## Your Environment
Python 2.7.12 on Arch Linux

**Comment by justsomedudeonthenet** [comment]
Using é could potentially cause all kinds of UTF-8 internationalization issues. At least it's better than calling them pokemen.

**Comment by vpzomtrrfrt** [comment]
Mostly I'm just asking to remove the 's'

**Comment by justsomedudeonthenet** [comment]
So modify it and put in a pull request.  Sounds like a good and easy fix to me.

**Comment by BaIthamel** [comment]
Yeah, I agree pokemons is a bit annoying but it's not really an *issue*
