### ISSUE TITLE
Scanned locations circles broken timer

### ISSUE THREAD

**Issue by Foxbond** [PokemonGoMap/PokemonGo-Map#977]
As title says, I just pull latest repo on server and I have this issue.

## Expected Behavior
Circles go green->yellow->red->disappear
![image](https://cloud.githubusercontent.com/assets/752127/17948027/628b4616-6a4f-11e6-9f2a-06878e4cddad.png)

## Current Behavior
Circles go yellow->red->disappear
![image](https://cloud.githubusercontent.com/assets/752127/17947963/2ffae9f4-6a4f-11e6-94f9-f2bfdf50db36.png)

## Possible Solution
I don't know project well enough, but its probably front-end bug only

## Steps to Reproduce (for bugs)
1.
2.
3.
4.

## Your Environment

* Version used: 083b05a
* Environment name and version (e.g. Python 2.7): python 2.7.9, pip 8.1.2, node v6.4.0, mySQL unknown (probably latest stable)
* Operating System and version (desktop or mobile): vps with ubuntu (sorry, unknown version)

step 4, scan delay 12, ~8 workers every with one acc + server

**Comment by averylarry** [comment]
Did you check if you're still scanning successfully?  Seems more like banned accounts than anything else.  Latest pull for me works as expected.

**Comment by BaIthamel** [comment]
This is not a support forum; please see [the discord #help channel](https://discord.gg/npVqkUn) for assistance.

**Comment by Foxbond** [comment]
@BaIthamel It's not about support -_-

@averylarry everything is working fine. Just time of disappear is starting like in middle of correct time.
