### ISSUE TITLE
pip install -r requirements.txt error (was working 10mins ago)

### ISSUE THREAD

**Issue by LIJE** [PokemonGoMap/PokemonGo-Map#98]
![Image](http://img4.hostingpics.net/pics/496488crash.jpg)

**Comment by patgi** [comment]
Try :
pip uninstall -r requirements.txt
And try to install again

**Comment by freakjam** [comment]
pip uninstall -r requirements.txt --upgrade might help too.

**Comment by LIJE** [comment]
Same error

![Image](http://img4.hostingpics.net/pics/671813err2.jpg)

**Comment by LIJE** [comment]
Same with "pip uninstall -r requirements.txt --upgrade"

**Comment by freakjam** [comment]
Try upgrading pip first.
easy_install pip

**Comment by wschoot** [comment]
I think there's no **--upgrade** to **uninstall**, but only to **install**

```
$ pip uninstall ---upgrade -r requirements.txt

Usage:
  pip uninstall [options] <package> ...
  pip uninstall [options] -r <requirements file> ...

no such option: ---upgrade

```

**Comment by LIJE** [comment]
easy_install pip fixed the issue.
Than uninstall then install again.

**Comment by danny6167** [comment]
This has been how I have been fixing it on my scan nodes.
```
rm -rf /usr/local/lib/python2.7/dist-packages/requests
pip install requests --upgrade --force
```
