### ISSUE TITLE
Debug messages visibility, creating log while on status page

### ISSUE THREAD

**Issue by zimpixa** [PokemonGoMap/PokemonGo-Map#980]
After "Add optional logging to file (#959)" commit, while using '-v' debug messages are visible in console, which I think should be hidden until '-vv' is used. 

Also log isnt written if console is on status page, which I assume was its main goal.

**Comment by ottowayne** [comment]
Debug messages are supposed to be shown with -v. -vv adds debug messages from used modules.

I can confirm the second part though. After a few lines the log stops.

**Comment by jtp10181** [comment]
Yes I was also expecting it to log everything even while in the status screen. Would be nice to have an option to just log the normal output without the debug messages, even while in the status screen.

**Comment by sebastienvercammen** [comment]
Fixed with #1640.
