### ISSUE TITLE
scan multiple areas

### ISSUE THREAD

**Issue by scopus-ru** [PokemonGoMap/PokemonGo-Map#983]
scan multiple areas
Help implement on Linux
https://pgm.readthedocs.io/en/develop/extras/workers.html
How to implement immediately
pavel12.10@bk.ru

**Comment by Christian-X** [comment]
You'll start multiple instances of runserver.py, each with a different location & different worker pool.

This is not an issue.

**Comment by BaIthamel** [comment]
This is not a support forum; please see [the discord #help channel](https://discord.gg/npVqkUn) for assistance.
