### ISSUE TITLE
Exception while downloading map when using new accounts

### ISSUE THREAD

**Issue by Freespirit2907** [PokemonGoMap/PokemonGo-Map#984]
## Expected Behavior
The program should start scanning normally without any issues.

## Current Behavior
The program succeeds to  the login procedure but when you start the scanning I get following Warning and Error:
2016-08-25 15:22:15,792 [ search-worker-0][        search][ WARNING] Exception while downloading map: 'NoneType' object is not iterable

2016-08-25 15:22:15,793 [ search-worker-0][        search][   ERROR] Invalid response at 51.507351,-0.127758, abandoning location.

the account used is brand new as of today and I've done the TOA.

## Steps to Reproduce (for bugs)
1. Create a knew account on the PTC website
2. try to use it for your scanning

## Context
I wanted the try the new spawnlocation scan feature using brand new accounts.
The accounts where tested in game and working.

## Your Environment
Windows 10
Python 2.7.12

I asked this question on the #help at DISCORD but no help there...

**Comment by jordyroosen** [comment]
i'v got the same issue

**Comment by AAnkudovich** [comment]
i was getting it this morning. log into the game and catch a starter . i think they are blocking requests from accounts with no game data

**Comment by m3g4mInD** [comment]
Guys just login in app  pass the lv 2 then logout w8 5 mnts because the DATA need to send niantic servers like 3 mnts and voila  you are free to use without any errors,for me work 100%.

**Comment by jordyroosen** [comment]
> 
m3g4mInD commented 2 hours ago
Guys just login in app pass the lv 2 then logout w8 5 mnts because the DATA need to send niantic servers like 3 mnts and voila you are free to use without any errors,for me work 100%.<

any scripts for this ?

**Comment by FrostTheFox** [comment]
Please try reading the closed issues before you post a new one.

http://thunderfox.nl/sharex/TXOJa4KdHe.png

#209 all the way at the bottom. 

`pip install -r requirements.txt --upgrade`  `npm install` and `npm build && npm run`
