### ISSUE TITLE
Get Directions Not Working

### ISSUE THREAD

**Issue by KyleBoyer** [PokemonGoMap/PokemonGo-Map#992]
The get directions link, must not be populated correctly with the GPS coordinate of that given Pokemon - I clicked get directions on a Pokemon that was right outside my drive way, and it was trying to take me 15 min away(not even close to my location). I tried to do the same with a different location Pokemon, and it mapped out to the same location as the first time! I believe these links may work for only one Pokemon on the map, not the one selected.

**Comment by jtp10181** [comment]
I tested on 3 different pokemon on my map, and it is working fine on my end.

I am running: https://github.com/PokemonGoMap/PokemonGo-Map/commit/c49cca443ff87d0b0e440c4d30d73f1d7df2d8b3

Using Google CHROME browser.

**Comment by ultrafunkamsterdam** [comment]
@KyleBoyer, you need to set your location by pushing the location button in the bottom right of your map, before starting the directions link.

**Comment by Slivo-fr** [comment]
I think we shouldn't start direction, and simply open pokemon coordinates, user will be able to start direction himself.
I don't think giving the coordinates will do the trick, as it might only suggest to review the path, without starting direction
