### ISSUE TITLE
Suggestion: Hover tip on spawn points shows spawn time

### ISSUE THREAD

**Issue by DrAtari** [PokemonGoMap/PokemonGo-Map#993]
Sorry if this is not meant for suggestions. Delete if necessary.

I'd find it very useful if the spawn points on the map had hover tips which show the most recent spawn time. So I could estimate the next time a pokemon spawns (usually one hour later) and create a walking route through the city which puts me near the spawn points at the right time.

**Comment by BaIthamel** [comment]
feathub is for suggestions
